### ISSUE TITLE
run-bench query syntax fails when run against db2

### ISSUE THREAD

**Issue by switnicki** [ibmdb/node-ibm_db#100]
the sql statements in the run-bench tests return an error, most tests are affected.

**Comment by bimalkjha** [comment]
yes, we are not running run-bench.js as it has many issues and it need to be make workable as run-test.js. I'll let @rhtpandeyIN to clean run-bench and make it workable. 

If you have any specific repro and seems a code defect, please share the repro. We'll look into that. Thanks.

**Comment by switnicki** [comment]
@bimaljha I should be able to make the changes to get it working. Do I just need to submit a pull request or is there more process in place for contributors?

**Comment by bimalkjha** [comment]
if you are non- IBMer, then there is more process involved and I may not be able to merge the pull request. Better you push the changes to your branch and let me know. I'll push those changes to master. Thanks.
