### ISSUE TITLE
New Feature/Enhancement Request : add SQL_COLUMN_LENGTH and SQL_DESC_BASE_TABLE_NAME into getColumnMetadataSync()

### ISSUE THREAD

**Issue by FredoMartini** [ibmdb/node-ibm_db#1003]
**Is your feature request related to a problem? Please describe.**

I need to retrieve some additional information about the columns using **getColumnMetadataSync()**.
More precisely I need **SQL_COLUMN_LENGTH** and **SQL_DESC_BASE_TABLE_NAME**.

**Describe the solution you'd like**

Add theses fields to the return of **getColumnMetadataSync()**.

**Describe alternatives you've considered**

A better alternative would be to be able to select the value to get from **getColumnMetadataSync()**.
Something like this :
```js
  const metadata = result.getColumnMetadataSync( [ "SQL_DESC_NAME", "SQL_DESC_TYPE_NAME", "SQL_DESC_LENGTH"] );
```

**Additional context**

**Comment by bimalkjha** [comment]
Open enhancement request in our internal Jira repo: https://jira.rocketsoftware.com/browse/DBC-16190
It will be planned and addressed accordingly. Thanks
