### ISSUE TITLE
Please generate windows bindings for Node v22

### ISSUE THREAD

**Issue by thepigs** [ibmdb/node-ibm_db#1005]
Could you please generate windows odbc bindings for v22 of node? 
I wish to use node 22.4.0+ to enable use of --experimental-require-module flag to mix commonjs and esm modules.
Currently build.zip contains bindings up to node v20.
I don't have access to required build tools: Minimum VsStudio 2017 and no internet access on site!
My customer is using Db2 Z/os.
Thanks in advance!

**Comment by dthunell** [comment]
Out of curiosity, do you have any estimation when the next release might ship?

**Comment by bimalkjha** [comment]
@dthunell It is out! Please check. Thanks.

**Comment by dthunell** [comment]
Great! Thank you so much for your work!
