### ISSUE TITLE
Error: Module Version mismatch. Expected 47, got 46. with < Node.js v4 version

### ISSUE THREAD

**Issue by madhu-bhushan** [ibmdb/node-ibm_db#102]
I am getting below exception.

Error: Module version mismatch. Expected 47, got 46.
    at Error (native)
    at Object.Module._extensions..node (module.js:424:18)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at bindings (E:\bm-codebase\mb-samplenode\node_modules\ibm_db\node_modules\bindings\bindings.js:74:15)
    at Object.<anonymous> (E:\bm-codebase\mb-samplenode\node_modules\ibm_db\lib\odbc.js:27:31)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)

**Comment by afinity** [comment]
Same issue w/ Nodejs v5 & npm v3. Attempts to rebuild the package gives an error with `node installer/driverInstall.js`.

**Comment by bimalkjha** [comment]
what is your platform?

**Comment by madhu-bhushan** [comment]
@bimalkjha::   Its windows 7 home premium. 64bit.

**Comment by afinity** [comment]
My personal issue arose from installing v5.7 of node (win7pro) without noticing. Downgrading to v4.4 has ibm_db v0.0.19 working well. Apologies for the unnecessary comment, thanks for your hard work getting v4 support up and running.

**Comment by bimalkjha** [comment]
Thanks @afinity 
@madhu-bhushan node.js v5.x is not supported on Windows. Please use node.js v4.x. Thanks.

**Comment by sribdvt** [comment]
@bimalkjha,
initially, I used Node version 5.6.0 and npm 3.6.0. (OS is windows 7-64 bit). with that I was getting the error " modules\bindings\bindings.js:79 ". After seeing this comment, I used now - Node version 4.4.1 and npm 2.14.20.
with this now I am getting error. 

error occurred [IBM][CLI Driver] SQL30081N  A communication error has been detec
ted. Communication protocol being used: "TCP/IP".  Communication API being used:
 "SOCKETS".  Location where the error was detected: "169.45.177.10".  Communicat
ion function detecting the error: "selectForConnectTimeout".  Protocol specific
error code(s): "0", "*", "*".  SQLSTATE=08001

I am trying to connect from local to DB2 which is in remote. 
can you please suggest the possible resolution on this..

thanks

**Comment by bimalkjha** [comment]
@sribdvt This issue has nothing to do with ibm_db. ibm_db seems working. This error is comming from DB2 server. Either server is not configured to accept remote connection or you are using wrong port. If you have access to server, run below commands on server and then try connection from ibm_db.
```
db2set DB2COMM=TCPIP
db2 update dbm cfg using svcename x$USER
db2 terminate
db2stop force
db2start
db2cli validate -database "dbname:hostname:port" -user username -password passwd -connect
```

thanks.

**Comment by sribdvt** [comment]
Thanks @bimalkjha , 
there was firewall issue, because of which I was getting this error. 
Now it is working. 

Thanks

**Comment by rhtpandeyIN** [comment]
Update:
@madhu-bhushan , @afinity , @sribdvt  ,  
now node.js/ibm_db is also supporting V5.x on Windows. you can directly install it from git by using following command: 
npm install git+https://git@github.com/ibmdb/node-ibm_db.git

Closing the issue now.
Thanks.
