### ISSUE TITLE
Unable to connect to informix db via ssl.

### ISSUE THREAD

**Issue by mafischer** [ibmdb/node-ibm_db#103]
[IBM][CLI Driver] SQL1109N  The command was not processed because the database manager failed to load the following DLL: "gsk8ssl_64.dll".  SQLSTATE=42724

using node v4.4.0 on windows 7 x64

**Comment by bimalkjha** [comment]
Seems your system has older GSKit installation. Edit/Add System Environment variable LIB and set/add .../ibm_db/installer/clidriver/bin/icc64 to LIB. Thanks.

**Comment by mafischer** [comment]
It's working now, thanks for your help.

**Comment by emiratesstadium098** [comment]
Adding this directory to my system environment paths didn't immediately solve the error, but eventually I added all the 'icc64' subdirectories to my user environment, which made the error go away.
