### ISSUE TITLE
Error while installing ibm_db in redhat linux rhel6, Node version 4.2.6,  ibm_db@0.0.19

### ISSUE THREAD

**Issue by sanraj22** [ibmdb/node-ibm_db#104]
npm install ibm_db, is failing in redhat rhel6 with ibm_db@0.0.19 and Node version 4.2.6 also with below error.

Can you please suggest.
Error:
npm info ibm_db@0.0.19 Failed to exec install script
npm verb unlock done using /root/.npm/_locks/ibm-db-ba18bfce146f2908.lock for /root/NodeDataProvider/node_modules/ibm_db
npm verb stack Error: ibm_db@0.0.19 install: node installer/driverInstall.js
npm verb stack Exit status 1
npm verb stack at EventEmitter. (/root/softwares/node-v4.2.6-linux-x64/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
npm verb stack at emitTwo (events.js:87:13)
npm verb stack at EventEmitter.emit (events.js:172:7)
npm verb stack at ChildProcess. (/root/softwares/node-v4.2.6-linux-x64/lib/node_modules/npm/lib/utils/spawn.js:24:14)
npm verb stack at emitTwo (events.js:87:13)
npm verb stack at ChildProcess.emit (events.js:172:7)
npm verb stack at maybeClose (internal/child_process.js:821:16)
npm verb stack at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
npm verb pkgid ibm_db@0.0.19
npm verb cwd /root/NodeDataProvider
npm ERR! Linux 2.6.32-573.18.1.el6.x86_64
npm ERR! argv "/root/softwares/node-v4.2.6-linux-x64/bin/node" "/root/softwares/node-v4.2.6-linux-x64/bin/npm" "install" "ibm_db" "--verbose"
npm ERR! node v4.2.6
npm ERR! npm v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! ibm_db@0.0.19 install: node installer/driverInstall.js
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ibm_db@0.0.19 install script 'node installer/driverInstall.js'.
npm ERR! This is most likely a problem with the ibm_db package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node installer/driverInstall.js
npm ERR! You can get their info via:
npm ERR! npm owner ls ibm_db
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]
npm verb unbuild node_modules/ibm_db
npm info preuninstall ibm_db@0.0.19
npm info uninstall ibm_db@0.0.19
npm verb unbuild rmStuff ibm_db@0.0.19 from /root/NodeDataProvider/node_modules
npm info postuninstall ibm_db@0.0.19
npm verb gentlyRm don't care about contents; nuking /root/NodeDataProvider/node_modules/ibm_db

npm ERR! Please include the following file with any support request:
npm ERR! /root/NodeDataProvider/npm-debug.log

**Comment by bimalkjha** [comment]
@sanraj22 You have not pasted the full error from start. i.e. the error reported by make. If you rerun the command, you can see errors like below:

make: Entering directory `/home/hotellnx113/bimaljha/opensource/nodework/installs/node_modules/ibm_db/build'
  CXX(target) Release/obj.target/odbc_bindings/src/odbc.o
make: Leaving directory `/home/hotellnx113/bimaljha/opensource/nodework/installs/node_modules/ibm_db/build'

```
{ [Error: Command failed: /bin/sh -c node-gyp configure build --IBM_DB_HOME=$IBM_DB_HOME --IS_DOWNLOADED=false
In file included from ../src/odbc.h:23,
                 from ../src/odbc.cpp:25:
../node_modules/nan/nan.h:41:3: error: #error **This version of node/NAN/v8 requires a C++11 compiler**
In file included from ../src/odbc.cpp:19:
```

So, the current compiler installed in your system does not support node.js v4.x source code and it fails to compile. It is not ibm_db issue. Please check your gcc version and upgrade it to latest.

I would suggest to install gcc5, then ibm_db would work. 
Download link for gcc5 is here: http://software.opensuse.org/package/gcc5

Thanks and Regards,
Bimal Jha
