### ISSUE TITLE
`npm i` fails to install this module from behind a corporate proxy.

### ISSUE THREAD

**Issue by josiah14** [ibmdb/node-ibm_db#111]
I'm building from inside of an RHEL6.5 64bit Docker container to build the packages against the deployment environment.

```bash
[root@83b5ef702df8 NodeProject]# npm i
 
> ibm_db@0.0.6 install /NodeProject/node_modules/ibm_db
> node installer/driverInstall.js

Downloading DB2 ODBC CLI Driver from https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz...

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: connect ECONNREFUSED
    at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete] (net.js:895:19)
npm ERR! ibm_db@0.0.6 install: `node installer/driverInstall.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the ibm_db@0.0.6 install script.
npm ERR! This is most likely a problem with the ibm_db package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node installer/driverInstall.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls ibm_db
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 4.0.9-boot2docker
npm ERR! command "/node-v0.10.29-linux-x64/bin/node" "/node-v0.10.29-linux-x64/bin/npm" "i"
npm ERR! cwd /NodeProject
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /NodeProject/npm-debug.log
npm ERR! not ok code 0
```

Every other dependency in my `packages.json` installs if I comment out the `ibm_db` dependency and re-run `npm i` after deleting the node_modules directory.

**Comment by bimalkjha** [comment]
Open /NodeProject/node_modules/ibm_db/installer/driverInstall.js, search for "public.dhe" and change "https" to "http". "npm i" should be able to install ibm_db.

I would suggest to move on newer node.js v4.4.2 and use latest version of ibm_db@0.0.19. Thanks.

**Comment by josiah14** [comment]
NPM clears the repository on a failed install.  Without the source tagged, here, I don't have access to `/NodeProject/node_modules/ibm_db/installer/driverInstall.js`

I shouldn't have to hack the source to get the module to install.  This should be patched.

**Comment by bimalkjha** [comment]
Is there any specific reason you want to stick with 0,0,6 version. Can you try `npm install ibm_db@0.0.15` and share result? Thanks.
