### ISSUE TITLE
non-standard callbacks to `query` method (i.e. `moreResultSets` argument)

### ISSUE THREAD

**Issue by zenflow** [ibmdb/node-ibm_db#113]
The node.js standard "error-first" callback convention does not allow for a callback to be called more than once. It expects the callback to be called once, with the entire result.

Having methods that break that convention prevents us from (easily, without wrapping them) composing them, "promisifying them" using say [bluebird](https://www.npmjs.com/package/bluebird), or using them with flow-control libraries like [async](https://www.npmjs.com/package/async).

My suggestion would be to follow the convention and call the callback once with the entire result set, and implement a separate method that returns a readable stream in ["object mode"](https://nodejs.org/docs/v0.11.5/api/stream.html#stream_object_mode) (feature of node.js since v0.11.5). Let's call it `queryStream`?

Is this a feature you're interested in supporting, if I submit a PR?

**Comment by bimalkjha** [comment]
@zenflow support for queryStream has been added to the latest push on git. Also, support for promise is available in ibm_db@1.0.1 using 'q'.

I don't see moreResultSets is the accepted argument for query() or querySync() APIs. Could you please share the documented API definition where you see use of moreResultSets?

**Comment by zenflow** [comment]
@bimalkjha That's awesome news!

All references to the `moreResultSets` argument are in the following sections of the main README.md

- https://github.com/ibmdb/node-ibm_db/blob/master/README.md#-2-opensyncconnectionstring-options
- https://github.com/ibmdb/node-ibm_db/blob/master/README.md#-3-querysqlquery--bindingparameters-callback

Here's a link to the exact line where the function signature for the `query` method is documented: https://github.com/ibmdb/node-ibm_db/blame/master/README.md#L232

**Comment by bimalkjha** [comment]
@zenflow I saw the documents. Docs are correct. `moreResultSets` is used when multiple SQL statements separated by semicolon is passed to `query()`. Here, callback is called with full result set only but only for one SQL. For another SQL, callback will be called again with the resultset of second SQL.
Execution of multiple statements at once is not supported by all drivers. It works only if driver has support for ODBC API [SQLMoreResults()](http://www.ibm.com/support/knowledgecenter/en/SSEPGG_11.1.0/com.ibm.db2.luw.apdv.cli.doc/doc/r0000628.html).
If single SQL is passed to query(), there will be single call to the callback function with full result. 
Thanks.

**Comment by zenflow** [comment]
@bimalkjha I assumed that the docs are correct. That's why I opened the issue. 

Like I said..

>The node.js standard "error-first" callback convention does not allow for a callback to be called more than once. It expects the callback to be called once, with the entire result.

> Having methods that break that convention prevents us from (easily, without wrapping them) composing them, "promisifying them" using say bluebird, or using them with flow-control libraries like async.

What I misinterpreted is *when* there will be more result sets. I wrongly assumed it would be used if there were more results than could be buffered into memory. There was at the time no indication of when there would be more result sets... But I see that when you closed this issue you updated the docs to imply that with the example, so that I guess is resolved. (It could be made explicit though)

Still, the `query` method uses it's callbacks in a non-standard way.

Please reopen this issue, since I can't.

*P.S. Shouldn't the issue author be given the chance to verify resolution and close the issue themselves?*

**Comment by bimalkjha** [comment]
@zenflow We have updated the docs and ibm_db code too to return all result set at once with single call of callback function. Please install the latest code from git using command `npm install git+https://git@github.com/ibmdb/node-ibm_db.git` to verify it. I am reopening the issue for you. Feel free to close it post verification. Thanks.

**Comment by mattbrunetti** [comment]
@bimalkjha 

Excellent! This is just what I meant. Much better!

Apparently I don't have permission to close my issue, but I do consider this issue resolved.

Thanks for addressing this. :)

**Comment by zenflow** [comment]
@bimalkjha

Excellent! This is just what I meant. Much better!

Apparently I don't have permission to close my issue, but I do consider this issue resolved.

Thanks for addressing this. :)
