### ISSUE TITLE
New version release (Question)

### ISSUE THREAD

**Issue by felipebritor** [ibmdb/node-ibm_db#118]
Greetings,

There are some updates in the master branch and one of them is very desired for a project I'm in, but we can't update it directly(git+https). Do you have an idea when a new version is going to be released?

Btw, Thanks for your work on this module!

**Comment by neurotech** [comment]
@felipebritor I'm not sure if you know this, but you can use git urls in the dependencies object in package.json: https://docs.npmjs.com/files/package.json#dependencies

**Comment by felipebritor** [comment]
I wasn't aware about the 'commit-ish' part.

Thanks for the link, @neurotech :)
