### ISSUE TITLE
Error inserting file to BLOB column

### ISSUE THREAD

**Issue by dhaazen** [ibmdb/node-ibm_db#120]
I have a file that is assigned to a variable as a buffer and I'm trying to insert into my table which has the BLOB data type. 

```
    conn.prepare('SELECT id FROM NEW TABLE(INSERT INTO support_document ('+
    'document_data,'+
    'mime_type,'+
    'support_document_type_id'+
    ') VALUES(?,?,?))', function(err, stmt) {

      stmt.execute([
        supportDocuments[i].buffer,
        supportDocuments[i].mimetype,
        supportDocumentLabels[i]
      ], function(err, result) {
        if(err){
          console.log(err);
        } else {

```

When this executes I get the following error:

```
{ [Error: [IBM][CLI Driver] CLI0123E  SQL data type out of range. SQLSTATE=HY004]
  errors: [],
  error: '[node-odbc] SQL_ERROR',
  message: '[IBM][CLI Driver] CLI0123E  SQL data type out of range. SQLSTATE=HY004',
  state: 'HY004' }
```

I was able to do a very similar insert into a postgres DB. Please advise

**Comment by dhaazen** [comment]
I tried to use the blob function as I've seen suggested:

```
    conn.prepare("SELECT id FROM NEW TABLE(INSERT INTO support_document ("+
    "document_data,"+
    "mime_type,"+
    "support_document_type_id"+
    ") VALUES(BLOB('?'),?,?))", function(err, stmt) {

      stmt.execute([
        supportDocuments[i].buffer.toString(),
        supportDocuments[i].mimetype,
        certificationConstants.supportDocumentType[supportDocumentLabels[i]]
      ], function(err, result) {
```

When I try that I get:

```
{ [Error: [IBM][CLI Driver][DB2/LINUXX8664] SQL0420N  Invalid character found in a character string argument of the function "DECIMAL".  SQLSTATE=22018
]
  errors: [],
  error: '[node-odbc] SQL_ERROR',
  message: '[IBM][CLI Driver][DB2/LINUXX8664] SQL0420N  Invalid character found in a character string argument of the function "DECIMAL".  SQLSTATE=22018\n',
  state: '22018' }
```

**Comment by rhtpandeyIN** [comment]
Hi @dhaazen 

Try once this code:

conn.querySync("create table testTable (photoname varchar(50), photofilename varchar(50), photo BLOB(10M))");
  conn.query('select 1 from sysibm.sysdummy1', function (err, data) {
	if (err) {
	console.log(err);
	}
    else {
	console.log(data);
	}
  });
  
  
  var photoname='sample photo';
  var photofilename='abc123.jpg';
  
  var imgfile = fs.readFileSync('abc123.jpg');
  console.log('success reading image file');
  
  var img = imgfile.toString('hex');
  

conn.prepare("insert into testTable(photoname, photofilename, photo) VALUES (?,?, blob('img'))", function (err, stmt) {
    if (err) {
      console.log(err);
      return conn.closeSync();
    }
	stmt.execute(['photoname','photofilename'], function (err, result) {
      if( err ) console.log(err);  
      else result.closeSync();
	  
	  conn.prepare("select * from testTable", function (err, stmt){
        if(err) {
          console.log(err);
          return conn.closeSync();
        }

     stmt.execute([], function(err, result) {
          if(err) console.log(err);
          else {
            data = result.fetchAllSync();
            console.log("table Details: = " );
			
            console.log(data);
            result.closeSync();
          
          }
        });
	
	});
	});
	});

**Comment by dhaazen** [comment]
Hey @rhtpandeyIN , the code that you gave I believe doesn't actually input the read file into the DB this line here:

`"insert into testTable(photoname, photofilename, photo) VALUES (?,?, blob('img'))" `

is just running the blob() function on a string 'img' not the var img if I change the code to:

`"insert into testTable(photoname, photofilename, photo) VALUES (?,?, blob('"+img+"'))" `

I get the following error message:
`
[IBM][CLI Driver][DB2/LINUXX8664] SQL0102N  The string constant beginning with "\'ffd8ffe000104a46494600010100000100010000ffdb0084000a07070807060a08080" is too long.  SQLSTATE=54002\n', `

The hex that goes into the DB with the original code is in fact: 696D67 which is just the hex version of 'img' so it seems like blob() does hex encoding already.

**Comment by polyrabbit** [comment]
Hey everyone, what if I want to place-hold the blob field, doing
```
conn.prepare("insert into testTable(photoname, photofilename, photo) VALUES (?,?, blob('?'))", function (err, stmt) {
}
```
results in 
```
{ [Error: [IBM][CLI Driver][DB2/LINUXX8664] SQL0420N  Invalid character found in a character string argument of the function "DECIMAL".  SQLSTATE=22018
]
  errors: [],
  error: '[node-odbc] SQL_ERROR',
  message: '[IBM][CLI Driver][DB2/LINUXX8664] SQL0420N  Invalid character found in a character string argument of the function "DECIMAL".  SQLSTATE=22018\n',
  state: '22018' }
```
Like @dhaazen said

**Comment by rhtpandeyIN** [comment]
@polyrabbit  @dhaazen Thanks for reporting the issue,
we are working on it, we will get back to you soon.

**Comment by rhtpandeyIN** [comment]
Hi all, this issue is taking little extra time to investigation, we can update you Monday about the ETA and the possible solution.

**Comment by rhtpandeyIN** [comment]
Update: We investigated the issue and verified all dependencies with code changes, we came into conclusion that this issue should be fixed within 2 weeks, well it may take less time also depending on the node dependencies. due to frequent changes in nodejs and nan version it is time consuming process to make generic and working APIs. So please wait for new update, we will update our progress within 2 days.
Thanks.

**Comment by dhaazen** [comment]
Thanks @rhtpandeyIN looking forward you update. Please keep us posted.

**Comment by bimalkjha** [comment]
@dhaazen We found the fix of this issue. Soon we'll have a new release with LOB support in node-ibm_db. There is no work around of this issue as of now. I think by Monday you'll have the fix. Thanks.

**Comment by bimalkjha** [comment]
@dhaazen May I know your platform please? Thanks.

**Comment by dhaazen** [comment]
@bimalkjha Sorry, but I'm not sure what you mean by platform...

**Comment by bimalkjha** [comment]
@dhaazen np. I just want to know the Operating System of the computer where you have installed ibm_db driver. Is it Windows or non-windows? Thanks.

**Comment by dhaazen** [comment]
@bimalkjha: When testing locally, I'm using a OSX, however the application will be deployed on Bluemix which uses Linux. So in both cases "non-Windows".

**Comment by bimalkjha** [comment]
@dhaazen For testing purpose, you can install ibm_db locally using below command. 

`npm install git+https://git@github.com/ibmdb/node-ibm_db.git`

This command requires git should be installed in your system. To know how to insert BLOB data, use these test files [test-blob-insert.js](https://github.com/ibmdb/node-ibm_db/blob/master/test/test-blob-insert.js) and [test-blob-file.js](https://github.com/ibmdb/node-ibm_db/blob/master/test/test-blob-file.js) . Thanks.

**Comment by bimalkjha** [comment]
Check [execute](https://github.com/ibmdb/node-ibm_db#executebindingparameters-callback) and [bindingParameters](https://github.com/ibmdb/node-ibm_db#bindingparameters) doc too for detail. Thanks.

**Comment by dhaazen** [comment]
Just adding a note for those that may check this issue:
Fix appears to work only for very small files. My 167 KB test file gives a "Segmentation fault 11". @bimalkjha is aware and looking to resolve this issue.

**Comment by bimalkjha** [comment]
@dhaazen Just pushed a fix for segfault. Please reinstall and check. Thanks.

**Comment by bimalkjha** [comment]
During testing we found that ibm_db is unable to return binary data of more than 256KB to application. If binary data is of larger than 256kb on server, it gets truncated. Issue is only with BLOB data. We are working to fix it asap.

**Comment by bimalkjha** [comment]
@dhaazen The binary data truncation issue is fixed now. Please reinstall latest code from git and verify. Thanks.

**Comment by dhaazen** [comment]
@bimalkjha I tested with a 1.1Mb file and it worked fine but I tried a 5Mb file and it truncated it.

**Comment by bimalkjha** [comment]
we tested using 1MB file as previously it was unable to retrieve more than 256kb data. we are able to repro using 5mb file and looking into the issue. Thanks.

**Comment by bimalkjha** [comment]
FYI, we got the fix and it will be pushed soon. Thanks.

**Comment by bimalkjha** [comment]
@dhaazen We have pushed the fix for this issue. Please get the latest code and verify. Thanks.

**Comment by dhaazen** [comment]
@bimalkjha That worked for a 11.2MB file seems to be good. Thanks!

**Comment by dhaazen** [comment]
@bimalkjha FYI just tried with 123MB it was truncated to about 70MB...

**Comment by rhtpandeyIN** [comment]
Hi @dhaazen , Can you once try again with different  >70MB file, and please update us what size you are getting back. is it 70 MB every time?

**Comment by dhaazen** [comment]
@rhtpandeyIN I tried an ~84MB file and it was truncated to the same size as the 123MB which is 7064348 as output by the .length of the encoded buffer output from the test.

**Comment by gsaxenaibm** [comment]
Kind of slow progress this way - l want to understand the requirement in detail - just not that we want blob of such and such size but the need for it. Normally in scripting, such use case is hard to understand. Please share the specs.

**Comment by dhaazen** [comment]
Hey @gsaxenaibm I informed @bimalkjha that we are aiming to support the max for the BLOB datatype in DB2 which is 2GB.

**Comment by bimalkjha** [comment]
@dhaazen We have fixed the issue with latest commit. I have tested using 180MB video. It should work till (2GB - 1) bytes of blob data if system is able to allocate that. Also, in node.js we need to write it with binary encoding. Please check the change in test-blob-file.js to know. You can get the latest code and verify. Thanks.

**Comment by rhtpandeyIN** [comment]
hi @dhaazen any updates?

**Comment by dhaazen** [comment]
Hey @rhtpandeyIN sorry Friday was a holiday. I tried to run a test today but when trying to do an install I encountered an error please see new issue.

**Comment by bimalkjha** [comment]
Please retry now, it was a temporary issue. Thanks.

**Comment by dhaazen** [comment]
@bimalkjha The latest worked. I don't really have the internet bandwidth to check any files over a GB but the 139mb I had worked fine. I'm content to close. Thanks everyone for the help.
