### ISSUE TITLE
Support for 32-bit windows?

### ISSUE THREAD

**Issue by luzlab** [ibmdb/node-ibm_db#121]
Hi - I'm working on a NW app that is supposed to run on old windows machines running industrial machinery. I need 32-bit drivers to connect to an embedded instance of DB2. How challenging would it be to add support for windows 32-bit architectures? Are there any technical reasons for not supporting 32-bit windows? Any help would be appreciated!

Thank you,
Carlo

**Comment by bimalkjha** [comment]
32 bit windows are least used and soon may be out of support. We don't see any significant customer request win32 support and hence ibm_db is not supporting it. Alternatively, you can compile the ibm_db source code with 32bit ODBC/CLI driver and make it working on win32. Thanks.
