### ISSUE TITLE
NodeJS v6 Crashing

### ISSUE THREAD

**Issue by arkihillel** [ibmdb/node-ibm_db#122]
NodeJS version >= 6 is crashing with this message

```
(node) v8::ObjectTemplate::Set() with non-primitive values is deprecated
```

Please update to the latest [nan](https://github.com/nodejs/nan) version to fix

**Comment by rhtpandeyIN** [comment]
Hi @arkihillel  which platform you are using? (Windows, Linux, Mac...?)

**Comment by arkihillel** [comment]
I'm using a mac, but it doesn't seem like it should work on any other
platform either since it's crashing when using a v8 deprecated function

**Comment by rhtpandeyIN** [comment]
Hi @arkihillel ,
you can now use node-ibm_db with node V6.X also. we have updated Github repository for the same.
you can use below command to install from github, as we haven't updated npm module yet.
`npm install git+https://git@github.com/ibmdb/node-ibm_db.git`

thanks
