### ISSUE TITLE
All column names are returned in UPPER CASE?

### ISSUE THREAD

**Issue by polyrabbit** [ibmdb/node-ibm_db#124]
Hi, I noticed the returned column name of a `select` query is always in upper case, which is rather counter-intuitive. Is there a way to change that behavior?

```
var ibmdb = require('ibm_db');

ibmdb.open("DRIVER={DB2};DATABASE=name;HOSTNAME=localhost;UID=test;PWD=ss;PORT=50000;PROTOCOL=TCPIP", function (err,conn) {
  if (err) return console.log(err);

  conn.query('select 1 as abc from sysibm.sysdummy1', function (err, data) {
      if (err) console.log(err);
      else console.log(data);

      conn.close(function () {
            console.log('done');
          });
    });
});
```

Results in:
```
[ { ABC: 1 } ]
done
```
Thanks

**Comment by bimalkjha** [comment]
By default all queries going to DB2 server get converted to upper case. If you want to not apply this rule on a column, table or schema; surround that name with double quote in query. Use below query in your test:
```
'select 1 as "abc" from sysibm.sysdummy1'
```
and result would be:
```
[ { abc: 1 } ]
done
```
Thanks and Regards,
Bimal Jha

**Comment by polyrabbit** [comment]
Many thanks @bimalkjha , I didn't know that.
