### ISSUE TITLE
IBM DB2 iSeries V7

### ISSUE THREAD

**Issue by SalahBen82** [ibmdb/node-ibm_db#125]
Hi,

I'd like to connect to a DB2 Iseries V7R1M0 with your module. but I am getting the below error : 

A communication error has been detected. Communication protocol being used: TCPIP.
Communication API being used: SOCKETS. Location where the error was detected: XXXXXX.
Communication function detecting the error: “selectforRecvtimeout”
Protocol specific error code(s): "0", "*", "*".  SQLSTATE=08001

We increase the time out value and we got the same error.

Have you ever encountered this error ?

I tried to connect with Rocket Software API (trial version), and It works. But We must use Node.js (free)

Could you help please ?

Thanks

**Comment by ibmdb** [comment]
Please modify below commands according to install path in your system and share the output:

export PATH=.../ibm_db/installer/clidriver/bin:../ibm_db/installer/clidriver/lib:$PATH
export LD_LIBRARY_PATH=..../ibm_db/installer/clidriver/lib:$LD_LIBRARY_PATH
db2cli validate -database "database_name:host_name:port_number" -connect -user db2_user_id -passwd server_password

If above validate command gives you success, open ibm_db/lib/odbc.js file and update line number 124 as below:

  self.connectTimeout = options.connectTimeout || 30 ;

Alternatively, you can use the connection timeout during ibmdb.open() call as below:
```
var ibmdb=require('ibm_db');
ibmdb.open(connectionString, {"connectTimeout": 30}, callback);
```

Thanks.

**Comment by bimalkjha** [comment]
Please modify below commands according to install path in your system and share the output:

```
export PATH=.../ibm_db/installer/clidriver/bin:../ibm_db/installer/clidriver/lib:$PATH
export LD_LIBRARY_PATH=..../ibm_db/installer/clidriver/lib:$LD_LIBRARY_PATH
db2cli validate -database "database_name:host_name:port_number" -connect -user db2_user_id -passwd server_password
```
If above validate command gives you success, you can use the connection timeout during ibmdb.open() call as below:
```
var ibmdb=require('ibm_db');
ibmdb.open(connectionString, {"connectTimeout": 30}, callback);
```
Alternatively, you can open `.../ibm_db/lib/odbc.js` file and update line number 124 as below:

  `self.connectTimeout = options.connectTimeout || 30 ;`

Thanks.

**Comment by SalahBen82** [comment]
Hi,

Thanks a lot for you replay.

I executed your commands but I steel getting the same error.

Attached, a db2cli validate output and ibmdb.open screenshots.

Do you have any ideas ?

Thanks a lot

![capture](https://cloud.githubusercontent.com/assets/19834667/16037090/385c2756-321f-11e6-8c5b-15ea08984974.PNG)
![capture1](https://cloud.githubusercontent.com/assets/19834667/16037092/3c18590a-321f-11e6-9319-40828475cc36.PNG)

Best Regards

**Comment by bimalkjha** [comment]
Seems your server is not configured to accept remote connection. Please check the TCP/IP port is enabled on server to accept remote connection. The connection is getting refused by the server. You may need to contact your AS400 system admin. Thanks.

**Comment by bimalkjha** [comment]
Also try using full host name or host ip address. Check you are using correct port and check SVCENAME dbm cfg parameter on server. SVCENAME on server should have the port number set. Thanks.

**Comment by SalahBen82** [comment]
Thanks for your quick reply.

I used the IP address instead of the host name but I steel getting the same error.

Regarding your second remark, I think that on the server side, everything is ok because we connected to successfully to it with Rocket Software.

Regards

**Comment by bimalkjha** [comment]
Not sure which protocol is used by Rocket software. Are you using Rocket software locally on AS400?
As we have seen, the connection is failing using db2cli tool too which is a ODBC/CLI tool. Is your system behind any firewall? Good to check with sysadmin and confirm about port as the error is coming from server. You can tell sysadmin to check why server is refusing the connection to client? Thanks.

**Comment by bimalkjha** [comment]
Closing it as it is not a ibm_db issue. Thanks.

**Comment by ptchankue** [comment]
@SalahBen82 Did you fix this?  I am experiencing the exact same issue

**Comment by bimalkjha** [comment]
@ptchankue make sure server is enabled to accept remote connection. The error is coming from server that is refusing connection from client. Also, check you are using correct tcp/ip port number of AS400 server. Thanks.
