### ISSUE TITLE
Security vulnerability with tar@0.1.20

### ISSUE THREAD

**Issue by micophilip** [ibmdb/node-ibm_db#127]
Running `nsp check` command returned Symlink Arbitrary File Overwrite security vulnerability with tar0.1.2, `tar.gz` already updated their dependencies to include the later version of tar that fixed the issue. Please update `tar.gz` to the latest version in order to get the fix.

**Comment by bimalkjha** [comment]
Update in master branch on github which will be available with new release soon. What about [unzip](https://www.npmjs.com/package/unzip) package? seems no-one is maintaining unzip and last update was 2 years back!

**Comment by bimalkjha** [comment]
Addressed in https://github.com/ibmdb/node-ibm_db/blob/master/package.json
