### ISSUE TITLE
Multiple statements execution

### ISSUE THREAD

**Issue by qubing** [ibmdb/node-ibm_db#128]
I want to execute some SQL statements in once invoking. Can this lib support? How?
I'd tried to do it by prepare-execute just like below, but only the first statement had been executed.

> function testBatchExecute(callback) {
>     connect(function(err, conn) {
>         if (err ) {
>             callback(err, conn);
>         }
>         else {
>             conn.prepare("insert into T_TWC_LOG values('1');insert into T_TWC_LOG values('2');", function (err, stmt) {
>                 stmt.execute([], function (err, result){
>                     if (err) {
>                         return callback(err, conn);
>                     }
>                     callback(null, conn, result);
>                 });
>             });
>         }
>     });
> }

**Comment by bimalkjha** [comment]
Just change your query as below:

conn.prepare("insert into T_TWC_LOG values('1'), ('2')" function (err, stmt) {....});

**Comment by qubing** [comment]
@bimalkjha
Thank you for your response so quickly.
Maybe my example is not very well. I want to load some sql statements from sql file, and then run them. So I'm not sure they are using same sql statement to insert lots of data, it's possible that there are may kinds of sql statements such as create table, drop table, insert, updates, etc. Can this kinds of operations be supported?

**Comment by bimalkjha** [comment]
No, node-ibm_db does not support batch mode. Thanks.

**Comment by alobaidizt** [comment]
@bimaljha is this still not supported? would be great if this library can support it? are you open for a PR to handle this issue?

**Comment by bimalkjha** [comment]
@qubing @alobaidizt Multiple sql execution using ibm_db is possible if server supports it. Please check `ibm_db\test\test-basic-test.js` file that is using multiple sql in single call of conn.query() API.

If you want to execute an sql from file and want to get output in another file, you can use can run below command as a system command as a [child process](https://nodejs.org/docs/latest/api/child_process.html) : 
 `db2cli execsql -connstring "database=sample;hostname=hostname.rocketsoftware.com;port=50000;uid=db2admin;pwd=secret" -inputsql sql.txt -outfile  outputfile.txt`

If application is unable to find db2cli executable, then source the ibm_db/installer/setenv.sh file or set similar environment variable for windows. Thanks.

**Comment by alobaidizt** [comment]
@bimaljha we want to run those SQL files using this Node driver for IBM_db. We are aware of the method above, but that doesn't allow us to execute it from within our Node apps programmatically.

**Comment by bimalkjha** [comment]
@alobaidizt Some ibm_db API like conn.execsqlSync(<sqlfile>, <output_file>) would serve your purpose? Such API would accept sqlfile as input, execute all the sql statements in that file one by one using querySync() internally and write the result to outputfile. Please describe the behavior of new API clearly if you want it to function in different way. Thanks.

**Comment by alobaidizt** [comment]
Thanks,@bimaljha! That would, but I don't see it in the Database Methods nor on this repo when I search for that method. Is it already implemented? Can you please post a link to the documentation?
