### ISSUE TITLE
unable to install from private npm registry

### ISSUE THREAD

**Issue by mafischer** [ibmdb/node-ibm_db#131]
When a server does not have internet access, builds fail because http://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/ cannot be reached.

Please consider something like this in your build process: https://www.npmjs.com/package/phantomjs#downloading-from-a-custom-url

**Comment by bimalkjha** [comment]
@mafischer Could you please be more specific? Do you mean hosting ibm_db somewhere else too other than github so that if github is down, application can download it from alternative site?

**Comment by mafischer** [comment]
yes, and especially being able to host it in a private mirror.

**Comment by ryan-roemer** [comment]
This might be a potentially helpful strawman idea for a customizable private url:

```diff
diff --git a/installer/driverInstall.js b/installer/driverInstall.js
index 777375a..2d17a34 100644
--- a/installer/driverInstall.js
+++ b/installer/driverInstall.js
@@ -105,7 +105,12 @@ var download_file_httpget = function(file_url) {
             }
         }
     } else {
-        if(platform == 'win32') 
+        if(process.env.IBM_DB_INSTALLER_FILE_URL)
+        {
+            // Allow environment overrides for installer file URL
+            installerfileURL = process.env.IBM_DB_INSTALLER_FILE_URL;
+        }
+        else if(platform == 'win32')
         {
             if(arch == 'x64') {
                 installerfileURL = installerURL + 'ntx64_odbc_cli.zip';
```

**Comment by mafischer** [comment]
https://github.com/ibmdb/node-ibm_db/pull/136
