### ISSUE TITLE
Error when running "npm install ibm_db" on Windows

### ISSUE THREAD

**Issue by D062271** [ibmdb/node-ibm_db#133]
Hello,

I tried to install the ibm_db node module on Windows. Unfortunately it was not successful.
I am using the latest version of node.
This was printed to the console:

======================================================================

C:\cxadmin>npm install ibm_db
npm WARN package.json checkmarxselfservice@1.0.0 No repository field.
npm WARN package.json checkmarxselfservice@1.0.0 No README data
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail o
n node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible
. Use 'npm ls graceful-fs' to find it in the tree.
\
> ibm_db@0.0.15 install C:\cxadmin\node_modules\ibm_db
> node installer/driverInstall.js

Downloading DB2 ODBC CLI Driver from http://public.dhe.ibm.com/ibmdl/export/pub/
software/data/db2/drivers/odbc_cli/ntx64_odbc_cli.zip...
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 170.225.15.112:80
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1061:14)
 npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "ibm_db"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! ibm_db@0.0.15 install: `node installer/driverInstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ibm_db@0.0.15 install script 'node installer/driverInstal
l.js'.
npm ERR! This is most likely a problem with the ibm_db package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node installer/driverInstall.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ibm_db
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls ibm_db
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\cxadmin\npm-debug.log
======================================================================

I hope somebody can help me.
Thank you in advance for your reply.

**Comment by rhtpandeyIN** [comment]
Hi @D062271 ,
latest version of node is 6.2.2
and from your log I can see you are using v4.4.4
can you please once check and confirm which version you are using?

**Comment by D062271** [comment]
Hi, thank you for your reply.
I looked it up, and indeed I am using v4.4.4
Should I install v 6.2.2?

Thank you very much.

**Comment by rhtpandeyIN** [comment]
Hi, Thanks for confirming, actually you are using `npm install ibm_db` to install this module, and npm till now is supporting upto nodejs v4.X, so in your case it should work fine.

If you will use nodejs V6.X then you have to install this module from github by using below command:
`npm install git+https://git@github.com/ibmdb/node-ibm_db.git`

well you don't need to install V6.2.2 (If you don't want). 
and by looking your log it seems the connectivity issue. are you using internet behind proxy?

**Comment by D062271** [comment]
Yes, it's a corporate network using a proxy.

**Comment by rhtpandeyIN** [comment]
It is firewall proxy issue, contact your administrator or check your firewall proxy settings for the same.
your firewall proxy not allowing to download clidriver form  `http://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/ntx64_odbc_cli.zip`

Thanks, closing issue now.

**Comment by D062271** [comment]
Okay, I'll try that. Thank you very much for your advise.
