### ISSUE TITLE
ibm_db2 object issue

### ISSUE THREAD

**Issue by kumargauravtiwary** [ibmdb/node-ibm_db#137]
![issue](https://cloud.githubusercontent.com/assets/8543375/16480565/73be92b4-3ec4-11e6-9684-7b66663e5ae9.png)

after ibm_db install , i am getting [object object]. pls check the screenshot

**Comment by rhtpandeyIN** [comment]
Hi @kumargauravtiwary,

What command you are trying? and which node version you are using?

**Comment by kumargauravtiwary** [comment]
i tried many versions of node such as - 4.4.2, 4.4.3  , 4.4.5 , 6.2.2 , 0.12.0 and i installed npm install ibm_db and then i gave npm test command

**Comment by kumargauravtiwary** [comment]
while running - npm test

**Comment by kumargauravtiwary** [comment]
If possible please reply soon. i am really stuck by this issue.

**Comment by rhtpandeyIN** [comment]
Ok sure, try below steps:
1) go to test directory (cd test)
2) then try `node run-tests.js` command. (but first edit config.testConnectionString.json file for your credentials)

let us know what you are getting now.

**Comment by rhtpandeyIN** [comment]
Hi @kumargauravtiwary, as per our personal discussion I am quoting conclusion here: " we found that it is not a `ibm-db` module issue, it is purely a system issue."
So I am closing this issue now. 
Hope I helped you to find the problems solution. Thanks.
