### ISSUE TITLE
"Assertion Failed" Error in ibm_db\build\Release\odbc_bindings.node  

### ISSUE THREAD

**Issue by svnasvna** [ibmdb/node-ibm_db#142]
Summary: "Assertion Failed" Error in ibm_db\build\Release\odbc_bindings.node  

Details: Please see the attachments. My NodeJS code that is working perfectly by pulling DB2i data, for the 1st few times, when I call this NodeJS router code "router.get('/:id', function (req, res)..." from Angular2.  However if I call the same route repeatedly (anywhere from 3 to 6 times), the node is hanging by throwing error from the ibm_db package file node_modules\ibm_db\build\Release\odbc_bindings.node in line# 620. See attached screen shot for the exact error messages. 

I have tried adding the  pool.close(function () {...} statements thinking whether I am running out of connections. No luck. I am hitting the same error.

So moved this code from my Windows7 laptop to the Windows2012Server machine and I am still hitting the same exact error. That confirms it is not machine related. I would appreciate if some one could suggest any solutions?

BTW: I have my Angular2 + NodeJS in Windows. DB2i in OS/400.
![ibm_db_error20160717a](https://cloud.githubusercontent.com/assets/18018068/16902898/3e1faeb6-4c3b-11e6-9557-3527ad1df6b4.jpg)
![ibm_db_error20160717a](https://cloud.githubusercontent.com/assets/18018068/16902899/4a32e5d8-4c3b-11e6-9e73-99e2270f32ca.jpg)
[lst_opps1.txt](https://github.com/ibmdb/node-ibm_db/files/368110/lst_opps1.txt)

**Comment by bimalkjha** [comment]
@svnasvna This error tells your application is closing the database connection while other request is still fetching data from the server. Such issues happens mainly due to application logic. If you modify your application as in `https://github.com/ibmdb/node-ibm_db/blob/master/test/webapp.js` , it should work. Just run `node webapp.js` and check. Thanks.

**Comment by svnasvna** [comment]
Hi Bimal. Thank you. Your code helped resolved the issue. However my issue was not "Premature DB connection close". Instead, I have this "**pool1.open(...**" code **inside the route**r that gets each time when call this router. Now I moved this "pool1.open(..." code **OUTside the router** similar to your code example in webapp.js. This resolved my issue. Thanks again.

**Comment by svnasvna** [comment]
This issue can be CLOSED now. Thank you.
