### ISSUE TITLE
graceful-fs@2 and @3 support will be removed soon

### ISSUE THREAD

**Issue by ChALkeR** [ibmdb/node-ibm_db#143]
Hi. `ibm_db` is currently `#64` in my [list of modules](https://gist.github.com/ChALkeR/d39b49642e02277d2292d66c2ea0bced) that would likely to be broken when https://github.com/nodejs/node/pull/6413 lands (which is anticipated to happen before v7.0).

Note that `graceful-fs@1` and `graceful-fs@4` are ok and would not be broken by this, but a `require()` on `graceful-fs@2` or `graceful-fs@3` would cause an error soon.

That is, runtime warning `fs: re-evaluating native module sources is not supported.` would be turned into a throw.

If you or your deps use `graceful-fs@2` or `graceful-fs@3` in runtime — you are affected. 

Tracking: https://github.com/nodejs/node/issues/5213.

**Comment by bimalkjha** [comment]
@ChALkeR ibm_db is not using graceful-fs@3 directly. It is the unzip package which is using graceful-fs@3. 

/Users/bimaljha/nodework/installs> npm ls graceful-fs
/Users/bimaljha/nodework/installs
└─┬ ibm_db@1.0.0
  ├─┬ fstream@1.0.10
  │ └── graceful-fs@4.1.4 
  └─┬ unzip@0.1.11
    └─┬ fstream@0.1.31
      └── graceful-fs@3.0.8 

Seems, no one is maintaining this unzip package as it is 2 years old. ibm_db is using unzip.Parse() to unzip the .zip file on ntx64 platform only. Do you know any good alternative of unzip that ibm_db can use to unzip a .zip on ntx64? Thanks.

**Comment by ChALkeR** [comment]
@bimaljha I have not used them (or even checked them), but other popular alternatives are [unzip2](https://www.npmjs.com/package/unzip2) (which is also affected, see https://github.com/glebdmitriew/node-unzip-2/issues/13) and [yauzl](https://www.npmjs.com/package/yauzl) (which seems to be fine).

I can't recommend them because I haven't used them, though.

**Comment by bimalkjha** [comment]
@ChALkeR Thanks for the info. I'll try to use `yauzl` instead of unzip.

**Comment by rhtpandeyIN** [comment]
Unzip has been removed from ibm_db module, replaced with [node-unzipper](https://github.com/ZJONSSON/node-unzipper).
