### ISSUE TITLE
What is the equivalent to the following JDBC URL in node-ibm_db?

### ISSUE THREAD

**Issue by Wizman888** [ibmdb/node-ibm_db#145]
Hi,

We have the following JDBC connection string:

```
jdbc:informix-sqli://127.0.0.1:49000/database:INFORMIXSERVER=server_tcp
```

What is the `node-ibm_db` equivalent connection string? The following connection string is not working:

```
DRIVER={DB2};DATABASE=database;HOSTNAME=127.0.01;UID=user;PWD=password;PORT=49000;PROTOCOL=TCPIP'
```

We also have tried this one:

```
Database=database;SERVER=127.0.0.1:49000;USERID=user;PASSWORD=password\
```

We can connect to the database successfully using JDBC and the Informix JDBC driver.

Also the following 29 tests fail:

```
C:\Users\cig.dimak\IdeaProjects\cdcadapter\node_modules\ibm_db\test>node run-tests.js

Warning : there are 23 disabled tests

Running test for [DB2] : test-all-data-types ... success
Running test for [DB2] : test-bad-connection-string ... success
Running test for [DB2] : test-bad-pool-connection-issue-42 ... fail
Running test for [DB2] : test-basic-test ... success
Running test for [DB2] : test-binding-connection-timeOut ... success
Running test for [DB2] : test-binding-statement-executeSync ... fail
Running test for [DB2] : test-binding-transaction-commit ... fail
Running test for [DB2] : test-binding-transaction-commitSync ... fail
Running test for [DB2] : test-blob-file ... success
Running test for [DB2] : test-blob-insert ... success
Running test for [DB2] : test-closed ... success
Running test for [DB2] : test-connection-object ... fail
Running test for [DB2] : test-date ... fail
Running test for [DB2] : test-describe-column ... fail
Running test for [DB2] : test-describe-database ... fail
Running test for [DB2] : test-describe-table ... fail
Running test for [DB2] : test-domains-open ... success
Running test for [DB2] : test-global-open-close ... fail
Running test for [DB2] : test-ibm-db-issue14 ... success
Running test for [DB2] : test-ibm-db-issue17 ... success
Running test for [DB2] : test-ibm-db-issue18 ... success
Running test for [DB2] : test-instantiate-one-and-end ... success
Running test for [DB2] : test-issue-54 ... success
Running test for [DB2] : test-issue-get-column-value-2 ... success
Running test for [DB2] : test-memory-leaks-new-objects ... success
Running test for [DB2] : test-multi-open-close ... fail
Running test for [DB2] : test-multi-open-query-close ... fail
Running test for [DB2] : test-multi-openSync-closeSync ... fail
Running test for [DB2] : test-open-close ... fail
Running test for [DB2] : test-open-connectTimeout ... fail
Running test for [DB2] : test-openSync ... fail
Running test for [DB2] : test-pool-close ... success
Running test for [DB2] : test-pool-connect ... success
Running test for [DB2] : test-pool-rollbackTransaction ... success
Running test for [DB2] : test-pool-uncommited ... success
Running test for [DB2] : test-prepareSync-bad-sql ... fail
Running test for [DB2] : test-prepareSync-multiple-execution ... fail
Running test for [DB2] : test-promisified-connection-pool ... success
Running test for [DB2] : test-query-create-table-fetchSync ... fail
Running test for [DB2] : test-query-create-table ... fail
Running test for [DB2] : test-query-drop-table ... fail
Running test for [DB2] : test-query-insert ... fail
Running test for [DB2] : test-query-select-fetch ... fail
Running test for [DB2] : test-query-select-fetchMode-array ... fail
Running test for [DB2] : test-query-select ... fail
Running test for [DB2] : test-querySync-select-with-execption ... fail
Running test for [DB2] : test-querySync-select ... fail
Running test for [DB2] : test-require-and-end ... success
Running test for [DB2] : test-transaction-commit-sync ... fail
Running test for [DB2] : test-transaction-commit ... fail
```

And we use the following configuration:

```json
{ "DRIVER" : "{DB2 ODBC Driver}",
  "DATABASE" : "database",
  "UID" : "user",
  "PWD" : "password",
  "HOSTNAME" : "127.0.0.1",
  "PORT" : 49000,
  "PROTOCOL" : "TCPIP" 
}
```

The client computer is Windows.

**Comment by rhtpandeyIN** [comment]
Hi @Wizman888 , 

I guess due to above mentioned connection issue test cases are failing.
please try as following and let us update.

```
ibmdb = require('ibm_db'), 
cn="DRIVER={DB2 ODBC Driver};DATABASE=database;HOSTNAME=127.0.0.1;UID=user;PWD=password;PORT=49000;PROTOCOL=TCPIP";

ibmdb.open(cn, function (err,conn) 
{
  if (err) 
  {
  return console.log(err);
  }

//Your code here........
});

```

**Comment by behrangsa** [comment]
Just FYI, the database that my colleague is trying to connect to is Informix. Also `cn` in your comment looks identical to the configuration we are using in the test case:

```json
{ "DRIVER" : "{DB2 ODBC Driver}",
  "DATABASE" : "database",
  "UID" : "user",
  "PWD" : "password",
  "HOSTNAME" : "127.0.0.1",
  "PORT" : 49000,
  "PROTOCOL" : "TCPIP" 
}
```

Finally, is it necessary to setup anything in the ODBC Data Source Administrator?

Thanks.

**Comment by Wizman888** [comment]
It does not work either

Error: [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error wa
s detected: "127.0.0.1".  Communication function detecting the error: "recv".  Protocol specific error code(s): "*", "*", "0".  SQLSTATE=08001

**Comment by rhtpandeyIN** [comment]
Hi @Wizman888 ,

Sorry for my late response, Just wanted to know- is it working fine now? After looking your comment it seems server is refusing connection. (It can be Firewall issue or poor internet connectivity)

**Comment by behrangsa** [comment]
We can connect with no problem using JDBC from the same box. So I doubt that it's a firewall issue.

**Comment by Wizman888** [comment]
Hi @rhtpandeyIN 

As far as I can undertand, the problem was in the driver. Your comminication string invokes DB2 while we need to have Informix driver. 

In any case, it did not work and I end up using java driver directly and loading it via jdbc package (that had it's own issues, btw)

**Comment by rhtpandeyIN** [comment]
Ok thanks for the information, I am looking into it, and I will share the details with you ASAP.

**Comment by rhtpandeyIN** [comment]
Hi @Wizman888 

The problem is the setup of DRDA port.
Informix uses SQLI protocol so its able to connect to 49000 port,
where as node-ibm_db or any other DB2 driver uses DRDA protocol - and it will not connect to same port 49000.
You will have to enable DRDA on informix server using different port number.

Please let us know If it works.

**Comment by rhtpandeyIN** [comment]
Do following changes in respective files and restart infomix server and connect using drda port 49001
$INFORMIXSQLHOSTS
server_tcp onsoctcp 127.0.0.1 49000
server_tcp_drda drsoctcp 127.0.0.1 49001

$INFORMIXDIR/etc/$ONCONFIG 
DBSERVERNAME server_tcp
DBSERVERALIASES server_tcp_drda
