### ISSUE TITLE
result.closeSync() resulting segmentation fault 11?

### ISSUE THREAD

**Issue by tokidoki11** [ibmdb/node-ibm_db#146]
I have a batch process of reading a csv and send the content to DB2 via preparedstatement because data contains >32K char.
I call this function I made, and after the batch process is complete, it returns me segmentation fault 11 even though the application seems to be running well, with dummy data.
However if I commented result.closeSync(), there is no segfault shown...

`function runPreparedStatement(bindingParams) {

    return new Promise(function(resolve, reject) {
        ibmdb.open(<SOMECONNSTRING>, function(err, conn) {
            if (err) return console.log(err);

            conn.prepare("INSERT INTO <TBLNAME> (<col1>, <col2>,<col3>, <col4>,<col5>, <col6>,<col7>,<col8>, <col9> ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)", function(err, stmt) {
                if (err) {
                    //could not prepare for some reason
                    console.log(err);
                    return conn.closeSync();
                }

                //Bind and Execute the statment asynchronously
                stmt.execute(bindingParams, function(err, result) {
                    if (err) {
                        //console.log("Prepare Statement Execution Error:" + err.message);
                        reject(err.message);
                    } else {
                        //this causing segmentation fault
                        //result.closeSync();
                    }

                    //Close the connection
                    conn.close(function(err) {
                        //console.log("Closing DB2 COnnection");
                        resolve(bindingParams[0]);
                    });

                });
            });
        });
    });
}`

**Comment by bimalkjha** [comment]
@tokidoki11 Instead of ibmdb.open() use pool.open(). Thanks.

**Comment by tokidoki11** [comment]
Yes, it works.. I think you should index it as hyperlink also on readme. :)
