### ISSUE TITLE
npm version

### ISSUE THREAD

**Issue by agov** [ibmdb/node-ibm_db#148]
npm version is behind master branch
_(i am not familiar with npm process, please close this if it's already pending)_

**Comment by bimalkjha** [comment]
@agov Could you let us know what version you see on npm and what version on github? I think both version are 1.0.0. If not, please share the version info. Thanks.

**Comment by agov** [comment]
@bimaljha Yes, you are right. However eg. [THIS](https://github.com/ibmdb/node-ibm_db/commit/f683c6c6a7b93274f5d848be236d3821de2cec0b) commit is not included in npm package.

**Comment by bimalkjha** [comment]
github code is always ahead of npm. the pointed code will move to npm on next release. we accumulate some code changes on github and after proper testing only release to npm with new version. So, it is normal. I am closing the ticket. Thanks.
