### ISSUE TITLE
IBM_DB Location in reference to JS file that references it.

### ISSUE THREAD

**Issue by andrew4412** [ibmdb/node-ibm_db#149]
Good Afternoon,

I have finally gotten IBM_DB installed on my Windows 7 64 bit machine, but now I am having problems in  referencing it from a Javascript file.  I'm using the tutorial found here: https://www.ibm.com/developerworks/community/blogs/pd/entry/using_ibm_db2_from_node_js4?lang=en

But the .JS file cannot find the installation of IBM_DB.  If the JS file is located at the root of the project, where should the "node-ibm_db" folder be located at?  
For example, say that the path to the node-ibm_db folder is one level down from the JS file in another folder called "nodeapp".  If this were the case, would 

var ibmdb = require('node-ibm_db');

turn into 

var ibmdb = require('nodeapp/node-ibm_db');
?

Thank you,

Andrew

**Comment by bimalkjha** [comment]
@andrew4412 When you run `npm install ibm_db`, on successful installation of ibm_db you'll get a folder `./node_modules/ibm_db/` folder in current directory. It is this `ibm_db` which should be loaded by `require()`. For more info, please check our test files under node-modules/ibm_db/test folder to know how these test files are using require(../) to get ibm_db : https://github.com/ibmdb/node-ibm_db/blob/master/test/test-basic-test.js

Also for loading error, please check file `node_modules/ibm_db/build/Release/odbc_bindings.node` exist or not?

Thanks,
Bimal Jha

**Comment by andrew4412** [comment]
I don't have that folder. I guess it didn't install correctly. I did the manual installation found here: https://github.com/ibmdb/node-ibm_db/blob/master/INSTALL.md#-8-node-ibm_db-how-to-manually-build-on-windows  
and I thought that it was successful, but apparently not.  I have that file, but it isn't under node_modules, it's under the root.  I think I messed up the installation folder somehow.  The odbc_bindings.node file can be found from the root at build/Release/odbc_bindings.node.

![root folder](https://cloud.githubusercontent.com/assets/19668701/17532293/eb514b98-5e4d-11e6-872c-8362f1b7d5ad.png)
![nodeapp folder](https://cloud.githubusercontent.com/assets/19668701/17532294/eb53b266-5e4d-11e6-9bbe-8f7464b55885.png)
![node-ibm_db folder](https://cloud.githubusercontent.com/assets/19668701/17532296/eb957d18-5e4d-11e6-8b22-3439724eb76d.png)
![root folder build directory](https://cloud.githubusercontent.com/assets/19668701/17532297/eb9c6ace-5e4d-11e6-8542-262970ec1391.png)

**Comment by bimalkjha** [comment]
@andrew4412 Building on Windows is a tricky and cumbersome process. I would suggest to build it first on Linux or Mac and then try same steps on Windows. Also, make sure your odbc_bindings.node file is linked to db2app64.dll and should not be dependent on odbc32.exe. You can check it using processExplorer.exe. Thanks.
