### ISSUE TITLE
Failing tests in ibm_db test suite

### ISSUE THREAD

**Issue by GeorgeAdamsIBM** [ibmdb/node-ibm_db#150]
I am trying to run the ibm_db test suite on ubuntu 14.04 with node 4.4.7.0 installed and these three tests keep failing. It is worth noting that I am using CITGM to run the tests.

_test-all-data-types
test-basic-test
test-promisified-connection-pool.js_

Has anyone seem this problem before ?

I have noticed that test-promisified-connection-pool.js is commented out so clearly shouldn't be run but the test seems to be failing anyway (not sure if this is because it expects a parameter to be returned upon passing the test or something?)

Any help appreciated!

Thanks

**Comment by bimalkjha** [comment]
Please update connection string information in `ibm_db\test\config.testConnectionStrings.json` file and then run `node test-basic-test.js`. It should work. If still not working, check your connection info. Thanks.

**Comment by GeorgeAdamsIBM** [comment]
Update:  Fixed by clearing my database and re creating it
```
test-all-data-types
test-basic-test
```

Fixed by running npm install bluebird
`test-promisified-connection-pool.js`
