### ISSUE TITLE
How can I connect to a database through a proxy server ? 

### ISSUE THREAD

**Issue by mayank-patel** [ibmdb/node-ibm_db#158]

**Comment by bimalkjha** [comment]
@mayank-patel what you want to achieve by using proxy server? Your proxy server must have db2connect server or an instance based db2 client installed to connect to the target server. This server will work like gateway. Check this webpage for more info: https://bytes.com/topic/db2/answers/724636-how-use-db2-connect-server-gateway-connect-mainframe-db2-database
