### ISSUE TITLE
test-querySync-select-with-exception.js failing on windows

### ISSUE THREAD

**Issue by GeorgeAdams95** [ibmdb/node-ibm_db#159]
I am having a problem running test-querySync-select-with-exception.js

I am getting the following error:

```
$ node test-querySync-select-with-execption.js
{ Error: [IBM][CLI Driver][DB2/AIX64] SQL0104N  An unexpected token "END-OF-STATEMENT" was found following "select invalid query".  Expected tokens may include:  "<table_expr>".  SQLSTATE=42601

    at Error (native)
    at Database.querySync (C:\newnode\node-ibm_db\lib\odbc.js:515:24)
    at Object.<anonymous> (C:\newnode\node-ibm_db\test\test-querySync-select-with-execption.js:12:17)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (node.js:348:7)
  errors: [],
  error: '[node-odbc] Error in ODBCConnection::QuerySync',
  message: '[IBM][CLI Driver][DB2/AIX64] SQL0104N  An unexpected token "END-OF-STATEMENT" was found following "select invalid query".  Expected tokens may include:  "<table_expr>".  SQLSTATE=42601\r\n',
  state: '42601' }

assert.js:90
  throw new assert.AssertionError({
  ^
AssertionError: '[node-odbc] Error in ODBCConnection::QuerySync' == '[node-ibm_db] Error in ODBCConnection::QuerySync while executing query.'
    at Object.<anonymous> (C:\newnode\node-ibm_db\test\test-querySync-select-with-execption.js:21:8)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (node.js:348:7)
    at startup (node.js:140:9)
    at node.js:463:3

```
Not getting this error on any other platform and all other tests are passing so not a connection string problem.

Any help would be apreciated

**Comment by bimalkjha** [comment]
Please share your node.js version. Thanks.

**Comment by GeorgeAdams95** [comment]
we are testing this on ibm node version 4.5.0.0 and 6.4.0.0

**Comment by rhtpandeyIN** [comment]
Hi @GeorgeAdams95 ,

I checked the test case "test-querySync-select-with-exception.js"
and following error message is the expected output/behavior for this. 
this test case is specifically made for to test the "Invalid Queries".
like : db.querySync("select invalid query");

Hence it will give following output.

{ Error: [IBM][CLI Driver][DB2/LINUXX8664] SQL0104N  An unexpected to
ken "END-OF-STATEMENT" was found following "select invalid query".  E
xpected tokens may include:  "<table_expr>".  SQLSTATE=42601

    at Error (native)
    at Database.querySync (E:\IBM_WORK_TRACK\2016\9IBM_Sep2016\Issue1
59\node_modules\ibm_db\lib\odbc.js:443:24)
    at Object.<anonymous> (E:\IBM_WORK_TRACK\2016\9IBM_Sep2016\Issue1
59\node_modules\ibm_db\test\test-querySync-select-with-execption.js:1
2:17)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
  errors: [],
  error: '[node-odbc] Error in ODBCConnection::QuerySync',
  message: '[IBM][CLI Driver][DB2/LINUXX8664] SQL0104N  An unexpected
 token "END-OF-STATEMENT" was found following "select invalid query".
  Expected tokens may include:  "<table_expr>".  SQLSTATE=42601\r\n',

  state: '42601' }


But in your case I can see there is assertion error after that, which is not in my case.
I testes with Windows machine and node 6.3.0.
I installed ibm_db using "npm install ibm_db"

make sure you haven't changed the assert values in your test case.
Following is the test file code:

``` 
var common = require("./common")
  , odbc = require("../")
  , db = new odbc.Database()
  , assert = require("assert")
  ;

db.openSync(common.connectionString);
assert.equal(db.connected, true);
var err = null;

try {
  var data = db.querySync("select invalid query");
}
catch (e) {
  console.log(e);
  
  err = e;
}

db.closeSync();
assert.equal(err.error, "[node-odbc] Error in ODBCConnection::QuerySync");

```

**Comment by bimalkjha** [comment]
@GeorgeAdams95 This test case is failing for you because you are installing it from github and not from npm. This test file is updated in github but its corresponding windows  binary is not updated. We'll update the windows binary on next release only. 

The reason for failure is the last line of test file and same you are getting in error:

AssertionError: '[node-odbc] Error in ODBCConnection::QuerySync' == '[node-ibm_db] Error in ODBCConnection:

If you get latest test file from github, it is expecting [node-ibm_db] but when you get the same test file from npm, it is expecting [node-odbc]. So, please use `npm install ibm_db@1.0.0` to install the ibm_db on windows and this test file would work. 

If you still want to use the latest code from git, then ignore this test failure till next release or modify the test file to expect [node-odbc] and not [node-ibm_db].

**Comment by GeorgeAdams95** [comment]
@bimalkjha thanks for that, could you please show me where I would need to change the test file to expect node-odbc?

**Comment by rhtpandeyIN** [comment]
db.closeSync();
assert.equal(err.error, "[**node-odbc]** Error in ODBCConnection::QuerySync");

^^^
Here in the last line of the test code.

**Comment by GeorgeAdams95** [comment]
Thanks, that code worked but obviously then doesn't work for other platforms... maybe we need to have an if statement that checks the OS first?

**Comment by GeorgeAdams95** [comment]
This fix has not worked for me, it has actually broken the test for all platforms now

**Comment by bimalkjha** [comment]
@GeorgeAdams95 can you paste the output of `node test-querySync-select-with-exception.js` command. It worked for me on Windows and Mac. Thanks.
