### ISSUE TITLE
Any alternative / manual install method without python?

### ISSUE THREAD

**Issue by agov** [ibmdb/node-ibm_db#160]
Hi,

`Error: Command failed: node-gyp configure build --IBM_DB_HOME=$IBM_DB_HOME --IS_DOWNLOADED=true
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.`

Any alternative way without python?

**Comment by bimalkjha** [comment]
No alternative for non-windows platform as source code get downloaded from npm repository and get compiled. We can't checkin binary for each supported platforms. Yes, on windows you may not need python as we ship compiled binary for ntx64.
Even if you want to build node.js from source code, you need python as documented here: https://nodejs.org/en/download/
"Note: Python 2.6 or 2.7 is required to build from source tarballs."

Thanks and Regards,
Bimal Jha

**Comment by agov** [comment]
@bimalkjha Thanks it makes sense. Is python only required for install or running too?

**Comment by bimalkjha** [comment]
Only to install. Thanks.
