### ISSUE TITLE
Connection Pool Management For Z/OS Systems

### ISSUE THREAD

**Issue by No9** [ibmdb/node-ibm_db#163]
Hi @bimaljha 
As part of the work that is happening to rectify the connection pooling approach in loopback-ibmdb
https://github.com/strongloop/loopback-ibmdb/pull/12 a question has been raised on how we can guarantee that the connections created through the pooling interface are managed so they don't saturate the DB2 server. 
I notice in the code in the pull request that there is an expectation that node-ibm_db will manage the connection pooling as there is no explicit pool management https://github.com/strongloop/loopback-ibmdb/blob/5605192a8dbf8d8d4901543bf651888fa89452bf/lib/ibmdb.js#L259

In previous conversations you explained that the db config for connection pooling `MAX_CONNECTIONS` is stored on the server then sent to the client dynamically and can be seen using `db2 get db cfg` command after a `db2 connect to <dbname>` command is ran.
You can set the configurable `MAX_CONNECTIONS` using `db2 set db cfg` command.

This was in the context of of an LUW system **not** db2 on Z/OS.

Can you confirm that the approach in the pull request will not saturate the DB2 on Z/OS instance or is additional configuration of the client and/or server required.

Please let me know if you need more info

**Comment by bimalkjha** [comment]
@No9 Yes, MAX_CONNECTIONS is a configuration parameter for DB2 for LUW Servers. I am not a Z/OS expert, but this link tells similar parameter exist for DB2 on Z/OS too: http://www.ibm.com/support/knowledgecenter/linuxonibm/liaag/pubdb2c/pubdb2c18.htm

DB2 for z/OS (DSNZPARM parameter)
On our DB2 for z/OS system we used the DSNZPARM parameter MAXDBATS.

MAXDBATS - The maximum number of database access agents from the DB2 connection pool. You can do a display command on DB2 for z/OS to see how many connections are concurrently active.

The z/OS for DB2 command to display this information is:
-dis ddf detail
See Monitor active connections for more details on this output.
From the results of this command, you can decide if MAXDBATS and/or MAXAGENTS needs to be increased. MAXDBATS should be equal to or greater than MAXAGENTS. For instance, if MAXAGENTS is 100 and MAXDBATS is 200 and you see 100 active connections from the display command, you will know the DB2 Connect connection concentration pool has limited the number of connections, while the DB2 connection pool can service 100 more connections from other sources.

For more info, you can contact DB2 for Z/OS support team. Thanks.

**Comment by bimalkjha** [comment]
@No9 We have released ibm_db@1.0.1 with connection pooling enhancement. It has introduced pool.setMaxPoolSize() API to control the maximum no of active connection in pool. Please check https://github.com/ibmdb/node-ibm_db#-4-setmaxpoolsizen for more info. I think it addresses the issue raised in this thread. Thanks.
