### ISSUE TITLE
list of available drivers?

### ISSUE THREAD

**Issue by martov1** [ibmdb/node-ibm_db#166]
Hi!,

When i see the example on the readme, the driver parameter on the connection string is set to
DRIVER={DB2}

However when i see the config example file on test/config.testConnectionStrings.json I see this.
DRIVER={DB2 ODBC Driver}

And when I go to the examples/describe.js example, there is no driver parameter at all.

Am i missing some other documentation?
 how can i know what is the correct connection string for me? 
what drivers are available?
should i be aware of some other possible parameters? like PROTOCOL being other than TCPIP?

**Comment by bimalkjha** [comment]
The value for DRIVER keyword get ignored by ibm_db as of now. So, no need to use in connection string. Thanks.
