### ISSUE TITLE
ssl connection failed 

### ISSUE THREAD

**Issue by BrianJZhang2** [ibmdb/node-ibm_db#167]
I got this error:
![image](https://cloud.githubusercontent.com/assets/20206532/18655816/7f5ad610-7f1e-11e6-9bd1-fbaf273ec647.png)

my configuration is like this:
![image](https://cloud.githubusercontent.com/assets/20206532/18655819/88400796-7f1e-11e6-85e5-ea0d9ab689ec.png)

I put my .arm file along with db2 configuration file under the same folder.

**Comment by bimalkjha** [comment]
Please use `SSLServerCertificate` keyword in `security` and not `SSL_Server_Certificate`. If it does not work, make sure the .arm file is saved under `.../ibm_db/installer/clidriver/cfg` folder and use absolute path of `.arm` file for `SSLServerCertificate` keyword. For more info, please visit this page: http://www.ibm.com/support/knowledgecenter/SSEPGG_10.5.0/com.ibm.db2.luw.apdv.cli.doc/doc/r0061825.html

**Comment by BrianJZhang2** [comment]
changing to `SSLServerCertificate`, putting .arm under `.../ibm_db/installer/clidriver/cfg` and setting the absolute path of .arm for `SSLServerCertificate` gives this error:
![image](https://cloud.githubusercontent.com/assets/20206532/18662069/3cd7085e-7f4b-11e6-8313-386ed6cbcf38.png)

**Comment by bimalkjha** [comment]
so what is your platform.. escape the slashes in path.

**Comment by BrianJZhang2** [comment]
redhat 7.2

**Comment by BrianJZhang2** [comment]
Thanks, Bimal! My problem is due to a permission issue.

**Comment by raguks** [comment]
@bimaljha can you please get the ssl related url information ibm_db_sa documentation? https://github.com/ibmdb/python-ibmdbsa/blob/6bc37aa81ca9117d5eb320ba0572f071fba85d89/ibm_db_sa/ibm_db_sa/ibm_db.py

**Comment by bimalkjha** [comment]
@raguks At line no 174 is ibm_db.py file, we can see 3 SSL related keywords: `['Security', 'SSLClientKeystoredb', 'SSLClientKeystash']`
So, you need to create` keystoredb` using IBM GSKit in your` ibm_db_sa` system and pass the values for these keywords in connection string as below:
```
"DATABASE=<dbname>;UID=<dbuser>;PWD=<dbpass>;HOSTNAME=<hostname>;port=<ssl_port>;security=SSL;SSLClientKeystoredb=<full/path/of/keystoredb>;SSLClientKeystash=<full/path/of/stashfile>"
```
If you are connecting to IBM Bluemix server using ssl, then using `Security=SSL` in connection string is sufficient and no need to use `SSLClientKeystoredb & SSLClientKeystash` keywords in connection string. i.e. no need to create keystoredb.

The` ibm_db.py` code at line 174 has missing keyword `SSLServerCertificate`. By use of `SSLServerCertificate` keyword in connection string, you can directly pass your `<CACerificate>.arm` file in connection string and no need to create keystoredb using GSKit. You can open an issue against `ibm_db_sa` to add `SSLServerCertificate` keyword at line no 174 in ibm_db.py file. Thanks.
