### ISSUE TITLE
Who is the owner of the driver (to contact in case service is unavailable) ?

### ISSUE THREAD

**Issue by huineng** [ibmdb/node-ibm_db#170]
the system cannot download the driver

http://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli//linuxx64_odbc_cli.tar.gz

Internal Server Error

who can we contact ?

**Comment by bimalkjha** [comment]
vgioia@br.ibm.com

**Comment by bimalkjha** [comment]
seems ibm site is down and other services are also impacted.. people are working on it and it should be up soon. currently  vgioia@br.ibm.com should be contacted for any issue with this site. Thanks.

**Comment by jDmacD** [comment]
The site itself is up but this particular directory `http://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/` was edited early this morning.

**Comment by bimalkjha** [comment]
There's an incident with DNS that is preventing the access to Internet server. Many people are working to fix this issue on high priority.

**Comment by bimalkjha** [comment]
The issue is fixed now and `npm install ibm_db` works find now. Please let me know if you still face any issue. Thanks.
