### ISSUE TITLE
ACR using ibm_db is not redirecting

### ISSUE THREAD

**Issue by exhesham** [ibmdb/node-ibm_db#178]
U configured the ACR configuration according to [this link](http://www.ibm.com/support/knowledgecenter/SSEPGG_10.5.0/com.ibm.db2.luw.apdv.cli.doc/doc/c0056196.html) but it is not working for me.

I tried to add the parameters to the connection url as mentioned below.
URL="....;enableAcr=true;clientRerouteAlternateServerName=rcc-hrl-kvg-626;clientRerouteAlternatePortNumber=55001;...."

Is ACR supported or i have syntax error or is it a bug in ODBC ACR?

Thanks

**Comment by bimalkjha** [comment]
The shared knowledgecenter link says to configure ACR parameters in db2dsdriver.cfg file and not in connection string. Using it in connection string will not work. You need to write db2dsdriver.cfg file with ACR settings and save it under ibm_db/installer/clidriver/cfg folder. Then ACR would work. ibm_db will read the db2dsdriver.cfg file from ibm_db/installer/clidriver/cfg folder. Thanks.

**Comment by bimalkjha** [comment]
@exhesham Let me know if you have issues configuring ACR in db2dsdriver.cfg file. Closing the issue as of now. Thanks.
