### ISSUE TITLE
node-ifx_db is already ready for ARM v8 ?

### ISSUE THREAD

**Issue by Trisolaranx** [ibmdb/node-ibm_db#187]
node-ifx_db is already ready for ARM v8 ?
we are developing a app on ARM platform and the OS version is Ubuntu(Linux 3.14.29).

**Comment by bimalkjha** [comment]
I am not sure about node-ifx_db. Probably you should ask in that forum. But, node-ibm_db does not support ARM platform. node-ibm_db uses IBM DB2 ODBC/CLI Driver for connectivity and IBM has no client driver for ARM Linux. Thanks.
