### ISSUE TITLE
Installer script - Leftovers

### ISSUE THREAD

**Issue by IronGremlin** [ibmdb/node-ibm_db#192]
The installer script pulls in an enormous amount of bloat in the form of dependencies and unnecessary cruft that isn't actually used in the module post installation.

Would you be open to a pull request to modify driverInstall.js to clean up after itself?

**Comment by bimalkjha** [comment]
It downloads only "bindings	fstream		nan		tar.gz		unzip" packages which is of 12MB approx. Do you mean installer should delete these packages post installation?

**Comment by IronGremlin** [comment]
That's the thought, at least for the stuff that you're literally only using to download the driver.

Nearly everything in that dependency chain is used once, for the express purpose of downloading and unzipping a single tar.gz file.

Also it might be worth reworking the logic the downloader is using to reduce the number of dependencies it needs up front.

It seems like gruntwork that doesn't add features, so I understand why you haven't done it.

But it's the first thing I do every time I install this package on a project, and I was thinking of writing something to automate it to save myself some time... And I figured if I was going to go that far I might as well just go the extra mile and contribute.
