### ISSUE TITLE
Random timeouts when connecting

### ISSUE THREAD

**Issue by wallali** [ibmdb/node-ibm_db#193]
It looks like sometimes openSync times out. not sure if there is a way to increase the timeout value. I have to keep retrying the connection till it connects.

```
var result = self.conn.openSync(connStr);
                         ^
Error: [IBM][CLI Driver] SQL30081N  A communication error has been detected. 
Communication protocol being used: "TCP/IP".  
Communication API being used: "SOCKETS".  
Location where the error was detected: "50.97.93.115".  
Communication function detecting the error: "selectForRecvTimeout".  
Protocol specific error code(s): "0", "*", "*".  SQLSTATE=08001
```

**Comment by bimalkjha** [comment]
@wallali You can pass connectTimeout value to ibmdb.openSync() as documented here: https://github.com/ibmdb/node-ibm_db#-2-opensyncconnectionstring-options
```
      var option = { connectTimeout : 40 };// Connection Timeout after 40 seconds.
      var conn = ibmdb.openSync(connString, option);
```
Thanks.

**Comment by wallali** [comment]
The connectTimeout value does not seem to make a difference, it appears it is being ignored.

**Comment by bimalkjha** [comment]
@wallali How are you setting it? Could you please share some repro? Thanks.

**Comment by bimalkjha** [comment]
@wallali The default value of connectTimeout is 30 second unless you pass a new value. Test case [test-open-connectTimeout.js](https://github.com/ibmdb/node-ibm_db/blob/master/test/test-open-connectTimeout.js) shows how to use it. This test case is working fine. Thanks.

**Comment by wallali** [comment]
@bimalkjha My timeout value is >30 but it seems to only wait till 30. BTW, what is loginTimeout?

**Comment by bimalkjha** [comment]
@wallali Is the test program test-open-connectTimeout.js not working properly for you? Please share your test program to reproduce the problem.

You can pass either [connectTimeout](http://www.ibm.com/support/knowledgecenter/SSEPGG_11.1.0/com.ibm.db2.luw.apdv.cli.doc/doc/r0021533.html) or loginTimeout as parameter in ibmdb.open(). loginTimeout overrides connectTimeout as both is saved in same variable. Both sets the ODBC connection attribute -[SQL_ATTR_LOGIN_TIMEOUT](http://www.ibm.com/support/knowledgecenter/SSEPGG_11.1.0/com.ibm.db2.luw.apdv.cli.doc/doc/r0006816.html) only.

**Comment by bimalkjha** [comment]
In coming release, we'll remove support for loginTimeout from odbc_connection.cpp file. It was deprecated long back and undocumented. Thanks.

**Comment by bimalkjha** [comment]
@wallali Could you please share the version of ibm_db you are using? you can get it using `npm list ibm_db` command.

**Comment by wallali** [comment]
Its `ibm_db@1.0.1`. 

The test case is verifying that the parameter is set correctly. I was actually using a stopwatch to check the timeout and it was timing out at 30 seconds regardless of the set value. Recent updates to IBM Dash db service are causing timeouts when connecting to the service from local developer machines.

Also the login_timeout value is mentioned in the `odbc_connection.cpp` so I thought maybe there is a race between the two values.

The error we get is:

`var result = self.conn.openSync(connStr);
                         ^
 Error: [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "50.97.93.115".  Communication function detecting the error: "selectForRecvTimeout".  Protocol specific error code(s): "0", "*", "*".  SQLSTATE=08001`

**Comment by bimalkjha** [comment]
@wallali Removed codes related to loginTimeout. Please install the latest code from GitHub and test it. Thanks.
