### ISSUE TITLE
Not correctly handling pull requests

### ISSUE THREAD

**Issue by gildean** [ibmdb/node-ibm_db#194]
You're currently trying to be clever and hide the contributors of pull requests by copy/pasting the code to your own branch and then changing things around and committing your own code while closing the pull request (instead of merging).

This first of all breaks git history for the changes and removes the input of the contributor from that channel as well as remove the credit for the person committing the code.
Also the changes to the code in the pr can lead to unknown effects and bugs or just render the new code unusable.

Try using the actual git merge feature, if you don't want the whole history from the pull request, you can always do a rebase and squash the commits together while still saving the commit messages and history.

**Comment by bimalkjha** [comment]
@gildean This is the only option until you accept and agree to the [cla-individual](https://github.com/ibmdb/node-ibm_db/blob/master/cla_docs/node-ibm_db%20Joint%20Copyright%20cla-individual%20contribution.pdf) contribution terms and conditions for your present and future contributions submitted to the Project. It is our decision to accept some pull request or reject or merge it manually. In your case, it is manually. In future, we have to deal with the bug in your submitted code if in future found any. We need to study and understand your code too, we can't simply merge all changes. For big changes, you should inform us in advance too. Please go through [this doc](https://github.com/ibmdb/node-ibm_db/blob/master/cla_docs/Contributions.md) in detail for more info. Thanks.
