### ISSUE TITLE
Release Connection after prepared statement when using connection pooling?

### ISSUE THREAD

**Issue by pfremm** [ibmdb/node-ibm_db#195]
I am confused on the proper procedures when using connection pooling after I receive my result set for a prepared statement.  Should I just be calling closeSync?

**Comment by bimalkjha** [comment]
Yes, closeSync() and close() moves the connection back to pool so that next call of poo.open() can utilise it. Do not call pool.close(). pool.close() closes all connections of pool and deletes the pool. call pool.close() only when your application terminates. Thanks.
