### ISSUE TITLE
CLI0123E: SQL data type out of range. SQLSTATE=HY004

### ISSUE THREAD

**Issue by ljerka** [ibmdb/node-ibm_db#196]
I am having a problem with calling stored procedure that has output parameters. This is the error:
```
Data is missing from [object Object]
{ Error: [IBM][CLI Driver] CLI0123E  SQL data type out of range. SQLSTATE=HY004  at Error (native)
  errors: [],
  error: '[node-odbc] SQL_ERROR',
  message: '[IBM][CLI Driver] CLI0123E  SQL data type out of range. SQLSTATE=HY004',
  state: 'HY004' }
```

My code:
```
ibmdb.open(driver+hostname+port+db+user+psw+protocol, function (err,conn) {
     if (err) return console.log(err);

     var query = "CaLL name.mySP(?,?,?,?,?,?,?,?,?,?,?)";

     var param1 = {ParamType:"INPUT", DataType:1, Data:""};
     var param2 = {ParamType:"INPUT", DataType:1, Data:""};
     var param3 = {ParamType:"INPUT", DataType:1, Data:76145};
     var param4 = {ParamType:"INPUT", DataType:1, Data:0};
     var param5 = {ParamType:"INPUT", DataType:1, Data:0};
     var param6 = {ParamType:"INPUT", DataType:1, Data:0};
     var param7 = {ParamType:"INPUT", DataType:1, Data:""};

     var param8 = {ParamType:"OUTPUT", DataType:1, Data:0};
     var param9 = {ParamType:"OUTPUT", DataType:1, Data:0};
     var param10 = {ParamType:"OUTPUT", DataType:1, Data:""};
     var param11 = {ParamType:"OUTPUT", DataType:1, Data:0};

     conn.query(query, [param1,param2,param3,param4,param5,param6,param7,param8,param9,param10,param11], function (err, data) {
          if (err) console.log(err);
          else console.log(data);

          conn.close(function () { console.log('>> closed'); });
     });
});
```
I was able to call stored procedure that has only input params but am unable to call any procedure that also has output params.

Any idea?

**Comment by bimalkjha** [comment]
@ljerka what is the version of your ibm_db? Please share output of `npm ls ibm_db` command.
Also, share the type of output parameters of SP. The Datatype in param should reflect the correct SQLType of the SP parameters. Can you share the definition of this SP? Thanks.

**Comment by ljerka** [comment]
`npm ls ibm_db` gives me an error, but here is the output:

```
D:\Projekti\NODE\node-client-db2-sp>npm ls ibm_db
node-db2-client@0.1.0 D:\Projekti\NODE\node-client-db2-sp
`-- ibm_db@1.0.0  extraneous

npm ERR! extraneous: ibm_db@1.0.0 D:\Projekti\NODE\node-client-db2-sp\node_modules\ibm_db
```
Params are:
1) input - char
2) input - char
3) input - integer
4) input - integer
5) input - integer
6) input - integer
7) input - char
8) output - smallint
9) output - integer
10) output - varchar
11) output - integer

Also, I have node v.6.7.0 and npm v.3.10.8., OS win7

**Comment by bimalkjha** [comment]
@ljerka Seems your ibm_db version is v1.0.0 and OUT param support is included in ibm_db@1.0.1. Please upgrade your ibm_db to latest version. It should work. Thanks.

**Comment by bimalkjha** [comment]
@ljerka I think error is due to blank Data in param10. Just use it as:

var param10 = {ParamType:"OUTPUT", DataType:1, Data:"abc"};

param1, 2 and 7 should also be empty? If it do not work after updating param10; update Data of param1, 2 and 7 too and then try. 

Thanks and Regards,
Bimal Jha

**Comment by bimalkjha** [comment]
@ljerka I think OUT param support is added in v1.0.0. so, it should work without update too, but good to update to latest version. Thanks.

**Comment by ljerka** [comment]
Upgraded to v.1.0.1. Got a different error:
```
Data is missing from {"ParamType":"INPUT","DataType":1,"Data":""}
{ Error: [IBM][CLI Driver] CLI0123E  SQL data type out of range. SQLSTATE=HY004
    at Error (native)
  errors: [],
  error: '[node-ibm_db] SQL_ERROR',
  message: '[IBM][CLI Driver] CLI0123E  SQL data type out of range. SQLSTATE=HY004',
  state: 'HY004' }
```
Then I changed param10, as you said. Got the same error so after that I changed param1, param2, param7 also (although they really should be empty - I have few different ways to call that stored procedure, depending on input params, one of them is that all but param3 are empty). Got the similar error:
```
Data is missing from {"ParamType":"INPUT","DataType":1,"Data":0}
{ Error: [IBM][CLI Driver] CLI0123E  SQL data type out of range. SQLSTATE=HY004
    at Error (native)
  errors: [],
  error: '[node-ibm_db] SQL_ERROR',
  message: '[IBM][CLI Driver] CLI0123E  SQL data type out of range. SQLSTATE=HY004',
  state: 'HY004' }
```
It seems that input parameters cannot be empty string for string or 0 for integer. Can that be the case?

**Comment by ljerka** [comment]
Update following my assumption... I changed all input params so that none of it will be an empty string or 0, like this:
```
    var param1 = {ParamType:"INPUT", DataType:1, Data:"a"};
     var param2 = {ParamType:"INPUT", DataType:1, Data:"a"};
     var param3 = {ParamType:"INPUT", DataType:1, Data:1};
     var param4 = {ParamType:"INPUT", DataType:1, Data:1};
     var param5 = {ParamType:"INPUT", DataType:1, Data:1};
     var param6 = {ParamType:"INPUT", DataType:1, Data:1};
     var param7 = {ParamType:"INPUT", DataType:1, Data:"a"};
```
And now I have no more errors thrown. Ofcourse, the stored procedure now isn't working as it is supposed to. So I think it really is a problem in empty strings an null values.

**Comment by bimalkjha** [comment]
@ljerka please install the latest code from git using command `npm install git+https://git@github.com/ibmdb/node-ibm_db.git` and run your older code and confirm. It should work now. Thanks.

**Comment by ljerka** [comment]
I am not getting any error now. But... I don't now how to get anything from the resultset. I am not 100% shure, but I think I was able to get resultset before, with v.1.0.0, when I was calling a procedure with just one input parameter. Now it doesn't seem to work, I only get output parameters.

Here is the code:
```
conn.query(query, [param1], function (err, data) {
          if (err) console.log(err);
          else {
              console.log(data);  // writes out "true" (or array of output parameters, if there are any)
              console.log("RS field: "+data[0].MSG); // error, data[0] not defined; I think it was defined before
          }
          conn.close(function () {});
     });
```
I tried adding third param in `conn.query(query, [param1], function (err, data, THIRD_PARAM) {....}` but it also didn't work.

If you think this has nothing to do with the innitial issue, I can close this and open a new one. Thanx.

**Comment by ljerka** [comment]
I checked, and it really is different for this version and v1.0.0.
Version 1.0.0: console.log(data) writes out the resultset
Version 1.0.1: console.log(data) writes out "true"
Version 1.0.2: console.log(data) writes out "true"

I would like to be able to read output parameters as well as the resultset.

**Comment by bimalkjha** [comment]
@ljerka You need to call it like data[0], data[1] as below:
```
   conn.query(query, [param1, param2, param3], function(err, result){
        if(err) console.log(err);
        else {
            console.log("return value = ", result[0], result[1]);
        }
```
Check the test case test-call-async.js  to know how it is working. Thanks.

**Comment by ljerka** [comment]
@bimalkjha I would like to be able to get resultset AND output params. As we both said, `data` is an array of output param values. It is not a resultset. A stored procedure can have both output params and resultset.
`data[0], data[1], ...` only gives me first, second, ... output parameter. It doesn't give me the resultset. Is it clearer now? Or am I misunderstanding something?

**Comment by bimalkjha** [comment]
@ljerka It is little bit confusing to me. SP returns result for OUT and INPUT params only. Could you please share some example or SP definition where it returns output params and resultset both? Thanks.

**Comment by ljerka** [comment]
I'm not sure what you mean by SP dfinition, but I will try to explain with some examples.

First, let's say that you want the SP to have only one input, city code, and that it outputs every citizen with that city code. Then you would call this SP like this:
```
     var query = "Call name.mySP(?)";
     var param1 = {ParamType:"INPUT", DataType:1, Data:"10000"};

     conn.query(query, [param1], function (err, data) {
          if (err) console.log(err);
          else console.log(data);
          conn.close(function () { console.log('>> closed'); });
     });
```

The result of calling this SP would be a resultset, a table like this:

```
NAME | AGE | STREET
-----------------------
John |  25 | Palace 20
Jane |  38 | Oxford 101
```
So for instance, if you want to writeout Jane's data, you would do it with `console.log(data[1]);`, and if you want to writeout Jane's street, you would do it with `console.log(data[1].STREET);`
This is what I mean when I say resultset, and that is what the v1.0.0. would give me. All newer versions would give me "undefined" for `console.log(data[1]);`

Now, let's say you want your SP too give you back the city name for the city code you entered as input parameter. Since it is always the same city, there is no need to put it into resultset (table), so you put it in output parameter.
Now you have
```
     var query = "Call name.mySP(?, ?)";
     var param1 = {ParamType:"INPUT", DataType:1, Data:"10000"};
     var param2 = {ParamType:"OUTPUT", DataType:1, Data:""};

     conn.query(query, [param1, param2], function (err, data) {
          if (err) console.log(err);
          else console.log(data);
          conn.close(function () { console.log('>> closed'); });
     });
```
So, from the SP you still should get the same resultset (table) as in the first case, but you should also get the output parameter, which is the city that corresponds to the input parameter "10000".

ibm_db@v1.0.0 couldn't handle output parameters so it would give me an error, but versions 1.0.1 and 1.0.2 are giving me output parameters, and no resultset.

I hope I was able to explain it good enough :)

**Comment by bimalkjha** [comment]
@ljerka Thank you for the explanation. We are looking into this will come back with solution. :)

**Comment by ljerka** [comment]
@bimalkjha Hope it will be soon :)
Btw, I see that `npm install ibm_db` still installs v.1.0.1. Since v.1.0.2 solved the blank input params problem, I think you can merge it with master.

**Comment by bimalkjha** [comment]
@ljerka Fix for this issue is available on github with recent push. Please install latest code from git and confirm. Thanks.

**Comment by bimalkjha** [comment]
Check https://github.com/ibmdb/node-ibm_db/blob/master/test/test-sp-resultset.js to see how can we retried OUT params and multiple result sets from SP using query() and querySync() APIs. Thanks.

**Comment by ljerka** [comment]
@bimalkjha I don't know how to install your latest commit. `npm install ibm_db `installs v.1.0.1, and `npm install git+https://git@github.com/ibmdb/node-ibm_db.git` installs v.1.0.2.

**Comment by bimalkjha** [comment]
@ljerka Please use this command : `npm install git+https://git@github.com/ibmdb/node-ibm_db.git`
It will install latest code from git. Thanks.

**Comment by bimalkjha** [comment]
yes, its version is 1.0.2 only.

**Comment by ljerka** [comment]
@bimalkjha Installed the latest version, read [test-sp-resultset.js](https://github.com/ibmdb/node-ibm_db/blob/master/test/test-sp-resultset.js). Not shure how I should call SP from now on, do I put `'1'` infront of parameters, like this: `conn.query(query, ['1', param2], function (err, result) { ... }`? It is giving me an error.

**Comment by bimalkjha** [comment]
@ljerka calling mechanism is same as before. If it is not INOUT or OUT parameter, you can directly put values too. i.e. you can use [param1, param2] as well as [3, 8] too. No change is calling mechanism. thanks.

**Comment by ljerka** [comment]
@bimalkjha Now it gives me the resultset, but no output parameters. How to get them?

Btw, I don't understand your examples in [test-sp-resultset.js](https://github.com/ibmdb/node-ibm_db/blob/master/test/test-sp-resultset.js). You always call SP with 2 parameters, `conn.query(query, ['1', param2], function (err, result) {}`, although (by your comments) first call should have SP with INOUT param and 2 Result Set, 2nd should have SP with only OUT param and no resultset, and 3rd SP with only Result Set and no OUT or INPUT param.

**Comment by bimalkjha** [comment]
@ljerka First SP has one IN parameter and one INOUT parameter. It also returns two resultset. So, passing two values during call. After call, in result variable, we'll have value for INOUT parameter and resultset two. Hopefully you are able to run test-sp-resultset.js script and see the result. thanks.

**Comment by ljerka** [comment]
I am running my script and not getting any output params, only resultset (with data studio I can check what is the output)

```
ibmdb.open(driver+hostname+port+db+user+psw+protocol, function (err,conn) {

     if (err) return console.log(err);

      var query = "CaLL name.SPNAME(?,?,?,?,?)";
      var p1 = {ParamType:"INPUT", DataType:1, Data:"1234567890"}; };
      var p2 = {ParamType:"INPUT", DataType:1, Data: "2016-12-28"};
      var p3 = {ParamType:"OUTPUT", DataType:1, Data:""};
      var p4 = {ParamType:"OUTPUT", DataType:1, Data:""};
      var p5 = {ParamType:"OUTPUT", DataType:1, Data:""};

      conn.query(query, [p1,p2,p3,p4,p5], function (err, data) {
          if (err) console.log(err);
          else {
              console.log(data); 
          }
          conn.close(function () {});
     });
});
```

**Comment by bimalkjha** [comment]
The error SQL1336N is expected as you have not updated the connection information in test-sp-resultset.js file. Please update connection information in ibm_db/test/config.testConnectionStrings.json file and then run `node test-sp-resultset.js`. Alternatively, you can edit this test file and provide connection string in ibmdb.open() function. First check, you are able to run test-sp-resultset.js successfully and able to see out params and resultset both, then update your script accordingly. thanks.

**Comment by ljerka** [comment]
I won't be able to do that because I don't have enough privileges to create tables etc. How do I need to update my script? You said the was no change is calling mechanism.

**Comment by bimalkjha** [comment]
Please share the output of `console.log(data)` that you are getting. Also, if possible, share the definition of name.SPNAME i.e. create procedure SQL for SPNAME. thanks.

**Comment by bimalkjha** [comment]
Also, in your script, add a line `ibmdb.debug(true);` before `ibmdb.open()` function and then run it. thanks.

**Comment by ljerka** [comment]
Here it is:
```
CREATE PROCEDURE namespace.spname 
	(IN P_1 CHAR(11), 
	IN P_2 DATE,
	OUT P_3 CHAR(1),
	OUT P_4 INTEGER,
	OUT P_5 CHAR(13), 
	OUT P_6 VARCHAR(2), 
	OUT P_7 CHAR(1),
	OUT P_8 CHAR(2),	
	OUT P_9 VARCHAR(200), 	
	OUT P_10 CHAR(4), 		
	OUT P_11 CHAR(4), 
	OUT P_12 CHAR(4), 		
	OUT P_13 CHAR(4), 	
	OUT P_14 CHAR(6), 	
	OUT P_15 VARCHAR(200),	
	OUT P_16 VARCHAR(5),		
	OUT P_17 CHAR(4),	
	OUT P_18 VARCHAR(5),		
	OUT P_19 VARCHAR(35), 	
	OUT P_20 CHAR(3),	
	OUT P_21 CHAR(2),
	OUT P_22 CHAR(2), 
	OUT P_23 CHAR(7),			 
	OUT P_24 CHAR(1),
	OUT P_25 CHAR(1),
	OUT P_26 CHAR(4),
	OUT P_27 CHAR(11))

	RESULT SETS 1
	ISOLATION LEVEL CS
	PACKAGE OWNER xxxx
	QUALIFIER yyyy
	LANGUAGE SQL
        CURRENT DATA NO
	VALIDATE BIND
	ASUTIME LIMIT 1000
```
Code where I call the SP
```
var query = "CaLL "+namespace+"."+spname+"(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
        var p1 = {ParamType:"INPUT", DataType:1, Data:"12345678901"}; };
	var p2 = {ParamType:"INPUT", DataType:1, Data: "2016-12-20"};
	var p3 = {ParamType:"OUTPUT", DataType:1, Data:"", Length:100};
	var p4 = {ParamType:"OUTPUT", DataType:1, Data:"", Length:100};
	var p5 = {ParamType:"OUTPUT", DataType:1, Data:"", Length:100};
	var p6 = {ParamType:"OUTPUT", DataType:1, Data:"", Length:100};
	var p7 = {ParamType:"OUTPUT", DataType:1, Data:"", Length:100};
	var p8 = {ParamType:"OUTPUT", DataType:1, Data:"", Length:100};
	var p9 = {ParamType:"OUTPUT", DataType:1, Data:"", Length:100};
	var p10= {ParamType:"OUTPUT", DataType:1, Data:"", Length:100};
	var p11= {ParamType:"OUTPUT", DataType:1, Data:"", Length:100};
	var p12= {ParamType:"OUTPUT", DataType:1, Data:"", Length:100};
	var p13= {ParamType:"OUTPUT", DataType:1, Data:"", Length:100};
	var p14= {ParamType:"OUTPUT", DataType:1, Data:"", Length:100};
	var p15= {ParamType:"OUTPUT", DataType:1, Data:"", Length:100};
	var p16= {ParamType:"OUTPUT", DataType:1, Data:"", Length:100};
	var p17= {ParamType:"OUTPUT", DataType:1, Data:"", Length:100};
	var p18= {ParamType:"OUTPUT", DataType:1, Data:"", Length:100};
	var p19= {ParamType:"OUTPUT", DataType:1, Data:"", Length:100};
	var p20= {ParamType:"OUTPUT", DataType:1, Data:"", Length:100};
	var p21= {ParamType:"OUTPUT", DataType:1, Data:"", Length:100};
	var p22= {ParamType:"OUTPUT", DataType:1, Data:"", Length:100};
	var p23= {ParamType:"OUTPUT", DataType:1, Data:"", Length:100};
	var p24= {ParamType:"OUTPUT", DataType:1, Data:"", Length:100};
	var p25= {ParamType:"OUTPUT", DataType:1, Data:"", Length:100};
	var p26= {ParamType:"OUTPUT", DataType:1, Data:"", Length:100};
	var p27= {ParamType:"OUTPUT", DataType:1, Data:"", Length:100};

        conn.query(query, 
[p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,p17,p18,p19,p20,p21,p22,p23,p24,p25,p26,p27],  
	function (err, data) {
                if (err) reject (err);
		else {
		       	console.log(data);
		}
          	conn.close(function () { });
         });
```

Complete output:
```
node-ibm_db logs enabled.
odbc.js:query() => CaLL namespace.spname(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
[ { SIF: '01', DESC: 'aaa' },
  { SIF: '02', DESC: 'bbb' },
  { SIF: '10', DESC: 'ccc' } ]
```

Last 3 lines are also the output of console.log(data);

**Comment by bimalkjha** [comment]
May I know your platform? It is windows or non-windows? thanks.

**Comment by ljerka** [comment]
Win7

**Comment by bimalkjha** [comment]
Ok.. the code changes that I delivered is not effective on windows yet. It will take some time to build binary for windows and update the git. You can see the new behaviour only on non-windows platform as of now. We'll update you once it will be available for windows too.

Also, after looking on your SP, I do not see any cursor opened. So, what is expected in resultset here?
Please let us know your target database server type as the shared create procedure SQL fails with below error on Linux server.
```
Error: [IBM][CLI Driver][DB2/LINUXX8664] SQL0104N  An unexpected token "LEVEL CS LANGUAGE SQL CURRENT DATA NO VAL" was found following "ULT SETS 1 ISOLATION".  Expected tokens may include:  "<space>".  LINE NUMBER=1.  SQLSTATE=42601
```
thanks.

**Comment by ljerka** [comment]
I didn't write the whole SP definition. There is another 400 lines of code with declarations, table selects and so on, but I can't share that with you.
You can see the resultset from the output I wrote you in the last post. It is a table with 2 columns - SIF and DESC (I changed the output variable names and values, but it looks like this):

```
[ { SIF: '01', DESC: 'aaa' },
  { SIF: '02', DESC: 'bbb' },
  { SIF: '10', DESC: 'ccc' } ] 
```
Looking forward to seeing code changes working on windows. Thank you for your help so far  :)

**Comment by bimalkjha** [comment]
@ljerka We have released the code changes for windows too. Please install ibm_db@1.0.2 and verify it. Thanks.

**Comment by ljerka** [comment]
It works! Thanks :)
