### ISSUE TITLE
ibm_db not available again

### ISSUE THREAD

**Issue by ichabondcrane** [ibmdb/node-ibm_db#197]
we cannot download  the ibm_db driver again.

http://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli//linuxx64_odbc_cli.tar.gz

Internal Server Error

Could you help us find the contact for this.. Thanks in advance.
This was the same issue we had last sept.
https://github.com/ibmdb/node-ibm_db/issues/170

**Comment by bimalkjha** [comment]
@ichabondcrane It is was a temporary network issue and site is up now. `npm install ibm_db` is working fine now. Please check.  Thanks.

**Comment by ichabondcrane** [comment]
Thanks @bimalkjha , its now working.
