### ISSUE TITLE
as400 iseries SQL30082N  Security processing failed

### ISSUE THREAD

**Issue by naxmefy** [ibmdb/node-ibm_db#199]
hello dont understand your documentation for as400 / iseries

wanna connect to a db2 but got following error
```
Error: [IBM][CLI Driver] SQL30082N  Security processing failed with reason "15" ("PROCESSING FAILURE").  SQLSTATE=08001
```
conn string
```
PROTOCOL=TCPIP;DATABASE=user;HOSTNAME=testhost;PORT=446;UID=user;PWD=pass
```

in your documentation u talked about a **db2connect license** - do i really need this?
When i use database viewer from intellij idea (JDBC DB2 JTOpen - same credentials) i can connect to db without problems :/

can someone please explain the problem?

(tried also node-jdbc -> node-java <- everything failed - i could cry T_T)

**Comment by bimalkjha** [comment]
@naxmefy Connectivity to iSeries and z/OS servers are not free. It is the requirement enforced by the server and not client. If server is configured to accept connection from any client without license, ibm_db should be able to connect. Please check with your system admin or IBM representative for iSeries for more info about it.
You may not require db2connect license at client side if iSeries server is db2connect activated. As you mentioned, you are able to establish connection using JDBC client, connection might be possible using  ibm_db. 
Looking on your SQL30082N error, it mentioned the reason 15 about this failure. If we look for detail about SQL30082N here `http://www.ibm.com/support/knowledgecenter/SSEPGG_11.1.0/com.ibm.db2.luw.messages.sql.doc/doc/msql30082n.html`
```
15 (PROCESSING FAILURE)
Security processing at the **server** failed.
```
So, please check with your sysadmin that why server is refusing connection from client? 

Thanks and Regards,
Bimal Jha

**Comment by naxmefy** [comment]
**INFO**
got it working with node-java and a jdbc implementation

**Comment by bimalkjha** [comment]
@naxmefy seems your server is enabled only to accept JDBC connection and not ODBC connection. please check with sysadmin. Also, you can update connection info in ibm_db/installer/testODBCConnection.sh file and run it to verify the ODBC connection. thanks.
