### ISSUE TITLE
npm install fails on xlinux - redhat 6.3

### ISSUE THREAD

**Issue by smartmouse** [ibmdb/node-ibm_db#2]
$ npm --version
1.4.3
../src/odbc.cpp:275: error: initializer expression list treated as compound expression
../src/odbc.cpp:275: error: expected â,â or â;â before â{â token
make: *** [Release/obj.target/odbc_bindings/src/odbc.o] Error 1
make: Leaving directory `/home/xxx/testdb2/node_modules/ibm_db/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/xxx/JoyentSVT64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:107:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1045:12)
gyp ERR! System Linux 2.6.32-431.1.2.el6.x86_64
gyp ERR! command "node" "/home/xxx/JoyentSVT64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /home/xxx/testdb2/node_modules/ibm_db
gyp ERR! node -v v0.11.12
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok
npm ERR! ibm_db@0.0.1 preinstall: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ibm_db@0.0.1 preinstall script.
npm ERR! This is most likely a problem with the ibm_db package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls ibm_db
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 2.6.32-431.1.2.el6.x86_64
npm ERR! command "/home/xxx/JoyentSVT64/bin/node" "/home/ixxx/JoyentSVT64/bin/npm" "install" "ibm_db"
npm ERR! cwd /home/xxx/testdb2
npm ERR! node -v v0.11.12
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/xxx/testdb2/npm-debug.log
npm ERR! not ok code 0

in the npm-debug.log

**Comment by mariobriggs** [comment]
thanks for confirming it worked with those versions.

As for other OS support it is just a matter of making the entries in bindings.gyp for those platforms. We have some internal IBM teams already interested in those and working with them and will be externalized once done (though as of today i cannot specify a concrete date). As for 1.2, this is the first request, so we will keep in our list of TODO's and  i would suggest you open a new issue with this title

**Comment by smartmouse** [comment]
Thank you, we can close this now,
