### ISSUE TITLE
problem with date timezone values

### ISSUE THREAD

**Issue by devnieL** [ibmdb/node-ibm_db#20]
Hi,

Well, I don't know if it's a problem of db2 or ibm_db or JavaScript, could you help me please?: 

My DB2 database has the following timezone `-60,000`, that is `GMT -0600`, so, for example, I have a  `2014-11-07 18:20:44.81477` value as a TIMESTAMP on DB2, (as I read, a timestamp doesn't include the timezone).

My application's OS timezone is GMT -5, and it's returing that timestamp value as following : 

`Fri Nov 07 2014 18:20:44 GMT-0500 (SA Pacific Standard Time)` , I think that this is product of 
`new Date('2014-11-07 18:20:44.81477')` that returns the worst result. The expected result is `Fri Nov 07 2014 18:20:44 GMT-0600 (SA Pacific Standard Time)`.

By now, my workaround is to use momentjs, where global.db2_tz is the DB2 timezone : 

`moment(timestamp_value).subtract(global.db2_tz - -(moment().zone()/60),'hours').zone(0)`

[Sorry, I didn't try the intermediate_fixes branch, let me try it and if the problem is resolved I will close the issue]

Thanks

**Comment by mariobriggs** [comment]
Sorry for the late reply. Can you confirm whether your DB2 server is LUW or z/OS. Will try to reproduce and keep you updated on findings. I dont believe we made any fixes in this area even in the latest 0.0.6
