### ISSUE TITLE
DB2 error when using password with semicolon in it

### ISSUE THREAD

**Issue by dkunz57** [ibmdb/node-ibm_db#203]
When I use the "Quick Example" code on https://www.npmjs.com/package/ibm_db to connect to DB2, I can do this successfully. However our security gods change our DB2 password every day. The passwords are complex and sometimes have semicolons in them. When there is a semicolon in the password the Quick Example script, it produces the error message below. I'm including a slightly obfuscated connect string below the error message. I've made attempts to escape the semicolon out but so far no luck. Any ideas? Is there another driver I can use? Thanks.

{ [Error: [IBM][CLI Driver] SQL30082N  Security processing failed with reason "24" ("USERNAME AND/OR PASSWORD INVALID").  SQLSTATE=
]
  errors: [],
  error: '[node-odbc] SQL_ERROR',
  message: '[IBM][CLI Driver] SQL30082N  Security processing failed with reason "24" ("USERNAME AND/OR PASSWORD INVALID").  SQLSTAT
  state: '08001' }

Here is the connect string I'm using:
"DATABASE=mydb;HOSTNAME=myhost;UID=myuserid;PWD=sample_password;with_semicolon;PORT=61020;PROTOCOL=TCPIP"

**Comment by bimalkjha** [comment]
@dkunz57 Try with password within single quote as in below CLP command:

`db2 connect to sample USER admin USING '!xyz' `

i.e. below connection string:

`"DATABASE=mydb;HOSTNAME=myhost;UID=myuserid;PWD='sample_password;with_semicolon';PORT=61020;PROTOCOL=TCPIP"`

Semicolon is used as separator in connection string, so ODBC driver parser logic is treating semicolon in password as delimiter. Thanks.

**Comment by bimalkjha** [comment]
@dkunz57 Password rules for IBM database drivers is documented here: [Password rules for drivers](http://www.ibm.com/support/knowledgecenter/en/SSEPGG_10.5.0/com.ibm.swg.im.dbclient.install.doc/doc/c0060749.html)

Seems, we can not use semicolon in password. Please follow the password rules as documented. Thanks.
