### ISSUE TITLE
Invalid Handle: SQLGetData retrun code = -2, stmt handle = 1:12, columnType = 12, index = 1 Assertion failed: (ret != SQL_INVALID_HANDLE), function GetColumnValue, file ../src/odbc.cpp, line 627. when using connection pooling and prepared statements

### ISSUE THREAD

**Issue by pfremm-NM** [ibmdb/node-ibm_db#204]
I am attempting to run many similar queries using connection pooling and prepared statement and connection pooling.  I seem to get inconsistent results on how many times I can this in a row before I get the error below:

Invalid Handle: SQLGetData retrun code = -2, stmt handle = 1:12, columnType = 12, index = 1
Assertion failed: (ret != SQL_INVALID_HANDLE), function GetColumnValue, file ../src/odbc.cpp, line 627.

Below is the code snipet my callback function is using to query the database.  Based on your documentation I am not seeing what my error is.
````
connPool.prepare(query, function (err, stmt) {
    if (err) {
        //could not prepare for some reason
        logger.error('Error preparing statement for UDB:' + err);
        conn.closeSync();
        return callback(err, null);
    }
    if(stmt === undefined)  {
      return callback(new Error('unknown db error occured'), {});
    }
    stmt.execute(param, function (err, result) {
      if(result === undefined)  {
        return callback(new Error('unknown db error occured'), {});
      }
      logger.info("execute db query");

        if (err) {
            logger.error('Error executing UDB Query: ' + err);
            result.closeSync();
            return callback(err, null);
        } else {
            result.fetchAll(function (err, data) {
              logger.info('fetch rows for  db');
                if (err) {
                    logger.error('Error on results: ' + JSON.stringify(
                      err));
                    callback(err, null);
                }
                result.closeSync();
                return callback(null, data);
            });
        }
    });
});
````

**Comment by pfremm-NM** [comment]
My issue was your documentation is not clear for prepared statements.  Needed to add stmt.closeSync() before the final callback.

**Comment by bimalkjha** [comment]
@pfremm-NM please let us know example of which API is incorrect. You have pasted some code but it is not clear for me - this code is from the example of which API and which line need to be added. we'll correct the docs. thanks.

**Comment by leonimurilo** [comment]
I had the same problem today and adding "stmt.closeSync()" solved it.
