### ISSUE TITLE
public.dhe.ibm.com wonky again

### ISSUE THREAD

**Issue by dexdexdex** [ibmdb/node-ibm_db#205]
Hello hello-

We saw that public.dhe.ibm.com had problems serving up files again at
http://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/

For the majority of the day we only saw three files nt32_odb_cli.zip, ntx64_odbc_cli.zip, and ibm_db2-1.9.6.1.tar. driverInstaller.js will try to grab a whole bunch of other stuff though based off of your OS and your architecture (like linuxx64_odbc_cli.tar.gz). 

It looks like that's restored, but I'm really curious since we've seen this multiple times what's up with public.dhe.ibm.com? Should we try not to reference that download location anymore if it's been unstable for us in the past? (see all the public dhe install issues this repo has had in the past).

I actually tried forking the repo and hard coding the binaries that our builds require before this functionality got restored. It would have been a terrible approach though because that increases the repo size by like 75MB, but we were about to deploy it so that our builds could get working again.

**Comment by dexdexdex** [comment]
public.dhe.ibm.com experienced some instability today as well.

**Comment by vuldin** [comment]
I mistakenly made comments related to this problem in a previously closed issue:

https://github.com/ibmdb/node-ibm_db/issues/156#issuecomment-267077339

That other issue was related to the same problem, but for some reason the issue was closed.

**Comment by qpresley** [comment]
This module relies on the official download site for the DB2 ODBC drivers which unfortunately can have periodic issues.  I'm not sure this is an issue that can or should be addressed within the node-ibm_db module.

**Comment by bimalkjha** [comment]
There are two ways to get rid of public.dhe.ibm.com:
1/  Keep the clidriver at some different location and set the path to environment variable IBM_DB_INSTALLER_URL as below:
    export IBM_DB_INSTALLER_URL='https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli'

2/  Install IBM Data Server Driver Package or other client driver from http://www-01.ibm.com/support/docview.wss?uid=swg21385217 first and point the install location to environment variable IBM_DB_HOME. You can also keep backup of ibm_db/installer/clidriver at other location and point IBM_DB_HOME to it as below:
    export IBM_DB_HOME=/User/bimaljha/clidriver

In both of the above case, `npm install ibm_db` has no dependency on public.dhe.ibm.com. For 2nd case, even no driver will get downloaded.

**Comment by bimalkjha** [comment]
node-ibm_db is using the ODBC/CLI driver available on IBM site here for download by customers: http://www-01.ibm.com/support/docview.wss?uid=swg21385217
node-ibm_db has less dependency to download odbc driver from https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/ . User can install IBM Client driver (dsdriver) from http://www-01.ibm.com/support/docview.wss?uid=swg21385217 and set IBM_DB_HOME environment variable to point the install directory. If IBM_DB_HOME is set; `npm install ibm_db` will not download odbc driver from https://public.dhe.ibm.com. Hope it explains. Thanks.
