### ISSUE TITLE
Rows Affected

### ISSUE THREAD

**Issue by mscottx88** [ibmdb/node-ibm_db#206]
Is there a mechanism to retrieve the number of rows affected by an SQL statement?

For instance, if I perform a delete natively, I can inspect sqlErrD(3) from the SQLCA to determine the number of rows.

Can/Should I use the GET DIAGNOSTICS statement after invoking a DELETE or something?

**Comment by bimalkjha** [comment]
@mscottx88 Not now. we can take it as an enhancement request. thanks.

**Comment by bimalkjha** [comment]
@mscottx88 Have you tried [executeNonQuery](https://github.com/ibmdb/node-ibm_db#executeNonQueryApi) API? It says:

It returns the number of rows in a table that were affected by an UPDATE, an INSERT, a DELETE, or a MERGE statement issued against the table, or a view based on the table. If no rows are affected, it returns -1 via the callback function.

Thanks.

**Comment by mscottx88** [comment]
Awesome, thanks Bimal, I'll give this a go!
