### ISSUE TITLE
drivers should be downloaded over https

### ISSUE THREAD

**Issue by rmg** [ibmdb/node-ibm_db#208]
As per [this report](https://snyk.io/vuln/npm%3Aibm_db%3A20161219), the installer should be downloading files over https, not bare http.

It looks like a one-line change, so it is probably easier for one of the committers to fix rather than mucking with contribution policies.

/cc @qpresley

**Comment by bimalkjha** [comment]
The binary for ODBC library is hosted on http://public.dhe.ibm.com. so `http` package is used here to download the tar.gz file only and no source code. I think it should be fine as of now. thanks.

**Comment by rmg** [comment]
The fact that it is a binary actually makes it worse, since it can't easily be inspected and verified. 

The problem isn't that public.dhe.ibm.com can't be trusted, the problem is that without SSL and certificate verification you can't verify that you are actually connecting to public.dhe.ibm.com. 

Note that the `https` module built in to node core uses the same API as the `http` module. The changes required are minimal.

**Comment by vuldin** [comment]
The binaries are also available via HTTPS. Most modern, properly configured web servers serve their content both securely (HTTPS) and insecurely (HTTP):

https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli//linuxx64_odbc_cli.tar.gz

Also, most modern, properly configured web applications take into account security, as mentioned by the original poster.

It makes no difference whether the link points to source code or binary, in fact it is worse if the content being downloaded is a binary.

**Comment by bimalkjha** [comment]
@vuldin Thanks. We'll push the fix for it soon.

**Comment by bimalkjha** [comment]
Advisory https://nodesecurity.io/advisories/163 is now updated with remediation. Thanks.

**Comment by vuldin** [comment]
Awesome thanks for your work.

**Comment by mafischer** [comment]
This solution has broken the ability to use [IBM_DB_INSTALLER_URL](https://github.com/ibmdb/node-ibm_db/blob/master/INSTALL.md#221-direct-installation) with http.

**Comment by rhtpandeyIN** [comment]
@mafischer we are working on this issue, If possible could you please once test this command in your setup environment, It is just for testing and feedback purpose. If below command works for you please update us.

npm install git+https://git@github.com/rhtpandeyIN/node-ibm_db.git

**Comment by bimalkjha** [comment]
@mafischer Use the url starting with https for IBM_DB_INSTALLER_URL. It it still does not work, check using the command provided by Rohit above. Thanks.

**Comment by bimalkjha** [comment]
@mafischer The latest commit to master has fix for IBM_DB_INSTALLER_URL. Please verify. Thanks.
