### ISSUE TITLE
Use of global mutex results in blocking of concurrent queries

### ISSUE THREAD

**Issue by qpresley** [ibmdb/node-ibm_db#211]
Note this may be related to #210.

The following code sample shows how the use of uv_mutex_lock with ODBC::g_odbcMutex with multiple parallel executions of a statement will result in hangs and eventual lock timeouts within the database.

The issue here is that when multiple threads execute the C code in this wrapper will take and release g_odbcMutex for many operations through the processing of a query.  Some examples are UV_Query, UV_GetRecordTuple, etc.  In the example below, when run, you can see that the first execution of the statement hangs in UV_GetRecordTuple because the second execution is holding the lock.  The second execution in this case happens to also be stuck because it is waiting on a ROW lock in the database which the first execution is holding (transaction hasn't committed).

The use of uv_mutex_lock needs to be reviewed across this module as concurrency of queries of similar row sets will inevitably result in deadlocks in the current design

``` javascript
var ibmdb = require("ibm_db");
var sleep = require("sleep");
var cn = 'DRIVER={db2};UID=<uid>;PWD=<pwd>;DATABASE=<dbName>;HOSTNAME=<host>;PORT=<port>';
var stmt0 = {};
var stmt1 = {};
var stmt2 = {};

stmt1.sql = 'SELECT COUNT(C1) FROM FINAL TABLE(UPDATE T1 SET C2=?, C3=? WHERE C1=1)';
stmt1.params = ['Joe', 'Tim'];
stmt1.noResults = false;

stmt2.sql = 'SELECT COUNT(C1) FROM FINAL TABLE(UPDATE T1 SET C2=?, C3=? WHERE C1=1)';
stmt2.params = ['Jane', 'Joan'];
stmt2.noResults = false;

//open a connection to the database
ibmdb.open(cn, function(err, conn1) {
  if (err) {
    //Something went bad
    console.log(err);

    //Let's not go any further
    return;
  }

  stmt0.sql = 'DROP TABLE T1';
  stmt0.noResults = true;
  try{
    conn1.querySync(stmt0.sql);
  } catch(e) {
    console.log('INFO: Table already dropped');
  }

  stmt0.sql = 'CREATE TABLE T1 (C1 INT PRIMARY KEY NOT NULL, C2 CHAR(50), C3 CHAR(50))';
  conn1.querySync(stmt0.sql);

  stmt0.sql = 'INSERT INTO T1 VALUES (1, \'ABCDEF\', \'GHIJK\')'
  conn1.querySync(stmt0.sql);
  
ibmdb.open(cn, function(err, conn2) {
    if (err) {
      //Something went bad
      console.log(err);

      //Let's not go any further
      return;
    }

    conn1.beginTransaction(function(err) {
      if (!err) {
        console.log('Transaction 1 opened');
          conn2.beginTransaction(function(err) {
            if (!err) {
              console.log('Transaction 2 opened');
              conn1.query(stmt1, function(err, data) {
                console.log('Query 1 executed');
                if (err) {
                  conn1.rollbackTransaction();
                  console.log(err);
                } else {
                  conn1.commitTransaction();
                  console.log('<<< DATA >>>:', data);
                }
              });

              conn2.query(stmt2, function(err, data) {
                console.log('Query 2 executed');
                if (err) {
                  conn2.rollbackTransaction();
                  console.log(err);
                } else {
                  conn2.commitTransaction();
                  console.log('<<< DATA >>>:', data);
                }
              });
            } else {
              console.log(err);
            }
          });
      } else {
        console.log(err);
      }
    });
  });
});
```

**Comment by kevindashgit** [comment]
Ya I spent the entire day today (wrote a tiny express app just for this) proving that ibm_db is acting up pretty badly. Multiple duplicate requests in rapid succession yeilds almost random results in terms of the latency that ibm_db introduces... like the first request takes about 30s, the next 1s, the next 2s, the next 9s etc... makes no sense at all. Running the same query directly on the database - it only takes 32ms 

¯\_(ツ)_/¯

**Comment by bimalkjha** [comment]
@qpresley @kevindashgit I am looking into it. Will update about findings soon. Thanks.

**Comment by kevindashgit** [comment]
I gave you access to it - check your @ibm.com email.

**Comment by bimalkjha** [comment]
Fix for this issue is pushed on github. Closing the issue now. Thanks.
