### ISSUE TITLE
Error during startup

### ISSUE THREAD

**Issue by crostonj** [ibmdb/node-ibm_db#212]
I get this error whenever I start my node project. 

	"Error: ENOENT: no such file or directory, stat 'D:\Projects\Node\Loans\node_modules\ibm_db\lib\package.json'
    at Error (native)
    at fs.existsSync (fs.js:264:13)
    at Function.getRoot (D:\Projects\Node\Loans\node_modules\bindings\bindings.js:153:9)
    at bindings (D:\Projects\Node\Loans\node_modules\bindings\bindings.js:55:32)
    at Object.<anonymous> (D:\Projects\Node\Loans\node_modules\ibm_db\lib\odbc.js:27:31)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)"

**Comment by rhtpandeyIN** [comment]
Hi @crostonj , the error you have posted is stating that "package.json" file is not present in your 'D:\Projects\Node\Loans\node_modules\ibm_db\lib\' directory. 
but which is actually true, package.json file should be outside lib\ directory not inside. ("\node_modules\ibm_db\package.json" something like that). Please can you comment here how you installed ibm_db module and which node version and OS you are using.

**Comment by crostonj** [comment]
Installed: npm install --save ibm_db
Node version: v6.3.0
OS: Windows 7 - 64 bit

**Comment by bimalkjha** [comment]
@crostonj Please use `npm install --save ibm_db@1.0.2` command and verify. Thanks.

**Comment by crostonj** [comment]
Did that and got the same:

"Error: ENOENT: no such file or directory, stat 'D:\Projects\Node\Payment\node_modules\ibm_db\lib\package.json'
    at Error (native)
    at fs.existsSync (fs.js:264:13)
    at Function.getRoot (D:\Projects\Node\Payment\node_modules\bindings\bindings.js:153:9)
    at bindings (D:\Projects\Node\Payment\node_modules\bindings\bindings.js:55:32)
    at Object.<anonymous> (D:\Projects\Node\Payment\node_modules\ibm_db\lib\odbc.js:27:31)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)"

**Comment by bimalkjha** [comment]
@crostonj Please share complete output of `npm install --save ibm_db@1.0.2` command. Thanks.

**Comment by crostonj** [comment]
Here is the verbose output:

npm verb gentlyRm don't care about contents; nuking D:\Projects\Node\Payment\node_modules\.staging\ibm_db-f7e074a9\node_modules
npm info lifecycle ibm_db@1.0.2~preinstall: ibm_db@1.0.2
npm info linkStuff ibm_db@1.0.2
npm verb linkBins ibm_db@1.0.2
npm verb linkMans ibm_db@1.0.2
npm info lifecycle ibm_db@1.0.2~install: ibm_db@1.0.2

> ibm_db@1.0.2 install D:\Projects\Node\Payment\node_modules\ibm_db
> node installer/driverInstall.js

Downloading DB2 ODBC CLI Driver from https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/ntx64_odbc_cli.zip...




Downloaded 100.00% (25824992 bytes)


****************************************
You are downloading a package which includes the Node.js module for IBM DB2/Informix.  The module is licensed under the Apache License 2.0. The package also includes IBM ODBC and CLI D
river from IBM, which is automatically downloaded as the node module is installed on your system/device. The license agreement to the IBM ODBC and CLI Driver is available in D:\Project
s\Node\Payment\node_modules\ibm_db\installer   Check for additional dependencies, which may come with their own license agreement(s). Your use of the components of the package and depe
ndencies constitutes your acceptance of their respective license agreements. If you do not accept the terms of any license agreement(s), then delete the relevant component(s) from your
 device.
****************************************

Download and extraction of DB2 ODBC CLI Driver completed successfully...

npm verb lifecycle ibm_db@1.0.2~install: unsafe-perm in lifecycle true
npm verb lifecycle ibm_db@1.0.2~install: PATH: C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin;D:\Projects\Node\Payment\node_modules\ibm_db\node_modules\.bin;D:\Project
s\Node\Payment\node_modules\.bin;C:\Program Files (x86)\nodejs;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Microsoft MPI\Bin\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System3
2\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\P
rogram Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\P
rogram Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementS
tudio\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\wbin;C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code;C:\Progr
am Files\Microsoft SDKs\Service Fabric\Tools\ServiceFabricLocalClusterManager;C:\Program Files (x86)\nodejs\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Windows Kits\10\Windows Per
formance Toolkit\;C:\Program Files\Amazon\AWSCLI\;C:\Program Files (x86)\Sennheiser\SoftphoneSDK\;C:\Program Files\dotnet\;C:\Program Files (x86)\Skype\Phone\;C:\Users\jcroston\.dnx\bi
n;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Program Files\Docker Toolbox;C:\Users\jcroston\AppData\Roaming\npm
npm verb lifecycle ibm_db@1.0.2~install: CWD: D:\Projects\Node\Payment\node_modules\ibm_db
npm info lifecycle ibm_db@1.0.2~postinstall: ibm_db@1.0.2
npm verb unlock done using C:\Users\jcroston\AppData\Roaming\npm-cache\_locks\staging-f6c828e1d59cfd06.lock for D:\Projects\Node\Payment\node_modules\.staging
npm verb saving [ { name: 'ibm_db', spec: '^1.0.2', save: 'dependencies' } ]
payment@1.0.0 D:\Projects\Node\Payment
`-- ibm_db@1.0.2

npm WARN payment@1.0.0 No description
npm WARN payment@1.0.0 No repository field.
npm verb exit [ 0, true ]
npm info ok

**Comment by bimalkjha** [comment]
@crostonj Seems, your node.js is installed correctly, so can you please update connection information in `ibm_db/test/config.testConnectionStrings.json` file and share output of `node test/test-basic-test.js` command? Thanks.

**Comment by crostonj** [comment]
I cannot run that script. I do not have enough permissions in the database.

**Comment by bimalkjha** [comment]
@crostonj Then copy that test file, modify it according to the permission and then run it. We just want from you to run a simple test program using the installed ibm_db. Or you can use a test script which just do connect with server and disconnect. If independent test program is working fine, then there should be some issue with application environment. Thanks.

**Comment by bimalkjha** [comment]
@crostonj you can execute `node test/test-connection-object.js` command. It just do connect and disconnect and no query execution. I think you should have permission to connect to the database. If you are no longer facing this issue, please confirm to close the issue. Thanks.
