### ISSUE TITLE
Need to process batch of Insert in dashDB

### ISSUE THREAD

**Issue by atulkumar-it** [ibmdb/node-ibm_db#215]
Hi,
I have a requirement to process a batch of Insert statements in dashdb and if some insert gives error and need to rollback all transaction otherwise commit. I tried ibm_db node modules but unable to resolve my problem. Could you please help me with some sample solution?

Thanks,
Atul

**Comment by bimalkjha** [comment]
@atulkumar-it Please share your test script to understand the repro the problem. thanks.

**Comment by atulkumar-it** [comment]
Hi Bimal,
Some code snippet as below:
First I am beginning the transaction-
    conn.beginTransaction()
    var stmt = conn.prepareSync("insert into mytable values(?, ?)"); // mytable (c1 int, c2 varchar(20))
Now having a loop where I am creating params and binding them to above query statement.
    stmt.bind(params);

Now my requirement is if we have any issue with executing any of statement and I have to rollback all statements otherwise will commit.
I tried multiple method -  stmt.executeSync() or conn.commitTransaction() or conn.rollbackTransaction() 
If i put any wrong insert (ex stmt.bind(['a', 'amit'])), it should rollback all previous transaction. But it doesn't rollback.

Can we do this using ibm_db node module?

Thanks,
Atul

**Comment by bimalkjha** [comment]
@atulkumar-it Check file ibm_db/test/test-prepareSync-multiple-execution.js . It is doing the same thing as you described and rollback seems working fine. Steps:
```
npm install ibm_db
cd node_modules/ibm_db/test
edit file config.testConnectionStrings.json and update connection information.
node test-prepareSync-multiple-execution.js
```
Thanks.

**Comment by atulkumar-it** [comment]
Bimal, In that test script, we are intentionally doing rollback for all transactions. Is there any way where we can do like - " while executing statements if there is some problem while inserting them to dashdb due to some data type error, then we do rollback. e.g.
stmt.execute(function (err, result) {
    if (err) {
        console.log(err);
        do rollback;
     } else {   
      do commit;
    }
}

**Comment by bimalkjha** [comment]
Yes, like that you can code. It should work. Check latest updated file https://github.com/ibmdb/node-ibm_db/blob/master/test/test-prepareSync-multiple-execution.js . Thanks.

**Comment by atulkumar-it** [comment]
Thanks Bimal. It works for me.
