### ISSUE TITLE
statement executes fires twice on error

### ISSUE THREAD

**Issue by huineng** [ibmdb/node-ibm_db#219]
I have this little code quite the same as the example.
I want to test error handling so the sql is an incorrect sql

```
conn.prepare(sql, (error: Error, stmt) => {
            console.info('prepare', error)
            if (error) {
                conn.closeSync();
                return callback(true, { message: error });
            }
            stmt.execute(params, (execerror, result) => {
                console.info('execute', execerror, result);
                if (execerror) {
                    conn.closeSync();
                    return callback(true, { message: execerror });
                } else {
                    result.closeSync();
                }
                conn.close(() => { return; });
                callback(false, true);
            });
        });
```

I log first the prepare ('prepare')
then i log the execute ('execute'

```
prepare null
execute Data is missing from 1485244662503 undefined
execute null ODBCResult { fetchMode: 4 }
``` 

as you can see the stmt.execute returns twice 
one with the "Data is missing from 1485244662503"
and then a second time

of course this produces a "Can't set headers after they are sent" error as it's supposed to only return something once..

I'm using node 1.0.0

**Comment by huineng** [comment]
to specify more this only happens when a table (that i'm trying to update) doesn't exist
it does not happen when the table exists but when the sql is wrong

**Comment by bimalkjha** [comment]
@huineng Please install ibm_db using `npm install ibm_db@1.0.2` OR `pm install git+https://git@github.com/ibmdb/node-ibm_db.git` command and check. Thanks.
