### ISSUE TITLE
API change broke compatibility - deprecate v1.0.2

### ISSUE THREAD

**Issue by tailsu** [ibmdb/node-ibm_db#221]
This commit changes the public API between 1.0.1 and 1.0.2:

https://github.com/ibmdb/node-ibm_db/commit/be4dbd9419c85dd54b0cd4b316cc7795cf8307ad

Because of that, our database processes broke. As per semver: Major version X (X.y.z | X > 0) MUST be incremented if any backwards incompatible changes are introduced to the public API.

**Comment by sam-github** [comment]
Generally, adding an extra trailing argument to a callback isn't considered semver major, because it is invisible:

```

fu(1,2,3)

function fu(a, b) {
  // doesn't know or care that it could receive an extra argument
```

If doing meta-programming by accessing the `arguments`, it is possible to notice the trailing arguments.

Was it only a trailing argument change, or did something else happen?

However, a new argument to a callback is a *feature*, and *must* be at least a minor, so that's definitely a semver violation.

**Comment by tailsu** [comment]
Oh no, no - the third argument was removed, not added :) Our client, which depended on the third argument to process multiple result-sets now doesn't work, because the third argument was removed and the semantics of the second argument got likewise changed.

**Comment by sam-github** [comment]
I read that diff backwards. Yes, that is definitely semver major!

**Comment by bimalkjha** [comment]
It was a non standard callback syntax reported by issue#113. Please go through issue #113 to know the details. I agree, existing application need to be changed but it would be simpler and according to node standards. Thanks.

**Comment by tailsu** [comment]
The change is a GOOD idea - I'm not against it.

Yet, you neglected proper API versioning and that broke existing installation is all I'm saying.

**Comment by tailsu** [comment]
Existing installations look for a version matching "^1.0.0", so far as I can tell. I suggest that you publish a 1.0.4 version without that breaking change and then 2.0.0 with that change. That way existing installations will continue to work and new installations will get the new goodies.

Although... That will break people who already use 1.0.2/1.0.3 with the new API...

Well, it's a mess.

**Comment by bimalkjha** [comment]
I think modifying the package.json to look only for 1.0.1 could also solve the issue like:

"ibm_db": "~1.0.1",

Yes, we are looking for a new release of ibm_db soon. Thanks.

**Comment by sam-github** [comment]
@bimaljha no, that tilde range would cause 1.0.2 to be installed, and 1.0.2 introduced an incompatible API change.

see https://github.com/npm/node-semver#tilde-ranges-123-12-1

also see http://semver.org/ and https://docs.npmjs.com/getting-started/semantic-versioning

A new release alone is not sufficient, the current release needs to be removed, or at least have the `latest` tag removed so it is no longer considered as a candidate by npm when searching for versions that match the depencency specification.

**Comment by ibmdb** [comment]
@sam-github I think just specifying the version in package.json like below should work:

"ibm_db" : "1.0.1"

https://docs.npmjs.com/files/package.json#git-urls-as-dependencies
"version Must match version exactly"

Also, we can add git-urls as dependency in package.json. Thanks.

**Comment by sam-github** [comment]
Once `2.0.0` is released, the 1.0.2 can be deprecated using https://docs.npmjs.com/cli/deprecate, so people will understand they should update.

> npm deprecate ibm_db@1.0.2 "1.0.2 was a major API change, please use 2.0.0 instead"

**Comment by sam-github** [comment]
@bimaljha any time estimate for when you will publish 2.x and deprecate 1.0.2?

**Comment by bimalkjha** [comment]
Can not deprecate v1.0.2 due to npm error. Many people has reported this issue in detail here: https://github.com/npm/npm/issues/15619

**Comment by bimalkjha** [comment]
Done. Tried to isntall 1.0.2 version and it is giving below message:
```
> npm install ibm_db@1.0.2
npm WARN deprecated ibm_db@1.0.2: 1.0.2 was a major API change, please use 2.0.0 instead
...
```
Thanks.
