### ISSUE TITLE
NSP 1 vulnerabilities found - Downloads Resources over HTTP

### ISSUE THREAD

**Issue by wallali** [ibmdb/node-ibm_db#223]
The project appears to be vulnerable to the following Node Security advisory

Downloads Resources over HTTP
https://nodesecurity.io/advisories/163

**Comment by bimalkjha** [comment]
@wallali This issue is a duplicate of closed issue #208. The fix is already available in ibm_db version 1.0.2. Now, ibm_db do not download resources over HTTP. Please check and feel free to close the issue. Thanks.

**Comment by bimalkjha** [comment]
@wallali This advisory is now updated with the remediation. Please check https://nodesecurity.io/advisories/163.  Thanks to contact@nodesecurity.io for quick action on my mail. Thanks.
