### ISSUE TITLE
ibmdb should be an orginization, not an individual user

### ISSUE THREAD

**Issue by sam-github** [ibmdb/node-ibm_db#224]
You will find it much easier to manage access and roles when it is an organization, info here:

- https://help.github.com/articles/what-s-the-difference-between-user-and-organization-accounts/
- https://help.github.com/articles/converting-a-user-into-an-organization/

**Comment by bimalkjha** [comment]
While trying to make ibmdb as organisation, github shows below warning:
```
Account transformation warning

What you are about to do is an irreversible and destructive process. Please be aware:
You will no longer be able to sign into ibmdb (all administrative privileges will be 
bestowed upon the owners you choose)
Any user-specific information (OAuth tokens, SSH keys, Job Profile, etc) will be erased
Any commits credited to ibmdb will no longer be linked to this GitHub account
If you are using ibmdb as a personal account, you should create a new personal 
account before transforming ibmdb into an organization.
```
Looking on above warning, I am afraid of loosing some unknown control or data. Thanks.

**Comment by bnoordhuis** [comment]
@bimalkjha What in particular are you afraid of?  The things GitHub warns for are what I would expect to happen when changing a personal account to an organization.

**Comment by sam-github** [comment]
Yep, that is exactly what you should see. Its an organization, you can't login as an organization, you'll have to login as an organization member, and as long as you have admin rights on your org (which you should, its yours), you will full control.

Note carefully:

> If you are using ibmdb as a personal account, you should create a new personal  account before transforming ibmdb into an organization.

But no one should be doing that, even now, unless by accident. And once you have converted ibmdb to an organization from a user, you won't even be able to accidentally commit as the `ibmdb` user anymore, and thats a good thing.

**Comment by bimalkjha** [comment]
Currently only ibmdb can publish ibm_db on npm and ibmdb has different credential from github. But, just want to confirm, making ibmdb an organization would cause any issue while publishing the ibm_db? Thanks.

**Comment by bnoordhuis** [comment]
The npm credentials are separate from GitHub so no issue there.

**Comment by bimalkjha** [comment]
Done!

**Comment by sam-github** [comment]
https://github.com/ibmdb looks great, thanks!
