### ISSUE TITLE
Informix docker returning SQL1042C

### ISSUE THREAD

**Issue by qpresley** [ibmdb/node-ibm_db#227]
I'm running on 12.10.FC8IE.  If you are interested in having a local environment you can run the following and see if it fails for you as well.

https://hub.docker.com/r/ibmcom/informix-innovator-c/

This should set up a docker container with informix running and ports 9088 (onsoctcp) and 9089 (drsoctcp).

So far I have been unable to connect through either a node.js app or a basic CLI app running through the client downloaded by ibm_db.  Unsure if I'm just missing something or if the client library downloaded with ibm_db is incompatible with this version of Informix.

**Comment by bimalkjha** [comment]
Use "Authentication=SERVER" in connection string. SQL1042C error will go away. Thanks.

**Comment by bimalkjha** [comment]
@qpresley Get the latest code from github and run [installer/ifx.sh](https://github.com/ibmdb/node-ibm_db/blob/master/installer/ifx.sh) script. ibm_db should work after that.

If it fails to connect to dev server, execute "/opt/IBM/informix/bin/dbaccessdemo" and connect to stores_demo database. Thanks.

**Comment by qpresley** [comment]
AUTHENTICATION=SERVER worked.  Will run the latest later.
