### ISSUE TITLE
Reduce package size from ~100MB for OpenWhisk/dashDB compatibility

### ISSUE THREAD

**Issue by kennu** [ibmdb/node-ibm_db#229]
The final installed package size of ibm_db is very big, ~100 MB on macOS and ~85 MB on Linux. This makes it impossible to deploy applications to IBM Bluemix OpenWhisk, because the size limit there is 48 MB.

**Comment by bimalkjha** [comment]
@kennu We have reduced the size of installed package to `~67MB` on Mac and Linux. Code changes are available on github. This is the minimum size that can be achieved. 
Size of downloaded ODBC/CLI driver is itself around 63MB where size of `libdb2.dylib` is ~30MB and size of `gskit libraries` are ~20MB.
You can avoid this download of clidriver and get installed package size to ~4MB by setting environment variable `IBM_DB_HOME` to a preinstalled clidriver folder. i.e. once you have downloaded package of ~67MB, copy `ibm_db/installer/clidriver` folder to some other location like $HOME. Then run `"export IBM_DB_HOME=<$HOME/clidriver>"` command to set the env variable. You can also set `IBM_DB_HOME` to any other preinstalled db2 client/server directory too. Now reinstall ibm_db. Size of new installed ibm_db would be around 4MB only. Hope, it will help. Thanks.

**Comment by kennu** [comment]
Thanks for your optimization and instructions! But does this mean that the driver can never be used in IBM OpenWhisk? :-( In my own experiments, OpenWhisk deployments actually failed unless I got the total size to be under 40MB, and even then there seemed to be some kind of startup error possibly related to running out of memory. (Either that or I messed up the binaries somehow.)

**Comment by bimalkjha** [comment]
@kennu ibm_db can work on OpenWhisk if size limit of OpenWhisk can be increased to 100MB. Even you can not install any DB2 Client driver on OpenWhisk! Also, ibm_db is supported only for those platform where we can install [IBM Data Server Driver Package](https://www-945.ibm.com/support/fixcentral/swg/selectFixes?parent=ibm%7EInformation%2BManagement&product=ibm/Information+Management/IBM+Data+Server+Client+Packages&release=11.1.*&platform=All&function=fixId&fixids=*-dsdriver*FP001*&includeSupersedes=0&source=fc). Thanks.

**Comment by kennu** [comment]
Okay thanks. If I understand right, Bluemix OpenWhisk would need to add special driver support into the platform, in order to make ibm_db work. And I didn't find any other way to connect to dashDB. :-(
