### ISSUE TITLE
Trusted context support

### ISSUE THREAD

**Issue by victorfando** [ibmdb/node-ibm_db#23]
Is it possible to switch users on a trusted context connection using something like SQLSetConnectAttr in CLI/ODBC applications?

Thanks

**Comment by mariobriggs** [comment]
Hi victorfando
 Sorry for late reply. No currently that feature is not supported, we can add it to our list of todo things. If you can provide any info about details about your usage here and if we see others also request for this feature, then we can take it up.

**Comment by rhtpandeyIN** [comment]
Your point is well taken and if we see others also requesting for this feature, then we can take it up. closing issue for now.
Thanks for your time and efforts.
