### ISSUE TITLE
Using arrays to pass parameter values

### ISSUE THREAD

**Issue by amcintyre99** [ibmdb/node-ibm_db#233]
I first mistakenly posted the DB2 z/OS doc link, so changed to this LUW link:
https://www.ibm.com/support/knowledgecenter/SSEPGG_11.1.0/com.ibm.db2.luw.apdv.cli.doc/doc/r0002218.html

It says on that page:
Specifying an array of input parameter values when SQLSetStmtAttr() with the SQL_ATTR_PARAMSET_SIZE attribute is used in conjunction with SQLBindParameter().

Do you support passing arrays?

thanks!!

**Comment by bimalkjha** [comment]
@amcintyre99 Currently array input is not supported by ibm_db. There is no ibm_db api to set statement attribute SQL_ATTR_PARAMSET_SIZE. Thanks.

**Comment by yo34** [comment]
This means that this is not working ?

var variables=[];
variables.push(2);
var rows = conn.querySync("select * from customers where id='?'", variables);

**Comment by bimalkjha** [comment]
@yo34 It is working. You can run `ibm_db\test\test-basic-test.js` file to see how it is working. Check this line: https://github.com/ibmdb/node-ibm_db/blob/master/test/test-basic-test.js#L54

In your query, ? is enclosed by quote, but it should not. Below query would work:
`var rows = conn.querySync("select * from customers where id=?", variables);`
Thanks.

**Comment by amcintyre99** [comment]
I believe @yo34 asked a question related to a single element array passed to a parameter marker.

My original question was related to multiple elements passed to a single parameter marker which I believe would require ibm_db to set SQL_ATTR_PARAMSET_SIZE which you said you don't do.

**Comment by Akshay3583** [comment]
Hi Team,

Even I tried passing an array to DB2 SP from NodeJS. But DB2 is always taking the first element of an array. Is it allowed to pass an array to DB2 SP from NodeJS?

**Comment by bimalkjha** [comment]
@Akshay3583 Its an enhancement request still open. In your SP use a parameter marker (?) for every member of array, i.e. if array has 3 elements, use 3 markers, then it should work. Thanks.

**Comment by Akshay3583** [comment]
@bimaljha  I tried doing same. But it's not working. Below is the screenshot of code which I am using. Could you please help me with this.
![image](https://user-images.githubusercontent.com/54398226/67780090-980e8f80-fa8b-11e9-8f43-927ee340f244.png)

**Comment by Akshay3583** [comment]
> @bimaljha I tried doing same. But it's not working. Below is the screenshot of code which I am using. Could you please help me with this.
> ![image](https://user-images.githubusercontent.com/54398226/67780090-980e8f80-fa8b-11e9-8f43-927ee340f244.png)

I tried passing values directly to bindParams array like bindParams = [8,9] & used 2 ?, even that approach is not working

**Comment by bimalkjha** [comment]
> > @bimaljha I tried doing same. But it's not working. Below is the screenshot of code which I am using. Could you please help me with this.
> > ![image](https://user-images.githubusercontent.com/54398226/67780090-980e8f80-fa8b-11e9-8f43-927ee340f244.png)
> 
> I tried passing values directly to bindParams array like bindParams = [8,9] & used 2 ?, even that approach is not working

@Akshay3583 in conn.query, just pass arr instead of bindParams. Thanks.

**Comment by Akshay3583** [comment]
@bimalkjha I already tried this approach. Even that is not working. I am just wondering that this is so common use case, how come it's not supported by this module. Please let me know if you know any alternate way of doing this.

**Comment by bimalkjha** [comment]
@Akshay3583 Please share the create procedure query for NOTIFY_TEST_PORTAL sp. It must be expecting something different. Good to share test code in text format rather in picture format.
You can also refer to our test case for SP where SP is called with two parameter markers: https://github.com/ibmdb/node-ibm_db/blob/master/test/test-sp-resultset-execute.js#L15
If your SP is expecting single array with two element as argument, then that is not supported in ibm_db as of now. Thanks.

**Comment by DarekDan** [comment]
You are trying to pass an array into a single value parameter. DB2 does not support TABLE VALUED parameters, but it does support arrays just fine for IN predicates for example. You should create a prepared statement and run it for each element of the array.

**Comment by amcintyre99** [comment]
Hey thanks for the update!

I will do some testing comparing my current code:
xmltable with xmlparse and single ? passed an xml string that's multi column and multi row
vs
your new array support with arrays passed to multiple ?

Curious to see which is faster.

Andrew

**Comment by amcintyre99** [comment]
I was looking at your latest update to the array feature and noticed that you assume that all 4 of your param markers have the same arraysize. What if they have different sizes?

Andrew

**Comment by bimalkjha** [comment]
@amcintyre99 Array insert of different sizes are not supported. To update all columns in a row, all arrays must of of same size or at least the number of elements in each array must be equal to the ArraySize parameter used in query() API. Only the values up to ArraySize will get considered.
As per [IBM documentation](https://www.ibm.com/support/knowledgecenter/SSEPGG_11.5.0/com.ibm.db2.luw.apdv.cli.doc/doc/t0007268.html): `Each array must contain at least SQL_ATTR_PARAMSET_SIZE elements, otherwise, memory access violations may occur.`
Thanks.

**Comment by bimalkjha** [comment]
@amcintyre99 @yo34 @DarekDan We have released ibm_db@2.7.0 with support of array insert. Please go through the documentation and test file [test-array-insert.js](https://github.com/ibmdb/node-ibm_db/blob/master/test/test-array-insert.js) to see its usage and example. Let me know if you face any issue. I am closing this issue now. Thanks.

**Comment by amcintyre99** [comment]
Re arrays of different sizes. Remember not all SQL is an INSERT.

So are you saying this won't work where the arrays are of different sizes?
```sql
with
  t1 (c1) as
    (values ?),
  t2 (c2) as
    (values ?)
select c1,c2
  from t1,t2
```

**Comment by bimalkjha** [comment]
@amcintyre99 Using IBM ODBC driver, Array is supported only in Insert, Delete and Update statements. So, only first value from the array will get considered if you use array in your shared sql.

Array Support in ibm_db is implemented as Column-wise Array input as documented [here](https://www.ibm.com/support/producthub/db2/docs/content/SSEPGG_11.5.0/com.ibm.db2.luw.apdv.cli.doc/doc/t0007268.html). 

https://www.ibm.com/support/producthub/db2/docs/content/SSEPGG_11.5.0/com.ibm.db2.luw.apdv.cli.doc/doc/c0007140.html
An application cannot place parameter markers in the listed locations:
In a SELECT list
As both expressions in a comparison-predicate
As both operands of a binary operator
As both the first and second operands of a BETWEEN operation
As both the first and third operands of a BETWEEN operation
As both the expression and the first value of an IN operation
As the operand of a unary + or - operation
As the argument of a SET FUNCTION reference

Thanks.

**Comment by amcintyre99** [comment]
My actual code is like below. The two xml strings have different numbers of columns and the row count varies. It's a great way to get many values into SQL with single param markers.

I guess I can't use your new support. I was hoping to see if it used less cpu than the xml functions.
```sql
select .....
    from ..... ,
            xmltable('$s/p/r' passing xmlparse(document cast(? as varchar(32000))) as "s"
                ... ,
            xmltable('$s/p/r' passing xmlparse(document cast(? as varchar(32000))) as "s"
               ... 
```

**Comment by sugumarworkspace** [comment]
> @amcintyre99 @yo34 @DarekDan We have released ibm_db@2.7.0 with support of array insert. Please go through the documentation and test file [test-array-insert.js](https://github.com/ibmdb/node-ibm_db/blob/master/test/test-array-insert.js) to see its usage and example. Let me know if you face any issue. I am closing this issue now. Thanks.

Hi @bimalkjha, Can we use the same technique to call procedures also? 
Eg., conn.prepareSync(`CALL SP_TEST_PROC(?, ?)`) and pass arrays as parameters.

**Comment by bimalkjha** [comment]
@sugumarworkspace Yes, we use the same technique to call procedures also. Thanks.

**Comment by bridgettepepper** [comment]
Hi @bimaljha I hope this issue is still being monitored as I have a question about passing an array of data into sql statement to update my DB2. This is my first time working DB2 and SQL so still working to understand...I have a node.js app using the ibm_db package, and I get 'DBData' from my front-end and I want to execute an UPDATE query into my db2. I am having a hard time understanding how to do that or if it is possible with 2 array params into a single sql statement.. 

paramsArray var looks like [ 'geo', 'user_email@ibm.com' ] on console log and i want to use 'geo' as lpad_default and 'user_email@ibm.com' as user_email. I tried a couple of different ways with the ? in the queryStr but each time I try and execute the query, I get an sql error. 
Code is below:

```
const updateLaunchpadDefault = async (DBdata) => {
    try {
        const client = await db.getDBClient();
        console.log('client', client);
        const paramsArray = db.prepQueryParams(DBdata);
        const queryStr= "UPDATE <DB/Table> SET lpad_default=? WHERE user_email=?";
        console.log('paramsArray', paramsArray);
        console.log('queryStr', queryStr);
        const res = await db.executeQuery(client, queryStr, paramsArray);
        console.log('res', res);
        await db.closeClient(client);
    }
    catch (error) {
        return error;
    }
};
```

**Comment by bimalkjha** [comment]
@bridgettepepper This issue is closed. Please open a new issue for yourself.
In new issue mention the value of `res` and implementation of db.executeQuery() as it is not an `ibm_db` api. Please check [here](https://github.com/ibmdb/node-ibm_db/blob/master/APIDocumentation.md) to see the list of ibm_db APIs and its usage with example. Thanks.
