### ISSUE TITLE
`npm rebuild` fails if folder permissions are not set correctly

### ISSUE THREAD

**Issue by kloener** [ibmdb/node-ibm_db#235]
Hi,

I get an error if I've installed the ibm_db package and call `npm rebuild` afterwards. 
The error message:

> Downloading DB2 ODBC CLI Driver from http://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli//macos64_odbc_cli.tar.gz...
> { Error: EACCES: permission denied, open '/..fullpath.../node_modules/ibm_db/installer/clidriver/msg/en_US.iso88591/db2adm.mo'
>   cause: 
>    { Error: EACCES: permission denied, open '/..fullpath.../node_modules/ibm_db/installer/clidriver/msg/en_US.iso88591/db2adm.mo'
>      errno: -13,
>      code: 'EACCES',
>      syscall: 'open',
>      path: '/..fullpath.../node_modules/ibm_db/installer/clidriver/msg/en_US.iso88591/db2adm.mo' },
>   isOperational: true,
>   errno: -13,
>   code: 'EACCES',
>   syscall: 'open',
>  path: '/..fullpath.../node_modules/ibm_db/installer/clidriver/msg/en_US.iso88591/db2adm.mo' }

Solution for me: `chmod -R +w node_modules/ibm_db/installer`. May be you can automate this step after you download odbc_cli.

Using Node 7.7.2 and NPM 4.1.2 on macOS Sierra.

kind regards,
Christian

**Comment by rhtpandeyIN** [comment]
issue addressed in the latest pull request and will merge soon.
