### ISSUE TITLE
electron-rebuild - Cannot open include file: 'sqlcli1.h'

### ISSUE THREAD

**Issue by kloener** [ibmdb/node-ibm_db#236]
Hi,

I've tried to rebuild the node modules for electron with `node_modules/.bin/electron-rebuild --target=1.5.1 --arch=x64` but I get the following error message:

On a windows 10 (x64) machine:

> Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
>   odbc.cpp
> c:\users\ieuser\desktop\myapp\node_modules\ibm_db\src\odbc.h(30): fatal error C1083: Cannot open include file: 'sqlcli1.h': No such file or directory [C:\Users\IEUser\Desktop\myapp\node_modules\ibm_db\build\odbc_bindings.vcxproj]
>   odbc_connection.cpp
> c:\users\ieuser\desktop\myapp\node_modules\ibm_db\src\odbc.h(30): fatal error C1083: Cannot open include file: 'sqlcli1.h': No such file or directory [C:\Users\IEUser\Desktop\myapp\node_modules\ibm_db\build\odbc_bindings.vcxproj]
>   odbc_statement.cpp
> c:\users\ieuser\desktop\myapp\node_modules\ibm_db\src\odbc.h(30): fatal error C1083: Cannot open include file: 'sqlcli1.h': No such file or directory [C:\Users\IEUser\Desktop\myapp\node_modules\ibm_db\build\odbc_bindings.vcxproj]
>   odbc_result.cpp
> c:\users\ieuser\desktop\myapp\node_modules\ibm_db\src\odbc.h(30): fatal error C1083: Cannot open include file: 'sqlcli1.h': No such file or directory [C:\Users\IEUser\Desktop\myapp\node_modules\ibm_db\build\odbc_bindings.vcxproj]
>   dynodbc.cpp
>   win_delay_load_hook.cc
> gyp ERR! build error
> gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1

On macOS Sierra (x64) the same issue:

> gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
>   CXX(target) Release/obj.target/odbc_bindings/src/odbc.o
> In file included from ../src/odbc.cpp:25:
> ../src/odbc.h:30:10: fatal error: 'sqlcli1.h' file not found
> #include <sqlcli1.h>
>          ^
> 1 error generated.
> make: *** [Release/obj.target/odbc_bindings/src/odbc.o] Error 1
> gyp ERR! build error 
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/Users/theuser/.nvm/versions/node/v7.7.2/lib/node_modules/electron-rebuild/node_modules/node-gyp/lib/build.js:285:23)
> gyp ERR! stack     at emitTwo (events.js:106:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
> gyp ERR! System Darwin 16.4.0
> gyp ERR! command "/Users/theuser/.nvm/versions/node/v7.7.2/bin/node" "/Users/theuser/.nvm/versions/node/v7.7.2/lib/node_modules/electron-rebuild/node_modules/.bin/node-gyp" "rebuild" "--target=1.5.1" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source"
> gyp ERR! cwd /Users/theuser/Documents/myapp/node_modules/ibm_db
> gyp ERR! node -v v7.7.2
> gyp ERR! node-gyp -v v3.6.0
> gyp ERR! not ok 
> 
> Failed with exit code: 1

Even if I only call `node-gyp rebuild --arch=x64` in the "node_modules/ibm_db" folder it fails with the same error.

How can I fix that?

Both machines have:
Node v7.7.2
NPM v4.1.2
node-gyp@3.6.0
electron v1.5.1
electron-rebuild v1.5.7

kind regards
Christian

**Comment by rhtpandeyIN** [comment]
Hi @kloener , do you have clidriver installed in your IBM_DB_HOME path? you will need that before building node-ibm_db.
Also if you already have that could you please confirm - is there any "include" folder inside clidriver or not?

**Comment by kloener** [comment]
Thanks for your fast reply :) This solved my problem!

> cd node_modules/ibm_db/installer/clidriver
> export IBM_DB_HOME=$(pwd) 
> cd ../..
> node-gyp rebuild --arch=x64

The `include` folder is present, too.

Thanks

**Comment by amangrover1** [comment]
Hi @rhtpandeyIN I am trying to rebuild the ibm_db but there is no "include" folder inside clidriver. Any suggestion?

**Comment by rhtpandeyIN** [comment]
Hi @amangrover1 , I think you are using Windows platform, that's why you didn't get include directory inside clidriver package. Please download linux clidriver package from the same IBM provided URL for download clidriver, and then copy "include" folder from that place to your existing clidriver package. Thanks

**Comment by amangrover1** [comment]
thanks, @rhtpandeyIN Yes I am using Windows Platform and after your suggestion able to re-build the package but now while running query I am getting [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified, errorSQLState=IM002

Earlier I was able to query for with integers and were getting code conversion error.

I updated binding.gyp in order to remove "UNICODE" and set "DEBUG" there.

'defines' : [
        "DEBUG"
      ],

I followed steps documented at https://github.com/ibmdb/node-ibm_db/blob/master/INSTALL.md#inswin

Please advice.

**Comment by amangrover1** [comment]
Hi @rhtpandeyIN , Thanks for your help it worked for. I missed one entry in my first attempt. Thanks a lot
