### ISSUE TITLE
built electron application on windows results in "specified module could not be found"

### ISSUE THREAD

**Issue by kloener** [ibmdb/node-ibm_db#239]
Hi,

I use ibm_db on my Mac and everything works fine. 
On Windows I recently got it working with `electron myProject` (for debugging only). 

But if I try to build an executable out of my electron project with "electron-builder" and the command `npm run build -w --x64`, I get an error when I try to open the created windows application (see attached image)
![bildschirmfoto 2017-03-27 um 15 44 57](https://cloud.githubusercontent.com/assets/737537/24360033/618c6cb2-1306-11e7-9fdc-10229769afdf.png)

What I did:
- `npm install` works
- copied "include" folder (from clidriver-linux zip) to ibm_db/installer/clidriver
- set IBM_DB_HOME path
- `electron-rebuild --arch=x64 --target=1.5.1` worked
- `npm rebuild` worked
- `cd node_modules/ibm_db/ && node-gyp rebuild` worked
- `npm run build -w --x64` **fails**, see error message below
- `cd node_modules/ibm_db/ && node-gyp configure build --IBM_DB_HOME=$IBM_DB_HOME --IS_DOWNLOADED=true` worked
- `npm run build -w --x64` **fails**, see error message below
- manually zipped ibm_db/build to build.zip
- `npm run build -w --x64` worked, but application **fails**.

Error message when I call `npm run build` without creating a "build.zip" in ibm_db-folder by myself:
> node installer/driverInstall.js
> IBM_DB_HOME environment variable have already been set to C:/Users/IEUser/Desktop/myproject/node_modules/ibm_db/installer/clidriver/
> Error output:
> events.js:163
>      throw er; // Unhandled 'error' event
>      ^
> Error: ENOENT: no such file or directory, open 'C:\Users\IEUser\Desktop\myproject\node_modules\ibm_db\build.zip'

What else can I do? Any idea?
What should the build.zip contain? 

Using
electron@1.5.1
electron-builder@13.11.1
electron-rebuild@1.5.7
node@7.7.4
npm@4.1.2
ibm_db@2.0.0

and Windows 10 

kind regards
Christian

**Comment by rhtpandeyIN** [comment]
Hi @kloener ,
Well build.zip contains the latest pre-compiled windows node binaries, and the time you install ibm_db, installer automatically downloads the corresponding node binary for the particular node version.  

So my first suggestion is: unless or until you haven't made any particular changes in ".c" program files there is no need to build the node-ibm_db (as you are already getting the pre-compiled binaries, and you can directly use them).

And if you want to manually build the module then you can follow the below link for instructions:
https://github.com/ibmdb/node-ibm_db/blob/master/INSTALL.md#inswinbld

feel free to contact if stuck somewhere :)

**Comment by kloener** [comment]
Thanks for your fast reply :-) 

I did not make any changes to the .c-files, but electron rebuilds all native modules when I try to build an executable. Without the build.zip the above mentioned error occurs. 

I found the build.zip in this repository and copied it to node_modules/ibm_db before I run "build -w". The build process succeeded, but it doesn't work inside the electron application (same error as in posted image above).

Again, I deleted node_modules completly, called `npm install`, downloaded the build.zip from github and called `build -w --x64`. After that I run the application and get that error message in the web-console.

> Uncaught Error: The specified module could not be found.
> \\\\?\C:\Users\IEUser\Desktop\MYPROJECT\dist\win-unpacked\resources\app.asar.unpacked\node_modules\ibm_db\build\Release\odbc_bindings.node
>     at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
>     at Object.Module._extensions..node (module.js:598:18)
>     at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
>     at Module.load (module.js:488:32)
>     at tryModuleLoad (module.js:447:12)
>     at Function.Module._load (module.js:439:3)
>     at Module.require (module.js:498:17)
>     at require (internal/module.js:20:19)
>     at bindings (C:\Users\IEUser\Desktop\MYPROJECT\dist\win-unpacked\resources\app.asar\node_modules\bindings\bindings.js:76:44)
>     at C:\Users\IEUser\Desktop\MYPROJECT\dist\win-unpacked\resources\app.asar\node_modules\ibm_db\lib\odbc.js:27:31
>     at Object.<anonymous> (C:\Users\IEUser\Desktop\MYPROJECT\dist\win-unpacked\resources\app.asar\node_modules\ibm_db\lib\odbc.js:1770:2)

Is the beginning of the path an issue? `\\?\C:\Users\...\ibm_db\build\Release\odbc_bindings.node`. Why is there a question mark?

On macOS it works without copying any file.
Is there any other step I'm missing for using ibm_db with electron on windows?

kind regards and thanks for the help!

**Comment by kloener** [comment]
I've created an example repository for testing: https://github.com/kloener/ibm-db-electron
There is exact the same behaviour: on macOS it works, on Windows it fails without build.zip and afterwards.

If I try to start electron (npm start) after install, there is an error. `electron-rebuild` helps for that issue on windows. After the rebuild I can start electron and ibm_db is accessable. For each rebuild I've to put the build.zip in the ibm_db folder again.

**But** when I try to build the executable on windows (npm run build:win) the executable starts with the error in the console (see image from first post).

Hope this helps to reproduce the issue.

**Comment by rhtpandeyIN** [comment]
Pull request #278 addressed this issue.

**Comment by diimallya** [comment]
I too had same error, after setting "%IBM_DB_HOME%\bin" path in "PATH" where IBM_DB_HOME directory path being ntx64_odbc_cli\clidriver, the error was resolved.

**Comment by rhtpandeyIN** [comment]
Hi @diimallya , are you using node-ibm_db with "Electron" ?

**Comment by diimallya** [comment]
No. I was using node-ibm_db for simple helloworld program ( https://github.com/IBM-Bluemix/dashdb-nodejs-helloworld) to test connectivity and was facing this error (The specified module could not be found)
