### ISSUE TITLE
support for create database?

### ISSUE THREAD

**Issue by seayerktai** [ibmdb/node-ibm_db#240]
Hi there,

I am facing an problem that I will need to create the database first before connect to it. use it, and delete it afterward.

For example, if i do this in command line

$ db2 create database sample
--database "sample" create successfully
$ db2 connect to sample
$ db2 select.........

--after all the query
$ db2 drop database sample

I check through the api and cannot find any way to do this. Is this operation possible by using this module?

**Comment by bimalkjha** [comment]
@seayerktai No, ibm_db driver do not support create database. You need to use CLP only to create database as you pasted the commands. Thanks.

**Comment by rhtpandeyIN** [comment]
Issue Addressed with the latest pull request commit : 
CreateDbSync() and dropDbSync() api support. (#341)
