### ISSUE TITLE
streaming query errors

### ISSUE THREAD

**Issue by volkmarbuehringer** [ibmdb/node-ibm_db#241]
during streaming the large query delivers an error:

Error: [IBM][CLI Driver] CLI0115E  Invalid cursor state. SQLSTATE=24000
    at Error (native)

   function select_stream(sql,fun) {
     return new Promise( (resolve, reject) => {
       ibmdb.open(cn,  (err,conn)=> {
         if (err) {
           conn.close();
           return reject(err);
         }
        const stream= conn.queryStream( sql, []);
        stream.on("data",  fun )
        .once("error", (err)=> {
          console.error("errorstream",err);
          conn.closeSync();
       return reject(err);
        })
        .once("end",  ()=> {
          conn.closeSync();
           return resolve({});
        });
   });
       });
   }

**Comment by bimalkjha** [comment]
@volkmarbuehringer Could you please clarify what do you mean by large query? Is it very large SQL statement or a query that returns large result set/no of rows? Please share your sql statement if possible. Thanks.

**Comment by kathywang** [comment]
I get the same error, I am connecting to bluemix dashDB, when expected queryStream result 1 million rows I get this error, I never be able to get complete 1 million rows data, 400 rows 193 columns is the most I get.
Also querystream response is slow, is there any suggestions can improve performance that 3 million rows with 193 columns can be streamed within 3 minutes?

**Comment by kathywang** [comment]
Another case for this error, when sql has " fetch first N rows only", it will trigger the cursor error.

**Comment by rhtpandeyIN** [comment]
Hi @volkmarbuehringer , @kathywang could you please follow up issue #250 and confirm the changes.
Thanks.

**Comment by rhtpandeyIN** [comment]
Closing the issue now, possible duplicate of issue #250 (Solution given for that). 
If you have further queries please feel free to reopen it again.
Thanks:
Rohit Pandey.
