### ISSUE TITLE
support for store procedure creation

### ISSUE THREAD

**Issue by seayerktai** [ibmdb/node-ibm_db#242]
Hi There,

I looks through the code and can not find the correct api to create the store procedure.

The code I am using is 

 var ibmdb = require('ibm_db');

 ibmdb.open("DATABASE=<dbname>;HOSTNAME=<myhost>;UID=db2user;PWD=password;PORT=<dbport>;PROTOCOL=TCPIP", function (err,conn) {
   if (err) return console.log(err);
  
   conn.query('CREATE PROCEDURE DBO.SIMPLESELECT  ()\nLANGUAGE SQL\nBEGIN\n    select 1 from sysibm.sysdummy1;\nEND', function (err, data) {
     if (err) console.log(err);
     else console.log(data);
 conn.close(function () {
      console.log('done');
    });
   });
 });

The error I got is 
{ [Error: [IBM][CLI Driver][DB2/LINUXX8664] SQL0104N  An unexpected token "select 1 from sysibm.sysdummy1;" was found following "ANGUAGE SQL  BEGIN  ".  Expected tokens may incl
ude:  "<delete>".  LINE NUMBER=6.  SQLSTATE=42601
]
  errors: [],
  error: '[node-ibm_db] SQL_ERROR',
  message: '[IBM][CLI Driver][DB2/LINUXX8664] SQL0104N  An unexpected token "select 1 from sysibm.sysdummy1;" was found following "ANGUAGE SQL  BEGIN  ".  Expected tokens may in
clude:  "<delete>".  LINE NUMBER=6.  SQLSTATE=42601\r\n',
  state: '42601' }

It complain about the syntax, but i think my code is fine, it just the driver does not parse the create procedure correctly.

Am I missing something?

**Comment by bimalkjha** [comment]
@seayerktai There are 4 test cases for stored procedure under ibm_db/test folder. Please check https://github.com/ibmdb/node-ibm_db/blob/master/test/test-sp-resultset.js that creates SP with result set.

Your create statement does not seems correct as it fails using CLP too. Please use the correct SQL to create procedure.
```
$ db2 connect to sample

   Database Connection Information

 Database server        = DB2/LINUXX8664 10.5.8
 SQL authorization ID   = BIMALJHA
 Local database alias   = SAMPLE

$ db2 "CREATE PROCEDURE DBO.SIMPLESELECT () LANGUAGE SQL BEGIN  select 1 from sysibm.sysdummy1; END"
DB21034E  The command was processed as an SQL statement because it was not a 
valid Command Line Processor command.  During SQL processing it returned:
SQL0104N  An unexpected token "sysibm" was found following "BEGIN  select 1 
from".  Expected tokens may include:  "INTO".  LINE NUMBER=1.  SQLSTATE=42601
$
```
Your syntax is correct or not, you can verify using any other client like CLP or CLPPlus. Thanks.
