### ISSUE TITLE
db2 CLI trace no longer seems to work

### ISSUE THREAD

**Issue by qpresley** [ibmdb/node-ibm_db#244]
In previous releases there was a db2cli.ini.sample file in installer/clidriver/cfg and by moving this to db2cli.ini or creating your own db2cli.ini file in this directory I could generate a CLI trace which was very useful in debugging issues.  This appears to no longer work.  Can someone have a look into why?

**Comment by bimalkjha** [comment]
@qpresley CLI Trace is working fine as before. You can create your own db2cli.ini file using any editor and have previous trace entries. Thanks.

**Comment by qpresley** [comment]
@bimaljha I've been unable to get this to work for multiple weeks now.  Also, where did the db2cli.ini.sample file go from installer/clidriver/cfg?

**Comment by bimalkjha** [comment]
db2cli.ini.sample file is removed to reduce the space as it is not required for clidriver to work. You can create db2cli.ini file using vi editor. The .sample file is not required. If you are unable to get CLI trace using db2cli.ini file too, please share the contents of db2cli.ini file. You can also verify your db2cli.ini file is correct or not using `db2cli validate` command. Thanks.

**Comment by qpresley** [comment]
Works now.  Closing.  FWIW, validate showed no errors.  Now I can't get it to stop working so I'll close for now.
