### ISSUE TITLE
Error with conn.query

### ISSUE THREAD

**Issue by hem1980** [ibmdb/node-ibm_db#245]
I am getting following error when calling a stored procedure with parameters:-

 "error": "[node-ibm_db] SQL_ERROR",
  "message": "[IBM][CLI Driver] CLI0111E  Numeric value out of range. SQLSTATE=22003",
  "state": "22003"

Same code works fine on my windows 10 environment but I get the error on my Docker-Linux environment.

**Comment by bimalkjha** [comment]
@hem1980 Please execute `node ibm_db/test/test-sp-resultset.js` file to see how SP is working. You need to update connection info in file test/config.testConnectionStrings.json before that. All SP related test cases are working fine. If test-sp-resultset.js is working fine for you, please share your test file to repro the issue. Thanks.

**Comment by hem1980** [comment]
I get below error on conn.query("insert into " + schema + ".mytab1 values (2, 'bimal'), (3, 'kumar')"  statement itself


Error {errors: Array[0], error: "[node-ibm_db] SQL_ERROR", message: "[IBM][CLI Driver][AS] SQL7008N  REXX variable "MYT…", state: "55019"}
error:"[node-ibm_db] SQL_ERROR"
errors:Array[0] []
message:"[IBM][CLI Driver][AS] SQL7008N  REXX variable "MYTAB1    " contains inconsistent data.  SQLSTATE=55019\r\n"
stack:"Error: [IBM][CLI Driver][AS] SQL7008N  REXX variable "MYTAB1    " contains inconsistent data.  SQLSTATE=55019\r\n\n    at Error (native)"
state:"55019"
__proto__:Error: [IBM][CLI Driver][AS] SQL7008N  REXX variable "MYTAB1    " contains inconsistent data.  SQLSTATE=55019\r

**Comment by bimalkjha** [comment]
@hem1980 Error SQL7008N is coming from server. ibm_db has nothing to do with it. Please check with your DBA why server is throwing error for your query. You can try executing the query using some other client too like DB2 or JCC driver. Thanks.
