### ISSUE TITLE
queryStream run 3 times get "Abort trap": 6 error

### ISSUE THREAD

**Issue by kathywang** [ibmdb/node-ibm_db#248]
Same code with queryStream, first two times work fine the third execution throw error and crush:
Invalid Handle: SQLGetData retrun code = -2, stmt handle = 1:1, columnType = 12, index = 1
Assertion failed: (ret != SQL_INVALID_HANDLE), function GetColumnValue, file ../src/odbc.cpp, line 609.
Abort trap: 6
getListStream: function(req, res) {
        //add encoding utf-8
        var No = 0, str ='';
        var ibmdb = require("ibm_db")
        try{
            var cn = "DATABASE=dbname;HOSTNAME=hostname;PORT=port;PROTOCOL=TCPIP;UID=dbuser;PWD=xxx";
            ibmdb.open(cn, {"fetchMode": 3}, function(err, conn)
            {
                try {
                    var stream = conn.queryStream("select * from customer_profile where Age = 20 and CHURN_IND in ('0') ");
                    stream.setEncoding('utf8');
                    res.writeHead(200, {'Content-Type': 'text/csv; charset=utf-8',
                                        'Transfer-Encoding': 'chunked',
                                        'Cache-Control': 'no-cache',
                                        'Content-disposition': 'attachment; filename=list.csv',
                                        'X-Content-Type-Options': 'nosniff'
                                   });
                    stream.on('data', function (result) {
                        res.write(result+'\n');
                    }).on('error', function (err) {
                        conn.closeSync();
                        console.log('error occurred: '+err);
                        //throw err;
                    }).on('end', function () {
                        //res.write(str);
                        conn.closeSync();
                        res.end();
                    });
                }
                catch (e) {
                    console.log("error occured: "+ e);   
                }       
            });
        } catch(e){
            console.log("error occured: "+ e);   
        }
    }

**Comment by rhtpandeyIN** [comment]
Please feel free to reopen or comment here if you are still facing this issue. As it was related to issue #250 , I closed this issue here.
Thanks.
