### ISSUE TITLE
Angular 2/ Angular CLI/ Typescript support

### ISSUE THREAD

**Issue by maxilyaev** [ibmdb/node-ibm_db#252]
Hi, I'm trying to use ibm_db package in a simple Angular 2 (typescript) app:

import { Database } from 'ibm_db';
let conn: Database = new Database();

and get the following warnings:
WARNING in ./~/bindings/bindings.js
76:22-40 Critical dependency: the request of a dependency is an expression
WARNING in ./~/bindings/bindings.js
76:43-53 Critical dependency: the request of a dependency is an expression

The app compiles, but doesn't work.
Could you help me with that, or point to some simple typescript app using ibm_db package?
Thanks,
---Max

**Comment by huineng** [comment]
try this

import * as db from 'ibm_db';
const Pool: any = db.Pool;
let conn: any;

etc..

**Comment by maxilyaev** [comment]
Thanks for a quick reply.
Tried it:
Here is the code sample:
--------------------------------------
`
import * as db from 'ibm_db';
let cn: string = "DRIVER={DB2};PROTOCOL=TCPIP;database=MY_DB;hostname=MY_HOST;port=50000; uid=my_user;pwd=my_password";
...

          const pool: any = db.Pool;
          pool.open(cn, function(err: any, conn: any){
              if (err) return console.log(err);
              conn.query('select 1 from sysibm.sysdummy1', function (err: any, data: any) {
                if (err) console.log(err);
                else console.log(data);
                conn.close(function () {
                  console.log('done');
                });
              });
          });
`
--------------------------------------

Still fails on binding (I think: here: var odbc = require("bindings")("odbc_bindings")):
![untitled](https://cloud.githubusercontent.com/assets/27353891/25005870/488388ee-2063-11e7-91a7-b1745a67aa06.png)

Any help would be very appreciated.

**Comment by rhtpandeyIN** [comment]
Hi @maxilyaev , Well I haven't used ibm_db with angular 2 yet, but it looks like some configuration issue.
Do you have any System.js script file in your application ?
If yes then could you please paste content of that file here.

**Comment by bimalkjha** [comment]
@maxilyaev Trying it on windows or non-windows platform?

**Comment by bimalkjha** [comment]
@maxilyaev Also confirm that your have ibm_db/build/Release/odbc_bindings.node file after install. 
Share your node.js version. Run below commands:
cd ibm_db
npm install bindings

**Comment by maxilyaev** [comment]
It's a Windows 7, x64
Node version: 6.10.0
 ibm_db/build/Release/odbc_bindings.node file exists
tried:
cd ibm_db
npm install bindings
- didn't help - get the same error

I'm using Angular CLI - uses webpack instead of System.js and on purpose doesn't give me ability to access webpack config.
Is there anything else I can do?

**Comment by huineng** [comment]
unless i'm mistaken, ibm_db is normally used on the node.js backend and not directly in your browser client window ?   or are you trying out angular universal ?

if it's on the node.js backend, you might need to share us your webpack config and tsconfig.json and also what version of typescript you use

ps i'm using wp  2.2  & typescript 2.3

**Comment by bimalkjha** [comment]
@maxilyaev You can also try setting below system environment variables:
> set LIB=../ibm_db/clidriver/bin;.../ibm_db/clidriver/lib;%LIB%
> set PATH=.../ibm_db/clidriver/bin;.../ibm_db/clidriver/lib;%PATH%
Thanks.

**Comment by maxilyaev** [comment]
@huineng You are right. Once I moved the code to backend side it works.

--------------------------------------
`

          import * as db2 from 'ibm_db';
          let cn: string = "DRIVER={DB2};PROTOCOL=TCPIP;database=MY_DB;hostname=MY_HOST;port=50000; uid=my_user;pwd=my_password";
          db2.open(cn, function(err: any, conn: any){
              if (err) return console.log(err);
              conn.query('select 1 from sysibm.sysdummy1', function (err: any, data: any) {
                if (err) console.log(err);
                else console.log(data);
                conn.close(function () {
                  console.log('done');
                });
              });
          });
`
--------------------------------------

Thanks a lot.
