### ISSUE TITLE
installation without network access documentation is incomplete

### ISSUE THREAD

**Issue by sam-github** [ibmdb/node-ibm_db#255]
https://github.com/ibmdb/node-ibm_db/blob/master/INSTALL.md#221-direct-installation
https://github.com/ibmdb/node-ibm_db#install

There are two references to an env var that can be used to by pass download of the ODBC driver package, but it doesn't document anywhere how to get that ODBC driver package, so the documentation is incomplete and can't be followed.

> export IBM_DB_INSTALLER_URL=<local path or url of folder contains odbc_cli.tar.gz file>

The env var is called `_URL`, but it doesn't hold a URL, it is a file path, that is confusing.

The docs say that the file path points not directly to a tar file, but to a folder? And in that folder must exist a file called `odbc_cli.tar.gz`? So, once the platform specific odbc file is downloaded, it needs to be renamed?

**Comment by rhtpandeyIN** [comment]
Thanks for letting us know about the issue, Now I have documented the information about environment variables. Please have a look once and let us know if you still found that confusing.
Thanks

**Comment by rhtpandeyIN** [comment]
Closing the issue now, please comment down if you are still facing any issue.

**Comment by sam-github** [comment]
It would have been better to PR your doc fix so it could be commented on.

> it doesn't document anywhere how to get that ODBC driver package

^--- this comment still not addressed. No information is provided as to how to get the thing that I need to download in order to avoid the install script requiring network access.

**Comment by rhtpandeyIN** [comment]
Hi @sam-github , please review the new PR. Thnaks.
