### ISSUE TITLE
Write a Knex Adapter

### ISSUE THREAD

**Issue by drmikeh** [ibmdb/node-ibm_db#257]
Are there any plans to write a Knex adapter for this project? It would be nice to use a knexfile for connecting to DB2 databases and use Knex for building DB2 SQL statements.

Knex already has support for Postgres, MSSQL, MySQL, MariaDB, SQLite3, and Oracle. See http://knexjs.org/

**Comment by mattbrunetti** [comment]
Hi @drmikeh , your issue belongs with with the knex repo since that's where all the adapters reside. 

The issue is already there - tgriesser/knex#1350

**Comment by rhtpandeyIN** [comment]
@drmikeh thanks for the information, we will see what we can do from our side. Closing the issue now.
