### ISSUE TITLE
 SQLCODE=-1042M][CLI Driver] SQL1042C  An unexpected system error occurred.  SQLSTATE=58004

### ISSUE THREAD

**Issue by Learner29** [ibmdb/node-ibm_db#258]
I'm trying to connect BigSQL using python 3.5.I from my Windows7.I used following code
from ibm_db import connect
connection = connect('DATABASE=bigsql;'
                     'HOSTNAME=my bigsql server address;'  # 127.0.0.1 or localhost works if it's local
                     'PORT=port;'
                     'PROTOCOL=TCPIP;'
                     'UID=uid;'
                     'PWD=pwd;', '', '')

But I'm getting error "SQLCODE=-1042M][CLI Driver] SQL1042C  An unexpected system error occurred.  SQLSTATE=58004" while executing the connection statement. Can you please help?

**Comment by rhtpandeyIN** [comment]
Hi @Learner29 ,

I think the db2systm file is either missing, permission issue or corrupted/invalid. This file is require in order for db2start to function properly.

Try to run db2start or db2stop locally, When "SQL1042C" error is encountered on db2start and db2stop, subsequently all other db2 commands (except "db2level") fail with the following.

'SQL5005C' error if the db2systm file is missing or permission issue such as:
$ db2 list db directory
SQL5005C System Error.

$ db2 get dbm cfg
SQL5005C System Error.

$ db2 list applications
SQL5005C System Error.

'SQL5055C' error if the db2systm file is corrupted/invalid such as:
$ db2 list db directory
SQL5055C The content of the database configuration file is not valid.

$ db2 get dbm cfg
SQL5055C The content of the database configuration file is not valid.

$ db2 list applications
SQL5055C The content of the database configuration file is not valid.



To recover the above situation :


- Drop and recreate the instance as the db2systm file is created when the instance of the database manager is created.

Or

- Issue 'db2iupdt' against the instance if the db2systm is corrupted.

**Comment by Learner29** [comment]
Hello @rhtpandeyIN Thanks for the response.I'm using BigSQL & I checked the server is working.My problem is that I have to add some truststore.jks file,that file has been used to connect BigSQL using Java.But I'm not sure where to add it.It was in this format in Java sslConnection=true;sslTrustStoreLocation="<Location where my truststore file is present in my harddisk>;sslTrustStorePassword=<my trust store password>" . I'm using following statement to connect BigSQL
 connection = connect('DATABASE=<my data base name>'
                     'HOSTNAME=<web address of my database>;'  # 127.0.0.1 or localhost works if it's local
                     'PORT=<port number of my data base>;'
                     'PROTOCOL=TCPIP;'
                     'UID=<my UID>;'
                     'PWD=<my pwd>;', '', '')
Can you please guide me about how/where to add trust store file details?

**Comment by rhtpandeyIN** [comment]
@Learner29 , I am afraid I can't help you in this. Well I will get that information for you.
I found one more solution for SQL1042C problem :
Please check if there is any LD_LIBRARY_PATH set in your system?
If not, then you will need to set it.
(set the "clidriver/lib" path and "clidriver/lib/icc" path into LD_LIBRARY_PATH environment variable)

for ex:
```
export LD_LIBRARY_PATH=/root/rohit/node_modules/ibm_db/installer/clidriver/lib:/root/rohit/node_modules/ibm_db/installer/clidriver/lib/icc
```

**Comment by rhtpandeyIN** [comment]
Hi @Learner29 , are you still facing this issue? Could you please share your experience with us?
I am closing the issue now, If in case you are still facing this issue please feel free to reopen it here.
Thanks.

**Comment by Learner29** [comment]
Hello @rhtpandeyIN ,yes I'm still facing the issue.Kindly don't close,if someone can able to solve it

**Comment by rhtpandeyIN** [comment]
Hi @Learner29 , did you try above solution (set LD_LIBRARY_PATH) ?

**Comment by Learner29** [comment]
Hello @rhtpandeyIN yes I did try

**Comment by bimalkjha** [comment]
@Learner29 Do you have c:\program files\ibm\gsk8 directory? If your system already have an older version of gskit installed, ibm_db will pickup that and throw SQL1042C error. If c:\program files\ibm\gsk8 exist, please rename it and then try the connection.
If it does not work, then try below steps:
Add .../ibm_db/installer/clidriver/bin, .../ibm_db/installer/clidriver/bin/icc64, .../ibm_db/installer/clidriver/lib at the start of PATH and LIB system environment variables and then test connectivity using new window.

Regarding truststore.jks file: it is the ssl certificate file for JDBC connection. node-ibm_db uses ODBC connection, so you need a new certificate with .arm extension for node-ibm_db. Then use below connection string for connectivity:
connection = connect('DATABASE='
'HOSTNAME=;' # 127.0.0.1 or localhost works if it's local
'PORT=;'
'PROTOCOL=TCPIP;'
'Security=SSL;'
'SSLServerCertificate=<certificate.arm>;'
'UID=;'
'PWD=;','', '')

Thanks.

**Comment by Learner29** [comment]
Thank you @bimaljha .I have gsKit8 Crypt 64 Bit & gsKit8 SSL 64 Bit. In my system I have BM Data Server Runtime Client V9. But I'm not finding ibm_db folder. I also have installed IBM DB2 Do I need to install any other ?
![ibmdb2](https://cloud.githubusercontent.com/assets/28400263/26151280/b1ef85ea-3b1f-11e7-8b40-7be54b21144b.png)
I have installed these in my system.Sorry I have very little knowledge in DB2.I don't know how to retrieve their version

**Comment by rhtpandeyIN** [comment]
Hi @Learner29 , ibm_db is nothing but node-ibm_db, when you install node-ibm_db using "npm install ibm_db" it will create a node_modules directory and inside that ibm_db will be install.
Thanks

**Comment by Learner29** [comment]
Hi @rhtpandeyIN, I'm using windows 7 & I'm getting error message 'npm' is not recognized as an internal or external command

**Comment by bimalkjha** [comment]
@Learner29 Seems you are not using node.js driver but python driver. So, correct github repository for which you should open issue is https://github.com/ibmdb/python-ibmdb and not this repository.

Anyway, I can have my two cents here. Issue seems due to two versions of DB2 installed in your system. Do you really need both DB2COPY1 and DB2COPY2? If not, the please uninstall the one which is not required or set the system environment variables PATH, LIB and INCLUDE to point the COPY that you want to be effective.
For SQL1042C issue, add c:\program files\ibm\gsk8\bin and c:\program files\ibm\gsk8\lib folder at the start of PATH and LIB system environment variables. Also, check you have the path of correct DB2COPY added in PATH and LIB. Add ....\SQLLIB\bin and ...\SQLLIB\lib to PATH and LIB. Add ....\SQLLIB\include to INCLUDE system environment variables. If LIB does not exist, create it.

Thanks.

**Comment by dantedubon** [comment]
Hello, I have the same problem using Windows Bash Shell (WSL). I have ran the file testODBCConnection.sh and I have the following output:  `
bash ./testODBCConnection.sh
Trace could not allocate the necessary IPC resources.  Please retry
using a smaller buffer size.

===============================================================================
Client information for the current copy:
===============================================================================

Client Package Type       : IBM Data Server Driver For ODBC and CLI
Client Version (level/bit): DB2 v10.5.0.5 (special_33523/64-bit)
Client Platform           : Linux/X8664
Install/Instance Path     : /home/YYYY/.nvm/versions/node/v6.10.2/lib/node_modul
es/ibm_db/installer/clidriver
DB2DSDRIVER_CFG_PATH value: <not-set>
db2dsdriver.cfg Path      : /home/YYYY/.nvm/versions/node/v6.10.2/lib/node_modul
es/ibm_db/installer/clidriver/cfg/db2dsdriver.cfg
DB2CLIINIPATH value       : <not-set>
db2cli.ini Path           : /home/YYYY/.nvm/versions/node/v6.10.2/lib/node_modul
es/ibm_db/installer/clidriver/cfg/db2cli.ini
db2diag.log Path          : /home/YYYY/.nvm/versions/node/v6.10.2/lib/node_modul
es/ibm_db/installer/clidriver/db2dump/db2diag.log

===============================================================================
db2dsdriver.cfg schema validation for the entire file:
===============================================================================

Success: The schema validation completed successfully without any errors.

===============================================================================
db2cli.ini validation for database "AS400:XXX:446":
===============================================================================

Note: The requested data source name or a database name cannot be found in 
db2cli.ini file. The file is searched at 
"/home/YYYY/.nvm/versions/node/v6.10.2/lib/node_modules/ibm_db/installer/clidriv
er/cfg/db2cli.ini".

===============================================================================
db2dsdriver.cfg validation for database "AS400:XXX:446":
===============================================================================

Note: The requested data source name or a database name cannot be found in 
db2dsdriver.cfg file. The file is searched at 
"/home/YYYY/.nvm/versions/node/v6.10.2/lib/node_modules/ibm_db/installer/clidriv
er/cfg/db2dsdriver.cfg".

===============================================================================
Connection attempt for database "AS400:XXX:446":
===============================================================================

[FAILED]: [IBM][CLI Driver] SQL1042C  An unexpected system error occurred.  SQLSTA
TE=58004


===============================================================================
Error: The validation operation failed.
===============================================================================

===============================================================================
The validation is completed.
===============================================================================

Trace is already off; no action was taken.
Could not read from file "1.trc".
Could not read from file "1.trc".
Could not read from file "1.trc".`

**Comment by Learner29** [comment]
Thanks @dantedubon ,it works

**Comment by bimalkjha** [comment]
@dantedubon Try below commands on windows:
```
set LIB=/home/YYYY/.nvm/versions/node/v6.10.2/lib/node_modul
es/ibm_db/installer/clidriver/lib;/home/YYYY/.nvm/versions/node/v6.10.2/lib/node_modul
es/ibm_db/installer/clidriver/bin;%LIB%
set PATH=/home/YYYY/.nvm/versions/node/v6.10.2/lib/node_modul
es/ibm_db/installer/clidriver/lib;/home/YYYY/.nvm/versions/node/v6.10.2/lib/node_modul
es/ibm_db/installer/clidriver/bin;%PATH%
db2trc on -f 1.trc 
bash ./testODBCConnection.sh
```
Thanks.

**Comment by dantedubon** [comment]
I have the same output with WSL.

**Comment by bimalkjha** [comment]
@dantedubon What is the output of "db2trc on -f 1.trc " command? If it works for you, can you share the generated trace files? Thanks.

**Comment by dantedubon** [comment]
Hi, sorry for the late response, but I had to upgrade my Windows 10 to Creators Update and also my WSL to Ubuntu 16.04.2 LTS. I have set all the variables from above in my bash profile and finally, I have executed the  db2trc command and I get: 
```
$ db2trc on -f 1.trc
Trace could not allocate the necessary IPC resources.  Please retry
using a smaller buffer size.

```

**Comment by rhtpandeyIN** [comment]
try this : 
`db2trc on -t -l 8m -f 1.trc`

**Comment by dantedubon** [comment]
I have the same result: 
```
$ db2trc on -t -l 8m -f 1.trc
Trace could not allocate the necessary IPC resources.  Please retry
using a smaller buffer size.
```

**Comment by rhtpandeyIN** [comment]
try to use smaller buffer size, like:
db2trc on -t -l 2m -f 1.trc

**Comment by dantedubon** [comment]
Trying to use a smaller one
```
$ db2trc on -t -l 2m -f 1.trc
Warning: The requested file size is < 8 MB. The filesize has been set to 8 MB.
Trace could not allocate the necessary IPC resources.  Please retry
using a smaller buffer size.
```

**Comment by lfpei** [comment]
@rhtpandeyIN @bimalkjha 
hello,error：[IBM][CLI Driver] SQL1042C  An unexpected system error occurred.  SQLSTATE=58004
What environment variables do I need to set?  windows system

**Comment by bimalkjha** [comment]
@lfpei First update database connection information in `ibm_db\installer\testODBCConnection.bat` file and run it to make sure server is reachable and no connection issue. Then set the environment variable as it is set in the script and run your node program.
I think you need to set PATH and LIB system env vars pointing to `ibm_db\installer\clidriver\bin, clidriver\lib & clidriver\lib64` folders. Thanks.

**Comment by lfpei** [comment]
@bimalkjha I set the environment variable：
Path:ibm_db\installer\clidriver\bin;
LIB:clidriver\lib;
But still report that error；I installed the ibm_db module in my program.Also recompile correctly

**Comment by lfpei** [comment]
ibm_db\installer\testODBCConnection.bat run error:[IBM][CLI Driver] SQL1042C An unexpected system error occurred. SQLSTATE=58004.

**Comment by bimalkjha** [comment]
@lfpei Please share 1.* files generated by testODBCConnection.bat file for investigation. You can open a new issue for it and mail the files to bjha@rocketsoftware.com. Thanks.
