### ISSUE TITLE
Are the crypto protocols configurable for FIPS compliance?

### ISSUE THREAD

**Issue by sam-github** [ibmdb/node-ibm_db#262]
We're trying to connect a (FIPS) Node application to DB2 JSON but we're getting an error that seems to be related with MD5. If I understood correctly, DB2 JSON Wire Listener authenticate connections using only MD5 which cannot be used for FIPS compliance.
 
The error is:
 
```
crypto.js:50
  this._handle = new binding.Hash(algorithm);
                 ^
Error: error:060A80A3:digital envelope routines:FIPS_DIGESTINIT:disabled for fips
    at Error (native)
    at new Hash (crypto.js:50:18)
    at Object.Hash (crypto.js:49:12)
    at /opt/ibm/consent/cm/node_modules/mongodb/node_modules/mongodb-core/lib/auth/mongocr.js:83:28
    at /opt/ibm/consent/cm/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:461:18
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
```
 
Do you have any suggestion of what we could do in this case?

**Comment by bimalkjha** [comment]
@sam-github I think node-ibm_db does not communicate with DB2 JSON Wire Listener as node-ibm_db is not a NoSQL client. Seems you are using mongodb node.js driver and it is the mongodb node.js driver which encrypts userid and password using MD5 and send to DB2 JSON Wire Listener. Since, data is encrypted using MD5 by the mongo client, wirelistener must use MD5 to decrypt it. DB2 Wirelistener then uses the decrypted userid and password to form JDBC connection string. DB2 JSON Wire listener talk to DB2 Server using JDBC. Thanks.

**Comment by sam-github** [comment]
Thanks, Bimal

**Comment by filipecorrea** [comment]
Hi, Bimal. Do you know if DB2 Wire Listener is ready for using another encryption algorithm? I'm trying to find how to update MongoDB Node.js driver to make this connection work.

**Comment by bimalkjha** [comment]
@filipecorrea I don't think DB2 Wire Listener is ready for using another encryption algorithm. DB2 Wire Listener must be enhanced to use any other encryption algorithm if mongo client is using other algorithm. Also, changing the encryption algorithm just for node.js mongodb client will not work as DB2 Wire listener is for all mongo client including python, java, C/C++, etc. If DB2 Wire Listener changes encryption algorithm to support node.js mongo client but java or python mongo driver still uses old encryption, the older client would stop working with DB2 Wire Listener with new encryption algorithm. 
So, changing the encryption algorithm for single mongo client would not work. The new encryption mechanism should come from mongo for all clients for newer releases first. Then DB2 Wire listener need to enhance to support the newer mongodb version. Then only it would work. I think current DB2 Wire Listner is supporting only mongodb v2.8.0 clients and I don't think it would change at least in 2017. Thanks.
