### ISSUE TITLE
The specified DLL could not be loaded.

### ISSUE THREAD

**Issue by mindej** [ibmdb/node-ibm_db#263]
I have ibm_db running on Win server 2012 R2 and I am getting this error: 
[node-odbc] SQL_ERROR,message:
[IBM][CLI Driver] SQL1109N  The specified DLL "GSKit Error: 202" could not be loaded.  SQLSTATE=42724

Do you know how to fix it? 

When I am doing npm install ibm_db it compleats successfully.

**Comment by bimalkjha** [comment]
@mindej Add .../ibm_db/installer/clidriver/bin, .../ibm_db/installer/clidriver/bin/icc64, .../ibm_db/installer/clidriver/lib at the start of PATH and LIB system environment variables and then test connectivity using new window. If LIB does not exist, create one.

Btw, which version of ibm_db you have installed? Your error is showing [node-odbc] and I think it is not coming with newer version of node-ibm_db. Thanks.

**Comment by mindej** [comment]
Hi, I am using 2.0.0

**Comment by bimalkjha** [comment]
Ok. share the result after setting PATH and LIB. Thanks.

**Comment by rols2015** [comment]
I have the same error. Adding settings to PATH and LIB did not solve my issue. can someone advice please?
