### ISSUE TITLE
npm install failing

### ISSUE THREAD

**Issue by norules4kiran** [ibmdb/node-ibm_db#264]
[log.txt](https://github.com/ibmdb/node-ibm_db/files/1010363/log.txt)

`node -v`
`v6.10.2`
and
`npm -v`
`3.10.10`
OS i'm using is Ubuntu 14.04
Error I'm getting is:
```
{ Error: EACCES: permission denied, chown '/data/workspace/Blueberry/Trustfulapi_build/SourceCode/trustfulapis/node_modules/ibm_db/installer/clidriver'
    at Error (native)
  errno: -13,
  code: 'EACCES',
  syscall: 'chown',
  path: '/data/workspace/Blueberry/Trustfulapi_build/SourceCode/trustfulapis/node_modules/ibm_db/installer/clidriver' }
TRUSTfulAPIs@1.0.0 /data/workspace/Blueberry/Trustfulapi_build/SourceCode/trustfulapis
`-- (empty)

npm ERR! Linux 4.4.0-45-generic
npm ERR! argv "/data/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJs_6.10.2_/bin/node" "/data/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJs_6.10.2_/bin/npm" "install"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! ibm_db@2.0.0 install: `node installer/driverInstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ibm_db@2.0.0 install script 'node installer/driverInstall.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ibm_db package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node installer/driverInstall.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ibm_db
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ibm_db
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /data/workspace/Blueberry/Trustfulapi_build/SourceCode/trustfulapis/npm-debug.log
npm ERR! code 1
```

**Comment by rhtpandeyIN** [comment]
Hi, @norules4kiran I think it is directory permission issue. As per the error you don't have access permission for '/data/workspace/Blueberry/Trustfulapi_build/SourceCode/trustfulapis/node_modules/ibm_db/installer/clidriver' directory.

**Comment by norules4kiran** [comment]
Hi @rhtpandeyIN, 
How can I give permission, before `npm install` that folder doesn't exist.

**Comment by rhtpandeyIN** [comment]
You can explicitly give access permissions to parent directory.
like: chmod -R 777 /data/workspace/Blueberry/Trustfulapi_build/SourceCode/trustfulapis/

**Comment by rhtpandeyIN** [comment]
Hi @norules4kiran , Are you able to solve the issue as per our "same time" communication? if you are still facing any trouble, please feel free to comment here. Thanks.

**Comment by norules4kiran** [comment]
Not really..! still facing the same issue

**Comment by rhtpandeyIN** [comment]
What error exactly now you are getting, is it same as previous one? (After using IBM_DB_HOME environment variable).

**Comment by norules4kiran** [comment]
After analysis, this looks like an issue with our underlying infra and we are further investigating on it

**Comment by rhtpandeyIN** [comment]
Hi @norules4kiran , we have pushed a fix for that into out github repo, you can try using following command : 
`npm install git+https://git@github.com/ibmdb/node-ibm_db.git`

I hope you will not face this issue again... (very soon we will also update the "npm" repo with this fix).
