### ISSUE TITLE
SchemaList in Connection String not working

### ISSUE THREAD

**Issue by bstahlhood** [ibmdb/node-ibm_db#265]
When connecting with the following connection string:

`"DATABASE=*;UID=*;PWD=*;HOSTNAME=*;port=*;SCHEMALIST=‘USER1’,’USER2’,’USER3’”`

The SchemaList is being ignored. Is there another option that needs to be set for this to work?

**Comment by bimalkjha** [comment]
Please follow the instructions here: https://www.ibm.com/support/knowledgecenter/SSEPGG_10.5.0/com.ibm.db2.luw.apdv.cli.doc/doc/r0008810.html 
Thanks.
