### ISSUE TITLE
Errors while trying to connect after long time.

### ISSUE THREAD

**Issue by gowthamravichandran** [ibmdb/node-ibm_db#270]
Hey team, 

We are using node-ibm_db driver for connecting to DB2.

If the app is let unused for sometime or hours together. We get the below errors randomly when trying to use it again. 

We were using node-ibm_db V1.0.0 initially, and then updated to V2.0.0 still face these issues. 

Error 1:
May 08 00:40:21.log: { Error: [IBM][CLI Driver] *SQL30081N*  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "169.111.111.41".  Communication function detecting the error: "*send*".  Protocol specific error code(s): "*110*", "*", "*".  SQLSTATE=*08001*

*Error description: ETIMEDOUT - Connection timeout*

Error 2:
May 09 11:57:57.log:   message: '[IBM][CLI Driver] *SQL30081N*  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "10.111.111.11".  Communication function detecting the error: "*send*".  Protocol specific error code(s): "*104*", "*", "0".  SQLSTATE=*08001*\n',

*Error description: ECONNRESET - Connection has been reset by partner*

Error 3:
May 18 14:19:07.log:   message: '[IBM][CLI Driver] *SQL30081N*  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "10.111.111.11".  Communication function detecting the error: "*recv*".  Protocol specific error code(s): "***", "*", "0".  SQLSTATE=*08001*\n',

*Error description: *,*,0 indicates the connection was closed by the peer. This could be any network device (i.e. firewall, router, workload balancing device, etc...) between the client and DB2 server, or the DB2 server itself.*

Error 4:
May 18 03:06:27.log: { Error: [IBM][CLI Driver] *SQL30081N*  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "169.111.111.41".  Communication function detecting the error: "*send*".  Protocol specific error code(s): "*32*", "*", "0".  SQLSTATE=*08001*

*Error description: EPIPE (Broken Pipe)*

Below is the code on how we create connection.

`        
            var ibmdb = require('ibm_db');
            var pool = new ibmdb.Pool();
            var connString = 'DRIVER={DB2};' +
                           'DATABASE='+dbName+';'+
                           'HOSTNAME='+hostName+';'+
                           'UID='+userName+';'+
                           'PWD='+password+';'+
                           'PORT='+port+';'+
                           'CURRENTSCHEMA='+schema+';'
                           'PROTOCOL=TCPIP';

     module.exports = {
        openConnection : function(callback){
        pool.open(connString, function (err , connection) {
        // Log Error
      
       if (err){
         return console.log(err);
       } else{
          callback(connection);
       }
      });
    }
  };`

Can you please help us solve this issue?

**Comment by fnschroeder** [comment]
I am a colleague to Gowtham, and I guess a question that might go inline with this issue is: 
How to code using this module and ensure that the pool connection's stay active so that a given user can get the information at any time. 
We see that if we don't use the application for longer periods, the first user that attempts it will get a failed connection, the app will restart itself, and then the user will be able to use it. 

Additional log entries to provide some insight:

> May 26 17:20:08 sbsd_dev_certification_app cert_app.log: [2017-05-26 20:20:08.290] [INFO] server - server starting on http://localhost:6001 (App started here)
> May 27 16:11:45 sbsd_dev_certification_app cert_app.log: [2017-05-27 19:11:45.104] [TRACE] login - Entry url : /boLogin Method : POST (someone trying to access app a while later)
> May 27 16:11:45 sbsd_dev_certification_app cert_app.log: [2017-05-27 19:11:45.106] [TRACE] login - Method : checkUserLogin
> May 27 16:11:45 sbsd_dev_certification_app cert_app.log: [2017-05-27 19:11:45.106] [TRACE] database - connection : pool opened
> May 27 16:11:45 sbsd_dev_certification_app cert_app.log: [2017-05-27 19:11:45.140] [ERROR] login - [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "<OUR_IP>".  Communication function detecting the error: "send".  Protocol specific error code(s): "32", "*", "0".  SQLSTATE=08001
> May 27 16:11:45 sbsd_dev_certification_app cert_app.log: [2017-05-27 19:11:45.140] [TRACE] login - connection closed
> May 27 16:11:45 sbsd_dev_certification_app cert_app.log: 82303.369 :: Pool {
> May 27 16:11:45 sbsd_dev_certification_app cert_app.log:   options: { connectTimeout: 50 },
> May 27 16:11:45 sbsd_dev_certification_app cert_app.log:   maxPoolSize: 20,
> May 27 16:11:45 sbsd_dev_certification_app cert_app.log:   index: 0,
> May 27 16:11:45 sbsd_dev_certification_app cert_app.log:   availablePool: { 'DRIVER={DB2};DATABASE=<OURDB>;HOSTNAME=<OURIP>;UID=<OURUSER>;PWD=<OURPASS>;PORT=<OUR_PORT>;CURRENTSCHEMA=<OURSCHEMA>;': [ [Object] ] },
> May 27 16:11:45 sbsd_dev_certification_app cert_app.log:   usedPool: { 'DRIVER={DB2};DATABASE=<OURDB>;HOSTNAME=<OURIP>;UID=<OURUSER>;PWD=<OURPASS>;PORT=<OUR_PORT>;CURRENTSCHEMA=<OURSCHEMA>;': [] },
> May 27 16:11:45 sbsd_dev_certification_app cert_app.log:   poolSize: 1,
> May 27 16:11:45 sbsd_dev_certification_app cert_app.log:   odbc: ODBC {} }
> May 27 16:11:45 sbsd_dev_certification_app cert_app.log: [2017-05-27 19:11:45.141] [TRACE] login - Exit method : checkUserLogin

**Comment by gowthamravichandran** [comment]
@bimalkjha Can you please help us out?

We are facing these errors more frequently which makes the production application unstable.

**Comment by bimalkjha** [comment]
What is your platform? Are you able to run "db2cli validate" command? Thanks.

**Comment by fnschroeder** [comment]
Hi Bimal,

We are running docker containers with the Debian Jessie image (node:6.9.2).
Output of the "db2cli validate" command:

root@instance-02021806:/usr/src/app/node_modules/ibm_db/installer/clidriver/bin#
./db2cli validate

===============================================================================
Client information for the current copy:
===============================================================================

Client Package Type       : IBM Data Server Driver For ODBC and CLI
Client Version (level/bit): DB2 v10.5.0.5 (special_33523/64-bit)
Client Platform           : Linux/X8664
Install/Instance Path     : ..
DB2DSDRIVER_CFG_PATH value: <not-set>
db2dsdriver.cfg Path      : ../cfg/db2dsdriver.cfg
DB2CLIINIPATH value       : <not-set>
db2cli.ini Path           : ../cfg/db2cli.ini
db2diag.log Path          : ../db2dump/db2diag.log

===============================================================================
db2dsdriver.cfg schema validation for the entire file:
===============================================================================

Note: The validation utility could not find the configuration file
db2dsdriver.cfg. The file is searched at "../cfg/db2dsdriver.cfg".

===============================================================================
The validation is completed.
===============================================================================

Best Regards,
Filipe Schroeder

**Comment by bimalkjha** [comment]
Ok. So, now you create a db2dsdriver.cfg file as below and copy under ibm_db/installer/clidriver/cfg folder:
```
$ cat db2dsdriver.cfg
<configuration>
   <dsncollection>
      <dsn alias="testdb" name="STLEC1" host="inec010.vmec.svl.ibm.com" port="446"/>
   </dsncollection>
   <databases>
      <database name="STLEC1" host="inec010.vmec.svl.ibm.com" port="446">
         <parameter name="userid" value="dbusername"/>
         <parameter name="password" value="dbpwd"/>
         <acr>
          <parameter name="enableACR" value="true"/>
          <parameter name="enableSeamlessACR" value="true"/>
          <alternateserverlist>
            <server name="S1" hostname="inec010.vmec.svl.ibm.com" port="446"/>
            <server name="S2" hostname="inec010.vmec.svl.ibm.com" port="446"/>
          </alternateserverlist>
          <affinitylist>
            <list name="list1" serverorder="S1,S2"/>
          </affinitylist>
         </acr>
      </database>
   </databases>
</configuration>
```
If you configure ACR as in above db2dsdriver.cfg file, in case of connection get terminated by server, driver will automatically reconnect to the same server. Update the connection information in this db2dsdriver.cfg file and just use "dsn=testdb" as connection string in your node.js application.
To verify the db2dsdriver.cfg file is configured and working properly, run this command:
`db2cli validate -dsn testdb -connect`

Thanks and Regards,
Bimal Jha

**Comment by bimalkjha** [comment]
Refer https://github.com/ibmdb/node-ibm_db/blob/master/test/webapp.js to see how to use connection pooling in a web application. Thanks.

**Comment by fnschroeder** [comment]
Thanks Bimal,

We used your suggested config for db2dsdriver.cfg (but with our own DB),
below are the results:
root@instance-02021806:/usr/src/app/node_modules/ibm_db/installer/clidriver/bin#
./db2cli validate -dsn certappDB -connect

===============================================================================
Client information for the current copy:
===============================================================================

Client Package Type       : IBM Data Server Driver For ODBC and CLI
Client Version (level/bit): DB2 v10.5.0.5 (special_33523/64-bit)
Client Platform           : Linux/X8664
Install/Instance Path     : ..
DB2DSDRIVER_CFG_PATH value: <not-set>
db2dsdriver.cfg Path      : ../cfg/db2dsdriver.cfg
DB2CLIINIPATH value       : <not-set>
db2cli.ini Path           : ../cfg/db2cli.ini
db2diag.log Path          : ../db2dump/db2diag.log

===============================================================================
db2dsdriver.cfg schema validation for the entire file:
===============================================================================

Failure: Internal error while loading xml4c library. Validation cannot
continue
         further. Contact IBM technical support to rectify the issue.

===============================================================================
The validation is completed.
===============================================================================

Checking the driver's lib directory:

root@instance-02021806:/usr/src/app/node_modules/ibm_db/installer/clidriver#
ls -la lib/
total 38356
drwxr-xr-x  3 24887 7777     4096 Feb 16  2015 .
drwxr-xr-x 12 24887 7777     4096 Jun 21 08:04 ..
drwxr-xr-x  4 24887 7777     4096 Jun 16 13:56 icc
lrwxrwxrwx  1 root  root       17 Jun 16 13:56 libDB2xml4c.so ->
libDB2xml4c.so.58
lrwxrwxrwx  1 root  root       19 Jun 16 13:56 libDB2xml4c.so.58 ->
libDB2xml4c.so.58.0
-r-xr-xr-x  1 24887 7777  5006630 Jan 22  2015 libDB2xml4c.so.58.0
lrwxrwxrwx  1 root  root       11 Jun 16 13:56 libdb2.so -> libdb2.so.1
-r-xr-xr-x  1 24887 7777 34221506 Jan 23  2015 libdb2.so.1
lrwxrwxrwx  1 root  root       19 Jun 16 13:56 libdb2clixml4c.so ->
libdb2clixml4c.so.1
-r-xr-xr-x  1 24887 7777    28927 Jan 23  2015 libdb2clixml4c.so.1

I then ran what is recommended over here:
http://www-01.ibm.com/support/docview.wss?uid=swg21689403

And got the success results:
root@instance-02021806:/usr/src/app/node_modules/ibm_db/installer/clidriver/bin#
./db2cli validate -dsn certappDB -connect

===============================================================================
Client information for the current copy:
===============================================================================

Client Package Type       : IBM Data Server Driver For ODBC and CLI
Client Version (level/bit): DB2 v10.5.0.5 (special_33523/64-bit)
Client Platform           : Linux/X8664
Install/Instance Path     :
/usr/src/app/node_modules/ibm_db/installer/clidriver
DB2DSDRIVER_CFG_PATH value: <not-set>
db2dsdriver.cfg Path      :
/usr/src/app/node_modules/ibm_db/installer/clidriver/cfg/db2dsdriver.cfg
DB2CLIINIPATH value       : <not-set>
db2cli.ini Path           :
/usr/src/app/node_modules/ibm_db/installer/clidriver/cfg/db2cli.ini
db2diag.log Path          :
/usr/src/app/node_modules/ibm_db/installer/clidriver/db2dump/db2diag.log

===============================================================================
db2dsdriver.cfg schema validation for the entire file:
===============================================================================

Success: The schema validation completed successfully without any errors.

===============================================================================
db2cli.ini validation for data source name "certappDB":
===============================================================================

Note: The validation utility could not find the configuration file
db2cli.ini.
The file is searched at
"/usr/src/app/node_modules/ibm_db/installer/clidriver/cfg/db2cli.ini".

===============================================================================
db2dsdriver.cfg validation for data source name "certappDB":
===============================================================================

[ Parameters used for the connection ]

Keywords                  Valid For     Value
---------------------------------------------------------------------------
DATABASE                  CLI,.NET,ESQL <myDB>
HOSTNAME                  CLI,.NET,ESQL <myIP>
PORT                      CLI,.NET,ESQL <myPort>
USERID                    CLI,.NET      <myUser>
PASSWORD                  CLI,.NET      *******


[ Parameters used for ACR ]

Parameter                 Value
---------------------------------------------------------------------------
enableACR                 true
enableSeamlessACR         true

alternate server list:

name:S1  hostname:<myhost>  port:<myport>
name:S2  hostname:<myhost>  port:<myport>

affinity list:

name:list1  serverorder:S1,S2

===============================================================================
Connection attempt for data source name "certappDB":
===============================================================================

[SUCCESS]

===============================================================================
The validation is completed.
===============================================================================

Question:
Does the init method ensures a minimum number of opened connections? Is
there a way to do so, as to avoid having to start from 0 after a failure?
Or will the module restart with what we have specified over the init method
(which will actually be our min connection size at the end)?

Best Regards,
Filipe Schroeder

**Comment by bimalkjha** [comment]
pool.init(n, connstring) - initialises pool with n number of connections. After connection get terminated by server due to long idle state, the pool will have n connections only. While trying to use the failed connection, the driver will automatically reconnect to the server. So, at a time you'll have n number of minimum connections in the pool. Please see doc on connection pooling apis here: https://github.com/ibmdb/node-ibm_db#connection-pooling-apis
Thanks and Regards,
Bimal Jha

**Comment by fnschroeder** [comment]
Bimal,

We just put in the configuration change inside the containers and did
further testing by taking down the DB quickly and starting it back up.
We had the expected DB Communication errors:

[IBM][CLI Driver] SQL30081N A communication error has been detected.
Communication protocol being used: "TCP/IP". Communication API being used:
"SOCKETS". Location where the error was detected: "<OUR_IP>". Communication
function detecting the error: "recv". Protocol specific error code(s): "*",
"*", "0". SQLSTATE=08001

But the module/code didn't recover, the app just couldn't connect to the DB
anymore until we manually restarted its process.
Can you guide me into proper tracing for us to discover why it didn't work?

Additional information that might help:

Our configuration file, where DBNAME, DB_HOSTNAME, DB_PORT,
DB_USERNAME,DB_PASSWORD and DB_SCHEMA have our real data (db2dsdriver.cfg):
*<configuration>*
*   <dsncollection>*
*      <dsn alias="certappDB" name="DBNAME" host="DB_HOSTNAME"
port="DB_PORT"/>*
*   </dsncollection>*
*   <databases>*
*      <database name="DBNAME" host="DB_HOSTNAME" port="DB_PORT">*
*         <parameter name="userid" value="DB_USERNAME"/>*
*         <parameter name="password" value="DB_PASSWORD"/>*
*         <parameter name="CurrentSchema" value="DB_SCHEMA"/>*
*         <acr>*
*          <parameter name="enableACR" value="true"/>*
*          <parameter name="enableSeamlessACR" value="true"/>*
*          <alternateserverlist>*
*            <server name="S1" hostname="DB_HOSTNAME" port="DB_PORT"/>*
*            <server name="S2" hostname="DB_HOSTNAME" port="DB_PORT"/>*
*          </alternateserverlist>*
*          <affinitylist>*
*            <list name="list1" serverorder="S1,S2"/>*
*          </affinitylist>*
*         </acr>*
*      </database>*
*   </databases>*


*</configuration>*
Our Connection testing results:





































































*===============================================================================Client
information for the current
copy:===============================================================================Client
Package Type       : IBM Data Server Driver For ODBC and CLIClient Version
(level/bit): DB2 v10.5.0.5 (special_33523/64-bit)Client Platform
: Linux/X8664Install/Instance Path     :
/usr/src/app/node_modules/ibm_db/installer/clidriverDB2DSDRIVER_CFG_PATH
value: <not-set>db2dsdriver.cfg Path      :
/usr/src/app/node_modules/ibm_db/installer/clidriver/cfg/db2dsdriver.cfgDB2CLIINIPATH
value       : <not-set>db2cli.ini Path           :
/usr/src/app/node_modules/ibm_db/installer/clidriver/cfg/db2cli.inidb2diag.log
Path          :
/usr/src/app/node_modules/ibm_db/installer/clidriver/db2dump/db2diag.log===============================================================================db2dsdriver.cfg
schema validation for the entire
file:===============================================================================Success:
The schema validation completed successfully without any
errors.===============================================================================db2cli.ini
validation for data source name
"certappDB":===============================================================================Note:
The validation utility could not find the configuration file db2cli.ini.The
file is searched
at"/usr/src/app/node_modules/ibm_db/installer/clidriver/cfg/db2cli.ini".===============================================================================db2dsdriver.cfg
validation for data source name
"certappDB":===============================================================================[
Parameters used for the connection ]Keywords                  Valid For
Value---------------------------------------------------------------------------DATABASE
CLI,.NET,ESQL <OUR_DB>HOSTNAME                  CLI,.NET,ESQL
<OUR_HOSTNAME>PORT                      CLI,.NET,ESQL
<OUR_PORT>USERID                    CLI,.NET
<OUR_USER>PASSWORD                  CLI,.NET
*******CURRENTSCHEMA             CLI,.NET      <OUR_SCHEMA>[ Parameters
used for ACR ]Parameter
Value---------------------------------------------------------------------------enableACR
trueenableSeamlessACR         truealternate server list:name:S1
hostname:<OUR_HOSTNAME>  port:<OUR_PORT>name:S2  hostname:<OUR_HOSTNAME>
port:<OUR_PORT>affinity list:name:list1
serverorder:S1,S2===============================================================================Connection
attempt for data source name
"certappDB":===============================================================================[SUCCESS]===============================================================================The
validation is
completed.===============================================================================*

Our Connection code:

(...)






















*pool.setConnectTimeout(connectionTimeOut);pool.setMaxPoolSize(poolSize);var
connString = 'dsn=certappDB';pool.init(6, connString); // Initialize pool
with n no of connections.var conn;module.exports = {  openConnection :
function(callback){    pool.open(connString, function (error , connection)
{      try{        if (error){          callback(error,null);        }
else{          logger.trace("connection : pool opened");
callback(null,connection);        }      }catch(error){
callback(error,null);      }    });  }};*
Our module version:








*root@instance-0204096d:/usr/src/app# npm list | grep ibmnpm info it worked
if it ends with oknpm info using npm@3.10.9npm info using node@v6.9.2+--
ibm_db@2.0.0npm info ok*
Any insights into debugging this is greatly appreciated.

Best Regards,
Filipe Schroeder

**Comment by fnschroeder** [comment]
(The original post was stripped down, trying another post directly here over GitHub)

Bimal,

We just put in the configuration change inside the containers and did further testing by taking down the DB quickly and starting it back up.
We had the expected DB Communication errors:

> [IBM][CLI Driver] SQL30081N A communication error has been detected. Communication protocol being used: "TCP/IP". Communication API being used: "SOCKETS". Location where the error was detected: "<OUR_IP>". Communication function detecting the error: "recv". Protocol specific error code(s): "*", "*", "0". SQLSTATE=08001

But the module/code didn't recover, the app just couldn't connect to the DB anymore until we manually restarted its process.
Can you guide me into proper tracing for us to discover why it didn't work?

Additional information that might help:

Our configuration file, where DBNAME, DB_HOSTNAME, DB_PORT, DB_USERNAME,DB_PASSWORD and DB_SCHEMA have our real data (db2dsdriver.cfg):

> <configuration>
>    <dsncollection>
>       <dsn alias="certappDB" name="DBNAME" host="DB_HOSTNAME" port="DB_PORT"/>
>    </dsncollection>
>    <databases>
>       <database name="DBNAME" host="DB_HOSTNAME" port="DB_PORT">
>          <parameter name="userid" value="DB_USERNAME"/>
>          <parameter name="password" value="DB_PASSWORD"/>
>          <parameter name="CurrentSchema" value="DB_SCHEMA"/>
>          <acr>
>           <parameter name="enableACR" value="true"/>
>           <parameter name="enableSeamlessACR" value="true"/>
>           <alternateserverlist>
>             <server name="S1" hostname="DB_HOSTNAME" port="DB_PORT"/>
>             <server name="S2" hostname="DB_HOSTNAME" port="DB_PORT"/>
>           </alternateserverlist>
>           <affinitylist>
>             <list name="list1" serverorder="S1,S2"/>
>           </affinitylist>
>          </acr>
>       </database>
>    </databases>
> </configuration>

Our Connection testing results:

> DATABASE                  CLI,.NET,ESQL <OUR_DB>
> HOSTNAME                  CLI,.NET,ESQL <OUR_HOSTNAME>
> PORT                      CLI,.NET,ESQL <OUR_PORT>
> USERID                    CLI,.NET      <OUR_USER>
> PASSWORD                  CLI,.NET      *******
> CURRENTSCHEMA             CLI,.NET      <OUR_SCHEMA>
> 
> 
> [ Parameters used for ACR ]
> 
> Parameter                 Value
> ---------------------------------------------------------------------------
> enableACR                 true
> enableSeamlessACR         true
> 
> alternate server list:
> 
> name:S1  hostname:<OUR_HOSTNAME>  port:<OUR_PORT>
> name:S2  hostname:<OUR_HOSTNAME>  port:<OUR_PORT>
> 
> affinity list:
> 
> name:list1  serverorder:S1,S2
> 
> ===============================================================================
> Connection attempt for data source name "certappDB":
> ===============================================================================
> 
> [SUCCESS]
> 
> ===============================================================================
> The validation is completed.
> ===============================================================================

Our Connection code:
```

(...)
pool.setConnectTimeout(connectionTimeOut);
pool.setMaxPoolSize(poolSize);
var connString = 'dsn=certappDB';
pool.init(6, connString); // Initialize pool with n no of connections.
var conn;
module.exports = {
  openConnection : function(callback){
    pool.open(connString, function (error , connection) {
      try{
        if (error){
          callback(error,null);
        } else{
          logger.trace("connection : pool opened");
          callback(null,connection);
        }
      }catch(error){
        callback(error,null);
      }
    });
  }
};
```

Our module version:

> root@instance-0204096d:/usr/src/app# npm list | grep ibm
> npm info it worked if it ends with ok
> npm info using npm@3.10.9
> npm info using node@v6.9.2
> +-- ibm_db@2.0.0
> npm info ok

Any insights into debugging this is greatly appreciated.

Best Regards,
Filipe Schroeder

**Comment by fnschroeder** [comment]
Hang on a bit, Bimal, I am up to something here, save your sweat for a bit. (thanks in advance though)

**Comment by fnschroeder** [comment]
Hi Bimal,
Added 

> db2 update alternate server for database OUR_DB using hostname OUR_HOSTNAME port OUR_PORT

Even it being the same server (alternative server is the same as the original), it allowed the ACR to be triggered. We are testing this further, but good results so far. More to come on our results.

**Comment by fnschroeder** [comment]
Ok, so in an effort to assist others with such issues:

Our path of success (with Bimal's help):

1) Configure alternate server on your DB (even if the alternate server is the same one as the original if you don't have a cluster):
`db2 update alternate server for database OUR_DB using hostname OUR_HOSTNAME port OUR_PORT`

2) Configure your db2dsdriver.cfg to recover from failures and have better connection handling parameters. Ours look like this:

`<configuration>
   <dsncollection>
      <dsn alias="ALIAS_NAME" name="DBNAME" host="DB_HOSTNAME" port="DB_PORT"/>
   </dsncollection>
   <databases>
      <database name="DBNAME" host="DB_HOSTNAME" port="DB_PORT">
         <parameter name="userid" value="DB_USERNAME"/>
         <parameter name="password" value="DB_PASSWORD"/>
         <parameter name="CurrentSchema" value="DB_SCHEMA"/>
         <parameter name="KeepAliveTimeout" value="5"/>
         <parameter name="ConnectionTimeout" value="2"/>
         <parameter name="MemberConnectTimeout" value="1"/>
         <acr>
          <parameter name="enableACR" value="true"/>
          <parameter name="enableSeamlessACR" value="true"/>
          <parameter name="acrRetryInterval" value="1"/>
          <parameter name="maxAcrRetries" value="3600"/>
          <alternateserverlist>
            <server name="S1" hostname="DB_HOSTNAME" port="DB_PORT"/>
            <server name="S2" hostname="DB_HOSTNAME" port="DB_PORT"/>
          </alternateserverlist>
          <affinitylist>
            <list name="list1" serverorder="S1,S2"/>
          </affinitylist>
         </acr>
      </database>
   </databases>
</configuration>`
Where ALIAS_NAME is the name you want to give to your datasource, DBNAME is the database name over DB2, DB_HOSTNAME is the hostname of your DB2 server,  DB_PORT is the port that your DB2 server listens on, DB_USERNAME is the user you use to connect to the DB,  DB_PASSWORD the password used by DB_USERNAME to connect and DB_SCHEMA is the actual schema where your DB artifacts are created into.

We are now recovering automatically from failures, retrying one every second for 1 hour (3600 attempts each second) in the event things go wrong, having a keepalive of 5 seconds, aggressive timeouts of 2 secs to wait for a connection to be established with DB.

Hope this helps others and thanks Bimal for the guidance into this.
This can be closed.

**Comment by bimalkjha** [comment]
Thanks @fnschroeder for well documenting the steps to help others. Closing the issue now.
