### ISSUE TITLE
Dropped support for v0.12?

### ISSUE THREAD

**Issue by rmg** [ibmdb/node-ibm_db#276]
The `README.md` makes it sound like node v0.12 is still supported but that support will be removed in the next version.

Using the following steps on macOS:
```
$ git clone git@github.com:ibmdb/node-ibm_db.git
$ cd node-ibm_db
$ npm install
```

Node v0.10.48 + npm v2.15.1: failed (expected)
Node v0.12.18 + npm v2.15.11: failed (???)
Node v4.8.3 + npm v2.15.11: success
Node v6.10.3 + npm v3.10.10: success
Node v7.10.0 + npm v4.2.0: success
Node v8.0.0 + npm v5.0.0: success

It looks to me like Node v0.12 support has already been dropped. Is that correct?

**Comment by rhtpandeyIN** [comment]
Hi @rmg , I don't think so it should affect non-windows platform, we provide pri-compiled binaries for windows and we are planning to discontinued that support which will affect only windows platform.
for other platform module dynamically complies at the installation time, so as much as node versions supports ibm_db used APIs, for them module should work fine.

I request you to please try below command once with node v0.12.
> npm install git+https://git@github.com/ibmdb/node-ibm_db.git

**Comment by bnoordhuis** [comment]
I get a compile error with v0.12.7 but I don't think it's node-ibm_db's fault.  It probably flew under the radar until a recent compiler update (for me: OS X, clang-802.0.42) because the code in v8.h is defective.

First, the error:
```
  CXX(target) Release/obj.target/odbc_bindings/src/odbc.o
In file included from ../src/odbc.cpp:19:
../../v0.12/deps/v8/include/v8.h:5768:54: error: 'CreateHandle' is a protected member of 'v8::HandleScope'
  return Handle<T>(reinterpret_cast<T*>(HandleScope::CreateHandle(
```
It can be fixed by patching v8.h in the v0.12.7 source tarball.  Note that it affects all v0.12 releases, not just v0.12.7.  Downgrading to an older version of node-ibm_db won't help either.
```diff
diff --git a/deps/v8/include/v8.h b/deps/v8/include/v8.h
index ef0bda6..148a1d4 100644
--- a/deps/v8/include/v8.h
+++ b/deps/v8/include/v8.h
@@ -836,6 +836,9 @@ class V8_EXPORT HandleScope {
   internal::Object** prev_next_;
   internal::Object** prev_limit_;
 
+  // Handle::New uses CreateHandle with an Isolate* parameter.
+  template<class F> friend class Handle;
+
   // Local::New uses CreateHandle with an Isolate* parameter.
   template<class F> friend class Local;
 
```
v0.12 is end-of-life so this is never going to be fixed upstream.  The workaround would be to either patch the source by hand or use an older compiler.

**Comment by rmg** [comment]
> I request you to please try below command once with node v0.12.

@rhtpandeyIN perhaps my initial post was unclear. I _did_ do that, with 6 different versions of Node and v0.12 failed.

**Comment by rhtpandeyIN** [comment]
@rmg I would like to refer @bnoordhuis above comment, this can be the issue. Please check once.

**Comment by rmg** [comment]
I'm sure that's the problem; I just meant that I had already done what you asked.

I'm fine with this being an unfixable problem - I mostly wanted to verify so that I know which versions to worry about if/when submitting pull requests.
