### ISSUE TITLE
Install failing due to 500 error on linuxx64_odbc_cli.tar.gz download

### ISSUE THREAD

**Issue by knolleary** [ibmdb/node-ibm_db#277]
As per topic, the following url is currently returning a 500 error - causing installs to fail.

https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz

This isn't the first time this external dependency has been unavailable and caused errors.

**Comment by rhtpandeyIN** [comment]
Hi @knolleary do you have permissions to download files form Internet, I mean this can be a Firewall permission issue. I tried to download form the same link and I am able to do it, might be in that particular time hosting site was down, I am not sure about that though.

If you do not want to download this driver dependency from external site, then I request you to please read the below article/steps about how to use this dependency from local system or from your own internal hosted URL.
>https://github.com/ibmdb/node-ibm_db#important-environment-variables-and-download-essentials

Please feel free to contact if you stuck somewhere. Thanks

**Comment by knolleary** [comment]
@rhtpandeyIN this error was happening from multiple locations - including from Bluemix, which was preventing applications from deploying.

It's a fact that public.dhe.ibm.com goes down occasionally breaking new installs of this module. It's good to know you've added the ability to host your own copy, but we're not going to start doing that for the boilerplate applications in Bluemix... it just introduces more dependencies and potential points of failure (keeping in sync etc).

Anyway, public.dhe.ibm.com appears to be back now, so we can close this issue.
