### ISSUE TITLE
BSON to JSON casting broken

### ISSUE THREAD

**Issue by bmcswee** [ibmdb/node-ibm_db#280]
Selecting a BSON field and casting it to JSON returns an escaped string, rather than the expected JSON object.

For example:
```sql
SELECT vj_data::JSON as vj_data
    FROM vouch_journal
```

returns:
```json
[ 
 {
  "vj_data": "{\"where\":\"Planet Ten\",\"when\":\"REAL SOON!\"}"
 }
]
```

However, selecting a specific member of the JSON field and casting it to VARCHAR _does_ work:

```sql
SELECT vj_data.when::VARCHAR as when
    FROM vouch_journal
```

```json
[
  {
    "when": "REAL SOON!"
  }
]
```

**Comment by bimalkjha** [comment]
node-ibm_db does not do any BSON to JSON conversion. I think you opened this issue in wrong group. Closing it. Thanks.
