### ISSUE TITLE
Build with Travis keeps getting stuck

### ISSUE THREAD

**Issue by crxmail** [ibmdb/node-ibm_db#281]
Since yesterday, doing a build with travis, the build gets stuck at around 38% when downloading the node-ibm_db package after a while and times out after 10 minutes of inactivity

```
Downloading DB2 ODBC CLI Driver from https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz...
38.85% | 7266304 bytes downloaded out of 18703240 bytes.
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

Any hints as to how we can solve the issue ?

```
Now using node v8.1.0 (npm v5.0.3)
$ node --version
v8.1.0
$ npm --version
5.0.3
$ nvm --version
0.33.0
```

Thanks for your feedback !

**Comment by huineng** [comment]
it even stops at 22.43%  can't this file be put somewhere on a more performant and stable server ?

**Comment by rhtpandeyIN** [comment]
I think server was down on that particular time period, which is up now. Could you please tell us is it working properly now? 

Thanks for your patience and support.

**Comment by crxmail** [comment]
Yes me managed to complete the build yesterday, though from time to time thru travis it still times out. When doing a build locally the install usually goes well.
Thanks for your feedback.

**Comment by rhtpandeyIN** [comment]
sure we will try to figure it out, and that is our first priority to keep the server up, but still sometimes downtime happens. Thanks.
