### ISSUE TITLE
Issue with Windows Users node 8.10.0

### ISSUE THREAD

**Issue by ichabondcrane** [ibmdb/node-ibm_db#283]
Hi, I'm a Windows 7 64-bit user with Node 8.10.0 installed...
I've tried various fixes such as npm rebuild and install and still get the same error message.
Mac users in our team, with Node 8.10.0 installed can start the app without any issues..
But for us windows users, Node  server/app wont work and I get these error message ...... Thanks in advance for your help..

C:\workspace\proj\proj1\node_modules\ibm_db\node_modules\bindings\bindings.js:83
1]         throw e
1]         ^
1]
1] Error: The module '\\?\C:\workspace\proj\proj1\node_modules\ibm_db\build\Release\odbc_bindings.node'
1] was compiled against a different Node.js version using
1] NODE_MODULE_VERSION 51. This version of Node.js requires
1] NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
1] the module (for instance, using `npm rebuild` or `npm install`).
1]     at Object.Module._extensions..node (module.js:598:18)
1]     at Module.load (module.js:503:32)
1]     at tryModuleLoad (module.js:466:12)
1]     at Function.Module._load (module.js:458:3)
1]     at Module.require (module.js:513:17)
1]     at require (internal/module.js:11:18)
1]     at bindings (C:\workspace\proj\proj1\node_modules\ibm_db\node_modules\bindings\bindings.js:76:44)
1]     at Object.<anonymous> (C:\workspace\proj\proj1\node_modules\ibm_db\lib\odbc.js:27:31)
1]     at Module._compile (module.js:569:30)
1]     at Object.Module._extensions..js (module.js:580:10)
1] [nodemon] app crashed - waiting for file changes before starting...

**Comment by bnoordhuis** [comment]
NODE_MODULE_VERSION 51 is node 7.x, not 8.x.  Did you try the suggestion?

> Please try re-compiling or re-installing the module (for instance, using npm rebuild or npm install).

**Comment by rhtpandeyIN** [comment]
Hi @ichabondcrane , we provide pre-compiled binaries for windows platform, and right now it doesn't have binaries for node version 8.x, so you can use it with node v8.x right now on windows platform.
It is working on other platform because - it just directly compile there at installation time, that's why no issue there.

I would suggest use node 7.x for windows platform until we provide support for node v8.x

Thanks:

**Comment by sam-github** [comment]
This seems like a feature opportunity to me, if the current platform doesn't have a pre-built binary, could the install script fall back to attempting to build the addon from source? That's what appmetrics does (it also provides binary builds).

**Comment by bnoordhuis** [comment]
As well, if the user has Visual Studio or Build Tools installed, it should Just Work(TM) on Windows as well, shouldn't it?

**Comment by bimalkjha** [comment]
@sam-github If install script fall back to attempting to build the addon from source on windows, in absence of visual studio, the build will fail. Now, user will complain that why they need to buy a visual studio license to use a free and open source node.js driver? To avoid the license dependency, we included windows binary. But, appmetrics tric has point. We'll look to match that. Thanks.

**Comment by bimalkjha** [comment]
Apart from the VS license dependency, windows compilation comes with lots of environment related issues. The build\odbc_bindings.vcxproj generated by node-gyp on windows has rule to link with odbc32.dll by default and it do not link with IBM ODBC/CLI driver - db2app64.dll. There will be lot of overhead to maintain and fix the bugs of windows compilation, so we decided it is good to have some delay in supporting new version of node.js on windows compared to flood of environment related issues. Thanks.

**Comment by rhtpandeyIN** [comment]
Node v8.x support has been added into github repo (we will update npm repo soon for the same).
Use following command to install from github:
`npm install git+https://git@github.com/ibmdb/node-ibm_db.git `

**Comment by ichabondcrane** [comment]
Hi @rhtpandeyIN - npm install git+https://git@github.com/ibmdb/node-ibm_db.git worked at my end..

**Comment by ichabondcrane** [comment]
thanks

**Comment by ichabondcrane** [comment]
@@rhtpandeyIN  - could I ask when would you be able to publish this in npm?

**Comment by rhtpandeyIN** [comment]
hi @ichabondcrane ,

2.1.0 released :)
