### ISSUE TITLE
Can't load image like in test-blob-file.js

### ISSUE THREAD

**Issue by Alwarja** [ibmdb/node-ibm_db#286]
Hi!

I'm trying to load a small image as BLOB in the database like in [test-blob-file.js](https://github.com/ibmdb/node-ibm_db/blob/master/test/test-blob-file.js), but it doesn't insert anything (it doesn't fail either, the ID is inserted correctly). Can you see anything I'm doing wrong?

Thanks!

`
ibmdb.open(connString,function(err,conn){
    //conn.querySync("create table mytab (id int, photo BLOB(2000M)) ORGANIZE BY ROW");
    conn.prepare("insert into mytab (id, photo) VALUES (?, ?)", function (err, stmt) {
      if (err) {
        //could not prepare for some reason
        console.log(err);
        return conn.closeSync();
      }

      // Create params object
      var img = {ParamType:"FILE", DataType: "BLOB", Data: "Koala.jgp"};

      //Bind and Execute the statment asynchronously
      console.log([ conv_id, img ]);
      stmt.execute([ conv_id, img ], function (err, result) {
        if( err ) console.log(err);
        else result.closeSync();

        //Close the connection
        stmt.closeSync();
  	  conn.close(function(err){});
      });
    });
  });
`

**Comment by Alwarja** [comment]
Same thing happens with [test-blob-insert.js](https://github.com/ibmdb/node-ibm_db/blob/master/test/test-blob-insert.js), the id is inserted but the BLOB data is ignored

**Comment by rhtpandeyIN** [comment]
Hi @Alwarja ,
Please try following code, it is tested and verified. And please update your credentials in connection string and image file name and text file name.

`fs = require('fs'),
ibmdb = require('ibm_db'), 

cn="DRIVER={DB2 ODBC Driver};DATABASE=SAMPLE;HOSTNAME=<my_username>;UID=<my_uid>;PWD=*********;PORT=50000;PROTOCOL=TCPIP";

ibmdb.open(cn, function (err,conn) {
	if (err) {
		return console.log(err);
	}
	
	conn.querySync("create table blobtest_table3 (empId int, photo BLOB(1M), notes CLOB(1M))");
	
	var imgfile= fs.readFileSync('abc123.jpg', 'binary');
	var notesfile = fs.readFileSync('notes.txt', 'ascii');
	
	var len1 = imgfile.length;
        var len2 = notesfile.length;
        console.log( "imgfile.length = " + len1);
        console.log( "notesfile.length = " + len2);
	
	
	conn.prepare("insert into blobtest_table3(empId, photo, notes) VALUES (?, ?, ?)", function (err, stmt) {
		if (err) {
			console.log(err);
			return conn.closeSync();
		}
		
		var photo = {ParamType:1, DataType: "BLOB", "Data":imgfile};
                var notes = {DataType: "CLOB", Data: notesfile};
		
		stmt.execute([18, photo, notes], function (err, result){
			if( err ) console.log(err);
			else result.closeSync();
			
			conn.prepare("select * from blobtest_table3", function (err, stmt){
				if(err) {
					console.log(err);
					return conn.closeSync();
				}
				stmt.execute([], function(err, result) {
					if(err) console.log(err);
					else {
						data = result.fetchAllSync();
						fs.writeFileSync("outputfile1.jpg", data[0].PHOTO, 'binary');
                                                fs.writeFileSync("outputfile2.txt", data[0].NOTES, 'ascii');
						try {
							conn.querySync("drop table blobtest_table3");
						} catch (e) {};
						
						result.closeSync();
						
						var size1 = fs.statSync("outputfile1.jpg")["size"];
						var size2 = fs.statSync("outputfile2.txt")["size"];
						
						console.log("Lengths after select = " + size1+ ", " + size2);
						
					}
				});
			});
		});
	});
});`

**Comment by rhtpandeyIN** [comment]
This is how you can directly upload the file using - "FILE" param-type option.

`
        fs = require('fs'),
        ibmdb = require('ibm_db'), 

    cn="DRIVER={DB2 ODBC Driver};DATABASE=SAMPLE;HOSTNAME=hotellnx122.torolab.ibm.com;UID=newton;PWD=A2m8test;PORT=18618;PROTOCOL=TCPIP";

    ibmdb.open(cn, function (err,conn) {
	if (err) {
		return console.log(err);
	}
	
	try {
      conn.querySync("drop table blobtest_table");
    } catch (e) {};
	
	try {
		conn.querySync("create table blobtest_table (empId int, photo BLOB(1M), notes CLOB(1M))");
	}catch (e) {};
	
	var img = 'abc123.jpg';
	var notesfile = 'notes.txt';
	
	var len1  = fs.statSync(img)["size"];
        var len2  = fs.statSync(notesfile)["size"];
        console.log( "img.length = " + len1);
        console.log( "notesfile.length = " + len2);
	
	conn.prepare("insert into blobtest_table(empId, photo, notes) VALUES (?, ?, ?)", function (err, stmt) {
		if (err) {
			console.log(err);
			return conn.closeSync();
		}
		
		var photo = {ParamType:"FILE", DataType: "BLOB", Data: img};
                var notes = {ParamType: 3, DataType: "CLOB", Data: notesfile};
		
		stmt.execute([18, photo, notes], function (err, result){
			if( err ) console.log(err);
			else result.closeSync();
			
			conn.prepare("select * from blobtest_table", function (err, stmt){
				if(err) {
					console.log(err);
					return conn.closeSync();
				}
				stmt.execute([], function(err, result) {
					if(err) console.log(err);
					else {
						data = result.fetchAllSync();
						fs.writeFileSync("output1.jpg", data[0].PHOTO, 'binary');
                                                fs.writeFileSync("output2.txt", data[0].NOTES, 'ascii');
						try {
							conn.querySync("drop table blobtest_table");
						} catch (e) {};
						
						result.closeSync();
						
						var size1 = fs.statSync("output1.jpg")["size"];
						var size2 = fs.statSync("output2.txt")["size"];
						
						console.log("Lengths after select = " + size1+ ", " + size2);				
					}
				});
			});
		});
	    });	
    });
`
