### ISSUE TITLE
Probless connecting to HADR database

### ISSUE THREAD

**Issue by lgfa29** [ibmdb/node-ibm_db#29]
When trying to access a database with HADR I receive this error:
```
Error: [IBM][CLI Driver] SQL1776N  The command cannot be issued on an HADR database. Reason code = "1".
```

Even though the reason code is 1 (`The command is not supported on an HADR standby database.`) I am sure I am pointing my app to the primary database because the query works normally the first time., this error only happens after the first successful request.

Also, I have no problem connecting to the same database using the DB2 PHP driver, so it doesn't look like a database base configuration issue.

**Comment by mariobriggs** [comment]
Is the test case required to reproduce this as follows - open 2 connections and in each issue a sql & we see the error on the 2nd connection ?

**Comment by lgfa29** [comment]
It doesn't have to be two connections in parallel. I have a test file that opens a connection and runs a simple query: https://gist.github.com/lgfa29/078389f3f83095e63c96#file-test-js

If I run this script just once (`node test.js`) everything works fine, but if I run it twice in the same Node.js process this happens: https://gist.github.com/lgfa29/078389f3f83095e63c96#file-result

**Comment by avikalar** [comment]
As discussed on email, it has been found out that, when connecting to a 9.7 FP 5 DB2 server from a latest version(10.5) of DB2 Client it returns the SQL1776N error, but when connected using a 9.7 DB2 CLI driver, the connection works. This is not a node-ibm_db specific issue, but a DB2 CLI driver specific one. The DB2 CLI team are working on this issue. Please use DB2 CLI 9.7 till the DB2 CLI team come back with the fix for this issue.

**Comment by lgfa29** [comment]
Yes, using an older version of the driver worked for me. Thanks for all the help @avikalar.

**Comment by Galaf** [comment]
Sorry to barge in but how can I use a different driver?

Somehow, specifying "DRIVER={DB2v9764}" inside the connection string doesn't do the trick, it still goes through the CLI Driver and I get this error.

**Comment by bimalkjha** [comment]
Use only "DRIVER={DB2}" in connection string. To use another driver, run below commands:
export IBM_DB_HOME=<install/dir/for/new/driver>
npm install ibm_db
