### ISSUE TITLE
Deploying on AWS Lambda

### ISSUE THREAD

**Issue by theodoretliu** [ibmdb/node-ibm_db#291]
Hey, I'm writing an AWS Lambda function with this package, but I cannot for the life of me get this package to work. I correctly zipped up the `node_modules` directory and file, but whenever I run the Lambda function, I get the error `"Cannot find module 'ibm_db'"` even though I _know_ it is in the `node_modules` folder. Any thoughts?

**Comment by sam-github** [comment]
This seems like a question for AWS, not IBM, have you read https://nodeaddons.com/c-addons-as-aws-lambda-functions/ ? What do you mean by "correct"? Did you follow the 4 requirements?

**Comment by theodoretliu** [comment]
I think the C++ addon is correctly uploaded to the Lambda since it is contained within `node_modules/ibm_db`. Everything runs fine locally as well. Somehow, something gets lost when I zip and upload to the Lambda.

**Comment by sam-github** [comment]
> Did you follow the 4 requirements?

^--- ?

**Comment by theodoretliu** [comment]
I think I met the 4 requirements. The solution ended up being `chmod -R 777 node_modules` although I'm sure this is overkill and bad practice. If a more granular solution can be found, I'd love to hear it.
