### ISSUE TITLE
Unable to connect/query to dashdb instance with ibm_db (2.1.x). SQL30081N . Protocol specific error code - 104

### ISSUE THREAD

**Issue by subinpc** [ibmdb/node-ibm_db#294]
When I deploy our team's nodejs app to bluemix, after configuring it to connect to a dashdb instance, I see this error in our logs -
[IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "<r.e.d.acted>".  Communication function detecting the error: "recv".  Protocol specific error code(s): "104", "*", "0".  SQLSTATE=08001

I am using ibm_db version ^2.1.0.
This error does not happen immediately, but after the first or second query to the db.
I've tried using ibm_db's pool too, but still getting the same issue.
Also, I am seeing this issue only with node ibm_db. Our team has other apps that use jdbc, and they seem to be working fine with the db instance.

According to documentation regarding this error code - http://www-01.ibm.com/support/docview.wss?uid=swg21164785,
I should be setting QUERYTIMEOUTINTERVAL=0 in db2cli.ini file.

But in terms of node ibm_db, how do I make it read this file? Is there a default location relative to node_modules? Or can we set some environment variable to point to the file? Or is there some other way to specify the above mentioned parameter?

**Comment by subinpc** [comment]
We are able to connect and query the same database via ssl without issue. Not sure via non-ssl is giving this problem.

**Comment by bimalkjha** [comment]
@subinpc Please collect server side db2 trace using non-ssl connection and let server team to identify the cause. It looks there is some problem at server side not in ibm_db. Thanks.
