### ISSUE TITLE
After DB Connection Failure, Available and Used Pool gets blank but poolSize still has value as max pool size

### ISSUE THREAD

**Issue by yakalra1** [ibmdb/node-ibm_db#297]
In our application, we have connection pool implemented with Max Pool Size as 40 and all connections gets initialized on App Start. Now we have encountered a scenario where there was a database connectivity failure for some time but after getting the connection back, the application was still not able to execute the queries. We need to restart the application to resolve the issue.
When I replicated the scenario from my local system, I noticed that after the connection failure the available and used pool gets blank but the poolSize and maxPoolSize is set as 40 due to which its not trying to obtain new connections.
Kindly help.

**Comment by bimalkjha** [comment]
share the repro test program.

**Comment by bimalkjha** [comment]
@yakalra1 Follow instructions [here](https://github.com/ibmdb/node-ibm_db/issues/270#issuecomment-311171336) to solve the connection error after database connectivity failure after long time idle. Thanks.

**Comment by yakalra1** [comment]
Thanks for the quick response.

Our application is deployed on bluemix platform and hence we cannot make any changes in the ibm_db module and we are using bluemix DashDB Service. Could you please guide me with the steps I should take for bluemix node js application.

**Comment by yakalra1** [comment]
Hi Team,

Thanks for the quick response.

Our application is deployed on bluemix platform and hence we cannot make
any changes in the ibm_db module and we are using bluemix DashDB Service.
Could you please guide me with the steps I should take for bluemix node js
application.

Thanks & Regards,
Yamini Kalra
IBM India Pvt. Ltd.
E-mail: yakalra1@in.ibm.com
Mobile : +91 9971990201

**Comment by bimalkjha** [comment]
@yakalra1 Redeploy the application with db2dsdriver.cfg file and code to copy db2dsdrvier.cfg file under node_modules/ibm_db/installer/clidriver/cfg folder after ibm_db get installed. Thanks.

**Comment by gerdwatmann** [comment]
@yakalra1 - we have a very similar issue leveraging ibm_db module v2.0.0 and a dashDB instance (leveraging cloud foundry node.js buildpack). We are getting temporary database connectivity failures (SQL30081N - error: "send" - SQLSTATE=01001) and we have issues with resilience / have to restart the CF app. Did you solve your problem? Thanks.

**Comment by rhtpandeyIN** [comment]
Hi @gerdwatmann , when you are trying to execute the queries after above mentioned scenario, what exact error you are getting? Is it stating : "message":"Connection Timeout Occurred, Pool is full."?
Also, could you be able to share full error log and a sample repro test case with us?
Thanks.

**Comment by bimalkjha** [comment]
Issue is fixed in latest code. Thanks.
