### ISSUE TITLE
In IBM Bluemix . "loopback": "^3.0.0" is not supporting with "loopback-connector-dashdb": "^2.0.1

### ISSUE THREAD

**Issue by A-P-Singh** [ibmdb/node-ibm_db#298]
Below Error is working fine with loopback": "^2.22.0" But not working with loopback": "^3.0.0" .

I am using these versions:
"loopback": "^3.0.0",
"loopback-connector-dashdb": "^2.0.1",
"engines": {
"node": "6.10.2",
"npm": "3.10.10"
}
And I am try to deploy my applications to IBM bluemix then getting some Error like.
STG/0 Failed to compile droplet
STG/0 Staging failed: Exited with status 223

Invoking 'cf push trustApplications5'...

Using manifest file /home/ajay/Documents/ajay/demoApp6/trustApplications5/manifest.yml

Updating app trustApplications5 in org Blueberry_Trust / space DEV as singha58@in.ibm.com...
OK

Using route trustApplications5.mybluemix.net
Uploading trustApplications5...
Uploading app files from: /home/ajay/Documents/ajay/demoApp6/trustApplications5
Uploading 147.9K, 54 files
Done uploading               
OK

Starting app trustApplications5 in org Blueberry_Trust / space DEV as singha58@in.ibm.com...
Downloading liberty-for-java_v3_10-20170525-1107...
Downloading go_buildpack...
Downloading python_buildpack...
Downloading swift_buildpack_v2_0_5-20170406-2317...
Downloading liberty-for-java_v3_9-20170419-1403...
Downloading java_buildpack...
Downloaded liberty-for-java_v3_10-20170525-1107
Downloading ruby_buildpack...
Downloaded go_buildpack
Downloading sdk-for-nodejs_v3_11-20170303-1144...
Downloaded swift_buildpack_v2_0_5-20170406-2317
Downloading noop-buildpack...
Downloaded python_buildpack
Downloaded liberty-for-java_v3_9-20170419-1403
Downloading nodejs_buildpack...
Downloaded sdk-for-nodejs_v3_11-20170303-1144
Downloading php_buildpack...
Downloaded noop-buildpack
Downloading xpages_buildpack...
Downloaded ruby_buildpack
Downloading staticfile_buildpack...
Downloaded java_buildpack
Downloading sdk-for-nodejs...
Downloaded nodejs_buildpack
Downloading liberty-for-java...
Downloaded php_buildpack
Downloading dotnet-core...
Downloaded xpages_buildpack
Downloading dotnet-core_v1_0_18-20170516-1601...
Downloaded staticfile_buildpack
Downloading swift_buildpack...
Downloaded sdk-for-nodejs
Downloading binary_buildpack...
Downloaded liberty-for-java
Downloaded dotnet-core_v1_0_18-20170516-1601
Downloaded dotnet-core
Downloaded swift_buildpack
Downloaded binary_buildpack
Creating container
Successfully created container
Downloading app package...
Downloading build artifacts cache...
Downloaded app package (292K)
Downloaded build artifacts cache (51.3M)
Staging...
-----> IBM SDK for Node.js Buildpack v3.12-20170505-0656
       Based on Cloud Foundry Node.js Buildpack v1.5.24
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=true
       NODE_ENV=production
       NODE_MODULES_CACHE=true
-----> Installing binaries
       engines.node (package.json):  6.10.2
       engines.npm (package.json):   3.10.10
       
       Installing IBM SDK for Node.js (6.10.2) from cache
       npm 3.10.10 already installed with node
-----> Restoring cache
       Loading 2 from cacheDirectories (default):
       - node_modules
       - bower_components (not cached - skipping)
-----> Checking and configuring service extensions before installing dependencies
-----> Building dependencies
       Installing node modules (package.json)
       
       > loopback-oracle-installer@1.4.6 install /tmp/app/node_modules/loopback-oracle-installer
       > node pkginstall.js
       
       Downloading/Extracting http://7e9918db41dd01dbf98e-ec15952f71452bc0809d79c86f5751b6.r22.cf1.rackcdn.com/loopback-oracle-Linux-x64-abi48-1.5.0.tar.gz
       Error: Prebuilt tarball not found for your node version and platform: http://7e9918db41dd01dbf98e-ec15952f71452bc0809d79c86f5751b6.r22.cf1.rackcdn.com/loopback-oracle-Linux-x64-abi48-1.5.0.tar.gz
       at Request.<anonymous> (/tmp/app/node_modules/loopback-oracle-installer/lib/download.js:83:24)
       at emitOne (events.js:96:13)
       at Request.emit (events.js:188:7)
       at Request.onRequestResponse (/tmp/app/node_modules/request/request.js:1074:10)
       at emitOne (events.js:96:13)
       at ClientRequest.emit (events.js:188:7)
       at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:473:21)
       at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
       at Socket.socketOnData (_http_client.js:362:20)
       at emitOne (events.js:96:13)
       loopback-example-app@3.2.0 /tmp/app
       └── (empty)
       
       npm ERR! code 1
Failed to compile droplet
-----> Build failed
       
       Check our support community to get help on common issues:
       http://ibm.biz/bluemixcommunitysupport
       If you need additional help and your subscription includes support, submit a ticket so we can help:
       http://ibm.biz/bluemixsupport
       
Exit status 223
Staging failed: Exited with status 223
Destroying container
Successfully destroyed container

FAILED
Error restarting application: BuildpackCompileFailed

**Comment by rhtpandeyIN** [comment]
Why do you think it is because of node-ibm_db?

**Comment by A-P-Singh** [comment]
Because when I am using some other Loopback database connectors with Loopback 3.0 then Its working fine.
And I think npm "loopback-connector-dashdb" is using internally npm node-ibm_db.

**Comment by sam-github** [comment]
I can't find the string "ibm_db" anywhere in your bug report.

```
   > loopback-oracle-installer@1.4.6 install /tmp/app/node_modules/loopback-oracle-installer
   > node pkginstall.js
   
   Downloading/Extracting http://7e9918db41dd01dbf98e-ec15952f71452bc0809d79c86f5751b6.r22.cf1.rackcdn.com/loopback-oracle-Linux-x64-abi48-1.5.0.tar.gz
   Error: Prebuilt tarball not found for your node version and platform: http://7e9918db41dd01dbf98e-ec15952f71452bc0809d79c86f5751b6.r22.cf1.rackcdn.com/loopback-oracle-Linux-x64-abi48-1.5.0.tar.gz
   
```

appears to be the only problem, unless there is something else I am not seeing?

This looks like you should report it to https://github.com/strongloop/loopback-connector-oracle, it has a quite complex build npm install process, and it is quite possible that it doesn't work so well on bluemix.
