### ISSUE TITLE
Creating loopback app using:: apic loopback command in local system and trying to deploy to any existing application IBM bluemix . 

### ISSUE THREAD

**Issue by A-P-Singh** [ibmdb/node-ibm_db#299]
Hi ,

I am using following versions :
"loopback": "^2.22.0",
"loopback-connector-dashdb": "^2.0.1",
"engines": {
"node": "6.10.2",
"npm": "3.10.10"
}

[ajay@oc7580771417 trustApplications8]$ bluemix app push trustApplications8
Invoking 'cf push trustApplications8'...

Updating app trustApplications8 in org Blueberry_Trust / space DEV as singha58@in.ibm.com...
OK

Uploading trustApplications8...
Uploading app files from: /home/ajay/Documents/ajay/demoApp8/trustApplications8
Uploading 13.3M, 12314 files
Done uploading               
OK

Starting app trustApplications8 in org Blueberry_Trust / space DEV as singha58@in.ibm.com...
Downloading liberty-for-java_v3_10-20170525-1107...
Downloading liberty-for-java...
Downloading php_buildpack...
Downloading sdk-for-nodejs...
Downloading staticfile_buildpack...
Downloading binary_buildpack...
Downloading sdk-for-nodejs_v3_11-20170303-1144...
Downloaded sdk-for-nodejs
Downloaded liberty-for-java
Downloading swift_buildpack_v2_0_5-20170406-2317...
Downloaded liberty-for-java_v3_10-20170525-1107
Downloaded staticfile_buildpack
Downloading liberty-for-java_v3_9-20170419-1403...
Downloaded php_buildpack
Downloading dotnet-core_v1_0_18-20170516-1601...
Downloaded binary_buildpack
Downloading ruby_buildpack...
Downloaded swift_buildpack_v2_0_5-20170406-2317
Downloading dotnet-core...
Downloaded sdk-for-nodejs_v3_11-20170303-1144
Downloading swift_buildpack...
Downloaded liberty-for-java_v3_9-20170419-1403
Downloading noop-buildpack...
Downloading go_buildpack...
Downloaded dotnet-core_v1_0_18-20170516-1601
Downloading java_buildpack...
Downloaded dotnet-core
Downloaded ruby_buildpack
Downloading nodejs_buildpack...
Downloaded swift_buildpack
Downloading python_buildpack...
Downloaded noop-buildpack
Downloading xpages_buildpack...
Downloaded java_buildpack
Downloaded python_buildpack
Downloaded go_buildpack
Downloaded xpages_buildpack
Downloaded nodejs_buildpack
Creating container
Successfully created container
Downloading app package...
Downloaded app package (37.5M)
Downloading build artifacts cache...
Downloaded build artifacts cache (12.2M)
Staging...
-----> IBM SDK for Node.js Buildpack v3.12-20170505-0656
       Based on Cloud Foundry Node.js Buildpack v1.5.24
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=true
       NODE_ENV=production
       NODE_MODULES_CACHE=true
-----> Installing binaries
       engines.node (package.json):  6.10.2
       engines.npm (package.json):   3.10.10
       
       Installing IBM SDK for Node.js (6.10.2) from cache
       npm 3.10.10 already installed with node
-----> Restoring cache
       Loading 2 from cacheDirectories (default):
       - node_modules (exists - skipping)
       - bower_components (not cached - skipping)
-----> Building dependencies
       Prebuild detected (node_modules already exists)
       Rebuilding any native modules
       
       > ibm_db@2.1.0 install /tmp/app/node_modules/ibm_db
       > node installer/driverInstall.js
       
       Rebuild Process: Found clidriver at -> /tmp/app/node_modules/ibm_db/installer/clidriver
       
       Downloading of clidriver skipped - build is in progress...
       
       make: Entering directory `/tmp/app/node_modules/ibm_db/build'
       CXX(target) Release/obj.target/odbc_bindings/src/odbc.o
       CXX(target) Release/obj.target/odbc_bindings/src/odbc_connection.o
       CXX(target) Release/obj.target/odbc_bindings/src/odbc_statement.o
       CXX(target) Release/obj.target/odbc_bindings/src/odbc_result.o
       SOLINK_MODULE(target) Release/obj.target/odbc_bindings.node
       make: Leaving directory `/tmp/app/node_modules/ibm_db/build'
       
       { Error: Command failed: node-gyp configure build --IBM_DB_HOME="$IBM_DB_HOME" --IS_DOWNLOADED=false
       ../src/odbc.cpp: In static member function ‘static void ODBC::UV_AfterCreateConnection(uv_work_t*, int)’:
       ../src/odbc.cpp:204:99: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const’ is deprecated (declared at /tmp/app/vendor/node/include/node/v8.h:3270): Use maybe version [-Wdeprecated-declarations]
       Local<Object> js_result = Nan::New<Function>(ODBCConnection::constructor)->NewInstance(2, info);
       ^
       ../src/odbc.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE ODBC::CreateConnectionSync(Nan::NAN_METHOD_ARGS_TYPE)’:
       ../src/odbc.cpp: In static member function ‘static v8::Local<v8::Value> ODBC::GetSQLError(SQLSMALLINT, SQLHANDLE, char*)’:
       ../src/odbc.cpp:1189:100: warning: ‘bool v8::Object::SetPrototype(v8::Local<v8::Value>)’ is deprecated (declared at /tmp/app/vendor/node/include/node/v8.h:2813): Use maybe version [-Wdeprecated-declarations]
       objError->SetPrototype(Exception::Error(Nan::New((uint16_t *) errorMessage).ToLocalChecked()));
       Local<Object> js_result(Nan::New<Function>(ODBCStatement::constructor)->NewInstance(3, params));
       Local<Object> js_result = Nan::New<Function>(ODBCStatement::constructor)->NewInstance(3, info);
       ../src/odbc.cpp:247:99: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const’ is deprecated (declared at /tmp/app/vendor/node/include/node/v8.h:3270): Use maybe version [-Wdeprecated-declarations]
       Local<Object> js_result = Nan::New<Function>(ODBCConnection::constructor)->NewInstance(2, params);
       ^
       ^
       ../src/odbc_connection.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE ODBCConnection::CreateStatementSync(Nan::NAN_METHOD_ARGS_TYPE)’:
       ../src/odbc_connection.cpp:579:96: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const’ is deprecated (declared at /tmp/app/vendor/node/include/node/v8.h:3270): Use maybe version [-Wdeprecated-declarations]
       ^
       ../src/odbc_connection.cpp: In static member function ‘static void ODBCConnection::UV_AfterCreateStatement(uv_work_t*, int)’:
       ../src/odbc_connection.cpp:663:96: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const’ is deprecated (declared at /tmp/app/vendor/node/include/node/v8.h:3270): Use maybe version [-Wdeprecated-declarations]
       ^
       ../src/odbc_connection.cpp: In static member function ‘static void ODBCConnection::UV_AfterQuery(uv_work_t*, int)’:
       ../src/odbc_connection.cpp:906:95: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const’ is deprecated (declared at /tmp/app/vendor/node/include/node/v8.h:3270): Use maybe version [-Wdeprecated-declarations]
       Local<Object> js_result = Nan::New<Function>(ODBCResult::constructor)->NewInstance(4, info);
       ^
       ../src/odbc_connection.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE ODBCConnection::QuerySync(Nan::NAN_METHOD_ARGS_TYPE)’:
       ../src/odbc_connection.cpp:1136:97: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const’ is deprecated (declared at /tmp/app/vendor/node/include/node/v8.h:3270): Use maybe version [-Wdeprecated-declarations]
       Local<Object> js_result = Nan::New<Function>(ODBCResult::constructor)->NewInstance(4, result);
       ^
       ../src/odbc_statement.cpp: In static member function ‘static void ODBCStatement::UV_AfterExecute(uv_work_t*, int)’:
       ../src/odbc_statement.cpp:217:95: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const’ is deprecated (declared at /tmp/app/vendor/node/include/node/v8.h:3270): Use maybe version [-Wdeprecated-declarations]
       Local<Object> js_result = Nan::New<Function>(ODBCResult::constructor)->NewInstance(4, info);
       ^
       ../src/odbc_statement.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE ODBCStatement::ExecuteSync(Nan::NAN_METHOD_ARGS_TYPE)’:
       ../src/odbc_statement.cpp:289:87: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const’ is deprecated (declared at /tmp/app/vendor/node/include/node/v8.h:3270): Use maybe version [-Wdeprecated-declarations]
       Local<Object> js_result = Nan::New(ODBCResult::constructor)->NewInstance(4, result);
       ^
       ../src/odbc_statement.cpp: In static member function ‘static void ODBCStatement::UV_AfterExecuteDirect(uv_work_t*, int)’:
       ../src/odbc_statement.cpp:531:85: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const’ is deprecated (declared at /tmp/app/vendor/node/include/node/v8.h:3270): Use maybe version [-Wdeprecated-declarations]
       js_result.Reset(Nan::New<Function>(ODBCResult::constructor)->NewInstance(4, info));
       ^
       ../src/odbc_statement.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE ODBCStatement::ExecuteDirectSync(Nan::NAN_METHOD_ARGS_TYPE)’:
       ../src/odbc_statement.cpp:596:87: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const’ is deprecated (declared at /tmp/app/vendor/node/include/node/v8.h:3270): Use maybe version [-Wdeprecated-declarations]
       js_result.Reset(Nan::New<Function>(ODBCResult::constructor)->NewInstance(4, result));
       ^
       ../src/odbc_result.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE ODBCResult::Fetch(Nan::NAN_METHOD_ARGS_TYPE)’:
       ../src/odbc_result.cpp:183:57: warning: ‘v8::Local<v8::Int32> v8::Value::ToInt32() const’ is deprecated (declared at /tmp/app/vendor/node/include/node/v8.h:8202): Use maybe version [-Wdeprecated-declarations]
       ^
       ../src/odbc_result.cpp:337:51: warning: ‘v8::Local<v8::Int32> v8::Value::ToInt32() const’ is deprecated (declared at /tmp/app/vendor/node/include/node/v8.h:8202): Use maybe version [-Wdeprecated-declarations]
       ^
       ../src/odbc_result.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE ODBCResult::FetchAll(Nan::NAN_METHOD_ARGS_TYPE)’:
       fetchMode = obj->Get(fetchModeKey)->ToInt32()->Value();
       ^
       /usr/bin/ld: cannot find -ldb2
       collect2: error: ld returned 1 exit status
       gyp ERR! build error
       gyp ERR! stack Error: `make` failed with exit code: 2
       gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
       gyp ERR! System Linux 4.4.0-75-generic
       gyp ERR! command "/tmp/app/vendor/node/bin/node" "/tmp/app/vendor/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build" "--IBM_DB_HOME=/tmp/app/node_modules/ibm_db/installer/clidriver" "--IS_DOWNLOADED=false"
       gyp ERR! cwd /tmp/app/node_modules/ibm_db
       data->fetchMode = obj->Get(fetchModeKey)->ToInt32()->Value();
       ../src/odbc_result.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE ODBCResult::FetchSync(Nan::NAN_METHOD_ARGS_TYPE)’:
       fetchMode = obj->Get(fetchModeKey)->ToInt32()->Value();
       ../src/odbc_result.cpp:435:57: warning: ‘v8::Local<v8::Int32> v8::Value::ToInt32() const’ is deprecated (declared at /tmp/app/vendor/node/include/node/v8.h:8202): Use maybe version [-Wdeprecated-declarations]
       data->fetchMode = obj->Get(fetchModeKey)->ToInt32()->Value();
       ^
       ../src/odbc_result.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE ODBCResult::FetchAllSync(Nan::NAN_METHOD_ARGS_TYPE)’:
       ../src/odbc_result.cpp:618:51: warning: ‘v8::Local<v8::Int32> v8::Value::ToInt32() const’ is deprecated (declared at /tmp/app/vendor/node/include/node/v8.h:8202): Use maybe version [-Wdeprecated-declarations]
       make: *** [Release/obj.target/odbc_bindings.node] Error 1
       gyp ERR! stack     at ChildProcess.onExit (/tmp/app/vendor/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
       gyp ERR! stack     at emitTwo (events.js:106:13)
       gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
       gyp ERR! node -v v6.10.2
       gyp ERR! node-gyp -v v3.4.0
       gyp ERR! not ok
       
       at ChildProcess.exithandler (child_process.js:204:12)
       at emitTwo (events.js:106:13)
       at ChildProcess.emit (events.js:191:7)
       at maybeClose (internal/child_process.js:886:16)
       at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
       killed: false,
       code: 1,
       signal: null,
       cmd: 'node-gyp configure build --IBM_DB_HOME="$IBM_DB_HOME" --IS_DOWNLOADED=false' }
       
       npm ERR! argv "/tmp/app/vendor/node/bin/node" "/tmp/app/vendor/node/bin/npm" "rebuild" "--nodedir=/tmp/app/vendor/node"
       npm ERR! Make sure you have the latest version of node.js and npm installed.
       npm ERR!     npm bugs ibm_db
       npm ERR!     npm owner ls ibm_db
       npm ERR! Linux 4.4.0-75-generic
       npm ERR! node v6.10.2
       npm ERR! npm  v3.10.10
       npm ERR! code ELIFECYCLE
       npm ERR! ibm_db@2.1.0 install: `node installer/driverInstall.js`
       npm ERR! Exit status 1
       npm ERR!
       npm ERR! Failed at the ibm_db@2.1.0 install script 'node installer/driverInstall.js'.
       npm ERR! If you do, this is most likely a problem with the ibm_db package,
       npm ERR! not with npm itself.
       npm ERR! Tell the author that this fails on your system:
       npm ERR!     node installer/driverInstall.js
       npm ERR! You can get information on how to open an issue for this project with:
       npm ERR! Or if that isn't available, you can get their info via:
       npm ERR! There is likely additional logging output above.
       
       npm ERR! Please include the following file with any support request:
       npm ERR!     /tmp/app/npm-debug.log
-----> Build failed
       
       Some possible problems:
       
       - node_modules checked into source control
       http://docs.cloudfoundry.org/buildpacks/node/node-tips.html
       
Failed to compile droplet
Exit status 223
Staging failed: Exited with status 223
Destroying container
Successfully destroyed container

FAILED
Error restarting application: BuildpackCompileFailed

TIP: use 'cf logs trustApplications8 --recent' for more information

**Comment by rhtpandeyIN** [comment]
Hi, after checking the error log, it seems - it's the issue of "gcc" version or may be you are missing some essential system libraries.
Can you please share the details of your gcc version?
I think you should update it if you are using an older version.

**Comment by csaroff** [comment]
I'm facing the same issue

@A-P-Singh Did you find a resolution to this?

@rhtpandeyIN Do you have a suggested method for specifying the required gcc version when pushing to bluemix?

**Comment by rhtpandeyIN** [comment]
Hi @csaroff , I would suggest use the latest gcc version and it is necessary that installed compiler must support C++11.
check this link `https://github.com/ibmdb/node-ibm_db/#prerequisite`

**Comment by rhtpandeyIN** [comment]
Closing the issue for now, If you have further questions please comment it down. Thanks.

**Comment by csaroff** [comment]
@rhtpandeyIN Would you be able to tell us how to specify that gcc version when pushing to bluemix?
