### ISSUE TITLE
Empty result after INSERT query

### ISSUE THREAD

**Issue by wilk** [ibmdb/node-ibm_db#3]
Hi!

First of all, thanks for sharing this library!

The problem here is with the result of the 'INSERT' query.
Take the following example:

``` javascript
conn.query('INSERT INTO Users (name, age) VALUES ("Wilk", 26)', function (err, result) {
  if (err) cb(err);
  else cb(null, result);
});
```

I expect that 'result' has the new inserted record with an unique ID but what I got is an empty array.
What's wrong with it? Is it a wanted behaviour?

Thanks in advance.

**Comment by onelifemedia** [comment]
Are you using a `prepare` statement?  I can't seem to get anything back from an `INSERT`.

I can't figure out how to `INSERT` an escaped string, which leaves me vulnerable to errors and SQL injection.  Of course, the `prepare` doesn't seem to return the new inserted row.

What a conundrum.

**Comment by avikalar** [comment]
You can use a prepare statement here, to insert an escaped string. But the INSERT will not return anything back.

**Comment by zamrokk** [comment]
this works, but if another solution exists ... i buy it

SELECT IDENTITY_VAL_LOCAL() FROM SYSIBM.SYSDUMMY1
