### ISSUE TITLE
bindings.js:79 - Error: The specified procedure could not be found.

### ISSUE THREAD

**Issue by Lonniebiz** [ibmdb/node-ibm_db#30]
The documention seems to imply that using this ibm_db module is as simple as running:

npm install ibm_db

and then running the basic samples provided.

I have a db2 server on the LAN, and I've tried to get the ibm_db module to work on two operating systems so far: Ubuntu 14.01 64bit and Windows 7 64 bit, and neither have I succeed with.

On both OSs I get this:
node_modules\ibm_db\node_modules\bindings\bindings.js:79
        throw e
              ^
Error: The specified procedure could not be found.

Even with Google I'm having difficulty getting to the bottom of this. Please advise.

**Comment by mariobriggs** [comment]
I believe you are on node version 0.12.x, which is ain't supported yet. see #28 . We should note this in our Readme till 0.12.x support is fixed

**Comment by Lonniebiz** [comment]
@mariobriggs : You are correct about the version I'm using. I agree that the documentation should specify version requirements before "npm install ibm_db" is ever mentioned. Such requirements are fundamental and stating them upfront will save hours of confusion to others.

Thank you for the quick reply. Without it, I would still be lost and confused.

**Comment by ibmdb** [comment]
welcome. Fixed the readme.

**Comment by Lonniebiz** [comment]
@mariobriggs : Which version should I choose, now that I know that 0.12.x is not supported yet?
http://nodejs.org/dist/

**Comment by avikalar** [comment]
@Lonniebiz : Can you please try node v0.10.30 ?

**Comment by Lonniebiz** [comment]
Ok, yes, I'm making some progress using v0.10.30, located here:
http://nodejs.org/dist/v0.10.30/x64/

The documentation needs to make it abundantly clear (before any mention of "npm install ibm_db" that they must use x64 version of node, and that (so far as I've tested) v0.10.30 is that latest edition that seems to get past that binding.js error.

I'm relatively new to node.js. I hope other modules are not this picky. I will certainly want to test elsewhere before upgrading anything in node.js. I suspect that's what I need to learn from this experience.

Database drivers on a relatively new framework are a pain. If you're able to get this ibm_db module to work across all these difference platforms and versions, that's a commendable accomplishment. It has been tough getting the ibm_db to work (due to lack of clear documentation about prerequisites), but this would be even harder without ibm_db. So thanks!

**Comment by mariobriggs** [comment]
v0.11 as the docs mention itself is unstable, so not to be used.

If its not working with v0.10.36, that is a bug in ibm_db that needs to be fixed. Please open an issue and will be looked into. I have used v0.10.35 and i know others who used v0.10.36 successfully.

As for 32 bit support on windows, in the latest version of ibm_db the install process does tell you that 32 bit is not supported and to use 64 bit version of node on windows. 

In general with working with Django, SQLAlchemy, Rails on the frameworks side and python and ruby, php on the language side, whenever a new release comes out (and more so if breaking changes for native components), it will take a while before the whole chain of dependencies support it: classic example being python 3.0.

**Comment by avikalar** [comment]
@Lonniebiz : Today, I tried installing ibm_db on node v10.36, and it works on both Linux and Windows.  Can you please send me the details of the error that you get, so that I can look into the issue.

**Comment by Lonniebiz** [comment]
@mariobriggs : When I tested v10.36, I think I was actually testing the 32bit version instead of the 64bit. At first I couldn't find the 64bit windows version when I was looking through the version repositories ( http://nodejs.org/dist/ ). For some reason, they put windows 64bit in a seperate folder, while for other operating systems they put both the 32bit and 64bit versions in the same root version folder.

I will upgrade to v0.10.36 tomorrow, and submit a bug if there are issues.

Thanks for pointing out that v0.11 is unstable. I've overlooked that documentation. Also, thanks for the comments that guide my general expectations about new versions of node and their package dependencies.

@avikalar : Thanks for confirming that a later version than the one I'm using also works; I will upgrade to that tomorrow.

As a new node user, the first thing I see, for any module, is the page that introduces it. It seems like it would be a good practice to showcase any prerequistes or warnings before the npm install steps.

**Comment by mariobriggs** [comment]
I have had other users too have issues finding the x64 windows version of node. I use this page - http://blog.nodejs.org/release/ where i easily find it.

>>
As a new node user,
<<
Happy to see new node users and starting with DB2 :-)  We would be happy to hear your use-case (drop us an email, if can't be shared on public forum)

**Comment by Lonniebiz** [comment]
Ah, that's much better (bookmarked); that page just shows the versions that really matter. Thanks.

**Comment by robert-loredo** [comment]
I am using v0.10.35 node.js on 64 bit windows and am getting this error. with ibm_db node module v0.10. Does anyone know what I might be missing? I have seen above that others have used this on the same version and worked. but i am getting the binding errors. Any help would be greatly appreciated.

**Comment by Lonniebiz** [comment]
@robert-loredo : Try the [v0.10.36 64bit version](http://nodejs.org/dist/v0.10.36/x64/) instead. I can confirm that this version has been working solid for me for quite some time now.
