### ISSUE TITLE
Getting very slow response.

### ISSUE THREAD

**Issue by A-P-Singh** [ibmdb/node-ibm_db#300]
Hi ,
I am try to get only 700 records from dashDB.
Its taking more than 20 seconds.

Is there any way to Improve the performance?

**Comment by rhtpandeyIN** [comment]
Could you please share repro for that?

**Comment by A-P-Singh** [comment]
Hi rhtpandeyIN

please find details:
"dependencies": {
    "cf-deployment-tracker-client": "^0.1.3",
    "compression": "^1.0.3",
    "cors": "^2.5.2",
    "helmet": "^1.3.0",
    "loopback": "^2.22.0",
    "loopback-boot": "^2.6.5",
    "loopback-component-explorer": "^4.2.0",
    "loopback-connector-dashdb": "^2.0.1",
    "loopback-datasource-juggler": "^2.39.0",
    "serve-favicon": "^2.0.1",
    "strong-error-handler": "^2.0.0"
  },
  "devDependencies": {
    "eslint": "^3.17.1",
    "eslint-config-loopback": "^8.0.0",
    "nsp": "^2.1.0"
  },
  "engines": {
    "node": "6.10.2",
    "npm": "3.10.10"
  },

**Comment by rhtpandeyIN** [comment]
Hi, thanks for the dependencies details. Also, can you please give us a sample repro test case for the same problem, so that we can test the exact scenario.

**Comment by rhtpandeyIN** [comment]
Hi, any updates please ?

**Comment by bimalkjha** [comment]
@A-P-Singh Check with ibm_db@2.2.0. Thanks.
