### ISSUE TITLE
Milllions INSERT queries failed to complete

### ISSUE THREAD

**Issue by yiemszx** [ibmdb/node-ibm_db#301]
Hi team,

I have a function in my system which will insert the data to the database using the querySync API
The function is executed once it received the data and I have millions of data to be inserted to database

However, the system stopped suddenly in between after only about 35000 data being inserted without any error message prompted out

I also using the try-catch to skip data that unable to be inserted 

I'm not using pool because I'm trying to avoid using callbacks. I'm not sure whether this is the main reason

Can you help me solve this problem?

Thank you.

Edit 1: Below is the function:

```
const write = (data) => {
    conn = getConnection();
    const { colNames, dataValues } = getDataValues(data);
    const qryString = `INSERT INTO schema.${config.table} ${colNames} VALUES (${dataValues.toString()})`;

    try {
      const result = conn.querySync(qryString);
      console.log(`result: ${result}`);
    } catch (e) {
      console.log('error write ', e.message);
    }
};
```

**Comment by yiemszx** [comment]
I used to INSERT using prepareSync & executeSync but error of String truncation was prompted and no single data was successfully inserted to the database

Maybe because of the data is too large or there is too many columns
I tried inserting single column as follows
INSERT INTO schema.ABCD (NO) VALUES (1)

and it works but sadly failed when inserting the desired data

Or maybe there's any limitation such as too long string for the prepareSync / queryString?

**Comment by rhtpandeyIN** [comment]
Can you please try with ibm_db version 1.0.1? Please let us know the output.
Thanks

**Comment by yiemszx** [comment]
Hi rhtpandeyIN

I already tried with ibm_db@1.0.1 using prepareSync & executeSync API
The new error prompted out which is Wrong number of parameters

But based on the query I log, the number of columns, number question marks and number of values bind are all equal which is 135 

*Sorry I can't post the query here because of the data confidentiality


For the querySync API, currently I'm testing it. Gonna share the output later

Thanks!

**Comment by rhtpandeyIN** [comment]
Hi,
We have pushed a fix for this issue, please take the latest code from github and if possible verify it.
Please use following command for that:

npm install git+https://git@github.com/ibmdb/node-ibm_db.git

Thanks.

**Comment by amcintyre99** [comment]
Still fails around 14000+.
```
$ cat prep_execsync_orig.js
"use strict";
let db = require("ibm_db")();
db.openSync("DATABASE=p1;UID=db2inst1;PWD=db2inst1");
let stmt = db.prepareSync("select current_time from (values 1);");
for (let i = 0; i < 50000; i++) {
  let result = stmt.executeSync([]);
  let data = result.fetchAllSync();
  if (data.length == 1) console.log(data,i);
  result.closeSync();
};

$ node -v
v8.2.1
$ node prep_execsync_orig.js
[ { '1': '12:26:13' } ] 0
[ { '1': '12:26:13' } ] 1
[ { '1': '12:26:13' } ] 2
[ { '1': '12:26:13' } ] 3
...
[ { '1': '12:26:17' } ] 14145
[ { '1': '12:26:17' } ] 14146
[ { '1': '12:26:17' } ] 14147
[ { '1': '12:26:17' } ] 14148
$ 
```

**Comment by amcintyre99** [comment]
Deleted comment I posted to wrong issue.

**Comment by yiemszx** [comment]
I've tested using prepareSync & executeSync API, the error switched back to String data right truncation error plus Numeric value out of range

While using querySync API, it still suddenly stopped in between

I wondering why binding data provides such error while INSERT query with values (without binding) using querySync is able to insert the data successfully but suddenly stopped during the process

**Comment by yiemszx** [comment]
Maybe because of too many columns / too many values affect the binding issue?

**Comment by rhtpandeyIN** [comment]
Thanks for the update, but we still need the repro code for testing the issue from our side. I tried to run a code but I didn't get any issue in that, so if you can provide us a dummy repro (not with your actual data) that would be really helpful.

Well it seems to me again Garbage collector issue, still we need to check it first before jumping to conclusion.

**Comment by agov** [comment]
@yiemszx can you monitor the available transaction log and number of applications during your application runtime? Wondering if connections are closed properly and the statements are committed

**Comment by bimalkjha** [comment]
Fixed with latest code on github. Please install latest code using `npm install git+https://git@github.com/ibmdb/node-ibm_db.git` command and test the fix for non-windows platform. For windows, wait till next release. Thanks.
