### ISSUE TITLE
Error: Can't find npm module 'moment'

### ISSUE THREAD

**Issue by djbristow** [ibmdb/node-ibm_db#303]
When starting the run-test.js it fails when it cannot find the npm module 'moment' To fix it I added a dependency to the package.jason and then did an npm install. Then it worked

**Comment by rhtpandeyIN** [comment]
Just do `npm install moment` .
This is a testing dependency that's why its not there by default.

**Comment by sam-github** [comment]
@djbristow isn't moment already in the deps? https://github.com/ibmdb/node-ibm_db/blob/master/package.json#L45-L48

Sounds like you are running from a node_modules folder, npm doesn't install the dev dependencies of packages by default unless they are top level. Just do `npm install` in `./node_modules/ibm_db/` and it will install the dev deps.
