### ISSUE TITLE
Sudden crash after a week of running: Invalid Handle: SQLGetData retrun code = -2, stmt handle = 1:1, columnType = 12, index = 2

### ISSUE THREAD

**Issue by j4rio** [ibmdb/node-ibm_db#304]
Using the ibm_db@2.1.0 and node 7.10.1 in Bluemix. My application runs OK about a week but then suddenly the application crashes with the following error: 

node: ../src/odbc.cpp:609: static v8::Handle<v8:Value> ODBC:GetColumnValue(SQLHSTMT,Column,uint16_t*,int): Assertion `ret != -2' failed.
Invalid Handle: SQLGetData retrun code = -2, stmt handle = 1:1, columnType = 12, index = 2

The issue pops up after a couple of days running. I checked the connection closing statements and at least "netstat -tn" did not show any hanging connections while the app was running. This issue looks very similar to issue:  https://github.com/ibmdb/node-ibm_db/issues/293

**Comment by rhtpandeyIN** [comment]
Hi @j4rio ,
This issue is still there in npm released version (2.1.0), I would suggest please test with the latest github code (as the fix is delivered into github repo, we will deliver this fix in next minor <2.2.0> release).
Thanks

**Comment by j4rio** [comment]
Thanx, I,ll check the new version when it is available.
Cheers, 
Jari O
