### ISSUE TITLE
Throw out errors when running npm install

### ISSUE THREAD

**Issue by whwangp** [ibmdb/node-ibm_db#306]
When I run 'npm install', it throws out the following errors. Would you please help check the issue about ibm_db?

npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! ibm_db@2.0.0 install: `node installer/driverInstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ibm_db@2.0.0 install script 'node installer/driverInstall.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ibm_db package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node installer/driverInstall.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ibm_db
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ibm_db
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/wangping/git/wcatoolsFirs/npm-debug.log

**Comment by rhtpandeyIN** [comment]
Please share the installation steps you are following and also paste the log file output.

**Comment by whwangp** [comment]
This issue has been fixed. I run ‘export HTTP_PROXY=’ before running npm install. And then it is successful. Thanks so much for your quick response. @rhtpandeyIN

**Comment by rhtpandeyIN** [comment]
Great, good news. Closing the issue now.
