### ISSUE TITLE
Expecting FIFO in Pool.open, but it is 1 second penalty box and connection stealing instead.

### ISSUE THREAD

**Issue by vjmp** [ibmdb/node-ibm_db#307]
https://github.com/ibmdb/node-ibm_db/blob/f11897ca749af89dce2fa59b420ba2851bb420a2/lib/odbc.js#L1484-L1503

- I was very suprised to see 1000 millisecond "penalty box" for caller who comes in when all connections are in use.
- I was expecting to get into some kind of FIFO queue and civil waiting
- In this model, new requests coming in can steal released connections from those that are already waiting
- 1000 milliseconds is very long time to wait, and if we should have response for user in less than 300ms (UX responsivenes of UIs) then single wait in connection pool breaks that [should this be more like 20ms and in queue]
- and if timeout is like 30 seconds, and there is burst of connection ativity during that time, waiting caller has only 30 times to try their luck before they timeout
- and each waiting call gets separate interval
- Please tell me that I have interpreted this wrong!
- And if this is actually as I describe it above, it is very severe issue IMHO and should be fixed ASAP (it might also explain some other issues raised)

**Comment by vjmp** [comment]
@bimalkjha -- can you check this since you are author of this code and tell me that I'm wrong.

I suspect that this is issue I see in Bluemix with case where max pool size is defined in entry level columnar DB2 database. And then there is burst of activity above that max limit.

**Comment by bimalkjha** [comment]
Ok. I'll reduce it soon. Thanks.

**Comment by vjmp** [comment]
This really should be FIFO queue (first-in, first out) with no delays after connection is released after previous reserver. Order of callers must be preserved.

So when free pool is empty, all callers should be added at the end of waiting queue, in order that they come in. No by-passing, no time penalty. The "first-in" part of FIFO.

When next connection comes available (released by previous reserver), first caller (earliest, one who has waited longest time already) should get that released connection right away without delay. No connection stealing. The "first-out" part of FIFO.

And yes please, fix and publish next version ASAP. I did some testing today, and current version produces very erratic UX, since unlucky user can get really long waiting time while others steal their connections.

Thank you.

**Comment by bimalkjha** [comment]
Fixed with latest code on github. Thanks.

**Comment by vjmp** [comment]
Thank you. When is next release to npm?

**Comment by bimalkjha** [comment]
We'll release it soon. We need to prepare windows binary before release to few other fixes in the release. Thanks.

**Comment by vjmp** [comment]
How long is it till "soon"?

**Comment by bimalkjha** [comment]
@vjmp Fix is released with ibm_db@2.2.0. Please install and verify the fix. Thanks.
