### ISSUE TITLE
Data corruption when inserting BLOBs from Buffers

### ISSUE THREAD

**Issue by wiktor-k** [ibmdb/node-ibm_db#308]
Hello,

I'm inserting an in-memory Buffer into DB2 BLOB column using this placeholder (mentioned in https://github.com/ibmdb/node-ibm_db/issues/202#issuecomment-314538595):

```js
{
    ParamType: 1,
    DataType: 'BLOB',
    Data: buffer
}
```

The column is defined as type BLOB but for my test cases (TIFF images) bytes are corrupted.

That's what I see in Hex Editor and in node when running `buffer.toString('hex')`:

    49 49 2A 00 C8 8C 00 00 73 C5 3C 13 83 39 98 35 ...

That's what I get in DB2:

    49 49 2A 00 0C 00 00 73 FD 3C 13 FD 39 FD 35 FD ...

Most of "high" bytes are being replaced with FD bytes, some other bytes are also mangled.

**Comment by rhtpandeyIN** [comment]
Hi @wiktor-k ,
What exact error you are getting? is it error or just byte corruption problem?

Would you please check and try it according to below link:
https://github.com/ibmdb/node-ibm_db/issues/286
#286 

I have given tested solution there, please update us your progress.

Thanks

**Comment by bimalkjha** [comment]
@wiktor-k Please share your TIFF image too. Thanks.

**Comment by wiktor-k** [comment]
The smallest reproducible test case I could think of is this:

```js
var ibmdb = require('ibm_db');

var pool = new ibmdb.Pool();
var db = 'DATABASE=SAMPLE;HOSTNAME=192.168.99.100;PORT=50000;UID=db2inst1;PWD=pwd;PROTOCOL=TCPIP';

pool.open(db, (error, connection) => {
    if (error) {
        console.error('Could not start database connection: ' + error);
        process.exit(2);
        return;
    }
    var data = [{
        ParamType: 1,
        DataType: 'BLOB',
        Data: Buffer.from('49 49 2A 00 C8 8C 00 00 73 C5 3C 13 83 39 98 35'.split(' ').map(x => parseInt(x, 16)))
    }];
    console.log(data[0].Data.toString('hex'));
    connection.query('INSERT INTO FILES(DATA) VALUES (?)', data, (err, data) => {
        if (error) {
            console.error('Could not insert data: ' + error);
            process.exit(2);
            return;
        }
        console.log(data);
    });
});
```

with a table created like that:

```sql
create table FILES (
	Data	blob(16777216)
);
```

Inserting data shows correct values in console but bad in DBeaver (in blob view). Interestingly if I insert small blob like `Buffer.from([1, 2, 3, 4, 5])` it's stored OK.

I'm using `ibmcom/db2express-c` docker image with sample database but the same behavior has been seen in production DB2 instances.

**Comment by rhtpandeyIN** [comment]
Hi @wiktor-k ,

I think there was some data encoding problem in above sample code, I modified you code little bit and now I am getting exact data what I am inserting. Please check the below sample program.

`
var fs = require('fs'),
ibmdb = require('./node-ibm_db');
var cn="DATABASE=sample;HOSTNAME=host;UID=uerid;PWD=password;PORT=50000;PROTOCOL=TCPIP";


    ibmdb.open(cn, (err, db) => {
        if (err) {
            console.log("open failed", err);
            return;
        }

    db.query("CREATE TABLE binary_test ( data BLOB(1M) );", (err, res) => {
        if (err) {
            console.log("create failed", err);
            db.query("DROP TABLE binary_test;", (err, res) => {
                if (err) {
                    console.log("drop failed", err);
                     return;
                 }
                 console.log("drop result", res);
                 db.closeSync();
            });
            return;
        }

        const buf = Buffer.from('49 49 2A 00 C8 8C 00 00 73 C5 3C 13 83 39 98 35', 'binary');
        console.log("buf is:");
        console.log(buf.toString());

        db.query("INSERT INTO binary_test (data) values (?);",
              [{ CType: "BLOB", DataType: "BLOB", Data: buf }], (err, res) => {
            if (err) {
                  console.log("insert failed", err);
                  return;
            }

           console.log("insert result", res);

           db.query("SELECT * FROM binary_test;", (err, res) => {
              if (err) {
                console.log("select failed", err);
                return;
             }

           console.log("select result", res);

          db.query("DROP TABLE binary_test;", (err, res) => {
               if (err) {
               console.log("drop failed", err);
               return;
           }

           console.log("drop result", res);
           db.closeSync();
        });
       });
     });
    });
    });
`

Output:
`
select result [ { DATA: '49 49 2A 00 C8 8C 00 00 73 C5 3C 13 83 39 98 35' } ]
`

Closing the issue for now, if you have further queries please feel free to ask. Thanks.
