### ISSUE TITLE
Returning data and communication error with DB2 z/OS

### ISSUE THREAD

**Issue by aroper23** [ibmdb/node-ibm_db#309]
I'm using ibm_db with a DB2 11 database on z/OS. I'm encountering two issues with ibm_db that I haven't been able to solve:

1. If I use a WHERE clause, data is only returned when I query a table on a character column with a size of 1. When I issue other queries using a WHERE clause matching a column to a value, no data is returned. Selecting "count(*)" also returns no data. If I query the database with no WHERE clause, or a WHERE clause such as "where someColumn is not null", or a WHERE clause with a single character string literal ("where dataType = 'P'"), the expected data is returned without errors.

2. All queries (whether they return data or not) result in a communication error like this:

```
0.102 ::  odbc.js:query() => Entry
0.105 ::  odbc.js:query() =>  select * from MYTABLE where ID = 'C1234'
query error: { Error: [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "172.30.26.71".  Communication function detecting the error: "recv".  Protocol specific error code(s): "*", "*", "0".  SQLSTATE=08001
  errors: [],
  error: '[node-ibm_db] SQL_ERROR',
  message: '[IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "172.30.26.71".  Communication function detecting the error: "recv".  Protocol specific error code(s): "*", "*", "0".  SQLSTATE=08001\n',
  state: '08007' }
```

-------------------------------------

WORKING QUERIES
select * from MYTABLE
select * from MYTABLE where ID is not null
select * from MYTABLE where dataType = 'P'
select * from MYTABLE where ID like '%'

NON-WORKING QUERIES
select * from MYTABLE where ID = 'C1234'
select * from MYTABLE where ID like 'C%'
select count(*) from MYTABLE

This is the node script I'm using to test connectivity to the database.

```javascript
var ibmdb = require('ibm_db');

let connStr = "DATABASE=aaaa;HOSTNAME=bbbbbb;UID=cccccc;PWD=dddddddd;PORT=50000;PROTOCOL=TCPIP;CurrentSchema=eeeeeee";

ibmdb.debug(true);
ibmdb.open(connStr, function(err, conn) {
    if (err) {
        console.error("connection error: ", err);
    } else {
        console.error("query error:", err);
        conn.query("select * from MYTABLE where ID = 'C1234'", function(err, data, moreResultSets) {
            for (var i = 0; i < data.length; i++) {
                console.log(data[i].ID);
            }

            conn.close(function() {
                console.log("Connection closed");
            });
        });
    }
});
```

**Comment by aroper23** [comment]
More information about the problem:

We see the above communication error when connecting to a DB2 Connect server. When we instead connect to the DB2 database server directly, no queries return data and this error is returned:

connection error:  [IBM][CLI Driver] SQL1598N  An attempt to connect to the database server failed because of a licensing problem.  SQLSTATE=42968

This seems strange, because when I validate the connection like so:

./db2cli validate -database "aaaa:bbbbb:50000" -connect -user cccccc -passwd ddddddd

...the connection validates successfully even without a local license file.

**Comment by bimalkjha** [comment]
@aroper23 Are you connecting to Db2 for z/OS via Db2 Connect server? If yes, then you need to apply license file on Db2 Connect Server. Thanks.

**Comment by aroper23** [comment]
We were connecting through DB2 Connect initially, but now we're connecting directly to DB2 on z/OS.

Are we required to connect to DB2 via DB2 Connect with the ibm_db module? We would prefer to connect to DB2 directly if that's not the case.

If we can connect directly, do you know what licensing might be required? Would we still need a DB2 Connect license file in ibm_db/installer/clidriver/license, or is the licensing error we get indicating some other form of licensing is required either on the server or on the client?

**Comment by bimalkjha** [comment]
@aroper23 You can connect to Db2 for z/OS directly using ibm_db module. No need to go through db2connect server. Connectivity to z/OS server from a Db2 client on LUW system is not free. So, you need to use db2consv_ee.lic license file to connect to z/OS server.

If your connectivity is `ibm_db -> Db2 connect server -> Db2 for z/OS`, then apply license file on `Db2 connect server`.
If your connectivity is `ibm-db-> Db2 for z/OS`, then apply license file on `ibm_db`. You need to copy db2consv_ee.lic file of Db2 V10.5FP5 under `ibm_db/installer/clidriver/license` folder.

If license file differs for different versions of DB2 client. i.e. if your Db2 connect server is not of Db2 V10.5 release, its license file would differ from the license file used for ibm_db. ibm_db uses odbc_cli driver of db2 v10.5fp5 internally to access db2 server.

Hope it would clarify. Thanks.

**Comment by aroper23** [comment]
So after our customer provides us with the correct license file for DB2 11.1, do you think that will work with the odbc_cli 10.5 driver? If not, do you know if there's a version 11.1 odbc_cli driver available? Otherwise, will be need to install DB2 client on the client machine to avoid ODBC/license version incompatibility? Thanks.

**Comment by bimalkjha** [comment]
A db2 connect license file for DB2 11.1 should work with the odbc_cli 10.5 driver. I am able to use a DB2  11.1 license file named db2consv_ee.lic with ibm_db using odbc_cli 10.5 driver. Using this license file, I can connect to z/OS server using both Db2 v10.5 and Db2 v11.1 versions of odbc_cli driver. I think a higher version of license file works with lower version of db2 client too. But older version of license file do not work with newer version of db2 client. i.e. a db2 connect license file of version 10.5 would not work with odbc_cli v11.1 driver.

Yes, you can download version 11.1 "IBM Data Server Driver for ODBC and CLI" from here: http://www-01.ibm.com/support/docview.wss?uid=swg24043794 and use it with ibm_db. After extracting the clidriver from this downloaded image, run `export IBM_DB_HOME=<path to v11.1 clidriver>` and then install ibm_db. If env variable IBM_DB_HOME is set, ibm_db will not download db2 v10.5 version of clidriver.

Yes, DB2 Connect Unlimited z/OS license is sufficient for odbc_cli to use.

Thanks.

**Comment by aroper23** [comment]
We obtained the DB2 11.1 license file from our customer (db2consv_zs.lic) and copied it to the ibm_db/installer/clidriver/license directory, but we still get the same error when connecting to or querying the DB2 database:

connection error:  [IBM][CLI Driver] SQL1598N  An attempt to connect to the database server failed because of a licensing problem.  SQLSTATE=42968

I ran testODBCConnection.sh with the connection parameters for our DB2 server, zipped up the trace files in a tarball, and will email it to you as soon as I can get someone to retrieve the file from the server and provide it to me.

Any assistance you can provide would be greatly appreciated.

**Comment by bimalkjha** [comment]
@aroper23 Seems your z/OS server is behind firewall. You need to first `telnet` z/OS host server from bluemix system and clear BSO. Then your app from bluemix server should be able to connect to z/OS server. Thanks.

**Comment by bimalkjha** [comment]
@aroper23 I mean to say when you run "telnet <zos host name or ipaddress>", provide database server userid and passwd to clear the firewall. If telnet throws error that host is not reachable or unknown then talk to Bluemix team. The z/OS server may not be accessible from the bluemix system. Thanks.

**Comment by aroper23** [comment]
Did you see something in the trace files I sent you that indicates we're connecting from bluemix? Neither the node.js application nor the DB2 database is hosted on bluemix. Would your suggestion to clear BSO only apply if we were using bluemix?

Is there something else that could be causing the behavior I've described and what's captured in the trace files?

The server running node.js is firewalled. In fact, we had to download the CLI drivers and access them via the IBM_DB_INSTALLER_URL environment variable because access to the internet is blocked from that server.

**Comment by aroper23** [comment]
To be clear: both the DB2 server and the server hosting the node.js application are behind the client's firewall.

**Comment by aroper23** [comment]
I reconfirmed that I am able to reach DB2 from the server hosting the node.js application using telnet on the port on which DB2 is listening, so I don't think there is any firewall blocking going on between the two.

**Comment by aroper23** [comment]
One more point of clarification: we see SYSLIC called on DB2 on the mainframe when we issue a query via ibm_db, presumably because the license file on the application server is not being processed. The SYSLIC check fails on the mainframe, and so the query fails.

**Comment by aroper23** [comment]
The solution to this issue was to use a DB2 Connect license file with the same version as that of the ODBC CLI, 10.5. After copying the license file (db2consv_zs.lic) for DB2 Connect 10.5 into the license directory we were able to connect to DB2 11.1, issue queries and get results back. The license file for DB2 11.1 was not compatible with ODBC CLI 10.5.
