### ISSUE TITLE
Local connection accepted, but not when pushed into Bluemix

### ISSUE THREAD

**Issue by RainerHo** [ibmdb/node-ibm_db#311]
@rhtpandeyIN, Hi I have a node.js (v8, npm v4) with ibm_db (v 2.1) connection established to db2 database. When I push this onto the Bluemix environment using cf I receive this error message:
Error: [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "XX.XX.XX.XX".  Communication function detecting the error: "selectForConnectTimeout".  Protocol specific error code(s): "115", "*", "*".  SQLSTATE=08001
The HOSTNAME as string was also rejected with a different error.

**Comment by uniquejava** [comment]
Have you read the README.md doc on the home page, 
```
To connect to dashDB in bluemix, just use below connection string:
connStr = "DATABASE=database;HOSTNAME=hostname;PORT=port;PROTOCOL=TCPIP;UID=username;PWD=passwd;Security=SSL";

```

Maybe you missed the `Security=SSL` part at the end of the string.

Here is a snippet from my code: 
```js
function initPool(db2_config, cb) {

  cn = format('DATABASE={db};HOSTNAME={host};PORT={port};PROTOCOL=TCPIP;UID={user};PWD={pass};Security=SSL', db2_config);

  // set to true then db2 driver will print debug logs.
  ibm_db.debug(!!db2_config.debug);

  pool.setMaxPoolSize(db2_config.maxPoolSize || 10);

  console.log('initializing pool, please wait ...');

  var result = pool.init(db2_config.poolSize || 1, cn);

  if (result != true) {
    return cb && cb(result);

  } else {
    console.log('pool initialized(' + db2_config.poolSize + ')');
    cb && cb(null);
  }

}

```
Hope it helps.
