### ISSUE TITLE
Deploy node-ibm_db with license file for DB2 on z/OS on Bluemix

### ISSUE THREAD

**Issue by georg90** [ibmdb/node-ibm_db#312]
Hi,

as the title says I want to connect to an DB2 on z/OS on Bluemix. On my local instance the connection is working as I copied my license file into `ibm_db/installer/clidriver/license`. On Bluemix I don't see a way to copy the license to this directory as node_modules is build while deployed with `cf push`

Can I somehow define a custom path to license file in my manifest or else?

Any help is appreciated!

**Comment by bimalkjha** [comment]
@georg90 First you need to push your app with db2connect license file. After ibm_db get installed on bluemix, write code in your app/ buildpack to copy license to clidriver/license folder. 
Many apps in bluemix is using same technique to use db2connect license file in bluemix. Thanks.

**Comment by georg90** [comment]
Thank you @bimaljha for replying. 

I copied the file to the folder, but it still gives me the same error.

The license file is working locally (i removed it from the file and readded it to test)

**Comment by bimalkjha** [comment]
@georg90 If possible, please delete the clidriver/cfgcache/conlic.bin file and try connection. Seems conlic.bin has the older info. Also, you can try by restarting the app. Thanks.

**Comment by georg90** [comment]
I deleted the file & restarted, still no change.

Also I added all license files I could find:

<img width="445" alt="image" src="https://user-images.githubusercontent.com/6489464/30647544-fd2ded30-9e1b-11e7-8a51-1f0926a6cf77.png">

Still the same error..

**Comment by bimalkjha** [comment]
From bluemix installation of ibm_db, open and edit the connection info in 'db2cli validate' command of  ibm_db/installer/testODBCConnection.sh file. Save and run this script to test connectivity and collect db2trace files. Please share output of this script file. You need to edit and put correct info for this command:
```
db2cli validate -database "sample:hotel.torolab.ibm.com:21169" -connect -user newton -passwd serverpass
```
Thanks.

**Comment by georg90** [comment]
```
Trace is turned on

===============================================================================
Client information for the current copy:
===============================================================================

Client Package Type       : IBM Data Server Driver For ODBC and CLI
Client Version (level/bit): DB2 v10.5.0.5 (special_33523/64-bit)
Client Platform           : Linux/X8664
Install/Instance Path     : /home/vcap/app/node_modules/ibm_db/installer/clidriver
DB2DSDRIVER_CFG_PATH value: <not-set>
db2dsdriver.cfg Path      : /home/vcap/app/node_modules/ibm_db/installer/clidriver/cfg/db2dsdriver.cfg
DB2CLIINIPATH value       : <not-set>
db2cli.ini Path           : /home/vcap/app/node_modules/ibm_db/installer/clidriver/cfg/db2cli.ini
db2diag.log Path          : /home/vcap/app/node_modules/ibm_db/installer/clidriver/db2dump/db2diag.log

===============================================================================
db2dsdriver.cfg schema validation for the entire file:
===============================================================================

Note: The validation utility could not find the configuration file 
db2dsdriver.cfg. The file is searched at 
"/home/vcap/app/node_modules/ibm_db/installer/clidriver/cfg/db2dsdriver.cfg".

===============================================================================
db2cli.ini validation for database "MYTABLE:HOSTNAME:15012":
===============================================================================

Note: The validation utility could not find the configuration file db2cli.ini. 
The file is searched at 
"/home/vcap/app/node_modules/ibm_db/installer/clidriver/cfg/db2cli.ini".

===============================================================================
db2dsdriver.cfg validation for database "MYTABLE:HOSTNAME:15012":
===============================================================================

Note: The validation utility could not find the configuration file 
db2dsdriver.cfg. The file is searched at 
"/home/vcap/app/node_modules/ibm_db/installer/clidriver/cfg/db2dsdriver.cfg".

===============================================================================
Connection attempt for database "MYTABLE:HOSTNAME:15012":
===============================================================================

[FAILED]: [IBM][CLI Driver] SQL1598N  An attempt to connect to the database server failed because of a licensing problem.  SQLSTATE=42968


===============================================================================
Error: The validation operation failed.
===============================================================================

===============================================================================
The validation is completed.
===============================================================================

Trace is turned off
Total number of trace records     : 28034
Trace truncated                   : NO
Trace wrapped                     : NO
Number of trace records formatted : 27885 (pid: 22699 tid 139724834232192 node: -1) 
Trace truncated                   : NO
Trace wrapped                     : NO
Total number of trace records     : 28034
Number of trace records formatted : 27885
Trace truncated                   : NO
Trace wrapped                     : NO
Total number of trace records     : 28034
Number of trace records formatted : 24
Trace truncated                   : NO
Trace wrapped                     : NO
Total number of trace records     : 28034
Number of trace records formatted : 149
```

**Comment by bimalkjha** [comment]
Please zip the generated files 1.fmt, 1.flw, 1.fmtc and 1.cli as a single zip file and mail to bimaljha@in.ibm.com. Thanks.

**Comment by bimalkjha** [comment]
Also, can you run the testODBCConnection.sh script in your local app setup where connection is working and from the 'db2cli validate' result, share the client version? Want to make sure the db2 client version used by local app and in bluemix app, both are same. Thanks.

**Comment by bimalkjha** [comment]
@georg90 Please check file permission of /home/vcap/app/node_modules/ibm_db/installer/clidriver/license/db2consv_ee.lic file and make it to 755. After permission change, test the connection. Thanks.

**Comment by georg90** [comment]
@bimaljha Thanks for the input, I'll check next week! 

Thanks for your help!

**Comment by bimalkjha** [comment]
@georg90 Your license files is for DB2 V11.1. Please get db2 connect license for DB2 V10.5. Your present license files are not compatible with ibm_db. Similar issue was reported by [issue 309](https://github.com/ibmdb/node-ibm_db/issues/309#issuecomment-332379420) and after using correct license file, they are able to establish connection with server. Thanks.

**Comment by georg90** [comment]
@bimaljha Thank you for being so persistent!

This was my error and the new license file fixed it. Maybe this should be pinned somewhere to make it easier for other people to figure it out?
