### ISSUE TITLE
Get ID of inserted row

### ISSUE THREAD

**Issue by jfconavarrete** [ibmdb/node-ibm_db#314]
Hello,

I've been trying to find a way to get the ID of a newly inserted row but with the current API that does not seem to be possible. 

My use case is as follows:
1. insert a record in table A and get it's id
2. use that id to insert a record in table B, referencing table A

Currently, what I do is insert in table A, and, before inserting in table B, do a query to get the id of the latest record inserted in table A. However, this gives problems when several rows are trying to be inserted in parallel.

Is it possible to get the ID assigned through a serial (autoincrementable) field after insertion?

Thanks

**Comment by rcsatheeshkumar** [comment]
Please try the  below logic using FINAL Table,

```
SELECT Employee_ID, Employee_name
        FROM FINAL TABLE (INSERT INTO Employee (Employee_name) VALUES (?);
```

**Comment by bimalkjha** [comment]
@jfconavarrete What do you mean by ID of a record in table. If it is ROWID then LUW server do not support ROWID: https://www.ibm.com/support/knowledgecenter/SSEPGG_11.1.0/com.ibm.db2.luw.apdv.java.doc/src/tpc/imjcc_cjvjdrwi.html

Your problem should be addressed using SQL and it has nothing to do with ibm_db package. You need to achieve your goal using SQL only. ibm_db just provides APIs to execute your SQL.

If you want to know the no of rows inserted in a table, you can use executeNonQuery() API as used in ibm_db/test/test-basic-test.js file:
```
    stmt.executeNonQuery([42, 'bimal'], function (err, ret) {
      if( err ) console.log(err);
      //else ret.closeSync(); // call closeSync() for execute().
      else console.log("Inserted row count = " + ret);
```
To select all rows from a table and insert into another, you can use SQL as below(from test-max-pool-size.js):
```
conn.querySync("insert into mtab2 (select * from mtab1)");
```
Closing it. thanks.

**Comment by jfconavarrete** [comment]
What I would like to achieve is to be able to get the value (id) that the database generated for a column defined as serial (autoincrementable) when a new row is inserted. 

What @rcsatheeshkumar proposed works and is what I'll use for now. Thank you very much for your solution :)

However, this makes the queries more complicated than they should be (as they have to include a select statement too). 

That is why I think it'd be a good idea if the ibm_db driver provided such value 
through the API [as other drivers do](https://www.npmjs.com/package/mysql#getting-the-id-of-an-inserted-row). For example, the [mysql driver](https://www.npmjs.com/package/mysql#getting-the-id-of-an-inserted-row) allows to do the following:

`connection.query('INSERT INTO posts SET ?', {title: 'test'}, function (error, results, fields) {`
`  if (error) throw error;`
`  console.log(results.insertId);`
`});`
