### ISSUE TITLE
ibm_db compatibility issue with node js on linux 64 bit

### ISSUE THREAD

**Issue by satyajitm93** [ibmdb/node-ibm_db#315]
emote: npm ERR! argv "/opt/nodejs/6.11.0/bin/node" "/usr/bin/npm-cli.js" "install" "--production"
remote: +-- body-parser@1.16.0
remote: npm ERR! node v6.11.0
remote: | +-- bytes@2.4.0
remote: npm ERR! npm  v3.10.10
remote: | +-- content-type@1.0.4
remote: npm ERR! code ELIFECYCLE
remote: | +-- debug@2.6.0
remote:
remote: | | `-- ms@0.7.2
remote: npm ERR! ibm_db@2.2.0 install: `node installer/driverInstall.js`
remote: | +-- depd@1.1.1
remote: npm ERR! Exit status 1
remote: | +-- http-errors@1.5.1
remote: npm ERR!
remote: | | +-- inherits@2.0.3
remote: npm ERR! Failed at the ibm_db@2.2.0 install script 'node installer/driverInstall.js'.
remote: | | +-- setprototypeof@1.0.2
remote: npm ERR! Make sure you have the latest version of node.js and npm installed.
remote: | | `-- statuses@1.3.1
remote: npm ERR! If you do, this is most likely a problem with the ibm_db package,
remote: | +-- iconv-lite@0.4.15
remote: npm ERR! not with npm itself.
remote: | +-- on-finished@2.3.0
remote: npm ERR! Tell the author that this fails on your system:
remote: | | `-- ee-first@1.1.1
remote: npm ERR!     node installer/driverInstall.js
remote: | +-- qs@6.2.1
remote: npm ERR! You can get information on how to open an issue for this project with:
remote: | +-- raw-body@2.2.0
remote: npm ERR!     npm bugs ibm_db
remote: | | `-- unpipe@1.0.0
remote: npm ERR! Or if that isn't available, you can get their info via:
remote: | `-- type-is@1.6.15
remote: npm ERR!     npm owner ls ibm_db
remote: |   +-- media-typer@0.3.0
remote: npm ERR! There is likely additional logging output above.
remote: |   `-- mime-types@2.1.17
remote:
remote: |     `-- mime-db@1.30.0
remote: npm ERR! Please include the following file with any support request:
remote: +-- cfenv@1.0.4

**Comment by rhtpandeyIN** [comment]
Hi @satyajitm93 , can you please share the repro steps? Are you able to install node-ibm_db using "npm install ibm_db" command?

If not please share the output of "npm install ibm_db" command. 
Thanks.

**Comment by satyajitm93** [comment]
yes, ibm_db got installed successfully, means i didn't get any error after doing npm install ibm_db. Only when am pushing it to azure it is throwing error.

I have tried below things:
1. Deployed application with ibm_db entry in package.json and push it azure
- got above error in the first post

2. Before deploying it azure i did npm install ibm_db ,no error, but on pushing it to azure 
- got above error in the first post 

3. Removed ibm db entry from package.json and did npm install ibm_db before pushing it azure.
- deployed successfully , but "Service not available" on accessing the application 

4. Removed ibm_db entry and deployed application to azure
 - deployed successfully and application is working fine but couldn't  access the db part since i have commented ibm_db call

**Comment by satyajitm93** [comment]
i have tried with changes mention by Bimal. Deployment is succesfully but on accessing the application got Service unavailable error.

**Comment by satyajitm93** [comment]
After doing the same, getting service not available issue after successful deployment.

**Comment by satyajitm93** [comment]
here is my package.json 

{
  "name": "NodeJSStarterApplication",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node server.js"
  },
  "dependencies": {
    "body-parser": "~1.16.0",
    "cfenv": "~1.0.x",
    "express": "~4.13.x",
    "nodemailer": "~4.0.1",
    "vcap_services": "~0.1.7",
    "ibm_db":"~2.2.0",
    "watson-developer-cloud": "~2.15.2"
     },
  "repository": {},
  "engines": {
    "node": "6.10.0"
  }
}

**Comment by satyajitm93** [comment]
Here is snapshot from my package.json

"dependencies": {
    "body-parser": "~1.16.0",
    "cfenv": "~1.0.x",
    "express": "~4.13.x",
    "nodemailer": "~4.0.1",
    "vcap_services": "~0.1.7",
    "ibm_db": "~2.2.0",
    "watson-developer-cloud": "~2.15.2"
     },
  "repository": {},
  "engines": {
    "node": "6.10.0"
  }

**Comment by bimalkjha** [comment]
@satyajitm93 Check now with your existing package.json. No need to change. Same app should work fine now using ibm_db@2.2.1. Thanks.
