### ISSUE TITLE
Connecting to DB2 on z/OS gives error: Reason Code "0x124C"("0203")""

### ISSUE THREAD

**Issue by georg90** [ibmdb/node-ibm_db#316]
When trying to connect to my DB2 on z/OS v10.5 I get this error:

```
[IBM][CLI Driver] SQL30020N  Execution of the command or SQL statement failed because of a syntax error in the communication data stream that will affect the successful execution of subsequent commands and SQL statements:  Reason Code "0x124C"("0203")"".  SQLSTATE=58009
```
using this connection string:
```
ibmdb.open("DATABASE=MYDB;HOSTNAME=MYHOSTNAME;UID=MYUSER;PWD=MYPWD;PORT=446", function(err, conn)
```

This error is already known: https://github.com/ibmdb/node-ibm_db/issues/144 but the solution didn't work for me. When reading about the error code I came across this: https://stackoverflow.com/questions/42768117/db2-connection-failure-reason-code-0x124c-0209

But since this should be a valid connection string, it should work, right?

**Comment by bimalkjha** [comment]
@georg90 May I know the version of z/OS server? Thanks.

**Comment by rhtpandeyIN** [comment]
Hi @georg90 , Are you still facing the same issue, or it got resolved? Please update. Thanks.

**Comment by georg90** [comment]
Hi @rhtpandeyIN ! Sorry, for not replying. I was asked by my DB admin to not go further on this, since it's not supported on the infrastructure I am using.

I mark this as closed.

Thank you @bimaljha for your support!
