### ISSUE TITLE
More information on Db2Connect license costs, purchasing, and install

### ISSUE THREAD

**Issue by ThePrez** [ibmdb/node-ibm_db#317]
I suggest the following information be added to the readme, where it is mentioned that a db2connect license is needed for connecting to Db2 for i:
- Db2Connect license and purchasing costs (link is good, even if it's a link to contact the right people)
- Clarity on whether anything is needed on the client, or if the licensing is all done on server side

In the meantime, please put this information into this issue so that people can find it. 

Thank you!

**Comment by bimalkjha** [comment]
2) If your Db2 for i server is activated to accept connection from any db2connect client, then no need to use license file in ibm_db. So, license is mainly enforced by the server to control connectivity not client. If your "Db2 for i" or "Db2 for z/OS" server is not activated to allow connection from any db2connect client, then you need to apply db2connect license at client side.

1) First check with your server admin to know you need a client side license or not. They might already have db2connect license that they can share with you.
Regarding purchasing cost of Db2Connect license - one should contact IBM Customer Support. All info are present here: https://www-05.ibm.com/support/operations/in/en/overview.html

Thanks.

**Comment by bimalkjha** [comment]
Info about requirement and installation of db2connect license is already documented here: https://github.com/ibmdb/node-ibm_db#for-zos-and-iseries-connectivity
Thanks.

**Comment by ThePrez** [comment]
Thanks!
