### ISSUE TITLE
querySync(query, params) is failing for 2.2.0 version

### ISSUE THREAD

**Issue by cjsaini** [ibmdb/node-ibm_db#318]
Hi,
I just updated ibm_db to 2.2.0 from 1.0.0. 
querySync started breaking with this version.

values passed to method are querySync(String,Array) -> querySync("select * from user where id = ?",[34245]);

If i am running query without passing parameters then it executes successfully: querySync("select * from user where id = 34245");

**Comment by bimalkjha** [comment]
@cjsaini Install ibm_db@2.2.1, update connection info in `ibm_db/test/config.testConnectionStrings.json` file and run `node ibm_db/test/test-basic-test.js` command. This test file is running same query as you have pasted in your post and it seems working fine. If you still see issue, please repro the issue by modifying test-basic-test.js file and share complete repro. Thanks.
