### ISSUE TITLE
multiple sql statements in query/querySync work but not prepare/prepareSync

### ISSUE THREAD

**Issue by amcintyre99** [ibmdb/node-ibm_db#319]
Using your test/bench-prepare-bind-execute-closeSync.js and trying to execute two sql statements in a single call like this:
`var stmt = db.prepareSync('select cast(? as INTEGER) as test from sysibm.sysdummy1; select cast(? as INTEGER) as test from sysibm.sysdummy1;');`

The first statement works but all text after the first semi-colon seems to be ignored.

According to DB2 doc, multiple statements on same handle should work:
"When a list of SQL statements is specified on the same statement handle, only one statement is issued at a time, starting with the first statement in the list. Each subsequent statement is issued in the order it appears."
https://www.ibm.com/support/knowledgecenter/SSEPGG_11.1.0/com.ibm.db2.luw.apdv.cli.doc/doc/t0007237.html

thanks!!

**Comment by rhtpandeyIN** [comment]
Hi @amcintyre99 , Please share full test repo for the same and with the output you are getting, also with the expected output. Thanks in advance.

**Comment by amcintyre99** [comment]
See above for the change I made to your test code. As I said, the first SQL statement works and anything after the semi-colon is simply ignored with no error msgs.

**Comment by amcintyre99** [comment]
I see your examples of query and querySync that support multiple statements per call.

Is there any way to get prepare and execute to support the same?

**Comment by bimalkjha** [comment]
@amcintyre99 "According to DB2 doc, multiple statements on same handle should work" and the example given by same doc is of SQLExecDirect. ibm_db APIs conn.query() and conn.querySync() uses SQLExecDirect internally and hence multiple queries using conn.query APIs works fine.
I do not see any example in DB2 doc where SQLPrepare is used to prepare multiple SQL statements. If you see any, could you please share the link?
I have used ODBC test case to pass multiple SQL statements in SQLPrepare() API and it accepts only single SQL and ignores rest. I think SQLPrepare() do not accept multiple SQL statements and hence ibm_db API conn.prepare() can also do not support that. You can see the following part of ODBC/CLI trace  : 
```
SQLPrepare( hStmt=1:1 )
    ---> Time elapsed - +1.200000E-005 seconds
( pszSqlStr="insert into table2 values (?, ?); insert into table1 values (?, ?);", cbSqlStr=68 )
( StmtOut="insert into table2 values (?, ?)" )

SQLPrepare( )
    <--- SQL_SUCCESS   Time elapsed - +4.000000E-005 seconds
```
Hence closing this issue. Please reopen if you get any example where ODBC API SQLPrepare() supports multiple SQL statements. Thanks.
