### ISSUE TITLE
question : list of ibm_db connection to db2 database

### ISSUE THREAD

**Issue by smartmouse** [ibmdb/node-ibm_db#32]
Does ibm_db support connection to db2 on z/OS?
or just windows, Linux and unix?
Thanks.

**Comment by avikalar** [comment]
You can use it to connect to a remote z/OS server from an LUW or Mac OS machine, but we don't support the client to run on a z/OS machine.

**Comment by avikalar** [comment]
Closing the issue, as it seems like it is resolved on your end.
