### ISSUE TITLE
TypeError: Error.captureStackTrace is not a function

### ISSUE THREAD

**Issue by tjx711** [ibmdb/node-ibm_db#322]
when i try to load the module
```
var ibmdb = require('ibm_db');
```
then get a compile error:
```
TypeError: Error.captureStackTrace is not a function
getFileName
node_modules/ibm_db/node_modules/bindings/bindings.js:126

  123 | }
  124 | 
  125 | // run the 'prepareStackTrace' function above
> 126 | Error.captureStackTrace(dummy)
  127 | dummy.stack
  128 | 
  129 | // cleanup
```

My node version is 8.5.0, ibm_db version is 2.2.1.

**Comment by bimalkjha** [comment]
@tjx711 I tested using node v 8.5.0 and 8.6.0 on MacOS. ibm_db@2.2.1 seems working fine all test cases executed successfully. Seems you are facing some different issue.
Also, the reported error is from `bindings` package and not `ibm_db` package. 
You can check installed version of this bindings package using below command:
```
/Users/bimaljha/nodework/installs> node -v
v8.6.0
/Users/bimaljha/nodework/installs> npm -v
4.1.2
/Users/bimaljha/nodework/installs> npm install ibm_db
.....
/Users/bimaljha/nodework/installs> npm list | grep bindings
  ├── bindings@1.2.1
```
Better to open issue [here](https://github.com/TooTallNate/node-bindings) with full details like npm version, platform, steps to repro, etc. Thanks.
