### ISSUE TITLE
Global leak detected and testcase fails

### ISSUE THREAD

**Issue by rjkuro** [ibmdb/node-ibm_db#323]
When I run Mocha testcases for my application enabling Mocha's global leak check, I saw the following message saying "global leak detected: key" and the testcase failed. 
```
  1 passing (721ms)
  1 failing

  1) test1
       testing :
     Error: global leak detected: key
      at ibmdb.open (index.js:21:12)
      at node_modules/ibm_db/lib/odbc.js:111:11
      at node_modules/ibm_db/lib/odbc.js:207:11
```

#### Environment
node-ibm_db version : 2.2.1
OS : macOS Sierra
Mocha version : 4.0.1

#### Reproduce steps 
1. Prepare Mocha testcase simply calling open and close. 
```
const ibmdb = require("ibm_db");

describe("test1", function () {
	it("testing ", function (done) {
		ibmdb.open(cn, (err, conn) => {
			if (err) {
				console.log("err", err);
			}
			ibmdb.close(conn);
			done();
		});
	});
});
```
2. run it with Mocha enabling global leak checking: 
./node_modules/.bin/mocha --check-leaks index.js

**Comment by rjkuro** [comment]
The cause looks to be in the close function in odbc.js. The "key" variable used in for loop doesn't have the "var" keyword. So the property is created on global object.
  
```
module.exports.close = function(db)
{
  if(db && typeof(db) === "object")
  {
    for(key in db)
    {
      delete db[key];
    }
...
```

**Comment by rhtpandeyIN** [comment]
Are you able to resolve it after changing it to "var"? Please share the prior investigation details with us.
Thanks.

**Comment by rjkuro** [comment]
@rhtpandeyIN yes, adding "var" resolved the problem. I logged the global object before/after the ibmdb.close() call, and confirmed no "key" property appeared for global object after adding "var".

**Comment by rhtpandeyIN** [comment]
@rjkuro , Thanks for the fix, Please feel free to open a PR, with matching following criteria and requirements:
https://github.com/ibmdb/node-ibm_db#contributing-to-the-node-ibm_db

**Comment by rjkuro** [comment]
@rhtpandeyIN sure, I will prepare PR. I already started internal process within my project/company. But the process sometimes takes long time. So I thought raising issues may be quicker. I can work on PR after I get approval.
