### ISSUE TITLE
Closing connection twice causes closing pool not to complete

### ISSUE THREAD

**Issue by rjkuro** [ibmdb/node-ibm_db#324]
When I accidentally closed the connection twice that I retrieved from pool, both the close calls finished without error. But then I tried to close the connection pool, and it took very long time and call back was never called. 

#### Environment
node-ibm_db version : 2.2.1
OS : macOS Sierra

#### Reproduce steps 
1. Prepare Mocha testcase that opens the pool, closes the connection twice, and then closes the pool. 
```
const Pool = require("ibm_db").Pool;
const pool = new Pool();

describe("test closing connection twice", function () {
	it("testing ", function (done) {
		pool.open(cn, (err, conn) => {
			if (err) {
				console.log("err", err);
				done();
				return;
			}
			conn.close(function (err2) {
				if (err2) {
					console.log("err2", err2);
					done();
					return;
				}
				conn.close(function (err3) {
					if (err3) {
						console.log("err3", err3);
						done();
						return;
					}
					console.log("going to close");
					pool.close(function (err4) {
						if (err4) {
							console.log("err4", err4);
							done();
							return;
						}
						done();
					});
				});
			});
		});
	});
});
```
2. run it with Mocha setting timeout : 
./node_modules/.bin/mocha --timeout 60000 index.js

You will see the test ends after 60 secs with error message complaining the done() callback was never called. 
```
  test closing connection twice
going to close
    1) testing


  0 passing (1m)
  1 failing

  1) test closing connection twice
       testing :
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

```
This means pool.close() didn't fire the callback and took 60 secs. 

#### Expected behavior
I would like ibmdb to allow calling close() more than once. Because it's convenient to call close() frequently to make sure the connection is closed. To ensure calling close() exactly once, I had to wrap the connection with my custom class. That's not difficult but requires extra lines of code. It's great for ibmdb to take care about that.

**Comment by bimalkjha** [comment]
@rjkuro Install the latest code from git using `npm install git+https://git@github.com/ibmdb/node-ibm_db.git` command and verify. Thanks.
