### ISSUE TITLE
ODBCStatement has closeSync, but no async method

### ISSUE THREAD

**Issue by rjkuro** [ibmdb/node-ibm_db#325]
When I prepare statement and call executeNonQuery(), I need to close the statement so that the resources allocated for the statement should be freed. I can do this by calling closeSync(), but to my knowledge, it's not clear how long it takes to close the statement, so I need async method in order to avoid the thread to block waiting indefinitely long. On current version 2.2.1, ODBCStatement class doesn't implement the async version of close method.

**Comment by bimalkjha** [comment]
@rjkuro stmt.closeSync() is very fast and doesn't take much time. It finishes within fraction of second and does not wait indefinitely. So, you can use it. We have not felt any need of async function due to that reason. But your request is valid and we'll add async method soon in ibm_db. Thanks.

**Comment by bimalkjha** [comment]
@rjkuro ibm_db@2.6.1 has added this support. Please install latest ibm_db version 2.6.1 and verify it. Thanks.
