### ISSUE TITLE
Unusual Memory Utilization in Production

### ISSUE THREAD

**Issue by genesislabs** [ibmdb/node-ibm_db#326]
Hey,

Thought of sharing some observations in production that may be of use for future development and improvements to the library. 

My team has used the ibm_db library (version 1.0) with a nodejs runtime (2048 MB allocated memory) running in a bluemix environment. The application is programmed to listen to an mqtt broker with an expected message frequency of approx 10 messages per hour. Not a particularly heavy load scenario - nevertheless, our application would run out of memory which would lead to crash.

Apart from common application programming issues such as nested callbacks - there was nothing particularly unusual in the way the library was used. The team had used the recommended way of using the library (as per guidelines in the readme file) - open a pool, open a connection, use connection to fire query, close connection. 

After a couple of weeks of processing mqtt messages, the applications memory would build up but never get released. All investigation leads to a memory leak scenario - but various profiling tools did not help in pinpointing the issue to ibm_db.

using other client functions such as cleanup (to clean stale connections in the pool) did not help release memory. At this point we suspect it might be the way the library handles memory allocation and deallocation. 

Configuring the application to make use of clustering has resolved the issue in production. But, clustering itself can lead to unwanted application behavior at high volumes. 

Thought I would share these observations with the community as part of general responsibilities of participating in open source initiatives.

Thanks.

**Comment by bimalkjha** [comment]
@genesislabs Please use ibm_db version 2.2.1 in bluemix and check memory utilisation. We have fixed many memory leak issues since ibm_db version 1.0. So, please use latest ibm_db and have your input. Thanks.
