### ISSUE TITLE
Library not loaded error on running on mac machines

### ISSUE THREAD

**Issue by tarzzz** [ibmdb/node-ibm_db#329]
Hi team,

I am working on an electron app, which uses `node-ibm_db`. I am getting 'Library not loaded' error while trying to run the app on other's machines. There are no errors while building the app.

Screenshot:
![image](https://user-images.githubusercontent.com/1546532/31481897-540b9be2-af43-11e7-9cc2-d3efa98200bf.png)

It seems that the library location is being absolute-referenced to my local machine path instead of linking to the assets in the app itself. 

This issue is only occuring for mac builds (windows and linux binaries are working fine), so I figured it _might_ be arising from `bindings.gyp`. Any suggestions in this regard would be really helpful.

**Comment by bimalkjha** [comment]
@tarzzz Please share the steps to reproduce the issue on mac starting with `npm install electron`.
You can set below env vars as a workaround and verify the error:
```
export DYLD_LIBRARY_PATH=/Users/tarun/plotly/plotly-database-connector/node_modules/ibm_db/installer/clidriver/lib:/Users/tarun/plotly/plotly-database-connector/node_modules/ibm_db/installer/clidriver/bin:$DYLD_LIBRARY_PATH
export PATH=$PATH: $DYLD_LIBRARY_PATH
```
Thanks.

**Comment by tarzzz** [comment]
@bimaljha Here is a reproducible version:

1. Create a blank node app in a new directory:

```
$ mkdir new_app && cd new_app
```

2. Add a barebones `package.json`:

```
{
  "name": "A",
  "description": "B",
  "version": "1.0.0",
  "dependencies": {
    "ibm_db": "^2.2.1"
  }
}
```

3. run npm install: `npm i`
4. cd to the installed `ibm_db` module:

```
$ cd node_modules/ibm_db/build/Release
```

5. Grep for db2:
```
grep db2 -r odbc_bindings.node
```

You will see something like this:

```
~/new_proj/node_modules/ibm_db/build/Release$ ack db2 -r odbc_bindings.node

h/Users/tarun/new_proj/node_modules/ibm_db/installer/clidriver/lib/libdb2.dylib
                                                                               03/usr/lib/libc++.1.dylib
                                                                                                        8<�/usr/lib/libSystem.B.dylib& ��)UH��AWAVATSH�� I����H�}�H����H�=�1�1��9�I���g�H�5�1ҹ����H���'�H��H���L��H���n�L���l��H���G�� �H�5@1ҹ����H�����H��H�������W�H���p��L��H��H�������
```

Here, the path is absolute in `binding.node`, which will fail on other machines (when the compiled app is distributed).

**Comment by tarzzz** [comment]
Update: it seems the issue is being caused by this line: https://github.com/ibm/node-ibm_db/blob/master/installer/driverInstall.js#L393

Which sets absolute library path instead of relative `@loader_path` in `change_name_tool`
For reference: https://stackoverflow.com/a/2164689/3310016 

I can create a PR to fix this issue..

**Comment by bimalkjha** [comment]
Latest push on GitHub has fixed this issue. Thanks.

**Comment by bimalkjha** [comment]
Another simpler way to install ibm_db for the use with electron on vscode is, install ibm_db using command: `npm install ibm_db --dist-url=https://atom.io/download/electron`
If you have already installed ibm_db then try below steps:
```
cd .../node_modules/ibm_db
rm -rf build
npm install --dist-url=https://atom.io/download/electron
node test/test-basic-test.js
```
Thanks.

**Comment by msimini** [comment]
Im having this issue

But the fix suggested above didnt work for me. Any suggestion ?

**Comment by msimini** [comment]
> @tarzzz Please share the steps to reproduce the issue on mac starting with `npm install electron`.
> You can set below env vars as a workaround and verify the error:
> 
> ```
> export DYLD_LIBRARY_PATH=/Users/tarun/plotly/plotly-database-connector/node_modules/ibm_db/installer/clidriver/lib:/Users/tarun/plotly/plotly-database-connector/node_modules/ibm_db/installer/clidriver/bin:$DYLD_LIBRARY_PATH
> export PATH=$PATH: $DYLD_LIBRARY_PATH
> ```
> Thanks.

It worked fine on the develop environment.

Have an idea how to move this to a solution on the electron package app ? 
When a run using the app file from the electron package got the same error

**Comment by bimalkjha** [comment]
@msimini This issue is fixed in the latest code on github and it would be available in the next release of ibm_db. 
You can test the solution by installing ibm_db using below command:
```
npm install git+https://git@github.com/ibmdb/node-ibm_db.git
```
You can put the url of this repo in your package.json file to install ibm_db from this location. thanks.
