### ISSUE TITLE
test-issue253 is failing

### ISSUE THREAD

**Issue by al-k21** [ibmdb/node-ibm_db#331]
I am seeing  a failure after `v2.1.0` release: 
```
Running test for [DB2] : test-issue253 ... fail  
 Stdout:  

 Stderr:  

assert.js:81
  throw new assert.AssertionError({
  ^
AssertionError: '[IBM][CLI Driver][DB2/AIX64] SQL0180N  The syntax of the string representation of a datetime value is incorrect.  SQLSTATE=2200 == '[IBM][CLI Driver][DB2/LINUXX8664] SQL0180N  The syntax of the string representation of a datetime value is incorrect.  SQLSTATE
    at /home/alk/tmp/node-ibm_db/test/test-issue253.js:24:20
    at /home/alk/tmp/node-ibm_db/lib/odbc.js:367:61
```
##### Useful Links:
- [#253](https://github.com/ibmdb/node-ibm_db/issues/253)
- [test-issue253.js](https://github.com/ibmdb/node-ibm_db/blob/master/test/test-issue253.js)

**Comment by rhtpandeyIN** [comment]
@al-k21 , thanks for reporting, I think you are facing this issue on Windows platform only, Am I right?

**Comment by al-k21** [comment]
@rhtpandeyIN I have reproduced this error on `rhel7` manually, but I'm also seeing the same failure on Jenkins on all distribution of Linux and Windows.

**Comment by rhtpandeyIN** [comment]
OK, got it. Well this error is because of assertion check, this has nothing to do with any functionality of node-ibm_db. Well I will fix this issue. Thanks for bringing this into notice and Thanks again for your efforts.

**Comment by rhtpandeyIN** [comment]
Well, I would like to ask you a favor, If you don't mind :) 
As you have already tested it on different platforms, would you be able to share those error outputs with us (mentioning the platforms), that would be a great help.

**Comment by al-k21** [comment]
It's the same failure on all this machines: 
![image](https://user-images.githubusercontent.com/29542357/31612082-738cdc0c-b276-11e7-8a0f-33e897672d92.png)

I am also seeing `libpam` eeror on `rhel7_x86`:
```

**Comment by rhtpandeyIN** [comment]
Error would be the same, but the error content must be the different depending on the specific platform.
I am referring below error line : 

>AssertionError: '[IBM][CLI Driver][DB2/AIX64] SQL0180N  The syntax of the string representation of a datetime value is incorrect.  SQLSTATE=2200 **==** '[IBM][CLI Driver][DB2/LINUXX8664] SQL0180N  The syntax of the string representation of a datetime value is incorrect.  SQLSTATE

The content in the right side of the "==" operator will remains same, but the left side content will change according to the platform.

"I need this information specifically".

**Comment by al-k21** [comment]
The console logs look identical to me... PTAL
```
sles12:
AssertionError: '[IBM][CLI Driver][DB2/AIX64] SQL0180N  The syntax of the string representation of a datetime value is incorrect.  SQLSTATE=2200 == '[IBM][CLI Driver][DB2/LINUXX8664] SQL0180N  The syntax of the string representation of a datetime value is incorrect.  SQLSTATE

aix61:
AssertionError: '[IBM][CLI Driver][DB2/AIX64] SQL0180N  The syntax of the string representation of a datetime value is incorrect.  SQLSTATE=2200 == '[IBM][CLI Driver][DB2/LINUXX8664] SQL0180N  The syntax of the string representation of a datetime value is incorrect.  SQLSTATE

win:
AssertionError: '[IBM][CLI Driver][DB2/AIX64] SQL0180N  The syntax of the string representation of a datetime value is incorrect.  SQLSTATE=2200 == '[IBM][CLI Driver][DB2/LINUXX8664] SQL0180N  The syntax of the string representation of a datetime value is incorrect.  SQLSTATE
```

**Comment by rhtpandeyIN** [comment]
Yes, it seems same, Oh then it's picking based on your CLI driver, I think you are using the same CLI driver for all platforms. Well no worry I will remove the platform specific part from the error content else that will make so many combinations.

**Comment by gibfahn** [comment]
>Well no worry I will remove the platform specific part from the error content else that will make so many combinations.

Maybe remove it from the error test rather than from the error itself (sounds like it would be useful to know which version of the CLI driver people are using).

**Comment by bimalkjha** [comment]
@al-k21 This test case fails only if target database server is other than DB2/LINUXX8664. You can ignore this failure as of now. It is only test case issue not a bug. I think @rhtpandeyIN will correct the test file. Thanks.

**Comment by rhtpandeyIN** [comment]
@gibfahn ,
>Maybe remove it from the error test rather than from the error itself 
I think I didn't explain it well before, sorry for the confusion. What I meant was, while checking the error content in the test case (at the time of assertion) I will not check the driver specific part, as this test case do not depends on any driver specific situations hence error will be generic and same for all (and I am not going to change error returned by the driver). 
This test case is failing because of "name/platform-name of the driver" not because of the error message or error code. 
To be very specific it's just a test case assertion change not the driver related or code related changes. I hope now I am clear. Thanks.

**Comment by rhtpandeyIN** [comment]
@al-k21 , I request you to please replace the test case (test-issue253.js) content with the following file content, and let me know the output. 
[https://github.com/rhtpandeyIN/node-ibm_db/blob/master/test/test-issue253.js](https://github.com/rhtpandeyIN/node-ibm_db/blob/master/test/test-issue253.js)

I think it should work now, I have tested it on Windows and it's working fine now. I am unable to access my other machines right now, hence can not test, any help would be great full. Thanks :)

**Comment by al-k21** [comment]
@rhtpandeyIN still seeing  an error on Linux:
```

**Comment by al-k21** [comment]
I am seeing this a lot:
```
Stderr:  
/home/alk/tmp/node-ibm_db/lib/odbc.js:1053
      self._bind(params, function (err) {
           ^

Error: Could not allocate enough memory for params in ODBC::GetParametersFromArray.
    at Error (native)
    at /home/alk/tmp/node-ibm_db/lib/odbc.js:1053:12
    at SimpleQueue.next (/home/alk/tmp/node-ibm_db/lib/simple-queue.js:34:5)
    at SimpleQueue.maybeNext (/home/alk/tmp/node-ibm_db/lib/simple-queue.js:22:10)
    at /home/alk/tmp/node-ibm_db/lib/simple-queue.js:37:12
    at /home/alk/tmp/node-ibm_db/lib/odbc.js:1400:14
```
Can you comment ?

**Comment by rhtpandeyIN** [comment]
@al-k21  please try with the new fix code, please replace the test case (test-issue253.js) content with the following file content, and let me know the output.
https://github.com/rhtpandeyIN/node-ibm_db/blob/master/test/test-issue253.js

**Comment by al-k21** [comment]
`test-issue253` is now passing:
```bash
Running test 29 for [DB2] : test-issue253 ... success 
```

Thank you @rhtpandeyIN ! 
Closing this, reopen if needed.
