### ISSUE TITLE
 test-call-async is faliing on WIndows

### ISSUE THREAD

**Issue by al-k21** [ibmdb/node-ibm_db#333]
Seeing this  failure on WIndows:
```node
Running test 12 for [DB2] : test-call-async ... fail
 Stdout:

 Stderr:

C:\Users\gb120491\tmp\node-ibm_db\lib\odbc.js:614
    result = self.conn.querySync(query);
                       ^
Error: [IBM][CLI Driver][DB2/AIX64] SQL0454N  The signature provided in the definition for routine "JTCJS11.PROC1" matches the signature of some other routine.  LINE NUMBER=1.  SQLSTATE=42723

    at Error (native)
    at Database.querySync (C:\Users\gb120491\tmp\node-ibm_db\lib\odbc.js:614:24)
    at C:\Users\gb120491\tmp\node-ibm_db\test\test-call-async.js:20:10
    at C:\Users\gb120491\tmp\node-ibm_db\lib\odbc.js:111:11
    at C:\Users\gb120491\tmp\node-ibm_db\lib\odbc.js:208:11
```
Can you comment @rhtpandeyIN ?

**Comment by rhtpandeyIN** [comment]
For me both are working fine: (test-call-stmt.js & test-call-async.js)

```
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

E:\IBM\issue331\node_modules\ibm_db>cd test

E:\IBM_WORK_TRACK\2017\10Oct2017\issue331\node_modules\ibm_db\test>node test-call-stmt.js
Output Parameters V2 =  1 , V3 =  verygood
done

E:\IBM\issue331\node_modules\ibm_db\test>node test-call-async.js
created proc1...

return value =  4 verygood
done

```

Can you please share the platform, nodejs version and clidriver version specific information with us.

**Comment by rhtpandeyIN** [comment]
Closing the other issue and making it's reference here.

**Comment by al-k21** [comment]
OS: Windows 7
Node: v6.11.4

Can you tell me how to check `clidriver` ? @rhtpandeyIN

**Comment by rhtpandeyIN** [comment]
My sincere apologies for late reply, well I was asking for the the node-ibm_db version and how you are installing it. Are you facing the same problem with latest node-ibm_db (try to install it using "npm install ibm_db" command).

One more thing, if possible please provide your "DB2" version against which you are running these test cases.

**Comment by rhtpandeyIN** [comment]
Well to me it's looking like some kind of configuration or system related issue, as I ran the same test cases against MAC, Windows, Linux systems and with different node versions, node-ibm_db versions and I never got the above mentioned error. 

Could you please once run this test case alone (go inside test/ directory and run "node test-call-async.js")?

It should give below output:
```
ibm_db\test>node test-call-async.js
created proc1...

return value =  4 verygood
done
```

**Comment by rhtpandeyIN** [comment]
Closing the issue now (resolved / abandoned).
