### ISSUE TITLE
Need an example of prepared statement (non-query) re-use

### ISSUE THREAD

**Issue by dongryphon** [ibmdb/node-ibm_db#338]
I am trying to run an INSERT via prepared statement and reuse that statement (to insert blocks of records) but the 2nd block no matter how many records are in it is always getting a PK violation as if the binding parameters from the first `executeNonQuery` are still being used on the 2nd call

**Comment by rhtpandeyIN** [comment]
Hi @dongryphon , can you please share your test case for the same. Need to figure out what exactly your requirements are.

**Comment by dongryphon** [comment]
Thanks @rhtpandeyIN - I was trying to understand the proper life-cycle of a prepared statement and there are two important aspects that the examples do not cover: reuse and final cleanup (if any on either is required).

A starter might be:

    // Use promisfy or wrap callbacks to enable "await":
    async function prepare (conn, sql) {
        return new Promise((resolve, reject) => {
            conn.prepare(sql, (err, result) => {
                err ? reject(err) : resolve(result);
            });
        });
    }

    async function executeNonQuery (conn, ...bindings) {
        return new Promise((resolve, reject) => {
            conn.executeNonQuery(bindings, (err, result) => {
                err ? reject(err) : resolve(result);
            });
        });
    }

    async truncate (conn, ...tables) {
        let stmt = await prepare(conn, 'TRUNCATE TABLE ? IMMEDIATE');

        for (let name of tables) {
            let result = await executeNonQuery(conn, name);
            //TODO what about "result"? what about "stmt" before reuse?
        }

        //TODO what about stmt?
    }

    truncate('Foo', 'Bar', 'Zip');

The specific SQL statement is not my concern so much as the `TODO` comments.

**Comment by rhtpandeyIN** [comment]
Hi @dongryphon, I checked your code snippet and below are my findings and review comments.

1) There is minor code problem in this particular function : 
>async truncate (conn, ...tables) {
>let result = await executeNonQuery(**conn,** name);

**You can not pass "conn" varibale to executeNonQuery function, rather you need to pass "stmt" argument here.**

**Most of the ibm_db functions takes care of closing of "stmt" statement internally (like executeNonQuery does), so you need not to manually close "stmt" statement. **

2) Please check the below code snippet, it's working fine. (I modified it little bit for my convenience). 

```
var fs = require('fs'),
ibmdb = require('ibm_db')
, cn="DRIVER={DB2 ODBC Driver};DATABASE=SAMPLE;HOSTNAME=localhost;UID=myuserid;PWD=mypassword;PORT=50000;PROTOCOL=TCPIP";

var TABLE_NAME = "testissue338";

ibmdb.open(cn, function (err,conn) {
    if (err) {
        return console.log(err);
    }

    conn.querySync("create table " + TABLE_NAME + " (empId int, name char(20))");
    //create table before testing.

    var data = [1,
                2,
                3];

    var sql1 = "insert into " + TABLE_NAME + " (empId) VALUES (?)";

    truncate(conn, data);

    async function truncate (conn, data) {
        let stmt = await prepare(conn, sql1);

        for (let name of data) {
            //let result = await executeNonQuery(conn, name);
            //TODO what about "result"? what about "stmt" before reuse?
            //WRONG arguments.
            let result = await executeNonQuery(stmt, name);
            //REVIEW COMMENT: you should pass "stmt", not "conn".
        }
    }

    // Use promisfy or wrap callbacks to enable "await":
    async function prepare (conn, sql) {
        return new Promise((resolve, reject) => {
            conn.prepare(sql, (err, result) => {
                err ? reject(err) : resolve(result);
            });
        });
    }

    async function executeNonQuery (stmt, ...bindings) {
        return new Promise((resolve, reject) => {
            stmt.executeNonQuery(bindings, (err, result) => {
                err ? reject(err) : resolve(result);
            });
        });
    }

});

```

**OUTPUT : **

C:\windows\system32>db2 select * from testissue338

EMPID       NAME
----------- --------------------
          1 -
          2 -
          3 -

  3 record(s) selected.

**Comment by rhtpandeyIN** [comment]
I hope this will clarify the issue, if you have further queries please feel free to ask.
