### ISSUE TITLE
Error: Could not locate the bindings file. Tried:

### ISSUE THREAD

**Issue by Sureshkadad** [ibmdb/node-ibm_db#339]
Hi, I am trying to run the following -

var ibmdb = require("ibm_db")

I have installed ibm_db on linux. I am getting the below error when i run the above command:

/home/mynode/node_modules/ibm_db/node_modules/bindings/bindings.js:91
throw err
^

Error: Could not locate the bindings file. Tried:
â /home/mynode/node_modules/ibm_db/build/odbc_bindings.node
â /home/mynode/node_modules/ibm_db/build/Debug/odbc_bindings.node
â /home/mynode/node_modules/ibm_db/build/Release/odbc_bindings.node
â /home/mynode/node_modules/ibm_db/out/Debug/odbc_bindings.node
â /home/mynode/node_modules/ibm_db/Debug/odbc_bindings.node
â /home/mynode/node_modules/ibm_db/out/Release/odbc_bindings.node
â /home/mynode/node_modules/ibm_db/Release/odbc_bindings.node
â /home/mynode/node_modules/ibm_db/build/default/odbc_bindings.node
â /home/mynode/node_modules/ibm_db/compiled/6.11.2/linux/x64/odbc_bindings.node
at bindings (/home/mynode/node_modules/ibm_db/node_modules/bindings/bindings.js:88:9)
at Object. (/home/mynode/node_modules/ibm_db/lib/odbc.js:31:31)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object. (/home/mynode/test_conn.js:3:13)

Please help.

**Comment by rhtpandeyIN** [comment]
Hi @Sureshkadad , Could you please share more details, like: Node version, How you are installing node-ibm_db, node-ibm_db version, and since when you are facing this problem.

**Comment by krisbaehr** [comment]
I'm having the same issue here: Windows 10 64 bit, Node 6.11.2, ibm_db 2.2.1. Looks like it's running into a certificate issue. Any way to get around that with npm?

C:\node\projects\users>npm install ibm_db --save

> ibm_db@2.2.1 install C:\node\projects\users\node_modules\ibm_db
> node installer/driverInstall.js

Downloading DB2 ODBC CLI Driver from https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/ntx64_odbc_cli.zip...

**{ Error: self signed certificate in certificate chain
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:610:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38) code: 'SELF_SIGNED_CERT_IN_CHAIN' }**
local_users@0.0.0 C:\node\projects\users
`-- ibm_db@2.2.1
  +-- bindings@1.2.1
  +-- fstream@1.0.11
  | +-- graceful-fs@4.1.11
  | +-- mkdirp@0.5.1
  | | `-- minimist@0.0.8
  | `-- rimraf@2.6.2
  |   `-- glob@7.1.2
  |     +-- fs.realpath@1.0.0
  |     +-- inflight@1.0.6
  |     | `-- wrappy@1.0.2
  |     +-- minimatch@3.0.4
  |     | `-- brace-expansion@1.1.8
  |     |   +-- balanced-match@1.0.0
  |     |   `-- concat-map@0.0.1
  |     +-- once@1.4.0
  |     `-- path-is-absolute@1.0.1
  +-- nan@2.3.5
  +-- q@1.4.1
  +-- request@2.81.0
  | +-- aws-sign2@0.6.0
  | +-- aws4@1.6.0
  | +-- caseless@0.12.0
  | +-- combined-stream@1.0.5
  | | `-- delayed-stream@1.0.0
  | +-- extend@3.0.1
  | +-- forever-agent@0.6.1
  | +-- form-data@2.1.4
  | | `-- asynckit@0.4.0
  | +-- har-validator@4.2.1
  | | +-- ajv@4.11.8
  | | | +-- co@4.6.0
  | | | `-- json-stable-stringify@1.0.1
  | | |   `-- jsonify@0.0.0
  | | `-- har-schema@1.0.5
  | +-- hawk@3.1.3
  | | +-- boom@2.10.1
  | | +-- cryptiles@2.0.5
  | | +-- hoek@2.16.3
  | | `-- sntp@1.0.9
  | +-- http-signature@1.1.1
  | | +-- assert-plus@0.2.0
  | | +-- jsprim@1.4.1
  | | | +-- assert-plus@1.0.0
  | | | +-- extsprintf@1.3.0
  | | | +-- json-schema@0.2.3
  | | | `-- verror@1.10.0
  | | |   `-- assert-plus@1.0.0
  | | `-- sshpk@1.13.1
  | |   +-- asn1@0.2.3
  | |   +-- assert-plus@1.0.0
  | |   +-- bcrypt-pbkdf@1.0.1
  | |   +-- dashdash@1.14.1
  | |   | `-- assert-plus@1.0.0
  | |   +-- ecc-jsbn@0.1.1
  | |   +-- getpass@0.1.7
  | |   | `-- assert-plus@1.0.0
  | |   +-- jsbn@0.1.1
  | |   `-- tweetnacl@0.14.5
  | +-- is-typedarray@1.0.0
  | +-- isstream@0.1.2
  | +-- json-stringify-safe@5.0.1
  | +-- oauth-sign@0.8.2
  | +-- performance-now@0.2.0
  | +-- qs@6.4.0
  | +-- stringstream@0.0.5
  | +-- tough-cookie@2.3.3
  | | `-- punycode@1.4.1
  | +-- tunnel-agent@0.6.0
  | `-- uuid@3.1.0
  +-- targz@1.0.1
  | `-- tar-fs@1.16.0
  |   +-- chownr@1.0.1
  |   +-- pump@1.0.2
  |   | `-- end-of-stream@1.4.0
  |   `-- tar-stream@1.5.5
  |     +-- bl@1.2.1
  |     `-- xtend@4.0.1
  `-- unzipper@0.7.6
    +-- binary@0.3.0
    | +-- buffers@0.1.1
    | `-- chainsaw@0.1.0
    |   `-- traverse@0.3.9
    +-- bluebird@3.4.7
    +-- buffer-indexof-polyfill@1.0.1
    +-- duplexer2@0.1.4
    | `-- readable-stream@2.3.3
    |   `-- string_decoder@1.0.3
    +-- listenercount@1.0.1
    +-- readable-stream@2.1.5
    | +-- buffer-shims@1.0.0
    | +-- core-util-is@1.0.2
    | +-- isarray@1.0.0
    | +-- process-nextick-args@1.0.7
    | +-- string_decoder@0.10.31
    | `-- util-deprecate@1.0.2
    `-- setimmediate@1.0.5

**Comment by WurstCommander** [comment]
Hi,

I got the same issue, how did you debug to the errormessage

```
{ Error: self signed certificate in certificate chain
at Error (native)
at TLSSocket. (_tls_wrap.js:1092:38)
at emitNone (events.js:86:13)
at TLSSocket.emit (events.js:185:7)
at TLSSocket._finishInit (_tls_wrap.js:610:8)
at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38) code: 'SELF_SIGNED_CERT_IN_CHAIN' }
```

?

sorry kind of nodejs newbie over here.

**Comment by krisbaehr** [comment]
@WurstCommander the message was just the standard output from the npm install command. I'm a newbie as well.

**Comment by rhtpandeyIN** [comment]
Hi @WurstCommander , @krisbaehr , @Sureshkadad , I think this is coming because of "node-gyp" module, here is the issue link :  [node-gyp issue 695](https://github.com/nodejs/node-gyp/issues/695)

Following are the workaround for this issue :
1) [Setting NODE_TLS_REJECT_UNAUTHORIZED=0 in the environment](https://github.com/nodejs/node-gyp/issues/448#issuecomment-44061248)  (But I would suggest before setting this into your environment, read the [document and suggestions](https://github.com/nodejs/node-gyp/issues/448#issuecomment-44061248) carefully)

2) If you have a firewall that does ssl-decrypt and it can't be turned off.
Then use "**npm config set strict-ssl false**". It should work with Electron too.

Thanks, closing the issue now. Please feel free to post your queries here.
