### ISSUE TITLE
[IBM][CLI Driver] SQL30081N - Error - SQLSTATE=08001 

### ISSUE THREAD

**Issue by WurstCommander** [ibmdb/node-ibm_db#340]
Hi,

after trying to connect to a DB2 instance I get the following error:

**Error message:**
```
{ Error: [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the erro
r was detected: "10.64.205.236".  Communication function detecting the error: "recv".  Protocol specific error code(s): "*", "*", "0".  SQLSTATE=08001
  at Error (native)
  errors: [],
  error: '[node-ibm_db] SQL_ERROR',
  message: '[IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the e
rror was detected: "realserverip".  Communication function detecting the error: "recv".  Protocol specific error code(s): "*", "*", "0".  SQLSTATE=08001\r\n',
  state: '08007' }
```

**Javascript-Code:**

```
var ibmdb = require('ibm_db');

ibmdb.open("DRIVER={DB2 ODBC Driver};DATABASE=mydb;UID=myuser;PWD=mypass;HOSTNAME=myhost;PORT=50000;PROTOCOL=TCPIP;", function(err, conn)
{
  if (err) return console.log(err);
  
  conn.query('select 1 from sysibm.sysdummy1', function (err, data) {
    if (err) console.log(err);
    else console.log(data); 
    conn.close(function () {
      console.log('done');
    });
  });
});
```

I can connect to the DB2 Instance via DBVisualizer and multiple Java apps (JDBC) / JBoss Servers without any problems.

I tried changing the Protocol PROTOCOL=SOCKETS, without any success. I tried removing the driver tag and multiple other variations of the connection string to no success.

Here are the drivers I used for JDBC normally and they work:

> DB2
> DSN11015
> IBM Data Server Driver for JDBC and SQLJ
> 3.69.24

**Specs:**
Windows 7 64bit
NodeJS 64bit v6.9.4
ibm_db 2.2.1

Reminder: It doesn't seem to be a problem regarding licenses (no connection error) but I don't have a licence file installed.

**Comment by rhtpandeyIN** [comment]
Hi @WurstCommander ,
```
SQL30081N A communication error has been
detected. Communication protocol being used: "TCP/IP". Communication
API being used: "SOCKETS". Location where the error was detected:
"192.168.1.200". Communication function detecting the error: "recv".
Protocol specific error code(s): **"*", "*", "0"**. SQLSTATE=08001
```

***,*,0** indicates the connection was closed by the peer. This could be any network device (i.e. firewall, router, workload balancing device, etc...) between the client and DB2 server, or the DB2 server itself. 

Check to determine if DB2 server has Workload Manager enabled in which SQL queries consuming longer than xx minutes will be disconnected. or check, if your firewall is allowing access to your application, or check, if your server port is active and listening to the TCPIP calls.

Try to run below commands and then, run your application again:
```
db2set DB2COMM=TCPIP
db2 update dbm cfg using SVCENAME <your_port_number>
```

**Comment by WurstCommander** [comment]
Hi,

thank you for your reply.

The DB2 is an enterprise server which is used by many people and services, the query was just one row, so timeouts can't be an issue. There are no connection issues with the server, because - as I mentioned - I can connect via IBM Datastudio, JBoss Application Server, DB Visualizer etc.

I know it's common to try out the "usual" subjects, but I can connect, still, I get this error.

**Comment by shireresident** [comment]
I just received this error on my connection pool that hasn't been used in a while. 

SQL30081N  A communication error has been detected. Communication protocol being used: \"TCP/IP\".  Communication API being used: \"SOCKETS\".  Location where the error was detected: \"10.108.0.10\".  Communication function detecting the error: \"send\".  Protocol specific error code(s): \"32\", \"*\", \"0\".  SQLSTATE=08001\n]\n  errors: [],\n  error: '[node-ibm_db] SQL_ERROR',

The error went away after trying a few times as I believe it recycled the bad connections. Is there an option similar to validationQuery/validationTimeout from Apache BasicDataSource?

**Comment by bimalkjha** [comment]
@shireresident You are getting TPCIP Error 32, that means ["Broken Pipe"]9https://www.ibm.com/support/knowledgecenter/en/SS6NHC/com.ibm.swg.im.dashdb.messages.doc/doc/r0058740.html), i.e. the connection between client and server is broken because connection was idle for long time. The reason might be network issue in between or server has closed the connection.
Similar problem was reported by issue #270 and solution is also there. Please go through the issue in detail and use the documented [solution](https://github.com/ibmdb/node-ibm_db/issues/270#issuecomment-311171336). The original problem reported by WurstCommander in this issue is different from yours. Thanks.

**Comment by bimalkjha** [comment]
@WurstCommander Do not change the protocol to SOCKET, that would not work. Try this connection string : `"DATABASE=mydb;UID=myuser;PWD=mypass;HOSTNAME=myhost;PORT=50000"`. Make sure you are using the correct port value. 
The other clients using which you are able to connect server is present in local system with DB2 server or remote system? We have seen that if server is not configured properly for remote conneciton, local clients are able to connect to the server without any issue but connection from remote systems fail. Please try to figure out the configuration problem and solve that. Thanks.

**Comment by RabeaWahab** [comment]
> solution

@bimaljha just to confirm, the mentioned solution would take care of this `Error: [IBM][CLI Driver] SQL30081N A communication error has been detected. Communication protocol being used: "TCP/IP". Communication API being used: "SOCKETS". Location where the error was detected: Communication function detecting the error: "recv". Protocol specific error code(s): "110", "*", "*". SQLSTATE=08001` ?

**Comment by bimalkjha** [comment]
@RabeaWahab Yes, setting up the ACR in db2dsdrvier.cfg file causes ibm_db to reconnect the server automatically when ibm_db sees SQL30081N error. Thanks.

**Comment by RabeaWahab** [comment]
Appreciate the quick response, after applying the change, I get one or two intervals in the day of a different error; `CLI0600E Invalid connection handle or connection is closed. SQLSTATE=S1000`, it happens for 30 min or so, and then goes back to running smoothly, the configuration is as below:

```
 <configuration>
        <dsncollection>
          <dsn alias="production" name="DB2_DATABASE" host="DB2_HOST" port="DB2_PORT"/>
        </dsncollection>
        <databases>
          <database name="DB2_DATABASE" host="DB2_HOST" port="DB2_PORT">
              <parameter name="userid" value="DB2_USER"/>
              <parameter name="password" value="DB2_PASS"/>
              <parameter name="KeepAliveTimeout" value="7200"/>
              <parameter name="ConnectionTimeout" value="30"/>
              <parameter name="MemberConnectTimeout" value="1"/>
              <acr>
              <parameter name="enableACR" value="true"/>
              <parameter name="enableSeamlessACR" value="true"/>
              <parameter name="acrRetryInterval" value="2"/>
              <parameter name="maxAcrRetries" value="30"/>
              <parameter name="affinityFailbackInterval" value="2"/>
              <alternateserverlist>
                <server name="S1" hostname="DB2_HOST" port="DB2_PORT"/>
                <server name="S2" hostname="DB2_HOST" port="DB2_PORT"/>
              </alternateserverlist>
              <affinitylist>
                <list name="list1" serverorder="S1,S2"/>
              </affinitylist>
              </acr>
          </database>
        </databases>
</configuration>
```

Node module is using the `DSN` from this configuration for the pool of connections with: 
- 50 Connections
- autocleanIdle = true

```
const pool = new Db2.Pool({
  maxPoolSize: 50,
  autoCleanIdle: true
})
```
