### ISSUE TITLE
node run-tests.js failing

### ISSUE THREAD

**Issue by stevenblibm** [ibmdb/node-ibm_db#343]
I am running the run-tests.js and it failed 57 out of 60 times.  The failure always is 

G:\CogniPay\cognipaydemo-master\cognipaydemo-master\server\node_modules\ibm_db\lib\odbc.js:1466
  if(!ENV) ENV = new odbc.ODBC();
                 ^
[object Object]

Running test 40 for [DB2] : test-pool-idle-connection ... fail
 Stdout:

 Stderr:
I can't find any help on what might be the issue.
NODE version 6.11.4
Database DB2/NT64 10.5.8
We just upgraded the database to that version and it was working before.

**Comment by rhtpandeyIN** [comment]
Hi @stevenblibm , How you are installing node-ibm-db and how you are running these test cases?
Can you please share the repro steps, because for me it's working fine. In which OS platform you are?

**Comment by stevenblibm** [comment]
I resolved it.  It was a permissions issue due to the upgrade.

**Comment by fkita** [comment]
hi @stevenblibm and @rhtpandeyIN I'm facing the same problem, could you please explain what have you done to fix the permission issues?
