### ISSUE TITLE
Using Dynamic Insert

### ISSUE THREAD

**Issue by hectotruj** [ibmdb/node-ibm_db#345]
IBM provides blocked (dynamic) inserts with the following example [Example 2](https://www.ibm.com/support/knowledgecenter/SSEPEK_11.0.0/sqlref/src/tpc/db2z_sql_execute.html#db2z_sql_execute)

```
STMT = 'INSERT INTO IWH.PROGPARM  (IWHID, UPDATE_BY,UPDATE_TS,NAME,
                                   SHORT_DESCRIPTION, ORDERNO, PARMDATA, 
                                   PARMDATALONG, VWPROGKEY)  
VALUES ( ? , ? , ? , ? , ? , ? , ? , ? , ? )';  
ATTRVAR = 'FOR MULTIPLE ROWS';
EXEC SQL PREPARE INS_STMT ATTRIBUTES :ATTRVAR FROM :STMT;
NROWS = 5;
EXEC SQL EXECUTE INS_STMT FOR :NROWS ROWS 
           USING :V1, :V2, :V3, :V4, :V5, :V6, :V7, :V8, :V9; 
```

How can I achieve that through imb_db?

**Thanks!**

**Comment by bimalkjha** [comment]
@hectotruj Just translate your above ESQL code to SQL and execute the SQL using [conn.prepare](https://github.com/ibmdb/node-ibm_db#-8-preparesql-callback) and [stmt.execute](https://github.com/ibmdb/node-ibm_db#-10-executebindingparameters-callback) APIs. Check ibm_db [API documentation](https://github.com/ibmdb/node-ibm_db#database-apis) for more info. Thanks.
