### ISSUE TITLE
Question: Is there a version/installTechnique for nodeJS on z/OS?

### ISSUE THREAD

**Issue by MikeC711** [ibmdb/node-ibm_db#348]
Tried a generic npm install and it failed with undefined runtime and many other issues.  Wondering if this is usable for z/OS.  Maybe there is a package which leverages the locality better ... but looking to access a local DB2 from nodeJS on z/OS.  Thanks,

**Comment by bimalkjha** [comment]
No. This node-ibm_db is only for LUW platforms. 
I remember some IBM team is working for the exact scenario that you described, but it is not ready. It will take some time. Once available, you can find that on github. But, I don't see that is coming in 2018. Thanks.

**Comment by MikeC711** [comment]
Thanks for your quick response.  I will wait to hear from my IBM contact.

**Comment by bimalkjha** [comment]
@MikeC711 ibm_db@2.4.0 has support for z/OS. i.e. you can now install ibm_db on z/OS. Please check the latest docs for detail info and setup instructions. Thanks.
