### ISSUE TITLE
db2jcc_license_cisuz license

### ISSUE THREAD

**Issue by brandonros** [ibmdb/node-ibm_db#349]
I have this JAR file but it is empty and doesn't have a license I can extract out.

I confirmed it works in Java and I am working on transferring it over to Javascript.

Where can I install the db2connect CLI tools mentioned?

**Comment by brandonros** [comment]
Is this what a sample .lic file looks like?

```
[LicenseCertificate]
CheckSum=2CA72409B863E93B74449C72A0AD6F19
TimeStamp=1015354197
PasswordVersion=7
VendorName=Dassault Systemes
VendorPassword=dgq5mxkpvqhbi
VendorID=5242378dbf8d.02.c0.09.c8.93.00.00.00
ProductName=MD2-Catia Mechanical Design C2
ProductID=2119
ProductVersion=TMPMCFA
ProductPassword=kukeitb8ipbgnvnnwc32g9apdhu7s5hauzackdimangaa
ProductAnnotation=TMPMCFAAAAALicenseStyle=nodelocked
LicenseStartDate=03/04/2002
LicenseDuration=366
LicenseEndDate=03/04/2003
LicenseCount=1
MultiUseRules=
RegistrationLevel=3
TryAndBuy=No
SoftStop=No
TargetType=26
TargetTypeName=MS Win-32 MAC
TargetID=745315e5
ExtendedTargetType=
ExtendedTargetID=
DerivedLicenseStyle=
DerivedLicenseStartDate=
DerivedLicenseEndDate=
DerivedLicenseAggregateDuration=
SerialNumber=TMPMCFAAAAA
Upgrade=No
CapacityType=
Bundle=No
InstallProgram=
AdditionalLicenseData=
CustomAttribute1=No
CustomAttribute2=No
CustomAttribute3=No
SubCapacityEligibleP
```

It sounds like the path would be: `./node_modules/ibm_db/installer/clidriver/license/`

**Comment by bimalkjha** [comment]
db2jcc_license_cisuz.jar is a license file for JAVA applications. For any non-java application like javascript, python, C++, etc you need different license file with extension .lic like db2consv_ee.lic. You need to get this license file from IBM Support or contact your sysadmin if they already have.
Yes, you need to copy db2consv_ee.lic file under ./node_modules/ibm_db/installer/clidriver/license folder. Thanks.
