### ISSUE TITLE
Test failed for remote host not found

### ISSUE THREAD

**Issue by Teamop** [ibmdb/node-ibm_db#350]
I tried to set up a local env, but when I ran the test, get ```Results : 52 of 60 tests failed.```, cause
```The remote host "hotel.torolab.ibm.com" was not found.  SQLSTATE=08001```

**Comment by rhtpandeyIN** [comment]
Hi @Teamop , 
you need to update the default host details with your host credentials (Server details). Please update the "test/config.testConnectionStrings.json" file and rerun the test cases.

Thanks.
