### ISSUE TITLE
Issue while Downloading the Package in Windows 7

### ISSUE THREAD

**Issue by RKishore222** [ibmdb/node-ibm_db#353]
Hi, I am getting error while downloading the package from node. Below are the software and versions details:
Node: v8.9.3
Python version 2.7.13
Windows 7  64 bit

I have downloaded IBM client clidriver and created environment variable and also added in path.

then I ran the below query for setup the Pythan and MS build tools:
npm install --global --production windows-build-tools

and also configured in environment variables.

then I ran the " npm install ibm_db". After running the command getting below error:

     C:\Windows>npm install ibm_db

> ibm_db@2.2.1 install C:\Windows\node_modules\ibm_db
> node installer/driverInstall.js

IBM_DB_HOME environment variable have already been set to -> C:\clidriver

Downloading of clidriver skipped - build is in progress...

C:\Windows\node_modules\ibm_db>if not defined npm_config_node_gyp (node "C:\Prog
ram Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\
bin\node-gyp.js" configure build  --IS_DOWNLOADED=false --IBM_DB_HOME=$IBM_DB_HO
ME )  else (node "" configure build  --IS_DOWNLOADED=false --IBM_DB_HOME=$IBM_DB
_HOME )

{ Error: Command failed: node-gyp configure build  --IS_DOWNLOADED=false --IBM_D
B_HOME=$IBM_DB_HOME
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: unable to verify the first certificate
gyp ERR! stack     at TLSSocket.<anonymous> (_tls_wrap.js:1103:38)
gyp ERR! stack     at emitNone (events.js:106:13)
gyp ERR! stack     at TLSSocket.emit (events.js:208:7)
gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:637:8)
gyp ERR! stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:467:38)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "bui
ld" "--IS_DOWNLOADED=false" "--IBM_DB_HOME=$IBM_DB_HOME"
gyp ERR! cwd C:\Windows\node_modules\ibm_db
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node-gyp configure build  --IS_DOWNLOADED=false --IBM_DB_HOME=$IBM_DB_HO
ME' }

node-gyp build process failed!
Proceeding with Pre-compiled Binary Installation.

===================================
node-ibm_db installed successfully!
===================================

npm WARN saveError ENOENT: no such file or directory, open 'C:\Windows\package.j
son'
npm notice created a lockfile as package-lock.json. You should commit this file.

npm WARN enoent ENOENT: no such file or directory, open 'C:\Windows\package.json
'
npm WARN Windows No description
npm WARN Windows No repository field.
npm WARN Windows No README data
npm WARN Windows No license field.
 
node-gyp was installed successfully using the below query: 
npm install --global node-gyp --verbose 

but when i trying to build the node-gyp getting below error:
C:\Windows>cd C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp

C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp>node-gyp configur
e

C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp>if not defined np
m_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-b
in\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure )  else (node "" conf
igure )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.9.3 | win32 | x64
gyp http GET https://nodejs.org/download/release/v8.9.3/node-v8.9.3-headers.tar.
gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: unable to verify the first certificate
gyp ERR! stack     at TLSSocket.<anonymous> (_tls_wrap.js:1103:38)
gyp ERR! stack     at emitNone (events.js:106:13)
gyp ERR! stack     at TLSSocket.emit (events.js:208:7)
gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:637:8)
gyp ERR! stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:467:38)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure"
gyp ERR! cwd C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp>

**Comment by RKishore222** [comment]
node-gyp was installed successfully using the below query: 
npm install --global node-gyp --verbose 

but when i trying to build the node-gyp getting below error:


C:\Windows>cd C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp

C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp>node-gyp configur
e

C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp>if not defined np
m_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-b
in\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure )  else (node "" conf
igure )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.9.3 | win32 | x64
gyp http GET https://nodejs.org/download/release/v8.9.3/node-v8.9.3-headers.tar.
gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: unable to verify the first certificate
gyp ERR! stack     at TLSSocket.<anonymous> (_tls_wrap.js:1103:38)
gyp ERR! stack     at emitNone (events.js:106:13)
gyp ERR! stack     at TLSSocket.emit (events.js:208:7)
gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:637:8)
gyp ERR! stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:467:38)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure"
gyp ERR! cwd C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp>



C:\Windows>cd C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp

C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp>node-gyp configur
e

C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp>if not defined np
m_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-b
in\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure )  else (node "" conf
igure )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.9.3 | win32 | x64
gyp http GET https://nodejs.org/download/release/v8.9.3/node-v8.9.3-headers.tar.
gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: unable to verify the first certificate
gyp ERR! stack     at TLSSocket.<anonymous> (_tls_wrap.js:1103:38)
gyp ERR! stack     at emitNone (events.js:106:13)
gyp ERR! stack     at TLSSocket.emit (events.js:208:7)
gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:637:8)
gyp ERR! stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:467:38)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure"
gyp ERR! cwd C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp>


C:\Windows>cd C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp

C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp>node-gyp configur
e

C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp>if not defined np
m_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-b
in\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure )  else (node "" conf
igure )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.9.3 | win32 | x64
gyp http GET https://nodejs.org/download/release/v8.9.3/node-v8.9.3-headers.tar.
gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: unable to verify the first certificate
gyp ERR! stack     at TLSSocket.<anonymous> (_tls_wrap.js:1103:38)
gyp ERR! stack     at emitNone (events.js:106:13)
gyp ERR! stack     at TLSSocket.emit (events.js:208:7)
gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:637:8)
gyp ERR! stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:467:38)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure"
gyp ERR! cwd C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp>

**Comment by RKishore222** [comment]
C:\Windows>cd C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp

C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp>node-gyp configur
e

C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp>if not defined np
m_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-b
in\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure )  else (node "" conf
igure )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.9.3 | win32 | x64
gyp http GET https://nodejs.org/download/release/v8.9.3/node-v8.9.3-headers.tar.
gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: unable to verify the first certificate
gyp ERR! stack     at TLSSocket.<anonymous> (_tls_wrap.js:1103:38)
gyp ERR! stack     at emitNone (events.js:106:13)
gyp ERR! stack     at TLSSocket.emit (events.js:208:7)
gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:637:8)
gyp ERR! stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:467:38)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure"
gyp ERR! cwd C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp>

**Comment by rhtpandeyIN** [comment]
Hi @RKishore222 , as per the error log, node-ibm_db installed successfully, but with the pre-compiled binary version. (because installation process got some "unable to verify the first certificate" error). 

Hence when you are trying to build pre-installed binary version, it is giving you error, you don't need to rebuild pre-compiled binaries. thanks.
