### ISSUE TITLE
bufferutil.o issue while running npm install using ibm_db for AIX

### ISSUE THREAD

**Issue by mash-ibm** [ibmdb/node-ibm_db#356]
Environment:
O.S: AIX 7
Node.js version 6 and 8
Application: Customer feedback
Using ibm_db driver for AIX
npm install

    websocket@1.0.25 install /ibm-redbooks/customer-feedback-power/node_modules/websocket
    (node-gyp rebuild 2> builderror.log) || (exit 0)

gmake: Entering directory '/ibm-redbooks/customer-feedback-power/node_modules/websocket/build'
CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
bufferutil.target.mk:95: recipe for target 'Release/obj.target/bufferutil/src/bufferutil.o' failed
gmake: Leaving directory '/ibm-redbooks/customer-feedback-power/node_modules/websocket/build'

    ibm_db@2.2.1 install /ibm-redbooks/customer-feedback-power/node_modules/ibm_db
    node installer/driverInstall.js

Downloading DB2 ODBC CLI Driver from https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/aix64_odbc_cli.tar.gz...

100.00% | 28401994 bytes downloaded out of 28401994 bytes.
Downloading and extraction of DB2 ODBC CLI Driver completed successfully ...

gmake: Entering directory '/ibm-redbooks/customer-feedback-power/node_modules/ibm_db/build'
CXX(target) Release/obj.target/odbc_bindings/src/odbc.o
odbc_bindings.target.mk:103: recipe for target 'Release/obj.target/odbc_bindings/src/odbc.o' failed
gmake: Leaving directory '/ibm-redbooks/customer-feedback-power/node_modules/ibm_db/build'

{ Error: Command failed: node-gyp configure build --IS_DOWNLOADED=true --IBM_DB_HOME="$IBM_DB_HOME"

So, the main issue is bufferutil as below:

gmake: Entering directory '/ibm-redbooks/customer-feedback-power/node_modules/bufferutil/build'
CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
In file included from ../src/bufferutil.cc:7:0:
../node_modules/nan/nan.h:52:21: fatal error: algorithm: No such file or directory
#include
^
compilation terminated.
bufferutil.target.mk:94: recipe for target 'Release/obj.target/bufferutil/src/bufferutil.o' failed
gmake: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 1

I tried as well:
npm install bufferutil --save

Same issue

**Comment by bnoordhuis** [comment]
`<algorithm>` is a system header that apparently you're missing.  That's not an issue with this module, not even with bufferutil.

**Comment by mash-ibm** [comment]
Then,  what do you suggest?
Ahmed (Mash) Mashhour
AIX Global Subject Matter Expert,
EMEA TSS-AIX Technical Lead
Egypt SW Client Innovation Center,
US and EMEA Support
IBM
Maadi technology Park - 2nd Floor - Bldg B MB 1
Maadi - Laselky Street
Cairo, 11435
Egypt
Phone: (+2) 02   3536 1915
Mobile: (+2) 012 2433 6060
E-mail: ahdmashr@eg.ibm.com

"Trust is like the air we breathe. When it's present, nobody really
notices. But when it's absent, everybody notices."
—Warren Buffett

**Comment by mash-ibm** [comment]
:-) I have everything installed! See this:
# gcc --version
gcc (GCC) 4.6.1
Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# g++ --version
g++ (GCC) 4.8.5
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# lslpp -la | grep -i xlc
  xlC.aix61.rte             13.1.3.1  COMMITTED  IBM XL C++ Runtime for AIX 6.1
  xlC.cpp                    9.0.0.0  COMMITTED  C for AIX Preprocessor
  xlC.msg.en_US.cpp          9.0.0.0  COMMITTED  C for AIX Preprocessor
  xlC.msg.en_US.rte         13.1.3.1  COMMITTED  IBM XL C++ Runtime
  xlC.rte                   13.1.3.1  COMMITTED  IBM XL C++ Runtime for AIX 
  xlC.sup.aix50.rte          9.0.0.1  COMMITTED  XL C/C++ Runtime for AIX 5.2

Cheers,
Mash

**Comment by bnoordhuis** [comment]
If I had to venture a guess, it's that headers like `<algorithm>` live in a separate package like libstdc++-devel.

**Comment by mash-ibm** [comment]
:-) I have all installed - See this:
# rpm -qa | grep -i stdc 
libstdc++-4.8.3-1
libstdc++-6.3.0-1
libstdc++-devel-6.3.0-1

# npm --version
5.5.1

# node --version
v8.9.3


Thanks,
Mash

**Comment by rhtpandeyIN** [comment]
@mash-ibm , Are you facing the same problem in any other system or platform? 
Well my first opinion is same as @bnoordhuis , but for more clarity can you please attach full error log. (Attach the output of "npm install ibm_db")

Thanks.

**Comment by mash-ibm** [comment]
# npm install ibm_db 

> websocket@1.0.25 install /ibm-redbooks/customer-feedback-power/node_modules/websocket
> (node-gyp rebuild 2> builderror.log) || (exit 0)

gmake: Entering directory `/ibm-redbooks/customer-feedback-power/node_modules/websocket/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
gmake: Leaving directory `/ibm-redbooks/customer-feedback-power/node_modules/websocket/build'

> ibm_db@2.2.1 install /ibm-redbooks/customer-feedback-power/node_modules/ibm_db
> node installer/driverInstall.js

Downloading DB2 ODBC CLI Driver from https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/aix64_odbc_cli.tar.gz...

100.00% | 28401994 bytes downloaded out of 28401994 bytes.

****************************************
You are downloading a package which includes the Node.js module for IBM DB2/Informix.  The module is licensed under the Apache License 2.0. The package also includes IBM ODBC and CLI Driver from IBM, which is automatically downloaded as the node module is installed on your system/device. The license agreement to the IBM ODBC and CLI Driver is available in undefined   Check for additional dependencies, which may come with their own license agreement(s). Your use of the components of the package and dependencies constitutes your acceptance of their respective license agreements. If you do not accept the terms of any license agreement(s), then delete the relevant component(s) from your device.
****************************************

Downloading and extraction of DB2 ODBC CLI Driver completed successfully ...

gmake: Entering directory `/ibm-redbooks/customer-feedback-power/node_modules/ibm_db/build'
  CXX(target) Release/obj.target/odbc_bindings/src/odbc.o
gmake: Leaving directory `/ibm-redbooks/customer-feedback-power/node_modules/ibm_db/build'

{ Error: Command failed: node-gyp configure build  --IS_DOWNLOADED=true --IBM_DB_HOME="$IBM_DB_HOME"
In file included from ../src/odbc.h:23:0,
                 from ../src/odbc.cpp:25:
../../nan/nan.h:50:21: fatal error: algorithm: No such file or directory
 #include <algorithm>
                     ^
compilation terminated.
gmake: *** [Release/obj.target/odbc_bindings/src/odbc.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `gmake` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/ibm/newnode/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System AIX 7.1
gyp ERR! command "/ibm/newnode/bin/node" "/ibm/newnode/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build" "--IS_DOWNLOADED=true" "--IBM_DB_HOME=/ibm-redbooks/customer-feedback-power/node_modules/ibm_db/installer/clidriver"
gyp ERR! cwd /ibm-redbooks/customer-feedback-power/node_modules/ibm_db
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node-gyp configure build  --IS_DOWNLOADED=true --IBM_DB_HOME="$IBM_DB_HOME"' }
npm WARN customer-feedback-power@0.0.1 No repository field.
npm WARN customer-feedback-power@0.0.1 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ibm_db@2.2.1 install: `node installer/driverInstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ibm_db@2.2.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /.npm/_logs/2018-01-16T12_29_20_931Z-debug.log



Contents of /.npm/_logs/2018-01-16T12_29_20_931Z-debug.log    attached:
[2018-01-16T12_29_20_931Z-debug.log](https://github.com/ibmdb/node-ibm_db/files/1635095/2018-01-16T12_29_20_931Z-debug.log)

**Comment by gireeshpunathil** [comment]
C++ header algorithm should be available at
/opt/freeware/lib/gcc/powerpc-ibm-aix6.1.0.0/`<gcc version number>`/include/c++/algorithm

such as:
```
$: ~/support/ibmdb >  l /opt/freeware/lib/gcc/powerpc-ibm-aix6.1.0.0/4.8.4/include/c++/algorithm
-rw-r--r--    1 gireesh     system         2518 Mar 03 2015  /opt/freeware/lib/gcc/powerpc-ibm-aix6.1.0.0/4.8.4/include/c++/algorithm
```

If this is missing in the default build script, you could export CPPFLAGS to point to this location (`export CPPFLAGS=-I/opt/freeware/lib/gcc/powerpc-ibm-aix6.1.0.0/4.8.4/include/c++`) prior to `npm install`. But I think the g++ installations in your system may be unstable, and need inspection. Please contact me privately to debug and fix this.

npm install dev is failing because it aggregates "npm install inotify" which is a Linux-only tool (wraps Linux's inotify syscall), and does not work on AIX.

**Comment by mash-ibm** [comment]
This does not work - for sorry

**Comment by mash-ibm** [comment]
I did export CPPFLAGS variable - but still having an error:::

# export CPPFLAGS=-I/opt/freeware/lib/gcc/powerpc-ibm-aix7.1.0.0/6.3.0/include/c++
# npm install

> ibm_db@2.2.1 install /ibm-redbooks/customer-feedback-power/node_modules/ibm_db
> node installer/driverInstall.js

Downloading DB2 ODBC CLI Driver from https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/aix64_odbc_cli.tar.gz...

100.00% | 28401994 bytes downloaded out of 28401994 bytes.

****************************************
You are downloading a package which includes the Node.js module for IBM DB2/Informix.  The module is licensed under the Apache License 2.0. The package also includes IBM ODBC and CLI Driver from IBM, which is automatically downloaded as the node module is installed on your system/device. The license agreement to the IBM ODBC and CLI Driver is available in undefined   Check for additional dependencies, which may come with their own license agreement(s). Your use of the components of the package and dependencies constitutes your acceptance of their respective license agreements. If you do not accept the terms of any license agreement(s), then delete the relevant component(s) from your device.
****************************************

Downloading and extraction of DB2 ODBC CLI Driver completed successfully ...

gmake: Entering directory `/ibm-redbooks/customer-feedback-power/node_modules/ibm_db/build'
  CXX(target) Release/obj.target/odbc_bindings/src/odbc.o
gmake: Leaving directory `/ibm-redbooks/customer-feedback-power/node_modules/ibm_db/build'

{ Error: Command failed: node-gyp configure build  --IS_DOWNLOADED=true --IBM_DB_HOME="$IBM_DB_HOME"
In file included from /opt/freeware/lib/gcc/powerpc-ibm-aix7.1.0.0/6.3.0/include/c++/algorithm:60:0,
                 from ../../nan/nan.h:50,
                 from ../src/odbc.h:23,
                 from ../src/odbc.cpp:25:
/opt/freeware/lib/gcc/powerpc-ibm-aix7.1.0.0/6.3.0/include/c++/utility:68:28: fatal error: bits/c++config.h: No such file or directory
 #include <bits/c++config.h>
                            ^
compilation terminated.
gmake: *** [Release/obj.target/odbc_bindings/src/odbc.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `gmake` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/ibm/newnode/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System AIX 7.1
gyp ERR! command "/ibm/newnode/bin/node" "/ibm/newnode/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build" "--IS_DOWNLOADED=true" "--IBM_DB_HOME=/ibm-redbooks/customer-feedback-power/node_modules/ibm_db/installer/clidriver"
gyp ERR! cwd /ibm-redbooks/customer-feedback-power/node_modules/ibm_db
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node-gyp configure build  --IS_DOWNLOADED=true --IBM_DB_HOME="$IBM_DB_HOME"' }
npm WARN ENOTDIR: not a directory, rmdir '/ibm-redbooks/customer-feedback-power/node_modules/ibm_db/installer/clidriver'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ibm_db@2.2.1 install: `node installer/driverInstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ibm_db@2.2.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by rhtpandeyIN** [comment]
Hi @mash-ibm ,
As per your error log, It looks like a compiler issue,
>/opt/freeware/lib/gcc/powerpc-ibm-aix7.1.0.0/6.3.0/include/c++/utility:68:28: fatal error: bits/c++config.h: No such file or directory
#include <bits/c++config.h>
^
compilation terminated.

I am not sure about any other solution (except the already given once), sorry about that. I will try to search something, and will get back to you. For now closing this issue as it is not direct part of node-ibm_db issues.

**Comment by mash-ibm** [comment]
Alright folks, I have managed to solve my issue completely. I re-installed everything: C++, G++, Libstdc, libstdc++, GCC, python,.. and the latest node.js.

Cheers,
Mash
