### ISSUE TITLE
SQLCODE +100 (record not found) is not returned

### ISSUE THREAD

**Issue by MariangelaQuagliatto** [ibmdb/node-ibm_db#358]
I am trying to code the application to handle the error in case the user try to delete a record that does not exist anymore and the (err) is returning null.

**Comment by bimalkjha** [comment]
Please share the test program to reproduce the issue. Thanks.

**Comment by MariangelaQuagliatto** [comment]
Hello, 

This is the piece of code that process the command:

 conn.query(req.body.command1, function (err, data) 
        {
          if (err) 
          {
            console.log(err);  
            strMsg = {"message1":err.message};          
          }   
          else 
          { 
            strMsg = {"message1":strMessage};           
          } 
        }); 

req.body.command1 has a delete command like this:
DELETE FROM KBD.USERS WHERE ID = 'QTRETZ5'
My program is using DB2 database in MVS.

This id does not exist in the table, and while in QMF in mainframe it returns SQLCODE=100 (not found),
the ibm_db is returning err=null and data is returning [], so I can not handle this error.
I need the err returns the sqlcode=100 like the others sqlcodes.

Let me know if this is enough to help you to investigate, I can not share the program.
Thanks a lot for your help!

**Comment by tanganellilore** [comment]
Hi, 
I have the same problem in a UPDATE query when the element to update not found in DB2 Warehouse on Cloud.

The online dashboard with the same query return error but the node.js app not return any error ( error=null and  data=[] ).

Thanks a lot for your help!

**Comment by bimalkjha** [comment]
@tanganellilore @MariangelaQuagliatto This issue is fixed in ibm_db@2.3.1. Please verify. Thanks.
