### ISSUE TITLE
Read SQL File

### ISSUE THREAD

**Issue by hectotruj** [ibmdb/node-ibm_db#359]
I have done some research, and it seems that the way to use SQL files in my app is to first read the files and then run the queries. Because I have multiple files, and large queries within each file, processing them gets clunky and it would be a lot easier if I could just pass the location of the file in my app and have ibm_db read and run the queries.

### Purpose
Simplify using SQL files in Node.js

### Case
I have a couple of SQL scripts in SQL files that I would like to be able to run in my methods. However, currently, I have to use the File System to read them and then submit the query.

**Comment by rhtpandeyIN** [comment]
Hi @hectotruj, thanks for reporting the issue. Is that mean you want a new feature in node-ibm_db which can support above mentioned behavior?

**Comment by hectotruj** [comment]
Yes, that would be fantastic!

**Comment by alobaidizt** [comment]
Would be great to get this feature in!

**Comment by rhtpandeyIN** [comment]
Hi @hectotruj , Can you please give me some example for this. 

Well let suppose we let this feature in, but I think it will be the same process right? The only difference will be, now ibm_db will read and parse the SQL file for getting the queries rather than the application. isn't it? 
But what purpose is it solving? I think process will take the same time.

One more thing, how ibm_db will figure out which SQL query to run first, will that be in sequential manner, if so can you please give me some more insight of the problem?

It would be really a great help, if you can provide me some examples for that. Thanks in advance.

**Comment by bimalkjha** [comment]
@hectotruj Please check this [comment](https://github.com/ibmdb/node-ibm_db/issues/128#issuecomment-386030998). You can execute sql from file suing system command. Thanks.

**Comment by bimalkjha** [comment]
Putting a sample test program about this feature to show, how it should work:
```
var ibmdb = require("ibm_db")
  , cn = "connection string";

ibmdb.open(cn, function(err, conn){
    conn.executeFile({fileName: sql.txt [, delimiter: ';', outputFile: out.txt]}, function(err) {
        if (err) {console.log(err);}
    });
    conn.executeFile(filename [, delimiter[, outputFile] ], function(err) {
        if (err) { console.log(err); }
    });
    conn.excuteFileSync({fileName: sql.txt [, delimiter: '<delimiter>', outputFile: out.txt ]});
    var err = conn.excuteFileSync(filename [, delimiter [, outputFile] ]);
    if (err) { console.log(err); }
});
```
executeFile() and executeFileSync() will call internally the conn.query and conn.querySync to execute each sql one by one and write the result to output file or stdout.
Default sql statement delimiter in file would be semicolon, but it can accept other delimiters too. delimiter can be of one or more than one character.

**Comment by bimalkjha** [comment]
@hectotruj We have added new API to read SQL file and execute query from input file, in latest code. Please check and let us know if we can close the issue.

**Comment by bimalkjha** [comment]
@hectotruj ibm_db@2.5.3 has added support for a new API [conn.executeFileSync()](https://github.com/ibmdb/node-ibm_db/blob/master/APIDocumentation.md#executeFileSyncApi) using which you can execute sql statements written in a file. Thanks.
