### ISSUE TITLE
Close connection problem

### ISSUE THREAD

**Issue by wilk** [ibmdb/node-ibm_db#36]
Sometime an error occures when I try to close a connection after executing a query (open the connection, execute the query, close the connection).
The error is thrown at this line: https://github.com/ibmdb/node-ibm_db/blob/master/lib/odbc.js#L161
At some point, the "self.conn" seems to be empty, so it cannot be closed.
To make the code working, I used the following work-around:

```javascript
self.conn && self.conn.close && self.conn.close(...);
```

I don't know why this error happens but a pre-check should be done before calling the close method on an undefined connection.

If a PR is needed, please tell me and I'll do it.

**Comment by bimalkjha** [comment]
Yes, we recently discovered this issue. We'll add the fix soon.
