### ISSUE TITLE
Ibm_db package cannot find odbc_bindings upon project build

### ISSUE THREAD

**Issue by ryankall** [ibmdb/node-ibm_db#361]
**I'm submitting a  issue I am having with ibm_db package I having. It will not build with universal. It having an issue finding the binding file.**
```
- [ x ] bug report
- [  ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.
```

* **What modules are related to this Issue?**
```
- [ ] aspnetcore-engine
- [ x ] express-engine
- [ ] hapi-engine
```

* **Do you want to request a *feature* or report a *bug*?**
Having an issue with npm ibm_db package. 

* **What is the current behavior?**
line 55 in server.ts
`var ibmdb = require('ibm_db');`

Error: Could not locate the bindings file. Tried:
 → C:\Users\Ryankall\Desktop\experiment\ex\build\odbc_bindings.node
 → C:\Users\Ryankall\Desktop\experiment\ex\build\Debug\odbc_bindings.node
 → C:\Users\Ryankall\Desktop\experiment\ex\build\Release\odbc_bindings.node
 → C:\Users\Ryankall\Desktop\experiment\ex\out\Debug\odbc_bindings.node
 → C:\Users\Ryankall\Desktop\experiment\ex\Debug\odbc_bindings.node
 → C:\Users\Ryankall\Desktop\experiment\ex\out\Release\odbc_bindings.node
 → C:\Users\Ryankall\Desktop\experiment\ex\Release\odbc_bindings.node
 → C:\Users\Ryankall\Desktop\experiment\ex\build\default\odbc_bindings.node
 → C:\Users\Ryankall\Desktop\experiment\ex\compiled\6.12.3\win32\x64\odbc_bindings.node
    at bindings (C:\Users\Ryankall\Desktop\experiment\ex\dist\server.js:158458:9)
    at Object.<anonymous> (C:\Users\Ryankall\Desktop\experiment\ex\dist\server.js:156611:36)
    at Object.<anonymous> (C:\Users\Ryankall\Desktop\experiment\ex\dist\server.js:158365:30)
    at __webpack_require__ (C:\Users\Ryankall\Desktop\experiment\ex\dist\server.js:20:30)
    at Object.<anonymous> (C:\Users\Ryankall\Desktop\experiment\ex\dist\server.js:112062:13)
    at __webpack_require__ (C:\Users\Ryankall\Desktop\experiment\ex\dist\server.js:20:30)
    at Object.defineProperty.value (C:\Users\Ryankall\Desktop\experiment\ex\dist\server.js:63:18)
    at Object.<anonymous> (C:\Users\Ryankall\Desktop\experiment\ex\dist\server.js:66:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

* **Demo repo**
[https://github.com/ryankall/IBM_DB_ERROR](https://github.com/ryankall/IBM_DB_ERROR)

* **What is the expected behavior?**
Project build 

* **Env:**
npm  5.6.0
node v6.12.3
node-gyp v3.6.2
python 2.7

* **Things I tried:**
1. Windows 10 x64: I ran it with a node standalone project and it builds and works with node v. 6.12.3, node-gyp v. 3.6.2
Ubuntu 16.04 x64: I ran it with a node standalone project and it builds and works with node v. 6.12.3, node-gyp v. 3.6.2
I tried it will universal and it fails because it cannot find the the complied files on both linux and windows. 

2. I tried in node_modules/ibm_db
`node-gyp rebuild`

3. reinstalling python 2.7  and msbuild on windows.

**Comment by rhtpandeyIN** [comment]
Hi @ryankall , I am sorry, but I am afraid I could not understand what you mean by universal?
Can you please elaborate it more? Thanks.

**Comment by ryankall** [comment]
Hi @rhtpandeyIN ,
universal : https://angular.io/guide/universal
It is has angular running it the front and Node.js in the back-end.

I have a demo Repo you can have a look at: https://github.com/ryankall/IBM_DB_ERROR

**Comment by rhtpandeyIN** [comment]
Hi @ryankall, can you please tell me, in which platform exactly you are facing this issue?
1) If in windows, then please share the steps how you are installing node-ibm_db, I am assuming you are using package.json of your application to install all dependencies, in that case please share the ibm_db installation log. 
I think for windows, the problem is build setup. to build ibm_db on windows you will required "visual studio" and "msbuild". if Visual studio is not there, then installation will get failed and pre-compiled binaries will get installed - and in that case you will get above errors.

2) If in Linux, then it's the matter of investigation, please share the installation log of ibm_db for more information.

Try to do "npm rebuild" inside your applications "node-modules" directory, it will rebuild all the dependencies including ibm_db.

**Comment by ryankall** [comment]
@rhtpandeyIN , I don't believe I have an environment problem because I made a nodejs project only and the ibm_db package build and worked just fine.  It is only when I try to use angular universal that the problem arises.

- Env:
npm 5.6.0
node v6.12.3
node-gyp v3.6.2
python 2.7

* **Things I tried:**
1. Windows 10 x64: I ran it with a node standalone project and it builds and works with node v. 6.12.3, node-gyp v. 3.6.2
Ubuntu 16.04 x64: I ran it with a node standalone project and it builds and works with node v. 6.12.3, node-gyp v. 3.6.2

I tried it will angular universal and it **fails** because it cannot find the compiled files on both **Linux and** **Windows**. 

2. I tried in node_modules/ibm_db
`node-gyp rebuild`  

and npm rebuild.

3. reinstalling python 2.7  and msbuild on windows.

4. I even went as far as to move the build folder from ibm_db  to where it is looking and still issues exist.

**Comment by rhtpandeyIN** [comment]
Thanks for your feedback, we will get back to you shortly, we are lookin into the issue.

**Comment by bimalkjha** [comment]
@ryankall Please verify your issue using ibm_db@2.3.1. It should work now. Thanks.

**Comment by ryankall** [comment]
@bimalkjha Using this repo to test https://github.com/ryankall/IBM_DB_ERROR 
I updated ibm_db@2.3.1. The same error comes up.
