### ISSUE TITLE
Error: Command failed: node-gyp configure build

### ISSUE THREAD

**Issue by brayansuarezm** [ibmdb/node-ibm_db#366]
I get this error:

C:\Users\Brayan Suárez M\Desktop\test_server>npm install ibm_db

> ibm_db@2.2.1 install C:\Users\Brayan Suárez M\Desktop\test_server\node_modules\ibm_db
> node installer/driverInstall.js

Downloading DB2 ODBC CLI Driver from https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/ntx64_odbc_cli.zip...

100.00% | 17935538 bytes downloaded out of 17935538 bytes.

****************************************
You are downloading a package which includes the Node.js module for IBM DB2/Informix.  The module is licensed under the Apache License 2.0. The package also includes IBM ODBC and CLI Driver from IBM, which is automatically downloaded as the node module is installed on your system/device. The license agreement to the IBM ODBC and CLI Driver is available in undefined   Check for additional dependencies, which may come with their own license agreement(s). Your use of the components of the package and dependencies constitutes your acceptance of their respective license agreements. If you do not accept the terms of any license agreement(s), then delete the relevant component(s) from your device.
****************************************

Downloading and extraction of DB2 ODBC CLI Driver completed successfully...

C:\Users\Brayan Su�rez M\Desktop\test_server\node_modules\ibm_db>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure build  --IS_DOWNLOADED=true --IBM_DB_HOME=$IBM_DB_HOME )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" configure build  --IS_DOWNLOADED=true --IBM_DB_HOME=$IBM_DB_HOME )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  odbc.cpp
  odbc_connection.cpp
  odbc_statement.cpp
  odbc_result.cpp
c:\users\brayan su�rez m\desktop\test_server\node_modules\nan\nan_maybe_43_inl.h(88): warning C4996: 'v8::Object::ForceSet': was declared deprecated (compiling source file ..\src\odbc_connection.cpp) [C:\Users\Brayan Su�rez M\Desktop\test_server\node_modules\ibm_db\build\odbc_bindings.vcxproj]
  C:\Users\Brayan Su�rez M\.node-gyp\9.4.0\include\node\v8.h(3117): note: see declaration of 'v8::Object::ForceSet' (compiling source file ..\src\odbc_connection.cpp)
c:\users\brayan su�rez m\desktop\test_server\node_modules\nan\nan_maybe_43_inl.h(88): warning C4996: 'v8::Object::ForceSet': was declared deprecated (compiling source file ..\src\odbc.cpp)c:\users\brayan su�rez m\desktop\test_server\node_modules\nan\nan_maybe_43_inl.h(88): warning C4996: 'v8::Object::ForceSet': was declared deprecated (compiling source file ..\src\odbc_statement.cpp) [C:\Users\Brayan Su�rez M\Desktop\test_server\node_modules\ibm_db\build\odbc_bindings.vcxproj]

  C:\Users\Brayan Su�rez M\.node-gyp\9.4.0\include\node\v8.h(3117): note: see declaration of 'v8::Object::ForceSet' (compiling source file ..\src\odbc.cpp)C:\Users\Brayan Su�rez M\.node-gyp\9.4.0\include\node\v8.h(3117): note: see declaration of 'v8::Object::ForceSet' (compiling source file ..\src\odbc_statement.cpp)

c:\users\brayan su�rez m\desktop\test_server\node_modules\nan\nan_maybe_43_inl.h(88): warning C4996: 'v8::Object::ForceSet': was declared deprecated (compiling source file ..\src\odbc_result.cpp) [C:\Users\Brayan Su�rez M\Desktop\test_server\node_modules\ibm_db\build\odbc_bindings.vcxproj]
  C:\Users\Brayan Su�rez M\.node-gyp\9.4.0\include\node\v8.h(3117): note: see declaration of 'v8::Object::ForceSet' (compiling source file ..\src\odbc_result.cpp)
c:\users\brayan su�rez m\desktop\test_server\node_modules\ibm_db\src\odbc.h(27): fatal error C1083: Cannot open include file: 'sqlcli1.h': No such file or directory (compiling source file ..\src\odbc.cpp) [C:\Users\Brayan Su�rez M\Desktop\test_server\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\users\brayan su�rez m\desktop\test_server\node_modules\ibm_db\src\odbc.h(27): fatal error C1083: Cannot open include file: 'sqlcli1.h': No such file or directory (compiling source file ..\src\odbc_statement.cpp) [C:\Users\Brayan Su�rez M\Desktop\test_server\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\users\brayan su�rez m\desktop\test_server\node_modules\ibm_db\src\odbc.h(27): fatal error C1083: Cannot open include file: 'sqlcli1.h': No such file or directory (compiling source file ..\src\odbc_connection.cpp) [C:\Users\Brayan Su�rez M\Desktop\test_server\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\users\brayan su�rez m\desktop\test_server\node_modules\ibm_db\src\odbc.h(27): fatal error C1083: Cannot open include file: 'sqlcli1.h': No such file or directory (compiling source file ..\src\odbc_result.cpp) [C:\Users\Brayan Su�rez M\Desktop\test_server\node_modules\ibm_db\build\odbc_bindings.vcxproj]
  win_delay_load_hook.cc

**{ Error: Command failed: node-gyp configure build  --IS_DOWNLOADED=true --IBM_DB_HOME=$IBM_DB_HOME
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:160:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "build" "--IS_DOWNLOADED=true" "--IBM_DB_HOME=$IBM_DB_HOME"
gyp ERR! cwd C:\Users\Brayan Suárez M\Desktop\test_server\node_modules\ibm_db
gyp ERR! node -v v9.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

    at ChildProcess.exithandler (child_process.js:272:12)
    at ChildProcess.emit (events.js:160:13)
    at maybeClose (internal/child_process.js:943:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node-gyp configure build  --IS_DOWNLOADED=true --IBM_DB_HOME=$IBM_DB_HOME' }

node-gyp build process failed!
Proceeding with Pre-compiled Binary Installation.

The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the path specified.
child_process.js:614
    throw err;
    ^

Error: Command failed: rmdir /s /q C:\Users\Brayan Suárez M\Desktop\test_server\node_modules\ibm_db\build
The system cannot find the file specified.
The system cannot find the file specified.
The system cannot find the path specified.

    at checkExecSyncError (child_process.js:574:11)
    at execSync (child_process.js:611:13)
    at installPreCompiledWinBinary (C:\Users\Brayan Suárez M\Desktop\test_server\node_modules\ibm_db\installer\driverInstall.js:463:21)
    at C:\Users\Brayan Suárez M\Desktop\test_server\node_modules\ibm_db\installer\driverInstall.js:283:21
    at ChildProcess.exithandler (child_process.js:279:5)
    at ChildProcess.emit (events.js:160:13)
    at maybeClose (internal/child_process.js:943:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ibm_db@2.2.1 install: `node installer/driverInstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ibm_db@2.2.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Brayan Suárez M\AppData\Roaming\npm-cache\_logs\2018-02-20T21_52_20_087Z-debug.log

C:\Users\Brayan Suárez M\Desktop\test_server>npm install --dist-url https://nodejs.org/download/release
npm ERR! code ENOPACKAGEJSON
npm ERR! package.json Non-registry package missing package.json: https://nodejs.org/download/release.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Brayan Suárez M\AppData\Roaming\npm-cache\_logs\2018-02-20T21_52_43_750Z-debug.log**

**Comment by rhtpandeyIN** [comment]
Hi @brayansuarezm , one part of your problem is known issue, but to figure out the other part I need your help to understand the root cause.
Can you please test the below steps, and share the output of those?

1) Please download linux clidriver tar file from below URL:
`https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz`
2) Untar it and set the untared "clidriver" directory path to "IBM_DB_HOME" environment variable.
for ex: "set IBM_DB_HOME=/c/home/clidriver"
note: cross check once that "IBM_DB_HOME" is set correctly. - echo %IBM_DB_HOME% (if windows)
3) Now try to install node-ibm_db using `npm install ibm_db` command.
4) and share the output with us.


Thanks.

**Comment by rhtpandeyIN** [comment]
Hi @brayansuarezm , 
The clidriver problem has been resolved, node-ibm_db installation should work now. 

You can use "npm install ibm_db" command to install node-ibm_db. Please note, check the IBM_DB_HOME environment variable in your system, and if it has some value please delete it, and then try to install ibm_db using above mentioned command.

thanks.
