### ISSUE TITLE
Issue when connecting to IBM DB2 hosted on IBM Bluemix

### ISSUE THREAD

**Issue by jbblairiii** [ibmdb/node-ibm_db#37]
I am trying to use your ibm_db module for Node JS to connect to an IBM DB2 hosted on IBM Bluemix. The version of the database is DB2LUW 10.5.4.

When I try to insert data into a table, I get the following error response:

{"error":"[node-odbc] SQL_ERROR","message":"[IBM][CLI Driver] CLI0123E SQL data type out of range. SQLSTATE=HY004","state":"HY004"}

Is this module compatible with the 10.5.4 release of IBM DB2?

**Comment by bimalkjha** [comment]
yes, it is compatible with db2 v10.5.4. But, not with node v0.12.x.
Can you confirm your node version and the commands using which you installed ibm_db? Also, please share the create table and insert statements commands. Thanks.
