### ISSUE TITLE
Connection Pool issue when using DB2 Cloud High-Availability (HA)

### ISSUE THREAD

**Issue by ripasapa** [ibmdb/node-ibm_db#372]
Have you noticed that using IBM cloud db2 HA the connection pool works only if pool size = 1 and if more than that nothing happens? I add sample add to test that one https://github.com/ripasapa/db2 I really do not know where the problem is ? My code or somewhere else ? thanks

**Comment by bimalkjha** [comment]
@ripasapa I executed the command `node nodedb2.js` after copying your repo. The test file `https://github.com/ripasapa/db2/blob/master/nodedb2.js` seems working fine for me.
This test is initializing pool with 1 connection. I modified it to open 5 connections using command `var ret = pool.init(5, cn);` and it is working fine!

To know how many connections are open in pool, you can just add a command `ibmdb.debug(true);` after ` var ibmdb=require(ibm_db);` command and see the logs in the test output. You can see 5 connections are getting opened and 5 are getting closed.
```
var ibmdb = require('ibm_db');
ibmdb.debug(true);
```
If you have any other test program which is throwing error, please share. The current nodedb2.js test file is working fine. Thanks.

**Comment by DamianCummins** [comment]
Hi @bimalkjha 

I'm also seeing this when running against an DB2 Warehouse on Cloud instance in IBM Cloud with High Availability enabled.

Our test fails with the following `Segmentation fault: 11` error.
```
  DB2Connector FVT
    Create ODBC DB2 Connector Object
Initialising ODBC Connection Pool. Initial size: 5, Max size: 10
----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |        0 |        0 |        0 |        0 |                   |
----------|----------|----------|----------|----------|-------------------|
Segmentation fault: 11
```

Our test succeeds when we point at another instance where High Availability is *not* enabled.
Our test also succeeds when we set the initial Pool size to 1.

We're connecting similarly to the example above.

Any ideas?

**Comment by bimalkjha** [comment]
@DamianCummins Verify it using ibm_db@3.2.3 and let us know. Thanks.
