### ISSUE TITLE
DB2 SQL30081N Error

### ISSUE THREAD

**Issue by Johnbastian** [ibmdb/node-ibm_db#374]
The following code is the entire `index.js` I'm trying to run.
```javascript
var _ = require('lodash'),
    ibmdb = require('ibm_db');

var dbConfig = require('./dbconfig.json');

var connectionObject = {
    DATABASE: dbConfig.database,
    HOSTNAME: dbConfig.host,
    UID: dbConfig.user,
    PWD: dbConfig.pass,
    PORT: dbConfig.port,
    PROTOCOL: 'TCPIP'
};

var query = _.join(['select * from ', dbConfig.schema, '.', dbConfig.table1], '');
console.log(query);

ibmdb.open(connectionObject, { connectTimeout: 120 }, function (openErr, conn) {

    if (openErr) return console.error(openErr);

    // setTimeout(function () {
    //
    //     conn.query(query, function (queryErr, data) {
    //
    //         if (queryErr) console.error(queryErr);
    //         else require('fs').writeFileSync(__dirname + '/data.js', JSON.stringify(data));
    //
    //         conn.close(function () {
    //             console.log('done');
    //         });
    //
    //     });
    //
    // }, 3000);

    conn.query(query, function (queryErr, data) {

        if (queryErr) console.error(queryErr);
        else require('fs').writeFileSync(__dirname + '/data.js', JSON.stringify(data));

        conn.close(function () {
            console.log('done');
        });

    });

});
```

When I first wrote the script and tried to run it, I got the following error:
```
{ Error: [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "169.46.12.230".  Communication function detecting the error: "recv".  Protocol specific error code(s): "54", "*", "0".  SQLSTATE=08001

    at Error (native)
  errors: [],
  error: '[node-odbc] Error in ODBCResult::UV_AfterFetchAll',
  message: '[IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "169.46.12.230".  Communication function detecting the error: "recv".  Protocol specific error code(s): "54", "*", "0".  SQLSTATE=08001\n',
  state: '40003' }
 ```
I would try and spam this script by running `node index.js`, and I found that most of the time it would fail with that error, but with the odd/rare success here and there.

I got in touch with a DB2 STSM (Senior Technical Staff Member) from IBM who tried to check for issues. He did indeed report there were several connection drops against my IP address, but after a few days, I ran the script several times again, and while there was improvement in that there were more success, there were still plenty of failures, with the same error message. However, the STSM contact reported that there were no further drops, and he theorised there may be a driver issue. 
We then raised a support ticket in IBM and later I was provided with this link: https://bitbucket.org/phiggins/db2cli

I downloaded the repo, copied the files into my project, and ran the following: 
`IBM_DB_HOME=./db2cli node index.js`

Now, the script has a lot more successes, but I have noticed an odd behaviour.

The first time I ran the script, it will fail with the same error as before; but, any immediate subsequent runs of the same script (i.e. I spam `IBM_DB_HOME=./db2cli node index.js`), it succeeds.
The same thing happens all over again after I leave it alone for a while.

I have tried several times using a timeout, (the commented out code), but with practically the same behaviour.

Any help in debugging and fixing this issue would be greatly appreciated.

P.S. When I try to open and perform a query on DataGrip, it works without any issues.

**Comment by rhtpandeyIN** [comment]
Hi @Johnbastian ,

Can you please share the 'db2cli' trace with us. It will be really helpful.

**Comment by rhtpandeyIN** [comment]
Hi @Johnbastian ,
Any good news? or do you need any help to collect "cli" traces. If so please contact me directly. thanks.

**Comment by bimalkjha** [comment]
@Johnbastian The "Error in ODBCResult::UV_AfterFetchAll" means query is getting timed out while selecting data. Is the result of select query is very large? Could you please share the SQL too that you passed to query()?

Setting `IBM_DB_HOME=./db2cli` seems incorrect. It should be `export IBM_DB_HOME=<absolute/path/of/db2/install/directory>` if you have installed any db2 client or server in your system locally. Also, IBM_DB_HOME should be set before execution of `npm install ibm_db` command. Thanks.

**Comment by Johnbastian** [comment]
Hello,

Apologies for the delayed response.

The sample query I run is `select * from FOUNDATION.V_HIGH_DEAL_CTRY_AGGREGATED`.

I was pointed to this package, https://bitbucket.org/phiggins/db2cli, but I'm not entirely sure if I've used it correctly. Some guidance on installing it would be helpful. 

I will also need guidance on collecting "cli" traces.

Kind Regards,
Johnbastian

**Comment by bimalkjha** [comment]
@Johnbastian Please do not use https://bitbucket.org/phiggins/db2cli. If you are setting IBM_DB_HOME to this db2cli then please clean the IBM_DB_HOME using "export IBM_DB_HOME= " command and install ibm_db by just running "npm install ibm_db" command.
If issue still exist, cd to ibm_db/installer directory. There you can find two script files: testODBCConnection.bat for windows and testODBCConnection.sh for non-windows. Open testODBCConnection.sh file in editor and replace the line no 29 i.e. db2cli validate command with "node test.js" to execute your test program using this script.
Now, you can execute testODBCConnection.sh to run your test program to repro the issue. testODBCConnection.sh script will generate db2trace files for your test program. On successful repro of the issue, collect the 1.flw, 1.fmt, 1.cli files and share with us. You can mail these files to me on bjha@rocketsoftware.com. Thanks.

**Comment by Johnbastian** [comment]
I've sent an email with a ZIP of the files attached. Hope this helps you to debug the issue

**Comment by Johnbastian** [comment]
The issue seemed to be network related.

**Comment by rhtpandeyIN** [comment]
Issue has been resolved, as per the discussion over mail.

**Comment by jinin2007** [comment]
@Johnbastian  I got exactly the same error code.  Would you mind sharing your solution please?  Thanks.

**Comment by jinin2007** [comment]
@rhtpandeyIN  Would you mind sharing what the issue was and your solution please?  Thanks.

**Comment by Johnbastian** [comment]
@jinin2007 Sorry, there was no code level solution. We determined the issue was with my office network, but we investigate any further to identify what was causing the initial connection drop.

However, if you are experiencing the same behaviour I did, i.e. it fails first time and then works subsequently, the only suggestion I can offer is implementing a limited retry mechanism in your code.

**Comment by jinin2007** [comment]
Hi @Johnbastian, thank you for your reply.  Unfortunately, it seems to fail every single time consistently for me.  Are you connecting to DB2 on Z-sytem?  Thanks.

**Comment by jinin2007** [comment]
Hi @rhtpandeyIN and @bimalkjha, can I use ibm_db to connect to DB2 on Z-sytem?  If so, do I need to install any library or licence for Z-system?  Thanks.

**Comment by bimalkjha** [comment]
@jinin2007 Yes, you can use ibm_db to connect to DB2 on Z/OS. You need to copy db2connect license file under `...\ibm_db\installer\clidriver\license` directory before connection. Please read this doc for detail info: https://github.com/ibmdb/node-ibm_db#for-zos-and-iseries-connectivity

**Comment by bimalkjha** [comment]
@jinin2007 To avoid SQL30081N error for the case reported by issue #497 , please see the update in that issue and use the db2dsdriver.cfg file as mentioned their. Thanks.

**Comment by jinin2007** [comment]
Hi @bimalkjha, thank you for you reply.  I have to delete node_module then deploy to IBM Bluemix using cloud Foundry.  In this case, would you know how to copy db2connect license file into the node_module\ibm_db\installer\clidriver\license folder after deployment by any chance please?  Thanks.

**Comment by bimalkjha** [comment]
@jinin2007 You can keep license file under your project directory anywhere and push it on bluemix along with other project files. Modify your deployment script to move the license file under ibm_db once ibm_db get installed. Thanks.

**Comment by jinin2007** [comment]
Thank you so much for all your help, @bimalkjha : )
