### ISSUE TITLE
test-issue211 connection closed before commit/rollback

### ISSUE THREAD

**Issue by joransiu** [ibmdb/node-ibm_db#375]
There appears to be a timing problem with the test-issue211.js: https://github.com/ibmdb/node-ibm_db/blob/master/test/test-issue211.js#L62-L65

>                   conn2.commitTransaction();
>                   console.log('<<< DATA >>>:', data);
>                   assert.deepEqual(data, [ { '1': 1 } ]);
>                   conn2.closeSync();

The problematic scenario is that commitTransaction is asynchronous, and its underlying SQLEndTrans() calls may thus be executed after conn2.closeSync().   conn1 also has the same issue.

From a failing scenario, we see the odbc traces as follows.  The problem arises in that SQLDisconnect/SQLFreeHandle were invoked before SQLEndTrans/SQLSetConnectAttr().

> [03000154 0000000000000000] SQLDisconnect( hDbc=2 )
> [03000154 0000000000000000] SQLDisconnect( )
> [03000154 0000000000000000]     ---> SQL_ERROR
> 
> [03000154 0000000000000000] SQLFreeHandle( fHandleType=SQL_HANDLE_DBC, hHandle=2 )
> [03000154 0000000000000000] SQLFreeHandle( )
> [03000154 0000000000000000]     ---> SQL_ERROR
> 
> [03000154 0000000000000008] SQLEndTran( fHandleType=SQL_HANDLE_DBC, hHandle=0, fType=SQL_COMMIT )
> [03000154 0000000000000008] SQLEndTran( )
> [03000154 0000000000000008]     ---> SQL_INVALID_HANDLE
> 
> [03000154 0000000000000008] SQLSetConnectAttr( hDbc=0, fAttribute=SQL_ATTR_AUTOCOMMIT, pvParam=&1, iStrLen=-3 )
> [03000154 0000000000000008] SQLSetConnectAttr( )
> [03000154 0000000000000008]     ---> SQL_INVALID_HANDLE

We need to ensure closeSync is invoked only after the rollback or commit has been completed.  Either make rollback/commitTransaction sync and/or have closeSync dependent on rollback/commitTransaction via cb, promise, etc.    

@bimalkjha : Which approach is better?  I don't want to break the original spirit of the test.

**Comment by bimalkjha** [comment]
Second approach is better i.e. have closeSync dependent on rollback/commitTransaction via cb, promise, etc. Thanks.
