### ISSUE TITLE
Resultset variable name length max 30 chars?

### ISSUE THREAD

**Issue by ljerka** [ibmdb/node-ibm_db#376]
Hi, 
I have a stored procedure that has variable names longer that 30 chars, however it seems that they are getting cut off after the 30th char. Because of that, all other variables with the same first 30 chars are not returned in a resultset.
For instance, instead of the resultset 
`{my_very_long_name_for_a_very_long_variable: 'some-value'}`
I am getting 
`{my_very_long_name_for_a_very_l: 'some-value'}`

Since I am not writing those procedures but only reading them, I would appreciate some fix for this.

Thank you in advance.

Node & ibm_db versions:
ibm_db@2.2.1
node: v8.9.3

**Comment by bimalkjha** [comment]
@ljerka Could you please share full DDL of your stored procedure? Thanks.

**Comment by ljerka** [comment]
I can't. As I said - I don't write them, I just call them. But if I am right, this error should really be easy to reproduce. Just put in a resultset (not output parameter) a variable that has a name longer than 30 chars.

**Comment by bimalkjha** [comment]
@ljerka There is a test program `ibm_db/test/test-sp-resultset.js` to test the resultset returned by SP. For `proc1`, we have declared two cursors cr1 and cr2. I have renamed these cursors as `my_very_long_name_for_a_very_long_variable1` and `my_very_long_name_for_a_very_long_variable2` and executed the test program. It works fine! Yes, we need to update connection information in `test/config.testConnectionStrings.json` file before running the test. Also, to get colum names in result set, need to pass `{fetchMode : 4}` in ibmdb.open in test file.
I do not see the name of result set is getting returned by SP. Only the column names. Please try running `node test-sp-resultset.js` command and check the output. Is it possible for you to modify the test-sp-resultset.js file to repro your problem and share here? Thanks.

**Comment by ljerka** [comment]
@bimalkjha I can't run the test. It requires me to have a create table privileges, and I do not have that. Also, I did not say that the resultset has a name, `my_very_long_name_for_a_very_long_variable` was the column name.

I am calling the same procedure via agent in domino designer, and there it is working as expected, the result set has 39 columns.
When calling via node, the result set has only 37 columns. In that 37 columns, the name of 2 of them is shortened to 30 chars, and probably because of that 2 columns are missing (their shortened names corresponds to those 2 shortened that I do get).

Did you try the test on linux or windows? I am on Win7, maybe that is the problem.

Thank you.

**Comment by ljerka** [comment]
@bimalkjha Are there any news regarding this problem? Were you able to reproduce the bug with the Select statement that I wrote in my last post? 
`'SELECT ibmreqd "changingColumnNameToAVeryLongOne" from sysibm.sysdummy1'`

**Comment by bimalkjha** [comment]
Ok. I am able to repro the issue by adding another conn.query() to your repro. Seems the column alias name is coming same as previous one for second too. Let me dig further for next update. thanks.

**Comment by ljerka** [comment]
I think you found another bug that has nothing to do with mine :)

But it seems I found out why this bug is happening only to me - it seems that our db2 has the column name setting of maximum 30bytes. Which then also affects all the aliases in stored procedures, table queries, .... 

I will close this issue since the problem obviously has nothing to do with the ibm_db package.

Thank you very much for your effort.

**Comment by bimalkjha** [comment]
That bug was with my test case. ibm_db is working fine. Thanks for letting that original issue was due to server setting. Thanks.
