### ISSUE TITLE
Memory issues causing node to crash when persisting BLOBS

### ISSUE THREAD

**Issue by iamcdonald** [ibmdb/node-ibm_db#377]
Hi,

I've recently come across an issue where by an `insert` through the `ibm_db` driver can cause the entire node process to crash. I've managed to reproduce it with various data-sets but am not entirely sure what the common thread is.

It first appeared in integration tests where we were trying to persist the the string 'the file content' base64 encoded.

I've created a repo ([https://github.com/iamcdonald/ibm_db-issue](https://github.com/iamcdonald/ibm_db-issue)) that reproduces this behaivour.

Any help would be greatly appreciated,

Iain

**Comment by bimalkjha** [comment]
@iamcdonald While trying the repro ibm_db-issue, I am getting below error. Does the issue reproduces only under docker or is there any simple test program to reproduce it on mac or windows system? 
```
BLR-D-MACOS01.local:/Users/bjha/nodework/install/ibm_db-issue> npm run test

> ibm_db-issue@1.0.0 test /Users/bjha/nodework/install/ibm_db-issue
> npm run deps:start && npm run test:only && npm run test:file:only && npm run deps:stop


> ibm_db-issue@1.0.0 deps:start /Users/bjha/nodework/install/ibm_db-issue
> ./db/start.sh

./db/start.sh: line 6: docker-compose: command not found
./db/start.sh: line 7: docker: command not found
./db/start.sh: line 8: docker-compose: command not found
```
Thanks.

**Comment by bimalkjha** [comment]
@iamcdonald I modified `test.spec.js` file as below and executed it successfully using `node test.spec.js` command. I do not see any memory error or node crash after executing this test file. I have created dummy table using command : `create table dummy (data BLOB(64K))` before running this test program.
```
const data = require('./data');
const fs = require('fs');
const path = require('path');

const INSERT_BLOB = `
  INSERT INTO DUMMY
  (DATA) VALUES (?)
`;

console.log('ibm_db memory issue');

console.log('when attempting to insert the data in base64 format');
var  val = 'dGhlIGZpbGUgY29udGVudA==';
//var  val = fs.readFileSync(path.resolve('file.xlsx')).toString('base64');

console.log('throws a myriad of memory errors within the ODBC binding');
const insertVal = {
        DataType: 'BLOB',
        Data: val
      };
data.execute(INSERT_BLOB, [insertVal]);
```
On selecting the data using db2cli, I can see below result:
```
> select * from dummy
select * from dummy
FetchAll:  Columns: 1
  DATA
  6447686C49475A7062475567593239756447567564413D3D
FetchAll: 1 rows fetched.
```
This test program works fine for data in file.xlsx too. You can just save the above pasted test program as test.js under test directory and execute it. Thanks.

**Comment by iamcdonald** [comment]
Docker is used to spin up a db2 instance with a db structure holding columns similar to how they're declared across environments (held in this [file](https://github.com/iamcdonald/ibm_db-issue/blob/master/db/db2/container/provision.sql)). I notice this is different to the `create table ...` command you used.

Also, with regards to the file.xlsx, if you read through the [file test](https://github.com/iamcdonald/ibm_db-issue/blob/master/test/test.file.spec.js) it's doing an insert to another table first, I found that without this I wasn't seeing the issue.

I'll see if I can run against a non-docker db2 but we're fairly locked down, hence the use of docker. 

Equally, it'd be good if you could run the [provision.sql](https://github.com/iamcdonald/ibm_db-issue/blob/master/db/db2/container/provision.sql)  against a non-docker version of db2 and run the tests as they are against that db2 instance (should just require changes to the connection string [here](https://github.com/iamcdonald/ibm_db-issue/blob/master/test/data.js#L4)). 

Would that be possible?

**Comment by iamcdonald** [comment]
Hi @bimalkjha,
 
I've now run the tests against both docker and non-docker db2 instances.
I've also ran both tests within linux (via docker) and locally on my mac.  

The outcomes of this and commands to make running the tests against various infrastructure have been added to the [repo](https://github.com/iamcdonald/ibm_db-issue) but the gist is below

 Host OS -> DB2                   | Error Seen        
 ---                       | ---       
linux -> docker db2              | &#x2713;          
linux -> actual db2 instance     | &#x2713;          
mac -> docker db2                | &#x2717;          
mac -> actual db2  instance      | &#x2717;      

This would lead me to think that the issue is with the underlying linux odbc driver pulled from [here](https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/) by  [`installer/driverInstall.js`](https://github.com/ibmdb/node-ibm_db/blob/master/installer/driverInstall.js#L14).

**Comment by bimalkjha** [comment]
@iamcdonald Please share version of your linux OS. Also, is it possible for you to try on Windows?
Good to check with older level of node.js too on linux like 4.x or 0.12.x. Thanks.

**Comment by iamcdonald** [comment]
I'm using the version of linux used within the `node:8` docker image which is `debian:jessie`. I'm afraid I don't have access to a windows machine unless I was to try and run the code in a Windows VM.

@bimalkjha Have you tried to run the tests against docker and actual db2 instances across the range of host OS's (Linux, Mac and Windows) running various versions of node (8.x, 4.x, 0.12.x)?

**Comment by iamcdonald** [comment]
Hi Bimal,

I'm trying to understand what you're suggesting from the above, Is any of the commented out code intended to show anything.

Furthermore, I can't help but notice that in your string `aaaaaaaaaaaaaaaaaaaaaaaa\0` you've added a termination character to a string which is already 24 characters long i.e.
```js
var chars24 = "aaaaaaaaaaaaaaaaaaaaaaaa\0"
console.log(chars24.length) //will print 25
```
If I remove one of the `a` characters from your suggestion so that I'm still persisting 24 characters but with the last one being a null termination (e.g. `aaaaaaaaaaaaaaaaaaaaaaa\0`) I still see the same issue as before.

Therefore I don't think this fixes the problem or even provides a workaround in the mean time.
