### ISSUE TITLE
Installation and runtime problems

### ISSUE THREAD

**Issue by yurigracida** [ibmdb/node-ibm_db#382]
I have recently change my laptop, from win 7 to win 10.
when run npm install on my project I see many warnings and notes like:
warning C4005: 'FAR'
warning C4244: '=': conversion from 'int64_t' to 'SQLSMALLINT'
warning C4996: 'v8::Object::SetPrototype': was declared deprecated
note: see declaration of 'v8::Function::NewInstance'
still got message node-ibm_db installed successfully!

now, when I run project I got this
[1] C:\github\grants\node_modules\ibm_db\lib\odbc.js:1466
[1]   if(!ENV) ENV = new odbc.ODBC();
[1]                  ^
[1] [object Object]
[0] [15:02:51] Finished 'index' after 112 ms
[1] [nodemon] app crashed - waiting for file changes before starting..

I have node v8.11.1, npm 5.6.0 and no clue why its failin. 

Any ideas ? Thanks !!!!

**Comment by bimalkjha** [comment]
@yurigracida Its looks same issue as reported by #168 & #343 . It occurs due to some permission issue. Please go through these two issues and fix your environment. Thanks.
