### ISSUE TITLE
ibm_db TIMEDOUT error when installing on windows 10

### ISSUE THREAD

**Issue by kotha16** [ibmdb/node-ibm_db#384]
i execute the following command 
npm i ibm_db

and get this error
{ Error: connect ETIMEDOUT 170.225.15.112:443
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',

Can anyone help me on this

**Comment by bimalkjha** [comment]
@kotha16 Are you able to install any other package from npm like `npm install nan` or `npm install express`? Can you check and then try `npm install ibm_db`? Thanks.

**Comment by kotha16** [comment]
Yes..I am able to install express and other npm packages. ibm_db fails with the above error

**Comment by kotha16** [comment]
Yes..I am able to install express and other npm packages. ibm_db fails with the above error

**Comment by bimalkjha** [comment]
@kotha16 Please share the complete output of `npm install ibm_db` command. Thanks.

**Comment by kotha16** [comment]
Attached the log of npm install ibm_db
[npm_ibm_db_log.txt](https://github.com/ibmdb/node-ibm_db/files/1967473/npm_ibm_db_log.txt)

**Comment by bimalkjha** [comment]
@kotha16 Thanks for sharing the complete output. Here is the error which is causing this issue:
```
Downloading DB2 ODBC CLI Driver from https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/ntx64_odbc_cli.zip...

{ Error: connect ETIMEDOUT 170.225.15.112:443
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '170.225.15.112',
  port: 443 }
```
Your installation is failing because ibm_db is unable to download https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/ntx64_odbc_cli.zip file. Could you try to download this file? Seems some firewall setting of your system is blocking it to download. Please check firewall settings to solve this problem. Thanks.

**Comment by kotha16** [comment]
> ibm_db@2.3.1 install C:\Users\A547010\Documents\NodeProjs\ts_demo1\node_modules\ibm_db
> node installer/driverInstall.js

Downloading DB2 ODBC CLI Driver from https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/ntx64_odbc_cli.zip...

After looking closely at the link from the error log above. It seems there are 3 dots after the ntx64_odbc_cli.zip... which may be causing the timeout error....

I copied the above link as is and got not found error in the browser....however if i remove the 3 dots at the end of ".zip..." then i can download the file in the browser.

Can you check the package and make sure the dots are not part of the link.

**Comment by rhtpandeyIN** [comment]
>Can you check the package and make sure the dots are not part of the link.
No, dots are not part of the downloading link, it was just coming from the console.log
>console.log('Downloading DB2 ODBC CLI Driver from ' +installerfileURL+'...\n');

So problem is not in the downloading URL, also you mentioned you were able to install via 'yarn' package manager, so it must be proxy configuration in npm. try to clean  npm and the set the correct proxy again.

You will need to set 'https' proxy, because downloading url is from https site. just for reference:
```
$ npm config set proxy http://<username>:<password>@<proxy-server-url>:<port>
$ npm config set https-proxy http://<username>:<password>@<proxy-server-url>:<port>
```

Thanks.

**Comment by bimalkjha** [comment]
@kotha16 Still seems issue with your firewall setting or application setting. To work around the issue, if you are able to download the file https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/ntx64_odbc_cli.zip, unzip it. You'll get a folder named `clidriver`. Set a system environment variable IBM_DB_HOME=<absolute_path_to_clidriver_folder>, open a new command window and install ibm_db. If IBM_DB_HOME is set, ibm_db do not download the .zip file as it is already downloaded. Thanks.

**Comment by rhtpandeyIN** [comment]
Hi @kotha16 , is this issue still persist, or you able to resolve it? Please share the update with us.

**Comment by 2020-abhilash** [comment]
It still doesn't work for me. I get the same error!

**Comment by rhtpandeyIN** [comment]
Hi @2020-abhilash , what version of node you are using? and can you please share the error log with us. Did you check your npm proxy configuration?

**Comment by bimalkjha** [comment]
@2020-abhilash Apply the solution shared on my 9th May update. If still facing problem, open a new issue. Thanks.

**Comment by Gajendrasinh** [comment]
Hello 

I have same issue any solution for below error


> ibm_db@2.5.2 install C:\Users\test\Desktop\Workspace\nodeapp\node_modules\ibm_db
> node installer/driverInstall.js

Downloading DB2 ODBC CLI Driver from https://porxy/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/ntx64_odbc_cli.zip

{ Error: connect ETIMEDOUT 170.225.15.112:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '170.225.15.112',
  port: 443 }

**Comment by 2020-abhilash** [comment]
Download the file manually and place it in a local directory. Set the environment variable to point to that path instead of the URL and then rerun your install command.

**Comment by Gajendrasinh** [comment]
@2020-abhilash 

Can you share where i can set path?

**Comment by 2020-abhilash** [comment]
@Gajendrasinh I do not remember the environment variable exactly. But it is easy to find if you Google. I guess it's IBM_DRIVER_PATH or something like that. That has been suggested in many other threads. Sorry I do not have my laptop at this time to find out the exact value.

**Comment by 2020-abhilash** [comment]
@Gajendrasinh do as mentioned in this comment by @bimalkjha

https://github.com/ibmdb/node-ibm_db/issues/384#issuecomment-387793930
