### ISSUE TITLE
QueryTimeout possibility?

### ISSUE THREAD

**Issue by oren1991** [ibmdb/node-ibm_db#385]
Hi All!
I would like to have the possibility to cancel an SQL execution in case the fetching have not started in a given timeperiod.

I could solve it with setTimeout or promises, however that would leave the db2 session running.
Is there any way to set up a timeout for the execution?

Thank you!

**Comment by huineng** [comment]
i do this in my connection string setting

```
connString: `PROTOCOL=TCPIP;
DATABASE=${datab.db};
UID=${datab.username};
PWD=${datab.password};
HOSTNAME=${datab.hostname};
Servicename=${datab.sslport};
QueryTimeout=120;
CHARSET=UTF8;`,
```

if this helps

**Comment by bimalkjha** [comment]
@oren1991 For execution timeout, you can set QueryTimeout  value in connection string as suggested by @huineng . Alternatively, you can set this value in ibm_db/installer/clidriver/cfg/db2cli.ini file and ibm_db/installer/clidriver/cfg/db2dsdriver.cfg file as well. You can update db2cli.ini file as below to make it effective for all connections to any database:
```
[common]
QueryTimeout=120

```
Thanks.
