### ISSUE TITLE
Output CHAR Parameter Length

### ISSUE THREAD

**Issue by shireresident** [ibmdb/node-ibm_db#386]
This isn't an issue but need clarification

In the samples of SP calls I see examples like this
param2 = {ParamType:"INOUT", DataType:1, Data:"abc", Length:50};

Does the length here denote characters or bytes?

 I am calling a stored procedure that returns CHAR output fields and they are all truncated to Length/2-1 characters. Seems like the data is double bytes and the Length denotes bytes. I need to confirm what the Length represents and how to verify the character set.

**Comment by bimalkjha** [comment]
@shireresident Your observation is correct. The Length denote the buffer length in byte to store the OUT Pamameter value. Strings in javascript is by default in unicode that takes 2 bytes and last character is null terminator character(which is of 2bytes for unicode), hence Length/2 -1.
The Length is used as BufferLength internally and its details is as below:
```
For output parameters, BufferLength is used to determine whether to truncate character or binary output data in the following manner:

    For character data, if the number of bytes available to return is greater than or equal to BufferLength, the data in Buffer is truncated to BufferLength-1 bytes and is null-terminated (unless null-termination has been turned off).
    For binary data, if the number of bytes available to return is greater than BufferLength, the data in ParameterValuePtr is truncated to BufferLength bytes.
```
Thanks.

**Comment by shireresident** [comment]
@bimalkjha thanks for the information. After posting this I realized that this only happens on my local WIN7 machine. When I deploy my code to a RHEL7 machine I don't see the same thing. The code processes all the bytes except the last one. All my strings here were English.

To validate I tried to add some French characters and it truncated some characters so I believe it is interpreting the string as UTF-8. 

The binding.gyp has
```
 'conditions' : [
        [ 'OS != "zos"',
          { 'defines' : [ 'UNICODE'], }
        ]
      ],
```
Looking at the C++ file it seems if UNICODE is set, it should interpret as 2 bytes else utf-8. 

Is there anything else that dictates this?

**Comment by bimalkjha** [comment]
@shireresident Please share a small test script to reproduce this behavior. Then I can look deeper into code and comment. Thanks.

**Comment by bimalkjha** [comment]
@shireresident [this](https://github.com/ibmdb/node-ibm_db/commit/0e4c01d005fb65a304d4c64ab58e569a0d97aaa2) commit has fixed the French characters issue. Similar problem was reported by issue #402 too. Using latest code you should not face this problem. Thanks.
