### ISSUE TITLE
Support Node v10.x

### ISSUE THREAD

**Issue by huineng** [ibmdb/node-ibm_db#387]
Node 10 is out , so i assume we might see an update soon to support the new release ?

thanks

```
Downloading and extraction of DB2 ODBC CLI Driver completed successfully ...

  CXX(target) Release/obj.target/odbc_bindings/src/odbc.o

{ Error: Command failed: node-gyp configure build  --IS_DOWNLOADED=true --IBM_DB_HOME="$IBM_DB_HOME"
In file included from ../src/odbc.cpp:28:
In file included from ../src/odbc.h:23:
In file included from ../../nan/nan.h:190:
../../nan/nan_maybe_43_inl.h:88:15: error: no member named 'ForceSet' in 'v8::Object'
  return obj->ForceSet(GetCurrentContext(), key, value, attribs);
         ~~~  ^
In file included from ../src/odbc.cpp:28:
In file included from ../src/odbc.h:23:
../../nan/nan.h:816:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
```

**Comment by alobaidizt** [comment]
@rhtpandeyIN any plans to support Node 10?

**Comment by bimalkjha** [comment]
Yes, we have plan to support Node 10 and Rohit is working on it. Note 10 has broke the backward compatibility and we are waiting for the release of a new version of [nan](https://www.npmjs.com/package/nan) package with Node 10 support. ibm_db has dependency on nan to support multiple versions of Node.js. Thanks.

**Comment by alobaidizt** [comment]
@bimaljha Thanks for the update! Did you open an issue on nan Github repo for supporting Node 10?

Also, is there a tentative timeline for when Node 10 support will be available? 

Thank you very much!

**Comment by bimalkjha** [comment]
@alobaidizt Yes, we have opened a [new issue](https://github.com/nodejs/nan/issues/770) against nan package. I can see few commits specific to node v10 in github repo of nan but documents says it supports node v0.8 to v9 only. Seems, they are working on it. Timeline I don't know. Feel free to comment on that issue. Thanks.

**Comment by alobaidizt** [comment]
@bimaljha their comment is pointing to an error coming from your code. Looks like that method you're calling no longer exist. Can you please resolve that problem?

**Comment by alobaidizt** [comment]
Do you have any ideas on that?

**Comment by rhtpandeyIN** [comment]
Hi @alobaidizt , @huineng , Issue has been addressed with the latest pull request, new node-ibm_db version will be released soon. thanks.

**Comment by alobaidizt** [comment]
Thank you so much guys!

**Comment by HermansJarno** [comment]
@rhtpandeyIN Any news about this?
