### ISSUE TITLE
Strange error code SQL0104N  An unexpected token "RO"

### ISSUE THREAD

**Issue by huineng** [ibmdb/node-ibm_db#388]
node: 9.11.1
ibm_db:  2.3.1

issue sql error when using special character  

test case was with the word "für"

this works .. 
select * from table where UCASE(NAME) LIKE '%FÜR%' FOR READ ONLY WITH UR OPTIMIZE FOR 50 ROWS

this works on sql tools but not in ibm_db  : select from table where (UCASE(NAME) LIKE '%FÜR%' OR UCASE(NAME) LIKE '%FÜR%') FOR READ ONLY WITH UR OPTIMIZE FOR 50 ROWS

it produces an error :
SQL0104N  An unexpected token "RO" was found following "H UR OPTIMIZE FOR 50"
which is absolutely not related to the syntax of the sql

so it works with just one statement but when including an OR 

this works in node changing the character

this works on sql tools : select from table where (UCASE(NAME) LIKE '%FUR%' OR UCASE(NAME) LIKE '%FUR%') FOR READ ONLY WITH UR OPTIMIZE FOR 50 ROWS

is this a bug or is there some special encoding setting to be done 

thanks

**Comment by huineng** [comment]
more or less same problem

```
UPDATE TABLE SET CUSTNAME = 'Crédit Agricole'
```

fails with "SQL0010N  The string constant beginning with"  which is NOT the real error

nevertheless sending this as a parameter works 

UPDATE TABLE SET CUSTNAME = ?
params = ['Crédit Agricole']

1. Is this normal behaviour 
2. the returned sql error (case)1 is not the right error, though i have not an idea what the real error is

**Comment by bimalkjha** [comment]
@huineng Test case [ibm_db/test/test-basic-test.js](https://github.com/ibmdb/node-ibm_db/commit/75cf66004232d071e7f76c7acfd7672db8f8e759) uses the same string "für" in SQL and it works fine for me. Please pull the latest code and verify that. I have just updated the test file with string "für" in query.

The SQL0010N error is coming from server. You can collect ODBC trace by running your test program replacing 'db2cli validate' command in ibm_db/installer/testODBCConnection.sh' file and see what SQL is actually getting send to server. If client is sending correct SQL to server, then some setting issue might be at server side. This error is coming from DB2 server. Thanks.

**Comment by huineng** [comment]
ok, i'm closing this, i also updated my docker (as this runs in docker) to update-locale LANG=en_US.UTF-8  and that seems to have solved the problem (on my mac i don't have lang ut8 so that might explain the difference on local
