### ISSUE TITLE
Failed to install Ibm_db Module

### ISSUE THREAD

**Issue by vamshikrishnanethi** [ibmdb/node-ibm_db#389]
All of a sudden doing an npm install is not working. Its continuously throwing this error saying that its unable to install ibm_db module. Not sure if npm support for ibm_db has been changed or deprecated.

![image](https://user-images.githubusercontent.com/17882168/39313935-2c26cbea-4941-11e8-9074-785c31233017.png)
![image](https://user-images.githubusercontent.com/17882168/39313985-47539498-4941-11e8-9b96-5b449a484476.png)
![image](https://user-images.githubusercontent.com/17882168/39314042-59c57a2e-4941-11e8-839a-fa3153fa28cc.png)

Thanks

**Comment by bimalkjha** [comment]
@vamshikrishnanethi Issue seems because your user name "Vamshi K Nethi" has space. Please try to install under C: drive or a path without space. That should work. Meanwhile, we'll try to fix this issue in ibm_db too. Thanks.

**Comment by vamshikrishnanethi** [comment]
@bimalkjha Thank you, that resolved the issue in my local. I didn't know a space created this issue.

My main issue is deploying the application to Bluemix. I have a node JS with React app running on a bluemix dedicated environment and we use Travis CI to build and deploy the application in bluemix. For some reason the build keeps failing continuously and looking into the logs I found out that its not able to install ibm_db module. So I tried to do in my local and it was not working either. So I have raised an issue.

Can you please take a look at the logs below and let me know if there is anything wrong from my end. This issue started 2 days ago. The previous builds were successful and I don't know what happened but all of a sudden builds started to fail.

![image](https://user-images.githubusercontent.com/17882168/39363292-c0285fbe-49f7-11e8-8579-6a316dc7fb18.png)
![image](https://user-images.githubusercontent.com/17882168/39363318-dc528304-49f7-11e8-9885-270b6c193d0f.png)
![image](https://user-images.githubusercontent.com/17882168/39363335-eeaaf400-49f7-11e8-8c12-a85cd95e89b2.png)
![image](https://user-images.githubusercontent.com/17882168/39363360-086d5e8c-49f8-11e8-964d-a78f1a05a67d.png)
![image](https://user-images.githubusercontent.com/17882168/39363373-194369f4-49f8-11e8-9455-67d2e9be8181.png)
![image](https://user-images.githubusercontent.com/17882168/39363399-2fdb96fa-49f8-11e8-9f74-6e2278f2c78d.png)
![image](https://user-images.githubusercontent.com/17882168/39363416-3e7b0fe2-49f8-11e8-915c-790fb43d94dc.png)
![image](https://user-images.githubusercontent.com/17882168/39363436-4fbaf592-49f8-11e8-8ad9-6df1a9427b75.png)

Thanks

**Comment by bimalkjha** [comment]
@vamshikrishnanethi The error that you are facing is same as #387 . You are using node.js v10.0.0 and ibm_db v2.2.1. Node.js v10.0.0 is released recently and we need to update code of ibm_db to support this version of node.js. Please use older version of node.js and latest version of ibm_db@2.3.1. That should fix your issue. Thanks.

**Comment by vamshikrishnanethi** [comment]
@bimalkjha Bulls eye. So the node version was creating all the trouble. Appreciate your help. Thank You.

Just FYI, I didn't find anywhere mentioning about ibm_db module not working with certain node versions. May be you need to put it so that the users will be aware of that. 

Thanks again
