### ISSUE TITLE
uploading to bluemix fails but local runs perfect

### ISSUE THREAD

**Issue by Zerodante** [ibmdb/node-ibm_db#390]
It runs perfectly on local but when i try to do "bluemix app push" it prints this error:     

 ibm_db@2.3.1 install /tmp/app/node_modules/ibm_db

       Rebuild Process: Found clidriver at -> /tmp/app/node_modules/ibm_db/installer/clidriver

       Downloading of clidriver skipped - build is in progress...
       CXX(target) Release/obj.target/odbc_bindings/src/odbc.o
       CXX(target) Release/obj.target/odbc_bindings/src/odbc_connection.o
       CXX(target) Release/obj.target/odbc_bindings/src/odbc_result.o
       SOLINK_MODULE(target) Release/obj.target/odbc_bindings.node
       { Error: Command failed: node-gyp configure build  --IS_DOWNLOADED=true --IBM_DB_HOME="$IBM_DB_HOME"
       ../src/odbc.cpp: In static member function ‘static void ODBC::UV_AfterCreateConnection(uv_work_t*, int)’:
       ../src/odbc.cpp:207:99: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const’ is deprecated (declared at /tmp/app/vendor/node/include/node/v8.h:3657): Use maybe version [-Wdeprecated-declarations]
       Local<Object> js_result = Nan::New<Function>(ODBCConnection::constructor)->NewInstance(2, info);
       ../src/odbc.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE ODBC::CreateConnectionSync(Nan::NAN_METHOD_ARGS_TYPE)’:
       ../src/odbc.cpp:250:99: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const’ is deprecated (declared at /tmp/app/vendor/node/include/node/v8.h:3657): Use maybe version [-Wdeprecated-declarations]
       Local<Object> js_result = Nan::New<Function>(ODBCConnection::constructor)->NewInstance(2, params);
       make: Entering directory `/tmp/app/node_modules/ibm_db/build'
       CXX(target) Release/obj.target/odbc_bindings/src/odbc_statement.o
       make: Leaving directory `/tmp/app/node_modules/ibm_db/build'

       ^
       ^
       ../src/odbc.cpp: In static member function ‘static v8::Local<v8::Value> ODBC::GetSQLError(SQLSMALLINT, SQLHANDLE, char*)’:
       ../src/odbc.cpp:1198:87: warning: ‘bool v8::Object::SetPrototype(v8::Local<v8::Value>)’ is deprecated (declared at /tmp/app/vendor/node/include/node/v8.h:3101): Use maybe version [-Wdeprecated-declarations]
       objError->SetPrototype(Exception::Error(Nan::New(errorMessage).ToLocalChecked()));
       ^
       ./Release/.deps/Release/obj.target/odbc_bindings/src/odbc.o.d.raw Stats {
       dev: 192,
       mode: 33188,
       nlink: 1,
       uid: 2000,
       gid: 2000,
       rdev: 0,
       blksize: 4096,
       ino: 22701,
       size: 1759,
       blocks: 8,
       atime: 2018-04-26T19:44:41.000Z,
       mtime: 2018-04-26T19:44:41.000Z,
       ctime: 2018-04-26T19:44:41.324Z,
       birthtime: 2018-04-26T19:44:41.324Z }
       ../src/odbc_connection.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE ODBCConnection::CreateStatementSync(Nan::NAN_METHOD_ARGS_TYPE)’:
       ../src/odbc_connection.cpp:809:96: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const’ is deprecated (declared at /tmp/app/vendor/node/include/node/v8.h:3657): Use maybe version [-Wdeprecated-declarations]
       Local<Object> js_result(Nan::New<Function>(ODBCStatement::constructor)->NewInstance(3, params));
       ^
       ../src/odbc_connection.cpp: In static member function ‘static void ODBCConnection::UV_AfterCreateStatement(uv_work_t*, int)’:
       ../src/odbc_connection.cpp:893:96: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const’ is deprecated (declared at /tmp/app/vendor/node/include/node/v8.h:3657): Use maybe version [-Wdeprecated-declarations]
       Local<Object> js_result = Nan::New<Function>(ODBCStatement::constructor)->NewInstance(3, info);
       ^
       ../src/odbc_connection.cpp: In static member function ‘static void ODBCConnection::UV_AfterQuery(uv_work_t*, int)’:
       ../src/odbc_connection.cpp:1136:95: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const’ is deprecated (declared at /tmp/app/vendor/node/include/node/v8.h:3657): Use maybe version [-Wdeprecated-declarations]
       Local<Object> js_result = Nan::New<Function>(ODBCResult::constructor)->NewInstance(4, info);
       ^
       ../src/odbc_connection.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE ODBCConnection::QuerySync(Nan::NAN_METHOD_ARGS_TYPE)’:
       ../src/odbc_connection.cpp:1365:97: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const’ is deprecated (declared at /tmp/app/vendor/node/include/node/v8.h:3657): Use maybe version [-Wdeprecated-declarations]
       Local<Object> js_result = Nan::New<Function>(ODBCResult::constructor)->NewInstance(4, result);
       ^
       ./Release/.deps/Release/obj.target/odbc_bindings/src/odbc_connection.o.d.raw Stats {
       dev: 192,
       mode: 33188,
       nlink: 1,
       uid: 2000,
       gid: 2000,
       rdev: 0,
       blksize: 4096,
       ino: 22707,
       size: 1781,
       blocks: 8,
       atime: 2018-04-26T19:44:44.000Z,
       mtime: 2018-04-26T19:44:44.000Z,
       ctime: 2018-04-26T19:44:44.088Z,
       birthtime: 2018-04-26T19:44:44.088Z }
       ../src/odbc_statement.cpp: In static member function ‘static void ODBCStatement::UV_AfterExecute(uv_work_t*, int)’:
       ../src/odbc_statement.cpp:217:95: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const’ is deprecated (declared at /tmp/app/vendor/node/include/node/v8.h:3657): Use maybe version [-Wdeprecated-declarations]
       Local<Object> js_result = Nan::New<Function>(ODBCResult::constructor)->NewInstance(4, info);
       ^
       ../src/odbc_statement.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE ODBCStatement::ExecuteSync(Nan::NAN_METHOD_ARGS_TYPE)’:
       ../src/odbc_statement.cpp:289:87: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const’ is deprecated (declared at /tmp/app/vendor/node/include/node/v8.h:3657): Use maybe version [-Wdeprecated-declarations]
       Local<Object> js_result = Nan::New(ODBCResult::constructor)->NewInstance(4, result);
       ^
       ../src/odbc_statement.cpp: In static member function ‘static void ODBCStatement::UV_AfterExecuteDirect(uv_work_t*, int)’:
       ../src/odbc_statement.cpp:531:85: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const’ is deprecated (declared at /tmp/app/vendor/node/include/node/v8.h:3657): Use maybe version [-Wdeprecated-declarations]
       js_result.Reset(Nan::New<Function>(ODBCResult::constructor)->NewInstance(4, info));
       ^
       ../src/odbc_statement.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE ODBCStatement::ExecuteDirectSync(Nan::NAN_METHOD_ARGS_TYPE)’:
       ../src/odbc_statement.cpp:596:87: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const’ is deprecated (declared at /tmp/app/vendor/node/include/node/v8.h:3657): Use maybe version [-Wdeprecated-declarations]
       js_result.Reset(Nan::New<Function>(ODBCResult::constructor)->NewInstance(4, result));
       ^
       ./Release/.deps/Release/obj.target/odbc_bindings/src/odbc_statement.o.d.raw Stats {
       dev: 192,
       mode: 33188,
       nlink: 1,
       uid: 2000,
       gid: 2000,
       rdev: 0,
       blksize: 4096,
       ino: 22709,
       size: 1779,
       blocks: 8,
       atime: 2018-04-26T19:44:46.000Z,
       mtime: 2018-04-26T19:44:46.000Z,
       ctime: 2018-04-26T19:44:46.032Z,
       birthtime: 2018-04-26T19:44:46.032Z }
       ../src/odbc_result.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE ODBCResult::Fetch(Nan::NAN_METHOD_ARGS_TYPE)’:
       ../src/odbc_result.cpp:183:57: warning: ‘v8::Local<v8::Int32> v8::Value::ToInt32() const’ is deprecated (declared at /tmp/app/vendor/node/include/node/v8.h:9041): Use maybe version [-Wdeprecated-declarations]
       data->fetchMode = obj->Get(fetchModeKey)->ToInt32()->Value();
       ^
       ../src/odbc_result.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE ODBCResult::FetchSync(Nan::NAN_METHOD_ARGS_TYPE)’:
       ../src/odbc_result.cpp:337:51: warning: ‘v8::Local<v8::Int32> v8::Value::ToInt32() const’ is deprecated (declared at /tmp/app/vendor/node/include/node/v8.h:9041): Use maybe version [-Wdeprecated-declarations]
       fetchMode = obj->Get(fetchModeKey)->ToInt32()->Value();
       ^
       ../src/odbc_result.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE ODBCResult::FetchAll(Nan::NAN_METHOD_ARGS_TYPE)’:
       ../src/odbc_result.cpp:435:57: warning: ‘v8::Local<v8::Int32> v8::Value::ToInt32() const’ is deprecated (declared at /tmp/app/vendor/node/include/node/v8.h:9041): Use maybe version [-Wdeprecated-declarations]
       data->fetchMode = obj->Get(fetchModeKey)->ToInt32()->Value();
       ^
       ../src/odbc_result.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE ODBCResult::FetchAllSync(Nan::NAN_METHOD_ARGS_TYPE)’:
       ^
       ./Release/.deps/Release/obj.target/odbc_bindings/src/odbc_result.o.d.raw Stats {
       dev: 192,
       mode: 33188,
       nlink: 1,
       uid: 2000,
       gid: 2000,
       rdev: 0,
       blksize: 4096,
       ino: 22711,
       size: 1773,
       blocks: 8,
       atime: 2018-04-26T19:44:47.000Z,
       mtime: 2018-04-26T19:44:47.000Z,
       ctime: 2018-04-26T19:44:47.780Z,
       birthtime: 2018-04-26T19:44:47.780Z }
       make: *** [Release/obj.target/odbc_bindings.node] Error 1
       gyp ERR! build error
       gyp ERR! stack     at ChildProcess.onExit (/tmp/app/vendor/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
       gyp ERR! stack     at emitTwo (events.js:106:13)
       gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
       gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
       gyp ERR! cwd /tmp/app/node_modules/ibm_db
       gyp ERR! not ok
       at ChildProcess.exithandler (child_process.js:205:12)
       at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
       killed: false,
       code: 1,
       cmd: 'node-gyp configure build  --IS_DOWNLOADED=true --IBM_DB_HOME="$IBM_DB_HOME"' }

       npm ERR! Linux 4.4.0-109-generic
       npm ERR! argv "/tmp/app/vendor/node/bin/node" "/tmp/app/vendor/node/bin/npm" "rebuild" "--nodedir=/tmp/app/vendor/node"
       npm ERR! Exit status 1
       ../src/odbc_result.cpp:618:51: warning: ‘v8::Local<v8::Int32> v8::Value::ToInt32() const’ is deprecated (declared at /tmp/app/vendor/node/include/node/v8.h:9041): Use maybe version [-Wdeprecated-declarations]
       fetchMode = obj->Get(fetchModeKey)->ToInt32()->Value();
       /usr/bin/ld: cannot find -ldb2
       collect2: error: ld returned 1 exit status
       gyp ERR! stack Error: `make` failed with exit code: 2
       gyp ERR! System Linux 4.4.0-109-generic
       gyp ERR! command "/tmp/app/vendor/node/bin/node" "/tmp/app/vendor/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build" "--IS_DOWNLOADED=true" "--IBM_DB_HOME=/tmp/app/node_modules/ibm_db/installer/clidriver"
       gyp ERR! node -v v7.10.0
       gyp ERR! node-gyp -v v3.5.0

       at emitTwo (events.js:106:13)
       at ChildProcess.emit (events.js:194:7)
       at maybeClose (internal/child_process.js:899:16)
       signal: null,
       npm ERR! node v7.10.0
       npm ERR! npm  v4.2.0
       npm ERR! code ELIFECYCLE
       npm ERR! errno 1
       npm ERR! ibm_db@2.3.1 install: `node installer/driverInstall.js`
       npm ERR!
       npm ERR! Failed at the ibm_db@2.3.1 install script 'node installer/driverInstall.js'.
       npm ERR! Make sure you have the latest version of node.js and npm installed.
       npm ERR! If you do, this is most likely a problem with the ibm_db package,
       npm ERR! not with npm itself.
       npm ERR! Tell the author that this fails on your system:
       npm ERR!     node installer/driverInstall.js
       npm ERR! You can get information on how to open an issue for this project with:
       npm ERR!     npm bugs ibm_db
       npm ERR! Or if that isn't available, you can get their info via:
       npm ERR!     npm owner ls ibm_db
       npm ERR! There is likely additional logging output above.

       npm ERR! Please include the following file with any support request:
       npm ERR!     /home/vcap/.npm/_logs/2018-04-26T19_44_47_904Z-debug.log
-----> Build failed

       Some possible problems:

       - node_modules checked into source control
       http://docs.cloudfoundry.org/buildpacks/node/node-tips.html

Failed to compile droplet: Failed to compile droplet: exit status 1
Exit status 223

**Comment by bimalkjha** [comment]
@Zerodante Could you share the output of `npm install ibm_db` from start? I am interested to look the output before below lines:
```
   Rebuild Process: Found clidriver at -> /tmp/app/node_modules/ibm_db/installer/clidriver

   Downloading of clidriver skipped - build is in progress...
```
Uploading is failing due to below error:
```
/usr/bin/ld: cannot find -ldb2
   collect2: error: ld returned 1 exit status
   gyp ERR! stack Error: `make` failed with exit code: 2
   gyp ERR! System Linux 4.4.0-109-generic
```
It says the ld command is unable to find libdb2.so.1 file. If you add /tmp/app/node_modules/ibm_db/installer/clidriver/lib to LD_LIBRARY_PATH, then this issue go. But, we need more info to find why it is failing and why `Rebuild` is happening. thanks.

**Comment by Zerodante** [comment]
Hello. i already solved it. I was uploading it with the node modules. when bluemix tried to build it it crashed because it was using the windows CLIdriver.
So i excluded the node modules with the cfignore.
