### ISSUE TITLE
Error: [IBM][CLI Driver] SQL1109N  The specified DLL "GSKit Error: 202" could not be loaded.  SQLSTATE=42724

### ISSUE THREAD

**Issue by rols2015** [ibmdb/node-ibm_db#395]

**Comment by bimalkjha** [comment]
@rols2015 Seems your system has multiple version of GSKit and existing GSKit is of older version. So, you need to apply solution written for issue #263 . If it still do not work: Update database connection string of `db2cli validate` command in script `ibm_db\installer\testODBCConnection.sh` (For windows `testODBCConnection.bat`) and run the script. Share the complete output of the script and the files generated by the script with me to assist further. Thanks.

**Comment by rols2015** [comment]
@bimalkjha yes, I had multiple versions of GSKit installed. I have added GSKit from idb_db to PATH and LIB env variables and looks like it solved the problem. Thank you

**Comment by vijayant296** [comment]
@rols2015 can you please guide me how to get and add GSKit to the env variables.
I am also getting below error while trying to use ibm_db.connect():

SQLCODE=-1109M][CLI Driver] SQL1109N  The specified DLL "GSKit Error: 202" could not be loaded.  SQLSTATE=42724

**Comment by bimalkjha** [comment]
@vijayant296 What is the Operating System on which you have installed `ibm_db`? You can find GSKit libraries in `...\node_modules\ibm_db\installer\clidriver\bin\icc64` directory. Thanks.

**Comment by linaedua** [comment]
@bimaljha I need help on a similar error. 
I have one single version of GSKit installed (8.0.55.17). 
The connection string is 
`connStr = "DATABASE=EPMUSAGE;HOSTNAME=dpywdcdba0101.sl.bluecloud.ibm.com;PORT=50005;Security=SSL;SSLServerCertificate=cert.arm;PROTOCOL=TCPIP;UID=user;PWD=password;";`
ibm_db version is 6.9.0. 
The error message I am getting is 
```
{ [Error: [IBM][CLI Driver] SQL1109N  The command was not processed because the database manager failed to load the following DLL: "".  SQLSTATE=42724
]
  error: '[node-ibm_db] SQL_ERROR',
  sqlcode: -1109,
  message:
   '[IBM][CLI Driver] SQL1109N  The command was not processed because the database manager failed to load the following DLL: "".  SQLSTATE=42724\r\n',
  state: '42724' }
```
I have found the GSKit libraries on the path you mention on your previous comment. I have pasted them into where GSKit is installed, but I still get the same error message. 
Are you able to guide me? 
Thanks.
