### ISSUE TITLE
npm ERR! ibm_db@2.2.1/@2.3.1 install: `node installer/driverInstall.js` in macOS V10.13.4 (17E199)

### ISSUE THREAD

**Issue by kathywang** [ibmdb/node-ibm_db#397]
I upgraded my laptop to macOS 10.13.4 (17E199), and now when I do npm install, I am keep getting error of :
Failed at the ibm_db@2.2.1 install script. also tried ibm_db@2.3.2 get same error.
I have upgraded the npm and node.js to both latest version still get the same error, please take a look and help resolve the issue. 
**Below are details:** 
Error message for node v6.x
![image](https://user-images.githubusercontent.com/3777308/39895571-c4b66eaa-5478-11e8-8f19-242a3980e5c3.png)

npm ERR! ibm_db@2.2.1 install: `node installer/driverInstall.js`
npm ERR! spawn sh ENOENT
npm ERR! 
npm ERR! Failed at the ibm_db@2.2.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kwang/.npm/_logs/2018-05-10T21_17_52_571Z-debug.log

Same with ibm_db@2.3.1
![image](https://user-images.githubusercontent.com/3777308/39897829-0e5b39e2-5482-11e8-8d01-e06720005da4.png)

more details:

3948 verbose stack Error: ibm_db@2.2.1 install: `node installer/driverInstall.js`
3948 verbose stack spawn sh ENOENT
3948 verbose stack     at _errnoException (util.js:1022:11)
3948 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
3948 verbose stack     at onErrorNT (internal/child_process.js:372:16)
3948 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
3948 verbose stack     at process._tickCallback (internal/process/next_tick.js:180:9)
3949 verbose pkgid ibm_db@2.2.1
3950 verbose cwd /Users/kwang/Documents/RESTWork/PCAWebApp_ubx
3951 verbose Darwin 17.5.0
3952 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
3953 verbose node v8.11.1
3954 verbose npm  v5.6.0
3955 error file sh
3956 error path sh
3957 error code ELIFECYCLE
3958 error errno ENOENT
3959 error syscall spawn sh
3960 error ibm_db@2.2.1 install: `node installer/driverInstall.js`
3960 error spawn sh ENOENT
3961 error Failed at the ibm_db@2.2.1 install script.

**Comment by bimalkjha** [comment]
@kathywang Please use node v8.11.1 and then run "npm install ibm_db@2.3.1". Please share the complete output of install command. From current pasted output, it is not clear that which line of driverInstall.js is throwing error and why?
Also, try to run "sh" command from terminal of your mac. We can see "error syscall spawn sh" just before the driverInstall.js error. driverInstall.js is using "require('child_process').exec" to fork child processes. Thanks.

**Comment by kathywang** [comment]
thanks @bimalkjha for look into the issue, sh was a path issue, even I add the default path still get error, googled the issue, get blow steps resolved the ibm_db install issue:
1. Install Command Line Tools :
xcode-select --install
2. Change the active directory:
sudo xcode-select -switch /Library/Developer/CommandLineTools
