### ISSUE TITLE
Error: Could not locate the bindings file

### ISSUE THREAD

**Issue by derekpollock** [ibmdb/node-ibm_db#400]
Hello,
I'm trying to ibm_db package on Linux based Docker container however getting the following error:

Any suggestions on how to resolve this please?

/home/src/app/node_modules/bindings/bindings.js:96
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /home/src/app/node_modules/ibm_db/build/odbc_bindings.node
 → /home/src/app/node_modules/ibm_db/build/Debug/odbc_bindings.node
 → /home/src/app/node_modules/ibm_db/build/Release/odbc_bindings.node
 → /home/src/app/node_modules/ibm_db/out/Debug/odbc_bindings.node
 → /home/src/app/node_modules/ibm_db/Debug/odbc_bindings.node
 → /home/src/app/node_modules/ibm_db/out/Release/odbc_bindings.node
 → /home/src/app/node_modules/ibm_db/Release/odbc_bindings.node
 → /home/src/app/node_modules/ibm_db/build/default/odbc_bindings.node
 → /home/src/app/node_modules/ibm_db/compiled/8.9.3/linux/x64/odbc_bindings.node
    at bindings (/home/src/app/node_modules/bindings/bindings.js:93:9)
    at Object.<anonymous> (/home/src/app/node_modules/ibm_db/lib/odbc.js:31:31)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)

The contents after npm install ibm_db is as follows. I noticed that _**build.zip**_ doesn't appear to have unzipped to create _build_ folder:

/home/src/app/node_modules/ibm_db/:
CHANGES.md
INSTALL.md
LICENSE
README.md
_config.yml
binding.gyp
build.zip
contributing
examples
installer
lib
node_modules
package.json
src
test

Thanks,
Derek

**Comment by bimalkjha** [comment]
@derekpollock Seems your installation did not went well. build.zip get unzipped only on windows. On non-windows platforms, it should get created during installation. Please paste the complete output of `npm install ibm_db` command. Thanks.

**Comment by derekpollock** [comment]
Thanks for your reply. I got a bit further as above issue appeared to be caused by failing to download linuxx64_odbc_cli.tar.gz file. Once I got that resolve the npm install completed ok.

However now getting the following error:


Error:
$ docker logs --follow 3da7093ad587
/home/src/app/node_modules/bindings/bindings.js:88
        throw e
        ^

Error: **libxml2.so.2**: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (module.js:664:18)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at bindings (/home/src/app/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/home/src/app/node_modules/ibm_db/lib/odbc.js:31:31)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/src/app/src/getAutoPolicyData.js:7:12)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)

**Comment by bimalkjha** [comment]
@derekpollock Seems xml2 library is missing from your system. Its an OS library. We install it on SUSE using `sudo zypper install libxml2-devel` command. Similar command and package you need to install on your system. Thanks.

**Comment by derekpollock** [comment]
Thanks for the help on this. Got this resolved by adding OS libraries to our Linux image.

**Comment by dmaisano** [comment]
Having a similar issue on Windows 10 (64bit) regarding the bindings located in `node_modules`.

Running a simple npm install of the package yields the following:
```
> ibm_db@2.4.0 install C:\Users\RPB6LCQ\Documents\Projects\ibm_db_test\node_modules\ibm_db
> node installer/driverInstall.js

Downloading DB2 ODBC CLI Driver from https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/ntx64_odbc_cli.zip...

{ Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1055:34)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket._finishInit (_tls_wrap.js:635:8) code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY' }
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN ibm_db_test@1.0.0 No description
npm WARN ibm_db_test@1.0.0 No repository field.

+ ibm_db@2.4.0
added 98 packages from 91 contributors and audited 171 packages in 10.318s
found 0 vulnerabilities
```

**Comment by dmaisano** [comment]
I created a simple test file to log the errors thrown by the `ibm_db` package..

`server.js`:
```javascript
const db = require('ibm_db');

console.log(db);
````

which results in the following output in the terminal:
```
C:\Users\RPB6LCQ\Documents\Projects\ibm_db_test\node_modules\bindings\bindings.js:96
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → C:\Users\RPB6LCQ\Documents\Projects\ibm_db_test\node_modules\ibm_db\build\odbc_bindings.node
 → C:\Users\RPB6LCQ\Documents\Projects\ibm_db_test\node_modules\ibm_db\build\Debug\odbc_bindings.node
 → C:\Users\RPB6LCQ\Documents\Projects\ibm_db_test\node_modules\ibm_db\build\Release\odbc_bindings.node
 → C:\Users\RPB6LCQ\Documents\Projects\ibm_db_test\node_modules\ibm_db\out\Debug\odbc_bindings.node
 → C:\Users\RPB6LCQ\Documents\Projects\ibm_db_test\node_modules\ibm_db\Debug\odbc_bindings.node
 → C:\Users\RPB6LCQ\Documents\Projects\ibm_db_test\node_modules\ibm_db\out\Release\odbc_bindings.node
 → C:\Users\RPB6LCQ\Documents\Projects\ibm_db_test\node_modules\ibm_db\Release\odbc_bindings.node
 → C:\Users\RPB6LCQ\Documents\Projects\ibm_db_test\node_modules\ibm_db\build\default\odbc_bindings.node
 → C:\Users\RPB6LCQ\Documents\Projects\ibm_db_test\node_modules\ibm_db\compiled\10.4.0\win32\x64\odbc_bindings.node
    at bindings (C:\Users\RPB6LCQ\Documents\Projects\ibm_db_test\node_modules\bindings\bindings.js:93:9)
    at Object.<anonymous> (C:\Users\RPB6LCQ\Documents\Projects\ibm_db_test\node_modules\ibm_db\lib\odbc.js:31:31)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\RPB6LCQ\Documents\Projects\ibm_db_test\server.js:1:74)
```

**Comment by bimalkjha** [comment]
@dmaisano Your issue is not related to this thread. libxml2 is not for Windows. You are getting binding error because ibm_db is not installed correctly. During installation you hit TLS error. Seems few CA certificates are missing from your system. Try to download `https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/ntx64_odbc_cli.zip` file on your system using browser and add the SSL certificate to your system. Then try to install ibm_db. Thanks.

**Comment by ParkerOu** [comment]
Same question here.
I have already download ODBC and set "clidriver" directory path to "IBM_DB_HOME" environment variable
How can I add the SSL certificate to my system? @bimalkjha

**Comment by bimalkjha** [comment]
@ParkerOu To know everything about SSL in ibm_db, just search for SSL word in [ibm_db documentation](https://github.com/ibmdb/node-ibm_db/blob/master/APIDocumentation.md).
You need to use `Security` and `SSLServerCertificate` keywords in the connection string. SSL Certificate can be copied anywhere in the system and use its pull path as the value of `SSLServerCertificate` in connection string. Thanks.

**Comment by jsalcedoa** [comment]
Hi @bimalkjha I'm having the same issue as the one from the screenshot that you commented above, the only difference is that I'm having this issue when deploying to the Kubernetes cluster using Docker image 14-stretch with node v14.19. 

I was having no issues when the Docket image 14-stretch was using node v14.18 or v14.17. Could you let me know if I have to include the CA certificates you mention that are missing and where do I need to include this certificates if the problem is not in my computer but in the cluster?

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/29698309/164499601-b1341f54-fa88-4f80-8b5a-801ef9b977ff.png">

Thanks.

**Comment by Abinaya-26** [comment]
Hi, Can I know how to resolve the same odbc binding error.. I am new to node js and I want to connect ibm db2 in windows .. So I have given npm i ibm_db and also npm i odbc.. But I'm getting the same binding error. 

Error: Could not locate the bindings file. Tried:
→ /home/src/app/node_modules/ibm_db/build/odbc_bindings.node
→ /home/src/app/node_modules/ibm_db/build/Debug/odbc_bindings.node

.. I have so deleted node modules and again installed node modules still same issue.. 
If anyone can pls help in this regard

**Comment by ParkerOu** [comment]
@Abinaya-26 
I switched to `node-jt400` package.
Maybe you could give it a try.

**Comment by bimalkjha** [comment]
@Abinaya-26 Please open a new issue with complete output of `npm install ibm_db` command. There should be some error during installation. Thanks.
