### ISSUE TITLE
Japanese garbled.

### ISSUE THREAD

**Issue by aaootan** [ibmdb/node-ibm_db#401]
Hello.

I used version 2, and Japanese garbled.
Do I need some initial setup to use it?
by the way,Version 1 has no problem.
Tanks.
environment:Windows7, Node6, Db2Warehouse(IBM Cloud)

**Comment by bimalkjha** [comment]
Latest code change has fix for this issue. You can test it using `npm install git+https://git@github.com/ibmdb/node-ibm_db.git` command on non-windows platform. Next release will have this fix.  Thanks.

**Comment by xinyi1989** [comment]
hi,
I have this problem , did you already solve this?

**Comment by bimalkjha** [comment]
@xinyi1989 Yes, it is already fixed in ibm_db@2.4.0. You can execute [test-chinese-char.js](https://github.com/ibmdb/node-ibm_db/blob/master/test/test-chinese-char.js) file to verify it. Thanks.
