### ISSUE TITLE
document fetchAll

### ISSUE THREAD

**Issue by huineng** [ibmdb/node-ibm_db#409]
fetchAllSync is documented in code part , fetchAll is not document , though it's in the examples

thanks

**Comment by huineng** [comment]
same for fetch   fetchSync is document fetch not

**Comment by rhtpandeyIN** [comment]
Sure, thanks for letting us know. We will document it.

**Comment by bimalkjha** [comment]
Documented [fetchAll](https://github.com/ibmdb/node-ibm_db/blob/master/APIDocumentation.md#fetchAllApi) and [fetch](https://github.com/ibmdb/node-ibm_db/blob/master/APIDocumentation.md#fetchApi) APIs. Thanks.
