### ISSUE TITLE
use RedHat 7.x install is error

### ISSUE THREAD

**Issue by johnsen-zhang** [ibmdb/node-ibm_db#410]
systemInfo: Linux localhost 3.10.0-693.el7.x86_64 #1 SMP Thu Jul 6 19:56:57 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux
Linux version 3.10.0-693.el7.x86_64 (mockbuild@x86-038.build.eng.bos.redhat.com) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) ) #1 SMP Thu Jul 6 19:56:57 EDT 2017

npm install ibm_db is error
error: 
downloading DB2 ODBC CLI Driver from https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz...

{ [Error: EACCES: permission denied, open '/nodeprojects/db2Test/node_modules/ibm_db/installer/linuxx64_odbc_cli.tar.gz']
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path:
   '/nodeprojects/db2Test/node_modules/ibm_db/installer/linuxx64_odbc_cli.tar.gz' }

**Comment by bimalkjha** [comment]
@JohnsenZhang0702 Seems your system is unable to download https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz file. Are you able to download it manually? Some firewall or proxy setting may be blocking the download. Please verify and update. Thanks.
