### ISSUE TITLE
How to use C++ to connect DB2?

### ISSUE THREAD

**Issue by Willdas** [ibmdb/node-ibm_db#411]
Hello,  I want to know how to use C++ to connect DB2S database under Linux system.

**Comment by bimalkjha** [comment]
@Willdas 1. Just google about "how to use C++ to connect DB2S database under Linux system". You'll get many pointers.
2. You need to install a client driver to talk to DB2 Server. Download "IBM Data Server Driver Package" from here: https://www-01.ibm.com/support/docview.wss?uid=swg21385217
3. In your C++ Program, you need to call ODBC APIs available in libdb2.so.1 library(for linux) or db2app64.dll (for Windows) that you get after installation of IBM Data Server Driver Package.
This question has nothing to do with ibm_db package which is for node.js applications and not C++ application, hence closing the issue. Thanks.
