### ISSUE TITLE
Serverless/Kubeless support

### ISSUE THREAD

**Issue by kentonbmax** [ibmdb/node-ibm_db#412]
I wanted to check and see if the lib and driver have been tested in a serverless environment?

**Comment by bimalkjha** [comment]
@kentonbmax yes, we always test ibm_db in a serverless environment that means our DB2 server is always on remote system and not in the system where we install ibm_db. If you are facing any issue with remote server, please let us know. Thanks.

**Comment by PavaniKa** [comment]
This lib is failing on both AWS Lambda & IBM Cloud functions environments, throwing initialization error. Attached are screenshots for reference.
![error_aws_lambda](https://user-images.githubusercontent.com/10548684/41743669-81a6c034-756f-11e8-9b9a-72f120782851.png)
![error_ibm_cloud_functions](https://user-images.githubusercontent.com/10548684/41743670-81b6a44a-756f-11e8-80cb-7891bd7ce4ab.png)

**Comment by bimalkjha** [comment]
@PavaniKa Which version of node.js you are using? Please use node.js version < 10.x. 
If your node version is correct, then you might have some permission issue as reported in issues 168, 343 & 382. Try to run your application with administrative privilege. I assume platforms in AWS Lambda & IBM Cloud is Linuxx64. If not, please let us know. Thanks.

**Comment by bimalkjha** [comment]
Also, it might be possible that you encountered  some error during installation of ibm_db itself in cloud, as a result runtime error. Please share the complete installation log too. Thanks.

**Comment by kentonbmax** [comment]
8.11.2. Is my node version.
