### ISSUE TITLE
Unable to install on windows x86

### ISSUE THREAD

**Issue by hyurl** [ibmdb/node-ibm_db#413]
When I tried to install this package, the process exited with message:
>>Unable to fetch driver download file. Exiting the install process.

So I tried to check the installer file `installer/driverInstall.js`, and found this code in it:
```javascript
if(platform == 'win32') {
  if(arch == 'x64') {
    installerfileURL = installerURL + 'ntx64_odbc_cli.zip';
  }
}
```
The installer only supports x64 version of windows, but in
[https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/](https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/)
, there is a `nt32_odbc_cli.zip` listed.

Hope windows x86 being supported in the next version.

**Comment by bimalkjha** [comment]
@hyurl Windows x86 is not supported by ibm_db. For 64bit-Windows we upload pre-compiled binary but there is no pre-compiled binary for 32bit windows. The nt32_odbc_cli.zip is there to be used by other open source drivers like python and php drivers.
If you still have need to have ibm_db on 32bit windows, you can clone the code from github, install visual studio compiler, modify the bindigs.gyp and driverInstall.js files and compile yourself by following the steps documented [here](https://github.com/ibmdb/node-ibm_db/blob/master/INSTALL.md#inswinbld). Thanks.
