### ISSUE TITLE
@types/ibm-db question

### ISSUE THREAD

**Issue by huineng** [ibmdb/node-ibm_db#414]
i'm trying to use the ibm_db types in my typescript project but i'm not sure if it's ok

a database.open returns a connection   db.open(connstring,(err,conn)

conn.query etc...

in you definitions you have 

```
export class Database implements Options {
    odbc: ODBC;
    queue: SimpleQueue | any[];
    fetchMode: number | null;
    connected: boolean;
    connectTimeout: number | null;
    conn?: ODBCConnection;

    constructor(options?: Options);

    open(connStr: string | ConnStr): Promise<ODBCConnection>;
    open(connStr: string | ConnStr, cb: (err: Error, conn?: ODBCConnection) => void): void;

    openSync(connStr: string | ConnStr): boolean;

    close(cb?: (err: Error, db: Database) => any): void;
    close(): Promise<void>;

    closeSync(): boolean;

    query(query: string, params: any[], cb: (err: Error, res: any[]) => void): void;
    query(query: string | {sql: string, params: any[]}, cb: (err: Error, res: any[]) => void): void;
    query(query: string | {sql: string, params: any[]}, params?: any[]): Promise<any[]>;
```

but i cannot use that as Database both contains open and query 

shouldn't it be 

Database  open 

export class Connection: ODBCConnection {
query(query: string, params: any[], cb: (err: Error, res: any[]) => void): void;
    query(query: string | {sql: string, params: any[]}, cb: (err: Error, res: any[]) => void): void;
    query(query: string | {sql: string, params: any[]}, params?: any[]): Promise<any[]>;
}

so i think you need to move all connection operations  query etc.. into a connection class

thanks

**Comment by huineng** [comment]
that's the point in your @types it returns a connection object and not a database object like you said

```
open(connStr: string | ConnStr): Promise<ODBCConnection>;
open(connStr: string | ConnStr, cb: (err: Error, conn?: ODBCConnection) => void): void;
```

so my typescript gives an error

you might need to modify it so that open returns a database object

```
open(connStr: string | ConnStr): Promise<Database>;
open(connStr: string | ConnStr, cb: (err: Error, conn?: Database) => void): void;
```

**Comment by cuzzlor** [comment]
@huineng as a side note, you might want to use the connection pool object. Here's what we use to a) open / close new connections (request scoped) and then shut down the entire connection pool (application scope).

we use a connection pool wrapper to provide openConnection (return Database), closeConnection (using Database) and close (the entire pool).

- open new connection (get a Database object) >> this doesn't have a promise version so here's our wrapper
```ts
    public async openConnection(connectionString: string): Promise<Database> {
        return new Promise<Database>((resolve, reject) => {
            const callback = (err: Error, db: Database) => {
                if (err) {
                    reject(err);
                } else {
                    resolve(db);
                }
            };
            this.pool.open(connectionString, callback.bind(this));
        });
    }
```

- close a connection (via the Database object) >>> releases connection back to the pool
```ts
await db.close();
```

- finally if required shutdown the connection pool (application scoped)
```ts
    public async close(): Promise<void> {
        return new Promise<void>(resolve => this.pool.close(resolve));
    }
```

**Comment by bimalkjha** [comment]
@huineng If you check the code [here](https://github.com/ibmdb/node-ibm_db/blob/master/lib/odbc.js#L96), ibmdb.open() is returning Database object db only. I have executed [promise-test-open-close.js](https://github.com/ibmdb/node-ibm_db/blob/master/test/promise-test-open-close.js) file with log for `db` and it shows a Database object only.
```
D:\nodework\master\ibm_db\test>node promise-test-open-close.js
db =  Database {
  odbc: ODBC {},
  queue: SimpleQueue { fifo: [], executing: false },
  fetchMode: null,
  connected: true,
  connectTimeout: null,
  systemNaming: undefined,
  codeSet: null,
  mode: null,
  conn: ODBCConnection { systemNaming: false, connectTimeout: 30, connected: tru
e } }
```
Could you please share the full test script using which I can see the incorrect type and then look for root cause? Thanks.
