### ISSUE TITLE
[IBM] [CLI Driver] SQL1336N The remote host "hostname" was not found. SQLSTATE=08001

### ISSUE THREAD

**Issue by djromasanta** [ibmdb/node-ibm_db#416]
Hi everyone, I am new to node js and using node-ibm_db to connect to DB2 and I am having trouble after deploying it to Bluemix. I am getting this error: [IBM] [CLI Driver] SQL1336N The remote host "hostname" was not found. SQLSTATE=08001, but in my local it works perfectly and I was able to connect and query to the database. I am using Cloud Foundry to deploy it. I am also using TCP/IP as my protocol. Pls help.

Thank you

**Comment by bimalkjha** [comment]
@djromasanta Since it works in your local, it might be possible that your server is not enabled to accept remote connection. From local run command `db2 get dbm cfg` and make sure SVCENAME is set to correct TCP/IP port and env variable DB2COMM=TCPIP is set. You can run below commands in sequence:
```
db2set DB2COMM=TCPIP
db2 update dbm cfg using svcename 5010
db2 terminate
db2stop
db2start
```
For SQL1336N error, please follow the user action documented [here](https://www.ibm.com/support/knowledgecenter/SSEPGG_11.1.0/com.ibm.db2.luw.messages.sql.doc/doc/msql01336n.html). You can login to the bluemix system and try to ping the host: AAAS.AU.IBM.COM. Alternatively, you can use ip address too for hostname in connection string.
Thanks.

**Comment by djromasanta** [comment]
@bimalkjha  Hi Bimal, thank you for your response. I have tried changing the hostname to an IP address. It works in my local but in bluemix it is not. I also figured that bluemix is blocked from the server. I'm also confused where can I ping the host from the Bluemix. I also don't know where to set db2 in my local. Sorry Bimal, I'm kind of new to this environment.

Here is the error:
2018-06-19T14:37:04.35+0800 [APP/PROC/WEB/0]OUT   message: '[IBM][CLI Driver] SQ
L30081N  A communication error has been detected. Communication protocol being u
sed: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the err
or was detected: "9.190.3.9".  Communication function detecting the error: "sele
ctForConnectTimeout".  Protocol specific error code(s): "115", "*", "*".  SQLSTA
TE=08001',

Thank you

**Comment by bimalkjha** [comment]
@djromasanta From local where connection is working, run below command and share the result:
```
db2cli validate -database "dbname:hostname.ibm.com:port" -user username -passwd password -connect
```
Please use all options in the command and update the connection information. Thanks.

**Comment by bimalkjha** [comment]
Also, clarify what do you mean by local - Your laptop where you install ibm_db locally before pushing to the bluemix or the aaas.au.ibm.com system where DB2 server is installed? Above db2cli command you should run on the system where DB2 server is installed. The commands that I shared in previous reply to set DB2COMM is also for aaas.au.ibm.com not for your local system. Basically, we need to make sure DB2 Server is configured properly to accept the remote connection. Thanks.

**Comment by djromasanta** [comment]
I only tested the web app in my laptop where I installed ibm_db and it's working. I just can't understand why it's not working if it's deployed in bluemix. I only have the credentials for the DB2, like the hostname, port, username and password. The problem is I don't have any control for the server.  Do you think there's another way to make this work? Thanks Bimal

**Comment by bimalkjha** [comment]
@djromasanta Thanks for clarifying it. So, when ibm_db is able to connect to DB2 on remote host from your TP, means DB2 server is configured properly to accept the remote connection. No issues at server side.
It means, bluemix is unable to reach your DB2 server system. May be some kind of firewall is blocking it. You should open issue with bluemix team and tell then why bluemix is unable to reach aaas.au.ibm.com? Thanks.

**Comment by bimalkjha** [comment]
Seems you are hitting SQL1336N error. Please follow the user action documented here: https://www.ibm.com/support/knowledgecenter/SSEPGG_11.1.0/com.ibm.db2.luw.messages.sql.doc/doc/msql01336n.html

**Comment by djromasanta** [comment]
Thank you so much Bimal. I might contact Bluemix support regarding this issue.
