### ISSUE TITLE
Question : Data Type out of Range/Array input for 

### ISSUE THREAD

**Issue by amangrover1** [ibmdb/node-ibm_db#420]
Query - Select cm_company,cm_compid from comp_master where cm_company in (?)

Binding Value - [['ARS_Q_AR-X_QB-V_P40',  'ARS_Q_AR-X_QB-X_P40'],{"Data": "string"}]

Error:
[object Object]----Select cm_company,cm_compid from comp_master where cm_company in (?)--ARS_Q_AR-X_QB-V_P40,ARS_Q_AR-X_QB-X_P40,[object Object]
2018-06-22T16:40:24.242Z - error: Execution Error Error: [IBM][CLI Driver] CLI0123E  SQL data type out of range. SQLSTATE=HY004

look's like syntax error, can someone elaborate how to solve this.

**Comment by bimalkjha** [comment]
@amangrover1 Please go through [this](https://github.com/ibmdb/node-ibm_db#bindParameters) documentation in details to understand how to pass bind parameters. In your sql, you have only one parameter marker, but Binding Value is an array of 2 items. Binding Value should also have only 1 item as there is only 1 parameter marker in sql.
Use below binding value in your program, it should work:
```
[{"Data": "'ARS_Q_AR-X_QB-V_P40', 'ARS_Q_AR-X_QB-X_P40'"}]
```
Thanks.

**Comment by amangrover1** [comment]
@bimalkjha , thanks for quick response. I tried your suggestion and also documentation but looks like I am missing something here. I am using ibm_db - 2.1.0

my complete method looks like
runPrepareQuery: function(schema, sql, binding, callback) {

        let data;
        let connStr = this.connectionStringBuilder(schema);

        console.log(schema +"--" + "--" + sql + "--" + binding);
        binding = ["'ARS_Q_AR-X_QB-V_P40','ARS_Q_AR-X_QB-X_P40'"]; -- overwriting for test

        return ibmdb.open(connStr, function(err, conn) {
            if (err) return logger.log("info", err);
            else {
                conn.prepare(sql, function(err, stmt) {
                    if (err) {
                        logger.log("error", "Connection error %s", err);
                        conn.close(function(err) {});
                    }
                    return stmt.execute(binding, function(err, result) {
                        if (err) {
                            logger.log("error", "Execution Error %s", err);
                            conn.close(function(err) {});
                            return err;
                        } else {
                            data = result.fetchAllSync();
                            result.closeSync();
                            stmt.closeSync();
                            conn.close(function(err) {});
                            return callback(null, data);
                        }
                    });
                });

            }
        });
    },

here i am passing binding parameter as described by you from other function

I am getting this output
Started
''ARS_Q_AR-X_QB-V_P40','ARS_Q_AR-X_QB-X_P40''
[object Object]----Select cm_company,cm_compid from comp_master where cm_company in (?)--'ARS_Q_AR-X_QB-V_P40','ARS_Q_AR-X_QB-X_P40'
[] -- it is blank here

but data do exist in DB
for e.g, when query for one parameter - ['ARS_Q_AR-X_QB-V_P40']
[ { cm_company: 'ARS_Q_AR-X_QB-V_P40', cm_compid: 1187 } ]

Can you please help here?

**Comment by bimalkjha** [comment]
@amangrover1 Just realized the issue with your test program. Actually, in your sql, you have used single parameter marker, but you are trying to pass two values in Param object. One parameter marker can have only one value. So, if you want to compare two values, you need to use two parameter markers in sql. Update your code as below. It should work.
```
SQL : Select cm_company,cm_compid from comp_master where cm_company in (?, ?)
Binding Value: ['ARS_Q_AR-X_QB-V_P40', 'ARS_Q_AR-X_QB-X_P40']
```
Thanks.

**Comment by bimalkjha** [comment]
Sorry, that is not possible. In such case, you should form static SQL every time using the variable values and execute it using query() API. A single parameter marker can accept value for a single field only. Thanks.

**Comment by lucaskuperman** [comment]
@bimalkjha is your last statement in this post still true as of today? Can I vote for such feature be implemented? It is a very common use case to have `IN (?)` statements
