### ISSUE TITLE
Problem with diacritics on v.2.4.0

### ISSUE THREAD

**Issue by ljerka** [ibmdb/node-ibm_db#423]
Hi,
recently I upgraded from v.2.2.1 to v.2.4.0 and now I have a problem with diacritics. 
Here is a part of an output from stored procedure on v.2.4.0:
```
{ 
      ID: '1',
      NAME: 'PRANJI�',
      ADDRESS: 'ZAGREBA�KA',
      NAME_OLD: '�OLA',
}
```

and the same output on v.2.2.1:
```
{ 
      ID: '1',
      NAME: 'PRANJIĆ',
      ADDRESS: 'ZAGREBAČKA',
      NAME_OLD: 'ŠOLA',
}
```

Is there any fix for this? Thank you.

**Comment by bimalkjha** [comment]
@ljerka Please share the SP definition and sample test program to repro the issue. Thanks.

**Comment by ljerka** [comment]
I can't, but it is very easy to reproduce - it happens on any query, not just on stored procedure.
Try inserting diacritics into any table and read inserted record:

`insert into ANYTABLE (DIACRITICS) values ('čćžšđČĆŽŠĐ');`
`select * from ANYTABLE;`

**Comment by bimalkjha** [comment]
@ljerka Test file [test-basic-test.js](https://github.com/ibmdb/node-ibm_db/blob/master/test/test-basic-test.js) uses diacritics in insert statement and able to select the correct value. Find 'für' work in this test file. Could you try to execute it and check. If it works find, then put your characters and verify. If it fails, please share modified test file. Thanks.

**Comment by bimalkjha** [comment]
I replaced 'für' with 'ZAGREBAČKA' in test-basic-test.js file and seems working fine. Thanks.

**Comment by ljerka** [comment]
I can't execute test-basic-test.js because I don't have priviledges to create table, but I inserted 'für' (via Data Studio) into existing table, and then I executed select statement via nodemon. It is still the same:

v.2.2.1:
```
[nodemon] starting `node server-sp02.js`
[ { DIACRITICS: 'für' } ]
```

v.2.4.0:
```
[nodemon] clean exit - waiting for changes before restart
[nodemon] restarting due to changes...
[nodemon] starting `node server-sp02.js`
[ { DIACRITICS: 'f�r' } ]
```

I am working on Windows7, npm version 5.6.0, node version 8.9.3

**Comment by bimalkjha** [comment]
@ljerka If you are inserting using datastudio and selecting using node.js, then it might be possible that code page of two applications are different. I just executed following small script and it works fine. 
```
var ibmdb = require('ibm_db');
var cn = "database=sample;hostname=waldev.com;port=50000;uid=db2user;pwd=secret";

ibmdb.open(cn, function(err, conn) { 
  if(err) console.log(err);
  conn.querySync("create table mytab1 (c1 int, c2 varchar(50))");
  conn.querySync("insert into mytab1 values ( 9999, 'žšs6yhŽŠs')");
  var data = conn.querySync("select * from mytab1 where c1=9999");
  console.log("Selected data = ", data);
});

C:\nodework\master>node diacritics.js
Selected data =  [ { C1: 9999, C2: 'žšs6yhŽŠs' } ]

C:\nodework\master>node -v
v8.11.1
```

If you can not create a table, you can use the existing table. In above test program, just remove the line with `create table` statement and replace `mytab1` with existing table name. Thanks.

**Comment by ljerka** [comment]
@bimalkjha Data studio is IBM client for db2. It shouldn't be a problem with coding mismatch. I am using ibm_db node package since v.1.0.0, and up until now with v.2.4.0 I never had any problem with diacritics, weather I insert data using Data studio, ibm_db package or something else.

I tried inserting 'für' with ibm_db, and then read it, and it was read ok. Although when reading with any other application/client it wasn't good. With diacritics it went a bit different, but still wrong:

```
ibmdb.open(driver+hostname+port+db+user+psw+protocol, function (err,conn) { 
    if (err) return console.log(err);
    let query = "update test.anytable set diacritics='čćžšđČĆŽŠĐ' where id=1";
    conn.query(query, [], function (err, data) {
        if (err) console.log(err);
        console.log(data);
        conn.close(function () {});
    });
});
```
```
ibmdb.open(driver+hostname+port+db+user+psw+protocol, function (err,conn) { 
    if (err) return console.log(err);
    let query = "select diacritics from test.anytable where id = 1";
    conn.query(query, [], function (err, data) {
        if (err) console.log(err);
        console.log(data);
        conn.close(function () {});
    });
});
```

```
[nodemon] starting `node server-sp02.js`
[ { DIACRITICS: 'č�\u001ažš�\u001aČ�\u001aŽŠĐ' } ]
```

In Data studio that data was read like this:
`ÄŤÄĹľĹˇÄÄŚÄĹ˝Ĺ Ä`

With v.2.2.1 it was all good - in Data studio and in nodemon.

What I would like to point out is that with v.2.4.0 I obviously get different results depending on with what I insert into table. If data is inserted with Data studio, java application or some other way, and then read it with ibm_db, I get diacritics wrong. Even if I insert with ibm_db, I get some diacritics wrong (although it is a bit better). That behaviour is deffinitely not good.
With versions 1.0.0 - v.2.2.1 I never had any problem with diacritics. It doesn't matter how did the data went into a table. I could insert diacritics with Data studio, java application, ibm_db package or any other way and I would always get the diacritics right. And I would always get them right no matter with what I read them.

**Comment by bimalkjha** [comment]
Ok. Looking into details. thanks.

**Comment by ljerka** [comment]
Hi, is there any progress regarding this issue? Thanks.

**Comment by bimalkjha** [comment]
@ljerka Please set system environment variable "DB2CODEPAGE=1208" and then restart the Data Studio to verify and share result. Thanks.

**Comment by bimalkjha** [comment]
I hope above post has fixed your issue so closing it. You can also try ibm_db@2.4.1. Thanks.

**Comment by ljerka** [comment]
Please reopen, I didn't have time to test this (and also can't understand how changing this locally on my computer would help) but I will as soon as I find the time. I have to test it on more than one computer and have to see weather other platforms and applications can read it well after changing (node applications on older versions, java applications, domino applications and so on).

**Comment by ljerka** [comment]
Hi, sorry for the late response. I have already set the env var "DB2CODEPAGE=1208" and it seems to be working (node script+data studio). However, I didn't find time to test it thoroughly on other platforms.
I am closing this issue and will open a new one if I stumble upon another problem regarding this problem.

Thank you very much for your help.
