### ISSUE TITLE
the japanese garbled at version 2.4

### ISSUE THREAD

**Issue by xinyi1989** [ibmdb/node-ibm_db#427]
i also have this problem, can not get japanese character at the version 2.4.0.

![japanese](https://user-images.githubusercontent.com/22472112/42675920-94593f00-86a8-11e8-97b0-df286851ffab.png)
![0](https://user-images.githubusercontent.com/22472112/42675937-a48473f4-86a8-11e8-9444-09109f4c0e6d.png)

**Comment by lx171717** [comment]
I meet the same issue 。 can you solve it ？

**Comment by bimalkjha** [comment]
@lx171717 Could you execute the test file [test-chinese-char.js](https://github.com/ibmdb/node-ibm_db/blob/master/test/test-chinese-char.js) and see it is working for you or not? If working, modify test file with Japanese chars and run it. Thanks.

**Comment by lx171717** [comment]
I try it  by your supply the method, but can not solve it.

**Comment by bimalkjha** [comment]
@lx171717 Please share the test program to reproduce the issue. Also, clarify the test program test-chinese-char.js gives correct result or not? Thanks.

**Comment by lx171717** [comment]
test-chinese-char.js  executed, but give not correct result.

**Comment by lx171717** [comment]
@aaootan  Can you tell us  where is  environment variables? it is environment variables of  the windows system ?

**Comment by rhtpandeyIN** [comment]
Hi @lx171717 ,

Please let us know if the issue still persist? 

Thanks.
