### ISSUE TITLE
SQL error 08001  error code 115

### ISSUE THREAD

**Issue by svallepu** [ibmdb/node-ibm_db#429]
Hi,
We are not able to connect to DB2 from our node 8 app .Pls find the error below.

2018-07-12 14:01:26.266 -- LEVEL=ERROR -- EVTC=CARD CODES -- [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "".  Communication function detecting the error: "selectForRecvTimeout".  Protocol specific error code(s): "115", "*", "*".  SQLSTATE=08001

Thanks,
Sudhakar Vallepu.

**Comment by bimalkjha** [comment]
@svallepu This error says server is not responding for the connection request. It seems server is not configured properly to accept remote connection. To verify that, please update connection information in below command and run on the server. 
```
db2cli validate -database "sample:hotel.torolab.ibm.com:21169" -connect -user newton -passwd serverpass
```
If above command fails, please contact the sysadmin to correct the server configuration. Thanks.

**Comment by svallepu** [comment]
when tried above cli command . its just hanging on client side  and DB server side we are seeing  below.
FUNCTION: DB2 UDB, common communication, sqlcctcplogIPAddress, probe:50
MESSAGE : DIA3220W Client sent data from IP address = "", port =
          "45666".

**Comment by svallepu** [comment]
Hi ,
I cann't run the db2cli on db but i ran its from our lower environment its working . Its not working from  our QA servers.

===============================================================================
Client information for the current copy:
===============================================================================

Client Package Type       : IBM Data Server Driver For ODBC and CLI
Client Version (level/bit): DB2 v10.5.0.5 (special_33523/64-bit)
Client Platform           : Linux/X8664
Install/Instance Path     : /opt/app-root/src/node_modules/ibm_db/installer/clidriver
DB2DSDRIVER_CFG_PATH value: <not-set>
db2dsdriver.cfg Path      : /opt/app-root/src/node_modules/ibm_db/installer/clidriver/cfg/db2dsdriver.cfg
DB2CLIINIPATH value       : <not-set>
db2cli.ini Path           : /opt/app-root/src/node_modules/ibm_db/installer/clidriver/cfg/db2cli.ini
db2diag.log Path          : /opt/app-root/src/node_modules/ibm_db/installer/clidriver/db2dump/db2diag.log

===============================================================================
db2dsdriver.cfg schema validation for the entire file:
===============================================================================

Note: The validation utility could not find the configuration file
db2dsdriver.cfg. The file is searched at
"/opt/app-root/src/node_modules/ibm_db/installer/clidriver/cfg/db2dsdriver.cfg".

**Comment by bimalkjha** [comment]
@svallepu In that case seems some issue with IP configuration of QA server. Could you try using the IP address in connection string instead of hostname? Thanks.
