### ISSUE TITLE
Retrieving data from double byte CLOB column

### ISSUE THREAD

**Issue by vpham16** [ibmdb/node-ibm_db#431]
Hi,
Thanks for quick response to the js promise question. When I try to query for a double byte clob column (i.e. DBCLOB data type), I get empty string back, while I know for sure the column has data. Do you know why? To verify it has data, I run the same select query from the cmd line and it returns the data for the column, but not from my node js app. 
Going further, I find out that If I have double bytes characters (like Chinese text) in this column, then the query from node js does return the data but it's all garbed up, totally unreadable. Again running the same query from cmd line returns the correct Chinese data. On the other hand, if the column has just single byte characters like English then it returns empty string. any idea why?

**Comment by PriyankaManoharan04** [comment]
@vpham16 Pull the code from node-ibm_db and verify that latest changes has fixed this issue.Thanks.
