### ISSUE TITLE
Does IBM_DB work for node 10 yet - Support Node v10.x #387

### ISSUE THREAD

**Issue by kpowers626** [ibmdb/node-ibm_db#432]
I just downloaded for windows yesterday but it will not install correctly. I have been trying everything on the sites and nothing seems to work.
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
  odbc.cpp
  odbc_connection.cpp
  odbc_statement.cpp
  odbc_result.cpp
c:\users\karen powers\appdata\roaming\npm\node_modules\ibm_db\src\odbc.h(27): fa
tal error C1083: Cannot open include file: 'sqlcli1.h': No such file or director
y (compiling source file ..\src\odbc_statement.cpp) [C:\Users\Karen Powers\AppDa
ta\Roaming\npm\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\users\karen powers\appdata\roaming\npm\node_modules\ibm_db\src\odbc.h(27): fa
tal error C1083: Cannot open include file: 'sqlcli1.h': No such file or director
y (compiling source file ..\src\odbc_connection.cpp) [C:\Users\Karen Powers\AppD
ata\Roaming\npm\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\users\karen powers\appdata\roaming\npm\node_modules\ibm_db\src\odbc.h(27): fa
tal error C1083: Cannot open include file: 'sqlcli1.h': No such file or director
y (compiling source file ..\src\odbc.cpp) [C:\Users\Karen Powers\AppData\Roaming
\npm\node_modules\ibm_db\build\odbc_bindings.vcxproj]
  win_delay_load_hook.cc
c:\users\karen powers\appdata\roaming\npm\node_modules\ibm_db\src\odbc.h(27): fa
tal error C1083: Cannot open include file: 'sqlcli1.h': No such file or director
y (compiling source file ..\src\odbc_result.cpp) [C:\Users\Karen Powers\AppData\
Roaming\npm\node_modules\ibm_db\build\odbc_bindings.vcxproj]

{ Error: Command failed: node-gyp configure build  --IS_DOWNLOADED=false --IBM_D
B_HOME=$IBM_DB_HOME
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (E:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:237:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "E:\\Program Files\\nodejs\\node.exe" "E:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "bui
ld" "--IS_DOWNLOADED=false" "--IBM_DB_HOME=$IBM_DB_HOME"
gyp ERR! cwd C:\Users\Karen Powers\AppData\Roaming\npm\node_modules\ibm_db
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

    at ChildProcess.exithandler (child_process.js:291:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
  killed: false,
  code: 1,

DB2 is installed on this server and that include directory and file exist. I have tried setting IBM_DB_HOME but nothing works

**Comment by kpowers626** [comment]
Update: I copied the clidrive folder from the ibm_db install attempt to a different folder and set IBM_DB_HOME to point to it. Now I get different errors:
..\src\odbc_statement.cpp(229): error C2661: 'v8::Function::NewInstance': no ove
rloaded function takes 2 arguments [C:\Users\Karen Powers\AppData\Roaming\npm\no
de_modules\ibm_db\build\odbc_bindings.vcxproj]
..\src\odbc_statement.cpp(241): warning C4996: 'Nan::Callback::Call': was declar
ed deprecated [C:\Users\Karen Powers\AppData\Roaming\npm\node_modules\ibm_db\bui
ld\odbc_bindings.vcxproj]
  C:\Users\Karen Powers\AppData\Roaming\npm\node_modules\ibm_db\node_modules\nan
\nan.h(1618): note: see declaration of 'Nan::Callback::Call'
..\src\odbc_statement.cpp(303): error C2661: 'v8::Function::NewInstance': no ove
rloaded function takes 2 arguments [C:\Users\Karen Powers\AppData\Roaming\npm\no
de_modules\ibm_db\build\odbc_bindings.vcxproj]
..\src\odbc_statement.cpp(406): warning C4996: 'Nan::Callback::Call': was declar
ed deprecated [C:\Users\Karen Powers\AppData\Roaming\npm\node_modules\ibm_db\bui
ld\odbc_bindings.vcxproj]
  C:\Users\Karen Powers\AppData\Roaming\npm\node_modules\ibm_db\node_modules\nan
\nan.h(1596): note: see declaration of 'Nan::Callback::Call'
..\src\odbc_statement.cpp(558): error C2661: 'v8::Function::NewInstance': no ove
rloaded function takes 2 arguments [C:\Users\Karen Powers\AppData\Roaming\npm\no
de_modules\ibm_db\build\odbc_bindings.vcxproj]
..\src\odbc_statement.cpp(558): error C2660: 'Nan::Persistent<v8::Object,v8::Non
CopyablePersistentTraits<T>>::Reset': function does not take 1 arguments [C:\Use
rs\Karen Powers\AppData\Roaming\npm\node_modules\ibm_db\build\odbc_bindings.vcxp
roj]
          with
          [
              T=v8::Object
          ]
..\src\odbc_statement.cpp(565): warning C4996: 'Nan::Callback::Call': was declar
ed deprecated [C:\Users\Karen Powers\AppData\Roaming\npm\node_modules\ibm_db\bui
ld\odbc_bindings.vcxproj]
  C:\Users\Karen Powers\AppData\Roaming\npm\node_modules\ibm_db\node_modules\nan
\nan.h(1618): note: see declaration of 'Nan::Callback::Call'
..\src\odbc_statement.cpp(625): error C2661: 'v8::Function::NewInstance': no ove
rloaded function takes 2 arguments [C:\Users\Karen Powers\AppData\Roaming\npm\no
de_modules\ibm_db\build\odbc_bindings.vcxproj]
..\src\odbc_statement.cpp(625): error C2660: 'Nan::Persistent<v8::Object,v8::Non
CopyablePersistentTraits<T>>::Reset': function does not take 1 arguments [C:\Use
rs\Karen Powers\AppData\Roaming\npm\node_modules\ibm_db\build\odbc_bindings.vcxp
roj]
          with
          [
              T=v8::Object
          ]
..\src\odbc_result.cpp(191): error C2661: 'v8::Value::ToInt32': no overloaded fu
nction takes 0 arguments [C:\Users\Karen Powers\AppData\Roaming\npm\node_modules
\ibm_db\build\odbc_bindings.vcxproj]
..\src\odbc_result.cpp(191): error C2227: left of '->Value' must point to class/
struct/union/generic type..\src\odbc_connection.cpp(318): warning C4996: 'Nan::C
allback::Call': was declared deprecated [C:\Users\Karen Powers\AppData\Roaming\n
pm\node_modules\ibm_db\build\odbc_bindings.vcxproj]

etc for pages and pages. Ends with

  C:\Users\Karen Powers\AppData\Roaming\npm\node_modules\ibm_db\node_modules\nan
\nan.h(1618): note: see declaration of 'Nan::Callback::Call'

{ Error: Command failed: node-gyp configure build  --IS_DOWNLOADED=false --IBM_D
B_HOME=$IBM_DB_HOME
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (E:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:237:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "E:\\Program Files\\nodejs\\node.exe" "E:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "bui
ld" "--IS_DOWNLOADED=false" "--IBM_DB_HOME=$IBM_DB_HOME"
gyp ERR! cwd C:\Users\Karen Powers\AppData\Roaming\npm\node_modules\ibm_db
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

    at ChildProcess.exithandler (child_process.js:291:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   'node-gyp configure build  --IS_DOWNLOADED=false --IBM_DB_HOME=$IBM_DB_HOME'
}

node-gyp build process failed!

Proceeding with Pre-compiled Binary Installation.


===================================
node-ibm_db installed successfully!
===================================

**Comment by kpowers626** [comment]
starting the service gives:
E:\coding\DataStage>node app
E:\coding\DataStage\node_modules\bindings\bindings.js:88
        throw e
        ^

Error: The specified procedure could not be found.
\\?\E:\coding\DataStage\node_modules\ibm_db\build\Release\odbc_bindings.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:731:18)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at bindings (E:\coding\DataStage\node_modules\bindings\bindings.js:81:44)
    at Object.<anonymous> (E:\coding\DataStage\node_modules\ibm_db\lib\odbc.js:1
8:31)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)

E:\coding\DataStage>

**Comment by kpowers626** [comment]
I tried node 10.7, same error

**Comment by dmaisano** [comment]
Installing `ibm_db` on my machine with Node v10.4.0 spits out the same errors, will try again on my unix machine with Node versions 8 & 9 to see if this might be a problem with v10+

**Comment by dmaisano** [comment]
@kpowers626 I went ahead and installed node v9.11.1 using [nvm](https://github.com/coreybutler/nvm-windows). Doing so I was able to download the driver without any issues. I would suggest using nvm if you want to have flexibility with managing your node versions on the fly, if not uninstall node v10 and opt for either the [lts](https://nodejs.org/en/download/) or [v9.11.1 (stable)](https://nodejs.org/en/blog/release/v9.11.1/).

Hope it helps 👍

**Comment by bimalkjha** [comment]
@kpowers626 Please use node.js v < 10.x . ibm_db do not works with node.js v10.x as of now. 
If you really need to work with node 10.x, then you can install ibm_db using below command:
```
npm install git+https://git@github.com/rhtpandeyIN/node-ibm_db.git
```
Thanks.
