### ISSUE TITLE
Question: DB2 on Cloud HA

### ISSUE THREAD

**Issue by Danwakeem** [ibmdb/node-ibm_db#433]
I ran into an interesting issue using this package and thought I would ask a question that you guys may know the answer to.

I had spun up a DB2 on Cloud instance on Bluemix and checked the HA option. When I tried integrating the new HA instance with my existing code I was running into a `Segmentation fault: 11` error after opening and closing a few different connections.

After doing some digging I realized my existing code was using the default `dsn` and if I switched to using the HA instances `ssldsn` then my code would work without giving me the seg fault.

Do you guys know why I needed to switch to the `ssldsn` string? 

I think I am better off using it but I was just curious why the normal `dsn` works on a non-HA instance but doesn't work on an HA instance? 

[Here is a gist](https://gist.github.com/Danwakeem/cc56ee0c298c72902313a103bf1a3a79) that will trigger a seg fault when using a normal `dsn` and work as expected when using an `ssldsn`

**Comment by bimalkjha** [comment]
@Danwakeem You should check it with bluemix team. Actually for few services, IBM Cloud enables only ssl port and disables tcp port. That should be the reason, your normal tcpip connection fails. Thanks.

**Comment by Danwakeem** [comment]
Ahh Okay, that must be what it is. I will shoot a message to the IBM Cloud team. Thank you for the response @bimalkjha :)
