### ISSUE TITLE
data now return null instead of []

### ISSUE THREAD

**Issue by huineng** [ibmdb/node-ibm_db#440]
With you latest commit https://github.com/ibmdb/node-ibm_db/commit/d9209d1f1101bc112a1e7aeb47d81a4c05c1292a  running a query that is supposed to return an empty array (eg  1 = 0) now returns null instead of []

Is this a breaking change or an error on your side ?

ps i use it promises way

```
conn
                    .query(sql)
                    .then((data: any) => {
                        console.info(data)  =>  now returns null instead of []
```

**Comment by bimalkjha** [comment]
@huineng May be a bug. Please share some simple repro. Thanks.

**Comment by bimalkjha** [comment]
@huineng Latest push should restore the old behavior. Thanks.
