### ISSUE TITLE
Best approach for connection Pooling

### ISSUE THREAD

**Issue by asoj1987** [ibmdb/node-ibm_db#442]
Could you please check the below code and advise/modify how to optimize it for connection pooling. 
I have an app that need to make 20 transactions (Inquiry/update) per sec with DB2. 
The pool init part was kept outside of 'callDB2' function because of the below reasons.
1. To have some connections initiated during the start of server itself. 
2. When kept inside the CallDB2 function we could see Pool is imitated every time and pool size is increasing with each request.

Also if we do Pool.close(), Is it closing all the connections in the Pool ?
Node version we are using is 8.9.4
****************************************************************************************
const ibmdb = require("ibm_db");
const db2config = require("../config/db2Config.js");
const connString = db2config.db2SPConfig.dB2ConnectionString;
ibmdb.debug(true);

let Pool = require("ibm_db").Pool,
    pool = new Pool(),
    cString = connString;

let ret = pool.init(4, cString);
if (ret != true) {
  return false;
}
exports.callDB2 =async (query,SPRequest)=>{
  try{
    pool.open(cString, function (err, db) {
      if (err) {
        return err;
      } 
      else {
        db.query(query, SPRequest, function (err, data) {
          if (err) {
            console.log("Error while calling the Stored Proc");
            console.log(err);
            pool.close(function () {
              console.log("all connections in the pool are closed");
            })
            return err;
          } else {
            console.log("DB2 Stored Proc call successful");
            pool.close(function () {
              console.log("all connections in the pool are closed");
            });
            clg
            return data;
          }
        });
        
      }
    });    
  }catch (error) {
    throw error;
  }
};
********************************************************************************************

**Comment by bimalkjha** [comment]
@asoj1987 pool.close() should be used when application terminates. Better do not use it at all. 
In your code, use db.close() instead of pool.close(). db.close() will transfer the connection to pool so that another pool.open can use it.
You can modify above program as below to perform better:
```
let ret = pool.init(20, cString);
pool.setMaxPoolSize(50);
....
db.close(function () {
```
Thanks.
