### ISSUE TITLE
Result of Select STATEMENT is under 100 rows

### ISSUE THREAD

**Issue by kobecow** [ibmdb/node-ibm_db#449]
I use ibm_db packages for Db2Warehouse. 

`ibmdb.open("DATABASE=XXXDB;HOSTNAME=dashdb-entry-XX-XXl.bluemix.net;UID=XXX;PWD=XXXXX;PORT=50000;PROTOCOL=TCPIP", function (err,conn) {
      if (err) return console.log(err);

      conn.query("select count (*) FROM SYSCAT.TABLES", function (err, data) {
        if (err) console.log(err);
        else {
          console.log(data);
          conn.close(function () {
            console.log('done');
          });
        });
      });`

result is  { '1': '659' }
it means the number of rows is 659.

Then I use this query(select * FROM SYSCAT.TABLES) .

result is 
 [ { TABSCHEMA: 'SYSIBM  ',
    TABNAME: 'SYSCOLUMNS',
    OWNER: 'SYSIBM  ',
    OWNERTYPE: 'S',
    TYPE: 'T',
    STATUS: 'N'
...
...
...
... 559 more items ]

Why I got limitation of the max number of result rows?
I tired  (select * FROM SYSCAT.TABLES FETCH FIRST 200 ROW ONLY).
But Result is same.

I'm very newbie. So I don't know whether it caused ibm_db or not.

any help is happy for me.

**Comment by kobecow** [comment]
Our environment is 
Node.js v8.11.4

**Comment by bimalkjha** [comment]
@kobecow If you print the result on screen, it is printing 100 rows and telling result have 559 more rows but it do not print all the rows. It is the property of Node.js language not ibm_db. If you access the data from result using program, you can get all 659 rows. You can have a for loop on `result` to select one row at a time from result and print. This way you can print all the data. I mean to say is data is there and ibm_db is returning all 659 rows but it the Node.js which prints limited no of rows. You need to code in better way to see all if you want. Thanks.
