### ISSUE TITLE
npm install failing on mac osx yosemite

### ISSUE THREAD

**Issue by manugeorge** [ibmdb/node-ibm_db#45]
npm install is failing as shown below

mpro:~ saboji$ npm install ibm_db
-
> ibm_db@0.0.12 install /Users/saboji/node_modules/ibm_db
> node installer/driverInstall.js

Downloading DB2 ODBC CLI Driver from http://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/macos64_odbc_cli.tar.gz...
Download and extraction of DB2 ODBC CLI Driver completed successfully ...
  CXX(target) Release/obj.target/odbc_bindings/src/odbc.o

{ [Error: Command failed: /bin/sh -c node-gyp configure build --IBM_DB_HOME=$IBM_DB_HOME --IBM_DB_HOME_WIN=%IBM_DB_HOME% --IS_DOWNLOADED=true
In file included from ../src/odbc.cpp:25:
../src/odbc.h:76:85: error: unknown type name 'NanCallback'
    static Handle<Value> CallbackSQLError(SQLSMALLINT handleType, SQLHANDLE handle, NanCallback* cb);
                                                                                    ^
../src/odbc.h:77:101: error: unknown type name 'NanCallback'
    static Handle<Value> CallbackSQLError (SQLSMALLINT handleType, SQLHANDLE handle, char* message, NanCallback* cb);
                                                                                                    ^
../src/odbc.h:112:3: error: unknown type name 'NanCallback'
  NanCallback* cb;
  ^
In file included from ../src/odbc.cpp:26:
../src/odbc_connection.h:95:7: error: unknown type name 'NanCallback'
      NanCallback* callback;
      ^
../src/odbc_connection.h:113:3: error: unknown type name 'NanCallback'
  NanCallback* cb;
  ^
../src/odbc_connection.h:120:3: error: unknown type name 'NanCallback'
  NanCallback* cb;
  ^
../src/odbc_connection.h:143:3: error: unknown type name 'NanCallback'
  NanCallback* cb;
  ^
../src/odbc_connection.h:151:3: error: unknown type name 'NanCallback'
  NanCallback* cb;
  ^
In file included from ../src/odbc.cpp:27:
../src/odbc_result.h:66:7: error: unknown type name 'NanCallback'
      NanCallback* cb;
      ^
In file included from ../src/odbc.cpp:28:
../src/odbc_statement.h:73:7: error: unknown type name 'NanCallback'
      NanCallback* callback;
      ^
../src/odbc_statement.h:95:3: error: unknown type name 'NanCallback'
  NanCallback* cb;
  ^
../src/odbc_statement.h:103:3: error: unknown type name 'NanCallback'
  NanCallback* cb;
  ^
../src/odbc_statement.h:109:3: error: unknown type name 'NanCallback'
  NanCallback* cb;
  ^
../src/odbc_statement.h:117:3: error: unknown type name 'NanCallback'
  NanCallback* cb;
  ^
../src/odbc.cpp:48:3: error: use of undeclared identifier 'NanScope'
  NanScope();
  ^
../src/odbc.cpp:50:50: error: use of undeclared identifier 'NanNew'
  Local<FunctionTemplate> constructor_template = NanNew<FunctionTemplate>(New);
                                                 ^
../src/odbc.cpp:50:57: error: 'FunctionTemplate' does not refer to a value
  Local<FunctionTemplate> constructor_template = NanNew<FunctionTemplate>(New);
                                                        ^
/Users/saboji/.node-gyp/0.12.7/deps/v8/include/v8.h:3452:17: note: declared here
class V8_EXPORT FunctionTemplate : public Template {
                ^
../src/odbc.cpp:53:38: error: use of undeclared identifier 'NanNew'
  constructor_template->SetClassName(NanNew("ODBC"));
                                     ^
../src/odbc.cpp:66:29: error: use of undeclared identifier 'NanNew'
  constructor_template->Set(NanNew<String>("SQL_CLOSE"), NanNew<Number>(SQL_CLOSE), constant_attributes);
                            ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/odbc_bindings/src/odbc.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build" "--IBM_DB_HOME=/Users/saboji/node_modules/ibm_db/installer/clidriver" "--IBM_DB_HOME_WIN=%IBM_DB_HOME%" "--IS_DOWNLOADED=true"
gyp ERR! cwd /Users/saboji/node_modules/ibm_db
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/bin/sh -c node-gyp configure build --IBM_DB_HOME=$IBM_DB_HOME --IBM_DB_HOME_WIN=%IBM_DB_HOME% --IS_DOWNLOADED=true' }
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "ibm_db"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! ibm_db@0.0.12 install: `node installer/driverInstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ibm_db@0.0.12 install script 'node installer/driverInstall.js'.
npm ERR! This is most likely a problem with the ibm_db package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node installer/driverInstall.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls ibm_db
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/saboji/npm-debug.log

**Comment by manugeorge** [comment]
https://www.dropbox.com/s/5xuqb2o08e32ft6/npm-debug.log?dl=1

**Comment by bimalkjha** [comment]
This issue is because latest nan release 2.0.0 has updated header files and removed few functions from previous release. We'll fix this issue soon as a new release. As a workaround, you can use this command to install ibm_db: npm install git+https://git@github.com/ibmdb/node-ibm_db.git

**Comment by mhixon** [comment]
This has not been fixed.

**Comment by bimalkjha** [comment]
@mhixon Please run "npm install ibm_db" and share the complete output. that would help us to find out the root cause. Many customers are using successfully it on Mac, so curious to know your issue.
If you are using nodejs V4.x, then please use this command to install it: npm install git+https://git@github.com/ibmdb/node-ibm_db.git#v4_support
Also, requesting you to fill this small form: http://goo.gl/forms/EKzg7A6HZw

**Comment by chethankumar** [comment]
I am still facing the same issue with v0.15 and v0.16 as well (running on Mac OS X 10.11.1)

chethan@chethans-mbp-2 ~/D/P/mfp-containers-app> sudo npm install ibm_db
Password:
npm WARN package.json mfp-containers-app@0.0.1 No license field.
-
> ibm_db@0.0.15 install /Users/chethan/Documents/Projects/mfp-containers-app/node_modules/ibm_db
> node installer/driverInstall.js

Downloading DB2 ODBC CLI Driver from http://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/macos64_odbc_cli.tar.gz...
Download and extraction of DB2 ODBC CLI Driver completed successfully ...
  CXX(target) Release/obj.target/odbc_bindings/src/odbc.o

{ [Error: Command failed: /bin/sh -c node-gyp configure build --IBM_DB_HOME=$IBM_DB_HOME --IS_DOWNLOADED=true
In file included from ../src/odbc.cpp:25:
In file included from ../src/odbc.h:23:
../node_modules/nan/nan.h:261:25: error: redefinition of '_NanEnsureLocal'
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../node_modules/nan/nan.h:256:25: note: previous definition is here
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                        ^
../node_modules/nan/nan.h:661:13: error: no member named 'smalloc' in namespace 'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^
../node_modules/nan/nan.h:672:12: error: no matching function for call to 'New'
    return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
           ^~~~~~~~~~~~~~~~~
/Users/chethan/.node-gyp/4.2.1/include/node/node_buffer.h:31:40: note: candidate function not viable: no known conversion from 'uint32_t' (aka 'unsigned int') to 'enum encoding' for 3rd argument
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/chethan/.node-gyp/4.2.1/include/node/node_buffer.h:43:40: note: candidate function not viable: 2nd argument ('const char *') would lose const qualifier
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/chethan/.node-gyp/4.2.1/include/node/node_buffer.h:28:40: note: candidate function not viable: requires 2 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                       ^
/Users/chethan/.node-gyp/4.2.1/include/node/node_buffer.h:36:40: note: candidate function not viable: requires 5 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
In file included from ../src/odbc.cpp:25:
In file included from ../src/odbc.h:23:
../node_modules/nan/nan.h:676:12: error: no viable conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object>'
    return node::Buffer::New(v8::Isolate::GetCurrent(), size);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/chethan/.node-gyp/4.2.1/include/node/v8.h:210:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'v8::MaybeLocal<v8::Object>' to 'const v8::Local<v8::Object> &' for 1st argument
class Local {
      ^
/Users/chethan/.node-gyp/4.2.1/include/node/v8.h:210:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object> &&' for 1st argument
class Local {
      ^
/Users/chethan/.node-gyp/4.2.1/include/node/v8.h:214:13: note: candidate template ignored: could not match 'Local' against 'MaybeLocal'
  V8_INLINE Local(Local<S> that)
            ^
/Users/chethan/.node-gyp/4.2.1/include/node/v8.h:326:13: note: candidate template ignored: could not match 'S *' against 'v8::MaybeLocal<v8::Object>'
  V8_INLINE Local(S* that)
            ^
In file included from ../src/odbc.cpp:25:
In file included from ../src/odbc.h:23:
../node_modules/nan/nan.h:683:26: error: no member named 'Use' in namespace 'node::Buffer'
    return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
           ~~~~~~~~~~~~~~^
../src/odbc.cpp:115:16: warning: implicit conversion of NULL constant to 'SQLHENV' (aka 'int') [-Wnull-conversion]
      m_hEnv = NULL;      
             ~ ^~~~
               0
../src/odbc.cpp:129:17: warning: implicit conversion of NULL constant to 'SQLHENV' (aka 'int') [-Wnull-conversion]
  dbo->m_hEnv = NULL;
              ~ ^~~~
                0
../src/odbc.cpp:221:32: warning: cast to 'void *' from smaller integer type 'SQLHENV' (aka 'int') [-Wint-to-void-pointer-cast]
    args[0] = NanNew<External>((void*)data->dbo->m_hEnv);
                               ^
../src/odbc.cpp:222:32: warning: cast to 'void *' from smaller integer type 'SQLHDBC' (aka 'int') [-Wint-to-void-pointer-cast]
    args[1] = NanNew<External>((void*)data->hDBC);
                               ^
../src/odbc.cpp:233:5: warning: 'FatalException' is deprecated: Use FatalException(isolate, ...) [-Wdeprecated-declarations]
    FatalException(try_catch);
    ^
/Users/chethan/.node-gyp/4.2.1/include/node/node.h:283:29: note: 'FatalException' has been explicitly marked deprecated here
                inline void FatalException(const v8::TryCatch& try_catch) {
                            ^
/Users/chethan/.node-gyp/4.2.1/include/node/node.h:66:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^
../src/odbc.cpp:268:32: warning: cast to 'void *' from smaller integer type 'SQLHENV' (aka 'int') [-Wint-to-void-pointer-cast]
  params[0] = NanNew<External>((void*)dbo->m_hEnv);
                               ^
../src/odbc.cpp:269:32: warning: cast to 'void *' from smaller integer type 'SQLHDBC' (aka 'int') [-Wint-to-void-pointer-cast]
  params[1] = NanNew<External>((void*)hDBC);
                               ^
../src/odbc.cpp:479:9: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tm_sec : 0
        ^~~~~~~~
        .tm_sec = 
../src/odbc.cpp:480:11: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        , tm_min : 0
          ^~~~~~~~
          .tm_min = 
../src/odbc.cpp:481:11: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        , tm_hour : 0
          ^~~~~~~~~
          .tm_hour = 
../src/odbc.cpp:482:11: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        , tm_mday : 0
          ^~~~~~~~~
          .tm_mday = 
../src/odbc.cpp:483:11: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        , tm_mon : 0
          ^~~~~~~~
          .tm_mon = 
../src/odbc.cpp:484:11: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        , tm_year : 0
          ^~~~~~~~~
          .tm_year = 
../src/odbc.cpp:485:11: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        , tm_wday : 0
          ^~~~~~~~~
          .tm_wday = 
../src/odbc.cpp:486:11: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        , tm_yday : 0
          ^~~~~~~~~
          .tm_yday = 
../src/odbc.cpp:487:11: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        , tm_isdst : 0
          ^~~~~~~~~~
          .tm_isdst = 
../src/odbc.cpp:488:11: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        , tm_gmtoff : 0
          ^~~~~~~~~~~
          .tm_gmtoff = 
../src/odbc.cpp:489:11: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        , tm_zone : 0
          ^~~~~~~~~
          .tm_zone = 
In file included from ../src/odbc.cpp:19:
/Users/chethan/.node-gyp/4.2.1/include/node/v8.h:221:5: error: assigning to 'v8::Primitive *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/chethan/.node-gyp/4.2.1/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:414:12: note: in instantiation of function template specialization 'v8::Local<v8::Primitive>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/odbc.cpp:19:
/Users/chethan/.node-gyp/4.2.1/include/node/v8.h:221:5: error: assigning to 'v8::Boolean *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/chethan/.node-gyp/4.2.1/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:424:12: note: in instantiation of function template specialization 'v8::Local<v8::Boolean>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/odbc.cpp:19:
/Users/chethan/.node-gyp/4.2.1/include/node/v8.h:221:5: error: assigning to 'v8::Function *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/chethan/.node-gyp/4.2.1/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1514:12: note: in instantiation of function template specialization 'v8::Local<v8::Function>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(handle)->Get(kCallbackIndex)
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/odbc.cpp:19:
/Users/chethan/.node-gyp/4.2.1/include/node/v8.h:221:5: error: assigning to 'v8::Object *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/chethan/.node-gyp/4.2.1/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1632:12: note: in instantiation of function template specialization 'v8::Local<v8::Object>::Local<v8::Value>' requested here
    return NanEscapeScope(handle->Get(NanNew(key)).As<v8::Object>());
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/odbc.cpp:19:
/Users/chethan/.node-gyp/4.2.1/include/node/v8.h:221:5: error: assigning to 'v8::Array *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/chethan/.node-gyp/4.2.1/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../src/odbc.cpp:961:10: note: in instantiation of function template specialization 'v8::Local<v8::Array>::Local<v8::Value>' requested here
  return NanEscapeScope(rows);
         ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
18 warnings and 10 errors generated.
make: *** [Release/obj.target/odbc_bindings/src/odbc.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build" "--IBM_DB_HOME=/Users/chethan/Documents/Projects/mfp-containers-app/node_modules/ibm_db/installer/clidriver" "--IS_DOWNLOADED=true"
gyp ERR! cwd /Users/chethan/Documents/Projects/mfp-containers-app/node_modules/ibm_db
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/bin/sh -c node-gyp configure build --IBM_DB_HOME=$IBM_DB_HOME --IS_DOWNLOADED=true' }
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "ibm_db"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! ibm_db@0.0.15 install: `node installer/driverInstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ibm_db@0.0.15 install script 'node installer/driverInstall.js'.
npm ERR! This is most likely a problem with the ibm_db package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node installer/driverInstall.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls ibm_db
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/chethan/Documents/Projects/mfp-containers-app/npm-debug.log
chethan@chethans-mbp-2 ~/D/P/mfp-containers-app> 


Is there any solution or workaround for this?

**Comment by bimalkjha** [comment]
@chethankumar Since you are using node.js v4.2.1, you should this command for installation:
`npm install git+https://git@github.com/ibmdb/node-ibm_db.git#v4_support`
Thanks.

**Comment by chethankumar** [comment]
@bimalkjha  I get the same error with the command you mentioned. 
Can I try anything else?

**Comment by zamrokk** [comment]
the command solved my problem on node V4.2.2

Thank you

**Comment by bimalkjha** [comment]
@chethankumar ibm_db@0.0.15  is not supported for node.js v4.x. First you need to delete all old installation of ibm_db from your system and then try the above command to install v4_support branch. thanks.

**Comment by bimalkjha** [comment]
ibm_db@0.0.19 is supported for node.js v 0.10.x, 0.12.x and 0.4.x. Thanks.

**Comment by sanraj22** [comment]
npm install is failing in redhat rhel6 with inb_db@0.0.19 and Node version 4.2.6 also with below error.

npm info ibm_db@0.0.19 Failed to exec install script
npm verb unlock done using /root/.npm/_locks/ibm-db-ba18bfce146f2908.lock for /root/NodeDataProvider/node_modules/ibm_db
npm verb stack Error: ibm_db@0.0.19 install: `node installer/driverInstall.js`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/root/softwares/node-v4.2.6-linux-x64/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
npm verb stack     at emitTwo (events.js:87:13)
npm verb stack     at EventEmitter.emit (events.js:172:7)
npm verb stack     at ChildProcess.<anonymous> (/root/softwares/node-v4.2.6-linux-x64/lib/node_modules/npm/lib/utils/spawn.js:24:14)
npm verb stack     at emitTwo (events.js:87:13)
npm verb stack     at ChildProcess.emit (events.js:172:7)
npm verb stack     at maybeClose (internal/child_process.js:821:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
npm verb pkgid ibm_db@0.0.19
npm verb cwd /root/NodeDataProvider
npm ERR! Linux 2.6.32-573.18.1.el6.x86_64
npm ERR! argv "/root/softwares/node-v4.2.6-linux-x64/bin/node" "/root/softwares/node-v4.2.6-linux-x64/bin/npm" "install" "ibm_db" "--verbose"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! ibm_db@0.0.19 install: `node installer/driverInstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ibm_db@0.0.19 install script 'node installer/driverInstall.js'.
npm ERR! This is most likely a problem with the ibm_db package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node installer/driverInstall.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls ibm_db
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]
npm verb unbuild node_modules/ibm_db
npm info preuninstall ibm_db@0.0.19
npm info uninstall ibm_db@0.0.19
npm verb unbuild rmStuff ibm_db@0.0.19 from /root/NodeDataProvider/node_modules
npm info postuninstall ibm_db@0.0.19
npm verb gentlyRm don't care about contents; nuking /root/NodeDataProvider/node_modules/ibm_db

npm ERR! Please include the following file with any support request:
npm ERR!     /root/NodeDataProvider/npm-debug.log
