### ISSUE TITLE
Getting Error: "0x0000" Parameter value "0x0000" is not supported after calling open()

### ISSUE THREAD

**Issue by JueZh** [ibmdb/node-ibm_db#450]
I'm trying to connect to my databases on two different servers, but one of them keep returning this error in the callback and the other works fine:

`[IBM][CLI Driver] SQL30073N  "0x0000" Parameter value "0x0000" is not supported.  SQLSTATE=58017`

I'm able to connect to both db via DataGrip or other tool.
I'm just using the sample code to connect:
```
ibmdb.open('DATABASE=MAIN;HOSTNAME=<my db name>;PORT=6001;UID=<my username>;PWD=<my password>', (err, conn) => {
    if (err) return console.log(err); // err exists

    conn.query('', function (err, data) {
        if (err) console.log(err);
        else console.log(data);

        conn.close(function () {
            console.log('done');
        });
    });
});
```

Here is the error object in callback: 
```
{
  "errors": [],
  "error": "[node-odbc] SQL_ERROR",
  "message": "[IBM][CLI Driver] SQL30073N  \"0x0000\" Parameter value \"0x0000\" is not supported.  SQLSTATE=58017\n",
  "state": "08001",
  "sqlcode": -30073
}
```

**Comment by bimalkjha** [comment]
I do not see any sql here: `conn.query('', function (err, data) {`

**Comment by JueZh** [comment]
Hi @bimalkjha , it's not going to that line yet, I'm just trying to test the connection.

**Comment by bimalkjha** [comment]
In that case, may be some issue with your connection string. Make sure your connection string is like: `connStr = "DATABASE=dbname;HOSTNAME=hostname;PORT=port;PROTOCOL=TCPIP;UID=username;PWD=passwd";` and you may try to run a test file with the codes shared as example [here](https://github.com/ibmdb/node-ibm_db#-1-openconnectionstring-options-callback). Thanks.
