### ISSUE TITLE
Memory leak issue using this module

### ISSUE THREAD

**Issue by gopi014** [ibmdb/node-ibm_db#452]
Hi,
I am using IBM_DB and my application is deployed in IBM Cloud. I see my application memory is going on higher side and it never comes down. I tried using memwatch node module to find out whether there is any memory leak and it did say there is memory leak. I tried isolating things one by one and seems this particular node module is causing the memory leak.I did want to confirm that this particular node module is causing the problem and I did restart of my app and tried hitting one api of my app and I saw increase in the memory and it never came down. I am using node version 8.11.4 and dash-db version is 2.4.0.  Can you please help me to get this memory leak resolved.

**Comment by bimalkjha** [comment]
@gopi014 It depends on the behavior of your application. If you application is not freeing up the connection or statements, it may hold memory and garbage collector of javascript may not be able to free it. If you could share small test program through which we can repro the issue by just updating connection string, it would help us to understand the issue. Thanks.

**Comment by gopi014** [comment]
@bimaljha You can clone the following application to see how it is been implemented in our application.
https://github.com/gopi014/dashdbsample

**Comment by gopi014** [comment]
@bimalkjha any updates on this?

**Comment by bimalkjha** [comment]
@rophy When you use `pool.open()`, the `connection.close()` do not close the actual connection and do not free the resources, rather it moves the connection to the pool so that next `pool.open()` can return this connection for use. It would be helpful if you could provide more info about how you come to the conclusion that use of `pool.open()` causes memory leak. Thanks.

**Comment by bimalkjha** [comment]
@gopi014 I cloned dashdbsample and tried to run it. But it fails with below error:
```
> node app.js
internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module '../logger'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/home/bjha/nodework/installed/dashdbsample/db/ibmdb.js:5:14)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/home/bjha/nodework/installed/dashdbsample/routes/superuser.js:7:15)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
```
This error is coming from here: https://github.com/gopi014/dashdbsample/blob/master/db/ibmdb.js#L5
`const logger=require('../logger').logger();`. I do not see any file of folder with name logger in dashdbsample. Also, do not see logger in package.json as a dependency. Thinking logger is a package, I have installed logger, but it throws `TypeError: require(...).logger is not a function`.
Please suggest how to run your sample code and how to identify memory leak? Thanks.

**Comment by gopi014** [comment]
@bimalkjha I have pushed the updated code.Please do check and let me know if you are able run

**Comment by saumil221b** [comment]
We are facing a very similar issue where the mem usage climbs rapidly and does not come down even with no traffic.
@rophy - What did you end up using ? Was there any resolution? and if you are not using the pool as you have mentioned above, how are you handling the heavy traffic if any on your app?

**Comment by bol07** [comment]
We are facing a very similar issue where the mem usage climbs rapidly and does not come down even with no traffic.
@rophy - What did you end up using ? Was there any resolution? and if you are not using the pool as you have mentioned above, how are you handling the heavy traffic if any on your app?

**Comment by bol07** [comment]
@bimalkjha Is this an open issue with the latest version of the package?

**Comment by bimalkjha** [comment]
@bol07 Don't know exact answer as I do not have any test program to reproduce the problem. We believe that there is no mem leak unless application is not freeing some memory properly.
Also, in case pool, as the connections in pool grows, you may see more memory usage but after sometime, it should be constant. If you have any test program using which I can repro the issue with steps, I can look into that. gopi has shared some app on github, but unfortunately it is not working and I do not see any step that can be followed to see the problem. Thanks.

**Comment by chiaki1770** [comment]
Hi @bimalkjha I'm facing a similar issue as well, I used conn.close() everywhere. Also, used Pool.open and configured Pool using idleTimeout and autoCleanIdle. Even though there's only one connection in the Pool, on the db2 server it listed around 40 connections.

**Comment by bimalkjha** [comment]
@chiaki1770 Please use ibm_db@2.5.2, thanks.

**Comment by chiaki1770** [comment]
@bimalkjha I upgraded to ibm_db@2.5.2 already.

**Comment by bimalkjha** [comment]
@chiaki1770 Please share some code to reproduce and steps to see the memory leak. Thanks.

**Comment by bimalkjha** [comment]
ibm_db@2.6.0 include fix of this issue. Thanks.
