### ISSUE TITLE
ibm_db vs ibm_db2

### ISSUE THREAD

**Issue by nsanthoshkumar** [ibmdb/node-ibm_db#454]
Can you guys let us know the difference between ibm_db vs ibm_db2? Are both the modules same or different? Because, I see the both modules are pointing to the same github repo. Also, the examples on the npm are pointing to ibm_db?

**Comment by bimalkjha** [comment]
@nsanthoshkumar ibm_db is the original package that we maintain and upload. ibm_db2 is uploaded by user kauegimenes and not us. You should use ibm_db package not ibm_db2. Thanks.
