### ISSUE TITLE
Invalid ELF Header when using Docker with Ubuntu:Xenial 

### ISSUE THREAD

**Issue by NeuralViva** [ibmdb/node-ibm_db#458]
Hi,

I'm trying to build a node 9.11.1 docker image using the docker file below.

```FROM ubuntu:xenial

ENV app /usr/src/app/ 
ENV NODE_VERSION 9.11.1

RUN groupadd -r node && useradd --no-log-init -r -g node node
RUN mkdir -p ${app} && chown node ${app}
RUN apt-get update -yq \
    && apt-get install curl gnupg -yq \
    && curl -sL https://deb.nodesource.com/setup_9.x | bash \
    && apt-get install nodejs -yq \
    && apt-get install build-essential -yq

WORKDIR ${app}

COPY package.json ${app}
RUN npm install
COPY . ${app}

CMD ["npm", "start"] 
```

The build runs successfully but when I try to run the image I get: 

``` 
usr/src/app/node_modules/bindings/bindings.js:88
        throw e
        ^

Error: /usr/src/app/node_modules/ibm_db/build/Release/odbc_bindings.node: invalid ELF header
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:683:18)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at bindings (/usr/src/app/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/usr/src/app/node_modules/ibm_db/lib/odbc.js:31:31)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

I have tried adding the node version specified in the [old fix](https://github.com/ibmdb/node-ibm_db/issues/68) to this but that made no difference.

Any ideas?

Thanks in advance.

Ollie

**Comment by bimalkjha** [comment]
Please share the complete output of install command. invalid ELF header means your odbc_bindings.node is not for current version of node.js. Have you copied this odbc_bindings.node from other location? Thanks.

**Comment by NeuralViva** [comment]
Hi Sorry for the slow reply.

The docker image builds as expected and the node application runs.

But when I try the first query (it's using a db pool) I get:

```
listening on 3000
/usr/src/app/node_modules/bindings/bindings.js:88
        throw e
        ^

Error: /usr/src/app/node_modules/ibm_db/build/Release/odbc_bindings.node: invalid ELF header
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:683:18)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at bindings (/usr/src/app/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/usr/src/app/node_modules/ibm_db/lib/odbc.js:31:31)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
```

My dependancies are:

```
  "dependencies": {
    "body-parser": "^1.18.3",
    "express": "^4.16.3",
    "request": "^2.88.0",
    "request-promise-native": "^1.0.5",
    "ibm_db": "^2.4.1"
  }
```

I was assuming it used the odbc driver built into the ibm_db package?

Should i be explicitly referencing one instead?

Regards

**Comment by bimalkjha** [comment]
@NeuralViva Could  you share how you got the file /usr/src/app/node_modules/ibm_db/build/Release/odbc_bindings.node? It does not exist on github. Thanks.

**Comment by NeuralViva** [comment]
There are two section that I'm working on.

My local dev environment is a Mac I'm running npm install and then a start script with: node index.js (this works)

I felt my docker build required building an Ubuntu install ( I was using Alpine but it didn't have the ODBC deps) 
I augmented this build with:

```
RUN apt-get update -yq \
    && apt-get install curl gnupg -yq \
    && curl -sL https://deb.nodesource.com/setup_9.x | bash \
    && apt-get install nodejs -yq \
    && apt-get install build-essential -yq
```

I added build-essential to run make as it seemed to me to be part of the build's requirements. 
Maybe the "/usr/src/app/node_modules/ibm_db/build/Release/odbc_bindings.node" was added as part of that process?

I'm not an expert in this area so I may have built this incorrectly. 
Do you have any suggestions for an alternative to this build?

Many thanks for the help.

**Comment by bimalkjha** [comment]
In the shared `RUN apt-get` command, I do not see ibm_db. Please share some info about how to get `/usr/src/app/node_modules/ibm_db` too. Thanks.

**Comment by rhtpandeyIN** [comment]
Hi @NeuralViva ,

Are you copying application code from your local system to docker image?
If that's the case then please add a `.dockerignore` excluding `node_modules` directory.

>I added build-essential to run make as it seemed to me to be part of the build's requirements.
Maybe the "/usr/src/app/node_modules/ibm_db/build/Release/odbc_bindings.node" was added as part of that process?

Well, no **"/ibm_db/build/Release/odbc_bindings.node"** file does not comes with build-essentials, it's a binary file which gets generated after the successful build of ibm_db (simply saying - when you build the ibm_db module you gets the odbc_bindings.node file).

It seems you are not building the ibm_db in the docker environment and pushing all your dependencies from your local mac system to docker Linux system. (I mean that's when this error comes generally)

If that's not the case, then it means ibm_db is not getting build properly, I would suggest try to install ibm_db separately in some other directory inside your docker image and check if it's working fine or not.
That way we can verify where the problem is.

**Comment by NeuralViva** [comment]
> Well, no "/ibm_db/build/Release/odbc_bindings.node" file does not comes with build-essentials, it's a binary file which gets generated after the successful build of ibm_db (simply saying - when you build the ibm_db module you gets the odbc_bindings.node file): Sorry if this was miscommunicated I mean't that `odbc_bindings.node` was added by make once it has run as part of my docker build.

This docker build runs on a separate machine from my mac so the node_modules folder is not being copied although I had not added a .dockerignore (which I have now, thanks for the tip I'll use those all the time now).

I'll try building an a image with only ibm_db in it and post the results. Do you have a standard docker file for building a base image that you would recommend using?

**Comment by bimalkjha** [comment]
>  Do you have a standard docker file for building a base image that you would recommend using?
We do not have any information about such base image.  Thanks.
