### ISSUE TITLE
Connection pool doesn't reconnect when server goes down, and no errors are returned

### ISSUE THREAD

**Issue by DannielWillian** [ibmdb/node-ibm_db#460]
Hi, I have a node.js application on Bluemix, and I use the ibm_db driver to connect to a Db2 Warehouse instance. Sometimes this db2 instance goes down for maintenance, and I get an error message like this (IP masked):

"[IBM][CLI Driver] SQL30081N A communication error has been detected. Communication protocol being used: "TCP/IP". Communication API being used: "SOCKETS". Location where the error was detected: "XXX.XX.XXX.XXX". Communication function detecting the error: "recv". Protocol specific error code(s): "104", "*", "0". SQLSTATE=08001

Sometimes the reason code is 104, sometimes is 115, 34, *...

After that, all my queries return empty instead of an error, and I have to restart the application to be able to reconnect to the server. Even though I still see all the connections in my pool and I'm still able to use them (getting empty responses back, that is).

I'm using ibm_db version ^2.4.0.

Is this the expected behaviour for the connection Pool? Is there a way, like a Pool configuration, that I can set to reconnect automatically?

**Comment by bimalkjha** [comment]
@DannielWillian To implement automatic reconnect, please configure db2dsdriver.cfg file as documented [here](https://github.com/ibmdb/node-ibm_db/issues/270#issuecomment-311171336). You are facing the similar issue. Thanks.

**Comment by DannielWillian** [comment]
Hi Bimal, thanks for the reply. I'll give it a shot. Best regards.
