### ISSUE TITLE
npm install ibm_db fails on Mac OS Mojave (10.14)

### ISSUE THREAD

**Issue by micophilip** [ibmdb/node-ibm_db#464]
Hello,

When attempting to install ibm_db 2.4.1 on macOS Mojave, I'm getting the error below:
```
Downloading and extraction of DB2 ODBC CLI Driver completed successfully ...

  CXX(target) Release/obj.target/odbc_bindings/src/odbc.o

{ Error: Command failed: node-gyp configure build  --IS_DOWNLOADED=true --IBM_DB_HOME="$IBM_DB_HOME"
warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
In file included from ../src/odbc.cpp:22:
/Users/micophilip/.node-gyp/6.14.4/include/node/v8.h:21:10: fatal error: 'utility' file not found
#include <utility>
         ^~~~~~~~~
1 warning and 1 error generated.
make: *** [Release/obj.target/odbc_bindings/src/odbc.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Darwin 18.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build" "--IS_DOWNLOADED=true" "--IBM_DB_HOME=/Users/micophilip/Documents/workspace/common/node_modules/ibm_db/installer/clidriver"
gyp ERR! cwd /Users/micophilip/Documents/workspace/common/node_modules/ibm_db
gyp ERR! node -v v6.14.4
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

    at ChildProcess.exithandler (child_process.js:199:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Socket.<anonymous> (internal/child_process.js:351:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:509:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node-gyp configure build  --IS_DOWNLOADED=true --IBM_DB_HOME="$IBM_DB_HOME"' }
```

**Comment by micophilip** [comment]
Update: I had to run the following before `npm install ibm_db` to get it to work - not sure if there's a way to do that by default in `binding.gyp` so that users won't have to explicitly set it before installing `ibm_db`
```
export CXXFLAGS="-mmacosx-version-min=10.9"
export LDFLAGS="-mmacosx-version-min=10.9"
```

**Comment by jlundgren** [comment]
> I tried @micophilip solution by exporting the flags to the terminal before I ran the installer, but still ran into issues - could this be because of version issues or am I a potatohead?
> 
> Any help would be greatly appreciated!
> 
> -- Snippet from "npm install ibm_db" command --
> 
> 5 warnings and 3 errors generated.
> make: *** [Release/obj.target/odbc_bindings/src/odbc.o] Error 1
> gyp ERR! build error
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack at ChildProcess.onExit (/Users/jens/.nvm/versions/node/v10.11.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
> gyp ERR! stack at ChildProcess.emit (events.js:182:13)
> gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
> gyp ERR! System Darwin 17.7.0
> gyp ERR! command "/Users/jens/.nvm/versions/node/v10.11.0/bin/node" "/Users/jens/.nvm/versions/node/v10.11.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build" "--IS_DOWNLOADED=true" "--IBM_DB_HOME=/Users/jens/development/ibm_iotf/node_modules/ibm_db/installer/clidriver"
> gyp ERR! cwd /Users/jens/development/ibm_iotf/node_modules/ibm_db
> gyp ERR! node -v v10.11.0
> gyp ERR! node-gyp -v v3.8.0
> gyp ERR! not ok
> 
> ```
> at ChildProcess.exithandler (child_process.js:289:12)
> at ChildProcess.emit (events.js:182:13)
> at maybeClose (internal/child_process.js:962:16)
> at Socket.stream.socket.on (internal/child_process.js:381:11)
> at Socket.emit (events.js:182:13)
> at Pipe._handle.close (net.js:606:12)
> ```
> killed: false,
> code: 1,
> signal: null,
> cmd:
> 'node-gyp configure build --IS_DOWNLOADED=true --IBM_DB_HOME="$IBM_DB_HOME"' }
> npm WARN testing_iotf@1.0.0 No description
> npm WARN testing_iotf@1.0.0 No repository field.
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! ibm_db@2.4.1 install: `node installer/driverInstall.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the ibm_db@2.4.1 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

I resolved my issue by manually downloading the ODBC driver and exporting the IBM_DB_INSTALLER_URL to the terminal before starting the npm installation

**Comment by bimalkjha** [comment]
@jlundgren `gyp ERR! node -v v10.11.0` is the issue. Use node.js v < 10.x. Thanks.

**Comment by rhtpandeyIN** [comment]
Closing the issue now, as it is resolved.
