### ISSUE TITLE
more detailed examples

### ISSUE THREAD

**Issue by madsteer** [ibmdb/node-ibm_db#467]
Not sure this qualifies as an issue, but I wasn't sure if there was a better way to ask or this.  Any way to get an example like the `singleRowFetch.js` example that includes returning the queried data out of the `conn.queryResult` code?  So, pretend the `conn.*` code is in a function and you need to return that data from the function and then use it in javascript code etc.  I'm stuck on this and caught up in all kinds of async/Promise tripe trying to get it to work.  Thanks,

**Comment by bimalkjha** [comment]
@madsteer Just grep for queryResult under ibm_db/test folder and you can see many test-*.js files using it. test-query-select-fetch.js shows how to fetch single row using fetch() api. test-queryResult.js also could help. To see how, individual rows can be retrieved using fetch, you can check test-fetch-apis.js. Also, the documentation has many examples that could help you. Thanks.

**Comment by madsteer** [comment]
I'm probably not asking my question very well, but the test-queryResult.js test is what I'm talking about.  Everything with the data is happening inside the function being passed to `imdv.open(`  I'm trying to understand how to:
1. make query
2. do processing on those results
3. make a second query
4. more processing
5. issue a CUD update/insert

perhaps I'm not thinking "functionally" but if I have to pass all the into the `ibmdb.open(` function as a function, that's going to be one big, ugly, hard to debug/maintain function isn't it?  I was hoping I could do something like:
```javascript
function myQueryFunction(query) {
  ibmdb.open(cn, (error, conn) => {
. . .
         conn.query(query (err, result) => {
               . . .
         }
   }
  return result
}

. . .
let myQueryResult = myQueryFunction("select blah de blah")
. . .
let my2ndQueryResult = myQueryFunction("select foo de bar")
. . .
```

What does something like that look like?

**Comment by bimalkjha** [comment]
@madsteer In such case, I think you should use Sync APIs. Please check `test-fetch-apis.js` file too which has similar use as you mentioned. See the below code which do not call multiple functions withing functions.
```
ibmdb.open(cn,function(err,conn){
  conn.querySync("create table hits (col1 varchar(40), col2 int)");
  conn.querySync("insert into hits values ('something', 42)");
  conn.querySync("insert into hits values ('für', 43)");

  // Fetch data Synchronously using fetchSync() API.
  var stmt = conn.prepareSync("select * from hits");
  var result = stmt.executeSync();
  var data = 0;
  console.log("result = ", result);
  console.log("Selected data using fetchSync() API = ");
  while( data = result.fetchSync({fetchMode:3}) ) {
    console.log(data);
  }
  result.closeSync();

  // Fetch data Synchronously using fetchAllSync() API.
  //stmt = conn.prepareSync("select * from hits");
  result = stmt.executeSync();
  data = result.fetchAllSync();
  console.log("Selected rows using fetchAllSync() API = ", data);
  result.closeSync();

  // Fetch data Asynchronously using fetchAll() API.
  result = stmt.executeSync();
  data = result.fetchAllSync();
  console.log("data = ", data);
  result.closeSync();
  conn.closeSync();
});
```
For async programming, there is only two ways in node.js. Either pass the callback function to async apis - i.e. functions withing functions, or use the promises as in `promise-test-all-data-types.js`. Thanks.

**Comment by madsteer** [comment]
All these tests and examples just log the data to console and never do anything with the data outside the scope of the database connection.

So, with a postgresql database for example, I can
```javascript
const { Pool } = require('pg')
const pool = new Pool({
  database: "value",
  host: "value",
  max: 30, // maximum number of concurrent clients (default = 10)
  password: "value",
  port: "value",
  user: "value"
})
. . .
const { rows } = pool.query("select blah de blah")
// yeah! I have my data and I've left the postgres code/scope
```

It would seem, that with this db2 driver, my data can never leave the scope of the `ibmdb.open`, right?  I have to do everything I want to do with the data inside that scope as I can not return it out off the `.open` scope.  How would I write a REST service to frontend a DB2 database, for example?  I could never return the data back on a GET call?  This is my question.

**Comment by bimalkjha** [comment]
@madsteer If you want to use data out of the scope of ibmdb.open, then use `ibmdb.openSync` api. Please check [test-querySync-select.js](https://github.com/ibmdb/node-ibm_db/blob/master/test/test-querySync-select.js) file. You can grep for `openSync` under test folder to see many examples. Thanks.

**Comment by ibmjm** [comment]
> All these tests and examples just log the data to console and never do anything with the data outside the scope of the database connection.
> 
> So, with a postgresql database for example, I can
> 
> ```js
> const { Pool } = require('pg')
> const pool = new Pool({
>   database: "value",
>   host: "value",
>   max: 30, // maximum number of concurrent clients (default = 10)
>   password: "value",
>   port: "value",
>   user: "value"
> })
> . . .
> const { rows } = pool.query("select blah de blah")
> // yeah! I have my data and I've left the postgres code/scope
> ```
> 
> It would seem, that with this db2 driver, my data can never leave the scope of the `ibmdb.open`, right? I have to do everything I want to do with the data inside that scope as I can not return it out off the `.open` scope. How would I write a REST service to frontend a DB2 database, for example? I could never return the data back on a GET call? This is my question.

@madsteer I wish I'd found your issue before I wasted a day and a half trying to do the same thing (get data out of the async methods).

**Comment by djtbdanner** [comment]
```
async function runQuery(dns, query, resultKey) {
    return new Promise((resolve, reject) => {
        pool.open(dns, function (err, connection) {
            if (err) {
                reject(err);
            }
            connection.query(sql, function (err1, rows) {
                if (err1) {
                    reject(err);
                }
                connection.close(function (err2) {
                    if (err2) console.log(err2);
                });
                resolve(rows);
            });
        });
    });
}
```
Can be called like this from an async function
```
const x = await runQuery('select * from table where colunm = ?', [id] );
```
