### ISSUE TITLE
CLI0109E  String data right truncation. SQLSTATE=22001 error happened in conn.query api

### ISSUE THREAD

**Issue by kokoji** [ibmdb/node-ibm_db#469]
I used ibm_db in my node.js program.
The error "CLI0109E  String data right truncation. SQLSTATE=22001"  happened when the insert SQL is executed by conn.query api which value of a row is over 256bytes.
How can I avoidable this error?
Thank you.

**Comment by bimalkjha** [comment]
@kokoji The insert query assumes that you are inserting a CHAR data which accepts max 255 bytes. If you data is of higher size, then you should use prepare, bind, execute logic or use parameter markers in sql and pass the values as param object as documented [here](https://github.com/ibmdb/node-ibm_db/blob/master/APIDocumentation.md#bindingparameters). 
To insert larger data you need to pass the data type as VARCHAR which support upto 32,672 characters. The param object can be as `{ParamType:"INPUT", SQLType: "VARCHAR", "Data": "your string data"}`
For more info about character data, you can check [this link](https://www.ibm.com/support/knowledgecenter/SSEPGG_11.1.0/com.ibm.db2.luw.sql.ref.doc/doc/r0008470.html). 
I still feel, ibm_db should be able to handle characters larger than 255 bytes automatically. If you can share some test program to reproduce the issue, it would help to enhance the code. Thanks.

**Comment by bimalkjha** [comment]
If you are inserting string larger than 255 chars, means the column in database is not of char type. It may be varchar, clob or dbclob. So, the same column type as in table should be used as SQLType in the param object. Thanks.

**Comment by kokoji** [comment]
Thank you.
I could insert over 256bytes by using 'CAST(? AS VARCHAR(32000)' .
