### ISSUE TITLE
Can't start node-red application with ibm_db error

### ISSUE THREAD

**Issue by TanyRay** [ibmdb/node-ibm_db#47]
Hi, from yesterday I can't start my NodeRed application which works with dashDB using ibm_db library with '0.x' in package.json. All the time I'm getting error:

> ibm_db@0.0.12 install /tmp/staged/app/node_modules/ibm_db
> node installer/driverInstall.js
IBM_DB_HOME environment variable have already been set to /tmp/staged/app/clidriver
make: Entering directory `/tmp/staged/app/node_modules/ibm_db/build'
  CXX(target) Release/obj.target/odbc_bindings/src/odbc.o
make: Leaving directory `/tmp/staged/app/node_modules/ibm_db/build'
{ [Error: Command failed: In file included from ../src/odbc.cpp:25:
../src/odbc.h:76: error: 'NanCallback' has not been declared
../src/odbc.h:77: error: 'NanCallback' has not been declared
../src/odbc.h:112: error: ISO C++ forbids declaration of 'NanCallback' with no type
../src/odbc.h:112: error: expected ';' before '*' token
In file included from ../src/odbc.cpp:26:
../src/odbc_connection.h:95: error: ISO C++ forbids declaration of 'NanCallback' with no type
../src/odbc_connection.h:95: error: expected ';' before '*' token
../src/odbc_connection.h:113: error: ISO C++ forbids declaration of 'NanCallback' with no type
../src/odbc_connection.h:113: error: expected ';' before '*' token
../src/odbc_connection.h:120: error: ISO C++ forbids declaration of 'NanCallback' with no type
../src/odbc_connection.h:120: error: expected ';' before '*' token
../src/odbc_connection.h:143: error: ISO C++ forbids declaration of 'NanCallback' with no type
../src/odbc_connection.h:143: error: expected ';' before '*' token
../src/odbc_connection.h:151: error: ISO C++ forbids declaration of 'NanCallback' with no type
../src/odbc_connection.h:151: error: expected ';' before '*' token
In file included from ../src/odbc.cpp:27:
../src/odbc_result.h:66: error: ISO C++ forbids declaration of 'NanCallback' with no type
../src/odbc_result.h:66: error: expected ';' before '*' token
In file included from ../src/odbc.cpp:28:
../src/odbc_statement.h:73: error: ISO C++ forbids declaration of 'NanCallback' with no type
../src/odbc_statement.h:73: error: expected ';' before '*' token
../src/odbc_statement.h:95: error: ISO C++ forbids declaration of 'NanCallback' with no type
../src/odbc_statement.h:95: error: expected ';' before '*' token
../src/odbc_statement.h:103: error: ISO C++ forbids declaration of 'NanCallback' with no type
../src/odbc_statement.h:103: error: expected ';' before '*' token
../src/odbc_statement.h:109: error: ISO C++ forbids declaration of 'NanCallback' with no type
../src/odbc_statement.h:109: error: expected ';' before '*' token
../src/odbc_statement.h:117: error: ISO C++ forbids declaration of 'NanCallback' with no type
../src/odbc_statement.h:117: error: expected ';' before '*' token
../src/odbc.cpp: In static member function 'static void ODBC::Init(v8::Handle<v8::Object>)':
../src/odbc.cpp:48: error: 'NanScope' was not declared in this scope
../src/odbc.cpp:50: error: 'NanNew' was not declared in this scope
../src/odbc.cpp:50: error: expected primary-expression before '>' token
../src/odbc.cpp:66: error: expected primary-expression before '>' token
../src/odbc.cpp:66: error: expected primary-expression before '>' token
../src/odbc.cpp:67: error: expected primary-expression before '>' token
../src/odbc.cpp:67: error: expected primary-expression before '>' token
../src/odbc.cpp:68: error: expected primary-expression before '>' token
../src/odbc.cpp:68: error: expected primary-expression before '>' token
../src/odbc.cpp:69: error: expected primary-expression before '>' token
../src/odbc.cpp:69: error: expected primary-expression before '>' token
../src/odbc.cpp:70: error: expected primary-expression before '>' token
../src/odbc.cpp:70: error: expected primary-expression before '>' token
../src/odbc.cpp:71: error: expected primary-expression before '>' token
../src/odbc.cpp:71: error: expected primary-expression before '>' token
../src/odbc.cpp:72: error: expected primary-expression before '>' token
../src/odbc.cpp:72: error: expected primary-expression before '>' token
../src/odbc.cpp:75: error: no matching function for call to 'SetPrototypeMethod(v8::Local<v8::FunctionTemplate>&, const char [17], Nan::NAN_METHOD_RETURN_TYPE (&)(const Nan::FunctionCallbackInfo<v8::Value>&))'
../src/odbc.cpp:76: error: no matching function for call to 'SetPrototypeMethod(v8::Local<v8::FunctionTemplate>&, const char [21], Nan::NAN_METHOD_RETURN_TYPE (&)(const Nan::FunctionCallbackInfo<v8::Value>&))'
../src/odbc.cpp:79: error: 'NanAssignPersistent' was not declared in this scope
../src/odbc.cpp: In static member function 'static Nan::NAN_METHOD_RETURN_TYPE ODBC::New(const Nan::FunctionCallbackInfo<v8::Value>&)':
../src/odbc.cpp:124: error: 'NanScope' was not declared in this scope
../src/odbc.cpp:127: error: 'args' was not declared in this scope
../src/odbc.cpp:143: error: 'NanThrowError' was not declared in this scope
../src/odbc.cpp:143: error: return-statement with a value, in function returning 'void'
../src/odbc.cpp:149: error: 'NanReturnValue' was not declared in this scope
../src/odbc.cpp: In static member function 'static Nan::NAN_METHOD_RETURN_TYPE ODBC::CreateConnection(const Nan::FunctionCallbackInfo<v8::Value>&)':
../src/odbc.cpp:163: error: 'NanScope' was not declared in this scope
../src/odbc.cpp:165: error: 'args' was not declared in this scope
../src/odbc.cpp:165: error: expected primary-expression before '>' token
../src/odbc.cpp:165: error: expected primary-expression before ')' token
../src/odbc.cpp:166: error: 'NanCallback' was not declared in this scope
../src/odbc.cpp:166: error: 'callback' was not declared in this scope
../src/odbc.cpp:166: error: expected type-specifier before 'NanCallback'
../src/odbc.cpp:166: error: expected ';' before 'NanCallback'
../src/odbc.cpp:178: error: 'struct create_connection_work_data' has no member named 'cb'
../src/odbc.cpp:187: error: 'NanUndefined' was not declared in this scope
../src/odbc.cpp:187: error: 'NanReturnValue' was not declared in this scope
../src/odbc.cpp:165: warning: unused variable 'cb'
../src/odbc.cpp: In static member function 'static void ODBC::UV_AfterCreateConnection(uv_work_t*, int)':
../src/odbc.cpp:206: error: 'NanScope' was not declared in this scope
../src/odbc.cpp:217: error: 'struct create_connection_work_data' has no member named 'cb'
../src/odbc.cpp:221: error: 'NanNew' was not declared in this scope
../src/odbc.cpp:221: error: expected primary-expression before '>' token
../src/odbc.cpp:222: error: expected primary-expression before '>' token
../src/odbc.cpp:224: error: expected primary-expression before '>' token
../src/odbc.cpp:226: error: expected primary-expression before '>' token
../src/odbc.cpp:226: error: 'NanNull' was not declared in this scope
../src/odbc.cpp:229: error: 'struct create_connection_work_data' has no member named 'cb'
../src/odbc.cpp:238: error: 'struct create_connection_work_data' has no member named 'cb'
../src/odbc.cpp: In static member function 'static Nan::NAN_METHOD_RETURN_TYPE ODBC::CreateConnectionSync(const Nan::FunctionCallbackInfo<v8::Value>&)':
../src/odbc.cpp:250: error: 'NanScope' was not declared in this scope
../src/odbc.cpp:252: error: 'args' was not declared in this scope
../src/odbc.cpp:268: error: 'NanNew' was not declared in this scope
../src/odbc.cpp:268: error: expected primary-expression before '>' token
../src/odbc.cpp:269: error: expected primary-expression before '>' token
../src/odbc.cpp:271: error: expected primary-expression before '>' token
../src/odbc.cpp:273: error: 'NanReturnValue' was not declared in this scope
../src/odbc.cpp: In static member function 'static v8::Handle<v8::Value> ODBC::GetColumnValue(void*, Column, uint16_t*, int)':
../src/odbc.cpp:369: error: 'NanEscapableScope' was not declared in this scope
../src/odbc.cpp:397: error: 'NanNull' was not declared in this scope
../src/odbc.cpp:397: error: 'NanEscapeScope' was not declared in this scope
../src/odbc.cpp:400: error: 'NanNew' was not declared in this scope
../src/odbc.cpp:400: error: expected primary-expression before '>' token
../src/odbc.cpp:400: error: 'NanEscapeScope' was not declared in this scope
../src/odbc.cpp:403: error: 'NanNew' was not declared in this scope
../src/odbc.cpp:403: error: expected primary-expression before '>' token
../src/odbc.cpp:403: error: 'NanEscapeScope' was not declared in this scope
../src/odbc.cpp:406: error: 'NanNew' was not declared in this scope
../src/odbc.cpp:406: error: expected primary-expression before '>' token
../src/odbc.cpp:406: error: 'NanEscapeScope' was not declared in this scope
../src/odbc.cpp:409: error: 'NanNew' was not declared in this scope
../src/odbc.cpp:409: error: expected primary-expression before '>' token
../src/odbc.cpp:409: error: 'NanEscapeScope' was not declared in this scope
../src/odbc.cpp:435: error: 'NanNull' was not declared in this scope
../src/odbc.cpp:435: error: 'NanEscapeScope' was not declared in this scope
../src/odbc.cpp:439: error: 'NanNew' was not declared in this scope
../src/odbc.cpp:439: error: expected primary-expression before '>' token
../src/odbc.cpp:439: error: 'NanEscapeScope' was not declared in this scope
../src/odbc.cpp:506: error: 'NanNull' was not declared in this scope
../src/odbc.cpp:506: error: 'NanEscapeScope' was not declared in this scope
../src/odbc.cpp:525: error: 'NanNew' was not declared in this scope
../src/odbc.cpp:525: error: expected primary-expression before '>' token
../src/odbc.cpp:526: error: 'NanEscapeScope' was not declared in this scope
../src/odbc.cpp:548: error: 'NanNull' was not declared in this scope
../src/odbc.cpp:548: error: 'NanEscapeScope' was not declared in this scope
../src/odbc.cpp:552: error: 'NanNew' was not declared in this scope
../src/odbc.cpp:552: error: 'NanEscapeScope' was not declared in this scope
../src/odbc.cpp:577: error: 'NanNull' was not declared in this scope
../src/odbc.cpp:577: error: 'NanEscapeScope' was not declared in this scope
../src/odbc.cpp:591: error: 'NanNew' was not declared in this scope
../src/odbc.cpp:599: error: 'NanNew' was not declared in this scope
../src/odbc.cpp:623: error: 'NanThrowError' was not declared in this scope
../src/odbc.cpp:624: error: 'NanUndefined' was not declared in this scope
../src/odbc.cpp:624: error: 'NanEscapeScope' was not declared in this scope
../src/odbc.cpp:629: error: 'NanEscapeScope' was not declared in this scope
../src/odbc.cpp: In static member function 'static v8::Local<v8::Object> ODBC::GetRecordTuple(void*, Column*, short int*, uint16_t*, int)':
../src/odbc.cpp:640: error: 'NanEscapableScope' was not declared in this scope
../src/odbc.cpp:642: error: 'NanNew' was not declared in this scope
../src/odbc.cpp:642: error: expected primary-expression before '>' token
../src/odbc.cpp:642: error: expected primary-expression before ')' token
../src/odbc.cpp:654: error: 'NanEscapeScope' was not declared in this scope
../src/odbc.cpp: In static member function 'static v8::Handle<v8::Value> ODBC::GetRecordArray(void*, Column*, short int*, uint16_t*, int)':
../src/odbc.cpp:664: error: 'NanEscapableScope' was not declared in this scope
../src/odbc.cpp:666: error: 'NanNew' was not declared in this scope
../src/odbc.cpp:666: error: expected primary-expression before '>' token
../src/odbc.cpp:666: error: expected primary-expression before ')' token
../src/odbc.cpp:673: error: 'NanEscapeScope' was not declared in this scope
../src/odbc.cpp: At global scope:
../src/odbc.cpp:789: error: 'NanCallback' has not been declared
../src/odbc.cpp: In static member function 'static v8::Handle<v8::Value> ODBC::CallbackSQLError(SQLSMALLINT, void*, int*)':
../src/odbc.cpp:790: error: 'NanEscapableScope' was not declared in this scope
../src/odbc.cpp:796: error: 'NanEscapeScope' was not declared in this scope
../src/odbc.cpp: At global scope:
../src/odbc.cpp:802: error: 'NanCallback' has not been declared
../src/odbc.cpp: In static member function 'static v8::Handle<v8::Value> ODBC::CallbackSQLError(SQLSMALLINT, void*, char*, int*)':
../src/odbc.cpp:803: error: 'NanEscapableScope' was not declared in this scope
../src/odbc.cpp:813: error: request for member 'Call' in '* cb', which is of non-class type 'int'
../src/odbc.cpp:815: error: 'NanUndefined' was not declared in this scope
../src/odbc.cpp:815: error: 'NanEscapeScope' was not declared in this scope
../src/odbc.cpp: In static member function 'static v8::Local<v8::Object> ODBC::GetSQLError(SQLSMALLINT, void*)':
../src/odbc.cpp:823: error: 'NanEscapableScope' was not declared in this scope
../src/odbc.cpp:828: error: 'NanEscapeScope' was not declared in this scope
../src/odbc.cpp: In static member function 'static v8::Local<v8::Object> ODBC::GetSQLError(SQLSMALLINT, void*, char*)':
../src/odbc.cpp:832: error: 'NanEscapableScope' was not declared in this scope
../src/odbc.cpp:836: error: 'NanNew' was not declared in this scope
../src/odbc.cpp:836: error: expected primary-expression before '>' token
../src/odbc.cpp:836: error: expected primary-expression before ')' token
../src/odbc.cpp:858: error: expected primary-expression before '>' token
../src/odbc.cpp:858: error: expected primary-expression before ')' token
../src/odbc.cpp:894: error: 'NanEscapeScope' was not declared in this scope
../src/odbc.cpp: In static member function 'static v8::Local<v8::Array> ODBC::GetAllRecordsSync(void*, void*, void*, uint16_t*, int)':
../src/odbc.cpp:908: error: 'NanEscapableScope' was not declared in this scope
../src/odbc.cpp:910: error: 'NanNew' was not declared in this scope
../src/odbc.cpp:910: error: expected primary-expression before '>' token
../src/odbc.cpp:910: error: expected primary-expression before ')' token
../src/odbc.cpp:918: error: expected primary-expression before '>' token
gyp ERR! System Linux 3.13.0-39-generic
gyp ERR! command "node" "/tmp/staged/app/vendor/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build" "--IBM_DB_HOME=/tmp/staged/app/clidriver" "--IBM_DB_HOME_WIN=%IBM_DB_HOME%" "--IS_DOWNLOADED=false"
gyp ERR! cwd /tmp/staged/app/node_modules/ibm_db
gyp ERR! node -v v0.10.38
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok
] killed: false, code: 1, signal: null }
> bson@0.2.22 install /tmp/staged/app/node_modules/mongodb/node_modules/bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)
make: Entering directory `/tmp/staged/app/node_modules/mongodb/node_modules/bson/build'
  CXX(target) Release/obj.target/bson/ext/bson.o
  SOLINK_MODULE(target) Release/obj.target/bson.node
  SOLINK_MODULE(target) Release/obj.target/bson.node: Finished
  COPY Release/bson.node
make: Leaving directory `/tmp/staged/app/node_modules/mongodb/node_modules/bson/build'
> bcrypt@0.8.3 install /tmp/staged/app/node_modules/node-red/node_modules/bcrypt
> node-gyp rebuild
make: Entering directory `/tmp/staged/app/node_modules/node-red/node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
  SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node
  SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node: Finished
  COPY Release/bcrypt_lib.node
make: Leaving directory `/tmp/staged/app/node_modules/node-red/node_modules/bcrypt/build'
> bufferutil@1.1.0 install /tmp/staged/app/node_modules/node-red/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

error, status code: 400, error code: 170004, message: App staging failed in the buildpack compile phase

**Comment by bimalkjha** [comment]
Please now again.

**Comment by bimalkjha** [comment]
Please check now again and confirm. It seems fixed with ibm_db@v0.0.13. Thanks.

**Comment by TanyRay** [comment]
I have new bunch of errors. Could you offer any idea how to quick fix this problem?

make: Leaving directory `/tmp/staged/app/node_modules/mongodb/node_modules/kerberos/build'
> ibm_db@0.0.13 install /tmp/staged/app/node_modules/ibm_db
> node installer/driverInstall.js
IBM_DB_HOME environment variable have already been set to /tmp/staged/app/clidriver
{ [Error: Command failed: Traceback (most recent call last):
  File "/tmp/staged/app/vendor/node/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 18, in <module>
    sys.exit(gyp.script_main())
  File "/tmp/staged/app/vendor/node/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 534, in script_main
    return main(sys.argv[1:])
  File "/tmp/staged/app/vendor/node/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 527, in main
    return gyp_main(args)
  File "/tmp/staged/app/vendor/node/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 503, in gyp_main
    options.circular_check)
  File "/tmp/staged/app/vendor/node/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 129, in Load
    params['parallel'], params['root_targets'])
  File "/tmp/staged/app/vendor/node/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2692, in Load
    variables, includes, depth, check, True)
  File "/tmp/staged/app/vendor/node/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 362, in LoadTargetBuildFile
    includes, True, check)
  File "/tmp/staged/app/vendor/node/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 239, in LoadOneBuildFile
    aux_data, variables, includes, check)
  File "/tmp/staged/app/vendor/node/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 277, in LoadBuildFileIncludesIntoDict
    False, check),
  File "/tmp/staged/app/vendor/node/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 219, in LoadOneBuildFile
    None)
  File "/home/vcap/.node-gyp/0.10.38/common.gypi", line 0
    ^
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/tmp/staged/app/vendor/node/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:462:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.13.0-39-generic
gyp ERR! command "node" "/tmp/staged/app/vendor/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build" "--IBM_DB_HOME=/tmp/staged/app/clidriver" "--IBM_DB_HOME_WIN=%IBM_DB_HOME%" "--IS_DOWNLOADED=false"
gyp ERR! cwd /tmp/staged/app/node_modules/ibm_db
gyp ERR! node -v v0.10.38
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok
] killed: false, code: 1, signal: null }
> bson@0.2.22 install /tmp/staged/app/node_modules/mongodb/node_modules/bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)
make: Entering directory `/tmp/staged/app/node_modules/mongodb/node_modules/bson/build'
  CXX(target) Release/obj.target/bson/ext/bson.o
  SOLINK_MODULE(target) Release/obj.target/bson.node
  SOLINK_MODULE(target) Release/obj.target/bson.node: Finished
  COPY Release/bson.node
make: Leaving directory `/tmp/staged/app/node_modules/mongodb/node_modules/bson/build'
> bcrypt@0.8.3 install /tmp/staged/app/node_modules/node-red/node_modules/bcrypt
> node-gyp rebuild
make: Entering directory `/tmp/staged/app/node_modules/node-red/node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
  SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node
  SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node: Finished
  COPY Release/bcrypt_lib.node
make: Leaving directory `/tmp/staged/app/node_modules/node-red/node_modules/bcrypt/build'
> utf-8-validate@1.1.0 install /tmp/staged/app/node_modules/node-red/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild
make: Entering directory `/tmp/staged/app/node_modules/node-red/node_modules/ws/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory `/tmp/staged/app/node_modules/node-red/node_modules/ws/node_modules/utf-8-validate/build'
> bufferutil@1.1.0 install /tmp/staged/app/node_modules/node-red/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild
make: Entering directory `/tmp/staged/app/node_modules/node-red/node_modules/ws/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
make: Leaving directory `/tmp/staged/app/node_modules/node-red/node_modules/ws/node_modules/bufferutil/build'
> serialport@1.7.4 install /tmp/staged/app/node_modules/node-red/node_modules/node-red-node-serialport/node_modules/serialport
> node-pre-gyp install --fallback-to-build
[serialport] Success: "/tmp/staged/app/node_modules/node-red/node_modules/node-red-node-serialport/node_modules/serialport/build/serialport/v1.7.4/Release/node-v11-linux-x64/serialport.node" is installed via remote
npm ERR! ibm_db@0.0.13 install: `node installer/driverInstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ibm_db@0.0.13 install script.
npm ERR! This is most likely a problem with the ibm_db package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node installer/driverInstall.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls ibm_db
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-39-generic
npm ERR! command "/tmp/staged/app/vendor/node/bin/node" "/tmp/staged/app/vendor/node/bin/npm" "install" "--unsafe-perm" "--quiet" "--userconfig" "/tmp/staged/app/.npmrc"
npm ERR! cwd /tmp/staged/app
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
Build failed
WARNING: Avoid checking node_modules into source control
 failed: Buildpack compilation step failed



error, status code: 400, error code: 170004, message: App staging failed in the buildpack compile phase

**Comment by bimalkjha** [comment]
Please run the command `npm install ibm_db` and share its output.

**Comment by TanyRay** [comment]
Thank you a lot. It works now.
