### ISSUE TITLE
ODBC CLI tar.gz files are not reachable

### ISSUE THREAD

**Issue by RabeaWahab** [ibmdb/node-ibm_db#470]
[https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/](https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/ ) content is not reachable ?

**Comment by dexdexdex** [comment]
Yeah I see the same on my builds, public.dhe.ibm.com dies so we see stuff like this:

[Linux Build] 
100.00% | 536 bytes downloaded out of 536 bytes.{ Error: incorrect header check
[Linux Build]     at Zlib._handle.onerror (zlib.js:371:17) errno: -3, code: 'Z_DATA_ERROR' }
[Linux Build] npm WARN tslint@5.11.0 requires a peer of typescript@>=2.1.0 || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev || >=2.4.0-dev || >=2.5.0-dev || >=2.6.0-dev || >=2.7.0-dev || >=2.8.0-dev || >=2.9.0-dev but none is installed. You must install peer dependencies yourself.

This has happened to us often enough that we ended up developing a separate ibm_db repository clone that has the binaries already downloaded (so we never end up having to go to public_dhe). I guess if there are really desperate souls out there that just want to get their builds going I can share my really janky repo?

**Comment by rickdesantis** [comment]
Still not working. A quick search on the issues here shows that that binary repository is at least unreliable.

Please consider adding some mirrors or something like that. This is frankly unacceptable for the only package available for using IBM DB2 databases via Node.

**Comment by StefanDoersam** [comment]
Still not working
 ibm_db2@3.0.0 install /home/travis/build/CMS/sap-customer-api/node_modules/ibm_db2

> node installer/driverInstall.js

Downloading DB2 ODBC CLI Driver from https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz...

100.00% | 536 bytes downloaded out of 536 bytes.{ Error: incorrect header check

    at Gunzip.zlibOnError (zlib.js:153:15) errno: -3, code: 'Z_DATA_ERROR' }

**Comment by rickdesantis** [comment]
You can also try downloading that file directly:

```bash
curl https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/macos64_odbc_cli.tar.gz
```

this is what you'll get:

```html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator,
 you@your.address and inform them of the time the error occurred,
and anything you might have done that may have
caused the error.</p>
<p>More information about this error may be available
in the server error log.</p>
</body></html>
```

same thing goes for the linux version.

**Comment by csantanapr** [comment]
This is critical affecting IBM Cloud Functions runtime pipelines both nodejs and python.
```
> ibm_db@2.4.1 install /node_modules/ibm_db
> node installer/driverInstall.js
Downloading DB2 ODBC CLI Driver from https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz...
100.00% | 536 bytes downloaded out of 536 bytes.{ Error: incorrect header check
    at Gunzip.zlibOnError (zlib.js:153:15) errno: -3, code: 'Z_DATA_ERROR' }
npm WARN marked-terminal@2.0.0 requires a peer of marked@^0.3.6 but none is installed. You must install peer dependencies yourself.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ibm_db@2.4.1 install: `node installer/driverInstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ibm_db@2.4.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
It also affects python by the way 😢 
```
Downloading https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-4rqrzt32/ibm-db/setup.py", line 164, in <module>
        file_stream = BytesIO(request.urlopen(url).read())
      File "/usr/local/lib/python3.6/urllib/request.py", line 223, in urlopen
        return opener.open(url, data, timeout)
      File "/usr/local/lib/python3.6/urllib/request.py", line 532, in open
        response = meth(req, response)
      File "/usr/local/lib/python3.6/urllib/request.py", line 642, in http_response
        'http', request, response, code, msg, hdrs)
      File "/usr/local/lib/python3.6/urllib/request.py", line 570, in error
        return self._call_chain(*args)
      File "/usr/local/lib/python3.6/urllib/request.py", line 504, in _call_chain
        result = func(*args)
      File "/usr/local/lib/python3.6/urllib/request.py", line 650, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 500: Internal Server Error
```

Please fix ASAP

**Comment by rickdesantis** [comment]
There's a temporary fix here if you already have the driver installed somewhere else (I don't).

https://github.com/ibmdb/python-ibmdb/issues/350

**Comment by rhtpandeyIN** [comment]
Hi, this URL is hosted by IBM and I think their site was down because of some technical reasons/maintenance.
Well, you can easily by-pass this URL by using below environment variables, please check the below attached link.
[environment variables details](https://github.com/ibmdb/node-ibm_db#important-environment-variables-and-download-essentials).

>This has happened to us often enough that we ended up developing a separate ibm_db repository clone that has the binaries already downloaded (so we never end up having to go to public_dhe). I guess if there are really desperate souls out there that just want to get their builds going I can share my really janky repo?

Well, actually you don't need to do that, you can use the original ibm_db repository and once you have successfully downloaded "clidriver" from "public.dhe..." URL then just follow the instructions (regarding use of env variables) already provided in README doc. 

>Please consider adding some mirrors or something like that. This is frankly unacceptable for the only package available for using IBM DB2 databases via Node.

If we keep getting this request from customers then surely we will take action into this regard, but still that issue is sometimes network related or related to downtime, same can happen to other URL's as well.
I would suggest please go through above mentioned URL and you will get more clarity, you can even host the same files into your own URL and you just need to set the `IBM_DB_INSTALLER_URL` env variable with your hosting URL as value.

**Comment by rickdesantis** [comment]
It seems to be working again now.

**Comment by RabeaWahab** [comment]
Would it help to host a mirror on a public CDN like Cloudflare's ?

**Comment by rhtpandeyIN** [comment]
>Would it help to host a mirror on a public CDN like Cloudflare's ?

Well, for your own use you can put these files into your private hosting space, I am not sure about the legal aspect of putting it on public domain. Yet, it is available to download but it's coming from the official source. Before putting it on a public URL and then give that URL as a mirror option(which is unofficial) I would first check the legal terms. 

Still, I can check this with our executives and legal team, if that's fine then surely you can do it.

Well, closing the issue for now, as it is not an issue with node-ibm_db, it's related to hosting site maintenance downtime.

**Comment by kadampritee** [comment]
please anyone help me, to find how to download IBM db2 ODBC cli tar.gz files

**Comment by bimalkjha** [comment]
@kadampritee Just click on this link and download the tar.gz file as per your Operating System: https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/
But, anyway you need not to download it. You just need to run `npm install ibm_db` and `ibm_db` automatically downloads it as per the platform on which it is getting installed.
If you are facing any other issue, please open a new issue as it is closed. Thanks.
