### ISSUE TITLE
UTF-8 Encoding for SQL queries

### ISSUE THREAD

**Issue by joetex** [ibmdb/node-ibm_db#471]
Hello, 
We are trying to use insert/update/select statements using Prepare and Execute/ExecuteNonQuery.

It seems there is an issue sending UTF-8 encoded characters to SQL. 

In NodeJS, we see this:
0A004G/1.1/es/TEST0A004SL_Introducción_a_IBM_SPSS_Modeler_and_Data_Mining_(v15).pdf

In DB2, however, we see this:
0A004G/1.1/es/TEST0A004SL_IntroducciÃ³n_a_IBM_SPSS_Modeler_and_Data_Mining_(v15).pdf

If you notice, the UTF-8 character 'ó' was split into two byte characters 'Ã³' when inserted to DB2. 

I am unsure how I am suppose to set the values for the prepare statement. Do I need to encode/decode or something before adding my values?  We need DB2 to show the UTF-8 character 'ó'.

**Comment by bimalkjha** [comment]
@joetex I am unable to access `TEST0A004SL_Introducción_a_IBM_SPSS_Modeler_and_Data_Mining_(v15).pdf` so it would be good if you can paste the content here. 
For unicode chars, If your database is created using `codeset utf-8`, I would suggest to set environment variable DB2CODEPAGE=1208 on non-windows and 1252 on windows in the system where ibm_db is installed and restart your application. Thanks.

**Comment by joetex** [comment]
@bimalkjha the codepage in our DB2 server (Linux) is 1208, I also tried on windows where I run the nodejs app:
set DBCODEPAGE=1208
But it doesn't seem to do anything.  
This seems to be interpreted wrong on ibm_db, as I have tried converting it to utf16 with no luck.  
I noticed there is some configuration in the gyp file, but how do I modify that for ibm_db if it's a remote package?

**Comment by bimalkjha** [comment]
Please share the codepage of your database and value of LANG env var if set. Thanks.

**Comment by joetex** [comment]
$ db2 get db cfg | grep code
 Database code page                                      = 1208
 Database code set                                       = UTF-8
 Database country/region code                            = 1

$ echo $LANG
en_US.UTF-8

**Comment by bimalkjha** [comment]
@joetex Please set LANG and CODEPAGE value in client system too where ibm_db is installed as below:
```
export LANG=en_US.UTF-8
export DB2CODEPAGE=1208
```
Thanks.

**Comment by bimalkjha** [comment]
@joetex Also, if possible, please share some small test program to reproduce the issue. You can run `ibm_db/test/test-basic-test.js` file which has used unicode characters. Thanks.

**Comment by robertpburgess** [comment]
We had essentially the same problem using the ibm_db module in an application running on Linux.  Setting the environment variable DB2CODEPAGE=1208 as mentioned above resolved the issue.  Would it be possible for the ibm_db module to default to that?

**Comment by lwf804** [comment]
@bimalkjha I have same problem on ubuntu.
I set:
```
DB2CODEPAGE=1208
LANG=en_US.UTF-8
```
But i insert jp text, still error?

**Comment by bimalkjha** [comment]
We need to set DB2CODEPAGE=1208 only if required or suggested by support. So, we can not set it by default in ibm_db module. It many cause unexpected behavior is some OS and some application. If required, yo can set it in your application before loading ibm_db as below:
```
process.env.DB2CODEPAGE = process.env.DB2CODEPAGE || 1208;
```
Below links provide good info about it:
https://www-01.ibm.com/support/docview.wss?uid=swg21601028
https://dba.stackexchange.com/questions/206145/db2-on-windows-fix-encoding-in-db2cmd-and-for-jdbc
Thanks.

**Comment by xuanzhaopeng** [comment]
Setting environment variable like this in Client system where ibm_db installed solved issue
```
process.env.DB2CODEPAGE = process.env.DB2CODEPAGE || 1208;
```

Thanks a lot @bimaljha ,  you saved me to!
