### ISSUE TITLE
Installation failure on mac

### ISSUE THREAD

**Issue by giucesar** [ibmdb/node-ibm_db#472]
[ibm_db_install.log](https://github.com/ibmdb/node-ibm_db/files/2522067/ibm_db_install.log)
The package fails to install in OSX. After the successful download of the ODBC CLI driver, it fails to install with the error message **SyntaxError: invalid syntax**. Log attached.

**Comment by markusdanek** [comment]
Try to install the package with another Node.js version.

**Comment by giucesar** [comment]
Thanks.
I figured it out:
1) Install the ODBC CLI manually
2) set IBM_HOME_DB to the cli folder
3) set PYTHON to a python 2.7 binary
4) Use Node 8.x
