### ISSUE TITLE
Issue while reading accent characters such as -  (é)

### ISSUE THREAD

**Issue by simararneja** [ibmdb/node-ibm_db#473]
While reading data from db2  on a linux machine, the response object shows -  

**"Povolo Vicepresidente II Novedades LA C�MARA NACIONAL DE APELACIONES EN LO PENAL ECON�MICO "** 
whereas the db contains this -

###  "Povolo Vicepresidente II Novedades LA CÁMARA NACIONAL DE APELACIONES EN LO PENAL ECONÓMICO"

Node version - 8.12
node-ibm_db - 2.4
Ubuntu 16.04 (docker)
DB2 version: 10.1.3

Whereas, When i run the same piece of code on MACOS it works fine and the string are read as they are in the database.

**Comment by bimalkjha** [comment]
@simararneja On linux, run `export DB2CODEPAGE=1208` and then run your test program. Thanks.

**Comment by simararneja** [comment]
@bimalkjha Thanks for the response. 

Assuming this command is supposed to be executed on a linux machine where node is installed. I executed this and restarted my node test and still got the same issue.

**Comment by simararneja** [comment]
@bimalkjha Thanks for the solution. It worked fine. `run export DB2CODEPAGE=1208`
