### ISSUE TITLE
 SQL30081N - Connection drop issue

### ISSUE THREAD

**Issue by asoj1987** [ibmdb/node-ibm_db#474]
Hi, 
We are getting the below error when trying to connect to DB2 after a short period.
 _Error: [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: \"TCP/IP\".  Communication API being used: \"SOCKETS\".  Location where the error was detected: \"148.171.100.20\".  Communication function detecting the error: \"recv\".  Protocol specific error code(s): \"104\", \"*\", \"0\".  SQLSTATE=08001\n",_

I have gone through the solutions you recommended to configure the db2dsdriver.cfg with connection details.
https://github.com/ibmdb/node-ibm_db/issues/327
https://github.com/ibmdb/node-ibm_db/issues/460

The issue I am having is, The way my infra/setup work doesn't allow me to edit the node modules code as it is downloaded in real time from my company's internal repo during deployment. So I am unable to take the changes in db2dsdriver.cfg to Prod.

Is there any way I can write this auto connect logic in my application js file where I have all the code for connection pooling.

See below.

const ibmdb = require("ibm_db");
const db2config = require("../config/db2Config.js");
const connString = db2config.db2SPConfig.dB2ConnectionString;
ibmdb.debug(true);

let Pool = require("ibm_db").Pool,
pool = new Pool(),
cString = connString;

let ret = pool.init(20, cString);
if (ret != true) {
return false;
}
pool.setMaxPoolSize(50);

exports.callDB2 = async (query, SPRequest) => {
try {
pool.open(cString, function (err, conn) {
if (err) {
return err;
}
else {
conn.query(query, SPRequest, function (err, data) {
if (err) {
console.log("Error while calling the Stored Proc");
conn.close(function () {
console.log("conn closed");
})
return err;
} else {
console.log("DB2 Stored Proc call successful");
conn.close(function () {
console.log("conn returned to pool");
});
return data;
}
});

        }
    });
} catch (error) {
    throw error;
}
};

**Comment by bimalkjha** [comment]
@asoj1987 Please share how frequently you face this issue. Do you see this problem when you reconnect within 30 min also? Please share the platform where ibm_db is used and db2 server is installed. Need to check database configuration to know is there any activity from server side to drop the connection so frequently?
The db2dsdriver.cfg file is read to reconnect by clidriver driver. At ibm_db level, implementation of reconnect logic is very difficult. You can try to check the return code from query api is -30081 or not and in case of -30081, write logic to reconnect.
You can have pre-configured db2dsdriver.cfg file and have code in deployment script to copy this file under ibm_db once ibm_db is deployed. Hope this idea could work. Thanks.

**Comment by asoj1987** [comment]
Thanks Bimal for the details. I am working with DBA and now we have concerns that the ID and password to connect to DB2 is stored in the config file. 
Could you please check the below questions.
1. We have 3 different regions E1,E2 and E3 and different ID and passwords to connect to these regions. These credentials are passed to the application in real time by the consumer app. so I cannot hardcode it in the db2dsdriver.cfg file. How so I input these to db2dsdriver.cfg  from the app without hardcoding ?
2. How can I maintain one db2dsdriver.cfg file and setup it for different environments which has different credentials and database settings ?

**Comment by bimalkjha** [comment]
1. No need to store ID and password in cfg file. You can have cfg file without userid and passwd parameters and keep all other parameters in cfg file. credentials can be provided by application in connection string with dsn name.
2. one db2dsdriver.cfg file can store N number of database information and similarly ACR section can be configured for each database. that is single cfg file with connection information of all regions except the userid and passwd. E1, E2, E3 will have different dsn aliases in the cfg file and automatic client reroute should be configured accordingly. In db2dsdriver.cfg file, we can have multiple unique dsn alias section under <dsncollection> tag. Similarly, we can have multiple <database> under <databases> tag. You need to have 3 <database> sections. Every <database> will have their own <acr> and <alternateserverlist> sections.
Please check [this](https://www.ibm.com/support/knowledgecenter/en/SSEPGG_11.1.0/com.ibm.db2.luw.apdv.cli.doc/doc/c0056196.html) link and other related links on this page for more info. Thanks.

**Comment by asoj1987** [comment]
Thanks Bimal.
1. currently we have the connection string as the below to take the values from db2dsdriver.cfg
    const ID = 'ABC';
    const PW ='123';
    const cString = "dsn=DSNE1";  // where DSNE1 is my E1 DSN name present in  db2dsdriver.cfg
     
How do I add the ID and PW to the cString ?

**2.  does the below db2dsdriver.cfg file looks good ?**

<configuration>  
  <dsncollection>    
    <dsn alias="DSNE1" name="E1DB1" host="E1DB1.app.xyz.com" port="123"/>
    <dsn alias="DSNE2" name="E2DB1" host="E2DB1.app.xyz.com" port="123"/> 
    <dsn alias="DSNE3" name="E3DB1" host="E3DB1.app.xyz.com" port="123"/>    
  </dsncollection>  
  <databases>    
    <database name="E1DB" host="E1DB1.app.xyz.com" port="123">      
      <acr>        
        <parameter name="enableAcr" value="true"/>        
        <parameter name="maxAcrRetries" value="10"/>       
        <parameter name="acrRetryInterval" value="5"/>        
        <parameter name="enableAlternateServerListFirstConnect" value="true"/>       
        <alternateserverlist>           
          <server name="E1fallbackServer" hostname="E1DB2.app.xyz.com" port="446"/>                   
        </alternateserverlist>   
      </acr>    
    </database> 
    <database name="E2DB" host="E2DB1.app.xyz.com" port="123">      
      <acr>        
        <parameter name="enableAcr" value="true"/>        
        <parameter name="maxAcrRetries" value="10"/>       
        <parameter name="acrRetryInterval" value="5"/>        
        <parameter name="enableAlternateServerListFirstConnect" value="true"/>       
        <alternateserverlist>           
          <server name="E2fallbackServer" hostname="E2DB2.app.xyz.com" port="446"/>                   
        </alternateserverlist>   
      </acr>    
    </database>  
    <database name="E3DB" host="E3DB1.app.xyz.com" port="123">      
      <acr>        
        <parameter name="enableAcr" value="true"/>        
        <parameter name="maxAcrRetries" value="10"/>       
        <parameter name="acrRetryInterval" value="5"/>        
        <parameter name="enableAlternateServerListFirstConnect" value="true"/>       
        <alternateserverlist>           
          <server name="E3fallbackServer" hostname="E3DB2.app.xyz.com" port="446"/>                   
        </alternateserverlist>   
      </acr>    
    </database>   
  </databases>
</configuration>

**Comment by bimalkjha** [comment]
@asoj1987 1. You need to use `const cString = "dsn=DSNE1;UID=" + ID + ";PWD=" + PW;`
2. The shared db2dsdriver.cfg file is not good. Seems you have not referred [this](https://github.com/ibmdb/node-ibm_db/issues/270#issuecomment-311171336) comment. 
* The value of name under \<database\> section should match with the value of name under \<dsn\> section.
* There should be at lease two servers under \<alternateserverlist\>.
* The \<affinitylist\> was missing.

I have updated the db2dsdriver.cfg file to correct it. Please find the attached db2dsdriver.txt file.
[db2dsdriver.txt](https://github.com/ibmdb/node-ibm_db/files/2554742/db2dsdriver.txt)

We can verify the contents of db2dsdriver.cfg file by using `db2cli validate -dsn <dsn_name>` command. You can find the `db2cli` executable under `ibm_db\installer\clidriver\bin` folder. Thanks.
