### ISSUE TITLE
GSKit command line tool

### ISSUE THREAD

**Issue by derekpollock** [ibmdb/node-ibm_db#475]
Hi,
Please can you advise where you can download the GSKit command line tool?

I'm looking to use this to create a KeyStore DB as referred to in following documentation:
https://github.com/ibmdb/node-ibm_db/blob/master/APIDocumentation.md#openApi

Thanks,
Derek

**Comment by bimalkjha** [comment]
@derekpollock You can download IBM Global Security Toolkit version 8.0.50.79 or later from IBM Support website or IBM Fix Central. GSKit installer is platform dependent so, based on your platform, please download it from here: [https://www-945.ibm.com/support/fixcentral/swg/selectFixes?parent=Security+Systems&product=ibm/Tivoli/IBM+Global+Security+Kit&release=All&platform=All&function=fixId&fixids=8.0.*&source=fc](https://www-945.ibm.com/support/fixcentral/swg/selectFixes?parent=Security+Systems&product=ibm/Tivoli/IBM+Global+Security+Kit&release=All&platform=All&function=fixId&fixids=8.0.*&source=fc). Thanks.
