### ISSUE TITLE
v2.4.1 - Windows 10 - Double-Byte Characters

### ISSUE THREAD

**Issue by Withnail73** [ibmdb/node-ibm_db#476]
Hiya... we're seeing issues with languages such as Japanese, Mandarin, Russian etc.  When viewing the data via DBeaver I can clearly see it rendered correctly, but when running inside Node app the data is pulled as squares and sent to the browser this way.  

I haven't tried saving data in these languages yet... will confirm back.

**Comment by cuzzlor** [comment]
Try setting environment variable DB2CODEPAGE=1208 - worked for us.

**Comment by lx171717** [comment]
> 
> 
> Try setting environment variable DB2CODEPAGE=1208 - worked for us.

can you tell how  to do it ?

**Comment by PriyankaManoharan04** [comment]
@lx171717 

> can you tell how to do it ?

on your command prompt type command `set DB2CODEPAGE=1208`  before you execute your program.Thanks

**Comment by bimalkjha** [comment]
https://github.com/ibmdb/node-ibm_db/issues/471#issuecomment-485379345
