### ISSUE TITLE
Open DB2 instance ERROR because of ";" in password

### ISSUE THREAD

**Issue by vtrinkl** [ibmdb/node-ibm_db#480]
Hi, 

I am using the module and want to connect to a db2 instance with:
ibmdb.open("DATABASE=<dbname>;HOSTNAME=<myhost>;UID=db2user;PWD=password;PORT=<dbport>;PROTOCOL=TCPIP", function() ....

Problem now is:
If I have a ";" in the password it will not work because the information is separated by a ";" and it will cut the password.

Is this a bug and can anybody help here?

Thank you in advance.

**Comment by bimalkjha** [comment]
@vtrinkl Its not a bug. You should not use semicolon in password as semicolon in used as keyword seperator in the connection string. The IBM ODBC driver do not support password in connection string and hence the ibm_db driver too. This limitation is documented [here](https://www.ibm.com/support/knowledgecenter/en/SSEPGG_11.1.0/com.ibm.swg.im.dbclient.install.doc/doc/c0060749.html): `The ; character, ASCII code 0x3b, is not supported for use in passwords.`. Thanks.
