### ISSUE TITLE
ApiDocumentation.md refactor

### ISSUE THREAD

**Issue by mvarrieur** [ibmdb/node-ibm_db#487]
@bimalkjha As you mentioned in #477 the links stopped working after I refactored. I believe right now it is due to capital letters getting lowercased when github generates the `user-content-` tags. The links were not previously working either, and it seems maybe the github flavored markdown has changed again.

There are two options to change these links into working links:

1) Change all links to point to lowercase versions `[.open(connectionString, [options,] callback)](#user-content-openapi)`
2) Change all links to use github generated anchors `[.open(connectionString, [options,] callback)](#-1-openconnectionstring-options-callback)`

I think probably #1 is nicer so we don't need to change all the links if the title changes. But I don't know that the github flavored markdown interpreter isn't going to change again to go back to respecting case sensitivity. I can do number 1 AND lowercase all the name tags and add matching ID tags to hopefully guard against this a bit? Let me know what you think.

**Comment by bimalkjha** [comment]
@mvarrieur Somehow I am not convinced that the links were not working previously either. It was working fine with all released version and whenever we change links, we test that it is working fine.
Please open https://github.com/ibmdb/node-ibm_db/blob/e727f1a2c9f6dd5ad7d8f5b933713c947399cc07/APIDocumentation.md and try to click on any link. It is working fine. If it is not working for you, please let me know your browser. I have checked with few colleagues too and it is working for them. When I click on fetchSyncApi, I am able to see it is going on link https://github.com/ibmdb/node-ibm_db/blob/e727f1a2c9f6dd5ad7d8f5b933713c947399cc07/APIDocumentation.md#fetchSyncApi and able to see the expected result. In your case, url changes but no effect on page. 
So, I would suggest to restore the older links using another pull request asap. Thanks.

**Comment by bimalkjha** [comment]
I have reverted the changes. If it is not working for you, please check your settings. Now it works fine for us on mac and windows in firefox and chrome. Thanks.
