### ISSUE TITLE
Can't install successfully

### ISSUE THREAD

**Issue by ju4nkA** [ibmdb/node-ibm_db#49]
Hi.
I'm trying to install the library.
I'm download a driver from https://www-01.ibm.com/marketing/iwm/iwm/web/reg/download.do?source=swg-idsdpds&lang=en_US&S_PKG=li_ip64&cp=UTF-8 (the name of the file is ibm_data_server_driver_package_linuxppc64_v10.5.tar.gz).
After download I run the command ./installDSdriver
Then I run the command export IBM_DB_HOME=/home/juan/dsdriver
By last I'm run npm install ibm_db --save and getting the next message:

\> ibm_db@0.0.13 install /home/juan/node/prueba_db2_1/node_modules/ibm_db
\> node installer/driverInstall.js

IBM_DB_HOME environment variable have already been set to /home/juan/dsdriver
make: Entering directory '/home/juan/node/prueba_db2_1/node_modules/ibm_db/build'
  CXX(target) Release/obj.target/odbc_bindings/src/odbc.o
  CXX(target) Release/obj.target/odbc_bindings/src/odbc_connection.o
  CXX(target) Release/obj.target/odbc_bindings/src/odbc_statement.o
  CXX(target) Release/obj.target/odbc_bindings/src/odbc_result.o
  CXX(target) Release/obj.target/odbc_bindings/src/dynodbc.o
  SOLINK_MODULE(target) Release/obj.target/odbc_bindings.node
odbc_bindings.target.mk:126: recipe for target 'Release/obj.target/odbc_bindings.node' failed
make: Leaving directory '/home/juan/node/prueba_db2_1/node_modules/ibm_db/build'

{ \[Error: Command failed: ../src/odbc_connection.cpp: In static member function ‘static void ODBCConnection::UV_Open(uv_work_t*)’:
../src/odbc_connection.cpp:239:19: warning: cast to pointer from integer of different size \[-Wint-to-pointer-cast]
       (SQLPOINTER)timeOut,    //ValuePtr
                   ^
../src/odbc_connection.cpp: In static member function ‘static v8::Handle<v8::Value> ODBCConnection::OpenSync(const v8::Arguments&)’:
../src/odbc_connection.cpp:365:19: warning: cast to pointer from integer of different size \[-Wint-to-pointer-cast]
       (SQLPOINTER)timeOut,    //ValuePtr
                   ^
../src/odbc_connection.cpp: In static member function ‘static v8::Handle<v8::Value> ODBCConnection::Query(const v8::Arguments&)’:
../src/odbc_connection.cpp:758:21: warning: variable ‘optionNoResultsKey’ set but not used \[-Wunused-but-set-variable]
       Local<String> optionNoResultsKey = NanNew(OPTION_NORESULTS);
                     ^
/usr/bin/ld: se salta el /home/juan/dsdriver/lib/libdb2.so incompatible mientras se busca -ldb2
/usr/bin/ld: no se puede encontrar -ldb2
collect2: error: ld returned 1 exit status
make: *** [Release/obj.target/odbc_bindings.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build" "--IBM_DB_HOME=/home/juan/dsdriver" "--IBM_DB_HOME_WIN=%IBM_DB_HOME%" "--IS_DOWNLOADED=false"
gyp ERR! cwd /home/juan/node/prueba_db2_1/node_modules/ibm_db
gyp ERR! node -v v0.10.32
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
] killed: false, code: 1, signal: null }

npm ERR! ibm_db@0.0.13 install: `node installer/driverInstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ibm_db@0.0.13 install script.
npm ERR! This is most likely a problem with the ibm_db package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node installer/driverInstall.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls ibm_db
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "ibm_db" "--save"
npm ERR! cwd /home/juan/node/prueba_db2_1
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

I'm working on a Debian Jessie 64 bits.
Wish you can help me.

**Comment by bimalkjha** [comment]
Currently, ibm_db is not supported on linuxppc64 client.

**Comment by ju4nkA** [comment]
Thx for your answer.
Did you know wich one I have to download and install? I'm missing something and I don't know what it is.

**Comment by ju4nkA** [comment]
Ok. I was able to install successfully. Thx for your answer bimalkjha. With that and a little googling I can do it finally.
It was almost a silly issue, sorry for that ;).
I install downloading from this link, to anyone that have the same mistake than me.
https://www-01.ibm.com/marketing/iwm/iwm/web/reg/download.do?source=swg-idsdpds&lang=en_US&S_PKG=li&cp=UTF-8&dlmethod=http
