### ISSUE TITLE
IBM Power i Install Issues

### ISSUE THREAD

**Issue by rcronin** [ibmdb/node-ibm_db#490]
Cannot get this installed on the power platform. Running into this issue...

stack     at getNotFoundError (/QOpenSys/pkgs/lib/nodejs8/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/QOpenSys/pkgs/lib/nodejs8/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/QOpenSys/pkgs/lib/nodejs8/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /QOpenSys/pkgs/lib/nodejs8/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /QOpenSys/pkgs/lib/nodejs8/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /QOpenSys/pkgs/lib/nodejs8/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System OS400 7.3
gyp ERR! command "/QOpenSys/pkgs/lib/nodejs8/bin/node" "/QOpenSys/pkgs/lib/nodejs8/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build" "--IS_DOWNLOADED=true" "--IBM_DB_HOME=/node_modules/ibm_db/installer/clidriver"
gyp ERR! cwd /node_modules/ibm_db
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

    at ChildProcess.exithandler (child_process.js:276:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Socket.stream.socket.on (internal/child_process.js:336:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:561:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node-gyp configure build  --IS_DOWNLOADED=true --IBM_DB_HOME="$IBM_DB_HOME"' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ibm_db@2.4.1 install: `node installer/driverInstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ibm_db@2.4.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/RCRONIN/.npm/_logs/2018-12-03T16_01_49_725Z-debug.log

**Comment by rhtpandeyIN** [comment]
Hi @rcronin ,
Please provide the full error log/output. Also, share the installation steps.

**Comment by rcronin** [comment]
npm install ibm_db2
                                                                                                                        ode_modules/sax
> ibm_db2@3.0.0 install /QOpenSys/pkgs/bin/node_modules/ibm_db2
> node installer/driverInstall.js

Downloading DB2 ODBC CLI Driver from https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/aix64_odbc_cli.tar.gz...

100.00% | 33216109 bytes downloaded out of 33216109 bytes.

****************************************
You are downloading a package which includes the Node.js module for IBM DB2/Informix.  The module is licensed under the Apache License 2.0. The package also includes IBM ODBC and CLI Driver from IBM, which is automatically downloaded as the node module is installed on your system/device. The license agreement to the IBM ODBC and CLI Driver is available in undefined   Check for additional dependencies, which may come with their own license agreement(s). Your use of the components of the package and dependencies constitutes your acceptance of their respective license agreements. If you do not accept the terms of any license agreement(s), then delete the relevant component(s) from your device.
****************************************

Downloading and extraction of DB2 ODBC CLI Driver completed successfully ...


{ Error: Command failed: node-gyp configure build  --IS_DOWNLOADED=true --IBM_DB_HOME="$IBM_DB_HOME"
gyp ERR! build error
gyp ERR! stack Error: not found: gmake
gyp ERR! stack     at getNotFoundError (/QOpenSys/pkgs/lib/nodejs8/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/QOpenSys/pkgs/lib/nodejs8/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/QOpenSys/pkgs/lib/nodejs8/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /QOpenSys/pkgs/lib/nodejs8/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /QOpenSys/pkgs/lib/nodejs8/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /QOpenSys/pkgs/lib/nodejs8/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System OS400 7.3
gyp ERR! command "/QOpenSys/pkgs/lib/nodejs8/bin/node" "/QOpenSys/pkgs/lib/nodejs8/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build" "--IS_DOWNLOADED=true" "--IBM_DB_HOME=/QOpenSys/pkgs/bin/node_modules/ibm_db2/installer/clidriver"
gyp ERR! cwd /QOpenSys/pkgs/bin/node_modules/ibm_db2
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

    at ChildProcess.exithandler (child_process.js:276:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Socket.stream.socket.on (internal/child_process.js:336:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:561:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node-gyp configure build  --IS_DOWNLOADED=true --IBM_DB_HOME="$IBM_DB_HOME"' }
npm WARN enoent ENOENT: no such file or directory, open '/QOpenSys/pkgs/bin/package.json'
npm WARN bin No description
npm WARN bin No repository field.
npm WARN bin No README data
npm WARN bin No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"aix","arch":"ppc64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ibm_db2@3.0.0 install: `node installer/driverInstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ibm_db2@3.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/RCRONIN/.npm/_logs/2018-12-03T16_13_39_275Z-debug.log

[2018-12-03T16_13_39_275Z-debug.log](https://github.com/ibmdb/node-ibm_db/files/2640477/2018-12-03T16_13_39_275Z-debug.log)

I believe I have all the prereqs installed. Installed via npm install ibm_db

**Comment by bimalkjha** [comment]
@rcronin Seems you are not installing ibm_db. The command `npm install ibm_db2` installs ibm_db2 which is not this package. `ibm_db` is correct package which get installed using `npm i ibm_db`. 
Second thing is you are trying to install ibm_db on AS400 which is not a supported platform for ibm_db. Please see documentation. Yes, using ibm_db, you can connect to a remote i-Series server from distributed platform, but you can not install ibm_db on i-Series. 
But, still you can try installing it on i-Series by setting IBM_DB_HOME env var to the install folder of database server like sqllib and run `npm i ibm_db`. For any issue or more info,  please contact AS400 server team. I am closing the issue as i-Series is not a supported platform for ibm_db. Thanks.
