### ISSUE TITLE
Error: Module Version mismatch. Expected 64, got 67

### ISSUE THREAD

**Issue by alenaSchmickl** [ibmdb/node-ibm_db#493]
When using the most recent package version I receive an error about a version mismatch with my node version. 

Error: The package was compiled against a different Node.js version using NODE_MODULE_VERSION 67. This version of Node.js requires NODE_MODULE_VERSION 64.

I am using node 10.14.1

Is there  a way to use support for Node v10? Thank you :)

**Comment by bimalkjha** [comment]
@alenaSchmickl Please remove the existing ibm_db directory and reinstall using `npm intall ibm_db`. Still getting error, check your package.json to make sure it has 2.5.0 version. If you see issue with 2.5.0 too, then please share the complete output of `npm i ibm_db` command. Thanks.

**Comment by alenaSchmickl** [comment]
Hi @bimalkjha I reinstalled ibm_db as suggested by you. The installed version is 2.5.0. I receive the following output with an error for node-gyp build

C:\Users\repo>npm install ibm_db

> ibm_db@2.5.0 install C:\Users\repo\node_modules\ibm_db
> node installer/driverInstall.js

Downloading DB2 ODBC CLI Driver from https://public.dhe.ibm.com/ibmdl/export/pub
/software/data/db2/drivers/odbc_cli/ntx64_odbc_cli.zip...

100.00% | 22570684 bytes downloaded out of 22570684 bytes.

****************************************
You are downloading a package which includes the Node.js module for IBM DB2/Info
rmix.  The module is licensed under the Apache License 2.0. The package also inc
ludes IBM ODBC and CLI Driver from IBM, which is automatically downloaded as the
 node module is installed on your system/device. The license agreement to the IB
M ODBC and CLI Driver is available in undefined   Check for additional dependenc
ies, which may come with their own license agreement(s). Your use of the compone
nts of the package and dependencies constitutes your acceptance of their respect
ive license agreements. If you do not accept the terms of any license agreement(
s), then delete the relevant component(s) from your device.
****************************************

Downloading and extraction of DB2 ODBC CLI Driver completed successfully...


C:\Users\Y086866\git-repos\watson.generali\10_1 KlassifikationsTool\node_modules
\ibm_db>if not defined npm_config_node_gyp (node "C:\Users\Y086866\AppData\Roami
ng\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modu
les\node-gyp\bin\node-gyp.js" configure build  --IS_DOWNLOADED=true --IBM_DB_HOM
E=$IBM_DB_HOME )  else (node "node C:\Users\Y086866\AppData\Roaming\npm\node_mod
ules\node-gyp\bin\node-gyp.js" configure build  --IS_DOWNLOADED=true --IBM_DB_HO
ME=$IBM_DB_HOME )

{ Error: Command failed: node-gyp configure build  --IS_DOWNLOADED=true --IBM_DB
_HOME=$IBM_DB_HOME
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module 'C:\Users\reponode_modules\ibm_db\node C:\Users\Y086866\AppData\Roaming\npm\nod
e_modules\node-gyp\bin\node-gyp.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)

    at ChildProcess.exithandler (child_process.js:289:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   'node-gyp configure build  --IS_DOWNLOADED=true --IBM_DB_HOME=$IBM_DB_HOME' }


node-gyp build process failed!

Proceeding with Pre-compiled Binary Installation.


===================================
node-ibm_db installed successfully!
===================================

npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed.
 You must install peer dependencies yourself.
npm WARN bootstrap@4.1.3 requires a peer of jquery@1.9.1 - 3 but none is install
ed. You must install peer dependencies yourself.
npm WARN bootstrap@4.1.3 requires a peer of popper.js@^1.14.3 but none is instal
led. You must install peer dependencies yourself.
npm WARN karma-jasmine-html-reporter@1.1.0 requires a peer of jasmine@>=3 but no
ne is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fse
vents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)

+ ibm_db@2.5.0
added 18 packages from 39 contributors and audited 27877 packages in 36.759s
found 15 vulnerabilities (1 low, 10 moderate, 4 high)
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by bimalkjha** [comment]
@alenaSchmickl Above installation result looks good. We have also tested using node v10.14.1 on windows and it works fine. After above installation, have you tried executing any test program. you can try executing `test/test-basic-test.js` too after updating connection string in `ibm_db/test/config.testConnectionStrings.json` file. 
Alternatively, you can unzip the ibm_db/build.zip file and find `odbc_bindings.node.10.14.1` under it. Copy this file as `ibm_db/build/Release/odbc_bindings.node` and run your test program. Please share the result of test output too. Thanks.

**Comment by rhtpandeyIN** [comment]
Hi @alenaSchmickl , As per the output log provided by you - ibm_db module is installing correctly. (Also, I have tested it with almost all the major node versions including 11.3.0, and it's working fine).

The error you are getting - seems you are using an older version of ibm_db version or may be you have installed it with some other version of node and now you are using it with some other version of node. (Version conflict - because you don't have the ibm_db compilation setup in your system and ibm_db installing the pre-compiled binaries instead).

Well, in first case (if you are using an older version of ibm_db) I will recommend to use the latest version of npm released ibm_db (2.5.0).
And in second case (if you are using latest code but have installed using some other version of node and now using some other node version), then in that case you will need to rebuild the module with the version of node which you are using currently. Run "npm rebuild" command inside node-modules directory and test it again. It should work fine.

Thanks.

**Comment by alenaSchmickl** [comment]
@rhtpandeyIN @bimalkjha thank you for the support! I ended up upgrading to Node v11, which immediately fixed the issue. The information that I can also use odbc_bindings.node.10.14.1 was very helpful.
