### ISSUE TITLE
Setting decimal separator: From comma to dot

### ISSUE THREAD

**Issue by gabrielwillemann** [ibmdb/node-ibm_db#495]
Hello,

When I run a query with decimal fields this driver return fields cast with string and saparated with comma.

For example:
```
conn.query('SELECT PRICE FROM PRODUCT', function (err, data) {
  console.log(data); // Return is: [ { PRICE: '21,45' }, { PRICE: '24,40' } ]
});

```
My server is a Windows Server 2012 (Brazilian Portuguese). The setting decimal separator is comma. But I can't change the setting because my database is legacy and many softwares connect to this database.

I finded many articles talking about decimal separator only current session, but I don't finded this setting on "node-ibm_db".

Articles finded:
* https://www.ibm.com/support/knowledgecenter/en/SSAE4W_9.5.1/db2/rbafzdatsep.htm
* https://www.ibm.com/support/knowledgecenter/en/ssw_ibm_i_73/db2/rbafzsoption.htm (DECMPT)
* https://www.ibm.com/support/knowledgecenter/en/ssw_ibm_i_72/cli/rzadpfnsenva.htm (SQL_ATTR_DECIMAL_SEP)
* https://www.ibm.com/support/knowledgecenter/en/SSEPEK_10.0.0/sqlref/src/tpc/db2z_refs2builtinsessionvars.html (DECIMAL_POINT)
* http://php.net/manual/pt_BR/function.db2-connect.php (i5_decimal_sep)

How to use setting decimal separator on the package "node-ibm_db"? I want use dot as separator.

PS: Original issue #394.

**Comment by bimalkjha** [comment]
@gabrielwillemann For this purpose, you can add "PATCH2=15;" in the connection string used for ibm_db. The details about this setting is documented [here](https://www.ibm.com/support/knowledgecenter/SSEPGG_11.1.0/com.ibm.db2.luw.apdv.cli.doc/doc/r0008805.html)
If you want it to be effective for all connections always, you can create  `.../ibm_db/installer/clidriver/cfg/db2cli.ini` file with below text:
```
[common]
Patch2=15

```
Thanks.

**Comment by gabrielwillemann** [comment]
It's work.
Thanks @bimalkjha
