### ISSUE TITLE
XML parameter to Stored Procedures

### ISSUE THREAD

**Issue by udemykotha** [ibmdb/node-ibm_db#499]
I have a stored procedure which accepts XML as an input parameter (P_IN_XML XML) ? Is XML parameter types supported ? If yes what is the parameter type in NodeJS? Also where can I find all the parameter types and their associated numeric codes?

**Comment by PriyankaManoharan04** [comment]
@udemykotha 

> Is XML parameter types supported

Yes XML Parameter type is supported.

> If yes what is the parameter type in NodeJS

The paramter type in nodejs is XML.

> Also where can I find all the parameter types and their associated numeric codes
The list of parameters supported by db2 are mentioned here `https://www.ibm.com/support/knowledgecenter/en/SSEPGG_11.1.0/com.ibm.db2.luw.apdv.cli.doc/doc/r0002218.html`.

Thanks

**Comment by PriyankaManoharan04** [comment]
@udemykotha you can refer this example to create table of xml type.

```
ibmdb.open(cn, function (err, conn) {
    conn.querySync("create table xml2 (c1 xml)");
    conn.prepare("insert into xml2(c1) VALUES (?)", function (err, stmt) {
        if (err) {
            //could not prepare for some reason
            console.log(err);
            return conn.closeSync();
        }

        //Bind and Execute the statment asynchronously
        stmt.execute(['<name>nodejs</name>'], function (err, result) {
            if (err) console.log(err);
            else result.closeSync();

            //Close the connection
            conn.close(function (err) { });
        });
    });
});
```
Thanks.
