### ISSUE TITLE
fatal error: 'utility' file not found

### ISSUE THREAD

**Issue by SabaKauser** [ibmdb/node-ibm_db#501]
opening on behalf of a reported issue in python forum.

 fatal error: 'utility' file not found (show original) Dec 20 (11 hours ago)
After upgrading Mac OS and installing new Xcode command line tools, I am having trouble with ibm_db building successfully.  Please help me identify root cause and solution?  I have no idea what 'utility' file is missing.  

scotts-mbp-8:source_node6.15.1 home$ yarn install
yarn install v1.6.0
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
warning " > @material-ui/core@1.1.0" has incorrect peer dependency "react@^16.3.0".
warning " > @material-ui/core@1.1.0" has incorrect peer dependency "react-dom@^16.3.0".
warning " > @material-ui/icons@1.0.0-beta.43" has incorrect peer dependency "material-ui@^1.0.0-beta.16".
warning " > ag-grid-react@17.1.0" has incorrect peer dependency "react@^15.5.0 || ^16.0.0".
warning " > ag-grid-react@17.1.0" has incorrect peer dependency "react-dom@^15.5.0 || ^16.0.0".
warning " > chai-immutable@1.6.0" has incorrect peer dependency "chai@>= 2.0.0 < 4".
warning " > file-loader@1.1.11" has incorrect peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0".
warning "file-loader > schema-utils@0.4.5" has incorrect peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0".
[5/5] 📃  Building fresh packages...
[-/6] ⡀ waiting...
[-/6] ⡀ waiting...
[3/6] ⡀ ibm_db:   cmd: 'node-gyp configure build  --IS_DOWNLOADED=true --IBM_DB_HOME="$IBM_DB_HOME"' }
[4/6] ⡀ dtrace-provider: info ok
error /Users/home/git/source_node6.15.1/node_modules/ibm_db: Command failed.
Exit code: 1
Command: node installer/driverInstall.js
Arguments: 
Directory: /Users/home/git/source_node6.15.1/node_modules/ibm_db
Output:
Downloading DB2 ODBC CLI Driver from https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/macos64_odbc_cli.tar.gz...

100.00% | 20080158 bytes downloaded out of 20080158 bytes.

****************************************
You are downloading a package which includes the Node.js module for IBM DB2/Informix.  The module is licensed under the Apache License 2.0. The package also includes IBM ODBC and CLI Driver from IBM, which is automatically downloaded as the node module is installed on your system/device. The license agreement to the IBM ODBC and CLI Driver is available in undefined   Check for additional dependencies, which may come with their own license agreement(s). Your use of the components of the package and dependencies constitutes your acceptance of their respective license agreements. If you do not accept the terms of any license agreement(s), then delete the relevant component(s) from your device.
****************************************

Downloading and extraction of DB2 ODBC CLI Driver completed successfully ...

  CXX(target) Release/obj.target/odbc_bindings/src/odbc.o

{ Error: Command failed: node-gyp configure build  --IS_DOWNLOADED=true --IBM_DB_HOME="$IBM_DB_HOME"
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.15.1 | darwin | x64
gyp info spawn /usr/bin/python
gyp info spawn args [ '/Users/home/.nvm/versions/node/v6.15.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/home/git/source_node6.15.1/node_modules/ibm_db/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/home/.nvm/versions/node/v6.15.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/home/.node-gyp/6.15.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/home/.node-gyp/6.15.1',
gyp info spawn args   '-Dnode_gyp_dir=/Users/home/.nvm/versions/node/v6.15.1/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/home/git/source_node6.15.1/node_modules/ibm_db',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
In file included from ../src/odbc.cpp:22:
/Users/home/.node-gyp/6.15.1/include/node/v8.h:21:10: fatal error: 'utility' file not found
#include <utility>
         ^~~~~~~~~
1 warning and 1 error generated.
make: *** [Release/obj.target/odbc_bindings/src/odbc.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/home/.nvm/versions/node/v6.15.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Darwin 18.0.0
gyp ERR! command "/Users/home/.nvm/versions/node/v6.15.1/bin/node" "/Users/home/.nvm/versions/node/v6.15.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build" "--IS_DOWNLOADED=true" "--IBM_DB_HOME=/Users/home/git/source_node6.15.1/node_modules/ibm_db/installer/clidriver"
gyp ERR! cwd /Users/home/git/source_node6.15.1/node_modules/ibm_db
gyp ERR! node -v v6.15.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

    at ChildProcess.exithandler (child_process.js:199:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Socket.<anonymous> (internal/child_process.js:351:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:509:12)
  killed: false,

**Comment by bimalkjha** [comment]
@SabaKauser If you open file /Users/home/.node-gyp/6.15.1/include/node/v8.h at line no 21 you can see `#include <utility>`. unitility.h is a C++ header file which is required by node.js header file v8.h. 
In your output we can see the `warning: include path for stdlibc++ headers not found`. Seems your system do not have c++ installed. You should install `XCode` on your mac to get it. Thanks.

**Comment by bimalkjha** [comment]
It happened due to old version of node.js. Check issue #516 for solution that reported same issue. Thanks.
