### ISSUE TITLE
Problem to connect using SSL

### ISSUE THREAD

**Issue by brvieira** [ibmdb/node-ibm_db#503]
Hi folks, I'm trying to access a db2 database using SSL, however, I'm facing some problems, it is because ibm_db package supports trust stores in .kdb format only, which is generated using GSkit.

How I'm using a MacOs, I think that I'm not able to install GSkit and generate it.

So, is there any way to do this connection using a .jks trust store?

Thanks team

**Comment by bimalkjha** [comment]
@brvieira The .jks trust store can only be accessed using Java driver. ibm_db or IBM ODBC driver can not read .jks trust store. 
If you have single certificate file with extension .arm, then you can directly use it in connection string as the value of SSLServerCertificate keyword.
To install GSKit on MacOS, I do not see independent installer. So, you can open a case on [IBM Support](https://www.ibm.com/mysupport/s/topic/0TO500000001fUNGAY/db2-linux-unix-and-windows?language=en_US&productId=01t50000004WmTk). They should help you. Thanks.
