### ISSUE TITLE
Mac OS [IBM][CLI Driver] SQL30082N

### ISSUE THREAD

**Issue by schmidtuconn** [ibmdb/node-ibm_db#504]
OS: macOS 10.14.2
Command: db.openSync(config);
Result: Error: [IBM][CLI Driver] SQL30082N

This command works when application is run on Windows machines with the same connection String. It also works running in a Docker container. This leads me to suspect there is something incompatible between the CLI Driver and the OS.

**Comment by bimalkjha** [comment]
@schmidtuconn  Please share the complete error message. The rc code in message gives more info. You can search about this error with rc code on google of [IBM Support](https://www-01.ibm.com/support/docview.wss?uid=swg21998811) page to find solution. It mostly relates with user permission and env issue. Thanks.

**Comment by schmidtuconn** [comment]
/Users/joshua.schmidtibm.com/Documents/raven/micromedex/cmdx/MDX-chatbot-service/node_modules/ibm_db/lib/odbc.js:376
  var result = self.conn.openSync(connStr);
                         ^
Error: [IBM][CLI Driver] SQL30082N  Security processing failed with reason "17" ("UNSUPPORTED FUNCTION").  SQLSTATE=08001

    at Database.openSync (/Users/joshua.schmidtibm.com/Documents/raven/micromedex/cmdx/MDX-chatbot-service/node_modules/ibm_db/lib/odbc.js:376:26)
    at Function.module.exports.openSync (/Users/joshua.schmidtibm.com/Documents/raven/micromedex/cmdx/MDX-chatbot-service/node_modules/ibm_db/lib/odbc.js:118:6)
    at openDBConnection (/Users/joshua.schmidtibm.com/Documents/raven/micromedex/cmdx/MDX-chatbot-service/database/db.js:33:19)
    at Object.getDataFromDB (/Users/joshua.schmidtibm.com/Documents/raven/micromedex/cmdx/MDX-chatbot-service/database/db.js:39:16)
    at Object.executeSQLQuery (/Users/joshua.schmidtibm.com/Documents/raven/micromedex/cmdx/MDX-chatbot-service/lib/queryMapping.js:139:8)
    at Object.drugInteractionHandler (/Users/joshua.schmidtibm.com/Documents/raven/micromedex/cmdx/MDX-chatbot-service/lib/customIntentHandler.js:49:16)
    at handler (/Users/joshua.schmidtibm.com/Documents/raven/micromedex/cmdx/MDX-chatbot-service/lib/wcsResponseHandler.js:219:25)
    at /Users/joshua.schmidtibm.com/Documents/raven/micromedex/cmdx/MDX-chatbot-service/lib/wcsResponseHandler.js:432:5
    at Request._callback (/Users/joshua.schmidtibm.com/Documents/raven/micromedex/cmdx/MDX-chatbot-service/node_modules/watson-developer-cloud/lib/requestwrapper.js:105:5)
    at Request.self.callback (/Users/joshua.schmidtibm.com/Documents/raven/micromedex/cmdx/MDX-chatbot-service/node_modules/request/request.js:186:22)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! chatbot-service@0.1.1 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the chatbot-service@0.1.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/joshua.schmidtibm.com/.npm/_logs/2019-02-06T18_26_13_365Z-debug.log

**Comment by schmidtuconn** [comment]
Note that this is only an issue on MacOS not on Windows

**Comment by bimalkjha** [comment]
It looks similar issue as documented here: https://www-01.ibm.com/support/docview.wss?uid=swg21237107
Please add AUTHENTICATION=SERVER in connection string and try. Thanks.

**Comment by schmidtuconn** [comment]
I have tried the connection string with both. 
Option 1:
"username=admin;password=****;hostname=***.bluemix.net;port=###;database=BLUDB;schema=SCHEMA_1;AUTHENTICATION_TYPE=SERVER_ENCRYPT;"
and
Option 2:
"username=admin;password==****;;hostname==***..bluemix.net;port=50000;database=BLUDB;schema=SCHEMA_1;AUTHENTICATION_TYPE=SERVER;"

Both lead to the same error posted above.

**Comment by bimalkjha** [comment]
@schmidtuconn Please run ` export ibm_db\installer\setenv.sh` command to set the env and then run your test script to make sure there is no env issue.
It it still fails, please update connection string in `ibm_db\installer\testODBCConnection.sh` file and run it. This script should test the connectivity to database server using ODBC and collect db2 trace files. Please share the generated 1.* files to bjha@rocketsoftware.com with the output of script. We'll look into the trace files to find out the root cause of the problem. Thanks.

**Comment by schmidtuconn** [comment]
I want to make sure I do this right. 

db2cli validate -database "sample:hotel.torolab.ibm.com:21169" -connect -user newton -passwd serverpass

So I put my connection string replaced for sample:hotel.torolab.ibm.com:21169?

And do I change the user and password at the end as well?

**Comment by bimalkjha** [comment]
yes, you need to change: dbname, hostname, port, userid and password. i.e. change the user and password at the end as well. thank.

**Comment by schmidtuconn** [comment]
This is the result of the run-tests.js:


Warning : there are 23 disabled tests

Running test 1 for [DB2] : test-all-data-types ... success  
Running test 2 for [DB2] : test-bad-connection-string ... success  
Running test 3 for [DB2] : test-bad-pool-connection-issue-42 ... success  
Running test 4 for [DB2] : test-basic-test ... success  
Running test 5 for [DB2] : test-binding-connection-timeOut ... success  
Running test 6 for [DB2] : test-binding-statement-executeSync ... success  
Running test 7 for [DB2] : test-binding-transaction-commit ... success  
Running test 8 for [DB2] : test-binding-transaction-commitSync ... success  
Running test 9 for [DB2] : test-blob-file ... success  
Running test 10 for [DB2] : test-blob-insert ... success  
Running test 11 for [DB2] : test-blocking-issue210 ... success  
Running test 12 for [DB2] : test-call-async ... success  
Running test 13 for [DB2] : test-call-stmt ... success  
Running test 14 for [DB2] : test-chinese-char ... success  
Running test 15 for [DB2] : test-closed ... success  
Running test 16 for [DB2] : test-connection-object ... success  
Running test 17 for [DB2] : test-date ... success  
Running test 18 for [DB2] : test-describe-column ... fail  
 Stdout:  
connected
[IBM][CLI Driver][DB2/LINUXX8664] SQL0204N  "BLUADMIN.NODE_ODBC_TEST_TABLE" is an undefined name.  SQLSTATE=42704

tables dropped
tables created
[]

 Stderr:  
assert.js:351
    throw err;
    ^

AssertionError [ERR_ASSERTION]: No records returned when attempting to describe the column COLDATETIME
    at /Users/joshua.schmidtibm.com/Documents/raven/micromedex/cmdx/MDX-chatbot-service/node_modules/ibm_db/test/test-describe-column.js:31:14
    at /Users/joshua.schmidtibm.com/Documents/raven/micromedex/cmdx/MDX-chatbot-service/node_modules/ibm_db/lib/odbc.js:1030:21

Running test 19 for [DB2] : test-describe-database ... fail  
 Stdout:  

 Stderr:  
assert.js:351
    throw err;
    ^

AssertionError [ERR_ASSERTION]: No records returned when attempting to describe the database
    at /Users/joshua.schmidtibm.com/Documents/raven/micromedex/cmdx/MDX-chatbot-service/node_modules/ibm_db/test/test-describe-database.js:15:14
    at /Users/joshua.schmidtibm.com/Documents/raven/micromedex/cmdx/MDX-chatbot-service/node_modules/ibm_db/lib/odbc.js:1053:21

Running test 20 for [DB2] : test-describe-table ... fail  
 Stdout:  

 Stderr:  
assert.js:351
    throw err;
    ^

AssertionError [ERR_ASSERTION]: No records returned when attempting to describe the tabe NODE_ODBC_TEST_TABLE
    at /Users/joshua.schmidtibm.com/Documents/raven/micromedex/cmdx/MDX-chatbot-service/node_modules/ibm_db/test/test-describe-table.js:17:14
    at /Users/joshua.schmidtibm.com/Documents/raven/micromedex/cmdx/MDX-chatbot-service/node_modules/ibm_db/lib/odbc.js:1030:21

Running test 21 for [DB2] : test-domains-open ... success  
Running test 22 for [DB2] : test-fetch-apis ... success  
Running test 23 for [DB2] : test-global-open-close ... success  
Running test 24 for [DB2] : test-ibm-db-issue14 ... success  
Running test 25 for [DB2] : test-ibm-db-issue17 ... success  
Running test 26 for [DB2] : test-ibm-db-issue18 ... success  
Running test 27 for [DB2] : test-instantiate-one-and-end ... success  
Running test 28 for [DB2] : test-issue-54 ... success  
Running test 29 for [DB2] : test-issue-get-column-value-2 ... success  
Running test 30 for [DB2] : test-issue211 ... success  
Running test 31 for [DB2] : test-issue253 ... success  
Running test 32 for [DB2] : test-max-pool-size ... success  
Running test 33 for [DB2] : test-memory-leaks-new-objects ... success  
Running test 34 for [DB2] : test-multi-open-close ... success  
Running test 35 for [DB2] : test-multi-open-query-close ... success  
Running test 36 for [DB2] : test-multi-openSync-closeSync ... success  
Running test 37 for [DB2] : test-open-close ... success  
Running test 38 for [DB2] : test-open-connectTimeout ... success  
Running test 39 for [DB2] : test-openSync ... success  
Running test 40 for [DB2] : test-pool-close ... success  
Running test 41 for [DB2] : test-pool-connect ... success  
Running test 42 for [DB2] : test-pool-idle-connection ... success  
Running test 43 for [DB2] : test-pool-rollbackTransaction ... success  
Running test 44 for [DB2] : test-pool-uncommited ... success  
Running test 45 for [DB2] : test-prepareSync-bad-sql ... success  
Running test 46 for [DB2] : test-prepareSync-multiple-execution ... success  
Running test 47 for [DB2] : test-promisified-connection-pool ... success  
Running test 48 for [DB2] : test-query-create-table-fetchSync ... success  
Running test 49 for [DB2] : test-query-create-table ... success  
Running test 50 for [DB2] : test-query-drop-table ... success  
Running test 51 for [DB2] : test-query-insert ... success  
Running test 52 for [DB2] : test-query-select-fetch ... success  
Running test 53 for [DB2] : test-query-select-fetchMode-array ... success  
Running test 54 for [DB2] : test-query-select ... success  
Running test 55 for [DB2] : test-queryResult ... success  
Running test 56 for [DB2] : test-queryStream ... success  
Running test 57 for [DB2] : test-querySync-select-with-exception ... success  
Running test 58 for [DB2] : test-querySync-select ... success  
Running test 59 for [DB2] : test-require-and-end ... success  
Running test 60 for [DB2] : test-sp-resultset-execute ... success  
Running test 61 for [DB2] : test-sp-resultset ... success  
Running test 62 for [DB2] : test-transaction-commit-sync ... success  
Running test 63 for [DB2] : test-transaction-commit ... success  

Results : 3 of 63 tests failed.

Total execution time = 2 min 58 sec.

**Comment by bimalkjha** [comment]
@schmidtuconn So, it is working fine. You can ignore those 3 test files which is specific to db2sampl database.
You can try now: `cd ibm_db\test; node test-basic-test.js`
It should work fine. And then you can run your repro also. 
I would suggest to use this connection string in your test first and then use SCHEMA or AUTHENTICATION keyword. AUTHENTICATION_TYPE keyword is not a valid keyword. Also, you are still missing PROTOCOL keyword in your shared connection string:
"username=admin;password=PWD;hostname=url.bluemix.net;port=###;database=BLUDB;PROTOCOL=TCPIP"
Thanks.
