### ISSUE TITLE
502 Bad Gateway: Registered endpoint failed to handle the request

### ISSUE THREAD

**Issue by karthick-blog** [ibmdb/node-ibm_db#505]
Hi Team,

we were using ibm_db with NodeJs. Since two weeks we were getting "502 Bad Gateway: Registered endpoint failed to handle the request" error. This issue occured random basis, on refresh we were able to get the response.

Node: 6.x
database: Db2 on Cloud

Kindly help us to resolve this issue.

thanks in advance.

**Comment by bimalkjha** [comment]
@karthick-blog "502 Bad Gateway" error is not from ibm_db or db2 server. It seems IBM Cloud has encountered some issue. Please take this issue with IBM Cloud team. Thanks.
