### ISSUE TITLE
Db2 HADR Alternate Client Reroute , Client attempts to non alternate server ip rather than Alternate Server IP

### ISSUE THREAD

**Issue by pmutyala** [ibmdb/node-ibm_db#509]
Hello,
One of our customers, who is using NodeJS driver on IBM Cloud against IBM Db2 with HADR setup on IBM Cloud is seeing an issue/error message in db2diag log on the client side.

The Db2 HADR server is configured with alternate server IP set to a floating ip and a port. The floating ip is moved to the new primary when there is failover. The server setup consists of 2 Db2 nodes configured as HA pair, and each server has a  primary IP associated to local hostname which is not routable. The VIP or floating ip / portable ip which is routable has a FQDN hostname is always up on the primary role node. The user is given or allowed to access or run connections against portable ip of the setup.

for e.g hostname-pri.domain -> x.x.x.x (local hostname/local ip of primary designated node)
            hostname-sby.domain -> x.x.x.x ( local hostname/local ip of standby designated node)
           hostname.domain -> x.x.x.x (resolvable hostname / floating ip always up on primary role node)
          
So ideally during failover when node fails, the portable ip gets moved, and app connections fail with SQL30108N and connection gets moved. 

But during runtime when all nodes are up when user tries to connect to the server from a nodeJS app, the connection hits an error since it attempts to connect to local hostname and then gets rerouted to the floating ip, rather than client always connecting to the portable ip.

The user is using
Client Package Type : IBM Data Server Runtime Client
Client Version (level/bit): DB2 v11.1.4.4 (s1811091400/64-bit)
Client Platform : Linux/X8664

```2018-12-08-15.04.43.010369+000 E481236E489 LEVEL: Warning
PID : 103 TID : 140116546279168 PROC : node
INSTANCE: DB2 NODE : 000 DB : BLUDB
APPID : 10.245.201.22.41412.181208150442
HOSTNAME: f7191f8f-cf22-4e59-424a-dd29
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrRetryEnd, probe:900
MESSAGE : ADM2508I Client Reroute successful. Hostname/IP Address:
"169.60.61.60" and Service name/Port number: "50001".

:

2018-12-08-15.05.17.776884+000 I484186E534 LEVEL: Error
PID : 103 TID : 140116571457280 PROC : node
INSTANCE: DB2 NODE : 000 DB : BLUDB
APPID : 10.245.201.22.51696.181207144914
HOSTNAME: f7191f8f-cf22-4e59-424a-dd29
FUNCTION: DB2 UDB, common communication, sqlcctcpconnr, probe:42
MESSAGE : DIA3222E The host name
"dashdb-txnha-flex-yp-dal10-69-sby.services.dal.bluemix.net" was not
found, TCP/IP function "getaddrinfo" error return code = "-2".

:

2018-12-08-15.05.19.322181+000 E488105E489 LEVEL: Warning
PID : 103 TID : 140116571457280 PROC : node
INSTANCE: DB2 NODE : 000 DB : BLUDB
APPID : 10.245.201.22.43946.181208150518
HOSTNAME: f7191f8f-cf22-4e59-424a-dd29
FUNCTION: DB2 UDB, DRDA Application Requester, sqljrRetryEnd, probe:900
MESSAGE : ADM2508I Client Reroute successful. Hostname/IP Address:
"169.60.61.60" and Service name/Port number: "50001".```


We have not seen this issue with JCC type drivers, but most of our user using nodeJS complained that client attempting to connect to local ip and then does the reroute, We are wondering why client is attempting to connect local ip even though catalog and connect string contains the resolvable ip ?

**Comment by pmutyala** [comment]
please note, the alternate server is configured at server side in the catalog, and no db2dsdriver.cfg set on client side.

**Comment by bimalkjha** [comment]
@pmutyala Its a but in the installed "IBM Data Server Runtime Client". There is some bug in the DRDA level of this product which is written in C. Java driver is independent and has different code base. 
I think you open PMR against "IBM Data Server Runtime Client" product. node.js driver is not doing anything here. node.js driver is just using the ODBC driver present in your "IBM Data Server Runtime Client" installation. Thanks.

**Comment by pmutyala** [comment]
thank u @bimaljha will raise it with driver team.
