### ISSUE TITLE
Does closing the connection inside a transaction also requires closing the statements?

### ISSUE THREAD

**Issue by leonimurilo** [ibmdb/node-ibm_db#510]
My code is executing a lot of statements inside a beginTransaction block. 

I would like to know if I just need to close the connection at the end or have to close every single prepared and executed statement before closing the connection.

**Comment by bimalkjha** [comment]
@leonimurilo you should add stmt.close() after you are done with the stmt, else driver may exhaust the no of open statement handles. thanks.
