### ISSUE TITLE
How to execute multiple prepared statements at the same time?

### ISSUE THREAD

**Issue by leonimurilo** [ibmdb/node-ibm_db#512]
I have a large array of prepared statement promises and I want to execute all of them at once. I tried using Promise.all inside a transaction to execute all of them, but it takes a VERY LONG time.

How can I execute multiple statements at once?

The way I did this feels like it goes through the network for every single statement instead of executing all of them at the same "request".

**Comment by bimalkjha** [comment]
@leonimurilo You can execute multiple static sql at once separated by semicolon. Check example [here](https://github.com/ibmdb/node-ibm_db/blob/master/APIDocumentation.md#-3-querysqlquery--bindingparameters-callback).
```
conn.query("select 1 from sysibm.sysdummy1;select 2 from sysibm.sysdummy1;" +
               "select 3 from sysibm.sysdummy1", function (err, rows, sqlca)
    {
```
thanks.

**Comment by leonimurilo** [comment]
> @leonimurilo You can execute multiple static sql at once separated by semicolon. Check example [here](https://github.com/ibmdb/node-ibm_db/blob/master/APIDocumentation.md#-3-querysqlquery--bindingparameters-callback).
> 
> ```
> conn.query("select 1 from sysibm.sysdummy1;select 2 from sysibm.sysdummy1;" +
>                "select 3 from sysibm.sysdummy1", function (err, rows, sqlca)
>     {
> ```
> thanks.

Even if the statements are of different types (inserts, updates and deletes)?

**Comment by bimalkjha** [comment]
@leonimurilo Yes, even the statements are of different types (inserts, updates and deletes). Give a try to verify. Thanks.

**Comment by ShahMV** [comment]
Related to this issue, I'm trying to execute multiple deletes at a time but only the first one is executed.  Multiple selects work fine as shown in the example linked above.

The following query works fine and I get all three results:
queryText = "select 1 from sysibm.sysdummy1;select 2 from sysibm.sysdummy1;" +
                            "select 3 from sysibm.sysdummy1";

But when I run this only the first delete is executed:
queryText = "delete from tab1 where col1='A';delete from tab1 where col1='B'";

Let me know if I should be opening a new issue for this.  Thanks.

**Comment by PriyankaManoharan04** [comment]
@ShahMV We have just delivered the fix of this issue. Even for the statements of different types (inserts, create and deletes) it works. You can clone the code from master branch, install it using npm install command and test your example.

Thanks.
