### ISSUE TITLE
Special chars are no saving right

### ISSUE THREAD

**Issue by IsCruz** [ibmdb/node-ibm_db#513]
I'm trying to save this: IBMCLOUD88 世 ibm_dbג“·$%ä&/(э)=?¿ñæ 
but instead of it saves this: IBMCLOUD88 ä¸ ibm_db×âÂ·$%Ã¤&/(Ñ)=?Â¿Ã±Ã¦

I tried put the DB2CODEPAGE according to the info and datatype defined in SYSCAT.DATATYPES but saves modified the chars

**Comment by PriyankaManoharan04** [comment]
@IsCruz Can you just try setting environment variable DB2CODEPAGE=1208. I just tried using this and it works for me.Give a try to verify.Thanks

**Comment by IsCruz** [comment]
@PriyankaManoharan04 I found that the problem was the text editor terminal, in main terminal works fine.
