### ISSUE TITLE
Error Installing on MacOS 10.14.3

### ISSUE THREAD

**Issue by danchirillo** [ibmdb/node-ibm_db#516]
Output:

{ Error: Command failed: node-gyp configure build  --IS_DOWNLOADED=true --IBM_DB_HOME="$IBM_DB_HOME"
warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
In file included from ../src/odbc.cpp:22:
/Users/admin/.node-gyp/6.16.0/include/node/v8.h:21:10: fatal error: 'utility' file not found
#include <utility>
         ^~~~~~~~~
1 warning and 1 error generated.
make: *** [Release/obj.target/odbc_bindings/src/odbc.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/admin/.nvm/versions/node/v6.16.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/Users/admin/.nvm/versions/node/v6.16.0/bin/node" "/Users/admin/.nvm/versions/node/v6.16.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build" "--IS_DOWNLOADED=true" "--IBM_DB_HOME=/Users/admin/Documents/work/apiconnect/acme-bank/node_modules/ibm_db/installer/clidriver"
gyp ERR! cwd /Users/admin/Documents/work/apiconnect/acme-bank/node_modules/ibm_db
gyp ERR! node -v v6.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 

    at ChildProcess.exithandler (child_process.js:199:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Socket.<anonymous> (internal/child_process.js:351:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:509:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node-gyp configure build  --IS_DOWNLOADED=true --IBM_DB_HOME="$IBM_DB_HOME"' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ibm_db@2.5.0 install: `node installer/driverInstall.js`
npm ERR! Exit status 1

[2019-03-25T17_45_14_587Z-debug.log](https://github.com/ibmdb/node-ibm_db/files/3004766/2019-03-25T17_45_14_587Z-debug.log)

**Comment by PriyankaManoharan04** [comment]
@danchirillo you have installed the v6.16.0 version of Nodejs, try to install the latest version of Nodejs and it works fine for me.Give a try to verify.Thanks

**Comment by danchirillo** [comment]
@PriyankaManoharan04 - I was using v6 because that's the latest version supported by the API Connect toolkit, but switching to v11, installing the connector and then switching back to v6 for API Connect worked.  Thank you.
