### ISSUE TITLE
[IBM][CLI Driver] SQL1042C  An unexpected system error occurred.  SQLSTATE=58004

### ISSUE THREAD

**Issue by zaidkazi** [ibmdb/node-ibm_db#521]
When i run it with my node server my node app runs fine but when i try to initiate a db2 connection my node server says 

 warn: [IBM][CLI Driver] SQL1042C  An unexpected system error occurred.  SQLSTATE=58004

Im running a windows with latest node-ibm.

Here is the output from the testconnection.bat file you guys provide

===============================================================================
Client information for the current copy (copy name: F_Jenkins_workspace_DataHub_API_development_node_modules_ibm_db_installer_clidriver):
===============================================================================

Client Package Type       : IBM Data Server Driver For ODBC and CLI
Client Version (level/bit): DB2 v11.1.3031.295 (s1804271300/64-bit)
Client Platform           : NT 64BIT
Install/Instance Path     : F:\Jenkins\workspace\DataHub_API_development\node_modules\ibm_db\installer\clidriver

Common App Data Path      : C:\ProgramData\IBM\DB2\F_Jenkins_workspace_DataHub_API_development_node_modules_ibm_db_installer_clidriver
DB2DSDRIVER_CFG_PATH value: <not-set>
db2dsdriver.cfg Path      : <Common App Data Path>\cfg\db2dsdriver.cfg
DB2CLIINIPATH value       : <not-set>
db2cli.ini Path           : <Common App Data Path>\cfg\db2cli.ini
db2diag.log Path          : <Common App Data Path>\db2diag.log

===============================================================================
List of all IBM Data Server client packages on the current workstation:
===============================================================================

Copyname                                                                               Version Package Language Installed-Location
-------------------------------------------------------------------------------
F_Jenkins_workspace_DataHub_API_development_node_modules_ibm_db_installer_clidriver[C] 11.1.0303 CLI     EN       F:\Jenkins\workspace\DataHub_API_development\node_modules\ibm_db\installer\clidriver
-------------------------------------------------------------------------------
 CLI: IBM Data Server Driver for ODBC and CLI
-------------------------------------------------------------------------------

===============================================================================
db2dsdriver.cfg schema validation for the entire file:
===============================================================================

Note: The validation utility could not find the configuration file
db2dsdriver.cfg. The file is searched at
"C:\ProgramData\IBM\DB2\F_Jenkins_workspace_DataHub_API_development_node_modules_ibm_db_installer_clidriver\cfg\db2dsdriver.cfg".

===============================================================================
db2cli.ini validation for database "sample:hotel.torolab.ibm.com:21169":
===============================================================================

Note: The validation utility could not find the configuration file db2cli.ini.
The file is searched at
"C:\ProgramData\IBM\DB2\F_Jenkins_workspace_DataHub_API_development_node_modules_ibm_db_installer_clidriver\cfg\db2cli.ini".

===============================================================================
db2dsdriver.cfg validation for database "sample:hotel.torolab.ibm.com:21169":
===============================================================================

Note: The validation utility could not find the configuration file
db2dsdriver.cfg. The file is searched at
"C:\ProgramData\IBM\DB2\F_Jenkins_workspace_DataHub_API_development_node_modules_ibm_db_installer_clidriver\cfg\db2dsdriver.cfg".

===============================================================================
Connection attempt for database "sample:hotel.torolab.ibm.com:21169":
===============================================================================

[FAILED]: [IBM][CLI Driver] SQL1042C  An unexpected system error occurred.  SQLSTATE=58004

===============================================================================
Error: The validation operation failed.
===============================================================================

===============================================================================
The validation is completed.
===============================================================================

**Comment by zaidkazi** [comment]
I have also uploaded the trace of my node server running 
[traceofapp.txt](https://github.com/ibmdb/node-ibm_db/files/3041732/traceofapp.txt)

**Comment by zaidkazi** [comment]
@bimalkjha any clue?

**Comment by bimalkjha** [comment]
Please correct the connection string information in ` testODBCConnection.bat` for `db2cli validate` command and then run. Currently it is trying to connect to `sample:hotel.torolab.ibm.com:21169` which do not exist. Also, use correct credentials. Share all generated files.
Also, execute "set > env.txt" on command prompt after execution of testODBCConnection.bat and share the env.txt file too. Thanks.

**Comment by zaidkazi** [comment]
Env output 

F:\Jenkins\workspace\DataHub_API_development\node_modules\ibm_db\installer>set
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\sysadmin\AppData\Roaming
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=zaid
ComSpec=C:\windows\system32\cmd.exe
DEFLOGDIR=C:\ProgramData\McAfee\Endpoint Security\Logs
HOMEDRIVE=C:
HOMEPATH=\Users\sysadmin
IBM_DB_HOME=F:\Jenkins\workspace\DataHub_API_development\node_modules\ibm_db\installer\clidriver
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_201
LIB=F:\Jenkins\workspace\DataHub_API_development\node_modules\ibm_db\installer\clidriver\lib;F:\Jenkins\workspace\DataHub_API_development\node_modules\ibm_db\installer\clidriver\lib;F:\Jenkins\workspace\DataHub_API_development\node_modules\ibm_db\installer\clidriver\lib;
LOCALAPPDATA=C:\Users\sysadmin\AppData\Local
LOGONSERVER=\\zaid
MAVEN_HOME=F:\Maven-3.6.0
NODE_PATH=C:\Users\sysadmin\AppData\npm\node_modules
NODE_TLS_REJECT_UNAUTHORIZED=0
NUMBER_OF_PROCESSORS=2
OS=Windows_NT
PATH=F:\Jenkins\workspace\DataHub_API_development\node_modules\ibm_db\installer\clidriver\bin;F:\Jenkins\workspace\DataHub_API_development\node_modules\ibm_db\installer\clidriver\adm;F:\Jenkins\workspace\DataHub_API_development\node_modules\ibm_db\installer\clidriver\lib;F:\Jenkins\workspace\DataHub_API_development\node_modules\ibm_db\installer\clidriver\bin;F:\Jenkins\workspace\DataHub_API_development\node_modules\ibm_db\installer\clidriver\adm;F:\Jenkins\workspace\DataHub_API_development\node_modules\ibm_db\installer\clidriver\lib;F:\Jenkins\workspace\DataHub_API_development\node_modules\ibm_db\installer\clidriver\bin;F:\Jenkins\workspace\DataHub_API_development\node_modules\ibm_db\installer\clidriver\adm;F:\Jenkins\workspace\DataHub_API_development\node_modules\ibm_db\installer\clidriver\lib;C:\Python27\;C:\Python27\Scripts;C:\Users\sysadmin\.windows-build-tools\python27;C:\Program Files\Java\jdk1.8.0_201\bin;C:\Program Files\nodejs;C:\Windows\System32;C:\Users\sysadmin\.windows-build-tools\python27\;C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\sysadmin\AppData\Roaming\npm\node_modules\windows-build-tools\node_modules\.bin;C:\Users\sysadmin\AppData\Roaming\npm\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\EMC NetWorker\nsr\bin;C:\Program Files\avs\bin;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Universal\USap\bin\;F:\Maven-3.6.0\bin;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin\;C:\Users\sysadmin\AppData\Local\Microsoft\WindowsApps;C:\Users\sysadmin\AppData\Roaming\npm;C:\Program Files\MongoDB\Server\3.4\bin;C:\Users\sysadmin\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin;C:\Program Files\nodejs\
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
pm2=C:\Users\sysadmin\AppData\Roaming\npm\pm2
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 45 Stepping 2, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=2d02
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=$P$G
PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\windows\system32\WindowsPowerShell\v1.0\Modules;C:\Program Files\Microsoft Monitoring Agent\Agent\PowerShell\
PUBLIC=C:\Users\Public
PYTHON=C:\Users\sysadmin\.windows-build-tools\python27
SystemDrive=C:
SystemRoot=C:\windows
TEMP=C:\Users\sysadmin\AppData\Local\Temp
TMP=C:\Users\sysadmin\AppData\Local\Temp
UATDATA=C:\windows\CCM\UATData\D9F8C395-CAB8-491d-B8AC-179A1FE1BE77
USERDOMAIN=zaid
USERDOMAIN_ROAMINGPROFILE=zaid
USERNAME=sysadmin
USERPROFILE=C:\Users\sysadmin
VS140COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\
windir=C:\windows

**Comment by zaidkazi** [comment]
running testconnetion to my server i have tried on my mac and it works fine so i know my server settings are correct. Here is the output after updating the information for database

===============================================================================
Client information for the current copy (copy name: F_Jenkins_workspace_DataHub_API_development_node_modules_ibm_db_installer_clidriver):
===============================================================================

Client Package Type       : IBM Data Server Driver For ODBC and CLI
Client Version (level/bit): DB2 v11.1.3031.295 (s1804271300/64-bit)
Client Platform           : NT 64BIT
Install/Instance Path     : F:\Jenkins\workspace\DataHub_API_development\node_modules\ibm_db\installer\clidriver

Common App Data Path      : C:\ProgramData\IBM\DB2\F_Jenkins_workspace_DataHub_API_development_node_modules_ibm_db_installer_clidriver
DB2DSDRIVER_CFG_PATH value: <not-set>
db2dsdriver.cfg Path      : <Common App Data Path>\cfg\db2dsdriver.cfg
DB2CLIINIPATH value       : <not-set>
db2cli.ini Path           : <Common App Data Path>\cfg\db2cli.ini
db2diag.log Path          : <Common App Data Path>\db2diag.log

===============================================================================
List of all IBM Data Server client packages on the current workstation:
===============================================================================

Copyname                                                                               Version Package Language Installed-Location
-------------------------------------------------------------------------------
F_Jenkins_workspace_DataHub_API_development_node_modules_ibm_db_installer_clidriver[C] 11.1.0303 CLI     EN       F:\Jenkins\workspace\DataHub_API_development\node_modules\ibm_db\installer\clidriver
-------------------------------------------------------------------------------
 CLI: IBM Data Server Driver for ODBC and CLI
-------------------------------------------------------------------------------

===============================================================================
db2dsdriver.cfg schema validation for the entire file:
===============================================================================

Note: The validation utility could not find the configuration file
db2dsdriver.cfg. The file is searched at
"C:\ProgramData\IBM\DB2\F_Jenkins_workspace_DataHub_API_development_node_modules_ibm_db_installer_clidriver\cfg\db2dsdriver.cfg".

===============================================================================
db2cli.ini validation for database "db01gcc:uadb2cp2.fg.zaid.com:50002":
===============================================================================

Note: The validation utility could not find the configuration file db2cli.ini.
The file is searched at
"C:\ProgramData\IBM\DB2\F_Jenkins_workspace_DataHub_API_development_node_modules_ibm_db_installer_clidriver\cfg\db2cli.ini".

===============================================================================
db2dsdriver.cfg validation for database "db01gcc:uadb2cp2.fg.zaid.com:50002":
===============================================================================

Note: The validation utility could not find the configuration file
db2dsdriver.cfg. The file is searched at
"C:\ProgramData\IBM\DB2\F_Jenkins_workspace_DataHub_API_development_node_modules_ibm_db_installer_clidriver\cfg\db2dsdriver.cfg".

===============================================================================
Connection attempt for database "db01gcc:uadb2cp2.fg.zaid.com:50002":
===============================================================================

[FAILED]: [IBM][CLI Driver] SQL1042C  An unexpected system error occurred.  SQLSTATE=58004


===============================================================================
Error: The validation operation failed.
===============================================================================

===============================================================================
The validation is completed.
===============================================================================

Trace is turned off
Total number of trace records     : 13437
Trace truncated                   : NO
Trace wrapped                     : NO
Number of trace records formatted : 12 (pid: 6800 tid 2080 node: -1)
Number of trace records formatted : 12796 (pid: 7100 tid 1784 node: -1)
Number of trace records formatted : 130 (pid: 4036 tid 7604 node: -1)
Trace truncated                   : NO
Trace wrapped                     : NO
Total number of trace records     : 13437
Number of trace records formatted : 12938
Trace truncated                   : NO
Trace wrapped                     : NO
Total number of trace records     : 13437
Number of trace records formatted : 0
Trace truncated                   : NO
Trace wrapped                     : NO
Total number of trace records     : 13437
Number of trace records formatted : 499

**Comment by zaidkazi** [comment]
trace file from testconnection

[traceofapp.txt](https://github.com/ibmdb/node-ibm_db/files/3044632/traceofapp.txt)

**Comment by zaidkazi** [comment]
@bimalkjha please advise still facing same problem works fine on my mac not sure whats wrong with my windows setup ive tried to reformat my pc twice and still facing the issue.

**Comment by bimalkjha** [comment]
@zaidkazi By looking on the shared trace file, the connection is failing in ODBC driver while initializing the GSKit Crypto libraries.
We can see repeated entries in your LIB and PATH system environment variables. Please remove the duplicate entries from both. Also, we don't see `F:\Jenkins\workspace\DataHub_API_development\node_modules\ibm_db\installer\clidriver\bin` in your `LIB` system environment variable. Please add `F:\Jenkins\workspace\DataHub_API_development\node_modules\ibm_db\installer\clidriver\lib` and `F:\Jenkins\workspace\DataHub_API_development\node_modules\ibm_db\installer\clidriver\lib\icc64` both path in your LIB system environment variable and then run your test program using new command prompt.
If still do not work, then as a work around, you can use "AUTHENTICATION=SERVER;" in your connection string and run the `testODBCConnection.bat` file. If it works, use the same in your node.js app connection string. Thanks.

**Comment by zaidkazi** [comment]
I did all of your updated suggestions but still the same issue.

I tried using authentication=server but i was getting a reason code 17 error as our database does not allow for server authentication.

please advice on next steps ? Is there some way i can uninstall all ibmdb related files as it seems to be a machine issue at this points but i cannot reformat the computer.

**Comment by zaidkazi** [comment]
F:\stuff\DataTool>set
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\sysadmin\AppData\Roaming
CLIENTNAME=C02YD37HJG5H
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=SE142201
ComSpec=C:\windows\system32\cmd.exe
DEFLOGDIR=C:\ProgramData\McAfee\Endpoint Security\Logs
HOMEDRIVE=C:
HOMEPATH=\Users\sysadmin
HTTPS_PROXY=http://807259361:Password100200!@zaid.com:8080/
HTTP_PROXY=http://807259361:Password100200!@zaid.com:8080/
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_201
LIB=F:\Jenkins\workspace\DataHub_API_development\node_modules\ibm_db\installer\clidriver\bin;F:\Jenkins\workspace\DataHub_API_development\node_modules\ibm_db\installer\clidriver\lib;F:\Jenkins\workspace\DataHub_API_development\node_modules\ibm_db\installer\clidriver\bin\icc64;
LOCALAPPDATA=C:\Users\sysadmin\AppData\Local
LOGONSERVER=\\SE142201
MAVEN_HOME=F:\Maven-3.6.0
NODE_PATH=C:\Users\sysadmin\AppData\npm\node_modules
NODE_TLS_REJECT_UNAUTHORIZED=0
NUMBER_OF_PROCESSORS=2
OS=Windows_NT
PATH=C:\Oracle;C:\Python27\;C:\Python27\Scripts;C:\Users\sysadmin\.windows-build-tools\python27;C:\Program Files\Java\jdk1.8.0_201\bin;C:\Program Files\nodejs;C:\Windows\System32;C:\Users\sysadmin\.windows-build-tools\python27\;C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\sysadmin\AppData\Roaming\npm\node_modules\windows-build-tools\node_modules\.bin;C:\Users\sysadmin\AppData\Roaming\npm\node_modules\.bin;C:\Python27\;C:\Python27\Scripts;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\EMC NetWorker\nsr\bin;C:\Program Files\avs\bin;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Universal\USap\bin\;F:\Maven-3.6.0\bin;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin\;C:\Users\sysadmin\AppData\Local\Microsoft\WindowsApps;C:\Users\sysadmin\AppData\Roaming\npm;C:\Program Files\MongoDB\Server\3.4\bin;C:\Users\sysadmin\AppData\Local\Programs\Microsoft VS Code\bin;C:\Python27\;C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin;C:\Program Files\nodejs\;
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
pm2=C:\Users\sysadmin\AppData\Roaming\npm\pm2
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 45 Stepping 2, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=2d02
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=$P$G
PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\windows\system32\WindowsPowerShell\v1.0\Modules;C:\Program Files\Microsoft Monitoring Agent\Agent\PowerShell\
PUBLIC=C:\Users\Public
PYTHON=C:\Users\sysadmin\.windows-build-tools\python27
SESSIONNAME=RDP-Tcp#1
SystemDrive=C:
SystemRoot=C:\windows
TEMP=C:\Users\sysadmin\AppData\Local\Temp\2
TMP=C:\Users\sysadmin\AppData\Local\Temp\2
UATDATA=C:\windows\CCM\UATData\D9F8C395-CAB8-491d-B8AC-179A1FE1BE77
USERDOMAIN=SE142201
USERDOMAIN_ROAMINGPROFILE=SE142201
USERNAME=sysadmin
USERPROFILE=C:\Users\sysadmin
VS140COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\
windir=C:\windows

**Comment by bimalkjha** [comment]
@zaidkazi To rule out the long path related issue, you can try below commands:
```
cd \
mkdir nodework
cd nodework
npm install ibm_db
cd node_modules\ibm_db\test
<Update connection info in test\config.testConnectionStrings.json>
node test-basic-test.js
```
Thanks.

**Comment by zaid2telus** [comment]
@bimalkjha I  just tried to deleted all sys env variables for sake of testing except node and still got the issue please advice.

**Comment by bimalkjha** [comment]
@zaidkazi This issue is related with the IBM ODBC Driver internally used by ibm_db for connectivity. Seems some issue with the GSKit libraries which is unable to initialize on this system. 
I would suggest to install [IBM Data Server Driver Package](https://ak-delivery04-mul.dhe.ibm.com/sdfdl/v2/sar/CM/IM/084v4/0/Xa.2/Xb.jusyLTSp44S0QgQgrNZSEmkkLwShwPUOUFBYjrrzK6JzpwwVqta343yOOHs/Xc.CM/IM/084v4/0/v11.1.4fp4a_ntx64_dsdriver_EN.exe/Xd./Xf.LPR.D1vk/Xg.10142285/Xi.habanero/XY.habanero/XZ.03dV1HpTwNlowMptHNf4N0lmNTU/v11.1.4fp4a_ntx64_dsdriver_EN.exe) from here, set env var `IBM_DB_HOME=<install dir of dsdriver>` and then install ibm_db. Please give a try and let me know. 
After installation of of dsdriver, the `db2cli validate` command from testODBCConnection.bat file should work fine from the command line. If validate command fails, then we need new trace files generated by running testODBCConnection.bat file to investigate the issue. Thanks.

**Comment by zaidkazi** [comment]
followed instructions and db2cli when executed nor runs from the server driver installation that is set to IBM_DB_HOME but running testODBCConnection after reinstalling driver and ibmdb node i get same issue. Here is the trace..


[trace.txt](https://github.com/ibmdb/node-ibm_db/files/3071240/trace.txt)

**Comment by zaidkazi** [comment]
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\sysadmin\AppData\Roaming
CLASSPATH=.;C:\PROGRA~1\IBM\IBMDRI~1\java\db2jcc.jar;C:\PROGRA~1\IBM\IBMDRI~1\java\sqlj.zip;C:\PROGRA~1\IBM\IBMDRI~1\bin
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=SE142201
ComSpec=C:\windows\system32\cmd.exe
DEFLOGDIR=C:\ProgramData\McAfee\Endpoint Security\Logs
HOMEDRIVE=C:
HOMEPATH=\Users\sysadmin
IBM_DB_HOME=F:\Jenkins\workspace\DataHub_API_development\node_modules\ibm_db\installer\clidriver
INCLUDE=C:\PROGRA~1\IBM\IBMDRI~1\INCLUDE;C:\PROGRA~1\IBM\IBMDRI~1\LIB
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_201
LIB=F:\Jenkins\workspace\DataHub_API_development\node_modules\ibm_db\installer\clidriver\lib;F:\Jenkins\workspace\DataHub_API_development\node_modules\ibm_db\installer\clidriver\bin;C:\PROGRA~1\IBM\IBMDRI~1\LIB;F:\Jenkins\workspace\DataHub_API_development\node_modules\ibm_db\installer\clidriver\lib;F:\Jenkins\workspace\DataHub_API_development\node_modules\ibm_db\installer\clidriver\bin\icc64;
LOCALAPPDATA=C:\Users\sysadmin\AppData\Local
LOGONSERVER=\\SE142201
MAVEN_HOME=F:\Maven-3.6.0
NODE_PATH=C:\Users\sysadmin\AppData\npm\node_modules
NODE_TLS_REJECT_UNAUTHORIZED=0
NUMBER_OF_PROCESSORS=2
OS=Windows_NT
PATH=F:\Jenkins\workspace\DataHub_API_development\node_modules\ibm_db\installer\clidriver\bin;F:\Jenkins\workspace\DataHub_API_development\node_modules\ibm_db\installer\clidriver\adm;F:\Jenkins\workspace\DataHub_API_development\node_modules\ibm_db\installer\clidriver\lib;C:\Python27\;C:\Python27\Scripts;C:\Users\sysadmin\.windows-build-tools\python27;C:\Program Files\Java\jdk1.8.0_201\bin;C:\Program Files\nodejs;C:\Windows\System32;C:\PROGRA~1\IBM\IBMDRI~1\BIN;C:\Users\sysadmin\.windows-build-tools\python27\;C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\sysadmin\AppData\Roaming\npm\node_modules\windows-build-tools\node_modules\.bin;C:\Users\sysadmin\AppData\Roaming\npm\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\EMC NetWorker\nsr\bin;C:\Program Files\avs\bin;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Universal\USap\bin\;F:\Maven-3.6.0\bin;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin\;C:\Users\sysadmin\AppData\Local\Microsoft\WindowsApps;C:\Users\sysadmin\AppData\Roaming\npm;C:\Program Files\MongoDB\Server\3.4\bin;C:\Users\sysadmin\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin;C:\Program Files\nodejs\
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
pm2=C:\Users\sysadmin\AppData\Roaming\npm\pm2
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 45 Stepping 2, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=2d02
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=$P$G
PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\windows\system32\WindowsPowerShell\v1.0\Modules;C:\Program Files\Microsoft Monitoring Agent\Agent\PowerShell\
PUBLIC=C:\Users\Public
PYTHON=C:\Users\sysadmin\.windows-build-tools\python27
SystemDrive=C:
SystemRoot=C:\windows
TEMP=C:\Users\sysadmin\AppData\Local\Temp
TMP=C:\Users\sysadmin\AppData\Local\Temp
UATDATA=C:\windows\CCM\UATData\D9F8C395-CAB8-491d-B8AC-179A1FE1BE77
USERDOMAIN=SE142201
USERDOMAIN_ROAMINGPROFILE=SE142201
USERNAME=sysadmin
USERPROFILE=C:\Users\sysadmin
VS140COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\
windir=C:\windows

**Comment by zaidkazi** [comment]
[trace.txt](https://github.com/ibmdb/node-ibm_db/files/3071250/trace.txt)


also here i validate that db2 cli is pointing correctly on my system to ibm driver installation

when i say :
F:\Jenkins\workspace\DataHub_API_development\node_modules\ibm_db\installer>where db2cli


it responds
C:\Program Files\IBM\IBMDRIVER\bin\db2cli.exe

**Comment by bimalkjha** [comment]
@zaidkazi Do you mean executing `db2cli validate` command from server driver installation works fine but running through testODBCConnection.bat fails? Please cd to `C:\Program Files\IBM\IBMDRIVER\bin` directory and share the output of below command after updating the connection information in below command:
```
db2cli validate -database "sample:hotel.torolab.ibm.com:21169" -connect -user newton -passwd serverpass
```
It it works, then we need output of testODBCConnection.bat file too. Update the connection info in script before running it. Thanks.

**Comment by zaidkazi** [comment]
they both fail what i attached above is the trace

**Comment by bimalkjha** [comment]
@zaidkazi Have you installed db2 server anytime in this system? Can you confirm the folder `C:\Program Files\ibm\gsk8` exist in your system? If yes, then it is the root cause. Try to remove it from system env variable or rename it. Thanks.

**Comment by bimalkjha** [comment]
In the shared trace file, we can see below logs:
```
5139	data DB2 Common OSSe OSSHLibrary::load cei (3.1.3.84.2.10)
	pid 628 tid 2112 sec 0 nsec 241783179 probe 10
	bytes 38

	Data1 	(PD_TYPE_DEFAULT,14) Hexdump:
	6773 6B38 7373 6C5F 3634 2E64 6C6C         gsk8ssl_64.dll

	Data2 	(PD_TYPE_DEFAULT,8) Hexdump:
	0000 0000 0000 0000                        ........

5144	data DB2 Common Cryptography cryptDynamicLoadGSKitCrypto cei (3.1.14.38.2.140)
	pid 628 tid 2112 sec 0 nsec 245457373 probe 140
	bytes 48

	Data1 	(PD_TYPE_DEFAULT,40) Hexdump:
	4753 4B69 7420 5353 4C20 6861 7665 2062    GSKit SSL have b
	6565 6E20 6C6F 6164 6564 2062 7920 7368    een loaded by sh
	6F72 7420 6E61 6D65                        ort name
......
5394	exit DB2 Common Cryptography cryptContextRealInit cei (2.1.14.31.2)
	pid 628 tid 2112 sec 0 nsec 249505722
	rc = 0x90000403 = -1879047165
......
5399	exit DB2 UDB global services sqlzGetZRCInfo cei (2.3.26.1.2)
	pid 628 tid 2112 cpid -1 node -1 sec 0 nsec 249525021
	rc = 0xFFFFFBEE = -1042
```
Above logs shows -1042 error returned by cryptography function `cryptContextRealInit` which gets translated to `SQL1042C`. The above error comes due to problem with GSKit version. It points that there is some old version of GSKit already installed in the system and ibm_db uses that GSKit as that is set in the system env variable. In the trace file, I do not see GSKit libraries from ibm_db or dsdriver is getting used. Please check your system. You can also search your whole system to find where file `gsk8ssl_64.dll` exists in your system. You need to delete all icc64 folders other than the one under installed dsdriver or under ibm_db. Thanks.

**Comment by zaidkazi** [comment]
i tried that but still facing issue

**Comment by bimalkjha** [comment]
@zaidkazi Is it possible to have a webex session where I can take control of your screen and check what is wrong with the env? Else, if you have IBM Support contact you can open ticket with them as issue is with the installed IBM Driver. You can share the result of db2cli validate to them. Thanks.

**Comment by zaidkazi** [comment]
im unfortunately not able to share screen during the time as its behind a corporate firewall and slightly confidential but we can schedule a time to work have phone call or skype chat

**Comment by bimalkjha** [comment]
@zaidkazi I am busy for 2 days. We can have call on Friday Torronto Morning time. You can mail me the plan on bjha@rocketsoftware.com. Thanks.

**Comment by prakash-aathi** [comment]
@bimalkjha  did you solve the issue?

**Comment by bimalkjha** [comment]
@prakash-aathi Yes.

**Comment by prakash-aathi** [comment]
same problem facing me ..can you explain how you solved it and what the problem is?

**Comment by bimalkjha** [comment]
@prakash-aathi This issue happens due to multiple copies of db2client in the system. The clidriver used by ibm_db is different but you many already have db2 in the system. So, PATH and LIB env vars should point to ibm_db/clidriver to fix the issue. We need to understand in detail about your setup and env to understand the root cause. So, if by correcting env vars, issue is not solved, open a new issue with all the requested details for new issue. Thanks.
