### ISSUE TITLE
odbc driver issue

### ISSUE THREAD

**Issue by rasilva-mission** [ibmdb/node-ibm_db#523]
Hello,

I had this working before but recently opened up the project again and I ran into issue just running my basic script.

Code
`var ibmdb = require('ibm_db');

ibmdb.open("DATABASE=<db>;HOSTNAME=<host>;UID=<userid>;PWD=<userpass>;PORT=<port>;PROTOCOL=<protocol>", function (err,conn) {
  if (err) return console.log("ibm db error", err);

  conn.query('select 1 from sysibm.sysdummy1', function (err, data) {
    if (err) console.log(err);
    else console.log(data);

    conn.close(function () {
      console.log('done');
    });
  });
});`

Issue console output
`node_modules\ibm_db\lib\odbc.js:267
  self.odbc = (options.odbc) ? options.odbc : ((ENV) ? ENV : new odbc.ODBC());
                                                             ^
[object Object]`

**Comment by PriyankaManoharan04** [comment]
@rasilva-mission Can you share your OS and nodejs version.Thanks

**Comment by rasilva-mission** [comment]
@PriyankaManoharan04, 

- Nodejs v10.8.0
- Windows 10 Pro v1803 os build 17134.709

**Comment by rasilva-mission** [comment]
I actually removed this package 'ibm_db' and installed 'ibm_db2' instead

**Comment by bimalkjha** [comment]
@rasilva-mission Please do not use ibm_db2. Its very old and do not get updated. Need to find how to remove it from npm.
Your problem looks same as reported by #168 & #343 . It occurs due to some permission issue. Please go through these two issues and fix your environment and user permissions. Thanks.

**Comment by rasilva-mission** [comment]
Thanks but node-jt400 worked out easier and didn't have to modify my environment
