### ISSUE TITLE
npm install failing in the IBM Cloud Foundry App[Nodejs] 

### ISSUE THREAD

**Issue by lx171717** [ibmdb/node-ibm_db#526]
local window7 node 10 npm 6 is   npm install  no problem.

but in the IBM cloud ,  execute ibmcloud cf push
  > ibm_db@2.5.0 install /tmp/app/node_modules/ibm_db
          > node installer/driverInstall.js

          Rebuild Process: Found clidriver at -> /tmp/app/node_modules/ibm_db/installer/clidriver

          Downloading of clidriver skipped - build is in progress...

          make: Entering directory `/tmp/app/node_modules/ibm_db/build'
          CXX(target) Release/obj.target/odbc_bindings/src/odbc.o
          make: Leaving directory `/tmp/app/node_modules/ibm_db/build'

          { Error: Command failed: node-gyp configure build  --IS_DOWNLOADED=true --IBM_DB_HOME="$IBM_DB_HOME"
          In file included from ../src/odbc.h:27:0,
          from ../src/odbc.cpp:28:
          /tmp/app/node_modules/ibm_db/installer/clidriver/include/sqlcli1.h:41:21: fatal error: windows.h: No such file or directory
          #include <windows.h>
          ^
          compilation terminated.

**Comment by bimalkjha** [comment]
@lx171717 It is similar to the issue reported by #462 . Please read [this](https://github.com/ibmdb/node-ibm_db/issues/462#issuecomment-426953983) for solution. You need to delete your node_modules folder before pushing to cf as the local ibm_db/installer/clidriver is windows specific which will not work on cf which is Linux. Thanks.

**Comment by lx171717** [comment]
Thanks very much  .  After delete my node_modules folder before pushing to cf .

**Comment by Naviar** [comment]
![image](https://user-images.githubusercontent.com/47994107/67740868-55927780-f9e5-11e9-94d9-3eebf24f96a3.png)I have this problem when trying to upload an api in js node with DB2 and to configure the environment variable but it gives me this error, I would appreciate the help

**Comment by bimalkjha** [comment]
@Naviar By looking on error message, it says "make" is not installed in your system. Please make sure these prerequisite are met before installing ibm_db. Thanks.

**Comment by bimalkjha** [comment]
@Naviar Please install make, gcc, g++(gcc-c++), python2.7.x on your system before installing ibm_db. Also, you are using older version of ibm_db@2.5.2. Please use ibm_db@2.6.1. Thanks.
