### ISSUE TITLE
Attempt to connect failed. Errors according port.

### ISSUE THREAD

**Issue by ju4nkA** [ibmdb/node-ibm_db#53]
Hi, I'm having problems to connect to an iSeries DB2.
When I choose **8471** port to connect I have a timeout error and can't  connect.
*{ [Error: [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "10.100.0.25".  Communication function detecting the error: "selectForRecvTimeout".  Protocol specific error code(s): "115", "*", "*".  SQLSTATE=08001]
  errors: [],
  error: '[node-odbc] SQL_ERROR',
  message: '[IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "10.100.0.25".  Communication function detecting the error: "selectForRecvTimeout".  Protocol specific error code(s): "115", "*", "*".  SQLSTATE=08001\n', state: '08001' }*

When I choose **446** port I have and licensing error:
*{ [Error: [IBM][CLI Driver] SQL1598N  An attempt to connect to the database server failed because of a licensing problem.  SQLSTATE=42968]
  errors: [],
  error: '[node-odbc] SQL_ERROR',
  message: '[IBM][CLI Driver] SQL1598N  An attempt to connect to the database server failed because of a licensing problem.  SQLSTATE=42968\n', state: '42968' }*

Wich one it's the correct port (if there is one) and how to solved (if it's possible, 'cause as far as I know, licensing error I need a license, that I do not have) ?

Thx for your help.

**Comment by bimalkjha** [comment]
To connect DB2 for zOS sever and i-Series server using ibm_db driver, you need to get db2connect license from IBM and copy it under ibm_db/installer/clidriver/license folder. Without license file, connection will fail. Thanks.

**Comment by rbonillajr** [comment]
how to find license? I have this problem. 
help me please.

**Comment by bimalkjha** [comment]
Check with your zOS or iSeries sys admin. They should have db2connect licenses, else they need to get it from IBM by contacting IBM support. Thanks.

**Comment by ju4nkA** [comment]
Here https://goo.gl/EImyBF, at the comments, this guy says that he could do it using unixODBC driver. It's really possible? How can I do it? I try but I don't know how is the correct configuration. Coul you help me on this?
Thx.

**Comment by bimalkjha** [comment]
I don't know how they have used unixODBC driver, but for that driver too they need db2connect license file to connect iSeries server. That guy has not mentioned anything about the license file. Thanks.

**Comment by wangleiwan** [comment]
@bimalkjha Hi I am trying to connect to DB2 for iSeries, and I have put the the license file under the designated directory(.../ibm_db/installer/clidriver/license), but I keep getting this security processing failed error, this is the screenshot of my error. 
![image](https://cloud.githubusercontent.com/assets/10186731/20685253/b22bfea4-b581-11e6-98f3-62c4d0584717.png)

Do you have any idea why and how to fix it? Thanks a lot!

**Comment by bimalkjha** [comment]
@wangleiwan please share your client OS name where you are hitting this issue.
Also, could you please update connection info in ibm_db/installer/testODBCConnection.sh file and run it? It will check and verify the connection. If it still fails, please mail me the generated trace files. Thanks.

**Comment by wangleiwan** [comment]
@bimalkjha thanks for your reply. My OS is Windows 7 64-bit. I checked the testODBCConnection.sh file and it says on the top that __The script is only for non-windows platform__ so I didn't update and run it. However, I did update the _config.testConnectionString.json_ file in the test folder and run the _run-tests.js_ file and this is some of the screenshots of the result
![image](https://cloud.githubusercontent.com/assets/10186731/20714160/11e6c152-b619-11e6-85b8-1af3767c3cc8.png)
![image](https://cloud.githubusercontent.com/assets/10186731/20714188/2cdd7b7c-b619-11e6-9392-fc80b22d0e21.png)
![image](https://cloud.githubusercontent.com/assets/10186731/20714281/7d646312-b619-11e6-9f5c-d125d68991a8.png)

Thanks a lot!

**Comment by bimalkjha** [comment]
@wangleiwan Please set below environment variables and run commands to test. Run these commands on command prompt or you can set it in systems environment variable:
```
set IBM_DB_HOME=path_to_ibm_db\installer\clidriver
set PATH=path_to_ibm_db\installer\clidriver\bin;path_to_ibm_db\installer\clidriver\lib;%PATH%
set LIB=path_to_ibm_db\installer\clidriver\lib;path_to_ibm_db\installer\clidriver\bin\icc64;%LIB%
db2trc on -f 1.trc
db2cli validate -database "sample:hotel.torolab.ibm.com:21169" -connect -user newton -passwd serverpass
db2trc off
db2trc flw 1.trc 1.flw
db2trc fmt 1.trc 1.fmt
db2trc fmt -cli 1.trc 1.cli
```
Update the connection information in above `db2cli validate` command before running it. Thanks.

**Comment by wangleiwan** [comment]
@bimalkjha Thanks for the reply. I tried the test, and here is the screenshots, still fails.
![test](https://cloud.githubusercontent.com/assets/10186731/20728063/ffd182c8-b649-11e6-8552-1295c18bc2ae.png)

![test2](https://cloud.githubusercontent.com/assets/10186731/20727922/5a63d4da-b649-11e6-86b5-69399f00acfb.png)

**Comment by bimalkjha** [comment]
@wangleiwan Please share the generated 1.flw and 1.fmt file as requested before.

The error SQL30082N comes from the server. It seems there is some issue with the userid used for connection. Seems some permission issue with this userid on the server. Please try using some other userid if you have. Also, check with sysadmin about the permission with userid. Seems this userid do not have permission for remote connection. Local connection may work. You can also verify it by running below CLP command on server:

`db2 "connect to <dbname> user <userid> using <passwd>"`

Thanks and Regards,
Bimal Jha

**Comment by wangleiwan** [comment]
@bimalkjha Here are the files. [db2Test.zip](https://github.com/ibmdb/node-ibm_db/files/628068/db2Test.zip)     Sorry about that.

I am currently contacting IBM about this issue as well and I will definitely let them know your suggestions. Thank you so very much for your help.

**Comment by bimalkjha** [comment]
@wangleiwan I checked your trace file. I see same error in 1.fmt file.
```
9563    data DB2 UDB National Language Support sqlnlsMessage cei (3.3.56.65.2.170)
    pid 10356 tid 10252 cpid -1 node -1 probe 170
    bytes 105

    Data1   (PD_TYPE_DEFAULT,97) Hexdump:
    5351 4C33 3030 3832 4E20 2053 6563 7572    SQL30082N  Secur
    6974 7920 7072 6F63 6573 7369 6E67 2066    ity processing f
    6169 6C65 6420 7769 7468 2072 6561 736F    ailed with reaso
    6E20 2231 3522 2028 2250 524F 4345 5353    n "15" ("PROCESS
    494E 4720 4641 494C 5552 4522 292E 2020    ING FAILURE").  
    5351 4C53 5441 5445 3D30 3830 3031 0D0A    SQLSTATE=08001..
    00                                         .
```
Your connection failed with SQL30082N error and the reason code is 15. We can see detail about this error here: http://www.ibm.com/support/knowledgecenter/SSEPGG_10.5.0/com.ibm.db2.luw.messages.sql.doc/doc/msql30082n.html

15 (PROCESSING FAILURE)
Security processing at the server failed.

So, you should check with your sysadmin why server fails to process the connection request? Is it some invalid port or this user do not have sufficient permission? This error is coming from server and I do not see any issue with client/driver code. Please check your credentials and port. Thanks.

**Comment by wangleiwan** [comment]
@bimalkjha Thank you so much for your help. I have already talked with sysadmin and they are trying to fix it now. Thanks again for you continuous efforts.
