### ISSUE TITLE
Lastest version doesn't build on zos, affecting sponsor users 

### ISSUE THREAD

**Issue by alexcfyung** [ibmdb/node-ibm_db#530]
Lastest version (Starting from commit 445acb197733aac679dc67106c70625832fa247f) doesn't build on zOS. The issue seems to be removing the build folder before building the binary. Comment out[ line 310 ](https://github.com/ibmdb/node-ibm_db/blob/395d1d256d1274d550faa66ca56e5833f318f81c/installer/driverInstall.js#L310)in install/driverInstall.js seems to fix the issue.

Please fix this asap as it is affecting sponsor users. Thanks.

**Comment by bimalkjha** [comment]
@alexcfyung Please confirm that latest changes has fixed this issue. Thanks.

**Comment by alexcfyung** [comment]
Thank you for the quick fix. The latest changes fixed the issue (`npm install` within the cloned repo), but `npm install ibm_db` still have the same issue. You may need to publish the latest commit to make it have an effect on `npm install ibm_db`.
