### ISSUE TITLE
Travis Build Issues 2.5.1 

### ISSUE THREAD

**Issue by brandonwarech** [ibmdb/node-ibm_db#532]
Setting environment variables from .travis.yml
$ export CXX=g++-4.8
$ export PATH=./node_modules/.bin:$PATH
Updating nvm
nvm.install
4.15s$ nvm install node
Downloading and installing node v12.1.0...
Downloading https://nodejs.org/dist/v12.1.0/node-v12.1.0-linux-x64.tar.xz...
Computing checksum with sha256sum
Checksums matched!
Now using node v12.1.0 (npm v6.9.0)
$ node --version
v12.1.0
$ npm --version
6.9.0
$ nvm --version
0.34.0
before_install.1
0.01s$ cd orchestration-nodeapp
before_install.2
1.23s$ npm install jasmine
npm notice created a lockfile as package-lock.json. You should commit this file.
+ jasmine@3.4.0
added 13 packages from 4 contributors and audited 16 packages in 0.811s
found 0 vulnerabilities
54.11s$ npm install 
npm WARN deprecated watson-developer-cloud@3.18.4: DeprecationWarning: watson-developer-cloud moved to ibm-watson. To get updates, use the new package.
npm WARN deprecated joi@6.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated topo@1.1.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
> websocket@1.0.28 install /home/travis/build/Watson-Implementations-Practice/WBS-Bot-Framework/orchestration-nodeapp/node_modules/websocket
> (node-gyp rebuild 2> builderror.log) || (exit 0)
make: Entering directory `/home/travis/build/Watson-Implementations-Practice/WBS-Bot-Framework/orchestration-nodeapp/node_modules/websocket/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
make: Leaving directory `/home/travis/build/Watson-Implementations-Practice/WBS-Bot-Framework/orchestration-nodeapp/node_modules/websocket/build'
> ibm_db@2.5.1 install /home/travis/build/Watson-Implementations-Practice/WBS-Bot-Framework/orchestration-nodeapp/node_modules/ibm_db
> node installer/driverInstall.js
Downloading DB2 ODBC CLI Driver from https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli//linuxx64_odbc_cli.tar.gz...
100.00% | 21032500 bytes downloaded out of 21032500 bytes.
****************************************
You are downloading a package which includes the Node.js module for IBM DB2/Informix.  The module is licensed under the Apache License 2.0. The package also includes IBM ODBC and CLI Driver from IBM, which is automatically downloaded as the node module is installed on your system/device. The license agreement to the IBM ODBC and CLI Driver is available in undefined   Check for additional dependencies, which may come with their own license agreement(s). Your use of the components of the package and dependencies constitutes your acceptance of their respective license agreements. If you do not accept the terms of any license agreement(s), then delete the relevant component(s) from your device.
****************************************
Downloading and extraction of DB2 ODBC CLI Driver completed successfully ...
make: Entering directory `/home/travis/build/Watson-Implementations-Practice/WBS-Bot-Framework/orchestration-nodeapp/node_modules/ibm_db/build'
  CXX(target) Release/obj.target/odbc_bindings/src/odbc.o
make: Leaving directory `/home/travis/build/Watson-Implementations-Practice/WBS-Bot-Framework/orchestration-nodeapp/node_modules/ibm_db/build'
Error: Command failed: node-gyp configure build  --IS_DOWNLOADED=true --IBM_DB_HOME="$IBM_DB_HOME"
In file included from ../src/odbc.cpp:28:0:
../src/odbc.h:111:26: error: ‘v8::Handle’ has not been declared
     static void Init(v8::Handle<Object> exports);
                          ^
../src/odbc.h:111:32: error: expected ‘,’ or ‘...’ before ‘<’ token
     static void Init(v8::Handle<Object> exports);
                                ^
../src/odbc.h:114:12: error: ‘Handle’ does not name a type
     static Handle<Value> GetColumnValue(SQLHSTMT hStmt, Column column, uint16_t* buffer, int bufferLength);
            ^
../src/odbc.h:115:12: error: ‘Handle’ does not name a type
     static Handle<Value> GetOutputParameter(Parameter prm);
            ^
In file included from ../src/odbc.cpp:28:0:
../src/odbc.h:118:12: error: ‘Handle’ does not name a type
     static Handle<Value> CallbackSQLError(SQLSMALLINT handleType, SQLHANDLE handle, Nan::Callback* cb);
            ^
In file included from ../src/odbc.cpp:29:0:
../src/odbc_connection.h:37:25: error: ‘v8::Handle’ has not been declared
    static void Init(v8::Handle<Object> exports);
                         ^
../src/odbc_connection.h:37:31: error: expected ‘,’ or ‘...’ before ‘<’ token
    static void Init(v8::Handle<Object> exports);
                               ^
In file included from ../src/odbc.cpp:30:0:
../src/odbc_result.h:26:25: error: ‘v8::Handle’ has not been declared
    static void Init(v8::Handle<Object> exports);
                         ^
../src/odbc_result.h:26:31: error: expected ‘,’ or ‘...’ before ‘<’ token
    static void Init(v8::Handle<Object> exports);
                               ^
In file included from ../src/odbc.cpp:31:0:
../src/odbc_statement.h:25:25: error: ‘v8::Handle’ has not been declared
    static void Init(v8::Handle<Object> exports);
                         ^
../src/odbc_statement.h:25:31: error: expected ‘,’ or ‘...’ before ‘<’ token
    static void Init(v8::Handle<Object> exports);
                               ^
../src/odbc.cpp:47:21: error: variable or field ‘Init’ declared void
 void ODBC::Init(v8::Handle<Object> exports)
                     ^
../src/odbc.cpp:47:17: error: ‘Handle’ is not a member of ‘v8’
 void ODBC::Init(v8::Handle<Object> exports)
                 ^
../src/odbc.cpp:47:34: error: expected primary-expression before ‘>’ token
 void ODBC::Init(v8::Handle<Object> exports)
                                  ^
../src/odbc.cpp:47:36: error: ‘exports’ was not declared in this scope
 void ODBC::Init(v8::Handle<Object> exports)
                                    ^
../src/odbc.cpp: In static member function ‘static void ODBC::UV_AfterCreateConnection(uv_work_t*, int)’:
../src/odbc.cpp:210:27: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated (declared at ../../nan/nan.h:1674) [-Wdeprecated-declarations]
     data->cb->Call(1, info);
                           ^
../src/odbc.cpp:222:27: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated (declared at ../../nan/nan.h:1674) [-Wdeprecated-declarations]
     data->cb->Call(2, info);
                           ^
../src/odbc.cpp: At global scope:
../src/odbc.cpp:404:1: error: ‘Handle’ does not name a type
 Handle<Value> ODBC::GetColumnValue( SQLHSTMT hStmt, Column column, 
 ^
../src/odbc.cpp:688:1: error: ‘Handle’ does not name a type
 Handle<Value> ODBC::GetOutputParameter( Parameter prm ) 
 ^
../src/odbc.cpp: In static member function ‘static v8::Local<v8::Object> ODBC::GetRecordTuple(SQLHSTMT, Column*, short int*, uint16_t*, int)’:
../src/odbc.cpp:838:72: error: ‘GetColumnValue’ was not declared in this scope
                 GetColumnValue( hStmt, columns[i], buffer, bufferLength));
                                                                        ^
../src/odbc.cpp: In static member function ‘static v8::Local<v8::Value> ODBC::GetRecordArray(SQLHSTMT, Column*, short int*, uint16_t*, int)’:
../src/odbc.cpp:860:72: error: ‘GetColumnValue’ was not declared in this scope
                 GetColumnValue( hStmt, columns[i], buffer, bufferLength));
                                                                        ^
../src/odbc.cpp: In static member function ‘static Parameter* ODBC::GetParametersFromArray(v8::Local<v8::Array>, int*)’:
../src/odbc.cpp:888:39: warning: ‘v8::Local<v8::Value> v8::Object::Get(uint32_t)’ is deprecated (declared at /home/travis/.node-gyp/12.1.0/include/node/v8.h:3416): Use maybe version [-Wdeprecated-declarations]
     Local<Value> value = values->Get(i);
                                       ^
../src/odbc.cpp:911:31: warning: ‘v8::Local<v8::Value> v8::Object::Get(uint32_t)’ is deprecated (declared at /home/travis/.node-gyp/12.1.0/include/node/v8.h:3416): Use maybe version [-Wdeprecated-declarations]
       val =  paramArray->Get(0); 
                               ^
../src/odbc.cpp:913:51: error: no matching function for call to ‘v8::Value::IntegerValue()’
           params[i].paramtype = val->IntegerValue();
                                                   ^
../src/odbc.cpp:913:51: note: candidate is:
In file included from ../src/odbc.cpp:22:0:
/home/travis/.node-gyp/12.1.0/include/node/v8.h:2565:40: note: v8::Maybe<long int> v8::Value::IntegerValue(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT Maybe<int64_t> IntegerValue(
                                        ^
/home/travis/.node-gyp/12.1.0/include/node/v8.h:2565:40: note:   candidate expects 1 argument, 0 provided
../src/odbc.cpp:915:31: warning: ‘v8::Local<v8::Value> v8::Object::Get(uint32_t)’ is deprecated (declared at /home/travis/.node-gyp/12.1.0/include/node/v8.h:3416): Use maybe version [-Wdeprecated-declarations]
       val =  paramArray->Get(1); 
                               ^
../src/odbc.cpp:917:48: error: no matching function for call to ‘v8::Value::IntegerValue()’
           params[i].c_type = val->IntegerValue();
                                                ^
../src/odbc.cpp:917:48: note: candidate is:
In file included from ../src/odbc.cpp:22:0:
/home/travis/.node-gyp/12.1.0/include/node/v8.h:2565:40: note: v8::Maybe<long int> v8::Value::IntegerValue(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT Maybe<int64_t> IntegerValue(
                                        ^
/home/travis/.node-gyp/12.1.0/include/node/v8.h:2565:40: note:   candidate expects 1 argument, 0 provided
../src/odbc.cpp:921:31: warning: ‘v8::Local<v8::Value> v8::Object::Get(uint32_t)’ is deprecated (declared at /home/travis/.node-gyp/12.1.0/include/node/v8.h:3416): Use maybe version [-Wdeprecated-declarations]
       val =  paramArray->Get(2); 
                               ^
../src/odbc.cpp:923:46: error: no matching function for call to ‘v8::Value::IntegerValue()’
           params[i].type = val->IntegerValue();
                                              ^
../src/odbc.cpp:923:46: note: candidate is:
In file included from ../src/odbc.cpp:22:0:
/home/travis/.node-gyp/12.1.0/include/node/v8.h:2565:40: note: v8::Maybe<long int> v8::Value::IntegerValue(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT Maybe<int64_t> IntegerValue(
                                        ^
/home/travis/.node-gyp/12.1.0/include/node/v8.h:2565:40: note:   candidate expects 1 argument, 0 provided
../src/odbc.cpp:929:35: warning: ‘v8::Local<v8::Value> v8::Object::Get(uint32_t)’ is deprecated (declared at /home/travis/.node-gyp/12.1.0/include/node/v8.h:3416): Use maybe version [-Wdeprecated-declarations]
           val =  paramArray->Get(4); 
                                   ^
../src/odbc.cpp:931:59: error: no matching function for call to ‘v8::Value::IntegerValue()’
               params[i].buffer_length = val->IntegerValue();
                                                           ^
../src/odbc.cpp:931:59: note: candidate is:
In file included from ../src/odbc.cpp:22:0:
/home/travis/.node-gyp/12.1.0/include/node/v8.h:2565:40: note: v8::Maybe<long int> v8::Value::IntegerValue(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT Maybe<int64_t> IntegerValue(
                                        ^
/home/travis/.node-gyp/12.1.0/include/node/v8.h:2565:40: note:   candidate expects 1 argument, 0 provided
../src/odbc.cpp:934:31: warning: ‘v8::Local<v8::Value> v8::Object::Get(uint32_t)’ is deprecated (declared at /home/travis/.node-gyp/12.1.0/include/node/v8.h:3416): Use maybe version [-Wdeprecated-declarations]
       val =  paramArray->Get(3); 
                               ^
../src/odbc.cpp: In static member function ‘static void ODBC::GetStringParam(v8::Local<v8::Value>, Parameter*, int)’:
../src/odbc.cpp:973:44: error: no matching function for call to ‘v8::Value::ToString()’
     Local<String> string = value->ToString();
                                            ^
../src/odbc.cpp:973:44: note: candidates are:
In file included from ../src/odbc.cpp:22:0:
/home/travis/.node-gyp/12.1.0/include/node/v8.h:2528:44: note: v8::MaybeLocal<v8::String> v8::Value::ToString(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
                                            ^
/home/travis/.node-gyp/12.1.0/include/node/v8.h:2528:44: note:   candidate expects 1 argument, 0 provided
In file included from /home/travis/.node-gyp/12.1.0/include/node/v8-internal.h:14:0,
                 from /home/travis/.node-gyp/12.1.0/include/node/v8.h:25,
                 from ../src/odbc.cpp:22:
/home/travis/.node-gyp/12.1.0/include/node/v8.h:2544:35: note: v8::Local<v8::String> v8::Value::ToString(v8::Isolate*) const
                     Local<String> ToString(Isolate* isolate) const);
                                   ^
/home/travis/.node-gyp/12.1.0/include/node/v8config.h:322:3: note: in definition of macro ‘V8_DEPRECATE_SOON’
   declarator __attribute__((deprecated(message)))
   ^
/home/travis/.node-gyp/12.1.0/include/node/v8.h:2544:35: note:   candidate expects 1 argument, 0 provided
                     Local<String> ToString(Isolate* isolate) const);
                                   ^
/home/travis/.node-gyp/12.1.0/include/node/v8config.h:322:3: note: in definition of macro ‘V8_DEPRECATE_SOON’
   declarator __attribute__((deprecated(message)))
   ^
../src/odbc.cpp:989:38: error: no matching function for call to ‘v8::String::Utf8Length()’
         bufflen = string->Utf8Length() + 1;
                                      ^
../src/odbc.cpp:989:38: note: candidate is:
In file included from ../src/odbc.cpp:22:0:
/home/travis/.node-gyp/12.1.0/include/node/v8.h:2678:7: note: int v8::String::Utf8Length(v8::Isolate*) const
   int Utf8Length(Isolate* isolate) const;
       ^
/home/travis/.node-gyp/12.1.0/include/node/v8.h:2678:7: note:   candidate expects 1 argument, 0 provided
../src/odbc.cpp:1009:49: error: no matching function for call to ‘v8::String::WriteUtf8(char*)’
         string->WriteUtf8((char *) param->buffer);
                                                 ^
../src/odbc.cpp:1009:49: note: candidate is:
In file included from ../src/odbc.cpp:22:0:
/home/travis/.node-gyp/12.1.0/include/node/v8.h:2738:7: note: int v8::String::WriteUtf8(v8::Isolate*, char*, int, int*, int) const
   int WriteUtf8(Isolate* isolate, char* buffer, int length = -1,
       ^
/home/travis/.node-gyp/12.1.0/include/node/v8.h:2738:7: note:   candidate expects 5 arguments, 1 provided
../src/odbc.cpp:1016:54: error: no matching function for call to ‘v8::String::WriteOneByte(uint8_t*)’
         string->WriteOneByte((uint8_t *)param->buffer);
                                                      ^
../src/odbc.cpp:1016:54: note: candidate is:
In file included from ../src/odbc.cpp:22:0:
/home/travis/.node-gyp/12.1.0/include/node/v8.h:2735:7: note: int v8::String::WriteOneByte(v8::Isolate*, uint8_t*, int, int, int) const
   int WriteOneByte(Isolate* isolate, uint8_t* buffer, int start = 0,
       ^
/home/travis/.node-gyp/12.1.0/include/node/v8.h:2735:7: note:   candidate expects 5 arguments, 1 provided
../src/odbc.cpp:1024:49: error: no matching function for call to ‘v8::String::WriteUtf8(char*)’
         string->WriteUtf8((char *) param->buffer);
                                                 ^
../src/odbc.cpp:1024:49: note: candidate is:
In file included from ../src/odbc.cpp:22:0:
/home/travis/.node-gyp/12.1.0/include/node/v8.h:2738:7: note: int v8::String::WriteUtf8(v8::Isolate*, char*, int, int*, int) const
   int WriteUtf8(Isolate* isolate, char* buffer, int length = -1,
       ^
/home/travis/.node-gyp/12.1.0/include/node/v8.h:2738:7: note:   candidate expects 5 arguments, 1 provided
../src/odbc.cpp: In static member function ‘static void ODBC::GetInt32Param(v8::Local<v8::Value>, Parameter*, int)’:
../src/odbc.cpp:1067:56: error: no matching function for call to ‘v8::Value::IntegerValue()’
     int64_t  *number = new int64_t(value->IntegerValue());
                                                        ^
../src/odbc.cpp:1067:56: note: candidate is:
In file included from ../src/odbc.cpp:22:0:
/home/travis/.node-gyp/12.1.0/include/node/v8.h:2565:40: note: v8::Maybe<long int> v8::Value::IntegerValue(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT Maybe<int64_t> IntegerValue(
                                        ^
/home/travis/.node-gyp/12.1.0/include/node/v8.h:2565:40: note:   candidate expects 1 argument, 0 provided
../src/odbc.cpp: In static member function ‘static void ODBC::GetNumberParam(v8::Local<v8::Value>, Parameter*, int)’:
../src/odbc.cpp:1083:54: error: no matching function for call to ‘v8::Value::NumberValue()’
     double *number   = new double(value->NumberValue());
                                                      ^
../src/odbc.cpp:1083:54: note: candidate is:
In file included from ../src/odbc.cpp:22:0:
/home/travis/.node-gyp/12.1.0/include/node/v8.h:2564:39: note: v8::Maybe<double> v8::Value::NumberValue(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT Maybe<double> NumberValue(Local<Context> context) const;
                                       ^
/home/travis/.node-gyp/12.1.0/include/node/v8.h:2564:39: note:   candidate expects 1 argument, 0 provided
../src/odbc.cpp: In static member function ‘static void ODBC::GetBoolParam(v8::Local<v8::Value>, Parameter*, int)’:
../src/odbc.cpp:1104:53: error: no matching function for call to ‘v8::Value::BooleanValue()’
     bool *boolean    = new bool(value->BooleanValue());
                                                     ^
../src/odbc.cpp:1104:53: note: candidates are:
In file included from ../src/odbc.cpp:22:0:
/home/travis/.node-gyp/12.1.0/include/node/v8.h:2559:8: note: bool v8::Value::BooleanValue(v8::Isolate*) const
   bool BooleanValue(Isolate* isolate) const;
        ^
/home/travis/.node-gyp/12.1.0/include/node/v8.h:2559:8: note:   candidate expects 1 argument, 0 provided
In file included from /home/travis/.node-gyp/12.1.0/include/node/v8-internal.h:14:0,
                 from /home/travis/.node-gyp/12.1.0/include/node/v8.h:25,
                 from ../src/odbc.cpp:22:
/home/travis/.node-gyp/12.1.0/include/node/v8.h:2562:51: note: v8::Maybe<bool> v8::Value::BooleanValue(v8::Local<v8::Context>) const
                 V8_WARN_UNUSED_RESULT Maybe<bool> BooleanValue(
                                                   ^
/home/travis/.node-gyp/12.1.0/include/node/v8config.h:307:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
/home/travis/.node-gyp/12.1.0/include/node/v8.h:2562:51: note:   candidate expects 1 argument, 0 provided
                 V8_WARN_UNUSED_RESULT Maybe<bool> BooleanValue(
                                                   ^
/home/travis/.node-gyp/12.1.0/include/node/v8config.h:307:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../src/odbc.cpp: At global scope:
../src/odbc.cpp:1174:1: error: ‘Handle’ does not name a type
 Handle<Value> ODBC::CallbackSQLError (SQLSMALLINT handleType,
 ^
../src/odbc.cpp: In static member function ‘static v8::Local<v8::Value> ODBC::CallbackSQLError(SQLSMALLINT, SQLHANDLE, char*, Nan::Callback*)’:
../src/odbc.cpp:1203:19: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated (declared at ../../nan/nan.h:1674) [-Wdeprecated-declarations]
   cb->Call(1, info);
                   ^
../src/odbc.cpp: In static member function ‘static v8::Local<v8::Value> ODBC::GetSQLError(SQLSMALLINT, SQLHANDLE, char*)’:
../src/odbc.cpp:1240:60: warning: ‘bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)’ is deprecated (declared at /home/travis/.node-gyp/12.1.0/include/node/v8.h:3358): Use maybe version [-Wdeprecated-declarations]
   objError->Set(Nan::New("errors").ToLocalChecked(), errors);
                                                            ^
../src/odbc.cpp:1260:91: warning: ‘bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)’ is deprecated (declared at /home/travis/.node-gyp/12.1.0/include/node/v8.h:3358): Use maybe version [-Wdeprecated-declarations]
       objError->Set(Nan::New("error").ToLocalChecked(), Nan::New(message).ToLocalChecked());
                                                                                           ^
../src/odbc.cpp:1268:98: warning: ‘bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)’ is deprecated (declared at /home/travis/.node-gyp/12.1.0/include/node/v8.h:3358): Use maybe version [-Wdeprecated-declarations]
       objError->Set(Nan::New("message").ToLocalChecked(), Nan::New(errorMessage).ToLocalChecked());
                                                                                                  ^
../src/odbc.cpp:1269:97: warning: ‘bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)’ is deprecated (declared at /home/travis/.node-gyp/12.1.0/include/node/v8.h:3358): Use maybe version [-Wdeprecated-declarations]
       objError->Set(Nan::New("state").ToLocalChecked(), Nan::New(errorSQLState).ToLocalChecked());
                                                                                                 ^
../src/odbc.cpp:1270:75: warning: ‘bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)’ is deprecated (declared at /home/travis/.node-gyp/12.1.0/include/node/v8.h:3358): Use maybe version [-Wdeprecated-declarations]
       objError->Set(Nan::New("sqlcode").ToLocalChecked(), Nan::New(native));
                                                                           ^
../src/odbc.cpp: In static member function ‘static v8::Local<v8::Array> ODBC::GetAllRecordsSync(SQLHENV, SQLHDBC, SQLHSTMT, uint16_t*, int)’:
../src/odbc.cpp:1340:5: warning: ‘bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)’ is deprecated (declared at /home/travis/.node-gyp/12.1.0/include/node/v8.h:3358): Use maybe version [-Wdeprecated-declarations]
     );
     ^
../src/odbc.cpp: In function ‘void node_register_module_v72(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Context>)’:
../src/odbc.cpp:1350:20: error: no matching function for call to ‘ODBC::Init(v8::Local<v8::Object>&)’
  ODBC::Init(exports);
                    ^
../src/odbc.cpp:1350:20: note: candidate is:
In file included from ../src/odbc.cpp:28:0:
../src/odbc.h:111:17: note: static void ODBC::Init(int)
     static void Init(v8::Handle<Object> exports);
                 ^
../src/odbc.h:111:17: note:   no known conversion for argument 1 from ‘v8::Local<v8::Object>’ to ‘int’
../src/odbc.cpp:1351:26: error: no matching function for call to ‘ODBCResult::Init(v8::Local<v8::Object>&)’
  ODBCResult::Init(exports);
                          ^
../src/odbc.cpp:1351:26: note: candidate is:
In file included from ../src/odbc.cpp:30:0:
../src/odbc_result.h:26:16: note: static void ODBCResult::Init(int)
    static void Init(v8::Handle<Object> exports);
                ^
../src/odbc_result.h:26:16: note:   no known conversion for argument 1 from ‘v8::Local<v8::Object>’ to ‘int’
../src/odbc.cpp:1352:30: error: no matching function for call to ‘ODBCConnection::Init(v8::Local<v8::Object>&)’
  ODBCConnection::Init(exports);
                              ^
../src/odbc.cpp:1352:30: note: candidate is:
In file included from ../src/odbc.cpp:29:0:
../src/odbc_connection.h:37:16: note: static void ODBCConnection::Init(int)
    static void Init(v8::Handle<Object> exports);
                ^
../src/odbc_connection.h:37:16: note:   no known conversion for argument 1 from ‘v8::Local<v8::Object>’ to ‘int’
../src/odbc.cpp:1353:29: error: no matching function for call to ‘ODBCStatement::Init(v8::Local<v8::Object>&)’
  ODBCStatement::Init(exports);
                             ^
../src/odbc.cpp:1353:29: note: candidate is:
In file included from ../src/odbc.cpp:31:0:
../src/odbc_statement.h:25:16: note: static void ODBCStatement::Init(int)
    static void Init(v8::Handle<Object> exports);
                ^
../src/odbc_statement.h:25:16: note:   no known conversion for argument 1 from ‘v8::Local<v8::Object>’ to ‘int’
../src/odbc.cpp: At global scope:
../src/odbc.cpp:1356:26: error: variable or field ‘init’ declared void
 extern "C" void init(v8::Handle<Object> exports)
                          ^
../src/odbc.cpp:1356:22: error: ‘Handle’ is not a member of ‘v8’
 extern "C" void init(v8::Handle<Object> exports)
                      ^
../src/odbc.cpp:1356:39: error: expected primary-expression before ‘>’ token
 extern "C" void init(v8::Handle<Object> exports)
                                       ^
../src/odbc.cpp:1356:41: error: ‘exports’ was not declared in this scope
 extern "C" void init(v8::Handle<Object> exports)
                                         ^
In file included from ../src/odbc.cpp:23:0:
../src/odbc.cpp:1364:28: error: ‘init’ was not declared in this scope
 NODE_MODULE(odbc_bindings, init)
                            ^
/home/travis/.node-gyp/12.1.0/include/node/node.h:556:36: note: in definition of macro ‘NODE_MODULE_X’
       (node::addon_register_func) (regfunc),                          \
                                    ^
../src/odbc.cpp:1364:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(odbc_bindings, init)
 ^
make: *** [Release/obj.target/odbc_bindings/src/odbc.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/travis/.nvm/versions/node/v12.1.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Linux 4.4.0-101-generic
gyp ERR! command "/home/travis/.nvm/versions/node/v12.1.0/bin/node" "/home/travis/.nvm/versions/node/v12.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build" "--IS_DOWNLOADED=true" "--IBM_DB_HOME=/home/travis/build/Watson-Implementations-Practice/WBS-Bot-Framework/orchestration-nodeapp/node_modules/ibm_db/installer/clidriver"
gyp ERR! cwd /home/travis/build/Watson-Implementations-Practice/WBS-Bot-Framework/orchestration-nodeapp/node_modules/ibm_db
gyp ERR! node -v v12.1.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
    at ChildProcess.exithandler (child_process.js:304:12)
    at ChildProcess.emit (events.js:196:13)
    at maybeClose (internal/child_process.js:1000:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:5) {
  killed: [secure],
  code: 1,
  signal: null,
  cmd: 'node-gyp configure build  ' +
    '--IS_DOWNLOADED=true ' +
    '--IBM_DB_HOME="$IBM_DB_HOME"'
}
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ibm_db@2.5.1 install: `node installer/driverInstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ibm_db@2.5.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2019-05-03T15_57_40_450Z-debug.log

**Comment by bimalkjha** [comment]
@brandonwarech Its not an issue with ibm_db 2.5.1 but you are getting error due to use of node.js v12.1.0. Please use lower version of node.js as ibm_db do not support node v12.x yet.
This issue seems duplicate of issue #528 , hence closing it. Thanks.

**Comment by rj00553657** [comment]
Hi for me the node js version is v10.15.3, but still I am gettiing the same above error.
Can you guys lets me know which node js version is supported.

Below is my error.

`root@mycluster:~/icp-airways-master/icp-backend/booking-microservice# npm i

> ibm_db@2.5.1 install /root/icp-airways-master/icp-backend/booking-microservice/node_modules/ibm_db
> node installer/driverInstall.js

internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module '/root/icp-airways-master/icp-backend/booking-microservice/node_modules/ibm_db/installer/driverInstall.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm WARN icp-backend@1.0.0 No description
npm WARN icp-backend@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"ppc64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ibm_db@2.5.1 install: `node installer/driverInstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ibm_db@2.5.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-05-07T07_50_52_766Z-debug.log
root@mycluster:~/icp-airways-master/icp-backend/booking-microservice# node -v
v10.15.3
`

**Comment by bimalkjha** [comment]
@rj00553657 Your issue is different than the one mentioned here. Please open a new issue with complete output of `npm install ibm_db`. From the shared output, we can figure out that you are installing on a LinuxPPC64 system and there is some error from installer/driverInstall.js file. But, what is the exact error and from which line; is not clear. Such error mostly comes due to issue with previous steps, so we need complete install output. Thanks.
