### ISSUE TITLE
Windows 7, issues when building ibmdb

### ISSUE THREAD

**Issue by PAnilReddy** [ibmdb/node-ibm_db#533]
I am trying to install "ibm_db": "2.2.1" using package json,
Windows 7
Node: v8.10.0
NPM:  5.6.0
I get the following error after the DB is downloaded and when trying to build configure the DB.
error log attached
[IBM-DB.txt](https://github.com/ibmdb/node-ibm_db/files/3144305/IBM-DB.txt)

**Comment by bimalkjha** [comment]
@PAnilReddy This issue is due to "ibm_db": "2.2.1". Please use latest version of ibm_db to fix it. You can run `npm install ibm_db@2.5.1` Thanks.
