### ISSUE TITLE
Npm install issue on Windows10

### ISSUE THREAD

**Issue by ParkerOu** [ibmdb/node-ibm_db#534]
I found similar issue here: https://github.com/ibmdb/node-ibm_db/issues/453
However, I used ibm_db@2.5.1 which support for Node V10.X.
I also set "clidriver" directory path to "IBM_DB_HOME" environment variable.
One thing I don't know how to do: add the SSL certificate to my system https://github.com/ibmdb/node-ibm_db/issues/400#issuecomment-402103418
What might be wrong?

Here's my error:
```
{ Error: Command failed: node-gyp configure build  --IS_DOWNLOADED=true --IBM_DB_HOME=$IBM_DB_HOME
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\User\AppData\Local\Programs\Python\Python36\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:289:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "D:\\useful\\node\\node.exe" "D:\\useful\\node\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "build" "--IS_DOWNLOADED=true" "--IBM_DB_HOME=$IBM_DB_HOME"
gyp ERR! cwd D:\work\API\test-db2\node_modules\ibm_db
gyp ERR! node -v v10.11.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

    at ChildProcess.exithandler (child_process.js:289:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   'node-gyp configure build  --IS_DOWNLOADED=true --IBM_DB_HOME=$IBM_DB_HOME' }

node-gyp build process failed!

Proceeding with Pre-compiled Binary Installation.


===================================
node-ibm_db installed successfully!
===================================
```

**Comment by PriyankaManoharan04** [comment]
@ParkerOu 

> node-ibm_db installed successfully!

This message implies that your ibm_db has been installed successfully.Under the test folder update your connection string in `config.testConnectionStrings.json` file and run `node test-basic-test.js` and if you can able to get the output then there is no problem with ibm_db installation process. Thanks

**Comment by ParkerOu** [comment]
@PriyankaManoharan04 
test-basic-test.js output:
```
  self.odbc = (options.odbc) ? options.odbc : ((ENV) ? ENV : new odbc.ODBC());
                                                             ^
[object Object]
```

**Comment by PriyankaManoharan04** [comment]
@ParkerOu  Your problem looks same as reported by #168 & #343 . It occurs due to some permission issue. Please go through these two issues and fix your environment and user permissions. Thanks.

**Comment by ParkerOu** [comment]
@PriyankaManoharan04 
Sorry. I still don't understand how to do it.
https://github.com/ibmdb/node-ibm_db/issues/168#issuecomment-300155925 「 I just started the other ODBC exe file from this link and once I did not see that popup entering 'System DNS'...」>> What ODBC exe file? 

run `test-basic-test.js` as administrator output:
```
{ [Error: [IBM][CLI Driver] SQL30081N  �w������@�ӳq�T���~�C���b�ϥΪ��q�T��w�G"TCP/IP"�C���b�ϥΪ
��q�T API�G"SOCKETS"�C ��������~����m�G"192.1.1.252"�C ��������~���q�T��ơG"selectForConnec
tTimeout"�C �q�T��w�S�w�����~�X�G"0"�B"*"�B"*"�C  SQLSTATE=08001
]
  errors: [],
  error: '[node-odbc] SQL_ERROR',
  message:
   '[IBM][CLI Driver] SQL30081N  �w������@�ӳq�T���~�C���b�ϥΪ��q�T��w�G"TCP/IP"�C���b�ϥΪ��q�
T API�G"SOCKETS"�C ��������~����m�G"192.1.1.222"�C ��������~���q�T��ơG"selectForConnectTimeou
t"�C �q�T��w�S�w�����~�X�G"0"�B"*"�B"*"�C  SQLSTATE=08001\r\n',
  state: '08001',
  sqlcode: -30081 }
assert.js:83
  throw new AssertionError(obj);
  ^

AssertionError [ERR_ASSERTION]: { [Error: [IBM][CLI Driver] SQL30081N  �w������@�ӳq�T���~�C���b�ϥΪ��q�T
��w�G"TCP/IP"�C���b�ϥΪ��q�T API�G"SOCKETS"�C ��������~... == null
    at D:\work\API\test-db2\node_modules\ibm_db\test\test-basic-test.js:9:10
    at D:\work\API\test-db2\node_modules\ibm_db\lib\odbc.js:111:11
    at D:\work\API\test-db2\node_modules\ibm_db\lib\odbc.js:332:18
```

**Comment by ParkerOu** [comment]
My case was connected to AS400/DB2.
I must have db2connect license of version 11.1, so that I can connect to AS400/DB2.

**Comment by lfpei** [comment]
windowsrebuild一直失败，按照96的操作，然后打开会说无效的win32程序

**Comment by lfpei** [comment]
windows rebuild ibm_db一直失败，按照#96的操作，然后打开会说无效的win32程序

**Comment by bimalkjha** [comment]
@lfpei  Do not use `npm rebuild` on windows. Always use `npm install` under the ibm_db directory to rebuild it. Also, make sure you have installed VS2015 or later and msbuild.exe is in PATH system environment variable to compile ibm_db on Windows. Thanks.

**Comment by lfpei** [comment]
我是先npm install ibm_db，然后按照 #96 重新编译，node中require('ibm_db')的时候，报错不是有效的win32程序，我是win10系统，安装有VS2017

**Comment by bimalkjha** [comment]
@lfpei Recommended way to rebuild `ibm_db` is to use `npm install` under ibm_db directory. For manual build, follow the instructions as documented [here](https://github.com/ibmdb/node-ibm_db/blob/master/INSTALL.md#-9-node-ibm_db-how-to-manually-build-on-windows). Thanks.

**Comment by lfpei** [comment]
执行 msbuild build/binding.sln /clp:Verbosity=minimal /nologo /p:Configuration=Release;Platform=x64 命令时报错：error MSB4019：未找到导入的项目“C:\Microsoft.Cpp.Default.props”

**Comment by lfpei** [comment]
也安装了windows-build-tools
