### ISSUE TITLE
Error while installing ibm db2 on ubuntu 14.1 npm ERR! ibm_db@2.5.1 install: `node installer/driverInstall.js`

### ISSUE THREAD

**Issue by sh-git** [ibmdb/node-ibm_db#535]
Hi !! 
My team is trying to install ibm_db on ubuntu 14.4 using node version node 9.11.2. The commands are run as root user. But this fails with the following error,
+ npm i ibm_db
> ibm_db@2.5.1 install /home/jenkins/workspace/XXXX/node_modules/ibm_db
> node installer/driverInstall.js

internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module '/home/jenkins/workspace/XXXX/node_modules/ibm_db/installer/driverInstall.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ibm_db@2.5.1 install: `node installer/driverInstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ibm_db@2.5.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
  
We will need assistance on this. The steps followed are,
apt-get install unixodbc build-essential g++
npm install -g node-gyp
npm i ibm_db
npm i odbc

**Comment by PriyankaManoharan04** [comment]
@sh-git 


> apt-get install unixodbc build-essential g++

No need to install unixodbc because ibm_db uses ibm_db odbc. Just run the command `npm install ibm_db`and provide the complete output of npm install ibm_db.

**Comment by sh-git** [comment]
Hi Priyanka,
Our original requirement was to get odbc node-module working,
I was able to get past the issue using the following steps,
  Step 3: Setup the environment for ibm_db
apt-get install unixodbc unixodbc-dev g++ git
npm i ibm_db -unsafe-perm


Step 4: Setup environment for odbc
Install node-gyp https://www.npmjs.com/package/node-gyp
npm install --save nan
##Install node at the global level /usr/bin/node-gyp -> /usr/lib/node_modules/node-gyp/bin/node-gyp.js
npm install -g node-gyp 

git clone git://github.com/wankdanker/node-odbc.git
cd node-odbc
node-gyp configure build
cd ..
npm i odbc -unsafe-perm
npm install
Thanks
Shanthi
