### ISSUE TITLE
db2dsdriver.cfg ACR doesn't work

### ISSUE THREAD

**Issue by leonimurilo** [ibmdb/node-ibm_db#537]
My team have been having the pool connection drop issue like [this](https://github.com/ibmdb/node-ibm_db/issues/474) and [this](https://github.com/ibmdb/node-ibm_db/issues/270).

We wrote the db2dsdriver.cfg file and we put it in the node_modules directory running a shell script like this:
`cp internals/config/db2/db2dsdriver.cfg node_modules/ibm_db/installer/clidriver/cfg/db2dsdriver.cfg;`

The problem is that it seems not to be working. Since the connection drop error is uncommon (but happens), we had to test using a a hostname that doesn't exist as an alternate server and then the real server as a second option.

Our db2dsdriver.cfg file is like this:
(I renamed the host name for private purposes)

```xml
<!-- https://www.ibm.com/support/knowledgecenter/en/SSEPGG_11.1.0/com.ibm.db2.luw.apdv.cli.doc/doc/c0056065.html -->
<configuration>
    <dsncollection>
        <!-- DEV, QA and PROD -->
        <dsn alias="dev" name="DSN4DEV" host="falseserver.db.com" port="5001"/>
        <dsn alias="qa" name="DSN8DEV" host="realserver.db.com" port="5008"/>
    </dsncollection>
    <databases>
        <!-- DEV: -->
        <database name="DSN4DEV" host="falseserver.db.com" port="5001">
            <!-- automatic client reroute (ACR)  -->
            <acr>
                <parameter name="enableACR" value="true"/>
                <parameter name="enableSeamlessACR" value="true"/>
                <!-- Specifies the number of seconds to wait between consecutive connection attempts. -->
                <parameter name="acrRetryInterval" value="1"/>
                <parameter name="maxAcrRetries" value="30"/>
                <parameter name="affinityFailbackInterval" value="1"/>
                <alternateserverlist>
                    <server name="S1" hostname="falseserver.db.com" port="5001"/>
                    <server name="S2" hostname="realserver.db.com" port="5001"/>
                </alternateserverlist>
                <affinitylist>
                  <list name="list1" serverorder="S1,S2"/>
                </affinitylist>
            </acr>
        </database>
        <!-- QA: -->
        <database name="DSN4DEV" host="falseserver.db.com" port="5008">
            <!-- automatic client reroute (ACR)  -->
            <acr>
                <parameter name="enableACR" value="true"/>
                <parameter name="enableSeamlessACR" value="true"/>
                <!-- Specifies the number of seconds to wait between consecutive connection attempts. -->
                <parameter name="acrRetryInterval" value="1"/>
                <parameter name="maxAcrRetries" value="30"/>
                <parameter name="affinityFailbackInterval" value="1"/>
                <alternateserverlist>
                    <server name="S1" hostname="falseserver.db.com" port="5008"/>
                    <server name="S2" hostname="realserver.db.com" port="5008"/>
                </alternateserverlist>
                <affinitylist>
                  <list name="list1" serverorder="S1,S2"/>
                </affinitylist>
            </acr>
        </database>
        <!-- Local IPC connection -->
        <database name="name3" host="localhost" port="0">
            <parameter name="IPCInstance" value="DB2"/>
            <parameter name="CommProtocol" value="IPC"/>
        </database>
    </databases>
</configuration>

```

When I tested with this file, I expected the db not to find the "falseServer" and then trying to connect to the "realserver".

By the way, the file passed the `db2cli validate` validation.

The connection string we are using on our code is:
`'DRIVER={DB2};HOSTNAME=falseserver.db.com;PORT=5001;DATABASE=DSN4DEV;TCPIP;UID=<HIDDEN>;PWD=<HIDDEN>;'`

Is there anything wrong with the file?

**Comment by PriyankaManoharan04** [comment]
@leonimurilo 

Hi,

There are few changes to be made in your `cfg` file.

> ```
> <server name="S2" hostname="realserver.db.com" port="5001"/>
> ```

Here the port number for the second server is incorrect.

> ```
>  <database name="DSN4DEV" host="falseserver.db.com" port="5008">
> ```

Here you should have realserver  in the QA.


> ```
>   <server name="S1" hostname="falseserver.db.com" port="5008"/>
> ```

Again here you have mentioned the incorrect port number.

`Modify your cfg file as given below and check can you able to solve this issue.

<configuration>
    <dsncollection>
        
        <dsn alias="dev" name="DSN4DEV" host="falseserver.db.com" port="5001"/>
        <dsn alias="qa" name="DSN8DEV" host="realserver.db.com" port="5008"/>
    </dsncollection>
    <databases>
        
        <database name="DSN4DEV" host="falseserver.db.com" port="5001">
            
            <parameter name="userid" value="userid"/>
            <parameter name="password" value="password"/>
            <acr>
                <parameter name="enableACR" value="true"/>
                <parameter name="enableSeamlessACR" value="true"/>
                <parameter name="acrRetryInterval" value="2"/>
                <parameter name="maxAcrRetries" value="30"/>
                <parameter name="affinityFailbackInterval" value="2"/>
                <alternateserverlist>
                    <server name="S1" hostname="realserver.db.com" port="5008"/>
                    <server name="S2" hostname="falseserver.db.com" port="5001"/>
                </alternateserverlist>
                <affinitylist>
                  <list name="list1" serverorder="S1,S2"/>
                </affinitylist>
                <clientaffinitydefined>
                    <client name="client1" hostname="localhost" listname="list1"/>
                </clientaffinitydefined>
            </acr>
        </database>
        
        <database name="DSN8DEV" host="realserver.db.com" port="5008">
            
            <parameter name="userid" value="userid"/>
            <parameter name="password" value="password"/>
            <acr>
                <parameter name="enableACR" value="true"/>
                <parameter name="enableSeamlessACR" value="true"/>
                <parameter name="acrRetryInterval" value="2"/>
                <parameter name="maxAcrRetries" value="30"/>
				<parameter name="affinityFailbackInterval" value="2"/>
                <alternateserverlist>
                    <server name="S1" hostname="falseserver.db.com" port="5001"/>
                    <server name="S2" hostname="realserver.db.com" port="5008"/>
                </alternateserverlist>
                <affinitylist>
                  <list name="list2" serverorder="S1,S2"/>
                </affinitylist>
                <clientaffinitydefined>
                    <client name="client1" hostname="localhost" listname="list2"/>
                </clientaffinitydefined>
            </acr>
        </database>
     </databases>
</configuration>`

Thanks.

**Comment by PriyankaManoharan04** [comment]
@leonimurilo 

Hi,

There are few changes to be made in your `cfg` file.

> ```
> <server name="S2" hostname="realserver.db.com" port="5001"/>
> ```

Here the port number for the second server is incorrect.

> ```
>  <database name="DSN4DEV" host="falseserver.db.com" port="5008">
> ```

Here you should have realserver  in the QA.


> ```
>   <server name="S1" hostname="falseserver.db.com" port="5008"/>
> ```

Again here you have mentioned the incorrect port number.

Modify your cfg file as given below and check can you able to solve this issue.

```
<configuration>
    <dsncollection>
        <!-- DEV, QA and PROD -->
        <dsn alias="dev" name="DSN4DEV" host="falseserver.db.com" port="5001"/>
        <dsn alias="qa" name="DSN8DEV" host="realserver.db.com" port="5008"/>
    </dsncollection>
    <databases>
        <!-- DEV: -->
        <database name="DSN4DEV" host="falseserver.db.com" port="5001">
            <!-- automatic client reroute (ACR)  -->
            <parameter name="userid" value="userid"/>
            <parameter name="password" value="password"/>
            <acr>
                <parameter name="enableACR" value="true"/>
                <parameter name="enableSeamlessACR" value="true"/>
                <parameter name="acrRetryInterval" value="2"/>
                <parameter name="maxAcrRetries" value="30"/>
                <parameter name="affinityFailbackInterval" value="2"/>
                <alternateserverlist>
                    <server name="S1" hostname="realserver.db.com" port="5008"/>
                    <server name="S2" hostname="falseserver.db.com" port="5001"/>
                </alternateserverlist>
                <affinitylist>
                  <list name="list1" serverorder="S1,S2"/>
                </affinitylist>
                <clientaffinitydefined>
                    <client name="client1" hostname="localhost" listname="list1"/>
                </clientaffinitydefined>
            </acr>
        </database>
        <!-- QA: -->
        <database name="DSN8DEV" host="realserver.db.com" port="5008">
            <!-- automatic client reroute (ACR)  -->
            <parameter name="userid" value="userid"/>
            <parameter name="password" value="password"/>
            <acr>
                <parameter name="enableACR" value="true"/>
                <parameter name="enableSeamlessACR" value="true"/>
                <parameter name="acrRetryInterval" value="2"/>
                <parameter name="maxAcrRetries" value="30"/>
				<parameter name="affinityFailbackInterval" value="2"/>
                <alternateserverlist>
                    <server name="S1" hostname="falseserver.db.com" port="5001"/>
                    <server name="S2" hostname="realserver.db.com" port="5008"/>
                </alternateserverlist>
                <affinitylist>
                  <list name="list2" serverorder="S1,S2"/>
                </affinitylist>
                <clientaffinitydefined>
                    <client name="client1" hostname="localhost" listname="list2"/>
                </clientaffinitydefined>
            </acr>
        </database>
     </databases>
</configuration>

```
Thanks.
