### ISSUE TITLE
db2 on z/OS does not support Boolean causing failing test case

### ISSUE THREAD

**Issue by alexcfyung** [ibmdb/node-ibm_db#541]
Since db2 on z/OS does not support boolean type, the test case `test-all-data-types.js` failed at create table line. I suggest adding a check and exclude boolean if it is in z/OS.

**Comment by PriyankaManoharan04** [comment]
@alexcfyung We have delivered the fix for this issue. You can clone the code from master branch and test can you able to run the test file `test-all-data-types.js` in z/OS

Thanks.

**Comment by alexcfyung** [comment]
@PriyankaManoharan04 Thank you the fix fixes this issue. However, `test-all-data-types.js` still failed because of the other issue #542
