### ISSUE TITLE
Frequent Connection Loss from DB2

### ISSUE THREAD

**Issue by Hasneet** [ibmdb/node-ibm_db#543]
My Node application when first started makes a connection using connection pooling concept with maxpoolsize(2) to a DB2 on IBM Cloud, after few hours its loses the connectivity somehow, and thereafter any query to database return empty response but no error on that very instant, suddenly after some time it shows an error stating - 

SQL30081N  A communication error has been detected.
   Communication protocol
   being used: "TCP/IP".  Communication API being used: "SOCKETS".
   Location
   where the error was detected: "X.X.X.X".  Communication
   function detecting
   the error: "send".  Protocol specific error code(s): "10032",
   "*", "*".
   SQLSTATE=08001

After every query I am doing db.close() and in every succeeding query pool.opn() is called on same connection string.

I have to manually restart my application everytime this shows up. How do I resolve this?

What might be causing this issue, is there some configuration I need to set in my application? Please help

I am attaching a file that demonstrate the way I am establishing the connection to database
[Db2Connection.txt](https://github.com/ibmdb/node-ibm_db/files/3285560/Db2Connection.txt)

**Comment by bimalkjha** [comment]
@Hasneet Seems, your ibm_db is not at latest level. This issue in fixed in ibm_db@2.5.2 . Please run `npm install ibm_db@latest` and then verify.  Thanks.

**Comment by Hasneet** [comment]
I have updated the version for ibm_db in my app, I will keep track of the logs from now. I will update whether or not I see this error again. Thanx for the information. :)

**Comment by aditi100** [comment]
Hi,
I am facing the same issue and my ibm_db version is "ibm_db": "^2.6.1", still I am getting the same error and I have to restart the application everyday.

**Comment by bimalkjha** [comment]
@aditi100 Please install ibm_db version 2.6.3 using command `npm install ibm_db@2.6.3` and then verify. Thanks.

**Comment by aditi100** [comment]
hi @bimalkjha,
I have tried installing the latest version i.e., 2.6.4 but then my code started giving errors which was earlier working with 2.6.1.
Is there a compatibility issue as I am using node-v10.16.0 currently.

**Comment by bimalkjha** [comment]
@aditi100 Yes, there is diff between 2.6.1 and 2.6.4, 2.6.1 had some major bugs. So, I would still recommend to use 2.6.4 and if you are hitting any issue, please open a new issue with details of error and how to reproduce it. Thanks.
