### ISSUE TITLE
After DB2 server restarts, connection in the pool still exists and return empty results

### ISSUE THREAD

**Issue by chiaki1770** [ibmdb/node-ibm_db#545]
I used connection pooling in my nodejs project. I recently noticed that after restarting db2 server, I couldn't login until I restart my backend. It seems the old connection in the pool will still be used. I checked conn.connected and conn.conn.connected, they are all true. Is there any way to check whether the connection is truly connected to the db2 (like mysql's ping function)?

**Comment by bimalkjha** [comment]
@chiaki1770 Which version of ibm_db you are using? This issue is fixed in ibm_db@2.5.2.
ping is very slow and implementing it will make active connections slower. Thanks.

**Comment by chiaki1770** [comment]
@bimalkjha I use "ibm_db": "2.5.0", I will try 2.5.2. Thanks!

**Comment by bimalkjha** [comment]
Seems same issue as #546 . Since, 546 is closed, hence closing it too. Thanks.
