### ISSUE TITLE
PoolSize increases even though I didn't use Pool.open to connect multiple db2

### ISSUE THREAD

**Issue by chiaki1770** [ibmdb/node-ibm_db#546]
My project connects to multiple db2. I used connection pooling for one db2 (Pool.open), which is frequently used. For the other db2s, I use ibm_db.open because they will be used only once per day. However, I noticed all the other db2 connections showed up in the Pool, For instance:
```{"options":{"idleTimeout":2000,"autoCleanIdle":true,"connectTimeout":60},"maxPoolSize":100,"index":0,"availablePool":{"DATABASE=AAA;HOSTNAME=XXXXX;PORT=XXXXX;PROTOCOL=TCPIP;UID=XXXXX;PWD=passw0rd":[]},"usedPool":{"DATABASE=AAA;HOSTNAME=XXXXX;PORT=XXXXX;PROTOCOL=TCPIP;UID=XXXXX;PWD=passw0rd":[{"odbc":{},"queue":{"fifo":[],"executing":true},"fetchMode":null,"connected":true,"connectTimeout":60,"codeSet":null,"mode":null,"conn":{"systemNaming":false,"connectTimeout":60,"connected":true},"created":1561323266128,"lastUsed":null}],"DATABASE=BBB;HOSTNAME=XXXXX;PORT=XXXXX;PROTOCOL=TCPIP;UID=XXXXX;PWD=XXXXX;":[{"odbc":{},"queue":{"fifo":[],"executing":false},"fetchMode":null,"connected":true,"connectTimeout":60,"codeSet":null,"mode":null,"conn":{"systemNaming":false,"connectTimeout":60,"connected":true},"created":XXXXXXXXXXX}]},"poolSize":64,"queue":{"fifo":[],"executing":true},"odbc":{}}```

NOTE: AAA is the only db I used Pool.open(), for BBB I used ibm_db.open(), also the PoolSize in the Pool object is 64. This is weird as well. Though eventually all the other db connection will be appended to the Pool.usedPool list.

Also, I did put conn.close() in my code

**Comment by bimalkjha** [comment]
@chiaki1770 If you see this behavior with ibm_db@2.5.2, please share a small test file to reproduce the issue. It may be due to application code logic, so please share some repro to look into it. Thanks.
