### ISSUE TITLE
encoding

### ISSUE THREAD

**Issue by yo34** [ibmdb/node-ibm_db#548]
My database encoding is set to iso-8859-15

I specify this connection URL :  DATABASE=mydb;HOSTNAME=localhost;UID=test;PWD=test;PORT=50000;PROTOCOL=TCPIP; DB2CODEPAGE=923"

On a "select" query, it's seem returned data use UTF8 encoding

Any idea to fix that ?

**Comment by PriyankaManoharan04** [comment]
@yo34 can you share your test file and share your output data returned and expected data so that we can able to reproduce it.

Thanks.

**Comment by bimalkjha** [comment]
@yo34 Do not specify `DB2CODEPAGE=923` in the connection string as connection string is not parsed by node.js code of ibm_db. Better to use [iconv-lite](https://www.npmjs.com/package/iconv-lite) package in your application for encoding conversion. Thanks.
