### ISSUE TITLE
No error on querying closed connection

### ISSUE THREAD

**Issue by hmottestad** [ibmdb/node-ibm_db#55]
Hi,

I have been using the Node-RED dashdb node that uses this library, and it will start to loose data when the connection times out to the dashDB database.

I modified the code, and found that I can still send insert queries to the database even after I have explicitly closed the connection without getting any errors.

**Comment by bimalkjha** [comment]
@hmottestad please share your modified code and repro steps.

**Comment by bimalkjha** [comment]
Please verify it on new released version ibm_db@0.0.15. Thanks.
