### ISSUE TITLE
Error using ibm_db

### ISSUE THREAD

**Issue by Campster** [ibmdb/node-ibm_db#550]
So I've been having trouble getting ibm_db to work properly with my existing project.  Basically, what I'm seeing is that it hangs as soon as it tries to open a DB connection or execute anything with a blank error.  

So I did the usual steps recommended elsewhere.  I.e.:

> cd \
> mkdir nodeapp
> cd nodeapp
> npm install ibm_db
> cd node_modules\ibm_db\test
> node test-basic-test.js

When I run the install I get the following log:

[no_crash_no_work_example.log](https://github.com/ibmdb/node-ibm_db/files/3351747/no_crash_no_work_example.log)

Which looks like it installs successfully! However, when I go and actually run the test, I get the following:

[test_run_example.log](https://github.com/ibmdb/node-ibm_db/files/3351941/test_run_example.log)

I'm quite certain this has to do with something during the build process, as it fails as soon as it tries to actually execute the .node bound database driver, but as far as I can tell there aren't any clear indicators of what to do since there are no proper errors when building.

**Comment by PriyankaManoharan04** [comment]
@Campster can you share your nodejs version and DB2 version.

Thanks.

**Comment by bimalkjha** [comment]
In shared log file, we can see `"IBM_DB_HOME environment variable have already been set to -> C:\ibm cli\clidriver"`.
Please share `db2level` output of this `clidriver` and from where you downloaded it. You can remove the IBM_DB_HOME setting, reinstall ibm_db and try.
I think you are using node.js version 10.14.1 or else, let us know.
Please share the Visual Studio version and Windows flavor name.
Seems your `ibm_db/Release/odbc_bindings.node` file has issue, so you can copy this file from `build.zip` and try. Thanks.

**Comment by yLeushun** [comment]
Hi,
I have the same error message 
Windows 10
node -v v8.9.0
npm -v 6.10.0

ntx64_odbc_cli.zip  was downloaded from https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/

I tried without IBM_DB_HOME - there was an error about missing file  'sqlcli1.h' when files we compiling

[node db2-result.txt](https://github.com/ibmdb/node-ibm_db/files/3372693/node.db2-result.txt)

Also tried to set 
>nvm use 9.11.2 -> Now using node v9.11.2 (64-bit)
and  replace odbc_bindings.node in ...db2_test\node_modules\ibm_db\build\Release 
the same error

PS
in my case, the same code works with the following configuration only
ibm_db@2.0.0
npm --version -> 4.2.0
node -v -> v7.10.1

**Comment by bimalkjha** [comment]
@yLeushun Please update database connection information in file `ibm_db\installer\testODBCConnection.bat` and execute this bat file from administrator command prompt. If you see, `SUCCESS` in the script output, you can replace the `db2cli validate` command in this script with `node app.js` and rerun the script. In case of failure, please share the script output and generated files. Thanks.

**Comment by yLeushun** [comment]
@bimalkjha, You have opened my eyes. I thought, that Visual Studio Code always asks Admin permission when it needed....
So, I followed your instruction. no errors,  bat with `node app.js` - ok.

The correct value in `IBM_DB_HOME` before installation and Running VS with admin right solved my issues
Thank you, @bimalkjha
