### ISSUE TITLE
executeNonQuery doesn't affect as many records as it should

### ISSUE THREAD

**Issue by dhulke** [ibmdb/node-ibm_db#551]
Our code currently opens/gets a connection from the connection pool, begins a transaction, executes several merge statements, commits the transaction and returns the connection back to the pool.

We execute the merge statements using the executeNonQuery function and we noticed that some times, this function returns 0, instead of 1. We haven't found a sure way to reproduce this error, but we noticed that it happens more frequently if we update lots of records in the same transaction or if we commit several transactions too fast.

Do you guys have any idea why this would be happening or where we could look for to maybe find whats causing this error? Any insights would be much appreciated.

**Comment by bimalkjha** [comment]
@dhulke executeNonQuery() internally calls SQLRowCount() to get the no of affected rows: https://github.com/ibmdb/node-ibm_db/blob/master/src/odbc_statement.cpp#L392
By looking on the documentation of [SQLRowCount](https://www.ibm.com/support/knowledgecenter/SSEPGG_11.1.0/com.ibm.db2.luw.apdv.cli.doc/doc/r0000644.html) API, we can see that it may return SQL_SUCCESS_WITH_INFO (1) in case of warning message and this case, code at https://github.com/ibmdb/node-ibm_db/blob/master/src/odbc_statement.cpp#L395 sets the rowCount as 0.

**Comment by dhulke** [comment]
Is there a way for me to know what was that warning? https://github.com/ibmdb/node-ibm_db/blob/master/src/odbc_statement.cpp#L404 only returns the rowCount so I'm not sure there is, but I would like to be able to understand whats going on with our code.

**Comment by bimalkjha** [comment]
@dhulke To know that warning, we need to enhance ibm_db code and return the warning message in the err field.
Another option is: you can enable ODBC trace by adding below text in `clidriver\cfg\db2cli.ini` file:
```
     [COMMON]
     Trace=1
     TraceFileName=C:\trace.txt
     TraceFlush=1
```
and run your application. In the trace.txt file, you can search for the return code from SQLRowCount() API. Currently, SQLRowCount() API is returning non-zero code, so rowcount is 0. Thanks.

**Comment by bimalkjha** [comment]
@dhulke We have pushed code changes to return warnings too. FYI, executeNonQuery() will return rowCount as 0 if the SQL statement is a searched UPDATE or searched DELETE and no rows satisfy the search condition. For more info, please check [this](https://www.ibm.com/support/knowledgecenter/SSEPGG_11.1.0/com.ibm.db2.luw.apdv.cli.doc/doc/r0000589.html) db2 knowledge center doc.
> >"but we noticed that it happens more frequently if we update lots of records in the same transaction or if we commit several transactions too fast."

In case of several transaction too fast, it might be possible that the update query is getting executed before the actual row get updated. In this case, if there is nothing to update in the table, the executeNonQuery() will return rowCount as 0.
Anyway you can verity any change in behavior by installing latest code from github. This fix will be part of next release. Closing the issue now.

**Comment by dhulke** [comment]
I've installed the new version and we see an exception being thrown now instead of just 0 affected rows. The exception is CLI0600E Invalid connection handle or connection is closed. SQLSTATE=S1000
