### ISSUE TITLE
esql-preprocess   'esql' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by Gajendrasinh** [ibmdb/node-ibm_db#552]
Hello 

I am getting below error.

Can anyone help to fixed this.

$ npm install ibm_db

> informix@1.0.0 install C:\Users\testuser\Desktop\project-name\node_modules\informix
> node-gyp rebuild

C:\Users\testuser\Desktop\project-name\node_modules\informix>if not defined npm_config_node_gyp (node "C:\Users\testuser\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\testuser\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Warning: Missing input files:
C:\Users\testuser\Desktop\project-name\node_modules\informix\build\..\build\esqlc.c
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  prepare
          1 file(s) copied.
  esql-preprocess
  'esql' is not recognized as an internal or external command,
  operable program or batch file.
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(209,5): error MSB6006: "cmd.exe" exited with code 1. [C:\Users\testuser\Desktop\project-name\node_modules\informix\build\esqlc.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\testuser\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\testuser\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\testuser\Desktop\project-name\node_modules\informix
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN gcdb6-ui-backend@1.0.0 No description
npm WARN gcdb6-ui-backend@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! informix@1.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the informix@1.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\testuser\AppData\Roaming\npm-cache\_logs\2019-07-04T09_26_32_559Z-debug.log

**Comment by PriyankaManoharan04** [comment]
@Gajendrasinh Try to install the latest version of node-ibm_db using `npm install ibm_db@2.5.2` command and check can you able to install.

**Comment by PriyankaManoharan04** [comment]
@Gajendrasinh 

> informix@1.0.0 install C:\Users\testuser\Desktop\project-name\node_modules\informix
> node-gyp rebuild

implies that it is not installing ibm_db instead it installs informix@1.0.0

Can you try exactly below steps on new command prompt window and share the result:

cd \
mkdir nodeapp
cd nodeapp
npm install ibm_db

Thanks.

**Comment by Gajendrasinh** [comment]
Hello @PriyankaManoharan04 ,

Thank you for reply.

I have try same step which you given.

Still I am getting below error. is it due proxy setting?

C:\Users\test\Desktop\Workspace\nodeapp>npm i

> ibm_db@2.5.2 install C:\Users\test\Desktop\Workspace\nodeapp\node_modules\ibm_db
> node installer/driverInstall.js

Downloading DB2 ODBC CLI Driver from https://proxy-url/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/ntx64_odbc_cli.zip...

{ Error: connect ETIMEDOUT 170.225.15.112:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '170.225.15.112',
  port: 443 }
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN nodeapp@1.0.0 No description
npm WARN nodeapp@1.0.0 No repository field.

added 102 packages from 95 contributors and audited 177 packages in 30.75s
found 0 vulnerabilities

**Comment by PriyankaManoharan04** [comment]
@Gajendrasinh Can you share the steps you followed to install ibm_db.

Thanks.

**Comment by PriyankaManoharan04** [comment]
@Gajendrasinh You can download the CLI Driver from this URL `https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/ntx64_odbc_cli.zip` and set the path of IBM_DB_HOME to this clidriver and install ibm_db using the command `npm install ibm_db`.

Thanks.

**Comment by PriyankaManoharan04** [comment]
@Gajendrasinh Closing this issuse as there is no response last one week. If you still face this issue you can reopen it.

Thanks.
