### ISSUE TITLE
Cannot install ibm_db@2.5.2

### ISSUE THREAD

**Issue by amitaher31** [ibmdb/node-ibm_db#553]
Running into following errors while installing ibm_db@2.5.2, can someone please help? many thanks!

Downloading DB2 ODBC CLI Driver from https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz...

**100.00% | 536 bytes downloaded out of 536 bytes.{ Error: incorrect header check
    at Zlib.zlibOnError [as onerror] (zlib.js:154:17) errno: -3, code: 'Z_DATA_ERROR' }**
npm WARN requestretry@2.0.2 requires a peer of request@~2.87.0 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN catalogonboarding-backend@1.0.0 No repository field.
npm WARN The package @iam/pep-client is included as both a dev and production dependency.
npm WARN The package jsonschema is included as both a dev and production dependency.
npm WARN The package utf8 is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ibm_db@2.5.2 install: `node installer/driverInstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ibm_db@2.5.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by PriyankaManoharan04** [comment]
@amitaher31 Can you share your  OS and nodejs version. 

Thanks.

**Comment by amitaher31** [comment]
Thanking for getting back!
Node dubnium 
Mac OS high seirra & on our Jenkins servers which are Linux (I can get back it’s OS type)

**Comment by PriyankaManoharan04** [comment]
@amitaher31 

You can download the CLI Driver Manually for MacOS and set the path of IBM_DB_HOME to that clidriver and install ibm_db using the command `npm install ibm_db`.

Thanks.

**Comment by bimalkjha** [comment]
@amitaher31 Please clarify on which OS you are installing ibm_db. MacOS or Linux? I think it can not be both at a time. From the logs, it seems you are installing ibm_db on Linux and error is coming while runtaring the linuxx64_odbc_cli.tar.gz file after download. The reason for the error is the downloaded linuxx64_odbc_cli.tar.gz file is corrupt. It has downloaded only 536 bytes which is incorrect size.
Do you have any proxy setting? why the size of linuxx64_odbc_cli.tar.gz is showing as only 536 bytes? can you please manually download https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz file and untar it? After untar you should get `clidriver` directory. Set the env var IBM_DB_HOME to this `clidriver` directory and run `npm install ibm_db`. It should work. Thanks.

**Comment by bimalkjha** [comment]
Follow the solutions mentioned here: https://stackoverflow.com/questions/48739985/npm-err-code-z-buf-error-when-install

**Comment by Naviar** [comment]
![image](https://user-images.githubusercontent.com/47994107/67740015-5d9ce800-f9e2-11e9-8a69-d45d6acd93a3.png)
me apsaba esto configuro la env , alguien me podria ayudar?
