### ISSUE TITLE
Problem with npm install on windows 10 fatal error LNK1181

### ISSUE THREAD

**Issue by huntergropy** [ibmdb/node-ibm_db#555]
Hi, 

I get this error:

C:\Proyectos\proyecto backlog>npm install ibm_db

> ibm_db@2.5.2 install C:\Proyectos\proyecto backlog\node_modules\ibm_db
> node installer/driverInstall.js

IBM_DB_HOME environment variable have already been set to -> C:\clidriver

Downloading of clidriver skipped - build is in progress...

C:\Proyectos\proyecto backlog\node_modules\ibm_db>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure build  --IS_DOWNLOADED=false --IBM_DB_HOME=$IBM_DB_HOME )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" configure build  --IS_DOWNLOADED=false --IBM_DB_HOME=$IBM_DB_HOME )
Los proyectos de esta soluci�n se van a compilar de uno en uno. Para habilitar la compilaci�n en paralelo, agregue el modificador "/m".
  odbc.cpp
  odbc_connection.cpp
  odbc_statement.cpp
  odbc_result.cpp
c:\clidriver\include\sqlcli.h(59): warning C4005: 'FAR': redefinici�n de macro (compilando archivo de origen ..\src\odbc_result.cpp) [C:\Proyectos\proyecto backlog\node_modules\ibm_db\build\odbc_bindings.vcxproj]
  c:\program files (x86)\windows kits\10\include\10.0.17763.0\shared\minwindef.h(150): note: vea la definici�n anterior de 'FAR' (compilando archivo de origen ..\src\odbc_result.cpp)
c:\proyectos\proyecto backlog\node_modules\ibm_db\src\odbc_result.cpp(288): warning C4996: 'Nan::Callback::Call': se declar� desusado [C:\Proyectos\proyecto backlog\node_modules\ibm_db\build\odbc_bindings.vcxproj]
  c:\proyectos\proyecto backlog\node_modules\nan\nan.h(1740): note: vea la declaraci�n de 'Nan::Callback::Call'
c:\proyectos\proyecto backlog\node_modules\ibm_db\src\odbc_result.cpp(312): warning C4996: 'Nan::Callback::Call': se declar� desusado [C:\Proyectos\proyecto backlog\node_modules\ibm_db\build\odbc_bindings.vcxproj]
  c:\proyectos\proyecto backlog\node_modules\nan\nan.h(1740): note: vea la declaraci�n de 'Nan::Callback::Call'
c:\proyectos\proyecto backlog\node_modules\ibm_db\src\odbc_result.cpp(596): warning C4996: 'Nan::Callback::Call': se declar� desusado [C:\Proyectos\proyecto backlog\node_modules\ibm_db\build\odbc_bindings.vcxproj]
  c:\proyectos\proyecto backlog\node_modules\nan\nan.h(1740): note: vea la declaraci�n de 'Nan::Callback::Call'
c:\clidriver\include\sqlcli.h(59): warning C4005: 'FAR': redefinici�n de macro (compilando archivo de origen ..\src\odbc_connection.cpp) [C:\Proyectos\proyecto backlog\node_modules\ibm_db\build\odbc_bindings.vcxproj]
  c:\program files (x86)\windows kits\10\include\10.0.17763.0\shared\minwindef.h(150): note: vea la definici�n anterior de 'FAR' (compilando archivo de origen ..\src\odbc_connection.cpp)
c:\proyectos\proyecto backlog\node_modules\ibm_db\src\odbc_connection.cpp(318): warning C4996: 'Nan::Callback::Call': se declar� desusado [C:\Proyectos\proyecto
backlog\node_modules\ibm_db\build\odbc_bindings.vcxproj]
  c:\proyectos\proyecto backlog\node_modules\nan\nan.h(1740): note: vea la declaraci�n de 'Nan::Callback::Call'
c:\proyectos\proyecto backlog\node_modules\ibm_db\src\odbc_connection.cpp(547): warning C4996: 'Nan::Callback::Call': se declar� desusado [C:\Proyectos\proyecto
backlog\node_modules\ibm_db\build\odbc_bindings.vcxproj]
  c:\proyectos\proyecto backlog\node_modules\nan\nan.h(1740): note: vea la declaraci�n de 'Nan::Callback::Call'
c:\proyectos\proyecto backlog\node_modules\ibm_db\src\odbc_connection.cpp(960): warning C4996: 'Nan::Callback::Call': se declar� desusado [C:\Proyectos\proyecto
backlog\node_modules\ibm_db\build\odbc_bindings.vcxproj]
  c:\proyectos\proyecto backlog\node_modules\nan\nan.h(1740): note: vea la declaraci�n de 'Nan::Callback::Call'
c:\proyectos\proyecto backlog\node_modules\ibm_db\src\odbc_connection.cpp(1189): warning C4996: 'Nan::Callback::Call': se declar� desusado [C:\Proyectos\proyecto backlog\node_modules\ibm_db\build\odbc_bindings.vcxproj]
  c:\proyectos\proyecto backlog\node_modules\nan\nan.h(1740): note: vea la declaraci�n de 'Nan::Callback::Call'
c:\proyectos\proyecto backlog\node_modules\ibm_db\src\odbc_connection.cpp(1216): warning C4996: 'Nan::Callback::Call': se declar� desusado [C:\Proyectos\proyecto backlog\node_modules\ibm_db\build\odbc_bindings.vcxproj]
  c:\proyectos\proyecto backlog\node_modules\nan\nan.h(1740): note: vea la declaraci�n de 'Nan::Callback::Call'
c:\proyectos\proyecto backlog\node_modules\ibm_db\src\odbc_connection.cpp(1809): warning C4996: 'Nan::Callback::Call': se declar� desusado [C:\Proyectos\proyecto backlog\node_modules\ibm_db\build\odbc_bindings.vcxproj]
  c:\proyectos\proyecto backlog\node_modules\nan\nan.h(1740): note: vea la declaraci�n de 'Nan::Callback::Call'
c:\proyectos\proyecto backlog\node_modules\ibm_db\src\odbc_connection.cpp(1991): warning C4996: 'Nan::Callback::Call': se declar� desusado [C:\Proyectos\proyecto backlog\node_modules\ibm_db\build\odbc_bindings.vcxproj]
  c:\proyectos\proyecto backlog\node_modules\nan\nan.h(1740): note: vea la declaraci�n de 'Nan::Callback::Call'
c:\clidriver\include\sqlcli.h(59): warning C4005: 'FAR': redefinici�n de macro (compilando archivo de origen ..\src\odbc_statement.cpp) [C:\Proyectos\proyecto backlog\node_modules\ibm_db\build\odbc_bindings.vcxproj]
  c:\program files (x86)\windows kits\10\include\10.0.17763.0\shared\minwindef.h(150): note: vea la definici�n anterior de 'FAR' (compilando archivo de origen ..\src\odbc_statement.cpp)
c:\clidriver\include\sqlcli.h(59): warning C4005: 'FAR': redefinici�n de macro (compilando archivo de origen ..\src\odbc.cpp) [C:\Proyectos\proyecto backlog\node_modules\ibm_db\build\odbc_bindings.vcxproj]
  c:\program files (x86)\windows kits\10\include\10.0.17763.0\shared\minwindef.h(150): note: vea la definici�n anterior de 'FAR' (compilando archivo de origen ..\src\odbc.cpp)
c:\proyectos\proyecto backlog\node_modules\ibm_db\src\odbc_statement.cpp(242): warning C4996: 'Nan::Callback::Call': se declar� desusado [C:\Proyectos\proyecto backlog\node_modules\ibm_db\build\odbc_bindings.vcxproj]
  c:\proyectos\proyecto backlog\node_modules\nan\nan.h(1740): note: vea la declaraci�n de 'Nan::Callback::Call'
c:\proyectos\proyecto backlog\node_modules\ibm_db\src\odbc_statement.cpp(408): warning C4996: 'Nan::Callback::Call': se declar� desusadoc:\proyectos\proyecto backlog\node_modules\ibm_db\src\odbc.cpp(210): warning C4996: 'Nan::Callback::Call': se declar� desusado [C:\Proyectos\proyecto backlog\node_modules\ibm_db\build\odbc_bindings.vcxproj]

  c:\proyectos\proyecto backlog\node_modules\nan\nan.h(1718): note: vea la declaraci�n de 'Nan::Callback::Call'c:\proyectos\proyecto backlog\node_modules\nan\nan.h(1740): note: vea la declaraci�n de 'Nan::Callback::Call'

c:\proyectos\proyecto backlog\node_modules\ibm_db\src\odbc_statement.cpp(567): warning C4996: 'Nan::Callback::Call': se declar� desusadoc:\proyectos\proyecto backlog\node_modules\ibm_db\src\odbc.cpp(222): warning C4996: 'Nan::Callback::Call': se declar� desusado [C:\Proyectos\proyecto backlog\node_modules\ibm_db\build\odbc_bindings.vcxproj]

  c:\proyectos\proyecto backlog\node_modules\nan\nan.h(1740): note: vea la declaraci�n de 'Nan::Callback::Call'c:\proyectos\proyecto backlog\node_modules\nan\nan.h(1740): note: vea la declaraci�n de 'Nan::Callback::Call'

c:\proyectos\proyecto backlog\node_modules\ibm_db\src\odbc_statement.cpp(793): warning C4996: 'Nan::Callback::Call': se declar� desusado [C:\Proyectos\proyecto backlog\node_modules\ibm_db\build\odbc_bindings.vcxproj]
  c:\proyectos\proyecto backlog\node_modules\nan\nan.h(1740): note: vea la declaraci�n de 'Nan::Callback::Call'
c:\proyectos\proyecto backlog\node_modules\ibm_db\src\odbc_statement.cpp(964): warning C4996: 'Nan::Callback::Call': se declar� desusado [C:\Proyectos\proyecto backlog\node_modules\ibm_db\build\odbc_bindings.vcxproj]
  c:\proyectos\proyecto backlog\node_modules\nan\nan.h(1740): note: vea la declaraci�n de 'Nan::Callback::Call'
c:\proyectos\proyecto backlog\node_modules\ibm_db\src\odbc.cpp(913): warning C4244: '=': conversi�n de 'int64_t' a 'SQLSMALLINT'; posible p�rdida de datos [C:\Proyectos\proyecto backlog\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\proyectos\proyecto backlog\node_modules\ibm_db\src\odbc.cpp(917): warning C4244: '=': conversi�n de 'int64_t' a 'SQLSMALLINT'; posible p�rdida de datos [C:\Proyectos\proyecto backlog\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\proyectos\proyecto backlog\node_modules\ibm_db\src\odbc.cpp(923): warning C4244: '=': conversi�n de 'int64_t' a 'SQLSMALLINT'; posible p�rdida de datos [C:\Proyectos\proyecto backlog\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\proyectos\proyecto backlog\node_modules\ibm_db\src\odbc.cpp(931): warning C4244: '=': conversi�n de 'int64_t' a 'SQLINTEGER'; posible p�rdida de datos [C:\Proyectos\proyecto backlog\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\proyectos\proyecto backlog\node_modules\ibm_db\src\odbc.cpp(1041): warning C4244: '=': conversi�n de 'SQLINTEGER' a 'SQLSMALLINT'; posible p�rdida de datos [C:\Proyectos\proyecto backlog\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\proyectos\proyecto backlog\node_modules\ibm_db\src\odbc.cpp(1203): warning C4996: 'Nan::Callback::Call': se declar� desusado [C:\Proyectos\proyecto backlog\node_modules\ibm_db\build\odbc_bindings.vcxproj]
  c:\proyectos\proyecto backlog\node_modules\nan\nan.h(1740): note: vea la declaraci�n de 'Nan::Callback::Call'
c:\proyectos\proyecto backlog\node_modules\ibm_db\src\odbc.cpp(1248): warning C4244: 'argumento': conversi�n de 'SQLINTEGER' a 'SQLSMALLINT'; posible p�rdida de
datos [C:\Proyectos\proyecto backlog\node_modules\ibm_db\build\odbc_bindings.vcxproj]
  win_delay_load_hook.cc
  strptime.c
LINK : fatal error LNK1181: no se puede abrir el archivo de entrada 'C:\clidriver\lib\db2cli64.lib' [C:\Proyectos\proyecto backlog\node_modules\ibm_db\build\odbc_bindings.vcxproj]

{ Error: Command failed: node-gyp configure build  --IS_DOWNLOADED=false --IBM_DB_HOME=$IBM_DB_HOME
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "build" "--IS_DOWNLOADED=false" "--IBM_DB_HOME=$IBM_DB_HOME"
gyp ERR! cwd C:\Proyectos\proyecto backlog\node_modules\ibm_db
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

    at ChildProcess.exithandler (child_process.js:276:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Socket.stream.socket.on (internal/child_process.js:336:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:561:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node-gyp configure build  --IS_DOWNLOADED=false --IBM_DB_HOME=$IBM_DB_HOME' }

node-gyp build process failed!

Proceeding with Pre-compiled Binary Installation.

===================================
node-ibm_db installed successfully!
===================================

npm WARN saveError ENOENT: no such file or directory, open 'C:\Proyectos\proyecto backlog\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Proyectos\proyecto backlog\package.json'
npm WARN proyecto backlog No description
npm WARN proyecto backlog No repository field.
npm WARN proyecto backlog No README data
npm WARN proyecto backlog No license field.

+ ibm_db@2.5.2
updated 1 package and audited 668 packages in 17.118s
found 0 vulnerabilities

-------------

note:
I used this problem as a guide: [https://github.com/ibmdb/node-ibm_db/issues/366#issuecomment-369640261](https://github.com/ibmdb/node-ibm_db/issues/366#issuecomment-369640261)

**Comment by PriyankaManoharan04** [comment]
@huntergropy 

> node-ibm_db installed successfully!

This message implies that your ibm_db has been installed successfully.Under the test folder update your connection string in config.testConnectionStrings.json file and run node test-basic-test.js and if you can able to get the output then there is no problem with ibm_db installation process. Thanks

**Comment by huntergropy** [comment]
Hi @PriyankaManoharan04 , thanks for answering.

this message appeared:

C:\Proyectos\proyecto backlog\back\node_modules\ibm_db\test>node test-basic-test.js
C:\Proyectos\proyecto backlog\back\node_modules\bindings\bindings.js:121
        throw e;
        ^

Error: The specified module could not be found.
\\?\C:\Proyectos\proyecto backlog\back\node_modules\ibm_db\build\Release\odbc_bindings.node
    at Object.Module._extensions..node (module.js:682:18)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at bindings (C:\Proyectos\proyecto backlog\back\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (C:\Proyectos\proyecto backlog\back\node_modules\ibm_db\lib\odbc.js:31:31)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)

**Comment by PriyankaManoharan04** [comment]
@huntergropy can you check odbc_bindings.node file exists under below path

> C:\Proyectos\proyecto backlog\back\node_modules\ibm_db\build\Release\odbc_bindings.node

Thanks

**Comment by huntergropy** [comment]
Yes, is there Attached?

**Comment by PriyankaManoharan04** [comment]
@huntergropy  Have you set the visual studio path in environment variable? If you still face this issue remove the node_modules and install new version of ibm_db using `npm install ibm_db@2.5.3`  command and under the test folder update your connection string in config.testConnectionStrings.json file and run node test-basic-test.js and if you can able to run the file.

Thanks.

**Comment by huntergropy** [comment]
@PriyankaManoharan04 yeah, i have set C:\Program Files (x86)\Microsoft Visual Studio  and  C:\Users\xxxxxx\AppData\Local\Programs\Microsoft VS Code\bin
then i uninstall ibm_db using `npm unistall ibm_db` then install using `npm install ibm_db@2.5.3`, and result is the same:

C:\Proyectos\proyecto backlog\back>npm uninstall ibm_db
npm WARN app@1.0.0 No description
npm WARN app@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
removed 87 packages and audited 2422 packages in 10.008s
found 0 vulnerabilities


C:\Proyectos\proyecto backlog\back>npm install ibm_db@2.5.3

> ibm_db@2.5.3 install C:\Proyectos\proyecto backlog\back\node_modules\ibm_db
> node installer/driverInstall.js

IBM_DB_HOME environment variable have already been set to -> C:\clidriver

Downloading of clidriver skipped - build is in progress...


C:\Proyectos\proyecto backlog\back\node_modules\ibm_db>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure build  --IS_DOWNLOADED=false --IBM_DB_HOME=$IBM_DB_HOME )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" configure build  --IS_DOWNLOADED=false --IBM_DB_HOME=$IBM_DB_HOME )
Los proyectos de esta soluci�n se van a compilar de uno en uno. Para habilitar la compilaci�n en paralelo, agregue el modificador "/m".
  odbc.cpp
  odbc_connection.cpp
  odbc_statement.cpp
  odbc_result.cpp
c:\proyectos\proyecto backlog\back\node_modules\ibm_db\src\odbc.cpp(210): warning C4996: 'Nan::Callback::Call': se declar� desusado [C:\Proyectos\proyecto backlog\back\node_modules\ibm_db\build\odbc_bindings.vcxproj]
  c:\proyectos\proyecto backlog\back\node_modules\nan\nan.h(1674): note: vea la declaraci�n de 'Nan::Callback::Call'
c:\proyectos\proyecto backlog\back\node_modules\ibm_db\src\odbc.cpp(222): warning C4996: 'Nan::Callback::Call': se declar� desusado [C:\Proyectos\proyecto backlog\back\node_modules\ibm_db\build\odbc_bindings.vcxproj]
  c:\proyectos\proyecto backlog\back\node_modules\nan\nan.h(1674): note: vea la declaraci�n de 'Nan::Callback::Call'
c:\proyectos\proyecto backlog\back\node_modules\ibm_db\src\odbc.cpp(671): warning C4311: 'conversi�n de tipo': truncamiento de puntero de 'SQLHSTMT' a 'long' [C:\Proyectos\proyecto backlog\back\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\proyectos\proyecto backlog\back\node_modules\ibm_db\src\odbc.cpp(671): warning C4302: 'conversi�n de tipo': truncamiento de 'SQLHSTMT' a 'long' [C:\Proyectos\proyecto backlog\back\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\proyectos\proyecto backlog\back\node_modules\ibm_db\src\odbc.cpp(672): warning C4311: 'conversi�n de tipo': truncamiento de puntero de 'SQLHSTMT' a 'long' [C:\Proyectos\proyecto backlog\back\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\proyectos\proyecto backlog\back\node_modules\ibm_db\src\odbc.cpp(672): warning C4302: 'conversi�n de tipo': truncamiento de 'SQLHSTMT' a 'long' [C:\Proyectos\proyecto backlog\back\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\proyectos\proyecto backlog\back\node_modules\ibm_db\src\odbc.cpp(913): warning C4244: '=': conversi�n de 'int64_t' a 'SQLSMALLINT'; posible p�rdida de datos [C:\Proyectos\proyecto backlog\back\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\proyectos\proyecto backlog\back\node_modules\ibm_db\src\odbc.cpp(917): warning C4244: '=': conversi�n de 'int64_t' a 'SQLSMALLINT'; posible p�rdida de datos [C:\Proyectos\proyecto backlog\back\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\proyectos\proyecto backlog\back\node_modules\ibm_db\src\odbc.cpp(923): warning C4244: '=': conversi�n de 'int64_t' a 'SQLSMALLINT'; posible p�rdida de datos [C:\Proyectos\proyecto backlog\back\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\proyectos\proyecto backlog\back\node_modules\ibm_db\src\odbc.cpp(931): warning C4244: '=': conversi�n de 'int64_t' a 'SQLINTEGER'; posible p�rdida de datos [C:\Proyectos\proyecto backlog\back\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\proyectos\proyecto backlog\back\node_modules\ibm_db\src\odbc.cpp(1041): warning C4244: '=': conversi�n de 'SQLINTEGER' a 'SQLSMALLINT'; posible p�rdida de datos [C:\Proyectos\proyecto backlog\back\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\proyectos\proyecto backlog\back\node_modules\ibm_db\src\odbc.cpp(1203): warning C4996: 'Nan::Callback::Call': se declar� desusado [C:\Proyectos\proyecto backlog\back\node_modules\ibm_db\build\odbc_bindings.vcxproj]
  c:\proyectos\proyecto backlog\back\node_modules\nan\nan.h(1674): note: vea la declaraci�n de 'Nan::Callback::Call'
c:\proyectos\proyecto backlog\back\node_modules\ibm_db\src\odbc.cpp(1248): warning C4244: 'argumento': conversi�n de 'SQLINTEGER' a 'SQLSMALLINT'; posible p�rdida de datos [C:\Proyectos\proyecto backlog\back\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\proyectos\proyecto backlog\back\node_modules\ibm_db\src\odbc_statement.cpp(242): warning C4996: 'Nan::Callback::Call': se declar� desusado [C:\Proyectos\proyecto backlog\back\node_modules\ibm_db\build\odbc_bindings.vcxproj]
  c:\proyectos\proyecto backlog\back\node_modules\nan\nan.h(1674): note: vea la declaraci�n de 'Nan::Callback::Call'
c:\proyectos\proyecto backlog\back\node_modules\ibm_db\src\odbc_statement.cpp(408): warning C4996: 'Nan::Callback::Call': se declar� desusado [C:\Proyectos\proyecto backlog\back\node_modules\ibm_db\build\odbc_bindings.vcxproj]
  c:\proyectos\proyecto backlog\back\node_modules\nan\nan.h(1652): note: vea la declaraci�n de 'Nan::Callback::Call'
c:\proyectos\proyecto backlog\back\node_modules\ibm_db\src\odbc_statement.cpp(567): warning C4996: 'Nan::Callback::Call': se declar� desusado [C:\Proyectos\proyecto backlog\back\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\proyectos\proyecto backlog\back\node_modules\ibm_db\src\odbc_connection.cpp(318): warning C4996: 'Nan::Callback::Call': se declar� desusadoc:\proyectos\proyecto backlog\back\node_modules\nan\nan.h(1674): note: vea la declaraci�n de 'Nan::Callback::Call' [C:\Proyectos\proyecto backlog\back\node_modules\ibm_db\build\odbc_bindings.vcxproj]

  c:\proyectos\proyecto backlog\back\node_modules\nan\nan.h(1674): note: vea la declaraci�n de 'Nan::Callback::Call'c:\proyectos\proyecto backlog\back\node_modules\ibm_db\src\odbc_statement.cpp(793): warning C4996: 'Nan::Callback::Call': se declar� desusado

c:\proyectos\proyecto backlog\back\node_modules\ibm_db\src\odbc_connection.cpp(547): warning C4996: 'Nan::Callback::Call': se declar� desusadoc:\proyectos\proyecto backlog\back\node_modules\nan\nan.h(1674): note: vea la declaraci�n de 'Nan::Callback::Call' [C:\Proyectos\proyecto backlog\back\node_modules\ibm_db\build\odbc_bindings.vcxproj]

  c:\proyectos\proyecto backlog\back\node_modules\nan\nan.h(1674): note: vea la declaraci�n de 'Nan::Callback::Call'
c:\proyectos\proyecto backlog\back\node_modules\ibm_db\src\odbc_statement.cpp(964): warning C4996: 'Nan::Callback::Call': se declar� desusadoc:\proyectos\proyecto backlog\back\node_modules\ibm_db\src\odbc_connection.cpp(960): warning C4996: 'Nan::Callback::Call': se declar� desusado [C:\Proyectos\proyecto backlog\back\node_modules\ibm_db\build\odbc_bindings.vcxproj]

  c:\proyectos\proyecto backlog\back\node_modules\nan\nan.h(1674): note: vea la declaraci�n de 'Nan::Callback::Call'c:\proyectos\proyecto backlog\back\node_modules\nan\nan.h(1674): note: vea la declaraci�n de 'Nan::Callback::Call'

c:\proyectos\proyecto backlog\back\node_modules\ibm_db\src\odbc_result.cpp(288): warning C4996: 'Nan::Callback::Call': se declar� desusadoc:\proyectos\proyecto backlog\back\node_modules\ibm_db\src\odbc_connection.cpp(1189): warning C4996: 'Nan::Callback::Call': se declar� desusado [C:\Proyectos\proyecto backlog\back\node_modules\ibm_db\build\odbc_bindings.vcxproj]

  c:\proyectos\proyecto backlog\back\node_modules\nan\nan.h(1674): note: vea la declaraci�n de 'Nan::Callback::Call'c:\proyectos\proyecto backlog\back\node_modules\nan\nan.h(1674): note: vea la declaraci�n de 'Nan::Callback::Call'

c:\proyectos\proyecto backlog\back\node_modules\ibm_db\src\odbc_result.cpp(312): warning C4996: 'Nan::Callback::Call': se declar� desusadoc:\proyectos\proyecto backlog\back\node_modules\ibm_db\src\odbc_connection.cpp(1216): warning C4996: 'Nan::Callback::Call': se declar� desusado [C:\Proyectos\proyecto backlog\back\node_modules\ibm_db\build\odbc_bindings.vcxproj]

  c:\proyectos\proyecto backlog\back\node_modules\nan\nan.h(1674): note: vea la declaraci�n de 'Nan::Callback::Call'c:\proyectos\proyecto backlog\back\node_modules\nan\nan.h(1674): note: vea la declaraci�n de 'Nan::Callback::Call'

c:\proyectos\proyecto backlog\back\node_modules\ibm_db\src\odbc_result.cpp(596): warning C4996: 'Nan::Callback::Call': se declar� desusado [C:\Proyectos\proyecto backlog\back\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\proyectos\proyecto backlog\back\node_modules\ibm_db\src\odbc_connection.cpp(1809): warning C4996: 'Nan::Callback::Call': se declar� desusadoc:\proyectos\proyecto backlog\back\node_modules\nan\nan.h(1674): note: vea la declaraci�n de 'Nan::Callback::Call' [C:\Proyectos\proyecto backlog\back\node_modules\ibm_db\build\odbc_bindings.vcxproj]

  c:\proyectos\proyecto backlog\back\node_modules\nan\nan.h(1674): note: vea la declaraci�n de 'Nan::Callback::Call'
c:\proyectos\proyecto backlog\back\node_modules\ibm_db\src\odbc_connection.cpp(1991): warning C4996: 'Nan::Callback::Call': se declar� desusado [C:\Proyectos\proyecto backlog\back\node_modules\ibm_db\build\odbc_bindings.vcxproj]
  c:\proyectos\proyecto backlog\back\node_modules\nan\nan.h(1674): note: vea la declaraci�n de 'Nan::Callback::Call'
  win_delay_load_hook.cc
  strptime.c
     Creando biblioteca C:\Proyectos\proyecto backlog\back\node_modules\ibm_db\build\Release\odbc_bindings.lib y objeto C:\Proyectos\proyecto backlog\back\node_modules\ibm_db\build\Release\odbc_bindings.exp
  Generando c�digo
  Generaci�n de c�digo finalizada
  odbc_bindings.vcxproj -> C:\Proyectos\proyecto backlog\back\node_modules\ibm_db\build\Release\\odbc_bindings.node


Kernel additional dependencies removed successfully!


{ Error: Command failed: msbuild /clp:Verbosity=minimal /nologo /p:Configuration=Release;Platform=x64 "C:\Proyectos\proyecto backlog\back\node_modules\ibm_db\build\binding.sln"
"msbuild" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

    at ChildProcess.exithandler (child_process.js:276:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'msbuild /clp:Verbosity=minimal /nologo /p:Configuration=Release;Platform=x64 "C:\\Proyectos\\proyecto backlog\\back\\node_modules\\ibm_db\\build\\binding.sln"' }

msbuild build process failed!

Proceeding with Pre-compiled Binary Installation.


===================================
node-ibm_db installed successfully!
===================================

npm WARN app@1.0.0 No description
npm WARN app@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
+ ibm_db@2.5.3
added 87 packages from 81 contributors and audited 2604 packages in 34.492s
found 0 vulnerabilities


C:\Proyectos\proyecto backlog\back>cd C:\Proyectos\proyecto backlog\back\node_modules\ibm_db\test

C:\Proyectos\proyecto backlog\back\node_modules\ibm_db\test>node test-basic-test.js
C:\Proyectos\proyecto backlog\back\node_modules\bindings\bindings.js:121
        throw e;
        ^

Error: The specified module could not be found.
\\?\C:\Proyectos\proyecto backlog\back\node_modules\ibm_db\build\Release\odbc_bindings.node
    at Object.Module._extensions..node (module.js:682:18)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at bindings (C:\Proyectos\proyecto backlog\back\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (C:\Proyectos\proyecto backlog\back\node_modules\ibm_db\lib\odbc.js:31:31)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)


Thanks.

**Comment by PriyankaManoharan04** [comment]
@huntergropy Even after setting visual studio path, ibm_db is installing using precompiled installation.I guess the problem is with your visual studio,remove the path of visual studio in environment variable and install ibm_db using `npm install ibm_db`.

Thanks

**Comment by PriyankaManoharan04** [comment]
@huntergropy 
You can update the connection string in ibm_db\installer\testODBCConnection.bat file and execute it to test the basic connectivity. If that work, then set the env var PATH and LIB as in testODBCConnection.bat and then try node test-basic-test.js. You can also comment the db2cli command in testODBCConnection.bat and write node test-basic-test.js there and execute to fix any env related issue. Thanks.
