### ISSUE TITLE
Multi statement error control

### ISSUE THREAD

**Issue by AckerApple** [ibmdb/node-ibm_db#557]
When I run multiple statements separated by a semi-colon AND one of the queries would cause an error, I get no errors thrown and the query completes with an array-of-arrays with no indication of error.

How should I catch errors for a mutli statement? Or how can I try/catch each multi statement to abort and report error.

Any thoughts? Thank you kindly.

**Comment by PriyankaManoharan04** [comment]
@AckerApple can you share your test program so that we can able to reproduce the error.

Thanks.

**Comment by PriyankaManoharan04** [comment]
@AckerApple Can you share your test program so that we can able to reproduce it.

Thanks.

**Comment by AckerApple** [comment]
I have found that as long as the last statement of a multi statement runs, then you get results as seen in screen capture.

Here is the query I am using for  DB2 zOS:

```js
    const x = await db.query(`
        select * from nothing;
        select * from nothing;
        select * from nothing;
        select * from nothing;
        select * from nothing;
        select * from nothing;

        select creator from sysibm.systables FETCH FIRST 1 ROWS ONLY;
    `);
```

![image](https://user-images.githubusercontent.com/7964429/62297606-8e9b6a00-b43f-11e9-8c09-1bad75fd49d5.png)

**Comment by bimalkjha** [comment]
@AckerApple The odbc api SQLExecute() returns SUCCESS_WITH_INFO i.e. 1 when it found error in multi statement. ibm_db ignores the warning as of now and only consider errors i.e. -ve return value. ibm_db ignore warnings at https://github.com/ibmdb/node-ibm_db/blob/master/src/odbc_connection.cpp#L1142 and https://github.com/ibmdb/node-ibm_db/blob/master/src/odbc_connection.cpp#L1324

**Comment by AckerApple** [comment]
I believe you are telling me that this seemingly incorrect behavior is just how ibm_db works "as of now". I am correct in that assumption?

Do we label this issue report a bug? The code seemingly looks out of my hands to work out a pull request but I would gladly help if I had a better hint of where to jump in (I don't know how to code cpp files).

Lastly, perhaps an options could be used to control how the error processing is treated? We really need to be running multiple sql statements to get much better performance out of our Node code but we can't risk flying blind on errors.

Thank you in great kind.

**Comment by bimalkjha** [comment]
@AckerApple I have pushed the fix of this issue on github and it'll be part of next release. You can verify the fix by installing ibm_db using command: `npm install git+https://git@github.com/ibmdb/node-ibm_db.git` on non-windows platform. Thanks.
