### ISSUE TITLE
IBM_DB does not support Node js 8.16.0

### ISSUE THREAD

**Issue by karthickgithubdev** [ibmdb/node-ibm_db#559]
ibm_db version 2.5.3 doesnt work with node js 8.16.0. 

Security processing failed with reason "24" ("USERNAME AND/OR PASSWORD INVALID") 
Please help us to resolve the issue.

**Comment by bimalkjha** [comment]
@karthickgithubdev Please read the pasted error message. It clearly says you are using wrong user name or password for the database to which you are connecting. You can update connection information in `ibm_db\installer\testODBCConnection.sh`[\.bat] file and execute it to test the connectivity. There is no issue with ibm_db.
You can get this error only after successful installation of ibm_db. Above error is not during installation time and hence it has nothing to do with node version 8.16.0. Hence, closing the issue. Thanks.
