### ISSUE TITLE
IBM_DB Test Cases Failed on linux 32 bit

### ISSUE THREAD

**Issue by elkorep** [ibmdb/node-ibm_db#56]
Node Build:  v0.12.7-IBMBuild-1.2.0.6-201508160201 (32bit)

The 64 bit versions of node on linux worked fine, but on the same systems the 32 bit versions have the following tests fail on these machines:

Machine Information:
RHEL 7
SUSE Linux 11
SLES 12

Running test for [DB2] : test-binding-statement-executeSync ... fail
Running test for [DB2] : test-binding-transaction-commit ... fail
Running test for [DB2] : test-binding-transaction-commitSync ... fail
Running test for [DB2] : test-describe-column ... fail
Running test for [DB2] : test-describe-database ... fail
Running test for [DB2] : test-describe-table ... fail
Running test for [DB2] : test-prepareSync-bad-sql ... fail
Running test for [DB2] : test-prepareSync-multiple-execution ... fail
Running test for [DB2] : test-transaction-commit-sync ... fail
Running test for [DB2] : test-transaction-commit ... fail 

All these tests pass on the 64 bit node build on the same machines with the exact same database and the same ibm_db/test/config.testConnectionStrings.json configurations.

Here is a breakdown of each tests issues:

1) test-binding-statement-executeSync
Error is caught and logged at line 65 and logs:

{ [Error: [IBM][CLI Driver] CLI0124E  Invalid argument value. SQLSTATE=HY009]
  errors: [],
  error: '[node-odbc] Error in ODBCStatement::BindSync',
  message: '[IBM][CLI Driver] CLI0124E  Invalid argument value. SQLSTATE=HY009',
  state: 'HY009' }

2) test-binding-transaction-commit
          data = result.fetchAllSync();
                        ^
Error: [IBM][CLI Driver] CLI0110E  Invalid output or indicator buffer specified. SQLSTATE=22002
    at Error (native)
    at /home/nodebot/nodetest-V12_32/node_modules/ibm_db/test/test-binding-transaction-commit.js:34:25

3) test-binding-transaction-commitSync
Failed when rolling back
{ [Error: [IBM][CLI Driver] CLI0110E  Invalid output or indicator buffer specified. SQLSTATE=22002]
  errors: [],
  error: '[node-odbc] Error in ODBC::GetColumnValue',
  message: '[IBM][CLI Driver] CLI0110E  Invalid output or indicator buffer specified. SQLSTATE=22002',
  state: '22002' }
Failed when committing
{ [Error: [IBM][CLI Driver] CLI0110E  Invalid output or indicator buffer specified. SQLSTATE=22002]
  errors: [],
  error: '[node-odbc] Error in ODBC::GetColumnValue',
  message: '[IBM][CLI Driver] CLI0110E  Invalid output or indicator buffer specified. SQLSTATE=22002',
  state: '22002' }

4) test-describe-column
connected
[IBM][CLI Driver][DB2/NT] SQL0204N  "ELKOREHP.NODE_ODBC_TEST_TABLE" is an undefined name.  SQLSTATE=42704

tables dropped
tables created

undefined:0

Error: [IBM][CLI Driver] CLI0110E  Invalid output or indicator buffer specified. SQLSTATE=22002
    at Error (native)

5) test-describe-database
undefined:0

Error: [IBM][CLI Driver] CLI0110E  Invalid output or indicator buffer specified. SQLSTATE=22002
    at Error (native)

6) test-describe-table
undefined:0

Error: [IBM][CLI Driver] CLI0110E  Invalid output or indicator buffer specified. SQLSTATE=22002
    at Error (native)

7) test-prepareSync-bad-sql
stmt.bindSync(["hello world", 1, null]);
     ^
Error: [IBM][CLI Driver] CLI0124E  Invalid argument value. SQLSTATE=HY009
    at Error (native)
    at Object.<anonymous> (/home/nodebot/nodetest-V12_32/node_modules/ibm_db/test/test-prepareSync-bad-sql.js:13:6)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

8) test-prepareSync-multilple-execution
[IBM][CLI Driver] CLI0124E  Invalid argument value. SQLSTATE=HY009
finish exit value: 3

9) test-transaction-commit-sync
Failed when committing
{ [Error: [IBM][CLI Driver] CLI0110E  Invalid output or indicator buffer specified. SQLSTATE=22002]
  errors: [],
  error: '[node-odbc] Error in ODBC::GetColumnValue',
  message: '[IBM][CLI Driver] CLI0110E  Invalid output or indicator buffer specified. SQLSTATE=22002',
  state: '22002' }

10) test-transaction-commit
  var data = result.fetchAllSync();
                    ^
Error: [IBM][CLI Driver] CLI0110E  Invalid output or indicator buffer specified. SQLSTATE=22002
    at Error (native)
    at Database.querySync (/home/nodebot/nodetest-V12_32/node_modules/ibm_db/lib/odbc.js:419:21)
    at /home/nodebot/nodetest-V12_32/node_modules/ibm_db/test/test-transaction-commit.js:60:19

**Comment by bimalkjha** [comment]
Please verify it on latest ibm_db@0.0.15. I am expecting improvement. Thanks.

**Comment by elkorep** [comment]
I tried these machines again and all test cases are successful. Thanks Bimal.
