### ISSUE TITLE
Executing Multiple Update Statements

### ISSUE THREAD

**Issue by Goochimagne** [ibmdb/node-ibm_db#562]
I want to loop through an array of values bind all the parameters to that query and then execute every n objects for 25K objects.
What is the most optimized what to preform this batch update or the equivalent of the below code in js.
`try {

  PreparedStatement ps = conn.prepareStatement(          

    "UPDATE DEPT SET  DEPTNAME=? " +

    "WHERE DEPTNO=?");
  ps.setString(1,"X01");                                 
  ps.setString(2,"Planning");
  ps.addBatch();                                         
  ps.setString(1,"Y01");                          
  ps.setString(2,"Bookkeeping");
  ps.addBatch();                                  
  int [] numUpdates=ps.executeBatch(); 
  conn.commit();`

**Comment by bimalkjha** [comment]
@Goochimagne Currently, ibm_db do not support array insert. So, you need to call statement.execute() for every statement.bind(). i.e. remove ` if (i % 25 == 0) {` from your original posted test program.
Write code to insert only 1 row in a table at once. That is the only way currently supported. Thanks.

**Comment by Goochimagne** [comment]
Thanks for the response! So this is the best I can do in terms of performance? I am trying to update 25K rows and at 20 queries/sec that is still about 30 min.. Or would concattenating the query a few times for a bulk insert be better?

**Comment by bimalkjha** [comment]
@Goochimagne Yes, you can concatenate multiple rows in once query and have bulk insert like `insert into mytab (c1, c2) values (2, 3), (4, 5), (8, 1)`. Thanks.

**Comment by bimalkjha** [comment]
If you are inserting dynamically, make sure your query has equal no of parameter markers in the sql statement as no of values you are passing. For above query, the dynamic sql should be: `insert into mytab (c1, c2) values (?, ?), (?, ?), (?, ?)`. Thanks.
