### ISSUE TITLE
Turning on debug logging prints the password in connect string. 

### ISSUE THREAD

**Issue by jajuanMitchell** [ibmdb/node-ibm_db#563]
Debug logging should not print the password in the log file.  Currently the password is part of the connect string and is logged which is a security issue.

**Comment by bimalkjha** [comment]
@jajuanMitchell Can you share the part of the log file where you see connection string is getting logged? I think it should be in case of pooled connection, where pool contents is getting dumped. pool stores all connection objects of same connection string in one array with connection string.  Also, debug mode is enabled by the user who already know the password. If user is sharing the log with others, should remove passwd from log file and then share. Thanks.

**Comment by jajuanMitchell** [comment]
> @jajuanMitchell Can you share the part of the log file where you see connection string is getting logged? I think it should be in case of pooled connection, where pool contents is getting dumped. pool stores all connection objects of same connection string in one array with connection string. Also, debug mode is enabled by the user who already know the password. If user is sharing the log with others, should remove passwd from log file and then share. Thanks.

![logs](https://user-images.githubusercontent.com/25333243/62944369-85e55500-bdaa-11e9-83ae-a69bb9013cea.jpg)

**Comment by bimalkjha** [comment]
@jajuanMitchell Thanks. Only option is to remove this log from code and above log will not get dumped when debug is enabled. We'll look into it.

**Comment by bimalkjha** [comment]
pushed fix of this issue as latest commit in master.
