### ISSUE TITLE
Stored Proc gets no result! result logs as {fetchMode : 4}, rObj is an empty array, should contain the output string

### ISSUE THREAD

**Issue by navdove** [ibmdb/node-ibm_db#57]
//simple procedure, takes in input param, has one out param
CREATE OR REPLACE PROCEDURE PROCIMATE(IN PARM VARCHAR(30),OUT o_PARAM VARCHAR(200)) 
BEGIN  
set o_PARAM= \'This is my | procedure| what do you say\' ; 
END
    
//javascipt code
    var query = "call procimate(?,?)";

    pool.acquire(function (err, conn) {
      if (err) {
        cb(httpstatus.getStatus('500', 'Error', 500, 'DB.Connection', 'Error', err.toString()));
      } else {

        conn.prepare(query, function (err, stmt) {

          if (err) {

            console.error('error: ', err.message);

            return conn.close(function (err) {
            });

          } else {

            stmt.execute(['1','?'], function (err, result) {

              if (err) console.log(err); // no error

              else {
                var rObj = result.fetchAllSync();
                console.log(rObj);
              }

              if (err) {

                console.error('error: ', err.message);

              }

              if (result) {
                result.closeSync();
              }

              conn.close(function (err) {
              });

            });

          }

        });
      }

    });

**Comment by bimalkjha** [comment]
Check issue #7 . Out params are not supported in Stored Procedures.

**Comment by bimalkjha** [comment]
@navdove check test files mentioned here https://github.com/ibmdb/node-ibm_db#callStmt about correct usage. Thanks.
