### ISSUE TITLE
Failure to run inside packaged Windows Service (without DB2 installed)

### ISSUE THREAD

**Issue by jezh42** [ibmdb/node-ibm_db#571]
I am attempting to create a Windows service executable (made using node pkg) to routinely connect to a DB2 server. However, when I run the service, it fails to find the odbc_bindings.node file. Putting the odbc_bindings.node file in the same directory as the service exe gives the following error. 
```
Error: The specified module could not be found.
\\?\C:\Users\Administrator\Documents\myWindowsService\service-packaged\odbc_bindings.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:728:18)
  ...
```
However, if the user has DB2 installed on their machine, and has "C:\Program Files\IBM\SQLLIB\BIN" in their path, the user doesn't get the error, hence it works with the bindings .node file. I was able to remove this error (and successfully start the service) on a machine that didn't have DB2, by copying the contents of the previously mentioned BIN folder into the folder with the service. However when I attempt to make a connection to the DB2 server I get the following error.
```
Error: CLI0600E Invalid connection handle or connection is closed. SQLSTATE=S1000
    at new Database (C:\snapshot\myWindowsService\node_modules\ibm_db\lib\odbc.js:267:62)
```
Ideally, I would like to run this service on a machine that doesn't have DB2 installed on it.

Thank you

**Comment by edcolyer** [comment]
I've had a similar issue. Would love to know a solution to this one too. Sorry I'm no help.

**Comment by bimalkjha** [comment]
@jezh42 @edcolyer odbc_bindings.node will work only if it is under ibm_db directory. Seems, you installed ibm_db and then copied odbc_bindings.node out of it?
Also, odbc_bindings.node has dependency on db2app64.dll which must existing under LIB & PATH system environment variable or under `...\ibm_db\installer\clidriver\bin` directory.
For ibm_db to get installed, C:\Program Files\IBM\SQLLIB is not required, i.e. you need not to install a Db2 client or server before installing ibm_db. ibm_db install clidriver automatically if you have not set IBM_DB_HOME environment variable pointing to a pre-installed db2 client or server directory. Thanks.

**Comment by bimalkjha** [comment]
@jezh42 @edcolyer let me know if you still need any assistance. Thanks.
