### ISSUE TITLE
Fail to use ibmdb node

### ISSUE THREAD

**Issue by ktingrui** [ibmdb/node-ibm_db#572]
Hi all,

I got the following error while opening node-red which cause I fail to use ibmdb node.

[node-red-contrib-db2-fixed/bigdb2] Error: Could not locate the bindings file. Tried:
 → /Users/garyke/.node-red/node_modules/ibm_db/build/odbc_bindings.node
 → /Users/garyke/.node-red/node_modules/ibm_db/build/Debug/odbc_bindings.node
 → /Users/garyke/.node-red/node_modules/ibm_db/build/Release/odbc_bindings.node
 → /Users/garyke/.node-red/node_modules/ibm_db/out/Debug/odbc_bindings.node
 → /Users/garyke/.node-red/node_modules/ibm_db/Debug/odbc_bindings.node
 → /Users/garyke/.node-red/node_modules/ibm_db/out/Release/odbc_bindings.node
 → /Users/garyke/.node-red/node_modules/ibm_db/Release/odbc_bindings.node
 → /Users/garyke/.node-red/node_modules/ibm_db/build/default/odbc_bindings.node
 → /Users/garyke/.node-red/node_modules/ibm_db/compiled/8.16.1/darwin/x64/odbc_bindings.node
 → /Users/garyke/.node-red/node_modules/ibm_db/addon-build/release/install-root/odbc_bindings.node
 → /Users/garyke/.node-red/node_modules/ibm_db/addon-build/debug/install-root/odbc_bindings.node
 → /Users/garyke/.node-red/node_modules/ibm_db/addon-build/default/install-root/odbc_bindings.node
 → /Users/garyke/.node-red/node_modules/ibm_db/lib/binding/node-v57-darwin-x64/odbc_bindings.node (line:4)

Here is my node version:
Node-RED version: v0.20.7
Node.js  version: v8.16.1

Is there any idea how to fix it? 
Thanks in advance!

**Comment by bimalkjha** [comment]
@ktingrui Please share the complete output of `npm install ibm_db`. There might be some problem during installation which caused this issue. Also, let us know that you can see the directory `/Users/garyke/.node-red/node_modules/ibm_db/installer/clidriver` exists. Thanks.

**Comment by ktingrui** [comment]
Hi

I checked my clidriver directory and it exists. 

Here are the log for npm install ibm_db

[db2install.log](https://github.com/ibmdb/node-ibm_db/files/3564402/db2install.log)

The output shows that I've downloaded DB2 ODBC CLI Driver successfully but found 2 critical vulnerabilities. I've tried 'npm audit fix' to fix the vulnerability but did not work.

Here is the npm audit output:
[audit.log](https://github.com/ibmdb/node-ibm_db/files/3564409/audit.log)

**Comment by bimalkjha** [comment]
@ktingrui From the db2install.log, we can see ibm_db is getting installed at /Users/garyke/node_modules/ibm_db. Its first line in db2install.log file. So, file /Users/garyke/node_modules/ibm_db/build/Release/odbc_bindings.node should exist in your system. You can cd /Users/garyke/node_modules/ibm_db/test and execute `node test-basic-test.js`. It should be able to execute and will give some error about hostname.

So, ibm_db is installed as `/Users/garyke/node_modules/ibm_db` but, node-red is looking for it under  `/Users/garyke/.node-red/node_modules/ibm_db` which is different from the installed location. You should investigate, why node-red is looking for ibm_db under /Users/garyke/.node-red/node_modules/ibm_db when it is installed as /Users/garyke/node_modules/ibm_db?
You may try to install ibm_db using -g option: `npm install -g ibm_db` and see if it make any difference.
If node-red is looking for ibm_db as `/Users/garyke/.node-red/node_modules/ibm_db`, it must be installed at this location. Thanks.

**Comment by bimalkjha** [comment]
The vulnerability error is about other 1054 packages already installed in your system. ibm_db or its dependency has no vulnerability. Thanks.

**Comment by ktingrui** [comment]
Hi,

Thanks a lot for your help. It works normally after I use 'npm install -g ibm_db' to install.
/Users/garyke/.node-red/ is the default path that node module installed. I should run in this path.
 
** node test-basic-test.js is able to execute  under /Users/garyke/.node-red/node_modules/ibm_db/test.
