### ISSUE TITLE
(2.6.1) Behavior change for update statement affecting no rows

### ISSUE THREAD

**Issue by dongryphon** [ibmdb/node-ibm_db#573]
For the past year or two we've had this statement running without issue:
```
update ORGANIZATION set created = 0 where created is NULL
```

As of 2.6.1, this now produces the following warning as an exception:

```
[IBM][CLI Driver][DB2/LINUXX8664] SQL0100W  No row was found for FETCH, UPDATE or DELETE; or the result of a query is an empty table.  SQLSTATE=02000
```
Is there a way to restore the original behavior? If not, how should we detect warnings like this to distinguish them from actual errors?

This seems to have also worked with 2.6.0. In the meantime, we have locked our version to 2.5.3 even though 2.5.1 is marked as the current release. Not sure what's up there.

Thanks!

**Comment by PriyankaManoharan04** [comment]
@dongryphon There was an request from the customer to return warning messages too. One of such request was from issue #557. So we modified the code to return warning messages too which was getting ignored before. This warning get returned when no rows are updated by your query `update ORGANIZATION set created = 0 where created is NULL`. To proceed on it, you can update your application code to check presence of `SQL0100W ` and ignore it. Or, just check for `if(err.sqlcode == 100)`, then ignore it. Thanks.

**Comment by dongryphon** [comment]
Thanks for the clarification. I'd say that that is definitely a breaking change since previously valid code in now reporting errors (i.e., all warnings are now reported as thrown exceptions/errors).

Ideally such fundamental changes would have to be enabled explicitly somehow. Perhaps as one of the `options` to the `open()` API. Failing that (i.e., a deliberate change to behavior), this should result in a top-level version number increment... so `3.0.0`.

As mentioned, we'll "fix" this on our side by locking down the version number, but I hope you can go the way of opt-in so we don't miss out on new features/fixes in your releases stream.

Thanks again!

**Comment by dongryphon** [comment]
For what it's worth, the Python `ibm_db` driver also does not report warnings as exceptions.

**Comment by AckerApple** [comment]
This new issue be killing us! Sorry to be dramatic and not offer any additional valuable comments but we are frantically trying to tackle this.

**Comment by AckerApple** [comment]
For now we used `npm install ibm_dm@2.5.3` to get ourselves back on last working version

And to prevent updating to newest version we have our dependencies as:
```
"dependencies": {
  "ibm_db": "~2.5.3",
```

This got us out of panic mode. @dongryphon, I personally hella appreciate you reporting this as we were lost thinking it was just my new data driven unit tests (aka nightmare to manage)

**Comment by bimalkjha** [comment]
@rbetjes Do you mean, ibm_db should continue ignoring any warning and return only errors? ibm_db APIs should return success for warning? Please share your views. Thanks.

**Comment by dongryphon** [comment]
I can see two easy paths:
- make it opt-in at `open()` time via a new option.
- store warning state on the connection instance for the last operation

I could see both being employed, as in the last warning is stored on the connection and optionally it may throw an exception / report failure.

**Comment by dongryphon** [comment]
In any case, the main issue is the change in control flow created by elevating warnings into the same path as errors.

**Comment by rbetjes** [comment]
Ibm_db should definately return succes on warnings because the sql statement is executed succesfully (in our case at least). There is no reason not to return the fetched data.
As for the warning itself, it could be helpfull to have access to it. Just not as an error.
To be fair, we are using a 3rd party package that acts as a wrapper around ibm_db. That package now throws an exception.

**Comment by AckerApple** [comment]
@PriyankaManoharan04, your recommend fix worked for us.

Now if an error occurs we check `err.sqlcode===100`. We are now back up to date on ibm_db

![image](https://user-images.githubusercontent.com/7964429/65461272-99f88980-de21-11e9-95b8-59ea3d268368.png)

**Comment by John-Kryspin** [comment]
Thanks for opening this @dongryphon 
I agree that it should by default not throw an exception for warning, but it can be an option when creating the DB2 connection.

The SQL is executed successfully, and the warning is not really an error, but rather more information.
For now we are going to stay on version 2.5.3.

**Comment by bimalkjha** [comment]
@dongryphon I have just pushed fix of this issue in master branch. Hence, closing it now. Thanks.
