### ISSUE TITLE
Queuing queries and going pending

### ISSUE THREAD

**Issue by Hasneet** [ibmdb/node-ibm_db#574]
I have been using ibm_db package - 2.5.2, and early this morning I have started to see that none of my queries are getting resolved. On further inspection of the connection pool object created I found that the fifo list under the simpleQueue is getting filled immensely with functions. I tried finding the solution but there was not much reference in this context.
 Also I would like to mention is using IBM Cloud's DB2 HA instance and as I checked the DB Connection over the DB2 instance I could not see any application connection there. However It should have automatically re-established a connection if it was staled as I am using connection pooling here and using db.close()  after I am done with the query.
 It is impacting at a huge scale. please help. I am attaching the connection object being used during the queries.

I have removed HOSTNAME and PWD fields.

`{
       options: { autoCleanIdle: true, connectTimeout: 60 },
       maxPoolSize: 2,
       index: 1,
       availablePool:
        { 'DATABASE=BLUDB;HOSTNAME=;PORT=50000;PROTOCOL=TCPIP;UID=bluadmin;PWD=': [] },
       usedPool:
        { 'DATABASE=BLUDB;HOSTNAME=;PORT=50000;PROTOCOL=TCPIP;UID=bluadmin;PWD=': [] },
       poolSize: 2,
       queue:
        SimpleQueue {
          fifo:
           [ [Function],
             [Function],
             [Function],
             [Function],
             [Function],
             [Function],
             [Function],
             [Function],
             [Function],
             [Function],
             [Function],
             [Function],
             [Function],
             [Function],
             [Function],
             [Function],
             [Function],
             [Function],
             [Function],
             [Function],
             [Function],
             [Function],
             [Function],
             [Function],
             [Function],
             [Function],
             [Function],
             [Function],
             [Function],
             [Function],
             [Function],
             [Function],
             [Function],
             [Function],
             [Function],
             [Function],
             [Function],
             [Function],
             [Function],
             [Function],
             [Function],
             [Function],
             [Function],
             [Function],
             [Function],
             [Function],
             [Function],
             [Function],
             [Function],
             [Function],
             [Function] ],
          executing: true },
       odbc: ODBC {} }`

This is the function where pool is created and being used.

````
var ibmdb = require('ibm_db');
let Pool = ibmdb.Pool;
pool = new Pool({autoCleanIdle: true});
pool.setMaxPoolSize(2);

const runQuery= (query,paramsValueArray)=>{
  
   console.log('inside runQuery');
    return new Promise(async (resolve,reject)=>{
```
      
      try {
        
        
        
       pool.open(cn, (err, db) => {
         
         if(err) {
           
           reject(err);
           return;
         }
         
         
        db.query(query,paramsValueArray,function(err,data){

          if(err)  {
            
            db.close(() => {
              console.log('connection Disconnected');
            });
            reject(err);
            return;
          }
          
          console.log('no error in query')
           resolve(data);
           db.close(() => {
             console.log('connection Disconnected');
            
             return;
           });
           
              
           });
       })
      }
      catch(err) {
        reject(err);
      }
    });
`};``


Please help. Why is this happening

**Comment by bimalkjha** [comment]
@Hasneet First would like to know you are still using 2.5.2 or some newer version? I would suggest to use 2.5.3 or 2.6.1 and verify. If you still see issues, would it be possible to reproduce the behavior using some small test script? If yes, please share.
To know further details about what is going on with current version, you can run command `npm install --debug` under `ibm_db` and then run your program. It would print lot of debug message on console that you can redirect to some file. You can share this log with us to look further. Thanks.

**Comment by Hasneet** [comment]
@bimalkjha I am still using 2.5.2 version, I just tried to manually restart the application, and I found that this time it successfully established the connection to the DB and I can see the connection over the IBM Cloud connection logs. Somewhat similar issue use to occur when I was using 2.5.1 version to which you had advised to switch into 2.5.2 as it was fixed here, ever since switching to version 2.5.2 this happened for the first time today. I am unable to reproduce the issue on demand since as soon as I restart, the application starts to work just fine but this use to occur earlier when application was up for a period of time and staled connection was not being re-established.
Sure I will use that command to debug and share the logs with you.

For the moment I will switch to 2.6.1 and see if that helps. Can you please see if I am initializing the pool correctly I have just updated this thread with the code.

**Comment by Hasneet** [comment]
@bimalkjha my concern was if there was no connection with the DB (as I am cross checked that part since it was not reflected within the DB Connection logs on the IBM cloud DB instance) why it did not throw an error in pool.open() and rather queued a few functions withing the fifo array.

If could tell me what it is exactly that is being queued withing simpleQueue and when does that suppose to happen?

**Comment by bimalkjha** [comment]
@Hasneet simpleQueue stores the query() request, execute it one by one and return the result to callback (or promise), one it is done with the execution: https://github.com/ibmdb/node-ibm_db/blob/master/lib/odbc.js#L472
Lot of functions in simpleQueue tells that lot of query() request is waiting as some query() is stuck and not finished or not called callback function. Can not say why without any repro. Version 2.5.2 has some pool related bug too when network connection goes down, delivered as [this](https://github.com/ibmdb/node-ibm_db/commit/4a7b1b5ee739486c32d65d2fbf440a3df0f4f80e) commit.

**Comment by Hasneet** [comment]
@bimalkjha Thank you so much for such detailed insight to this. :) you have been very helpful.
I will run app with debug mode and will provide you with the application logs, and for the time being I will switch other instances with the latest release of ibm_db. Thanx a lot again 👍
