### ISSUE TITLE
Error: [IBM][CLI Driver] SQL30081N, Protocol specific error code(s): "0", "*", "*".

### ISSUE THREAD

**Issue by snyang** [ibmdb/node-ibm_db#575]
I encountered the following error when I tries to connect a DB2 server in a docker container.
The database can be connected via other db utilities.
And ibm_db can also connect a DB2 server located in a Windows Server.

```
Error: [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "9.111.98.139".  Communication function detecting the error: "selectForConnectTimeout".  Protocol specific error code(s): "0", "*", "*".  SQLSTATE=08001
```

**Comment by bimalkjha** [comment]
@snyang It seems the db2 server in the container is not configured to accept remote connection. Do you know on what TCPIP port the server is listening? If you know the correct port number, first run below commands on db2 server using db2 command line tool to make sure server configuration is correct:
```
db2 terminate
db2stop force
db2set DB2COMM=TCPIP
db2 update dbm cfg using SVCENAME 60000  <= change it to correct port.
db2 terminate
db2start
db2 connect to dbname user username using password
```
Update dbname, username and password in above command. If above command works, then ibm_db should also be able to connect. If above connect command fails, then you need to contact the db2 server team to fix the issue. Thanks.

**Comment by bimalkjha** [comment]
you can find the port by running ` docker inspect ibmcom/db2`
I hope you have installed db2 using command: `docker run -itd --name mydb2 --privileged=true -p 50000:50000 -e LICENSE=accept -e DB2INST1_PASSWORD=<choose> -e DBNAME=testdb -v <db dir>:/database ibmcom/db2` 
For above command the port to connect to db2 from external process is the port after colon which is 50000. Thanks.

**Comment by bimalkjha** [comment]
Please follow instructions here to setup the db2 server in docker: https://hub.docker.com/r/ibmcom/db2-amd64
