### ISSUE TITLE
Ｉgot garbled character with ibm_db@2.6.1 in nodejs project

### ISSUE THREAD

**Issue by 54346946** [ibmdb/node-ibm_db#579]
I am working on a nodejs project. There is company name 'ABC AEROLÍNEAS SA DE CV' in DB2. While using ibm_db@2.6.1 to get the name, it turned into 'ABC AEROL�NEAS SA DE CV' in my nodejs. 

I tried to verify it by using python with ibm_db 3.0.1 and got 'ABC AEROL\xcdNEAS SA DE CV'. I think the '\xcd' should be correct since it displays 'ABC AEROLÍNEAS SA DE CV' in python console. Furthermore, I tested it by JDBC and got the correct name too.

I don't know why nodejs's ibm_db cannot get the correct name. Could someone help to check this? Thanks.

DB
![db](https://user-images.githubusercontent.com/31400781/65174605-cdcf5a00-da83-11e9-8295-eacb617a8211.png)

Results of nodejs
![nodejs1](https://user-images.githubusercontent.com/31400781/65174010-9ad89680-da82-11e9-8e7f-7f97f7935095.png)

Results of python
![python1](https://user-images.githubusercontent.com/31400781/65174048-ae83fd00-da82-11e9-829c-8ddab2a89c27.png)

**Comment by PriyankaManoharan04** [comment]
@54346946 Can you just try setting DB2CODEPAGE=1208. I just tried using this and it works for me.Give a try to verify.Thanks

**Comment by 54346946** [comment]
@PriyankaManoharan04 Thanks. Let me contact the DBA and try it.

**Comment by bimalkjha** [comment]
@54346946 You need to set DB2CODE in the system where you have installed `ibm_db`. On windows, set it in system environment variable and on non-windows, run `export DB2CODEPAGE=1208` on terminal or set in .profile file and then run your application to test. Thanks.

**Comment by 54346946** [comment]
@bimalkjha Yes, it works. Thanks for your help.
