### ISSUE TITLE
ibm_db fails to install if the absolute path to node_modules contains spaces

### ISSUE THREAD

**Issue by mtp401** [ibmdb/node-ibm_db#58]
If the absolute path to your node_modules folder contains spaces, ibm_db will fail to install with:

{ [Error: Command failed: make: *** No rule to make target `xxx/node_modules/ibm_db/installer/clidriver'.  Stop.
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.13.0-62-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "configure" "build" "--IBM_DB_HOME=/var/tmp/space" "dir/dir/node_modules/ibm_db/installer/clidriver" "--IBM_DB_HOME_WIN=%IBM_DB_HOME%" "--IS_DOWNLOADED=true"
gyp ERR! cwd /var/tmp/space dir/dir/node_modules/ibm_db
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
] killed: false, code: 1, signal: null }
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! weird error 1
npm ERR! not ok code 0

Steps to reproduce:

```bash
mkdir -p "/var/tmp/dir with spaces/subdir"
cd "/var/tmp/dir with spaces/subdir"
npm install ibm_db
```

Note, this breaks most intelligently named Jenkins jobs.

**Comment by bimalkjha** [comment]
I tried it on my Linux system and it seems working:

linuxcli: /home/bimaljha/tmp> mkdir -p "dir with spaces/subdir"
linuxcli: /home/bimaljha/tmp> cd dir\ with\ spaces/subdir/
linuxcli: /home/bimaljha/tmp/dir with spaces/subdir> npm install ibm_db
/
> ibm_db@0.0.14 install /home/bimaljha/node_modules/ibm_db
> node installer/driverInstall.js

Downloading DB2 ODBC CLI Driver from http://public.dhe.ibm.com/ibmdl/.../drivers/odbc_cli/linuxx64_odbc_cli.tar.gz...
Download and extraction of DB2 ODBC CLI Driver completed successfully ...
make: Entering directory `/home/bimaljha/node_modules/ibm_db/build'
  CXX(target) Release/obj.target/odbc_bindings/src/odbc.o
  CXX(target) Release/obj.target/odbc_bindings/src/odbc_connection.o
  CXX(target) Release/obj.target/odbc_bindings/src/odbc_statement.o
  CXX(target) Release/obj.target/odbc_bindings/src/odbc_result.o
  CXX(target) Release/obj.target/odbc_bindings/src/dynodbc.o
  SOLINK_MODULE(target) Release/obj.target/odbc_bindings.node
  SOLINK_MODULE(target) Release/obj.target/odbc_bindings.node: Finished
  COPY Release/odbc_bindings.node
make: Leaving directory `/home/bimaljha/node_modules/ibm_db/build'

ibm_db@0.0.14 ../../../node_modules/ibm_db
âââ bindings@1.0.0
âââ nan@1.8.4
âââ fstream@1.0.7 (inherits@2.0.1, graceful-fs@3.0.8, mkdirp@0.5.1, rimraf@2.4.3)
âââ unzip@0.1.11 (setimmediate@1.0.2, readable-stream@1.0.33, match-stream@0.0.2, pullstream@0.4.1, binary@0.3.0, fstream@0.1.31)
âââ tar.gz@0.1.1 (tar@0.1.20, commander@1.1.1, fstream@0.1.31)
linuxcli: /home/bimaljha/tmp/dir with spaces/subdir>

**Comment by mtp401** [comment]
It's working because you have a pre-existing 'node_modules' directory higher up in your path. Notice 

```make: Entering directory /home/bimaljha/node_modules/ibm_db/build' CXX(target) ```

**Comment by joshuarichard** [comment]
I could replicate the problem @mtp401 found.

Make sure you delete node_modules.
```shell
joshuarhardsmbp:subdir joshuarichard$ pwd
/var/tmp/dir with spaces/subdir
joshuarhardsmbp:subdir joshuarichard$ npm install ibm_db
\
> ibm_db@0.0.14 install /private/var/tmp/dir with spaces/subdir/node_modules/ibm_db
> node installer/driverInstall.js

Downloading DB2 ODBC CLI Driver from http://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/macos64_odbc_cli.tar.gz...
Download and extraction of DB2 ODBC CLI Driver completed successfully ...

{ [Error: Command failed: /bin/sh -c node-gyp configure build --IBM_DB_HOME=$IBM_DB_HOME --IBM_DB_HOME_WIN=%IBM_DB_HOME% --IS_DOWNLOADED=true
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

make: *** No rule to make target `with'.  Stop.
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build" "--IBM_DB_HOME=/private/var/tmp/dir" "with" "spaces/subdir/node_modules/ibm_db/installer/clidriver" "--IBM_DB_HOME_WIN=%IBM_DB_HOME%" "--IS_DOWNLOADED=true"
gyp ERR! cwd /private/var/tmp/dir with spaces/subdir/node_modules/ibm_db
gyp ERR! node -v v0.12.5
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/bin/sh -c node-gyp configure build --IBM_DB_HOME=$IBM_DB_HOME --IBM_DB_HOME_WIN=%IBM_DB_HOME% --IS_DOWNLOADED=true' }
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "ibm_db"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE

npm ERR! ibm_db@0.0.14 install: `node installer/driverInstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ibm_db@0.0.14 install script 'node installer/driverInstall.js'.
npm ERR! This is most likely a problem with the ibm_db package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node installer/driverInstall.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls ibm_db
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/tmp/dir with spaces/subdir/npm-debug.log
```

**Comment by bimalkjha** [comment]
It is not the ibm_db issue. It is node-gyp issue which is used to compile the source code of ibm_db/src folder. Issue already reported here for node-gyp package: https://github.com/nodejs/node-gyp/issues/65
Unfortunately I don't see its fix. Workaround suggest not to use install path with spaces. Thanks.
