### ISSUE TITLE
Synchronous executeNonQuery()

### ISSUE THREAD

**Issue by lucaskuperman** [ibmdb/node-ibm_db#583]
Hello, I'm attempting to use ibm_db on a serverless IBMFunction, and for that, would be beneficial to have a executeNonQuerySync() method. Is there already such a method? If not, is there a plan for it? If not, how can I easily and synchronously run an update and get the number of rows affected? Thanks!

**Comment by bimalkjha** [comment]
@lucaskuperman You can use executeNonQuerySync() method in your code. It is supported in ibm_db. Only thing is documentation was missing that I added now. You can see its use in test file here: https://github.com/ibmdb/node-ibm_db/blob/master/test/test-chinese-char.js#L34 . Thanks.
