### ISSUE TITLE
Support for JSON2BSON and BSON2JSON for JSON objects

### ISSUE THREAD

**Issue by ashutoshrnjn** [ibmdb/node-ibm_db#584]
As per the IBM DB2 SYSTOOLS Documentation, the suggested approach of inserting or retrieving  JSON data to and from Database is to use JSON2BSON and BSON2JSON function.
I couldn't found the implementation for these function in current ibm_db library.

Please suggest how can we implement this.

**Comment by bimalkjha** [comment]
@ashutoshrnjn JSON2BSON and BSON2JSON functions should be used in SQL as UDF. There is no API available for it in Db2. For example, you can execute below queries to work with JSON data in Db2:
```
CREATE TABLE TEST."book" (ID CHAR(12) FOR BIT DATA NOT NULL,DATA BLOB(1K) INLINE LENGTH 250, ROWCREATED TIMESTAMP(12) NOT NULL WITH DEFAULT,PRIMARY KEY(ID)) ORGANIZE BY ROW
INSERT INTO TEST."book" (ID,DATA) VALUES(x'5af57dadacbc336e28621f32', JSON2BSON('{"_id":{"$oid":"5af57da5acbc336e28621f32"}, "name":"math"}'))
INSERT INTO TEST."book" (ID,DATA) VALUES(x'5af57dadacbc336e28621f33', JSON2BSON('{"_id":{"$oid":"5af57dadacbc336e28621f33"}, "name":"history"}'))
SELECT ID, DATA  FROM TEST."book" 
CREATE INDEX TEST."book_xname" ON TEST."book" ( JSON_VAL(DATA, 'name', 's:1024:na'))
SELECT JSON_VAL(DATA, 'name', 's:1024:na')  FROM TEST."book" 
```
In SYSTOOLS documentation, you can how JSON2BSON is used in SQL: https://www.ibm.com/support/knowledgecenter/SSEPGG_11.5.0/com.ibm.swg.im.dbclient.json.doc/doc/r0070290.html . JSON support in Db2 has nothing to do with ibm_db. Db2 provides UDF for JSON support and those UDFs should be used in SQL. Thanks.
