### ISSUE TITLE
Security Vulnerability in unzipper@0.8.14 calls fstream@1.0.11

### ISSUE THREAD

**Issue by LmKupke** [ibmdb/node-ibm_db#588]
https://www.npmjs.com/advisories/886

**Comment by bimalkjha** [comment]
As per package.json of ibm_db, fstream@1.0.12 get installed before installation of unzipper and unzipper uses the fstream@1.0.12 as a higher version is already installed. So, when you install ibm_db, there is no security issue as latest fstream is used. Anyway, I would pumpup the unzipper version. Thanks.
