### ISSUE TITLE
LOB data is truncated by null ( x00 )

### ISSUE THREAD

**Issue by netsmile** [ibmdb/node-ibm_db#59]
Using the ibm_db node module to access a DB2 with codepage 1208. One of the columns in the database is a CLOB and can contain unicode characters. What I am seeing is that the the result set coming back from the query is dropping a lot of the text.

conn.query('select * from schema.table', function (err, data) {
    if (err) console.log(err);
    else console.log(data);
    conn.close(function () {
      console.log('done');
    });
  });

The CLI trace shows the app and database are in codepage 1208 and I can see the full text .
CLI trace snippet showing codepage info:
( Application Codepage=1208, Database  Codepage=1208, Database XML Codepage=1208, Char Send/Recv Codepage=1208, Graphic Send/Recv Codepage=1200, XML Send/Recv Codepage=1208 )

**Comment by bimalkjha** [comment]
console.log(data) writes data till the null character. Your CLOB data has null characters and hence nodes does not print any data after it hit the null character. Simple solution is to modify your query and use REPLACE function to replace all '\0' by ' ' like REPLACE(T.TEXT, '\0', ' '). I verified and it seems working for me. Thanks.
