### ISSUE TITLE
unable to npm install ibm_db on z/OS 

### ISSUE THREAD

**Issue by patbossman** [ibmdb/node-ibm_db#590]
> node installer/driverInstall.js

platform =  os390
oput 'DSNC10.SDSNMACS(DSNAO64C)' '/doeu/doedba/node-samp2/node_modules/ibm_db/build/dsnao64c.x'

{ Error: Command failed: node-gyp configure build  --IS_DOWNLOADED=false --IBM_DB_HOME="$IBM_DB_HOME"
FSUM9380 make: Unknown option -C
Usage: make [-eEinpqrstuvVx] [-k|-S] [-c dir] [-D macro=value] [-f file] [macro=value ...] [target ...]
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lpp/nodejs/v8r0/cnj/IBM/node-v8.16.0-os390-s390x/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System OS/390 26.00
gyp ERR! command "/usr/lpp/nodejs/v8r0/cnj/IBM/node-v8.16.0-os390-s390x/bin/node" "/usr/lpp/nodejs/v8r0/cnj/IBM/node-v8.16.0-os390-s390x/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build" "--IS_DOWNLOADED=false" "--IBM_DB_HOME=DSNC10"
gyp ERR! cwd /doeu/doedba/node-samp2/node_modules/ibm_db
gyp ERR! node -v v8.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 

    at ChildProcess.exithandler (child_process.js:281:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:934:16)
    at Socket.stream.socket.on (internal/child_process.js:355:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:561:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node-gyp configure build  --IS_DOWNLOADED=false --IBM_DB_HOME="$IBM_DB_HOME"' }
npm WARN node-samp2@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ibm_db@2.6.1 install: `node installer/driverInstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ibm_db@2.6.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /doeu/doedba/.npm/_logs/2019-11-19T01_23_57_759Z-debug.log

**Comment by patbossman** [comment]
[npm-debug.log](https://github.com/ibmdb/node-ibm_db/files/3864091/npm-debug.log)

**Comment by bimalkjha** [comment]
>> FSUM9380 make: Unknown option -C
Usage: make [-eEinpqrstuvVx] [-k|-S] [-c dir] [-D macro=value] [-f file] [macro=value ...] [target ...]
gyp ERR! build error
gyp ERR! stack Error: make failed with exit code: 2

@patbossman It looks issue with node.js package [node-gyp](https://www.npmjs.com/package/node-gyp) on os390. It is not using correct option for os390.
Please install latest node-gyp using command `npm install -g node-gyp` and update the line no 164 in file `node-gyp/lib/build.js` from `      argv.push('-C')` to `      argv.push('-c')` and save it. Then try to install ibm_db by following the instructions documented here: https://github.com/ibmdb/node-ibm_db#configure-odbc-driver-on-zos

**Comment by patbossman** [comment]
npm install

> ibm_db@2.6.1 install /doeu/doedba/odbc-test3/node_modules/node-ibm_db
> node installer/driverInstall.js

platform =  os390
oput 'DSNC10.SDSNMACS(DSNAO64C)' '/doeu/doedba/odbc-test3/node_modules/node-ibm_db/build/dsnao64c.x'

{ Error: Command failed: node-gyp configure build  --IS_DOWNLOADED=false --IBM_DB_HOME="$IBM_DB_HOME"
FSUM9380 make: Unknown option -C
Usage: make [-eEinpqrstuvVx] [-k|-S] [-c dir] [-D macro=value] [-f file] [macro=value ...] [target ...]
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/doeu/doedba/node-v6.16.0-os390-s390x/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System OS/390 26.00
gyp ERR! command "/doeu/doedba/node-v6.16.0-os390-s390x/bin/node" "/doeu/doedba/node-v6.16.0-os390-s390x/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build" "--IS_DOWNLOADED=false" "--IBM_DB_HOME=DSNC10"
gyp ERR! cwd /doeu/doedba/odbc-test3/node_modules/node-ibm_db
gyp ERR! node -v v6.16.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

    at ChildProcess.exithandler (child_process.js:199:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:939:16)
    at Socket.<anonymous> (internal/child_process.js:370:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:509:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node-gyp configure build  --IS_DOWNLOADED=false --IBM_DB_HOME="$IBM_DB_HOME"' }

npm ERR! OS/390 26.00
npm ERR! argv "/doeu/doedba/node-v6.16.0-os390-s390x/bin/node" "/doeu/doedba/node-v6.16.0-os390-s390x/bin/npm" "install"
npm ERR! node v6.16.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! ibm_db@2.6.1 install: `node installer/driverInstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ibm_db@2.6.1 install script 'node installer/driverInstall.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ibm_db package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node installer/driverInstall.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ibm_db
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ibm_db
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /doeu/doedba/odbc-test3/node_modules/node-ibm_db/npm-debug.log

**Comment by patbossman** [comment]
[npm-debug.log](https://github.com/ibmdb/node-ibm_db/files/3870123/npm-debug.log)

**Comment by bimalkjha** [comment]
You are still hitting the "make: Unknown option -C" error coming from node-gyp and your node-gyp version is still v3.4.0

**Comment by patbossman** [comment]
The -c is lowercase, as you asked me to change it.  I had to switch to use a local copy of node, because our global directory is mounted read only (and this will be common on z). 

But my npm -g list says node-gyp 6.0

$ npm -g list
/doeu/doedba/node-v6.16.0-os390-s390x/lib
+-- node-gyp@6.0.1
| +-- env-paths@2.2.0
| +-- glob@7.1.6
| | +-- fs.realpath@1.0.0
| | +-- inflight@1.0.6
| | | `-- wrappy@1.0.2
| | +-- inherits@2.0.4
| | +-- minimatch@3.0.4
| | | `-- brace-expansion@1.1.11
| | |   +-- balanced-match@1.0.0
| | |   `-- concat-map@0.0.1
| | +-- once@1.4.0
| | `-- path-is-absolute@1.0.1
| +-- graceful-fs@4.2.3
| +-- mkdirp@0.5.1
| | `-- minimist@0.0.8
| +-- nopt@4.0.1
| | +-- abbrev@1.1.1
| | `-- osenv@0.1.5
| |   +-- os-homedir@1.0.2
| |   `-- os-tmpdir@1.0.2
| +-- npmlog@4.1.2
| | +-- are-we-there-yet@1.1.5
| | | +-- delegates@1.0.0
| | | `-- readable-stream@2.3.6
| | |   +-- core-util-is@1.0.2
| | |   +-- isarray@1.0.0
| | |   +-- process-nextick-args@2.0.1
| | |   +-- string_decoder@1.1.1
| | |   `-- util-deprecate@1.0.2
| | +-- console-control-strings@1.1.0
| | +-- gauge@2.7.4
| | | +-- aproba@1.2.0
| | | +-- has-unicode@2.0.1
| | | +-- object-assign@4.1.1
| | | +-- signal-exit@3.0.2
| | | +-- string-width@1.0.2
| | | | +-- code-point-at@1.1.0
| | | | `-- is-fullwidth-code-point@1.0.0
| | | |   `-- number-is-nan@1.0.1
| | | +-- strip-ansi@3.0.1
| | | | `-- ansi-regex@2.1.1
| | | `-- wide-align@1.1.3
| | `-- set-blocking@2.0.0
| +-- request@2.88.0
| | +-- aws-sign2@0.7.0
| | +-- aws4@1.8.0
| | +-- caseless@0.12.0
| | +-- combined-stream@1.0.8
| | | `-- delayed-stream@1.0.0
| | +-- extend@3.0.2
| | +-- forever-agent@0.6.1
| | +-- form-data@2.3.3
| | | `-- asynckit@0.4.0
| | +-- har-validator@5.1.3
| | | +-- ajv@6.10.2
| | | | +-- fast-deep-equal@2.0.1
| | | | +-- fast-json-stable-stringify@2.0.0
| | | | +-- json-schema-traverse@0.4.1
| | | | `-- uri-js@4.2.2
| | | |   `-- punycode@2.1.1
| | | `-- har-schema@2.0.0
| | +-- http-signature@1.2.0
| | | +-- assert-plus@1.0.0
| | | +-- jsprim@1.4.1
| | | | +-- extsprintf@1.3.0
| | | | +-- json-schema@0.2.3
| | | | `-- verror@1.10.0
| | | `-- sshpk@1.16.1
| | |   +-- asn1@0.2.4
| | |   +-- bcrypt-pbkdf@1.0.2
| | |   +-- dashdash@1.14.1
| | |   +-- ecc-jsbn@0.1.2
| | |   +-- getpass@0.1.7
| | |   +-- jsbn@0.1.1
| | |   +-- safer-buffer@2.1.2
| | |   `-- tweetnacl@0.14.5
| | +-- is-typedarray@1.0.0
| | +-- isstream@0.1.2
| | +-- json-stringify-safe@5.0.1
| | +-- mime-types@2.1.25
| | | `-- mime-db@1.42.0
| | +-- oauth-sign@0.9.0
| | +-- performance-now@2.1.0
| | +-- qs@6.5.2
| | +-- safe-buffer@5.1.2
| | +-- tough-cookie@2.4.3
| | | +-- psl@1.4.0
| | | `-- punycode@1.4.1
| | +-- tunnel-agent@0.6.0
| | `-- uuid@3.3.3
| +-- rimraf@2.7.1
| +-- semver@5.7.1
| +-- tar@4.4.13
| | +-- chownr@1.1.3
| | +-- fs-minipass@1.2.7
| | +-- minipass@2.9.0
| | +-- minizlib@1.3.3
| | `-- yallist@3.1.1
| `-- which@1.3.1
|   `-- isexe@2.0.0
`-- npm@3.10.10
  +-- abbrev@1.0.9
  +-- ansi-regex@2.0.0
  +-- ansicolors@0.3.2
  +-- ansistyles@0.1.3
  +-- aproba@1.0.4
  +-- archy@1.0.0
  +-- asap@2.0.5
  +-- chownr@1.0.1
  +-- cmd-shim@2.0.2
  +-- columnify@1.5.4
  | `-- wcwidth@1.0.0
  |   `-- defaults@1.0.3
  |     `-- clone@1.0.2
  +-- config-chain@1.1.11
  | `-- proto-list@1.2.4
  +-- debuglog@1.0.1
  +-- dezalgo@1.0.3
  +-- editor@1.0.0
  +-- fs-vacuum@1.2.9
  +-- fs-write-stream-atomic@1.0.8
  +-- fstream@1.0.10
  +-- fstream-npm@1.2.0
  | `-- fstream-ignore@1.0.5
  |   `-- minimatch@3.0.3
  |     `-- brace-expansion@1.1.6
  |       +-- balanced-match@0.4.2
  |       `-- concat-map@0.0.1
  +-- glob@7.1.0
  | +-- fs.realpath@1.0.0
  | +-- minimatch@3.0.3
  | | `-- brace-expansion@1.1.6
  | |   +-- balanced-match@0.4.2
  | |   `-- concat-map@0.0.1
  | `-- path-is-absolute@1.0.1
  +-- graceful-fs@4.1.9
  +-- has-unicode@2.0.1
  +-- hosted-git-info@2.1.5
  +-- iferr@0.1.5
  +-- imurmurhash@0.1.4
  +-- inflight@1.0.5
  +-- inherits@2.0.3
  +-- ini@1.3.4
  +-- init-package-json@1.9.4
  | +-- glob@6.0.4
  | | +-- minimatch@3.0.3
  | | | `-- brace-expansion@1.1.6
  | | |   +-- balanced-match@0.4.2
  | | |   `-- concat-map@0.0.1
  | | `-- path-is-absolute@1.0.0
  | `-- promzard@0.3.0
  +-- lockfile@1.0.2
  +-- lodash._baseindexof@3.1.0
  +-- lodash._baseuniq@4.6.0
  | +-- lodash._createset@4.0.3
  | `-- lodash._root@3.0.1
  +-- lodash._bindcallback@3.0.1
  +-- lodash._cacheindexof@3.0.2
  +-- lodash._createcache@3.1.2
  +-- lodash._getnative@3.9.1
  +-- lodash.clonedeep@4.5.0
  +-- lodash.restparam@3.6.1
  +-- lodash.union@4.6.0
  +-- lodash.uniq@4.5.0
  +-- lodash.without@4.4.0
  +-- mkdirp@0.5.1
  | `-- minimist@0.0.8
  +-- node-gyp@3.4.0
  | +-- minimatch@3.0.3
  | | `-- brace-expansion@1.1.6
  | |   +-- balanced-match@0.4.2
  | |   `-- concat-map@0.0.1
  | +-- npmlog@3.1.2
  | | +-- are-we-there-yet@1.1.2
  | | | `-- delegates@1.0.0
  | | +-- console-control-strings@1.1.0
  | | +-- gauge@2.6.0
  | | | +-- has-color@0.1.7
  | | | +-- object-assign@4.1.0
  | | | +-- signal-exit@3.0.0
  | | | +-- string-width@1.0.2
  | | | | +-- code-point-at@1.0.0
  | | | | | `-- number-is-nan@1.0.0
  | | | | `-- is-fullwidth-code-point@1.0.0
  | | | |   `-- number-is-nan@1.0.0
  | | | `-- wide-align@1.1.0
  | | `-- set-blocking@2.0.0
  | `-- path-array@1.0.1
  |   `-- array-index@1.0.0
  |     +-- debug@2.2.0
  |     | `-- ms@0.7.1
  |     `-- es6-symbol@3.1.0
  |       +-- d@0.1.1
  |       `-- es5-ext@0.10.12
  |         `-- es6-iterator@2.0.0
  +-- nopt@3.0.6
  +-- normalize-git-url@3.0.2
  +-- normalize-package-data@2.3.5
  | `-- is-builtin-module@1.0.0
  |   `-- builtin-modules@1.1.1
  +-- npm-cache-filename@1.0.2
  +-- npm-install-checks@3.0.0
  +-- npm-package-arg@4.2.0
  +-- npm-registry-client@7.2.1
  | +-- concat-stream@1.5.2
  | | +-- readable-stream@2.0.6
  | | | +-- core-util-is@1.0.2
  | | | +-- isarray@1.0.0
  | | | +-- process-nextick-args@1.0.7
  | | | +-- string_decoder@0.10.31
  | | | `-- util-deprecate@1.0.2
  | | `-- typedarray@0.0.6
  | +-- npmlog@3.1.2
  | | +-- are-we-there-yet@1.1.2
  | | | `-- delegates@1.0.0
  | | +-- console-control-strings@1.1.0
  | | +-- gauge@2.6.0
  | | | +-- has-color@0.1.7
  | | | +-- object-assign@4.1.0
  | | | +-- signal-exit@3.0.0
  | | | +-- string-width@1.0.2
  | | | | +-- code-point-at@1.0.0
  | | | | | `-- number-is-nan@1.0.0
  | | | | `-- is-fullwidth-code-point@1.0.0
  | | | |   `-- number-is-nan@1.0.0
  | | | `-- wide-align@1.1.0
  | | `-- set-blocking@2.0.0
  | `-- retry@0.10.0
  +-- npm-user-validate@0.1.5
  +-- npmlog@4.0.0
  | +-- are-we-there-yet@1.1.2
  | | `-- delegates@1.0.0
  | +-- console-control-strings@1.1.0
  | +-- gauge@2.6.0
  | | +-- has-color@0.1.7
  | | +-- object-assign@4.1.0
  | | +-- signal-exit@3.0.0
  | | +-- string-width@1.0.2
  | | | +-- code-point-at@1.0.0
  | | | | `-- number-is-nan@1.0.0
  | | | `-- is-fullwidth-code-point@1.0.0
  | | |   `-- number-is-nan@1.0.0
  | | `-- wide-align@1.1.0
  | `-- set-blocking@2.0.0
  +-- once@1.4.0
  +-- opener@1.4.2
  +-- osenv@0.1.3
  | +-- os-homedir@1.0.1
  | `-- os-tmpdir@1.0.1
  +-- path-is-inside@1.0.2
  +-- read@1.0.7
  | `-- mute-stream@0.0.5
  +-- read-cmd-shim@1.0.1
  +-- read-installed@4.0.3
  | `-- util-extend@1.0.3
  +-- read-package-json@2.0.4
  | +-- glob@6.0.4
  | | +-- minimatch@3.0.3
  | | | `-- brace-expansion@1.1.6
  | | |   +-- balanced-match@0.4.2
  | | |   `-- concat-map@0.0.1
  | | `-- path-is-absolute@1.0.0
  | `-- json-parse-helpfulerror@1.0.3
  |   `-- jju@1.3.0
  +-- read-package-tree@5.1.5
  +-- readable-stream@2.1.5
  | +-- buffer-shims@1.0.0
  | +-- core-util-is@1.0.2
  | +-- isarray@1.0.0
  | +-- process-nextick-args@1.0.7
  | +-- string_decoder@0.10.31
  | `-- util-deprecate@1.0.2
  +-- readdir-scoped-modules@1.0.2
  +-- realize-package-specifier@3.0.3
  +-- request@2.75.0
  | +-- aws-sign2@0.6.0
  | +-- aws4@1.4.1
  | +-- bl@1.1.2
  | | `-- readable-stream@2.0.6
  | |   +-- core-util-is@1.0.2
  | |   +-- isarray@1.0.0
  | |   +-- process-nextick-args@1.0.7
  | |   +-- string_decoder@0.10.31
  | |   `-- util-deprecate@1.0.2
  | +-- caseless@0.11.0
  | +-- combined-stream@1.0.5
  | | `-- delayed-stream@1.0.0
  | +-- extend@3.0.0
  | +-- forever-agent@0.6.1
  | +-- form-data@2.0.0
  | | `-- asynckit@0.4.0
  | +-- har-validator@2.0.6
  | | +-- chalk@1.1.3
  | | | +-- ansi-styles@2.2.1
  | | | +-- escape-string-regexp@1.0.5
  | | | +-- has-ansi@2.0.0
  | | | `-- supports-color@2.0.0
  | | +-- commander@2.9.0
  | | | `-- graceful-readlink@1.0.1
  | | +-- is-my-json-valid@2.15.0
  | | | +-- generate-function@2.0.0
  | | | +-- generate-object-property@1.2.0
  | | | | `-- is-property@1.0.2
  | | | +-- jsonpointer@4.0.0
  | | | `-- xtend@4.0.1
  | | `-- pinkie-promise@2.0.1
  | |   `-- pinkie@2.0.4
  | +-- hawk@3.1.3
  | | +-- boom@2.10.1
  | | +-- cryptiles@2.0.5
  | | +-- hoek@2.16.3
  | | `-- sntp@1.0.9
  | +-- http-signature@1.1.1
  | | +-- assert-plus@0.2.0
  | | +-- jsprim@1.3.1
  | | | +-- extsprintf@1.0.2
  | | | +-- json-schema@0.2.3
  | | | `-- verror@1.3.6
  | | `-- sshpk@1.10.1
  | |   +-- asn1@0.2.3
  | |   +-- assert-plus@1.0.0
  | |   +-- bcrypt-pbkdf@1.0.0
  | |   +-- dashdash@1.14.0
  | |   +-- ecc-jsbn@0.1.1
  | |   +-- getpass@0.1.6
  | |   +-- jodid25519@1.0.2
  | |   +-- jsbn@0.1.0
  | |   `-- tweetnacl@0.14.3
  | +-- is-typedarray@1.0.0
  | +-- isstream@0.1.2
  | +-- json-stringify-safe@5.0.1
  | +-- mime-types@2.1.12
  | | `-- mime-db@1.24.0
  | +-- node-uuid@1.4.7
  | +-- oauth-sign@0.8.2
  | +-- qs@6.2.1
  | +-- stringstream@0.0.5
  | +-- tough-cookie@2.3.1
  | `-- tunnel-agent@0.4.3
  +-- retry@0.10.0
  +-- rimraf@2.5.4
  +-- semver@5.3.0
  +-- sha@2.0.1
  +-- slide@1.1.6
  +-- sorted-object@2.0.1
  +-- strip-ansi@3.0.1
  +-- tar@2.2.1
  | `-- block-stream@0.0.8
  +-- text-table@0.2.0
  +-- uid-number@0.0.6
  +-- umask@1.1.0
  +-- unique-filename@1.1.0
  | `-- unique-slug@2.0.0
  +-- unpipe@1.0.0
  +-- validate-npm-package-license@3.0.1
  | +-- spdx-correct@1.0.2
  | | `-- spdx-license-ids@1.2.0
  | `-- spdx-expression-parse@1.0.2
  |   +-- spdx-exceptions@1.0.4
  |   `-- spdx-license-ids@1.2.0
  +-- validate-npm-package-name@2.2.2
  | `-- builtins@0.0.7
  +-- which@1.2.11
  | `-- isexe@1.1.2
  +-- wrappy@1.0.2
  `-- write-file-atomic@1.2.0

**Comment by patbossman** [comment]
Ok, I see it was picking up node-gyp from under npm/node_modules/node-gyp, so I updated that one (which is not updated by -g, ...?) 

New error:
$ npm install ibm_db

> ibm_db@2.6.1 install /doeu/doedba/odbc-test3/node_modules/ibm_db
> node installer/driverInstall.js

platform =  os390
oput 'DSNC10.SDSNMACS(DSNAO64C)' '/doeu/doedba/odbc-test3/node_modules/ibm_db/build/dsnao64c.x'

{ Error: Command failed: node-gyp configure build  --IS_DOWNLOADED=false --IBM_DB_HOME="$IBM_DB_HOME"
make: Makefile: line 14: Error -- FSUM8232 Expecting macro or rule defn, found neither
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 255
gyp ERR! stack     at ChildProcess.onExit (/doeu/doedba/node-v6.16.0-os390-s390x/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System OS/390 26.00
gyp ERR! command "/doeu/doedba/node-v6.16.0-os390-s390x/bin/node" "/doeu/doedba/node-v6.16.0-os390-s390x/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build" "--IS_DOWNLOADED=false" "--IBM_DB_HOME=DSNC10"
gyp ERR! cwd /doeu/doedba/odbc-test3/node_modules/ibm_db
gyp ERR! node -v v6.16.0
gyp ERR! node-gyp -v v6.0.1
gyp ERR! not ok 

    at ChildProcess.exithandler (child_process.js:199:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:939:16)
    at Socket.<anonymous> (internal/child_process.js:370:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:509:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node-gyp configure build  --IS_DOWNLOADED=false --IBM_DB_HOME="$IBM_DB_HOME"' }
npm WARN odbc-test3@1.0.0 No description
npm WARN odbc-test3@1.0.0 No repository field.
npm ERR! OS/390 26.00
npm ERR! argv "/doeu/doedba/node-v6.16.0-os390-s390x/bin/node" "/doeu/doedba/node-v6.16.0-os390-s390x/bin/npm" "install" "ibm_db"
npm ERR! node v6.16.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! ibm_db@2.6.1 install: `node installer/driverInstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ibm_db@2.6.1 install script 'node installer/driverInstall.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ibm_db package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node installer/driverInstall.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ibm_db
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ibm_db
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /doeu/doedba/odbc-test3/npm-debug.log

**Comment by patbossman** [comment]
[npm-debug3.log](https://github.com/ibmdb/node-ibm_db/files/3870590/npm-debug3.log)

**Comment by patbossman** [comment]
ok - was picking up wrong make.  After that was fixed, did not need to change anything.
