### ISSUE TITLE
behaviour change between 2.6.0 and 2.6.1 related to empty sub-select warning vs. failure

### ISSUE THREAD

**Issue by chris-ratcliffe** [ibmdb/node-ibm_db#591]
In version 2.6.0 and previous versions, running a statement like the following:

```
DELETE FROM TABLEA 
WHERE CATEGORY_ID IN 
  ( SELECT CATEGORY_ID FROM TABLEB B, TABLEC C 
    WHERE B.CATEGORY_ID=C.ID AND B.SURVEY_ID=? AND \"GROUP\"=?
  ) 
AND SURVEY_ID=?"
```

would work fine, even if the sub-select returned an empty set.  However, starting in 2.6.1, the statement is failing when run with the executeNonQuery() function, such that the err argument is non-null in the callback function.  The SQL error being returned is sql100w , which is not really an error at all, and simply an indication that the fetch was empty.  But again, starting in the latest version, its now causing the error path to be executed in the callback.

**Comment by bimalkjha** [comment]
@chris-ratcliffe Please pull the latest code from github and verify. We have delivered fix for this issue, hence closing it. Thanks.

**Comment by chris-ratcliffe** [comment]
@bimalkjha , I tend to install using npm.  Will there a 2.6.2 release available with the fix?

**Comment by bimalkjha** [comment]
@chris-ratcliffe You can install ibm_db@2.6.3. Thanks.
