### ISSUE TITLE
npm install issue with Node V6.16.0

### ISSUE THREAD

**Issue by lyangus** [ibmdb/node-ibm_db#592]
I did he following on my Db2 z/OS machine:
8.3.2 Manual Installation by using git clone
Using Git on z/OS, clone the GitHub respository.

git clone git://github.com/ibmdb/node-ibm_db .   <-- this failed and afetr I changed my node 
                                                                                          from V6.14.4 to V6.16.0.  It worked fine
cd node-ibm_db
Install the ibm_db module dependencies with:

npm install .   <--- give me warning

I  did npm install and it shows me this message:
# npm install
npm WARN lifecycle ibm_db@2.6.1~install: cannot run in wd %s %s (wd=%s) ibm_db@2.6.1 node installer/driverInstall.js /u/oeusr02/node-ibm_db
ibm_db@2.6.1 /u/oeusr02/node-ibm_db
+-- async@2.6.3 
| `-- lodash@4.17.15 
+-- bindings@1.5.0 

Then I go to node-ibm_db/test, try to run the sample testcase 

node test-date.js, it gave me the following errors:/u/oeusr02/node-ibm_db/node_modules/bindings/bindings.js:135
 throw err;
 ^
Error: Could not locate the bindings file. Tried:
→ /u/oeusr02/node-ibm_db/build/odbc_bindings.node
→ /u/oeusr02/node-ibm_db/lib/binding/node-v48-os390-s390x/odbc_bindings.node
   at bindings (/u/oeusr02/node-ibm_db/node_modules/bindings/bindings.js:126:9)
   at Object.<anonymous> (/u/oeusr02/node-ibm_db/lib/odbc.js:31:31)
   at Module._compile (module.js:577:32)
   at Object.Module._extensions..js (module.js:586:10)
   at Module.load (module.js:494:32)
   at tryModuleLoad (module.js:453:12)
   at Function.Module._load (module.js:445:3)
   at Module.require (module.js:504:17)
   at require (internal/module.js:20:19)
   at Object.<anonymous> (/u/oeusr02/node-ibm_db/test/common.js:1:74)

**Comment by lyangus** [comment]
I also tried npm install --unsafe-perm. I got my latest node.js on my EC which is V6.16.0
# node --version
v6.16.0

npm install --unsafe-perm
ibm_db@2.6.1 install /u/oeusr02/node-ibm_db
node installer/driverInstall.js
platform =  os390
oput 'DB2A.SDSNMACS(DSNAO64C)' '/u/oeusr02/node-ibm_db/build/dsnao64c.x'
Assertion failed: r == sizeof msg || (r == -1 && (errno == EAGAIN || errno == EWOULDBLOCK)), file: ../deps/uv/src/unix/signal.c, line: 199, function: uv__signal_handler
CEE5207E The signal SIGABRT was received.
npm ERR! OS/390 26.00
npm ERR! argv "/usr/lpp/nodejs/v600/cnj/IBM/node-v6.16.0-os390-s390x/bin/node" "/usr/lpp/nodejs/v600/cnj/IBM/node-v6.16.0-os390-s390x/bin/npm" "install" "--unsafe-perm"
npm ERR! node v6.16.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! ibm_db@2.6.1 install: node installer/driverInstall.js
npm ERR! Exit status 131
npm ERR!
npm ERR! Failed at the ibm_db@2.6.1 install script 'node installer/driverInstall.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ibm_db package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node installer/driverInstall.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ibm_db
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ibm_db
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /u/oeusr02/node-ibm_db/npm-debug.log
#

**Comment by bimalkjha** [comment]
@lyangus Please follow the instructions as documented here: https://github.com/ibmdb/node-ibm_db#configure-odbc-driver-on-zos

**Comment by lyangus** [comment]
I removed everything and reinstalled withNode V8 and it 
works now
