### ISSUE TITLE
Named parameters support

### ISSUE THREAD

**Issue by DarekDan** [ibmdb/node-ibm_db#594]
Is IBM planning on adding support for named parameters? i.e.

`SELECT * FROM TABLE WHERE COLA= :filterOn`

It would be of great help and increase adoption.

**Comment by bimalkjha** [comment]
@DarekDan you can use parameter markers in SQL instead of named parameters. Its simple to use in node.js as documented here: https://github.com/ibmdb/node-ibm_db/blob/master/APIDocumentation.md#executeApi Thanks.

**Comment by DarekDan** [comment]
Classic IBM. Deflect and do not answer.
