### ISSUE TITLE
NODE_MODULE_VERSION error when using imb_db in electron app

### ISSUE THREAD

**Issue by mitchdennett** [ibmdb/node-ibm_db#598]
I'm building an electron app and I'm getting 

```
node_modules/ibm_db/build/Release/odbc_bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 75
```

Tried downloading the -vscode version. I get the below error. Also attached npm log.

```

> ibm_db@2.6.2 install /Development/Electron/GISMCv2/gismc/node_modules/ibm_db
> node installer/driverInstall.js

platform =  darwin , arch =  x64 , node.js version =  v12.13.1
make version =  GNU Make 3.81

Proceeding to build IBM_DB for Electron framework...
/bin/sh: code: command not found
Unable to detect VSCode version, will use Electron version  6.1.5
IBM_DB_HOME environment variable have already been set to -> /Development/clidriver

Downloading of clidriver skipped - build is in progress...

  CXX(target) Release/obj.target/odbc_bindings/src/odbc.o

Error: Command failed: node-gyp configure build  --IS_DOWNLOADED=false --target=6.1.5 --arch=x64 --dist-url=https://atom.io/download/electron --IBM_DB_HOME="$IBM_DB_HOME"
../src/odbc.cpp:215:15: warning: 'Call' is deprecated [-Wdeprecated-declarations]
    data->cb->Call(1, info);
              ^
../../nan/nan.h:1739:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/odbc.cpp:227:15: warning: 'Call' is deprecated [-Wdeprecated-declarations]
    data->cb->Call(2, info);
              ^
../../nan/nan.h:1739:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/odbc.cpp:997:35: error: no matching member function for call to 'ToString'
    Local<String> string = value->ToString(ISOLATE);
                           ~~~~~~~^~~~~~~~
/Users/mdennett/Library/Caches/node-gyp/6.1.5/include/node/v8.h:2504:44: note: candidate function not viable: no known conversion from 'v8::Isolate *' to 'Local<v8::Context>' for 1st argument
  V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
                                           ^
/Users/mdennett/Library/Caches/node-gyp/6.1.5/include/node/v8.h:10433:22: note: candidate function not viable: requires 0 arguments, but 1 was provided
Local<String> Value::ToString() const {
                     ^
../src/odbc.cpp:1235:7: warning: 'Call' is deprecated [-Wdeprecated-declarations]
  cb->Call(1, info);
      ^
../../nan/nan.h:1739:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
3 warnings and 1 error generated.
make: *** [Release/obj.target/odbc_bindings/src/odbc.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build" "--IS_DOWNLOADED=false" "--target=6.1.5" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--IBM_DB_HOME=/Development/clidriver"
gyp ERR! cwd /Development/Electron/GISMCv2/gismc/node_modules/ibm_db
gyp ERR! node -v v12.13.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 

    at ChildProcess.exithandler (child_process.js:295:12)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:210:5)
    at Pipe.<anonymous> (net.js:659:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node-gyp configure build  --IS_DOWNLOADED=false --target=6.1.5 --arch=x64 --dist-url=https://atom.io/download/electron --IBM_DB_HOME="$IBM_DB_HOME"'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ibm_db@2.6.2 install: `node installer/driverInstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ibm_db@2.6.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mdennett/.npm/_logs/2019-12-09T19_48_50_467Z-debug.log
```

Im on macos
[2019-12-09T19_45_29_880Z-debug.log](https://github.com/ibmdb/node-ibm_db/files/3941457/2019-12-09T19_45_29_880Z-debug.log)

**Comment by mitchdennett** [comment]
The version of electron I’m using is 7.1.2

**Comment by bimalkjha** [comment]
@mitchdennett In your install output, we can see below text:
```
Unable to detect VSCode version, will use Electron version  6.1.5
```
Actually, there is no way for ibm_db to find which version of electron you have installed. So, you need to clone latest code of ibm_db from github, modify `ibm_db/installer/driverInstall.js` script, correct the electron version at line no 25, save this file and execute `npm install --vscode` under ibm_db directory. That should fix your issue. Check Electron version in the install output to make sure it is building with correct electron version.
If you know any hack to find electron version in driverInstall.js file while it is executing, please share with me. I would like to implement that. Thanks.

**Comment by mitchdennett** [comment]
@bimalkjha Thanks, I used electron-rebuild to rebuild them with the latest electron version and that worked except now I get this error 
![Screen Shot 2019-12-10 at 8 39 21 AM](https://user-images.githubusercontent.com/16268619/70535736-9379d400-1b2b-11ea-9b13-d6526b705280.png)

**Comment by mitchdennett** [comment]
@bimalkjha Actually, i used the -vscode version and it worked!!! Thank you

**Comment by TrashManOfficial** [comment]
I'm having a similar problem
macOS：12.2.1
electron：v12.0.16
while building an electron APP,I came into this problem
<img width="773" alt="image" src="https://user-images.githubusercontent.com/52907859/168955816-02726ab3-cb25-484e-947e-774c5e1d72a0.png">
then I try npm install --vscode
<img width="801" alt="image" src="https://user-images.githubusercontent.com/52907859/168956054-3a16e79a-d76b-452e-ae15-eac0aa0e39ef.png">
after that I still got the problem blew
<img width="802" alt="image" src="https://user-images.githubusercontent.com/52907859/168956458-e3c1b89a-78ab-45bc-a336-d3b74e86a695.png">

**Comment by bimalkjha** [comment]
@TrashManOfficial It seems you are using electron version v12.0.16 but `npm ls electron` is not showing any version. Either run `npm install electron@v12.0.16` under ibm_db and then `npm install` or open file `ibm_db\installer\driverInstall.js` and update electron version to `12.0.16` at line no 26 and save. Then run `npm install` under ibm_db directory.
If still you see the issue, would suggest to use the same version of node.js as used by vscode or electron. You can also check different options as suggested on [this page](https://stackoverflow.com/questions/46384591/node-was-compiled-against-a-different-node-js-version-using-node-module-versio). Thanks.

**Comment by TrashManOfficial** [comment]
@bimalkjha Thanks for your reply, I figure out this problem was caused by the difference between my node version and my electron version, but I can't change the version of electron or node, so I try to rebuild the ibm_db modules  using script:
`node-gyp rebuild --target=12.0.16 --arch=x64 --dist-url=https://atom.io/download/electron --openssl_fips=X`
then I met another problem,
![LsROiYodAz](https://user-images.githubusercontent.com/52907859/169738182-3d67c06b-30b8-4eba-860e-72c8e177d3a5.png)
I guess this line of driverinstaller didn't execute
`install_name_tool -change libdb2.dylib @loader_path/../../installer/clidriver/lib/libdb2.dylib ./build/Release/odbc_bindings.node`
so I copy this code and run under ibm_db folder, and it works in my development environment, but after I build my app using electron-builder, it can't work again, and I can't locate the issue after build

**Comment by bimalkjha** [comment]
@TrashManOfficial Instead of running the node-gyp command manually, update the electron version in ibm_db\installer\driverInstall.js file as suggested in my previous update and run "npm install -vscode" under ibm_db.
If it also do not work, then you must have to use the same version of node.js as used by electron. Thanks.
