### ISSUE TITLE
Stored procedure support

### ISSUE THREAD

**Issue by ander2** [ibmdb/node-ibm_db#6]
I suppose there's no stored procedure support since it's not documented

Anyway, I've tried to run some tests and I was not able to get any result.

Is there any plan to add stored procedure support?

**Comment by rahulpratik** [comment]
How to call a DB2 stored proc which has input as well as output params? I checked for examples but there aren't any for the same. Can someone highlight how to use the same? This sp has just 1 out param .
If I just use call schema.samplesp(), i am getting error : 
No authorized routine named "schema.SAMPLESP" of type "PROCEDURE" having compatible arguments was found.  SQLSTATE=42884\n',
  state: '42884' }

**Comment by RocketRooster** [comment]
You can't call a SP with one or more params by not specifying parameters. SQL isn't javascript.

**Comment by rahulpratik** [comment]
Thanks for pointing that out. I was able to call SP by CALL schema.samplesp(?) . If the samplesp has no out params, it is working fine. But if the SP has an out param, its failing with same error as above. Please  let me know on how to handle out param while calling SP.

**Comment by RocketRooster** [comment]
Are you using nodeodbc? It doesn't support out params (yet). Declare a cursor for return if you want to retrieve values from your SP.

**Comment by wisewins** [comment]
How do I know if i am using nodeodbc

**Comment by zenflow** [comment]
@ander2 @rahulpratik @wisewins See #7. It has the details of the work-around mentioned above by @RocketRooster

**Comment by bimalkjha** [comment]
Code changes related to Stored Procedure support is pushed on github and will be released soon. You can get it by using `npm install git+https://git@github.com/ibmdb/node-ibm_db.git` command. 
To know how to pass OUT and INPUT parameters for SP, see the test examples which is calling stored procedure synchronously and asynchronously : https://github.com/ibmdb/node-ibm_db/blob/master/test/test-call-stmt.js 
https://github.com/ibmdb/node-ibm_db/blob/master/test/test-call-async.js

Code is currently under testing.. if you face any issue, please report here. This issue will get closed once we release a new version with support of SP. Thanks.

**Comment by bimalkjha** [comment]
@ander2 @rahulpratik @wisewins ibm_db@1.0.1 is released with stored procedure support. You can check https://github.com/ibmdb/node-ibm_db#callStmt for more info. Thanks.
