### ISSUE TITLE
String data right truncation. SQLSTATE=22001

### ISSUE THREAD

**Issue by daniel-ferenczi** [ibmdb/node-ibm_db#60]
When trying to insert longer data into a shorter varchar - for example a 12 long string into a 10 long column, I get the error "String data right truncation. SQLSTATE=22001".

In the self.queue.push method the message is put in the initialErr parameter - however this causes the 
```javascript
if((err && err['message'].search("SQL30081N") != -1) ||
               (initialErr &&
               initialErr['message'].search("SQL30081N") != -1))
```
check to fails, as err['message'] is undefined.
As a consequence, the application exists afterwards.

Would it be possible to change this check, so that no search is performed for error variables lacking a 'message' key?

**Comment by bimalkjha** [comment]
@daniel-ferenczi we can update code to check err['message'] or initialErr['message'] is not undefined then only go for search. Before that could you help to repro the issue? I used below script and can see the message is part of error. 

```javascript
var ibmdb = require("ibm_db")
    , cn = "DRIVER={DB2};DATABASE=sample;HOSTNAME=myhost.ibm.com;UID=myname;PWD=pass;PORT=50000;PROTOCOL=TCPIP";

ibmdb.open(cn, function (err,conn) {
  if (err) return console.log(err);

  conn.querySync("create table tab1 (c1 int, c2 varchar(10))");
  conn.prepare("insert into tab1 values (?, ?)", function(err, stmt) {
    if(err) {
      console.log(err);
      return conn.closeSync();
    }
    stmt.execute([3, 'bimalkumarjha'], function(err, result){
      if(err) console.log(err);
      else {
        result.closeSync();
        conn.query('select * from tab1', function (err, data) {
          if (err) console.log(err);
          else console.log(data);
        });
      }
      conn.query('drop table tab1', function (err, data) {
        if (err) console.log(err);
        conn.close(function () { console.log('done'); });
      });
    });
  });
});
```

**Comment by bimalkjha** [comment]
Also, please fill this form: http://goo.gl/forms/EKzg7A6HZw

**Comment by daniel-ferenczi** [comment]
Done :)
Actually I run the statements directly with query.sync() without preparing them.
Could there be a difference between them when it comes to error handling?
