### ISSUE TITLE
allways end with error when I use fetchAllSync

### ISSUE THREAD

**Issue by coolstate** [ibmdb/node-ibm_db#600]
error: '[node-odbc] Error in ' +
    'ODBCResult::UV_AfterFetchAll; probably your query ' +
    'did not have a result set.',
  sqlcode: -952,

stmt = conn.prepareSync('select * from aaa');
      rs = stmt.executeSync(params);
      rows = rs.fetchAllSync();

affect rows count is about 1000.

can u tell me why? thanks.

**Comment by bimalkjha** [comment]
@coolstate Please share the test case to reproduce the error. We have many test cases under ibm_db/test directory and none is throwing this error. You can update database connection information in file `ibm_db/test/config.testConnectionStrings.json` and execute `node test-fetch-apis.js` command to verify it. This test file is calling fetchAllSync() twice and returns result without any error. Please feel free to modify the file `test-fetch-apis.js` to reproduce your error and share the repro test with us. After getting the repro test, we can investigate to know the reason of this error. Thanks.
