### ISSUE TITLE
Need function to remove broken connections from a Pool

### ISSUE THREAD

**Issue by ardor91** [ibmdb/node-ibm_db#602]
Hello,
I'm faced an issue with Pooling API.
How to reproduce:

1. Initialize Pool:
```
this.pool = new Pool(
            {
                autoCleanIdle: true,
                maxPoolSize: 20,
            });
let result = this.pool.init(this.config.connectionPoolSize, this.config.connectionString);
```
2. Get connection and query simple sql:
```
this.pool.open(this.config.connectionString, (err, db) => {
         if(err) {
             console.log("Open pool connection error: ", err);
             reject(err);
          }
          db.queryResult(sql, parameters, (err, result) => {
               if(err) { 
                    if(err.state = '40003') {
                        this.removeBrokenConnection(db, this.config.sslConnectionString);  //Custom function to remove broken connections
                     } else {
                         console.log("Query result error: " + err); reject(err); 
                      }
                  }
                  else {
                     let res = result.fetchAllSync();
                     resolve(res);
                     result.closeSync(); // Must call in application.
                     db.close();
                    }
               });
           });
```
1st call is okay. Then go to DB2 console and manually terminate opened connection:
(This is only way how can I simulate db2 behaviour. After approx 2-4 hours of inactivity - it closes connections manually)
```
SELECT * FROM SYSIBMADM.APPLICATIONS where APPL_NAME like '%node%'
call sysproc.admin_cmd('force application (13457)')
-- call sysproc.admin_cmd('force application all')
```
When I execute query now - I will have this exeception:
`[IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: \"SSL\".  Communication API being used: \"SOCKETS\".  Location where the error was detected: \"\".  Communication function detecting the error: \"sqlccSSLSocketRead\".  Protocol specific error code(s): \"420\", \"*\", \"*\".  SQLSTATE=08001\r\n`

So, only way how can I avoid such error is by using my custom function
```
private removeBrokenConnection(db, connStr) {
        if(db) {
            db.realClose(() => {
                if(this.pool.poolSize) this.pool.poolSize--;
                this.pool.usedPool[connStr].splice(this.pool.usedPool[connStr].indexOf(db), 1);
            });
        }
    }
```
But it lacks some needed functionality. For example, If I have 20 connections in the Pool and all of them are terminated, then I will remove one connection, then the Pool will give me another broken connection. 
So, ideally I need to close all such connections and create new ones. 
Moreover, seems that `db.connected` can't handle such situations.
```
this.pool.availablePool[this.config.sslConnectionString].forEach(conn => {
            console.log(`Conn status: ${conn.connected ? 'connected': 'broken'}`);
});
```
Displays: 'Conn status: connected'

-----------------
I'm using Node **12.14.0**
ibm_db **2.6.3**

**Comment by bimalkjha** [comment]
@ardor91 If queryResult() hits SQL30081N, we already call `checkConnectionError()` function [here](https://github.com/ibmdb/node-ibm_db/blob/master/lib/odbc.js#L675) to remove all broken connection from the pool. Check it [here](https://github.com/ibmdb/node-ibm_db/blob/master/lib/odbc.js#L433). So, next call of pool.open() after SQL30081N error will get fresh connection as all connections from the pool is already removed.
We have a test file [test-bad-pool-connection-issue-42.js](https://github.com/ibmdb/node-ibm_db/blob/master/test/test-bad-pool-connection-issue-42.js) to test such scenarios. Just update the connection information in `ibm_db/test/config.testConnectionString.json` file and execute the `test/test-bad-pool-connection-issue-42.js` to verify it. You need to update timeout in test-bad-pool-connection-issue-42.js file at last line to 30000 ms before executing it.
To drop all active connections, no need to terminate individual connection on server, you just need to execute `db2stop force; db2start` command. It will terminate and remove all active connections from the server. Please verify it and let us know. Thanks.

**Comment by ardor91** [comment]
@bimalkjha Hi, sorry for late reply, I were busy with other app functionality.
Thanks for your description of this issue. I can't reproduce it anymore via forcing connections to db. Seems work good.
About `db2stop force;` - I can't do it, because we have cloud DB2 and don't have access to CLI terminal.

Last week we are having another similar issue, but I'm not sure if it is related to SQL30081N code. Let me describe this:
Because of our DB structure, we are having Deadlock issues very rare (we are investigating this). After first deadlock issue, all connections to DB totally blocked. One way to solve it (except db2stop/restart) is to execute `call sysproc.admin_cmd('force application all')`. It helps, but after this DB2 driver stopping work without any response code. I did a little investigation and noticed that it hangs on getting new connection from pool:
```
        console.log("Getting connection");
        this.pool.open(this.config.sslConnectionString, (err, db) => {
            console.log("resolving");
            if(err) {
                console.log("Open pool connection error: ", err);
                reject(err);
            }
```
No more logs after line "Getting connection". Then after about 1 minute I have 500 Timeout response.
We have another app written on PHP that uses same db, and it works good after forcing all connections.
Pls review it. If it is not related to first my question - I will open new issue
Thanks!

**Comment by bimalkjha** [comment]
@ardor91 Please open a new issue as it is different than this one. Also, please share are you using maxpoolsize parameter or not. Thanks.
