### ISSUE TITLE
Error: `gyp` failed with exit code: 1

### ISSUE THREAD

**Issue by klaraaaaaaaaaa** [ibmdb/node-ibm_db#603]
I need to use ibm_db on Windows, using node v12.14.0 and node-gyp v6.0.1.
However, when trying to execute a file containing
```
var ibmdb = require('ibm_db');
console.debug("abc");
```
I get the following error (module not found):
```
C:\Users\link\to\project>node db2-test.ts
C:\Users\link\to\project\node_modules\bindings\bindings.js:121
        throw e;
        ^

Error: Das angegebene Modul wurde nicht gefunden.
\\?\C:\Users\link\to\project\node_modules\ibm_db\build\Release\odbc_bindings.node
[90m    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1025:18)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:815:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:727:14)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:852:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:74:18)[39m
    at bindings (C:\Users\link\to\project\node_modules\[4mbindings[24m\bindings.js:112:48)
    at Object.<anonymous> (C:\Users\link\to\project\node_modules\[4mibm_db[24m\lib\odbc.js:31:31)
[90m    at Module._compile (internal/modules/cjs/loader.js:959:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:815:32)[39m
```

I presume that something must have gone wrong with the installation.
1) I downloaded  the clidriver from https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/
2) set the environment variables IBM_DB_HOME and IBM_DB_INSTALLER_URL pointing to the location of the unzipped clidriver-folder
3) installed node-gyp, python and VS 19 and set the paths accordingly
4) ran "npm install ibm_db" - [npm_install_ibm_db.txt](https://github.com/ibmdb/node-ibm_db/files/4009701/npm_install_ibm_db.txt)

Then I tried to rebuild node-gyp with "node-gyp rebuild --debug --IBM_DB_HOME=$IBM_DB_HOME  --IS_DOWNLOADED=true", but it also failed - [node-gyp_rebuild.txt](https://github.com/ibmdb/node-ibm_db/files/4009700/node-gyp_rebuild.txt)

Could you please help me fixing this? Thanks in advance.

**Comment by bimalkjha** [comment]
@klaraaaaaaaaaa Setting both IBM_DB_HOME and IBM_DB_INSTALLER_URL may be causing the issue. If you have downloaded clidriver and set IBM_DB_HOME to the unzipped clidriver folder, it should work fine.
If you want to set IBM_DB_INSTALLER_URL, then it should point to the .zip file and not the unzipped clidriver folder. Also, if IBM_DB_INSTALLER_URL is set, no need to set IBM_DB_HOME.
You can avoid setting of both IBM_DB_INSTALLER_URL or IBM_DB_HOME, if you simply use "npm install ibm_db" command. This command will automatically download clidriver and unzip it for use. Thanks.

**Comment by bimalkjha** [comment]
@klaraaaaaaaaaa After looking on your node-gyp_rebuild.txt file, the issue seems due to Python38. Please use python 2.7.x with ibm_db. We have not verified installation of ibm_db using Python3 yet. Thanks.

**Comment by klaraaaaaaaaaa** [comment]
Thanks for the answer, I downgraded my Python version and edited the IBM_DB_HOME and IBM_DB_URL. However, I get the same error as before.

**Comment by bimalkjha** [comment]
@klaraaaaaaaaaa I hope you have not set both IBM_DB_HOME and IBM_DB_URL. Also, I would suggest to not use these environment variables unless you really need to use it.
Please share the complete output of `npm install ibm_db` so that I can look further about the cause of issue. Thanks.

**Comment by klaraaaaaaaaaa** [comment]
I deleted the IBM_DB_URL and kept the IBM_DB_HOME as I've got some proxy issues and can't download it directly. Here is my output: [npm_install_ibm_db_update.txt](https://github.com/ibmdb/node-ibm_db/files/4034716/npm_install_ibm_db_update.txt)

**Comment by bimalkjha** [comment]
@klaraaaaaaaaaa Thanks for sharing the output file. In the shared file, we can see below lines which provide info about the problem:
```
C:\Users\link\to\project\clidriver_zip\ directory does not exist. Please check if you have set the IBM_DB_HOME environment variable's value correctly.

C:\Users\link\to\project\clidriver_zip\include directory does not exist. Please check if you have set the IBM_DB_HOME environment variable's value correctly.

C:\Users\link\to\project\clidriver_zip\lib directory does not exist. Please check if you have set the IBM_DB_HOME environment variable's value correctly.
```
Seems, IBM_DB_HOME is not set correctly. Please check your clidriver_zip folder. If it have another folder with clidriver, then IBM_DB_HOME should point to `C:\Users\link\to\project\clidriver_zip\clidriver` folder. Basically ibm_db is looking for `lib` folder under `IBM_DB_HOME`. If there is no `lib` or `include` folder, it means `IBM_DB_HOME` is not set correctly. So, please set `IBM_DB_HOME` to `C:\Users\link\to\project\clidriver_zip\clidriver` and install ibm_db. If you still face issue, please share the complete output of `npm install ibm_db` command again. Thanks.

**Comment by klaraaaaaaaaaa** [comment]
Thanks for your answer. I finally succeeded in downloading the driver via

> npm install ibm_db

without the variables. This resulted in the same "node-gyp"-error as the initial problem: [npm_install_ibm_db.txt](https://github.com/ibmdb/node-ibm_db/files/4039297/npm_install_ibm_db.txt)

**Comment by bimalkjha** [comment]
@klaraaaaaaaaaa Thanks for sharing the new output file. In the shared file, I see multiple commands.
First you executed "npm install ibm_db" which installed ibm_db successfully as in below message:
```
node-ibm_db installed successfully!


> ibm_db2@3.0.0 install C:\Users\link\to\project\node_modules\ibm_db2
> node installer/driverInstall.js
```
After installing ibm_db successfully, you have fired command to install `ibm_db2` which is not required. Your error is from `npm install ibm_db2`  command and not from `npm install ibm_db`.
Please note that `ibm_db2` is not the correct node.js driver for db2. It is uploaded by someone else on npm and not maintained. So, first of all, please remove any reference of `ibm_db2` from your application and do not install `ibm_db2`. `ibm_db` is the correct driver name and  you should only use `npm install ibm_db`. Thanks.

**Comment by klaraaaaaaaaaa** [comment]
I was now able to download `ibm_db` directly over npm and it worked fine on Windows and Linux.
Thanks for your support.
