### ISSUE TITLE
How to set NULL value with prepare parameters

### ISSUE THREAD

**Issue by ardor91** [ibmdb/node-ibm_db#604]
Hello,
I'm using `executeNonQuery` with prepared parameters. Everything works good except setting NULL to BLOB or CLOB fields.
I have next object for prepare param:
`{ CType: 'BLOB', DataType: 'BLOB', Data: null }`

Which gives me this error:
`[IBM][CLI Driver][DB2/LINUXX8664] SQL0301N  The value of input variable, expression or parameter number "1" cannot be used because of its data type.  SQLSTATE=07006\r\n'`

I also tried to pass only `null` as parameter (without datatype object), but having same issue.

When I execute plain sql like: `update table set column = null` it works good.

I googled several days, but can't find any solution for this.

**Comment by bimalkjha** [comment]
@ardor91 You can try { CType: 'BLOB', DataType: 'BLOB', Data: '' }. Please share your 'CREATE TABLE' query so that I can create similar table and try. Thanks.

**Comment by ardor91** [comment]
@bimalkjha I currently using this way, because it is one solution for now. But anyway, I need to set NULL because some queries and views may compare this with NULL, not empty string. 

This is my table (I have removed other fields)
```
CREATE TABLE
    RECORD
    (
        ID INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 100, INCREMENT BY 1),
        TITLE_TEXT VARCHAR(128),
        COMPL_MGR_INSTR BLOB(1048576),
        PRIMARY KEY (ID)
    );
```

Thanks

**Comment by bimalkjha** [comment]
@ardor91 We have just pushed the fix of this issue. There was a bug in our code.
You can install the latest code from github using command `npm install git+https://git@github.com/ibmdb/node-ibm_db.git` on non-windows platform and verify the fix. Thanks.
