### ISSUE TITLE
application crashing when trying to connect IBM cloud Db2 high availability database instance 

### ISSUE THREAD

**Issue by ddhabak1** [ibmdb/node-ibm_db#606]
For Db2 cloud  foundry service instance it is working as expected but when migrated to db2 high availability instance application crashing. getting segment fault

`PID 33481 received SIGSEGV for address: 0x0
0   segfault-handler.node               0x00000001026f30c6 _ZL16segfault_handleriP9__siginfoPv + 310
1   libsystem_platform.dylib            0x00007fff71edd42d _sigtramp + 29
2   ???                                 0x0000000000002a35 0x0 + 10805
3   libdb2.dylib                        0x00000001059f9fc3 _Z20sqljrInternalConnectP14db2UCconHandlePbPib + 9491
4   libdb2.dylib                        0x00000001059faecc _Z30sqljrFindBestAddressAndConnectP14db2UCconHandle + 108
5   libdb2.dylib                        0x00000001059ed907 _Z23sqljrDrdaArAuthenticateP14db2UCinterfacelPj + 6247
6   libdb2.dylib                        0x00000001058d32d5 _Z20sqlexAppAuthenticateP14db2UCinterface + 2533
7   libdb2.dylib                        0x00000001059a476b _Z18sqljrDrdaArConnectP14db2UCinterface + 4683
8   libdb2.dylib                        0x00000001058b6ee7 _Z16sqleUCdrdaARinitP14db2UCconHandle + 279
9   libdb2.dylib                        0x0000000105889f41 sqleUCappConnect + 2161
10  libdb2.dylib                        0x00000001053ba1b7 _Z14CLI_sqlConnectP15CLI_CONNECTINFOP5sqlcaP19CLI_ERRORHEADERINFO + 4327
11  libdb2.dylib                        0x0000000105362e33 _Z11SQLConnect2P15CLI_CONNECTINFOPhsS1_sS1_sS1_sh + 2083
12  libdb2.dylib                        0x00000001053794b2 _Z17SQLDriverConnect2P15CLI_CONNECTINFOPvPhsS2_sPsthhP19CLI_ERRORHEADERINFO + 74034
13  libdb2.dylib                        0x0000000105352ce6 SQLDriverConnect + 1206
14  odbc_bindings.node                  0x000000010335a999 _ZN14ODBCConnection7UV_OpenEP9uv_work_s + 55
15  node                                0x000000010099edbe worker + 196
16  libsystem_pthread.dylib             0x00007fff71ee8e65 _pthread_start + 148
17  libsystem_pthread.dylib             0x00007fff71ee483b thread_start + 15
Segmentation fault: 11`

If I use connection pool it is working, so looks like the issue with odbc driver

**Comment by dlholt** [comment]
@ddhabak1 please include some relevant details so the maintainers can help.

For example:

- Node version
- Library version
- DB2 version
- Simple, working code that can be used to recreate the issue
- Instructions for recreating the issue

**Comment by ddhabak1** [comment]
Issue resolved by using ssl connection

**Comment by ddhabak1** [comment]
resolved

**Comment by bimalkjha** [comment]
@ddhabak1 Yes, few db2 instances in cloud has only SSL port active. Thanks.
