### ISSUE TITLE
Error: [IBM][CLI Driver] SQL1022C  There is not enough memory available to process the command.  SQLSTATE=57011

### ISSUE THREAD

**Issue by Kalenzhu** [ibmdb/node-ibm_db#609]
when I use Keystore Files to do SSL connection,there will be an error .
Error: [IBM][CLI Driver] SQL1022C  There is not enough memory available to process the command.  SQLSTATE=57011

Here is parameters I was using
DATABASE=bigsql; HOSTNAME=hdp-master-7.datalake-hdp.zc2.ibm.com ;UID=<username>;PWD=<password>; PORT=52000; PROTOCOL=TCPIP;  SSLClientKeystash=keyclient.sth; Security=SSL; SSLClientKeystoredb=keyclient.kdb

**Comment by bimalkjha** [comment]
@Kalenzhu Here is the details about the error that you are hitting: https://www.ibm.com/support/knowledgecenter/SSEPGG_11.5.0/com.ibm.db2.luw.messages.sql.doc/com.ibm.db2.luw.messages.sql.doc-gentopic5.html#sql1022c
Please check the user response section and try.
Good to check this link too: https://www.ibm.com/support/pages/error-sql1022c-there-not-enough-memory-available-process-command-after-changing-hostname-db2-server

If you are still hitting this error, please share the db2diag.log file from client system.
1. Do you have both bigsql server and ibm_db installed in the same system?
2. Please share operating system of the bigsql and ibm_db systems.
3. Please share output of `db2level` command from the system where `ibm_db` is installed.
4. node.js version in use.
Thanks.

**Comment by Kalenzhu** [comment]
1.Do you have both bigsql server and ibm_db installed in the same system?
no,the remote db2 server is red hat linux, the ibm_db is on my local windows 10 system
2.Please share operating system of the bigsql and ibm_db systems.
remote db2 server is red hat linux,the ibm_db is on my local windows 10 system
3.Please share output of db2level command from the system where ibm_db is installed.
 DB2 client version on my local: DB2 v10.1.0.872

4.node.js version in use.
node version : v10.17.0, ibm_db version is 2.6.3
[db2diag.log](https://github.com/ibmdb/node-ibm_db/files/4187467/db2diag.log)

**Comment by Kalenzhu** [comment]
BTW, as long as there are these 2 parameters(SSLClientKeystoredb, SSLClientKeystash) in connection information, even if values of them are empty, there will be SQL1022C error

**Comment by bimalkjha** [comment]
@Kalenzhu Issue looks due to use of DB2 v10.1.0.872 in client system whose gskit libraries are older and conflicting with the gskit library of ibm_db. There could be few solution as below:

1. set env variable IBM_DB_HOME=<install_dir_of_DB2 v10.1.0.872_client>
npm uninstall ibm_db
npm install ibm_db

2. Remove reference of DB2 v10.1.0.872 from PATH and LIB system environment variables. Remove reference of GSKit too from PATH and LIB env vars.
npm install ibm_db

3. Uninstall DB2 v10.1.0.872 client and install DB2 v11.1.4.5 client from fix central and use it.
Thanks.

**Comment by Kalenzhu** [comment]
I tried Option 2， Removed reference of DB2 GSKit tool so that it will use ODBC driver of ibm_db. Now, ODBC connection is working in my local application. thank you so much!!!

**Comment by bimalkjha** [comment]
Glad to know that your problem is solved! Closing the issue now. Thanks.
