### ISSUE TITLE
is it possible to Jest mock this module

### ISSUE THREAD

**Issue by madsteer** [ibmdb/node-ibm_db#610]
I'm having an issue when trying to mock a module.  I'm getting a similar error message to #271 but the circumstances are different. I'm not actually trying to mock `ibm_db` but rather a module that imports/requires `ibm_db`.

I have a piece of code named `minddb.js` that has the `const ibmdb = require('ibm_db');` in it in `src/db/`.  I'm trying to mock `minddb.js` by putting `src/db/__mocks__/minddb.js` with:
```
const minddb = jest.genMockFromModule('../minddb');

let mockResult = {};

const __setMockResult = (result) => {
  mockResult = result;
}
. . .
minddb.__setMockResult = __setMockResult

module.exports = minddb
```

Then I have a test like so:
```
jest.mock('../../../src/db/minddb');
const ibmdb = jest.genMockFromModule('ibm_db');
const minddb = require('../../../src/db/minddb');
. . .
describe('', () => {
  test('', async() => {
  minddb.__setMockResult(<some data>);
. . .
  });
});
```
When I try to run my test I get the 
```bash
 /Users/<redacted>/. . ./node_modules/ibm_db/lib/odbc.js: Deleting local variable in strict mode (256:4)

        254 |       delete db[key];
        255 |     }
      > 256 |     delete db;
            |     ^
        257 |     db = undefined;
        258 |   }
        259 | }; // ibmdb.clos
```
error.  If I put a `__mocks__/ibm_db.js` at the parent of the project (same folder as `src/` and `node_modules` the problem goes away.  I guess I can just do that, but if some other test doesn't want to mock `ibm_db` in their test, the'll have issues and won't know why,  I'm just perplexed why I'm having trouble getting this to work.  I do this kind of mocking all the time.  Just wondering if there's something about `ibm_db` that I'm not understanding that is making it hard to mock.

**Comment by bimalkjha** [comment]
@madsteer Please comment the line 256 of odbc.js and then run your application. If it works fine without any issue, we can remove "> 256 |     delete db;" code from ibm_db to fix this issue. Thanks.

**Comment by madsteer** [comment]
i had to commend out the `delete db;` at line 256 and 1843 but after I did that the problem went away.  So, if it's safe to do that then I believe this would fix the issue.
