### ISSUE TITLE
Signing App in MacOS gives errors

### ISSUE THREAD

**Issue by mitchdennett** [ibmdb/node-ibm_db#612]
I'm building an electron app. On MacOS during Apple's notarization process I'm gettting the following errors.  The binaries included in the CLIDRIVER are built using an old macos sdk and Apple no longer allows them in applications.

```  "issues": [
    {
      "severity": "error",
      "code": null,
      "path": "GMC.zip/GMC.app/Contents/Resources/app.asar.unpacked/node_modules/ibm_db/installer/clidriver/bin/db2drdat",
      "message": "The binary uses an SDK older than the 10.9 SDK.",
      "docUrl": null,
      "architecture": "x86_64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "GMC.zip/GMC.app/Contents/Resources/app.asar.unpacked/node_modules/ibm_db/installer/clidriver/bin/db2dsdcfgfill",
      "message": "The binary uses an SDK older than the 10.9 SDK.",
      "docUrl": null,
      "architecture": "x86_64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "GMC.zip/GMC.app/Contents/Resources/app.asar.unpacked/node_modules/ibm_db/installer/clidriver/bin/db2support",
      "message": "The binary uses an SDK older than the 10.9 SDK.",
      "docUrl": null,
      "architecture": "x86_64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "GMC.zip/GMC.app/Contents/Resources/app.asar.unpacked/node_modules/ibm_db/installer/clidriver/bin/db2trc",
      "message": "The binary uses an SDK older than the 10.9 SDK.",
      "docUrl": null,
      "architecture": "x86_64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "GMC.zip/GMC.app/Contents/Resources/app.asar.unpacked/node_modules/ibm_db/installer/clidriver/bin/db2level",
      "message": "The binary uses an SDK older than the 10.9 SDK.",
      "docUrl": null,
      "architecture": "x86_64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "GMC.zip/GMC.app/Contents/Resources/app.asar.unpacked/node_modules/ibm_db/installer/clidriver/bin/db2diag",
      "message": "The binary uses an SDK older than the 10.9 SDK.",
      "docUrl": null,
      "architecture": "x86_64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "GMC.zip/GMC.app/Contents/Resources/app.asar.unpacked/node_modules/ibm_db/installer/clidriver/bin/db2cli",
      "message": "The binary uses an SDK older than the 10.9 SDK.",
      "docUrl": null,
      "architecture": "x86_64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "GMC.zip/GMC.app/Contents/Resources/app.asar.unpacked/node_modules/ibm_db/installer/clidriver/lib/libDB2xml4c.dylib",
      "message": "The binary uses an SDK older than the 10.9 SDK.",
      "docUrl": null,
      "architecture": "x86_64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "GMC.zip/GMC.app/Contents/Resources/app.asar.unpacked/node_modules/ibm_db/installer/clidriver/lib/libdb2.dylib",
      "message": "The binary uses an SDK older than the 10.9 SDK.",
      "docUrl": null,
      "architecture": "x86_64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "GMC.zip/GMC.app/Contents/Resources/app.asar.unpacked/node_modules/ibm_db/installer/clidriver/lib/libdb2clixml4c.dylib",
      "message": "The binary uses an SDK older than the 10.9 SDK.",
      "docUrl": null,
      "architecture": "x86_64"
    }
  ]
}```

**Comment by bimalkjha** [comment]
@mitchdennett Please share version of your macos. From terminal you can run `sw_vers` command and share the result. Please share your electron and node.js version too.
We have tested ibm_db using macos version 10.14.6 and it works fine. Thanks.

**Comment by bimalkjha** [comment]
ibm_db works with this configuration on macos: GCC VERSION : Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1 Apple LLVM version 10.0.1 (clang-1001.0.46.4) Target: x86_64-apple-darwin18.7.0 Thread model: posix InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by mitchdennett** [comment]
@bimalkjha 
```
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G1012
```

I've built an electron app. It works fine locally and packaged on other machines. However, I need to get that app notarized through Apple's new notarization system. IBM_DB is packaged with that app and it also goes through the notarization process. The notarization process is complaining that the binaries compiled in the CLIDRIVER used an SDK older than 10.9. If I can't get it notarized my app won't run on any MacOS Catalina machines. 

Does this make sense?

**Comment by bimalkjha** [comment]
@mitchdennett Ok. so it is the apple's notarization process that has issue with older clidriver. 
We are working on to have a latest clidriver for macos. Unfortunately latest clidriver for macos has some issue with SSL connection and IBM team is working to have a special build. Once special build with fix of SSL issue would be available for mac, we'll update clidriver in ibm_db too. Hopefully, that should solve your issue.
Meanwhile, we would recommend to download and install dsdriver from [here](https://ak-delivery04-mul.dhe.ibm.com/sdfdl/v2/sar/CM/IM/08n8l/0/Xa.2/Xb.jusyLTSp44S0wfVmeNIFNTd7ZB8VTFCgDAR6wLLlfJIuGGmevvOqKHSDiKM/Xc.CM/IM/08n8l/0/v11.1.4fp5_macos_dsdriver.dmg/Xd./Xf.LPR.D1vk/Xg.10588147/Xi.habanero/XY.habanero/XZ.607n_azo3NbXsAR38j7KDRi1UNM/v11.1.4fp5_macos_dsdriver.dmg) and install it. Then execute below commands to install ibm_db:
```
export IBM_DB_HOME=/Apllications/dsdriver/
npm install ibm_db
```
Also, is it possible to remove clidriver from `ibm_db/installer/` directory and pass the notarization process? Thanks.

**Comment by mitchdennett** [comment]
@bimalkjha It is possible. But I assume the CLIDRIVER is needed to run the app? I can't remove it and then add it back in. 

I will try the dsdriver and let you know.

**Comment by mitchdennett** [comment]
![Screen Shot 2020-02-20 at 10 08 33 AM](https://user-images.githubusercontent.com/16268619/74947551-02479900-53c9-11ea-9a0f-f0c6f182d002.png)
 I'm getting this when trying to download the DSDRIVER

**Comment by mitchdennett** [comment]
Also is there a timeline for when the CLIDRIVER will be updated?

**Comment by bimalkjha** [comment]
@mitchdennett You can download dsdriver from [this](https://www.ibm.com/support/fixcentral/swg/selectFixes?parent=ibm%7EInformation%2BManagement&product=ibm/Information+Management/IBM+Data+Server+Client+Packages&release=11.1.*&platform=All&function=fixId&fixids=*-dsdriver*FP005*&includeSupersedes=0&source=fc) page too if you are able to access it. Please check. If facing issue, please click on download link for "IBM Data Server Driver Package" near middle of the page after scrolling down on this page: https://www.ibm.com/support/pages/node/1115973
Then you can select the driver for macos and proceed. It just required you to register on ibm site so that you can have an ibmid. Once you get ibmid, you can login and download it. Previous link failed because you may not have ibmid and you might not have logged in. Thanks.

**Comment by bimalkjha** [comment]
We can update clidriver as soon as IBM provides one. Currently IBM do not have a driver that we want to upload. I'll check with IBM team about timeline for availability of driver. @shilumathai FYI. Thanks.

**Comment by bimalkjha** [comment]
@mitchdennett We have updated CLIDRIVER used by open source drivers. Just install ibm_db@2.6.4 and you'll have updated clidriver of version db2 11.1.4.5 on macos. Thanks.

**Comment by mitchdennett** [comment]
@bimalkjha I'm still getting the same error. 

`      "path": "GMC.zip/GMC.app/Contents/Resources/app.asar.unpacked/node_modules/ibm_db/installer/clidriver/lib/libdb2.dylib",
      "message": "The binary uses an SDK older than the 10.9 SDK.",`

**Comment by mitchdennett** [comment]
I did an `otool -l libdb2.dylib` and it shows that the binaries are built using the 10.7 SDK's

`Load command 8
      cmd LC_VERSION_MIN_MACOSX
  cmdsize 16
  version 10.7
      sdk 10.7
`

**Comment by bimalkjha** [comment]
@mitchdennett You are right. Currently, all IBM drivers for macos are built using sdk 10.7. IBM build team is working to upgrade it. It is expected to come up with new driver with updated sdk in July 2020. Thanks.

**Comment by mitchdennett** [comment]
@bimalkjha Thanks for getting back to me. Can we keep this issue open until this gets resolved?
In case other people come across this issue.

**Comment by mitchdennett** [comment]
@bimalkjha Hey, is the new driver still expected for July 2020?

**Comment by bimalkjha** [comment]
@mitchdennett Yes, Db2 Build team is still working on to upgrade SDK on MacOS. Work is not complete yet. Thanks.

**Comment by bimalkjha** [comment]
@mitchdennett I can see new dsdriver image is available [here](https://www.ibm.com/support/fixcentral/swg/selectFixes?parent=ibm%7EInformation%2BManagement&product=ibm/Information+Management/IBM+Data+Server+Client+Packages&release=11.5.4.0*&platform=All&function=fixId&fixids=*-dsdriver*FP000*&includeSupersedes=0&source=fc). You can download and mount it and install it by executing `/Volumes/dsdriver/installDSDriver` script. Then `export IBM_DB_HOME=/Volumes/dsdriver` and `npm install ibm_db`. It should use the new installed driver.
I have checked the SDK version of this new driver. It is of version 10.15:
```
Load command 9
       cmd LC_BUILD_VERSION
   cmdsize 32
  platform macos
       sdk 10.15
     minos 10.15
    ntools 1
      tool ld
   version 556.6
```
We'll update ibm_db to use this new version of driver soon. But, you can verify it by following above step that it solves your problem. Thanks.

**Comment by mitchdennett** [comment]
@bimalkjha Awesome. I will verify and get back to you

**Comment by mitchdennett** [comment]
@bimalkjha I have verified that this passed Apple's notarization process.

**Comment by bimalkjha** [comment]
@mitchdennett We have updated the clidriver for macos. Fresh installation of `ibm_db` should download latest version of clidriver automatically and use it. That should fix this issue now. Hence, closing the issue. Thanks.
