### ISSUE TITLE
Passing parameters as a non-predicate results in an error

### ISSUE THREAD

**Issue by DarekDan** [ibmdb/node-ibm_db#613]
The simplest example to try would be `SELECT ? FROM SYSIBM.SYSDUMMY1`. It will always result in SQL0418N error.

[IBM][CLI Driver][DB2] SQL0418N  The statement was not processed because the statement contains an invalid use of one of the following: an untyped parameter marker, the DEFAULT keyword, or a null value.  SQLSTATE=42610

Regardless of DataType specification. Tested with z/OS. 
Works in JAVA and any mainstream database client (DbVisualizer, DataGrip, Aqua Data Studio)

**Comment by DarekDan** [comment]
It works only in scenarios where parameter type can be implied from the columns, i.e. `CASE WHEN A BETWEN ? AND ? THEN A ELSE 0 END`. But this will work when we cast some parameter types: 
`UPDATE LA
SET AU = CASE WHEN
 AU = ? THEN CAST(? AS CHAR(36))
 ELSE CAST(? AS CHAR(36)) END,
 UPDATE_TS = CURRENT_TIMESTAMP
WHERE AU IN (?, ?);`

**Comment by bimalkjha** [comment]
@DarekDan Please check about "Restrictions on untyped parameter marker usage" [here](https://www.ibm.com/support/knowledgecenter/es/SSEPGG_11.1.0/com.ibm.db2.luw.apdv.sqlpl.doc/doc/c0020295.html).
The syntax of SQL "SELECT ? FROM SYSIBM.SYSDUMMY1" where value will be provided as bind parameter is not supported by IBM DB2 ODBC and CLI Driver. I'll check how it works in Java with jdbc driver development team but such sql is not supported by any non-java driver supported by IBM.
Just save below lines in a cli.txt file:
```
opt echo on
opt calldiag on
quickc 1 1 sample
sqlallocstmt 1 1
sqlprepare 1 "select ? from sysibm.sysdummy1" -3
getmem 1 1 SQL_C_LONG
updatemem 1 SQL_C_LONG VALUE 11 
sqlbindparameter 1 1 SQL_PARAM_INPUT SQL_C_LONG SQL_INTEGER 0 0 1
sqlexecute 1
sqltransact 1 1 sql_rollback
sqlfreestmt 1 sql_drop
killenv 1
```
and execute it from any db2 server system using "db2cli < cli.txt" command. It'll return the same error. 
Note that the error returned by ibm_db driver is from db2 server and not from the driver itself. If query is not supported by server, server will return error to ibm_db and same error is returned by ibm_db to the application. Thanks.

**Comment by bimalkjha** [comment]
@DarekDan I checked with JDBC driver development about it. They too confirmed about same error: com.ibm.db2.jcc.am.SqlSyntaxErrorException: DB2 SQL Error: SQLCODE=-418, SQLSTATE=42610, SQLERRMC=unresolved untyped expression, DRIVER=4.26.4
They mentioned that its an usage issue. They have used below code:
```
PreparedStatement pstmt = con.prepareStatement("select ? FROM SYSIBM.SYSDUMMY1");
	pstmt.setString(1, "a");
	ResultSet rs = pstmt.executeQuery();
	while(rs.next()){
	System.out.println(rs.getString(1));
	}
```
If it is working for you using JCC driver, please share the test program so that we can see how it is working. If your query is different, please share the program with that query. If some query is working using JCC driver against Db2 server, it should work using other drivers too. Thanks.

**Comment by DarekDan** [comment]
How about the second example? Is that unsupported too?

UPDATE LA
SET AU        = CASE WHEN AU = ? THEN CAST(? AS CHAR(36)) ELSE CAST(? AS CHAR(36)) END,
    UPDATE_TS = CURRENT_TIMESTAMP
WHERE AU IN (?, ?);

Without CAST you will get the exact same error.

**Comment by bimalkjha** [comment]
@DarekDan Please share the create table statement and one insert statement too, so that I can verify using a test program. Thanks.

**Comment by bimalkjha** [comment]
Closing the issue as not received any response in past 20 days. Thanks.
