### ISSUE TITLE
Error: The specified module could not be found. \node_modules\ibm_db\build\Release\odbc_bindings.node

### ISSUE THREAD

**Issue by Owenzh** [ibmdb/node-ibm_db#617]
Background:
OS: Windonws 10 64bit
Nodejs: v10.14.0
NPM: v6.4.1
Before build app, I install gyp and windows-build-tools:
```
npm install -g node-gyp
npm --vs2015 install --global --production windows-build-tools
```
And then check: npm config list: 
```
msvs_version = "2015"
node = "bin"
production = false
python = "2.7"

```
Go to app root directory:  build and  run app successfully. 
But when visit pages, throw the error:
`Error: The specified module could not be found.\\?\C:\.......\node_modules\ibm_db\build\Release\odbc_bindings.node at Object.Module._extensions..node (internal/modules/cjs/loader.js:717:18)`

I also check the locate this file , it exists already.
it is so weird, Could you anyone help me? 

Thanks.

**Comment by bimalkjha** [comment]
@Owenzh Now, edit file `...\node_modules\ibm_db\test\config.testConnectionStrings.json` and update database connection information. Then execute below commands and share the complete output:
```
cd node_modules\ibm_db
npm install
node test\test-basic-test.js
```
Thanks.

**Comment by Owenzh** [comment]
As your suggestion, I run the node test\test-basic-test.js

`>\node_modules\ibm_db\node_modules\bindings\bindings.js:121
        throw e;
        ^

Error: The specified module could not be found.
\\?....\node_modules\ibm_db\build\Release\odbc_bindings.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:717:18)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at bindings (C:...\node_modules\ibm_db\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (C:..\node_modules\ibm_db\lib\odbc.js:31:31)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)`

Still have this issue.

**Comment by bimalkjha** [comment]
@Owenzh Please share output of `cd node_modules\ibm_db; npm install` too. We need complete output of `npm install` command. Thanks.

**Comment by Owenzh** [comment]
C:\APP\node_modules\ibm_db>node -v
v10.14.0

C:\APP\node_modules\ibm_db>npm -v
6.4.1

C:\APP\node_modules\ibm_db>npm install

> ibm_db@2.6.4 install C:\APP\node_modules\ibm_db
> node installer/driverInstall.js

platform =  win32 , arch =  x64 , node.js version =  v10.14.0
IBM_DB_HOME environment variable have already been set to -> C:\ntx64_odbc_cli\clidriver

Downloading of clidriver skipped - build is in progress...


C:\APP\node_modules\ibm_db>if not defined npm_config_node_gyp (node "C:\Users\xudongz\AppData\Roaming\nvm\v10.14.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure build  --IS_DOWNLOADED=false --IBM_DB_HOME=$IBM_DB_HOME )  else (node "C:\Users\xudongz\AppData\Roaming\nvm\v10.14.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" configure build  --IS_DOWNLOADED=false --IBM_DB_HOME=$IBM_DB_HOME )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  odbc.cpp
  odbc_connection.cpp
  odbc_statement.cpp
  odbc_result.cpp
c:\APP\node_modules\ibm_db\src\odbc_statement.cpp(243): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\APP\node_modules\ibm_db\build\odbc_bindings.vcxproj]
  c:\APP\node_modules\ibm_db\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'c:\APP\node_modules\ibm_db\src\odbc.cpp(215): warning C4996: 'Nan::Callback::Call': was declared deprecated
  c:\APP\node_modules\ibm_db\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
c:\APP\node_modules\ibm_db\src\odbc.cpp(227): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\APP\node_modules\ibm_db\build\odbc_bindings.vcxproj]
  c:\APP\node_modules\ibm_db\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'

c:\APP\node_modules\ibm_db\src\odbc_statement.cpp(419): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\APP\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\APP\node_modules\ibm_db\src\odbc.cpp(690): warning C4311: 'type cast': pointer truncation from 'SQLHSTMT' to 'long'c:\APP\node_modules\ibm_db\node_modules\nan\nan.h(1718): note: see declaration of 'Nan::Callback::Call' [C:\APP\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\APP\node_modules\ibm_db\src\odbc.cpp(690): warning C4302: 'type cast': truncation from 'SQLHSTMT' to 'long' [C:\APP\node_modules\ibm_db\build\odbc_bindings.vcxproj]

c:\APP\node_modules\ibm_db\src\odbc.cpp(691): warning C4311: 'type cast': pointer truncation from 'SQLHSTMT' to 'long' [C:\APP\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\APP\node_modules\ibm_db\src\odbc.cpp(691): warning C4302: 'type cast': truncation from 'SQLHSTMT' to 'long' [C:\APP\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\APP\node_modules\ibm_db\src\odbc_statement.cpp(570): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\APP\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\APP\node_modules\ibm_db\src\odbc.cpp(1237): warning C4996: 'Nan::Callback::Call': was declared deprecatedc:\APP\node_modules\ibm_db\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call' [C:\APP\node_modules\ibm_db\build\odbc_bindings.vcxproj]

c:\APP\node_modules\ibm_db\src\odbc_result.cpp(287): warning C4996: 'Nan::Callback::Call': was declared deprecatedc:\APP\node_modules\ibm_db\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call' [C:\APP\node_modules\ibm_db\build\odbc_bindings.vcxproj]

  c:\APP\node_modules\ibm_db\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'c:\APP\node_modules\ibm_db\src\odbc_statement.cpp(775): warning C4996: 'Nan::Callback::Call': was declared deprecated

  c:\APP\node_modules\ibm_db\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
c:\APP\node_modules\ibm_db\src\odbc_result.cpp(312): warning C4996: 'Nan::Callback::Call': was declared deprecatedc:\APP\node_modules\ibm_db\src\odbc_statement.cpp(946): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\APP\node_modules\ibm_db\build\odbc_bindings.vcxproj]
  c:\APP\node_modules\ibm_db\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'

  c:\APP\node_modules\ibm_db\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
c:\APP\node_modules\ibm_db\src\odbc_statement.cpp(1066): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\APP\node_modules\ibm_db\build\odbc_bindings.vcxproj]
  c:\APP\node_modules\ibm_db\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
c:\APP\node_modules\ibm_db\src\odbc_result.cpp(598): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\APP\node_modules\ibm_db\build\odbc_bindings.vcxproj]
  c:\APP\node_modules\ibm_db\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
c:\APP\node_modules\ibm_db\src\odbc_connection.cpp(305): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\APP\node_modules\ibm_db\build\odbc_bindings.vcxproj]
  c:\APP\node_modules\ibm_db\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
c:\APP\node_modules\ibm_db\src\odbc_connection.cpp(529): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\APP\node_modules\ibm_db\build\odbc_bindings.vcxproj]
  c:\APP\node_modules\ibm_db\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
c:\APP\node_modules\ibm_db\src\odbc_connection.cpp(904): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\APP\node_modules\ibm_db\build\odbc_bindings.vcxproj]
  c:\APP\node_modules\ibm_db\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
c:\APP\node_modules\ibm_db\src\odbc_connection.cpp(1129): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\APP\node_modules\ibm_db\build\odbc_bindings.vcxproj]
  c:\APP\node_modules\ibm_db\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
c:\APP\node_modules\ibm_db\src\odbc_connection.cpp(1159): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\APP\node_modules\ibm_db\build\odbc_bindings.vcxproj]
  c:\APP\node_modules\ibm_db\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
c:\APP\node_modules\ibm_db\src\odbc_connection.cpp(1679): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\APP\node_modules\ibm_db\build\odbc_bindings.vcxproj]
  c:\APP\node_modules\ibm_db\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
c:\APP\node_modules\ibm_db\src\odbc_connection.cpp(1861): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\APP\node_modules\ibm_db\build\odbc_bindings.vcxproj]
  c:\APP\node_modules\ibm_db\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
  win_delay_load_hook.cc
  strptime.c
     Creating library C:\APP\node_modules\ibm_db\build\Release\odbc_bindings.lib and object C:\APP\node_modules\ibm_db\build\Release\odbc_bindings.exp
  Generating code
  All 537 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Finished generating code
  odbc_bindings.vcxproj -> C:\APP\node_modules\ibm_db\build\Release\\odbc_bindings.node


Kernel additional dependencies removed successfully!

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  odbc.cpp
  odbc_connection.cpp
  odbc_statement.cpp
  odbc_result.cpp
c:\APP\node_modules\ibm_db\src\odbc_statement.cpp(243): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\APP\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\APP\node_modules\ibm_db\src\odbc_connection.cpp(305): warning C4996: 'Nan::Callback::Call': was declared deprecatedc:\APP\node_modules\ibm_db\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call' [C:\APP\node_modules\ibm_db\build\odbc_bindings.vcxproj]

  c:\APP\node_modules\ibm_db\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'c:\APP\node_modules\ibm_db\src\odbc_statement.cpp(419): warning C4996: 'Nan::Callback::Call': was declared deprecated

c:\APP\node_modules\ibm_db\src\odbc_connection.cpp(529): warning C4996: 'Nan::Callback::Call': was declared deprecatedc:\APP\node_modules\ibm_db\node_modules\nan\nan.h(1718): note: see declaration of 'Nan::Callback::Call' [C:\APP\node_modules\ibm_db\build\odbc_bindings.vcxproj]

  c:\APP\node_modules\ibm_db\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
c:\APP\node_modules\ibm_db\src\odbc_statement.cpp(570): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\APP\node_modules\ibm_db\build\odbc_bindings.vcxproj]
  c:\APP\node_modules\ibm_db\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
c:\APP\node_modules\ibm_db\src\odbc_connection.cpp(904): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\APP\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\APP\node_modules\ibm_db\src\odbc_result.cpp(287): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\APP\node_modules\ibm_db\build\odbc_bindings.vcxproj]
  c:\APP\node_modules\ibm_db\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'c:\APP\node_modules\ibm_db\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'

c:\APP\node_modules\ibm_db\src\odbc_result.cpp(312): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\APP\node_modules\ibm_db\build\odbc_bindings.vcxproj]
  c:\APP\node_modules\ibm_db\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
c:\APP\node_modules\ibm_db\src\odbc_statement.cpp(775): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\APP\node_modules\ibm_db\build\odbc_bindings.vcxproj]
  c:\APP\node_modules\ibm_db\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
c:\APP\node_modules\ibm_db\src\odbc_statement.cpp(946): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\APP\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\APP\node_modules\ibm_db\src\odbc_connection.cpp(1129): warning C4996: 'Nan::Callback::Call': was declared deprecatedc:\APP\node_modules\ibm_db\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call' [C:\APP\node_modules\ibm_db\build\odbc_bindings.vcxproj]

  c:\APP\node_modules\ibm_db\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
c:\APP\node_modules\ibm_db\src\odbc_result.cpp(598): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\APP\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\APP\node_modules\ibm_db\src\odbc_connection.cpp(1159): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\APP\node_modules\ibm_db\build\odbc_bindings.vcxproj]
  c:\APP\node_modules\ibm_db\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'c:\APP\node_modules\ibm_db\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'

c:\APP\node_modules\ibm_db\src\odbc_statement.cpp(1066): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\APP\node_modules\ibm_db\build\odbc_bindings.vcxproj]
  c:\APP\node_modules\ibm_db\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
c:\APP\node_modules\ibm_db\src\odbc_connection.cpp(1679): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\APP\node_modules\ibm_db\build\odbc_bindings.vcxproj]
  c:\APP\node_modules\ibm_db\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
c:\APP\node_modules\ibm_db\src\odbc_connection.cpp(1861): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\APP\node_modules\ibm_db\build\odbc_bindings.vcxproj]
  c:\APP\node_modules\ibm_db\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
c:\APP\node_modules\ibm_db\src\odbc.cpp(215): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\APP\node_modules\ibm_db\build\odbc_bindings.vcxproj]
  c:\APP\node_modules\ibm_db\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
c:\APP\node_modules\ibm_db\src\odbc.cpp(227): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\APP\node_modules\ibm_db\build\odbc_bindings.vcxproj]
  c:\APP\node_modules\ibm_db\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
c:\APP\node_modules\ibm_db\src\odbc.cpp(690): warning C4311: 'type cast': pointer truncation from 'SQLHSTMT' to 'long' [C:\APP\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\APP\node_modules\ibm_db\src\odbc.cpp(690): warning C4302: 'type cast': truncation from 'SQLHSTMT' to 'long' [C:\APP\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\APP\node_modules\ibm_db\src\odbc.cpp(691): warning C4311: 'type cast': pointer truncation from 'SQLHSTMT' to 'long' [C:\APP\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\APP\node_modules\ibm_db\src\odbc.cpp(691): warning C4302: 'type cast': truncation from 'SQLHSTMT' to 'long' [C:\APP\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\APP\node_modules\ibm_db\src\odbc.cpp(1237): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\APP\node_modules\ibm_db\build\odbc_bindings.vcxproj]
  c:\APP\node_modules\ibm_db\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
  win_delay_load_hook.cc
  strptime.c
     Creating library C:\APP\node_modules\ibm_db\build\Release\odbc_bindings.lib and object C:\APP\node_modules\ibm_db\build\Release\odbc_bindings.exp
  Generating code
  All 537 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Finished generating code
  odbc_bindings.vcxproj -> C:\APP\node_modules\ibm_db\build\Release\\odbc_bindings.node


node-ibm_db installed successfully!

audited 187 packages in 39.731s
found 0 vulnerabilities


C:\APP\node_modules\ibm_db>

**Comment by bimalkjha** [comment]
@Owenzh Since you have set IBM_DB_HOME to C:\ntx64_odbc_cli\clidriver, you need to set PATH and LIB environment variables too. Please set below environment variables and then try:
```
set PATH=C:\ntx64_odbc_cli\clidriver\bin;C:\ntx64_odbc_cli\clidriver\lib;%PATH%
set LIB=C:\ntx64_odbc_cli\clidriver\bin;C:\ntx64_odbc_cli\clidriver\lib;%LIB%
```
Thanks.

**Comment by Owenzh** [comment]
Set PATH and LIB env var, it seems working. 
`C:\ntx64_odbc_cli\clidriver\bin;C:\ntx64_odbc_cli\clidriver\lib;`

Thank you very much, Close it for now.
