### ISSUE TITLE
passing decimal value of length 11 to stored procedure throws exception

### ISSUE THREAD

**Issue by isajja1** [ibmdb/node-ibm_db#618]
I am trying to call a DB2 stored procedure which accepts input parameter of decimal (11,0). I defined the parameter as below:
const DECIMAL = 3;
 const param1 =
    {ParamType:"INPUT", SQLType: DECIMAL ,  DataType: "INTEGER", Data: parseInt(data.stockNumber), Length: 11};
I am getting Numeric value out of range. SQLSTATE=22003.
I also tried to pass CType:"CHAR" but still am not able to call successfully.
Any help is highly appreciated.

**Comment by bimalkjha** [comment]
@isajja1 Please update code as below:
```
const DECIMAL = 3;
const param1 =
{ParamType:"INPUT", CType: 8 , DataType: DECIMAL, Data: parseInt(data.stockNumber), Length: 11};
```
Thanks.

**Comment by isajja1** [comment]
Thank you. Tried that still seeing [IBM][CLI Driver] CLI0111E Numeric value out of range. SQLSTATE=22003.
I tried DataType: 1 I am able to call the stored procedure.

**Comment by lakhanpalv** [comment]
Hi Bimal, how do you pass a precision value in the above param object you asked to try? Say if I have a Decimal value (15,2)? I am getting some issues when I tried different combinations, listed here: https://github.com/ibmdb/node-ibm_db/issues/636

**Comment by bimalkjha** [comment]
@lakhanpalv ibm_db internally calculates precision and scale of the decimal number based on the decimal value passed in params. ibm_db uses this scale to bind the data using SQLBindParameter() ODBC API. Thanks.

**Comment by bimalkjha** [comment]
Closing it as issue 636 is closed. You can still add comment here if required. Thanks.
