### ISSUE TITLE
Unable to connect because of license

### ISSUE THREAD

**Issue by sravannerella** [ibmdb/node-ibm_db#621]
Hello,

I'm trying to connect to my Db2 instance deployed on IBM iSeries with my node application. But I'm running into the following error. I'm not sure where can I find this license, could you point me in the right direction? Or show me a workaround to connect to the DB for development at least?

```js
{ [Error: [IBM][CLI Driver] SQL1598N  An attempt to connect to the database server failed because of a licensing problem.  SQLSTATE=42968
]
 error: '[node-ibm_db] SQL_ERROR',
 sqlcode: -1598,
 message:
  '[IBM][CLI Driver] SQL1598N  An attempt to connect to the database server failed because of a licensing problem.  SQLSTATE=42968\r\n',
 state: '42968' }
```
Here is my source code:

```js
const db = require('ibm_db');

const cs = "DATABASE=xxxx;HOST=xxx.xxx.xxx.xxx;PORT=50000;UID=db2inst1;PWD=testdb;PROTOCOL=TCPIP;";

db.open(cs, (err, db) => {
    if(err) return console.error(err);
    console.log("CONNECTED", db);
});
```
Could you please help me in fixing this error.

**Quick update:** I was able to connect using JDBC connection but running into licensing issue with this.

**Comment by bimalkjha** [comment]
@sravannerella Please read this [documentation](https://github.com/ibmdb/node-ibm_db#for-zos-and-iseries-connectivity). You need to ask your iSeries DBA to activate the server for db2connect. If server is configured to be connected by remote db2connect clients, you need not to apply client side license, else you need a client side db2connect license to talk to iSeries server. Please talk to your DBA about it and update us. Then we can see how can we help you. Thanks.

**Comment by hvpulok** [comment]
Hi @bimalkjha,
We are also getting this license error. this is our db2 license info
<img width="963" alt="image" src="https://user-images.githubusercontent.com/19298777/182946480-236646e6-dbdb-49e6-b111-eb25ec996ad7.png">
May I know how to resolve this issue?

**Comment by bimalkjha** [comment]
@hvpulok Check this documentation: https://github.com/ibmdb/node-ibm_db#sql1598n
All information is there.

From your result, it seems you have installed 32bit Db2 Server version 10.5. Db2 V10.5 is very old and out of support. Also, ibm_db do not support 32bit windows. You should install ibm_db on a 64bit windows machine where it will get installed with latest db2connect odbc driver and you need to get a Db2 Version 11.5 db2connect license from IBM. Let me know what you think and open a new issue for further assistance. Thanks.

**Comment by hvpulok** [comment]
@bimalkjha Thank you for your prompt response. I think I need to give you more context for better answer:
- Our DB2 Server version: DSN12015, which means I assume 12.x
- DB2 server runs on Zos and it's already in prod serving millions of customers. Our most of the API services are written in JAVA and they are communicating with DB2 without any problem.
- We are now trying to create a Node.js service which will communicate with that DB2 v12 in Zos. And we are getting `SQL1598N ` license error.
- The earlier screen shot I gave from a windows **client** machine  and all the info was related to that client. However I installed the DB2 connect latest 11.5 version.
You mentioned we need db2connect license from IBM, since our JAVA APIs are already working, why we need another license?

**Comment by bimalkjha** [comment]
@hvpulok The db2connect license file for Java and non-Java applications are different. The db2connect license file for Java application is a .jar file but for non-java applications, name of db2connect license file is db2con*.lic that should be copied under `ibm_db/installer/clidriver/license` directory.
So, if your Java application is already working, means you have the db2connect license. Just contact your admin and tell to share the db2consv*.lic file which is required for ibm_db.
The SQL1598N error comes if you install ibm_db on a distributed system like Windows, Linux, Unix or Mac. If you install ibm_db locally on z/OS system where you already have Db2 server installed, then there are different steps to follow to install ibm_db on z/OS system and such installation does not require db2connect license as you have Db2 server available locally. You need to follow these instructions to install ibm_db on z/OS system: https://github.com/ibmdb/node-ibm_db#configure-odbc-driver-on-zos

Again, db2connect license is required only if Db2 for z/OS server is on remote system. If server is available locally, then no db2connect license required and there is different installation steps. We need to set a system environment variable IBM_DB_HOME pointing to the install directory of Db2 Server before installation of ibm_db. Thanks.

**Comment by hvpulok** [comment]
@bimalkjha Thank you very much. The issue has been resolved after putting the license file in the suggested `ibm_db/installer/clidriver/license` folder.
