### ISSUE TITLE
Invalid connection handle

### ISSUE THREAD

**Issue by xerxessie** [ibmdb/node-ibm_db#622]
Please Help Thank you.
{ "DRIVER" : "{DB2 ODBC Driver}",
  "DATABASE" : "xxx",
  "UID" : "xxxx",
  "PWD" : "xxxx",
  "HOSTNAME" : "xxxx",
  "PORT" : xxxx,
  "PROTOCOL" : "TCPIP" 
self.odbc = (options.odbc) ? options.odbc : ((ENV) ? ENV : new odbc.ODBC());     
                                                             ^
Error: CLI0600E Invalid connection handle or connection is closed. SQLSTATE=S1000
    at new Database (C:\Users\xxx\Desktop\trade-finance-api\node_modules\ibm_db\lib\odbc.js:265:62)
    at DBFactory (C:\Users\xxx\Desktop\trade-finance-api\node_modules\ibm_db\lib\odbc.js:78:12)
    at Function.module.exports.open (C:\Users\xxx\Desktop\trade-finance-api\node_modules\ibm_db\lib\odbc.js:108:8)
    at Object.<anonymous> (C:\Users\xxx\Desktop\trade-finance-api\node_modules\ibm_db\test\test-basic-test.js:8:7)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)       
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)

**Comment by bimalkjha** [comment]
@xerxessie Please share the version of node.js, ibm_db and Operating System name. Also, share the complete output of `npm install ibm_db` command. Thanks.

**Comment by xerxessie** [comment]
@bimalkjha Thanks for the reply.
node v10.16.3
"ibm_db": "^2.6.4"
Windows 10 Home 64bit

100.00% | 23445646 bytes downloaded out of 23445646 bytes.cated, see https://github.com/request/request/issues/3142

****************************************\trade-finance-api\node_modules\ibm_db
You are downloading a package which includes the Node.js module for IBM DB2/Informix.  The module is licensed under the Apache License 2.0. The package also includes IBM ODBC and CLI Driver from IBM, which is automatically downloaded as the node module is installed on your system/device. The license agreement to the IBM ODBC and CLI Driver is available in undefined   Check for additional dependencies, which may come with their own license agreement(s). Your use of the components of the package and dependencies constitutes your acceptance of their respective license agreements. If you do not accept the terms of any license agreement(s), then delete the relevant component(s) from your device.
****************************************

Downloading and extraction of DB2 ODBC CLI Driver completed successfully...


C:\Users\xxx\Desktop\trade-finance-api\node_modules\ibm_db>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure build  --IS_DOWNLOADED=true --IBM_DB_HOME=$IBM_DB_HOME )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" configure build  --IS_DOWNLOADED=true --IBM_DB_HOME=$IBM_DB_HOME )

{ Error: Command failed: node-gyp configure build  --IS_DOWNLOADED=true --IBM_DB_HOME=$IBM_DB_HOME
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Program Files\MySQL\MySQL Workbench 6.3 CE\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack ImportError: No module named site
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "build" "--IS_DOWNLOADED=true" "--IBM_DB_HOME=$IBM_DB_HOME"
gyp ERR! cwd C:\Users\xxx\Desktop\trade-finance-api\node_modules\ibm_db
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   'node-gyp configure build  --IS_DOWNLOADED=true --IBM_DB_HOME=$IBM_DB_HOME' }

node-gyp build process failed!

Proceeding with Pre-compiled Binary Installation.


===================================
node-ibm_db installed successfully!
===================================

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ ibm_db@2.6.4
updated 1 package and audited 1677 packages in 141.205s
found 10 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by xerxessie** [comment]
I found the issue , when I used the IBM DB2 SERVER version 11.1 has error, but when i used db2 server  version10.5 connection has no error.

**Comment by bimalkjha** [comment]
@xerxessie The error seems due to conflict of libraries. Actually ibm_db comes with its own odbc driver  and binaries are generated using that. If you have a preinstalled db2 client or server in the system, at runtime the installed libraries get priority. So, the pre-compiled node binary had conflict with existing libraries of server/client installed.

It can work with version 11.1 server too if you run below commands on windows command prompt:
```
npm install ibm_db
set PATH=C:\Users\xxx\Desktop\trade-finance-api\node_modules\ibm_db\installer\clidriver\bin;C:\Users\xxx\Desktop\trade-finance-api\node_modules\ibm_db\installer\clidriver\lib;%PATH%
set LIB=C:\Users\xxx\Desktop\trade-finance-api\node_modules\ibm_db\installer\clidriver\bin;C:\Users\xxx\Desktop\trade-finance-api\node_modules\ibm_db\installer\clidriver\lib;%LIB%
node test\test-basic-test.js
```
Thanks.

**Comment by xerxessie** [comment]
@bimalkjha thanks.

**Comment by itdxsd** [comment]
@bimaljha hello again. 
![image](https://user-images.githubusercontent.com/23701488/85243985-ef77ca80-b475-11ea-8c8c-dcaf28e05c79.png)


> @xerxessie The error seems due to conflict of libraries. Actually ibm_db comes with its own odbc driver and binaries are generated using that. If you have a preinstalled db2 client or server in the system, at runtime the installed libraries get priority. So, the pre-compiled node binary had conflict with existing libraries of server/client installed.
> 
> It can work with version 11.1 server too if you run below commands on windows command prompt:
> 
> ```
> npm install ibm_db
> set PATH=C:\Users\xxx\Desktop\trade-finance-api\node_modules\ibm_db\installer\clidriver\bin;C:\Users\xxx\Desktop\trade-finance-api\node_modules\ibm_db\installer\clidriver\lib;%PATH%
> set LIB=C:\Users\xxx\Desktop\trade-finance-api\node_modules\ibm_db\installer\clidriver\bin;C:\Users\xxx\Desktop\trade-finance-api\node_modules\ibm_db\installer\clidriver\lib;%LIB%
> node test\test-basic-test.js
> ```
> 
> Thanks.

![image](https://user-images.githubusercontent.com/23701488/85244002-fbfc2300-b475-11ea-9c41-1bb91a76c8ed.png)

hello i updated db2 server to 11.5 version. 
 "ibm_db": "^2.7.0"
Thanks.

**Comment by itdxsd** [comment]
@bimalkjha  . Its ok now, due to conflict driver  solve this by reinstalling npm ibm_db. thanks
