### ISSUE TITLE
Requesting the PKG-INFO file at the root.  

### ISSUE THREAD

**Issue by KevinLawhon** [ibmdb/node-ibm_db#624]

**Comment by bimalkjha** [comment]
@KevinLawhon Please share more info like how this pkg-info file should looks and what information you are expecting in it. We already have package.json at root which comes with all npm packages. Thanks.

**Comment by KevinLawhon** [comment]
This might be the wrong repo, not sure.  We are installing ibm-db for python using pip.  However, we are not downloading from Pypi, but instead are using artifactory.  The PKG-INFO.txt file is not present at the root, but under the .egg directory.  This is causing an issue where artificatory is not able to download from pip as it is looking for the PKG-INFO. txt file at the root.  Is this the right git, or should I be on another?

**Comment by bimalkjha** [comment]
@KevinLawhon Yes, its wrong repo. This repo is only for node.js ibm_db driver issues. Please open and issue here: https://github.com/ibmdb/python-ibmdb/issues for python driver. Thanks.
