### ISSUE TITLE
Error pip install ibm_db

### ISSUE THREAD

**Issue by thangalan** [ibmdb/node-ibm_db#626]

**Comment by thangalan** [comment]
Using pip install i get lots of errors:

![image](https://user-images.githubusercontent.com/62855110/77860177-9542d280-71c2-11ea-885f-266fcec252fd.png)

**Comment by bimalkjha** [comment]
@thangalan This is repo is for node.js driver, not for python driver. For python driver, please open an issue here: https://github.com/ibmdb/python-ibmdb/issues/new
