### ISSUE TITLE
Throw SQL0437W warning when use 2.6.4, the 2.3.1 is good

### ISSUE THREAD

**Issue by owen-rpx** [ibmdb/node-ibm_db#627]
[IBM][CLI Driver][DB2/LINUXX8664] SQL0437W Performance of this complex query might be sub-optimal. Reason code: "2". SQLSTATE=01602

How to avoid it from codes level?

Thanks

**Comment by bimalkjha** [comment]
@Owenzh Could you please share any small test program that can reproduce this error? It'll help in investigation and finding a solution. Thanks.

**Comment by bimalkjha** [comment]
@Owenzh Till version 2.3.1, ibm_db was ignoring the warnings and returning only errors. But, Robert Penny <rpenny@rocketsoftware.com>; Jeff Long <jlong@rocketsoftware.com>
Fabian Illanes <fillanes@rocketsoftware.com>; Colin Maxfield <CMaxfield@rocketsoftware.com>; Shilu Mathai <SMathai@rocketsoftware.com>; Jason Johnson <jjohnson@rocketsoftware.com>; Tim Willging <twillging@rocketsoftware.com>; Kimberly Andersson <kandersson@rocketsoftware.com>, etc has requested to change this behavior for NEWTON to solve the JIRA issue https://jira.rocketsoftware.com/browse/NDOE-1412. The code change was delivered as [this](https://github.com/ibmdb/node-ibm_db/commit/d9209d1f1101bc112a1e7aeb47d81a4c05c1292a) commit.
One option is you can update code to have check for sqlcode 437 and ignore it. Thanks.

**Comment by Owenzh** [comment]
Can you tell me which option to use or give example? 
Thx

**Comment by bimalkjha** [comment]
@owen-rpx You can check for sqlca.sqlcode > 0. For warning, sqlcode is positive and for error, its -ve. You can get sqlca as documented [here](https://github.com/ibmdb/node-ibm_db/blob/master/APIDocumentation.md#-3-querysqlquery--bindingparameters-callback). Also, you can see it in https://github.com/ibmdb/node-ibm_db/blob/master/test/test-basic-test.js, just search for sqlca. Thanks.

**Comment by bimalkjha** [comment]
@owen-rpx Is it working for you now? May I close the issue? Thanks.

**Comment by owen-rpx** [comment]
yes, I will try to solve it, thanks.

**Comment by owen-rpx** [comment]
conn.query(query, bindings || [], (err: Error, data: any[], sqlca) => {
          console.log('sqlca===>', sqlca);
          if (err) { return reject(err); }
          ret = ret.concat(data);
          logger.debug('--IBMDB--query()--ret='+util.inspect(ret, { depth: null }));

          return resolve(ret);
        });

log::==>
sqlca===> { state: '01602', sqlcode: 437 }

It still throw error==>
 :: "Error: [IBM][CLI Driver][DB2/LINUXX8664] SQL0437W  Performance of this complex query might be sub-optimal.  Reason code: \"2\".  SQLSTATE=01602\r\n"

**Comment by bimalkjha** [comment]
@owen-rpx In application code, just this check:
if(sqlca.sqlcode > 0) err = null;

If your expectation is in case of sqlcode=437, ibm_db should return some data and current version of ibm_db is unable to return data, then I have look into code and modify it.

You can also pass [IgnoreWarnings=1](https://www.ibm.com/support/knowledgecenter/SSEPGG_11.5.0/com.ibm.db2.luw.apdv.cli.doc/doc/r0008796.html) in database connection string to see the warnings get suppressed or not. If you do not see any effect, then pass [IgnoreWarnList="'01605','01602'"](https://www.ibm.com/support/knowledgecenter/SSEPGG_11.5.0/com.ibm.db2.luw.apdv.cli.doc/doc/r0008797.html) in connection string. Let me know result of your trials, then I can investigate further. Thanks.

**Comment by owen-rpx** [comment]
Set **IgnoreWarnings=1** into connect string, it works well now.

BTW, if(sqlca.sqlcode > 0) err = null; not working since db query return empty array.

Close it. Thanks.
