### ISSUE TITLE
Calling a stored procedure is giving SQL30020N communication data stream error

### ISSUE THREAD

**Issue by isajja1** [ibmdb/node-ibm_db#628]
Calling a stored procedure 
"CALL SP0123(9995573, 1200316, 99910234, 92459319780,  'AQP')"
is returning an error as below. How can we fix the error?
Error: [IBM][CLI Driver] SQL30020N Execution of the command or SQL statement failed because of a syntax error in the communication data stream that will affect the successful execution of subsequent commands and SQL statements: Reason Code \"0x124C\"(\"0114\")\"\". SQLSTATE=58009\r\n"
The same stored procedure works fine when called from C#.

**Comment by bimalkjha** [comment]
@isajja1 Can we get the definition of SP SP0123 or any small node.js test program to reproduce it?
