### ISSUE TITLE
db2 encoding

### ISSUE THREAD

**Issue by yo34** [ibmdb/node-ibm_db#629]
I opened an issue about db2 encoding #548, I did not get the correct way to have the french encoding. 

My database was created with "USING CODESET ISO-8859-15 TERRITORY FR".
Locales on db2 instance are :

_LANG=fr_FR@euro
LANGUAGE=fr_FR
LC_CTYPE="fr_FR@euro"
LC_NUMERIC="fr_FR@euro"
LC_TIME="fr_FR@euro"
LC_COLLATE="fr_FR@euro"
LC_MONETARY="fr_FR@euro"
LC_MESSAGES="fr_FR@euro"
LC_PAPER="fr_FR@euro"
LC_NAME="fr_FR@euro"
LC_ADDRESS="fr_FR@euro"
LC_TELEPHONE="fr_FR@euro"
LC_MEASUREMENT="fr_FR@euro"
LC_IDENTIFICATION="fr_FR@euro"
LC_ALL=fr_FR@euro_

Same locale on the client on nodejs.

When using openSync function ,I set the option {codeSet: 'ISO-8859-15'} but when I query the database I get strange character like "R�sultat"

**Comment by bimalkjha** [comment]
@yo34 If you are using terminal then you can set the environment variable using `export DB2CODEPAGE=923` and then run your application. Alternatively, you can set it in your application using `process.env.DB2CODEPAGE = 923;` before calling ibmdb.open() API. Thanks.

**Comment by yo34** [comment]
@bimalkjha , I am already using this environment variable. I already do both ( in the terminal and the application using process.env).

What do the codeSet option of querySync ?

In java application I used to set charset  and territory in the uri of the jdbc, but you already told me the ibm_db2 module does nothing with this kind of properties.

**Comment by bimalkjha** [comment]
@yo34 Setting DB2CODEPAGE environment variable is similar to setting charset in java. {codeSet: 'ISO-8859-15'} is not a valid option for querySync() or query() API. If setting DB2CODEPAGE on client system do not help you, please set LANG=fr_FR@euro on ibm_db system or in application and then try.
Also, verify the data in the table using some other client too. Data might exist in table in the same byte format? Thanks.

**Comment by yo34** [comment]
Hi @bimalkjha 

Same when DB2CODEPAGE is set to 923 and LANG is set to fr_FR@euro, on the application where ibm_db is used.

I tried getting data from others clients (GUI and shell), all is OK.

I think there is some encoding missing when using this nodejs client. The ibm_db is running on Windows machine.

**Comment by bimalkjha** [comment]
@yo34 Please share some test program having create table, insert data and select data. Also, share the expected output and wrong output. Using your test program, I can investigate to see how to get the correct data. Thanks.
