### ISSUE TITLE
How do you set special registers with this module

### ISSUE THREAD

**Issue by afinegan** [ibmdb/node-ibm_db#630]
I am looking to setup these specialRegisters
"specialRegisters=CURRENT APPLICATION COMPATIBILITY=V11R1,CURRENT DEGREE=ANY"

Do you know how I can achieve this with this driver?

**Comment by bimalkjha** [comment]
@afinegan If you see any CLI/ODBC configuration keyword corresponding to an special register in db2 knowledge center [here](https://www.ibm.com/support/knowledgecenter/SSEPGG_11.1.0/com.ibm.db2.luw.apdv.cli.doc/doc/r0007964.html), you can pass it via connection string in ibmdb.open() api. Few keywords are only supported by db2dsdriver.cfg file and that should be set in db2dsdriver.cfg file only if it is documented in db2 v11.1 knowledge center. node-ibm_db supports db2cli.ini and db2dsdriver.cfg file both as documented in db2 knowledge center.

To set CURRENT APPLICATION COMPATIBILITY special register, you need to create a `.../ibm_db/installer/clidriver/cfg/db2dsdriver.cfg` file and specify special register as below:
```
	<specialregisters> 
		<parameter name="CURRENT APPLICATION COMPATIBILITY" value="V11R1"/>
	</specialregisters>
```
Please check this page for details: https://www.ibm.com/support/knowledgecenter/SSEPGG_11.1.0/com.ibm.db2.luw.qb.dbconn.doc/doc/c0061167.html
To make sure your db2dsdriver.cfg file is correct and special register is effective, you can validate the db2dsdriver.cfg file by using below commands:
```
cd .../ibm_db/installer/clidriver/bin
./db2cli validate -dsn <dsnname>
```

For "CURRENT DEGREE=ANY", you can add "DB2Degree=ANY" in the connection string passed to ibmdb.open() API. It is documented in detail [here](https://www.ibm.com/support/knowledgecenter/SSEPGG_11.1.0/com.ibm.db2.luw.apdv.cli.doc/doc/r0008783.html). 

If you face any issue, please search in db2 knowledge center and share you db2dsdriver.cfg file. We'll look into the issue. Thanks.
