### ISSUE TITLE
Issue with error:  Could not locate the bindings file when running tests on windows

### ISSUE THREAD

**Issue by berlinbrown** [ibmdb/node-ibm_db#631]
When I try to run the following command, 

/node_modules/ibm_db/test

And: 
 node run-tests.js

I get the following error:
Error: Could not locate the bindings file. Tried:
 ? C:\cygwin64\home\user\git-main2\mongodbibm-nestjs-starter\app\node_modules\ibm_db\build\odbc_bindings.node
 ? C:\cygwin64\home\user\git-main2\mongodbibm-nestjs-starter\app\node_modules\ibm_db\build\Debug\odbc_bindings.node
...
And a list of directories.

I have added the following setting and it appears in the node environment variables.
 IBM_DB_HOME: 'C:\\IBM\\SQLLIB\\ntx64_odbc_cli\\clidriver',

Is there anything else to try?

Versions: 
 ibm_db@2.6.4
node -v v10.16.3

I am running under an enterprise proxy, that might impact

**Comment by bimalkjha** [comment]
@berlinbrown Cd to ibm_db directory and execute `npm install` command. Please share the complete output of `npm install` command. After npm install, you can execute `node test\test-basic-test.js` and share the result. These outputs will help to understand the root cause. Thanks.

**Comment by berlinbrown** [comment]
I had to run with a proxy:

NODE_TLS_REJECT_UNAUTHORIZED=0 \
HTTP_PROXY="http://proxy.com:3128" \
HTTPS_PROXY="http://proxy.com:3128" \
npm install


> ibm_db@2.6.4 install C:\cygwin64\home\user\git-main2\mongodbibm-nestjs-starter\app\node_modules\ibm_db
> node installer/driverInstall.js

platform =  win32 , arch =  x64 , node.js version =  v10.16.3
IBM_DB_HOME environment variable have already been set to -> C:\IBM\SQLLIB\ntx64_odbc_cli\clidriver

Downloading of clidriver skipped - build is in progress...


C:\cygwin64\home\user\git-main2\mongodbibm-nestjs-starter\app\node_modules\ibm_db>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure build  --IS_DOWNLOADED=false --IBM_DB_HOME=$IBM_DB_HOME )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" configure build  --IS_DOWNLOADED=false --IBM_DB_HOME=$IBM_DB_HOME )

{ Error: Command failed: node-gyp configure build  --IS_DOWNLOADED=false --IBM_DB_HOME=$IBM_DB_HOME
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 500 status code downloading 64-bit node.lib
gyp ERR! stack     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\install.js:374:20)
gyp ERR! stack     at Request.emit (events.js:203:15)
gyp ERR! stack     at Request.onRequestResponse (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1066:10)
gyp ERR! stack     at ClientRequest.emit (events.js:198:13)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:442:20)
gyp ERR! stack     at TLSSocket.emit (events.js:198:13)
gyp ERR! stack     at addChunk (_stream_readable.js:288:12)
gyp ERR! stack     at readableAddChunk (_stream_readable.js:269:11)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "build" "--IS_DOWNLOADED=false" "--IBM_DB_HOME=$IBM_DB_HOME"
gyp ERR! cwd C:\cygwin64\home\user\git-main2\mongodbibm-nestjs-starter\app\node_modules\ibm_db
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   'node-gyp configure build  --IS_DOWNLOADED=false --IBM_DB_HOME=$IBM_DB_HOME' }

**Comment by bimalkjha** [comment]
@berlinbrown Ok. So its happening due to proxy configuration. Seems, node-gyp is unable to reach the network. Here the error:
```
{ Error: Command failed: { Error: Command failed: node-gyp configure build --IS_DOWNLOADED=false --IBM_DB_HOME=$IBM_DB_HOME
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 500 status code downloading 64-bit node.lib
gyp ERR! stack at Request. (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\install.js:374:20)
gyp ERR! stack at Request.emit (events.js:203:15)

gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 500 status code downloading 64-bit node.lib
gyp ERR! stack at Request. (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\install.js:374:20)
gyp ERR! stack at Request.emit (events.js:203:15)
```
You can try to cd to ibm-db and run command: `node-gyp configure build --IS_DOWNLOADED=false --IBM_DB_HOME=$IBM_DB_HOME --verbose`.  It looks `Error: 500 status code downloading 64-bit node.lib` is the main error. node-gyp is trying to download 64-bit node.lib from internet and it fails. Do not forget to add --verbose option with node-gyp. It will give url of node.lib or any other lib which fails to download. Based on the error, try to resolve or share the complete output of command `node-gyp configure build --IS_DOWNLOADED=false --IBM_DB_HOME=$IBM_DB_HOME --verbose` here. Thanks.

**Comment by berlinbrown** [comment]
You can close, looks like some internal issues.   I am assume there is no pure nodejs driver kind of like the java jdbc driver?

**Comment by bimalkjha** [comment]
@berlinbrown Yes, there is no pure node.js driver and it can not be available by IBM due to license issue for z/OS. Other users are free to develop.
Thanks for clarifying that it was internal issue. Yes, node-ibm_db and all other open source drivers by IBM uses IBM ODBC driver using native api calls to provide connectivity from server. Thanks.
