### ISSUE TITLE
ibm_db connection fail

### ISSUE THREAD

**Issue by betogm08** [ibmdb/node-ibm_db#632]
Hello! I have an application in node js using express, and I try to connect to a database using ibm_db. I have the carootcert.der file to put it in the connection string but when I run the app, it sends me this error:
'**[IBM][CLI Driver] SQL10013N  The specified library "GSKit Error: 93" could not be loaded.  SQLSTATE=42724\n**'

This is my connection string:
DATABASE=${base};HOSTNAME=${host};PORT=52000;PROTOCOL=TCPIP;UID=${user};PWD=${pass};Security=SSL;SSLServerCertificate=${tsl}

tsl variable stores the path to carootcert.der file. Can you help me?

**Comment by bimalkjha** [comment]
@betogm08 For TSL connection, in ibm_db documentation if we search for SSL [here](https://github.com/ibmdb/node-ibm_db/blob/master/APIDocumentation.md#-1-openconnectionstring-options-callback), we can see below instruction at end:
`Note: The SSL Certificate file must have .arm extention. Certificate file with .crt or any other extention would not work with SSLServerCertificate keyword. You need to create keystoredb using GSKit and add certificate of other extention to keystoredb to use as documented in DB2 Infocenter.`

So, you are getting this error due to use of .der file. can you get a carootcert.arm file? That should work fine.
We are working to provide support for other certificate types too like .cert and .der. But that will take some time. If you can get .arm, it is very simple, else there is some lengthy process that I can share. Thanks.

**Comment by betogm08** [comment]
Could you please share what is that process? I'm reding that I have to execute some GSKit commands to get the SSL certificate...

**Comment by bimalkjha** [comment]
@betogm08 Please download the GSKit from this link based on you platform: https://www.ibm.com/support/fixcentral/swg/selectFixes?parent=Security+Systems&product=ibm/Tivoli/IBM+Global+Security+Kit&release=All&platform=All&function=fixId&fixids=8.0.*&source=fc
After installing it, please follow the instructions documented [here](https://www.ibm.com/support/knowledgecenter/en/SSEPGG_11.1.0/com.ibm.db2.luw.admin.sec.doc/doc/t0053518.html). You need to create keydb and add your certificate to this keydb using below commands:
```
gsk8capicmd_64 -keydb -create -db "mydbclient.kdb" -pw "myClientPassw0rdpw0"  -stash
gsk8capicmd_64 -cert -add -db "mydbclient.kdb" -pw "myClientPassw0rdpw0" 
      -label "dbselfsigned" -file "carootcert.der" -format binary -fips
```
Please correct the -format value based on format of your .der file. I think it should be binary, but it may be different. Then you can extract certificate.arm file using below command:
`gsk8capicmd_64.exe -cert -extract -db mydbclient.kdb -pw myClientPassw0rdpw0 -label "dbselfsigned" -target "certificate.arm" -format ascii -fips`

If you do not want to use certificate.arm file as it is in ascii format, then you can directly specify the keydbname and stash file name in ibm_db connection string as below:
`"DATABASE=sample;UID=newton;PWD=passwd;HOSTNAME=myserver.xyz.com;PORT=448;Security=SSL;SSLClientKeystoredb=C:\Program Files\IBM\gsk8\bin\client.kdb;SSLClientKeystash=C:\Program Files\IBM\gsk8\bin\client.sth"`
Thanks.

**Comment by betogm08** [comment]
Can I run these commands in cmd? Or they must execute in a specific CLI?

**Comment by bimalkjha** [comment]
@betogm08 Yes you need to run these commands from windows command prompt only. Also, make sure that you post GSKit installation, C:\Program Files\ibm\gsk8\bin and C:\Program Files\ibm\gsk8\lib64 got added to system PATH and LIB environment variable. Else, you can "cd C:\Program Files\ibm\gsk8\bin" and then try. Thanks.

**Comment by betogm08** [comment]
Hi @bimalkjha thank you very much for your help, it really works use GSKit commands, I could make the connection successfully. But I'm facing with another error with my connection string. When I make the connection in localhost, it does the connection with ease, but when I deploy my application in a dev environment using ibm cloud foundry, I try to make the connection and it sends me this error:
**error: "[node-ibm_db] SQL_ERROR", sqlcode: -1336, message: "[IBM][CLI Driver] SQL1336N  The remote host \"MYHOST\" was not found.  SQLSTATE=08001\n", state: "08001"**
It is not make sense for me. Could you please help me?
