### ISSUE TITLE
Building and running the  ibm db node driver through docker error, Exec format error

### ISSUE THREAD

**Issue by berlinbrown** [ibmdb/node-ibm_db#633]
We are getting an error when "running" the ibm db driver.    The error is listed below, would you have an experience and or suggestion setting up docker to integrate with the ibm db driver and node.

Running docker build host on a Mac os system

Here is the docker file and error below,

# Build stage
FROM node:9.11.1-alpine as build-stage
WORKDIR /app
COPY app/ ./
COPY .npmrc ./
#RUN  apk/yum install add make gcc gcc-c++ kernel-devel openssl-devel bzip2-devel
#RUN  apk add python2.7.x
#RUN  apk add node.js
RUN apk update
RUN apk add build-base
#RUN apk search python2
RUN apk add python2
RUN apk add python-dev
RUN apk add py-pip
#RUN apk add node.js
RUN apk search node
RUN apk add nodejs
RUN npm install && npm run build

# Production stage
FROM node:9.11.1-alpine as production-stage
WORKDIR /app
COPY --from=build-stage --chown=node:node /app .
COPY docker-entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint.sh
USER node
ENTRYPOINT ["docker-entrypoint.sh"]

...

Error: Error loading shared library /app/node_modules/ibm_db/build/Release/odbc_bindings.node: Exec format error
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:683:18)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at bindings (/app/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/app/node_modules/ibm_db/lib/odbc.js:31:31)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
500 Internal Server Error

... And message:

> banking-consent-proc@1.0.11 build /app
> nest build

Removing intermediate container d9520a24ee5b
 ---> f99faddafef5
Step 14/20 : FROM node:9.11.1-alpine as production-stage
 ---> 9cc7800b3f3c
Step 15/20 : WORKDIR /app
 ---> Running in e50952ecc296
Removing intermediate container e50952ecc296
 ---> 9e7a25e479b0
Step 16/20 : COPY --from=build-stage --chown=node:node /app .
 ---> 5fb7c89f2b17
Step 17/20 : COPY docker-entrypoint.sh /usr/local/bin/
 ---> 36ec568ab2a7
Step 18/20 : RUN chmod +x /usr/local/bin/docker-entrypoint.sh
 ---> Running in 5227836bb2f0
Removing intermediate container 5227836bb2f0
 ---> 32eb5305fdcf
Step 19/20 : USER node
 ---> Running in ed864f218d6d
Removing intermediate container ed864f218d6d
 ---> eac3cbe74db9
Step 20/20 : ENTRYPOINT ["docker-entrypoint.sh"]
 ---> Running in 5656bd9270c4
Removing intermediate container 5656bd9270c4
 ---> 2c0b9ff3c4e2
Successfully built 2c0b9ff3c4e2
Successfully tagged bankconsent:latest
user-MacBook-Pro:banking-consent-proc user$ ./scripts/loc-build.sh 
Sending build context to Docker daemon  389.1MB
Step 1/20 : FROM node:9.11.1-alpine as build-stage
 ---> 9cc7800b3f3c
Step 2/20 : ENV http_proxy http://pxyfhq.com:3128
 ---> Running in e7087db6028f
Removing intermediate container e7087db6028f
 ---> 0a044501d8a5
Step 3/20 : ENV https_proxy http://pxyfhq.com:3128
 ---> Running in 30c6b170a1c5
Removing intermediate container 30c6b170a1c5
 ---> ba6bf85f96bb
Step 4/20 : WORKDIR /app
 ---> Running in b5b36db804d9
Removing intermediate container b5b36db804d9
 ---> 2e95c823bef8
Step 5/20 : COPY app/ ./
 ---> ad226a3d91f4
Step 6/20 : COPY .npmrc ./
 ---> 3974e3f8de8b
Step 7/20 : RUN apk update
 ---> Running in fa9261207793
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/community/x86_64/APKINDEX.tar.gz
v3.6.5-44-gda55e27396 [http://dl-cdn.alpinelinux.org/alpine/v3.6/main]
v3.6.5-34-gf0ba0b43d5 [http://dl-cdn.alpinelinux.org/alpine/v3.6/community]
OK: 8448 distinct packages available
Removing intermediate container fa9261207793
 ---> 6f21b5b808fc
Step 8/20 : RUN apk add build-base
 ---> Running in cd926a955ecb
(1/18) Upgrading musl (1.1.16-r14 -> 1.1.16-r15)
(2/18) Installing binutils-libs (2.30-r1)
(3/18) Installing binutils (2.30-r1)
(4/18) Installing gmp (6.1.2-r0)
(5/18) Installing isl (0.17.1-r0)
(6/18) Installing libgomp (6.3.0-r4)
(7/18) Installing libatomic (6.3.0-r4)
(8/18) Installing pkgconf (1.3.7-r0)
(9/18) Installing mpfr3 (3.1.5-r0)
(10/18) Installing mpc1 (1.0.3-r0)
(11/18) Installing gcc (6.3.0-r4)
(12/18) Installing musl-dev (1.1.16-r15)
(13/18) Installing libc-dev (0.7.1-r0)
(14/18) Installing g++ (6.3.0-r4)
(15/18) Installing make (4.2.1-r0)
(16/18) Installing fortify-headers (0.8-r0)
(17/18) Installing build-base (0.5-r0)
(18/18) Upgrading musl-utils (1.1.16-r14 -> 1.1.16-r15)
Executing busybox-1.26.2-r9.trigger
OK: 160 MiB in 29 packages
Removing intermediate container cd926a955ecb
 ---> 42fd37f30424
Step 9/20 : RUN apk add python2
 ---> Running in 361631ceebcf
(1/10) Installing libbz2 (1.0.6-r5)
(2/10) Installing expat (2.2.0-r1)
(3/10) Installing libffi (3.2.1-r3)
(4/10) Installing gdbm (1.12-r0)
(5/10) Installing ncurses-terminfo-base (6.0_p20171125-r1)
(6/10) Installing ncurses-terminfo (6.0_p20171125-r1)
(7/10) Installing ncurses-libs (6.0_p20171125-r1)
(8/10) Installing readline (6.3.008-r5)
(9/10) Installing sqlite-libs (3.25.3-r0)
(10/10) Installing python2 (2.7.15-r0)
Executing busybox-1.26.2-r9.trigger
OK: 208 MiB in 39 packages
Removing intermediate container 361631ceebcf
 ---> db3648a994ce
Step 10/20 : RUN apk add python-dev
 ---> Running in f77e213f012e
(1/1) Installing python2-dev (2.7.15-r0)
Executing busybox-1.26.2-r9.trigger
OK: 216 MiB in 40 packages
Removing intermediate container f77e213f012e
 ---> 29ca2f775a87
Step 11/20 : RUN apk add py-pip
 ---> Running in c7b865d28cf1
(1/2) Installing py-setuptools (33.1.1-r1)
(2/2) Installing py2-pip (9.0.1-r1)
Executing busybox-1.26.2-r9.trigger
OK: 226 MiB in 42 packages
Removing intermediate container c7b865d28cf1
 ---> 0b3dbc7b724e
Step 12/20 : RUN apk search node
 ---> Running in 2427081000b5
nodejs-6.10.3-r2
nodejs-current-npm-7.10.1-r1
munin-node-2.0.33-r0
nodejs-current-doc-7.10.1-r1
nodejs-npm-6.10.3-r2
nodejs-current-7.10.1-r1
perl-tree-dag_node-1.29-r0
nodejs-dev-6.10.3-r2
nodejs-current-dev-7.10.1-r1
sngtc_client-1.3.7-r1
nodejs-doc-6.10.3-r2
perl-tree-dag_node-doc-1.29-r0
Removing intermediate container 2427081000b5
 ---> 7efe5a46ea63
Step 13/20 : RUN npm install && npm run build
 ---> Running in dcf78c4cf9dd
npm WARN banking-consent-proc@1.0.11 No description
npm WARN banking-consent-proc@1.0.11 No repository field.
npm WARN The package config is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: abbrev@1.1.1 (node_modules/chokidar/node_modules/fsevents/node_modules/abbrev):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/app/node_modules/chokidar/node_modules/fsevents/node_modules/abbrev' -> '/app/node_modules/chokidar/node_modules/fsevents/node_modules/.abbrev.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ansi-regex@2.1.1 (node_modules/chokidar/node_modules/fsevents/node_modules/ansi-regex):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/app/node_modules/chokidar/node_modules/fsevents/node_modules/ansi-regex' -> '/app/node_modules/chokidar/node_modules/fsevents/node_modules/.ansi-regex.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: aproba@1.2.0 (node_modules/chokidar/node_modules/fsevents/node_modules/aproba):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/app/node_modules/chokidar/node_modules/fsevents/node_modules/aproba' -> '/app/node_modules/chokidar/node_modules/fsevents/node_modules/.aproba.DELETE'

**Comment by berlinbrown** [comment]
OK added unsafe perm, got a little further.  Now getting this, How to install libcrypt for build and runtime.      "message": "Error loading shared library libcrypt.so.1: No such file or directory (needed by /app/node_modules/ibm_db/build/Release/../../installer/clidriver/lib/libdb2.so.1)",

**Comment by bimalkjha** [comment]
@berlinbrown https://pkgs.org/download/libcrypt.so.1

**Comment by berlinbrown** [comment]
Can you post a reference to or show a standard dockerfile that works with ibm_db?

**Comment by bimalkjha** [comment]
@berlinbrown "FROM node:9.11.1-alpine as build-stage"
Seems you are using Alpile linux. ibm_db do not work with alpine. Please check [this comment](https://github.com/ibmdb/node-ibm_db/issues/605#issuecomment-578423994).
You can use https://hub.docker.com/_/amazonlinux. ibm_db works fine with amazonlinux.

**Comment by berlinbrown** [comment]
Will try, amazonlinux doesn't have node, will look around

**Comment by berlinbrown** [comment]
Getting closer, this one compiles at least, but get an error on runtime.
https://gist.github.com/berlinbrown/cab2c5eae6f13a69390a87cef241b208

About to require ibm
Error: /app/node_modules/ibm_db/build/Release/odbc_bindings.node: invalid ELF header
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:683:18)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)

**Comment by berlinbrown** [comment]
OK I fixed and got this, thanks you can close.  I still want to use a non amazon-linux image, centos or rhel.  https://github.com/berlinbrown/dockerfile-amazon-db2-nodejs

**Comment by lakhanpalv** [comment]
ubuntu:18.04 worked for me. alpine didn't work for me as well.

**Comment by bimalkjha** [comment]
@berlinbrown ibm_db works with centos and rhel too. You can try those images. Thanks.

**Comment by berlinbrown** [comment]
Thanks, ok to close.   Also, outside of mine, wish had a full example Dockerfile.
