### ISSUE TITLE
querySync fails with SELECT from INSERT statement

### ISSUE THREAD

**Issue by sifear** [ibmdb/node-ibm_db#634]
querySync fails with SELECT from INSERT statement, whereas query() works fine.
No exception is thrown. Node.js server terminates. Last debug message:

```
15.042 ::  odbc.js:querySync() =>  SELECT PROJ_ID FROM FINAL TABLE (INSERT INTO PARENT_PROJ (PROJ_ID, PROJ_NAME, PROJ_DESCR) VALUES(L
PAD(CAST(NEXT VALUE FOR PARENT_PROJECT_ID AS VARCHAR(4)), 4, '0'), ?, ?))
```

No other message, server aborts, got back terminal prompt.

My case:

```
let query_parent =
            "SELECT PROJ_ID " +
            "FROM FINAL TABLE (" +
            "INSERT INTO PARENT_PROJ (PROJ_ID, PROJ_NAME, PROJ_DESCR) " +
            "VALUES(LPAD(CAST(NEXT VALUE FOR PARENT_PROJECT_ID AS VARCHAR(4)), 4, '0'), ?, ?))";

let param1_parent = {ParamType: "IN", DataType: "SQL_CHAR", Data: req.body.group};
let param2_parent = {ParamType: "IN", DataType: "SQL_CHAR", Data: req.body.desc};
...
// This works fine, data has content like: [ { PROJ_ID: '0053' } ]
let projectId = conn.query(query_parent, [param1_parent, param2_parent], function (err, data) {
   console.log(data);
});
...
// This does not work, node server terminates without exception
let projectId = conn.querySync(query_parent, [param1_parent, param2_parent]);
```

**Comment by bimalkjha** [comment]
@sifear I just pushed an update to test file to test the scenario described by you.
```
    let param1 = {ParamType: "IN", DataType: "SQL_CHAR", Data: 'rocket'};
    let data = db.querySync("select COLTEXT from final table (insert into " + common.tableName + " (COLTEXT) values (?))", [param1]);
    console.log("Inserted data = ", data);
    assert.deepEqual(data, [ { COLTEXT: 'rocket' } ]);
```
You can get the latest file from git and run it after updating connection information in `test/config.testConnectionStrings.json` file. We can see the described scenario is working fine without any issue.
Your case may be specific. I would request to reproduce the issue by modifying `test/test-query-insert.js` file and share the repro file here to investigate further. Thanks.

**Comment by bimalkjha** [comment]
I am closing the issue as of now. We can reopen it if you can reproduce the problem by modifying the test-query-insert.js test file. Thanks.
