### ISSUE TITLE
Possible to set DB connection as read-only?

### ISSUE THREAD

**Issue by Mattperkinsee** [ibmdb/node-ibm_db#638]
Is this possible when you create the connection? The data I'm connecting to is used on a daily basis, and it would be nice if you could set the connection to be read-only.

**Comment by bimalkjha** [comment]
@Mattperkinsee Yes, you can use ReadOnlyConnection=1 in connection string passed to ibmdb.open() or pool.open() APIs. Its documented [here](https://www.ibm.com/support/knowledgecenter/SSEPGG_11.1.0/com.ibm.db2.luw.apdv.cli.doc/doc/r0061511.html). Thanks.

**Comment by Mattperkinsee** [comment]
Thank you!
