### ISSUE TITLE
HADR?

### ISSUE THREAD

**Issue by robomeister** [ibmdb/node-ibm_db#643]
I've got an HADR setup between DB2 servers in two different locations, so I can't do any kind of IP takeover.

Does the driver support identifying multiple DB2 servers, like we can in java?

**Comment by bimalkjha** [comment]
@robomeister Yes driver supports HADR connection like using ODBC driver. Thanks.

**Comment by robomeister** [comment]
That's awesome!  What would the syntax look like, and how would reconnection work?

**Comment by bimalkjha** [comment]
@robomeister You need to configure HADR primary and standby databases on server. If your server is already configured, your application just need to connect to the primary database. Use the hostname or ipaddress of primary database in connection string. Thanks.

**Comment by robomeister** [comment]
That's great, I didn't realize.  We have HADR setup.

Does the same go for JDBC drivers?  Currently, my the definitions in one of my apps looks like this:

```
<properties.db2.jcc currentSchema="DB2" databaseName="demo" portNumber="50000" serverName="10.166.204.90" user="db2" password="password"
                        enableClientAffinitiesList="1"
                        clientRerouteAlternateServerName="10.166.204.90,10.141.54.118"
                        clientRerouteAlternatePortNumber="50000,50000" 
                        maxRetriesForClientReroute="5" 
                        retryIntervalForClientReroute="2" />
```

Do I need all the reroute parameters, or can I just connect to the primary database?

**Comment by bimalkjha** [comment]
@robomeister You need to create a ibm_db/installer/clidriver/cfg/db2dsdriver.cfg file and configure ACR as documented here: https://www.ibm.com/support/knowledgecenter/SSEPGG_11.1.0/com.ibm.db2.luw.apdv.cli.doc/doc/c0056272.html
You need to configure alternateserverlist, affinitylist, etc in this file with the values as you shared in above post. Your db2dsdriver.cfg file may look like as one in [this comment](https://github.com/ibmdb/node-ibm_db/issues/537#issue-444938243). Then no need to use these java params in connection string. ibm_db reads it from db2dsdriver.cfg file and use it during connection. Thanks.

**Comment by robomeister** [comment]
OK, thanks.

**Comment by bimalkjha** [comment]
@robomeister You can avoid userid and password in db2dsdriver.cfg file and use it in connection string. The keywords in connection string get merged into the key,value read from db2dsdriver.cfg file and value used in connection string takes high priority. Thanks.
