### ISSUE TITLE
Connection time out

### ISSUE THREAD

**Issue by jaydipdangariya** [ibmdb/node-ibm_db#644]
Hello team,

We are using connection pool in our appliocation we need some your input in below quetions
1) what is the optimal connection pool size to get best performance?
2) we we are not set any coonection time out then what is the defaault timeout ?
3) what is optimal timeout to get best result?

Please provide your input.

**Comment by bimalkjha** [comment]
@jaydipdangariya Good to know that you are using connection pooling feature for better performance of the application. Please find answers as below:
1. It depends on how much concurrent connection requests comes to your application. You can start with some lower number like 10 or 20. Then let the pool grow based on request. After sometime it will become stable.
2. Default connection timeout is set to 60sec [here](https://github.com/ibmdb/node-ibm_db/blob/master/lib/odbc.js#L1825)
3. It again depends on your network speed. But, 60 sec is optimal which ibm_db set by default. If you see frequent timeout with this value, then you can change it to 180 sec. You can pass it in option as { connectTimeout : 40} as documented for .open or [.openSync](https://github.com/ibmdb/node-ibm_db/blob/master/APIDocumentation.md#-2-opensyncconnectionstring-options) APIs. Thanks.

**Comment by jaydipdangariya** [comment]
Thank you for your quick response

Also we want to know what the maximum limit of connection pool?

Thanks

**Comment by bimalkjha** [comment]
@jaydipdangariya There is no maximum limit of connection pool however there is limit for maximum number of allowed connection on db2 server as per db2 documentation. You can have a maximum of 512 connections opened against a db2 server.
If you do not close a connection by calling conn.close(), the connection will remain open until server do not close it from their side. Db2 server monitors the ideal connection and closes it after keep alive timeout.
We always recommend to close a connection by calling conn.close() once its job is done.
conn.connected variable tells that connection is open or not. You can not access closed connection. Check test file test-open-connectTimeout.js to see how we verify the opened connection. Thanks.

**Comment by bimalkjha** [comment]
```
test-max-pool-size.js:pool.setMaxPoolSize(5); // Max no of active connections.
```
You can set the maximum number of allowed connections in connection pool: https://github.com/ibmdb/node-ibm_db/blob/master/APIDocumentation.md#-4-setmaxpoolsizen

While initializing the pool using `ibmdb.Pool()`, you can pass `autoCleanIdle:true` option to instruct ibm_db to clean the idle connection from connection pool after every 30min or you can set `idleTimeout:<sec>` as option in ibmdb.Pool() to automatically clean idle connections from pool periodically.
You can pass `maxPoolSize` and `connectTimeout` too as option while initializing pool. For details, check [this](https://github.com/ibmdb/node-ibm_db/blob/master/lib/odbc.js#L1800) code.
```
let  ibmdb = require("ibm_db");
let pool = new ibmdb.Pool({maxPoolSize:50, connectTimeout:40, autoCleanIdle:true, idleTimeout:1200});
pool.open(connectionStr, ....
```
Thanks.

**Comment by jaydipdangariya** [comment]
Thank you it will really help us

**Comment by Kannndev** [comment]
For someone facing this, only when you use Pool it is set to 60 seconds by default. If you do not use Pool, the default value for connectTimeout is null. So you need to pass this value explicitly if you don't use the pool.
