### ISSUE TITLE
Query TimeOut

### ISSUE THREAD

**Issue by castasint** [ibmdb/node-ibm_db#645]
We've been running our portal using this module to connect to an LUW 10.5 server.  Recently, our DBA has reported that there were a couple of queries hanging in there for 4 days.  I want to know if there is a way to pass the query time out along with the query/connection. I have checked the type definition and it doesn't contain any property that indicates a query level timeout setting.  

Then I came across this https://www.ibm.com/support/knowledgecenter/SSEPGG_10.1.0/com.ibm.swg.im.dbclient.config.doc/doc/r0057060.html  and tried entering the value in the config file. It did not work either.

So, any thoughts on how I can troubleshoot it, and fix it?

**Comment by bimalkjha** [comment]
@castasint Please validate the created db2dsdriver.cfg file using `db2cli validate -dsn <dsnalias> -user <userid> -passwd <dbpass> -connect` command. If it fails,then query timeout set in the cfg file may not be effective.
You can also share your db2dsdriver.cfg file with us to verify it is correct or not. Also, would like to know, what connection string you are using in ibmdb.open() call. cfg file should be validated against that connection string to make sure query timeout is read properly and effective. Thanks.
