### ISSUE TITLE
Many nodejs forks vs single nodejs with pool connections - DB2 multiple core usage

### ISSUE THREAD

**Issue by amcintyre99** [ibmdb/node-ibm_db#648]
Many nodejs child forks, each with their own DB2 connection, will let DB2 use multiple cores on a box. I have the code and it works great.

My question is, will a single nodejs using multiple DB2 pool connections, let DB2 use multiple cores?

thanks,
Andrew

**Comment by bimalkjha** [comment]
@amcintyre99 Thought I have not verified, but yes, in later case also it should use multiple cores. ibm_db uses libuv threads to execute queries. That means by default, your node application will use one event loop thread and four worker thread. These threads will use different cores for parallel execution as in case of multiple child forks. Using pooled connection is always faster as it already has an established connection. Thanks.

**Comment by amcintyre99** [comment]
Thanks!! Do you have an example of a single node using multiple pooled connections asynchronously? So they all overlap and use multiple cores?

thanks,
Andrew

**Comment by bimalkjha** [comment]
@amcintyre99 You can execute `ibm_db\test\test-pool-connect.js` after updating connection string in `ibm_db\test\config.testConnectionStrings.json` and verify it. You can modify `test-pool-connect.js` to increase the number of connections in pool. I do not have any other example and can not verify use of multiple cores. Thanks.
