### ISSUE TITLE
Trouble with CLI_keywords

### ISSUE THREAD

**Issue by DarekDan** [ibmdb/node-ibm_db#649]
I am failing to switch application compatibility level with the ODBC driver. It works just fine in JAVA with special JDBC registers, but does anyone have recommendation how could I get the ODC driver to recognize CLI keywords, for example, `CLI_ClientApplCompat=V11R1` as part of the connection string.

https://www.ibm.com/support/knowledgecenter/SSEPGG_11.1.0/com.ibm.db2.luw.apdv.cli.doc/doc/r0000584.html

https://www.ibm.com/support/knowledgecenter/SSEPGG_11.1.0/com.ibm.swg.im.dbclient.config.doc/doc/r0070137.html

Environment variables are also not recognized, i.e. SQL_ATTR_CLIENT_APPLCOMPAT.

**Comment by DarekDan** [comment]
If I remove `CLI_` prefix, I get this error:

Error: [IBM][CLI Driver] SQL0969N  There is no message text corresponding to SQL error "-30025" in the message file on this workstation.  The error was returned from module "**REMOVED**" with original tokens "**REMOVED** DSN12010:V11R1:V10R1 0600 0002".  SQLSTATE=56073

**Comment by bimalkjha** [comment]
@DarekDan If you check the link https://www.ibm.com/support/knowledgecenter/SSEPGG_11.1.0/com.ibm.swg.im.dbclient.config.doc/doc/r0070137.html , you can find that there is no equivalent CLI keyword for `ClientApplCompat` and hence you can not use it in db2cli.ini file or connection string. You need to use db2dsdrvier.cfg file and add it as suggested in the link.
Yes, currently ibm_db do not have capability to support all connection and environment attributes. Use of `db2dsdriver.cfg` file is recommended. You can find a sample file as `ibm_db\installer\clidriver\cfg\db2dsdriver.cfg.sample` or search KC for more info. Make sure to run `db2cli validate` command to verify your db2dsdriver.cfg file is correct and CientApplCompat keyword is getting read. Thanks.

**Comment by DarekDan** [comment]
I believe you are correct. I presumed that `ClientApplCompat` is the keyword, so combined with `CLI_` I was expecting it to work. The documentation on `db2dsdriver.cfg` is limited at it comes to integrations with NodeJS, and I don't have the db2cli client installed. Could you advise where such file should be placed for an NodeJS app? Much appreciated.

**Comment by DarekDan** [comment]
... and how do I pick a connection from it ...

**Comment by DarekDan** [comment]
I will be happy to expand the documentation once tested.

**Comment by DarekDan** [comment]
I've tried using DB2DSDRIVER_CFG_SOURCE_PATH but it did not succeed.

**Comment by DarekDan** [comment]
Tried DB2DSDRIVER_CFG_PATH as well, pointing the the directory and/or the file.

**Comment by DarekDan** [comment]
So I've found the db2cli, but since I am on a Mac, I can't set LD_LIBRARY_PATH to lib, so I am getting this nice error:

===============================================================================
db2dsdriver.cfg schema validation for the entire file:
===============================================================================

```
Failure: Internal error while loading xml4c library. Validation cannot continue
         further. Contact IBM technical support to rectify the issue.
```

**Comment by bimalkjha** [comment]
@DarekDan db2dsdriver.cfg file need to be copied as `ibm_db\installer\clidriver\cfg\db2dsdriver.cfg`.
You can find db2cli as `ibm_db\installer\clidriver\bin\db2cli`.
No need to set DB2DSDRIVER_CFG_PATH or DB2DSDRIVER_CFG_SOURCE_PATH if cfg file is saved as `ibm_db\installer\clidriver\cfg\db2dsdriver.cfg`, so please clean these environment variables.
On macos, you can set DYLD_LIBRARY_PATH env var. LD_LIBRARY_PATH  is not for macos.
You can source `ibm_db\installer\setenv.sh` script to set environment variables, then db2cli command will work fine.

You can update the connection string in below file and save it as `ibm_db\installer\clidriver\cfg\db2dsdriver.cfg`:
```
$ cat db2dsdriver.cfg
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<configuration>
  <dsncollection>
    <dsn alias="rs23db" host="rs23.rocketsoftware.com" name="dbname" port="3780">
      <parameter name="UserID" value="dbuser"/>
      <parameter name="Password" value="dbpass"/>
      <parameter name="ClientApplCompat" value="V12R1M500"/>
    </dsn>
  </dsncollection>
  <databases>
    <database host="rs23.rocketsoftware.com" name="dbname" port="3780"/>
  </databases>
</configuration>
```
You can verify the above cfg file using below command:
```
source ibm_db\installer\setenv.sh
db2cli validate -dsn rs23db -connect
<above validate command must print success in last, else check connection info output and cfg>
```
Then in ibm_db connection string, use connection string as: "dsn=rs23db;". It should work fine.
You can remove UserID and Password keyword from db2dsdrvier.cfg file. In that case validate command would be:
`db2cli validate -dsn rs23db -user dbuser -passwd dbpass -connect`
and connection string for `ibmdb.open()` would be "dsn=rs23db;uid=dbuser;pwd=dbpass".
Thanks.
