### ISSUE TITLE
ibm_db installation fails "make: *** [Release/obj.target/odbc_bindings/src/odbc.o] Error 1"

### ISSUE THREAD

**Issue by mswist** [ibmdb/node-ibm_db#650]
Hello,
When I'm trying to install ibm_db, I'm getting the following error:

npm WARN package.json sql@0.0.1 No description
npm WARN package.json sql@0.0.1 No repository field.
npm WARN package.json sql@0.0.1 No README data
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN engine request@2.88.2: wanted: {"node":">= 6"} (current: {"node":"0.10.46","npm":"2.15.1"})
npm WARN engine fs-extra@8.1.0: wanted: {"node":">=6 <7 || >=8"} (current: {"node":"0.10.46","npm":"2.15.1"})
npm WARN engine form-data@2.3.3: wanted: {"node":">= 0.12"} (current: {"node":"0.10.46","npm":"2.15.1"})
npm WARN engine har-validator@5.1.3: wanted: {"node":">=6"} (current: {"node":"0.10.46","npm":"2.15.1"})
npm WARN engine universalify@0.1.2: wanted: {"node":">= 4.0.0"} (current: {"node":"0.10.46","npm":"2.15.1"})
npm WARN engine har-schema@2.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.46","npm":"2.15.1"})
npm WARN engine punycode@2.1.1: wanted: {"node":">=6"} (current: {"node":"0.10.46","npm":"2.15.1"})
npm WARN engine punycode@2.1.1: wanted: {"node":">=6"} (current: {"node":"0.10.46","npm":"2.15.1"})

> ibm_db@2.6.4 install /home/x6030/apps/sql/node_modules/ibm_db
> node installer/driverInstall.js

platform =  linux , arch =  x64 , node.js version =  v0.10.46
Unable to find 'make' in PATH. Installation may fail!
IBM_DB_HOME environment variable have already been set to -> /home/x6030/apps/sql/clidriver

Downloading of clidriver skipped - build is in progress...

make: Entering directory `/home/x6030/apps/sql/node_modules/ibm_db/build'
  CXX(target) Release/obj.target/odbc_bindings/src/odbc.o
make: Leaving directory `/home/x6030/apps/sql/node_modules/ibm_db/build'

{ [Error: Command failed: ../src/odbc.cpp: In static member function âstatic void ODBC::UV_AfterCreateConnection(uv_work_t*, int)â:
../src/odbc.cpp:215:27: warning: âv8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) constâ is deprecated (declared at ../node_modules/nan/nan.h:1742) [-Wdeprecated-declarations]
     data->cb->Call(1, info);
                           ^
../src/odbc.cpp:227:27: warning: âv8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) constâ is deprecated (declared at ../node_modules/nan/nan.h:1742) [-Wdeprecated-declarations]
     data->cb->Call(2, info);
                           ^
../src/odbc.cpp: In static member function âstatic void ODBC::GetStringParam(v8::Local<v8::Value>, Parameter*, int)â:
../src/odbc.cpp:1039:17: error: âclass v8::Stringâ has no member named âWriteOneByteâ
         string->WriteOneByte( ISOLATECOMMA (uint8_t *)param->buffer );
                 ^
../src/odbc.cpp: In static member function âstatic v8::Local<v8::Value> ODBC::CallbackSQLError(SQLSMALLINT, SQLHANDLE, char*, Nan::Callback*)â:
../src/odbc.cpp:1237:19: warning: âv8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) constâ is deprecated (declared at ../node_modules/nan/nan.h:1742) [-Wdeprecated-declarations]
   cb->Call(1, info);
                   ^
make: *** [Release/obj.target/odbc_bindings/src/odbc.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.10.0-1127.el7.x86_64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build" "--IS_DOWNLOADED=false" "--IBM_DB_HOME=/home/x6030/apps/sql/clidriver"
gyp ERR! cwd /home/x6030/apps/sql/node_modules/ibm_db
gyp ERR! node -v v0.10.46
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
] killed: false, code: 1, signal: null }
npm ERR! Linux 3.10.0-1127.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i" "ibm_db"
npm ERR! node v0.10.46
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! ibm_db@2.6.4 install: `node installer/driverInstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ibm_db@2.6.4 install script 'node installer/driverInstall.js'.
npm ERR! This is most likely a problem with the ibm_db package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node installer/driverInstall.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ibm_db
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls ibm_db
npm ERR! There is likely additional logging output above.

Thank You
Maciej

**Comment by bimalkjha** [comment]
@mswist In your post, we can see "node.js version = v0.10.46". It is more than 5 years old node.js version. Many node.js packages do not support this initial version of node.js as visible in the warning. Please install node.js version > 8.x and then install ibm_db. 

As per ibm_db documentation: `Recommended version of node.js is >= V6.X`
If you have some kind of dependency on this older node.js version, then you can use `npm install ibm_db@2.5.3` to install ibm_db. Thanks.
