### ISSUE TITLE
Can we connect using API Key/Access Token without using User Id and Password?

### ISSUE THREAD

**Issue by vamshikrishnanethi** [ibmdb/node-ibm_db#651]
Hello,

We are trying to establish a communication with DB2 module on Cloud using ibm_db and want to know if the module can use an API Key or an Access Token in the connection string to communicate with the DB instead of traditional User ID and Password.

**Comment by bimalkjha** [comment]
@vamshikrishnanethi It is not the client that decides authentication mechanism to establish connection with server but its the server which facilitates authentication mechanisms and client just follow it. If client use any API Key or Access Token for connection, but server do not support any such mechanism then application can not get any connection. So, you should check with you cloud provider that the Db2 server instance supports API Key based authentication or not. If server supports, then all clients have to support it.
I checked Db2 knowledge center and found a link that documents all types of authentication mechanism supported by the server here: https://www.ibm.com/support/knowledgecenter/SSEPGG_11.1.0/com.ibm.db2.luw.admin.sec.doc/doc/c0005435.html
All mechanism documented on above page is supported by ibm_db. Thanks.

**Comment by vamshikrishnanethi** [comment]
@bimalkjha Thanks for the response. We know that the DB2 instance can be authenticated using an API Key/Access Token as we have tried something similar with a JAVA Liberty application. When trying to do the same with a Node app we are getting different errors like Username/Password incorrect, Communication error etc., It might be due to syntax errors as well.

We have looked everywhere but couldn't find an example or documentation related to the Connection string parameters for ibm_db. May be an example of connection string with API Key/Access Token might help.

**Comment by bimalkjha** [comment]
>> Thanks for the response. We know that the DB2 instance can be authenticated using an API Key/Access Token as we have tried something similar with a JAVA Liberty application.

@vamshikrishnanethi  Could you please share some link or example that shows you can authenticate to Db2 server using API Key/Access Token? I checked Db2 server documentation and no IBM Database Server support API Key for authentication as of now in any released version of Db2.

Liberty might be supporting API Key/Access Token for authentication but that should be for application server authentication and not for Db2 server authentication. No released version of IBM Java/JDBC driver supports API Key/Access Token based authentication as of now. We are working on to support JSON Web Token in JDBC, ODBC and other Open Source drivers that will be available for use in next release of Db2 after few months, but till now, none of the IBM Client Driver or Server supports ACCESS TOKEN based authentication. Thanks.

**Comment by vamshikrishnanethi** [comment]
@bimalkjha This is the documentation we are following as of now. https://cloud.ibm.com/docs/Db2onCloud?topic=Db2onCloud-iam#jdbc

They have listed examples for different database client interfaces like JDBC, CLP, CLPPLUS, ODBC with different IAM authentication methods like Access Token, API Key, IBMid/password

Following the same, we were able to connect using JAVA Liberty as it uses JDBC connection but having issues with Node JS app as ibm_db uses ODBC.

**Comment by bimalkjha** [comment]
@vamshikrishnanethi Ok. So you are following the cloud documentation. Since, ibm_db uses ODBC driver internally so instructions documented for [ODBC](https://cloud.ibm.com/docs/Db2onCloud?topic=Db2onCloud-iam#odbc-clpplus) should work for ibm_db.
The Db2onCloud documentation has example using db2dsdrvier.cfg file that you can create either manually or using `db2cli writecfg` command as documented in example. Also, you can directly use ACCESSTOKEN or APIKEY in connection string without using db2dsdriver.cfg file as below:
```
"database=sample; hostname=localhost; port=52912;uid=dbuser;pwd=dbpass; Authentication=GSSPLUGIN ;protocol=TCPIP; accesstoken=<string>"

                                                    or 
"database=sample; hostname=localhost; port=52912;uid=dbuser;pwd=dbpass;protocol=TCPIP; Authentication=GSSPLUGIN; apikey=<string>"
                                                   
                                                    or
"database=sample; hostname=localhost; port=52912;uid=dbuser@<string>.com;pwd=dbpass;protocol=TCPIP; Authentication=GSSPLUGIN
```
To use ACCESSTOKEN or APIKEY, we must specify `Authentication=GSSPLUGIN` in database connection string. Let me know if you face any issue using these connection string. Thanks.

**Comment by vamshikrishnanethi** [comment]
@bimalkjha Again, thanks for the quick response. The reason we are trying to use Access Token/API Key is to avoid using the traditional user id and password but looking at the connection strings you have provided it needs the uid and pwd no matter what. 

Is there a way to only use Access Token / API Key? Thanks!

**Comment by bimalkjha** [comment]
@vamshikrishnanethi 
>> Is there a way to only use Access Token / API Key without the uid and pwd? 

No, currently to connection dashdb using non-JCC driver, userid and passwd is mandatory with ACCESSTOKEN/APIKEY. I am not sure about connection using JCC driver. Need to check with JCC team. Thanks.

**Comment by vamshikrishnanethi** [comment]
@bimaljha 

So you are saying we were able to connect from JAVA Liberty app as it was using JDBC connection and the same is not possible here as we are using ODBC?

If don't think that's true according to this documentation at least
https://cloud.ibm.com/docs/Db2onCloud?topic=Db2onCloud-iam#odbc-clpplus

as they have provided the examples for ODBC connection. Again, my only question here was if the npm ibm_db@2.6.3 is capable of handling this type of connection or do we need to install any plugins to make this work. 

I even tried the manual installation of ibm_db (2.2.2 Manual Installation by using git clone) from here
https://github.com/ibmdb/node-ibm_db/blob/master/INSTALL.md/#inslnx

and even the config.json provided after installation had uid and pwd. That's where I was stuck and not exactly sure how to proceed further.

**Comment by bimalkjha** [comment]
@vamshikrishnanethi I checked with my team member. Here is update from him:
```
If we don’t give both userid and password, only give accesstoken or apikey it is going ahead 
for IAM using below connection string.

"database=MYLUDB; hostname=waldevdbcwtst03.rocketsoftware.com;
port=50000;Authentication=GSSPLUGIN;protocol=TCPIP; accesstoken=abc;"

So the documentation looks correct. Ie. Only apikey or accesstoken or userid/passwd is good 
enough for IAM.

Note:
If you just give passwd and don’t give user id, client security layer is throwing
 “userid missing error”. Sameway if we give userid and don’t give password, 
client security layer will throw error which I believe may be ok.
```
Thanks and Regards,
Bimal Jha

**Comment by bimalkjha** [comment]
@vamshikrishnanethi Please let me know your Operating System name on which you are installing ibm_db. Also, would suggest to remove current ibm_db directory and install ibm_db@2.6.4. If you have some older version of ibm_db installed then IAM authentication may not work on few platforms due to some missing library which we have fixed recently by updating ibm_db/installer/clidriver on all platforms. If you are not on windows, the please check directory `ibm_db/installer/clidriver/security64` exist or not. Thanks.

**Comment by vamshikrishnanethi** [comment]
@bimalkjha 

Thanks for the update. I was using ibm_db@2.6.3 earlier and looks like updating it to 2.6.4 solved the problem. We have successfully established a communication using  API Key. Appreciate the help.

**Comment by bimalkjha** [comment]
@vamshikrishnanethi Glad to know that its working for you and your issue is fixed. Thanks.
