### ISSUE TITLE
CLI0600E Invalid connection handle or connection is closed. SQLSTATE=S1000

### ISSUE THREAD

**Issue by ic1011** [ibmdb/node-ibm_db#652]
Hello!

I'm trying to establish a connection from Windows 10 to DB2 on IBM i but I get the error from the title. I basically did ```npm install ibm_db``` and adjusted the example code snippet provided by you. The node version is v12.16.2. Here is the code snippet (the connection string has been redacted):

```javascript
var ibmdb = require('ibm_db');

ibmdb.open("HOSTNAME=X.X.X.X;PORT=446;DATABASE=db_name;PROTOCOL=TCPIP;UID=user1;PWD=pass1;", function (err,conn) {
  if (err) return console.log(err);
  
  conn.query('select 1 from sysibm.sysdummy1', function (err, data) {
    if (err) console.log(err);
    else console.log(data);

    conn.close(function () {
      console.log('done');
    });
  });
});
```

Did I miss some prerequisites? Any info on what is going on will be much appreciated, thank you!

**Comment by bimalkjha** [comment]
@ic1011 Please update the database connection information in `ibm_db\installer\testODBCConnection.bat` file for `db2cli validate` command near line number 16 and execute testODBCConnection.bat script to verify the connectivity to iSeries server. Please share the complete output of `testODBCConnection.bat` script with us. Also, if you do not get `SUCCESS` at the end of output of this script, please email the generated 1.* files to bjha@rocketsoftware.com. Thanks.

**Comment by ic1011** [comment]
@bimalkjha, thank you for your reply! As requested, I've sent the trace files to the provided email.

The batch script returned "**Failed to alloc env handle**" just before the line "**The validation is completed.**"

Just tell me if you need any further info. Thanks!

**Comment by ic1011** [comment]
Just for clarity - I've tried to set up an ODBC connection through C# .NET, using the same driver, and got the same error. So I am guessing that the problem is perhaps somehow related to the driver itself.

**Comment by bimalkjha** [comment]
@ic1011 I checked the shared trace files and found that your systems language and code page is unrecognized by db2 odbc driver and hence error:
```
1.flw:
-------
4385           0.357752600   | | | | | | sqlnlsmapcodeset exit [rc = 0x800F005F = -2146500513 = SQLO_BADCP]
4386           0.357752700   | | | | | sqlnlsgetcpcc exit [rc = 0x870F00C8 = -2029059896 = SQLO_UNKCPCC]
4387           0.357752800   | | | | sqlogetcpcc exit [rc = 0x870F00C8 = -2029059896 = SQLO_UNKCPCC]
4388           0.357753700   | | | CLI_utlGetCodePage error [probe 1]
4389           0.357754600   | | | | CLI_errStoreError entry
4390           0.357755600   | | | | CLI_errStoreError exit
4391           0.357755800   | | | CLI_utlGetCodePage exit [rc = 0xFFFFFFFF = -1]
4392           0.357756000   | | CLI_allocInitializeNewEnvInfo error [probe 4]
4393           0.357756200   | | | CLI_errStoreError entry
4394           0.357756700   | | | CLI_errStoreError data [probe 999]
4395           0.357756900   | | | CLI_errStoreError exit
4396           0.357757100   | | CLI_allocInitializeNewEnvInfo exit [rc = 0xFFFFFFFF = -1]
4397           0.357757200   | SQLAllocEnv2 error [probe 6]
4398           0.357757500   | SQLAllocEnv2 data [probe 1]
4399           0.357757600   | SQLAllocEnv2 exit [rc = 0xFFFFFFFF = -1]
4408           0.357763500   SQLAllocEnv exit [rc = 0xFFFFFFFF = -1]

1.fmt:
-------
4375	data DB2 UDB National Language Support sqlnlsgetcpcc cei (3.3.56.39.2.26)
	pid 13384 tid 15316 cpid -1 node -1 sec 0 nsec 357744100 probe 26
	bytes 31

	Data1 	(PD_TYPE_DEFAULT,23) Hexdump:
	4275 6C67 6172 6961 6E5F 4275 6C67 6172    **Bulgarian_Bulgar ia.1251**
	6961 2E31 3235 31                         

4381	exit DB2 UDB National Language Support sqlnlsmapterritory cei (2.3.56.43.2)
	pid 13384 tid 15316 cpid -1 node -1 sec 0 nsec 357750700
	rc = 0

4382	data DB2 UDB National Language Support sqlnlsgetcpcc cei (3.3.56.39.2.40)
	pid 13384 tid 15316 cpid -1 node -1 sec 0 nsec 357751000 probe 40
	bytes 23

	Data1 	(PD_TYPE_DEFAULT,2) Hexdump:
	4247                                       BG

	Data2 	(PD_TYPE_DEFAULT,5) Hexdump:
	6267 5F42 47                               bg_BG

4385	exit DB2 UDB National Language Support sqlnlsmapcodeset cei (2.3.56.44.2)
	pid 13384 tid 15316 cpid -1 node -1 sec 0 nsec 357752600
	rc = 0x800F005F = -2146500513 = **SQLO_BADCP**

4386	exit DB2 UDB National Language Support sqlnlsgetcpcc cei (2.3.56.39.2)
	pid 13384 tid 15316 cpid -1 node -1 sec 0 nsec 357752700
	rc = 0x870F00C8 = -2029059896 = **SQLO_UNKCPCC**

```
Could you please set the system environment variable DB2CODEPAGE=1251and then try? You can also run `db2set DB2CODEPAGE=1251` on windows command prompt and then run your test script. Thanks.

**Comment by bimalkjha** [comment]
Actually, I do not see the code set ia.1251 into supported code set for Windows platfom [here](https://www.ibm.com/support/knowledgecenter/SSEPGG_11.1.0/com.ibm.db2.luw.admin.nls.doc/doc/r0004565.html). Are you using ia64 system instead of x64 system? Thanks.

**Comment by bimalkjha** [comment]
Closing the issue now. Please reopen with more info if you are still facing issue. Thanks.
