### ISSUE TITLE
Error: incorrect header check at Gunzip.zlibOnError

### ISSUE THREAD

**Issue by yLeushun** [ibmdb/node-ibm_db#653]
Hi Team

System gets the following error during npm install 

> npm install
> node-report@2.2.10 install /home/jenkins/agent/workspace/release/_1. Build server/node_modules/node-report
> node-gyp rebuild
>make: Entering directory '/home/jenkins/agent/workspace/release/_1. Build >server/node_modules/node-report/build'
>  CXX(target) Release/obj.target/api/src/node_report.o
> CXX(target) Release/obj.target/api/src/module.o
>CXX(target) Release/obj.target/api/src/utilities.o
> SOLINK_MODULE(target) Release/obj.target/api.node
>COPY Release/api.node
> COPY /home/jenkins/agent/workspace/release/_1. Build server/node_modules/node-report/api.node
  TOUCH Release/obj.target/install.stamp
make: Leaving directory '/home/jenkins/agent/workspace/release/_1. Build server/node_modules/node-report/build'

> ibm_db@2.6.1 install /home/jenkins/agent/workspace/release/_1. Build server/node_modules/loopback-ibmdb/node_modules/ibm_db
> node installer/driverInstall.js

>platform =  linux
>Downloading DB2 ODBC CLI Driver from https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz...

>100.00% | 607 bytes downloaded out of 607 bytes.{ Error: incorrect header check
    at Gunzip.zlibOnError (zlib.js:153:15) errno: -3, code: 'Z_DATA_ERROR' }
>npm WARN mfr-dev@0.0.1 No repository field.
>npm WARN mfr-dev@0.0.1 No license field.
>npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
>npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

>npm ERR! code ELIFECYCLE
>npm ERR! errno 1
>npm ERR! ibm_db@2.6.1 install: `node installer/driverInstall.js`
>npm ERR! Exit status 1
>npm ERR! 
>npm ERR! Failed at the ibm_db@2.6.1 install script.
>npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

>npm ERR! A complete log of this run can be found in:
>npm ERR!     /home/jenkins/.npm/_logs/2020-05-20T15_45_37_466Z-debug.log
Build step 'Execute shell' marked build as failure
>[Cobertura] Publishing Cobertura coverage report...`

**Comment by bimalkjha** [comment]
@yLeushun It seems your system is unable to download https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz from web. Probably your system is behind some firewall or network config issue. So can you try downloading it manually? After download untar it => it will give a directory named clidriver.
Then set an environment variable using `export IBM_DB_HOME=<full path of clidriver>` and run `npm install ibm_db@2.6.4`. It should work.
From the log, it seems you are using version 2.6.1 of ibm_db which is older. So, request you to first try `npm install ibm_db@2.6.4`. If it fails with same error, then download the linuxx64_odbc_cli.tar.gz manually, set env var and install ibm_db. Thanks.

**Comment by John-Kryspin** [comment]
Hi, I got the same error inside an IBM Toolchain and opened a ticket on IBM cloud, and they pointed me to this repository, as they believe it was not a toolchain issue and was an ibm_db issue. Looks like the issue is resolved, now the package installs properly, but I hope this doesn't happen again as it prevented a preproduction deploy for a few hours.

**Comment by yLeushun** [comment]
Hi @bimalkjha, @John-Kryspin, I confirm that the issue is already resolved, the root was inside integration server, which has issue with firewall.

Thank you for your time!
