### ISSUE TITLE
small fix: prevent error 

### ISSUE THREAD

**Issue by huineng** [ibmdb/node-ibm_db#655]
there are 2 lines in odbc https://github.com/ibmdb/node-ibm_db/blob/master/lib/odbc.js#L1941
eg...

```
self.usedPool[connStr].splice(self.usedPool[connStr].indexOf(db), 1);
```

there are circumstances i cannot reproduce like that , but i get the error 

cannot read property splice of undefined

little fix is just to add 

```
if(self.usedPool[connStr]) {
self.usedPool[connStr].splice(self.usedPool[connStr].indexOf(db), 1);
}
```

**Comment by bimalkjha** [comment]
@huineng Thanks for reporting it. We'll update the code soon.

**Comment by bimalkjha** [comment]
Done. Thanks.
