### ISSUE TITLE
Sporadic database error 

### ISSUE THREAD

**Issue by cityfurnituredev** [ibmdb/node-ibm_db#656]
For about 1-2 months ago, we have been facing a sporadic error that we couldn't pinpoint the cause of it, the error can not be reproduced easily, and all queries using node-ibm_db have been working with no issues once the query is rerun.

Below is the message we get from the CLI driver:
```
[IBM][CLI Driver][AS] SQL0901N  The SQL statement or command failed because of a database system error. (Reason \"CPF4204\".)  SQLSTATE=58004\n"
```
IBM documentation mentions that it is not easy to reproduce, hoping we can find an answer with your help.

Below is IBM's link
[https://www.ibm.com/support/pages/query-failing-message-cpf4204](https://www.ibm.com/support/pages/query-failing-message-cpf4204
)

We are currently running `2.6.3` and the CLI driver is on version `11.4.5`. Node version is `10.2`.
Any help is appreciated, thank you.

**Comment by bimalkjha** [comment]
@cityfurnituredev This error SQL0901N is coming from database server. ibm_db is just returning the error to application as given by server. As suggested in the shared IBM link, please check joblog on the db2 server and use the DSPJOBLOG command to review the joblog of the job that was executing the query. You should contact your system admin to know the cause of the error or contact db2 server support.
If you wanted to know which query is causing this error, the you need to enable debug logs of ibm_db. For that you just need to call `ibmdb.debug(true);` in your application code just after `require('ibm_db')`, but it may cause you performance. Thanks.

**Comment by city-furniture** [comment]
thanks for getting back to us, we will work on checking the suggested. @bimaljha . 🙏
