### ISSUE TITLE
Stored Procedures v2.6.4 and Node.js 10.0.0 Error

### ISSUE THREAD

**Issue by shireresident** [ibmdb/node-ibm_db#657]
Environment
- Windows 10
- Using cli driver from IBM Hosted URL
- Node.js 10.0.0
- NPM 6.14.5

Database: DB2 on Z/OS
DB2 connection works fine and SQL SELECT works fine.
Calling a Stored Procedure throws a native code error - line 600 of ojdbc.js.
Process finished with exit code -1066598273 (0xC06D007F)

The same package 2.6.4 and same code works fine on Node.js 8.16.0

Is there a DEBUG version of the driver hosted?

```
query=call ABC.XYZ(?,?,?,?,?,?,?,?,?,?,?,?,?,?), params=[
ParamType=INPUT, DataType=CHAR, Data=xxx,
ParamType=OUTPUT, DataType=DECIMAL, Data=,
ParamType=OUTPUT, DataType=CHAR, Data=, Length=22,
ParamType=OUTPUT, DataType=DECIMAL, Data=,
ParamType=OUTPUT, DataType=CHAR, Data=, Length=12642,
ParamType=OUTPUT, DataType=CHAR, Data=, Length=12642,
ParamType=OUTPUT, DataType=CHAR, Data=, Length=12642,
ParamType=OUTPUT, DataType=CHAR, Data=, Length=12642,
ParamType=OUTPUT, DataType=CHAR, Data=, Length=12642,
ParamType=OUTPUT, DataType=CHAR, Data=, Length=12642,
ParamType=OUTPUT, DataType=CHAR, Data=, Length=12642,
ParamType=OUTPUT, DataType=CHAR, Data=, Length=12642,
ParamType=OUTPUT, DataType=CHAR, Data=, Length=12642,
ParamType=OUTPUT, DataType=CHAR, Data=, Length=12642]
```

**Comment by bimalkjha** [comment]
@shireresident You can get the debug version by executing `npm install --debug` under ibm_db directory. Thanks.

**Comment by bimalkjha** [comment]
You can also collect ODBC and db2trace for your node application and check the odbc trace.

**Comment by shireresident** [comment]
>  You can get the debug version by executing npm install --debug under ibm_db directory.

Is this for building the driver from source?

I was able to get db2trace but looks like it fails before it outputs anything related to the SP call.

Works fine on Linux. Will check more and get back.

**Comment by bimalkjha** [comment]
>> Is this for building the driver from source?

Yes, its building from the source. Just noticed that you are on Windows platform. On windows, to compile source code, you need Visual Studio. We do not have debug library on npm/github. If you can't build, then I can share debug binary with you. Thanks.

**Comment by shireresident** [comment]
I will get VS or try to find someone in my org who has it. Please leave issue open until then. How would you share the binary? Unfortunately I will not be able to accept a binary unless it is hosted on a trusted platform due to org policies.

**Comment by bimalkjha** [comment]
@shireresident I can share binary via email or can attach here. For other methods as per your org policies, you may have to contact IBM support for assistance or let me know the way that works for you. 
To build code on windows using VS, you need to set the msbuild path into `PATH` environment variable.
   ie.: `C:\Program Files (x86)\MSBuild\14.0\bin\`.
and then execute `npm install --debug` under ibm_db directory . Thanks.

**Comment by bimalkjha** [comment]
@shireresident Let me know if any action from me is required for this issue. Else, can we close this issue?
