### ISSUE TITLE
Feature Request - Support Promises Natively

### ISSUE THREAD

**Issue by John-Kryspin** [ibmdb/node-ibm_db#658]
Hi,
Working with this framework has been great, except for one thing: callbacks. My team has written a thin wrapper for ibm_db which exposes the interface through promises. Is there a plan for Promises to ever be supported natively, or is that out of the ibm_db team's scope?

If there is some advantage to callbacks I am not seeing please let me know!

**Comment by bimalkjha** [comment]
@John-Kryspin ibm_db APIs already return promises. See [test/promise-test-all-data-types.js](https://github.com/ibmdb/node-ibm_db/blob/master/test/promise-test-all-data-types.js) for example. You can run this test file after updating connection string in `test/config.testConnectionStrings.json` file. callbacks are not mandatory. Let me know if you see promise is not getting returned by any API that you are using in your application. Thanks.

**Comment by John-Kryspin** [comment]
Thanks @bimaljha, this is very helpful. I never saw promises were used in the documentation of ibm_dbm, I didn't even know they existed!
https://github.com/ibmdb/node-ibm_db/blob/master/APIDocumentation.md#openApi
Perhaps there should be a little note in the docs mentioning this functionality?

**Comment by bimalkjha** [comment]
@John-Kryspin We have mentioned about promise support in doc and updated quick example too. Thanks.
