### ISSUE TITLE
set package path and application compatibility

### ISSUE THREAD

**Issue by siva-srini** [ibmdb/node-ibm_db#662]
Is there any way, we can set package path and application compatibility options in the connection string or anywhere..

we are using some new functions (LISTAGG) from (Db2 v12 R1 Function level 501), for which we need to set below options before we execute the SELECT statement with LISTAGG function.

SET CURRENT PACKAGE PATH = 'NULLIDV12R1M501';
SET CURRENT APPLICATION COMPATIBILITY = 'V12R1M501';

Is there any way we can set this up in connection string itself?  may be something like below.

https://www.ibm.com/support/knowledgecenter/SSEPGG_11.1.0/com.ibm.db2.luw.apdv.java.doc/src/tpc/imjcc_tjv00019.html

**Comment by bimalkjha** [comment]
@siva-srini CURRENT PACKAGE PATH and CURRENT APPLICATION COMPATIBILITY are special registers and you can set it using db2dsdrvier.cfg file as documented here: [Application compatibility on Db2 for z/OS] (https://www.ibm.com/support/knowledgecenter/en/SSEPGG_11.1.0/com.ibm.db2.luw.qb.dbconn.doc/doc/c0061167.html). 
db2dsdriver.cfg file should be saved under `.../ibm_db/installer/clidriver/cfg` directory. Thanks.

**Comment by siva-srini** [comment]
@bimalkjha ok.. i can have the db2dsdriver.cfg (edited) in my library and copy it to node_modules folders respectively after npm install.  however can you help me with how the entry should be added?

```
<xs:element name="specialregisters" minOccurs="0" maxOccurs="1">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="parameter" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
</xs:element>
```

**Comment by bimalkjha** [comment]
@siva-srini The information that you requested is mentioned in [this](https://www.ibm.com/support/knowledgecenter/en/SSEPGG_11.1.0/com.ibm.db2.luw.qb.dbconn.doc/doc/c0061167.html) already shared link with example of db2dsdriver.cfg fle. Thanks.
