### ISSUE TITLE
Issue authenticating ibm_db using IBMid and Password

### ISSUE THREAD

**Issue by vamshikrishnanethi** [ibmdb/node-ibm_db#663]
Hello @bimalkjha 

We have discussed about this issue earlier and looks like we have not addressed all the scenarios of authenticating ibm_db using IAM Authentication.

You can refer to the discussion we had earlier in the issue #651 

I was able to communicate with the ibm_db using an API Key and Access Token but I am still having difficulties using IBMid and Password. 

I have tried a couple different methods and not matter what how I try, I keep getting this error.
error:  [IBM][CLI Driver] SQL30082N  Security processing failed with reason "27" ("INVALID SERVER CREDENTIAL").  SQLSTATE=08001

and this is the sample syntax of my connection string
DATABASE=;HOSTNAME=;PORT=;Authentication=GSSPLUGIN;protocol=TCPIP;UID=;PWD=;Security=SSL;

I did verify that my IBMid has access from the db2 Console and everything looks fine to me. Not exactly sure what am I missing here. Any help is appreciated.

**Comment by bimalkjha** [comment]
@vamshikrishnanethi You are using Security=SSL in connection string. Have you configured your server for SSL connection? Please remove Security=SSL from connection string and then try. Thanks.

**Comment by vamshikrishnanethi** [comment]
@bimalkjha 
The server is configured for SSL connection and works when using API Key or Access Token for the connection but does not work with IBMid.

**Comment by bimalkjha** [comment]
@vamshikrishnanethi Ok. So do you have SSL Certificate file from server for SSL connection? If yes, you need to add one more keyword "SSLServerCertificate=<absolute_path_of_certificate_file>;" in connection string. This certificate should be a *.arm file. Thanks.

**Comment by vamshikrishnanethi** [comment]
@bimalkjha I did try adding the SSL Server Certificate to the connection string but its still the same error.

**Comment by vamshikrishnanethi** [comment]
@bimalkjha This is kind of a high priority issue from our end and I am still waiting on your response. Thanks!

**Comment by bimalkjha** [comment]
@vamshikrishnanethi I assume you are trying to connect to dash-db instance of IBM Cloud. In that case SSLServerCertificate keyword is not required in connection string.  We need db2trace to investigate further. What the OS of the system on which you have installed ibm_db? Thanks.

**Comment by bimalkjha** [comment]
You are hitting SQL30082N  with reason code 27. As per details of this error documented [here](https://www.ibm.com/support/knowledgecenter/SSEPGG_11.1.0/com.ibm.db2.luw.messages.sql.doc/com.ibm.db2.luw.messages.sql.doc-gentopic27.html#sql30082n):
```
27 (INVALID SERVER CREDENTIAL)

    The server security plugin encountered an invalid server credential.

User response
27

    Verify that the server credential is provided during security plugin initialization and that 
it is in a format recognized by the security plugin. As the credential will be used to accept 
contexts, it must be an ACCEPT or BOTH credential.
```
It seems some configuration/setup is missing at server side. Thanks.

**Comment by bimalkjha** [comment]
@vamshikrishnanethi Please collect the db2trace files for investigation by running below commands:
```
db2trc on -f 1.trc
node test.js
db2trc off
db2trc flw 1.trc 1.flw
db2trc fmt 1.trc 1.fmt
db2trc fmt -cli 1.trc 1.cli
```
Please zip all 1.* files and email to bjha@rocketsoftware.com for investigation. Thanks.

**Comment by bimalkjha** [comment]
Also, I hope you are using value of userid as `user@ibm.com` which is required for Authentication=GSSPLUGIN. Thanks.

**Comment by vamshikrishnanethi** [comment]
@bimalkjha Thanks for the response.

I did investigate on the error and pretty much found the same information which is why I have reached out to you in the first place. The only thing which confuses me is why is it working with API Key & Access Token and not work with IBMid.

The value of user id would be an IBM email id which can be in various formats (different for each country) and not always user@ibm.com. Would that be a problem?

For example, the user id can be user@us.ibm.com / user@ie.ibm.com / user@hu.ibm.com / user@ibm.com

I will collect the db2trace files and send them to you ASAP so that we can further investigate. Thank you!

**Comment by bimalkjha** [comment]
@vamshikrishnanethi We just check "@" character in the userid to differentiate between normal authentication and GSSPLUGIN authentication. Only thing I suspect is it should be the userid that is used to `login in cloud` for dashdb instance. The `reason "27" ("INVALID SERVER CREDENTIAL")` in your error also tells the userid used in connection string is not the correct userid. Thanks.

**Comment by vamshikrishnanethi** [comment]
@bimalkjha I think we are getting close here. Now that you have said about "@" character, are there any limitations for the password as well? I mean can the password have special characters? If no, can you tell me which characters are not accepted.

The reason behind asking this question is, the IBMid which I am trying to use has "@" character in the password.

**Comment by bimalkjha** [comment]
@vamshikrishnanethi You can use special characters in password. Where a DB2 password contains special characters it needs to be quoted in the connection string. Enclose the password in quotes when you use the operating system shells for connecting to Db2 command line, or to run a fix pack installation. Use single quotes for Linux and double quotes for Windows.

You can check this link for more info: https://www.ibm.com/support/knowledgecenter/SSWPVP_3.0.1/com.ibm.sklm.doc/admin/ref/ref_ic_supportedspecialcharacters_password.html 
You can refer this link however it if for Java application: https://stackoverflow.com/questions/8032575/special-characters-in-db2-passwords-when-connecting-from-java 
Also, for CLPPlus client, semicolon is not supported: https://www.ibm.com/support/knowledgecenter/SSEPGG_11.1.0/com.ibm.swg.im.dbclient.install.doc/doc/c0060749.html

It is good to avoid `";" , "!" and "@"` characters in password. Different clients behave differently. CLP do not work when "@" is used at end of password. For some client, we use escape character (\) before special characters. You can try with different combinations. Special characters get expanded by OS when used on command prompt without escape or quote. For ibm_db, you need to use escape character before special character. Please try using quote or \. Thanks.

**Comment by bimalkjha** [comment]
You can print the connection string in your test program to see actually what connection string is passed to ibmdb.open() function. Is it correct or changed.

**Comment by vamshikrishnanethi** [comment]
@bimalkjha Thanks for quick response. 

I have already verified the connection string before and it looks fine to me, even though password has special characters like '@'.

I will either try changing the password to not have any special characters or use a different Id to see if that's an issue or not. If I still hit problems, I will send you the db2trace files.

**Comment by bimalkjha** [comment]
@vamshikrishnanethi Let us know if you are still facing the problem. Else, can we close this issue? Thanks.
