### ISSUE TITLE
Export a connection so I can reuse it in another file

### ISSUE THREAD

**Issue by evandroestima** [ibmdb/node-ibm_db#665]
Hello, I'm trying to create a connection in a database.js file (for example) and exporting it, so I can use it in my controllers without having to declare a new connection in every function. I do it with other databases, but I don't seem to be able to do it with db2.

Also, I'd like to know if there is any way to use a orm with db2. Thanks :)

**Comment by bimalkjha** [comment]
@evandroestima You can use [ibmdb.openSync](https://github.com/ibmdb/node-ibm_db/blob/master/APIDocumentation.md#-2-opensyncconnectionstring-options) API to get a connection in database.js and return it. If it is not working for you, please share a sample test file to reproduce the problem.
```
var conn = ibmdb.openSync(connString, option);
```
You can use sequelize ORM with db2 luw server as documented [here](https://github.com/ibmdb/sequelize#installation). But, you need to use below  commands to install ORM and ibm_db. Make sure you have git installed in the system. @shilumathai 
```
git --version
npm install --save git+https://git@github.com/ibmdb/sequelize.git#db2_support
npm install --save ibm_db
```
Thanks and Regards,
Bimal Jha

**Comment by evandroestima** [comment]
Thank you a lot! I'm gonna see if I can make everything work. Again, thanks!
