### ISSUE TITLE
Max pool size

### ISSUE THREAD

**Issue by nsanthoshkumar** [ibmdb/node-ibm_db#67]
How do I know max pool size for ibm_db. Also, is there anyway that I can change the max_pool size?

**Comment by bimalkjha** [comment]
When you run pool.open() first time using ibm_db, it opens first connection and on close put that connection back to the pool. On next pool.open(), ibm_db will return this connection back. If pool do not have any available connection, it opens a new one and return that connection to application. This way pool and pooled connections grows.

You can have maximum 512 connections opened in such way which includes connections in pool as well as connections in use. There is no option to set the maximum pool size as of now, but application can implement their own logic to do that. Thanks.

**Comment by nsanthoshkumar** [comment]
Thank you for the explanation. When you say close, it is connection.close() right,  not pool.close().

**Comment by bimalkjha** [comment]
Yes it is connection.close(). pool.close() will close all the connections in pool.

**Comment by nsanthoshkumar** [comment]
Thanks for the response.
