### ISSUE TITLE
Simple select query with ur not giving uncommitted records

### ISSUE THREAD

**Issue by ramadutta** [ibmdb/node-ibm_db#671]
Hi, I am facing a strange issue while reading uncommitted data from DB2. Below are the flow of events.

1. I have a Java component which opens a transaction and inserts two records into a table.
2. Then java component makes a rest call to nodejs api to validate some data.
3. Nodejs app gets the request and as part of it's logic it tries to read the table to get the inserted records in step 1.

As step 3 is querying for uncommitted data we are using **WITH UR** in the select query. But this query is not returning records **sometimes**. Please note that the transaction opened in java doesn't commit or rollback till the nodejs API responds. Any idea on how to resolve this?

Below are some more details.
Node version: v10.19.0
ibm_db version: 2.6.1

**Comment by bimalkjha** [comment]
@ramadutta If query is not returning the desired result, then it should be server problem. You should collect server side db2trace for steps 1, 2 &3, and contact db2support to know why server is not returning data for the SQL. ibm_db driver is just returning the data sent by server to application. Thanks.

**Comment by bimalkjha** [comment]
One of the reason for not returning the records could be the record is not inserted in the table by the time node.js app is trying to read it. Try using synchronous apis of ibm_db to read record and make sure java call is happening after node.js call only. Thanks.
