### ISSUE TITLE
CLP/CLPPlus commands

### ISSUE THREAD

**Issue by lucaskuperman** [ibmdb/node-ibm_db#674]
Hello, not sure if this is a non-sense question, but within my Express backend I could make use of CLP/CLPPlus commands to fulfill an export requirement. Does the ibm_db module provide CLP/CLPPlus commands, somehow? Is this even possible?

**Comment by bimalkjha** [comment]
@lucaskuperman node-ibm_db do not have support for import/export commands, but you can use array insert feature of ibm_db to insert multiple rows at once in faster way.
Most of the commands that you can execute using CLP/CLPPlus, you can execute using query() API of ibm_db too. But, import/export commands are tide with Db2 Instance which comes with Db2 client/server installations only. You can download the IBM Data Server Runtime Client from [here](https://www.ibm.com/support/fixcentral/swg/selectFixes?parent=ibm%7EInformation%2BManagement&product=ibm/Information+Management/IBM+Data+Server+Client+Packages&release=11.5.4.0*&platform=All&function=fixId&fixids=*-rtcl*FP000*&includeSupersedes=0&source=fc). It comes with CLP and CLPPlus. On top of this client, you can install ibm_db too by using two commands:
```
export IBM_DB_HOME=<install_dir_of_db_client>
npm intall ibm_db
```
You can execute a *.sql file in batch mode like CLP batch command using [executeFile()](https://github.com/ibmdb/node-ibm_db/blob/master/APIDocumentation.md#executeFileApi) and executeFileSync() APIs of ibm_db.
Thanks.

**Comment by lucaskuperman** [comment]
Thank you @bimalkjha !
