### ISSUE TITLE
ibm_db  zOS license now fails with licensing problem.  SQLSTATE=42968

### ISSUE THREAD

**Issue by debrajo** [ibmdb/node-ibm_db#677]
We have an existing ibm_db node application connecting to a zOS system.  Our local dev builds began failing a two weeks ago after an npm upgrade from 2.6.4 to 2.7.  They fail with the error. 
[IBM][CLI Driver] SQL1598N An attempt to connect to the database server failed because of a licensing problem. SQLSTATE=42968 
Reverting back to 2.6.4 did not fix the problem.

We're running both windows 10 for Dev, followed by Docker containers before promoting to Cloud UAT , then Cloud Production

Lots of problem determination later, and I found that linuxx64_odbc_cli.tar.gz and ntx64_odbc_cli.zip from https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli  have new time/date stamps.   

I need a bit of help to determine if something needs be fixed in ibm_db  or  if it needs to go to IBM support.

**Comment by bimalkjha** [comment]
@debrajo Your finding is correct. We have updated db2connect driver used by ibm_db internally from db2 v11.1 to db2 v11.5 for new installations. So, now you need to get db2connect license of v11.5 from IBM Support and use it. Applying the db2 v11.5 db2connect license fixes the licensing error. Thanks.

**Comment by debrajo** [comment]
I've been using license  db2consv_zs.lic /  11.1    
Let me get  v11.5 and retry ..

**Comment by debrajo** [comment]
Switched to db2consv_zs.lic / 11.5  and I'm now working successfully 
Please consider changing the readme.md  reference that ibm_db uses  db2 v11.5 so the license file needs to match.  Right now it says  11.0

**Comment by debrajo** [comment]
A little titbit.  If all you are changing in your project is the license file to fix the license issue, the docker build image may not update the cache, which will have the old license file.  You'll need to prune the image caches and make sure it pulls the new license into the image.
