### ISSUE TITLE
Array Insert unable to handle null values, irrespective of DataType

### ISSUE THREAD

**Issue by lucaskuperman** [ibmdb/node-ibm_db#679]
Hello, 
I cannot make array insert (with query API) to properly handle null values within my data arrays, irrespective of what DataType I'm trying to insert.

`params: [{ParamType:"ARRAY", SQLType:"SQL_DECIMAL", Data: [5.2,null]}]`
Result: number zero inserted instead of null

`params: [{ParamType:"ARRAY", SQLType:"SQL_DECIMAL", Data: [null,5.2]}]`
Result: both inserted as null

`params: [{ParamType:"ARRAY", Data: ["blah",null], Length: 4}]`
Result: the literal string 'null' is inserted, instead of null value

`params: [{ParamType:"ARRAY", Data: [null,"blah"], Length: 4}]`
Result: both inserted as null

`params: [{ParamType:"ARRAY", SQLType:"SQL_TYPE_TIMESTAMP",Data: [null,"2020-02-02 00:00:00.0"]}]`
Result: both inserted as null

`params: [{ParamType:"ARRAY", SQLType:"SQL_TYPE_TIMESTAMP",Data: ["2020-02-02 00:00:00.0",null]}]`
Result: Error: [IBM][CLI Driver] CLI0113E  SQLSTATE 22007: An invalid datetime format was detected; that is, an invalid string representation or value was specified. SQLSTATE=22007

Please advise if I'm doing something wrong.
Thanks

**Comment by bimalkjha** [comment]
@lucaskuperman Thanks for reporting this bug. We have fixed it now and pushed the code changes. You can verify it on non-windows by installing using command `npm install git+https://git@github.com/ibmdb/node-ibm_db.git`. It would be available with next release. Thanks.

**Comment by lucaskuperman** [comment]
Thanks @bimalkjha! but unfortunately I don't have a non-windows environment where to test your fix, yet. I tried installing it anyway but I see no difference. Forgive my ignorance, but may I know where the Win limitation comes from? I'm kinda lost. Also, when do you expect the next release be available?
Thanks!

**Comment by bimalkjha** [comment]
@lucaskuperman We are about to release a new version ibm_db with this fix in 2-3 days. Thanks.

**Comment by lucaskuperman** [comment]
Thank you @bimalkjha!! I've just downloaded 2.7.1 and is correctly handling null values now! Appreciate you and your team for fixing this.
