### ISSUE TITLE
cp: FSUM6258 cannot open file "//'DDA1LIB.SDSNC.H'": EDC5092I An I/O abend was trapped.

### ISSUE THREAD

**Issue by ebnerbenoit** [ibmdb/node-ibm_db#680]
I try to install ibm_db on a zOS node.js SMPE v12 installation.
I'll already upgrade the node-gyp and change -C to -c for the installation part.
But, I have now this error:

`15 [11:22:51] VPS@HOSTGIWD: ~/myapp  # npm i ibm_db
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported

> ibm_db@2.7.0 install /u/tsyebn/node_modules/ibm_db
> node installer/driverInstall.js

platform =  os390 , arch =  s390x , node.js version =  v12.16.1
make: Error -- FSUM8705 No target
Unable to find 'make' in PATH. Installation may fail!
cp: FSUM6258 cannot open file "//'DDA1LIB.SDSNC.H'": EDC5092I An I/O abend was trapped.
child_process.js:682
    throw err;
    ^

Error: Command failed: cp "//'DDA1LIB.SDSNC.H'" /u/tsyebn/node_modules/ibm_db/build/include
cp: FSUM6258 cannot open file "//'DDA1LIB.SDSNC.H'": EDC5092I An I/O abend was trapped.

    at checkExecSyncError (child_process.js:643:11)
    at execSync (child_process.js:679:15)
    at install_node_ibm_db (/u/tsyebn/node_modules/ibm_db/installer/driverInstall.js:113:11)
    at Object.<anonymous> (/u/tsyebn/node_modules/ibm_db/installer/driverInstall.js:655:1)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 63 70 3a 20 46 53 55 4d 36 32 35 38 20 63 61 6e 6e 6f 74 20 6f 70 65 6e 20 66 69 6c 65 20 22 2f 2f 27 44 44 41 31 4c 49 42 2e 53 44 53 4e 43 2e 48 27 ... 38 more bytes>
  ],
  pid: 16842941,
  stdout: <Buffer >,
  stderr: <Buffer 63 70 3a 20 46 53 55 4d 36 32 35 38 20 63 61 6e 6e 6f 74 20 6f 70 65 6e 20 66 69 6c 65 20 22 2f 2f 27 44 44 41 31 4c 49 42 2e 53 44 53 4e 43 2e 48 27 ... 38 more bytes>
}
npm WARN tsyebn@1.0.0 No description
npm WARN tsyebn@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ibm_db@2.7.0 install: `node installer/driverInstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ibm_db@2.7.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /u/tsyebn/.npm/_logs/2020-08-20T09_23_44_592Z-debug.log
`

for the "make" that it don't found, I don't understand as I have make in my path:
`17 [11:26:09] VPS@HOSTGIWD: ~/myapp  # make -v
>>> Defined macro MAKECMD=make
>>> Defined macro MFLAGS=
>>> Defined macro MAKEFLAGS=
>>> Defined macro OS=OPENMVS
>>> Defined macro @B=$(@:b)
>>> Defined macro @D=$(@:d)
>>> Defined macro @F=$(@:f)
>>> Defined macro %B=$(%:b)
>>> Defined macro %D=$(%:d)
>>> Defined macro %F=$(%:f)
>>> Defined macro *B=$(*:b)
>>> Defined macro *D=$(*:d)
>>> Defined macro *F=$(*:f)
>>> Defined macro <B=$(<:b)
>>> Defined macro <D=$(<:d)
>>> Defined macro <F=$(<:f)
>>> Defined macro ?B=$(?:b)
>>> Defined macro ?F=$(?:f)
>>> Defined macro ?D=$(?:d)
>>> /etc/startup.mk: line 0: Defined macro INCDEPTH=0
>>> /etc/startup.mk: line 0: Defined macro MAKESTARTUP=/etc/startup.mk
>>> /etc/startup.mk: line 0: Reading startup file '/etc/startup.mk'
>>> /etc/startup.mk: line 22: Defined macro __SILENT=
>>> /etc/startup.mk: line 23: Defined macro .SILENT=yes
`
[2020-08-20T09_23_44_592Z-debug.log](https://github.com/ibmdb/node-ibm_db/files/5102023/2020-08-20T09_23_44_592Z-debug.log)

**Comment by bimalkjha** [comment]
@ebnerbenoit I hope your problem is resolved, so closing the issue now. Thanks.
