### ISSUE TITLE
Connection timeout

### ISSUE THREAD

**Issue by huineng** [ibmdb/node-ibm_db#682]
Question, is this supposed to be working in all circumstances ?

Today we tried to make a connection (as usual) to out db2 warehouse on cloud .. using our local tools like dbeaver the connection stays in status ..connect to .. and this for 10 minutes and more.. so db2 does not even return us an error like "SQL30081N  A communication error has been detected  nothing..it stays in status trying to connect

I'm using this code in ibmdb

```
ibmdb: new Pool({
                    maxPoolSize: 50,
                    connectTimeout: 40,
                    autoCleanIdle: true,
                    idleTimeout: 1200,
                    systemNaming: true,
                }),
```

but i don't get an error back (like it has the same situation described above)

is there another setting or method where i can surely abort a connection  regardless i get a message or no message back ?

thanks

**Comment by bimalkjha** [comment]
Connection timeout should happen. Is it possible to reproduce it using a small test file? If yes, you can execute it using `test/trace repro.js` command and share the generated files for investigation. Thanks.
