### ISSUE TITLE
The specified module could not be found.  odbc_bindings.node

### ISSUE THREAD

**Issue by z1811021** [ibmdb/node-ibm_db#685]
![image](https://user-images.githubusercontent.com/15137711/91273734-41a7d580-e7b0-11ea-83df-bb5e5272a198.png)
It shows i don't have  odbc_bindings.node but in noudles_moudles i can find that

**Comment by bimalkjha** [comment]
@z1811021 What is name of your Windows OS and what version of node.js you are using? Thanks.

**Comment by z1811021** [comment]
windos 10
node v12.13.1
I already set the clidriver But when i run npm install show me the error
![image](https://user-images.githubusercontent.com/15137711/91399872-55674080-e871-11ea-8a38-53893e63587e.png)
![image](https://user-images.githubusercontent.com/15137711/91399890-5ef0a880-e871-11ea-9938-56bfb4f490e7.png)

**Comment by bimalkjha** [comment]
@z1811021 In the above shared screen, we can see `node-ibm_db installed successfully!` message near end. So, there is no issue with ibm_db installation.

We have released a new version of ibm_db@2.7.1 today. Please install this driver and let us know the result. Thanks.
