### ISSUE TITLE
ibmdb can't create connection

### ISSUE THREAD

**Issue by davidveres** [ibmdb/node-ibm_db#686]
We are having issues with connection to DB2 databases on Z/OS using ibmdb. We run a NodeJs server and when the application tries to open a connection(or initialize a pool) the server stops without giving any error message.
The issue appeared after the ODBC CLI Driver update, nothing changed in the code regarding how the connection is created.
The issue is present on both Windows and Linux.

One of my colleague who is facing the same problem gets a Segmentation fault message.

**Comment by hartalex** [comment]
I'm getting the same issue with the new driver.

ID 641 received SIGSEGV for address: 0x7ffc87191000
/opt/app/node_modules/segfault-handler/build/Release/segfault-handler.node(+0x2f36)[0x7fdd58f71f36]
/lib64/libpthread.so.0(+0x12dd0)[0x7fdd5bd4ddd0]
/lib64/libc.so.6(+0x9fbf5)[0x7fdd5ba18bf5]
/opt/clidriver/lib/libdb2.so.1(LicAddLicense+0x71b)[0x7fdd42d2eb6b]

**Comment by bimalkjha** [comment]
@hartalex Please share the Windows OS name on which you are hitting the issue. 
For above issue of Linux platform, I your gcc version might be older and installing latest gcc version >8.4 may fix the issue. Try fresh installation and let us know. Thanks.

**Comment by hartalex** [comment]
Hi @bimalkjha,
I'm working in linux.
I think i figured out the issue.  I was missing the final newline in my license file, which was somehow being dropped in my pipeline.
It also seems there was a newer version of the linux driver that dropped today which could have fixed it as well.

**Comment by sifear** [comment]
New line at the end of the licence file indeed solves the issue. Thanks for the tip @hartalex! (Windows 10, build 1909)

**Comment by davidveres** [comment]
New line worked for me too, thanks @hartalex .

**Comment by bimalkjha** [comment]
Good to know issue is solved. Closing the issue now. Thanks.
