### ISSUE TITLE
Connecting Node.js to Db2 system requiring SSL certificate

### ISSUE THREAD

**Issue by steven-ponessa** [ibmdb/node-ibm_db#687]
Node.js, like a number of modern toolkits, use ODBC like drivers instead of JDBC drivers to connect to backend relational databases.
When connecting to these Db2 instances outside of Node.js, we need to use the following parameters 
- sslConnection=true
- sslCertLocation=/full-path/certificate-name.crt

However, when trying to set up the connection in Node.js using the ibm_db package, I receive the following error:

```
[IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP". 
Communication API being used: "SOCKETS".  Location where the error was detected: "9.56.22.237".  
Communication function detecting the error: "recv".  Protocol specific error code(s): "104", "*", "0".  SQLSTATE=08001
```
The 104 indicates, “Connected partner has closed the connection.”

Reading that ibm_db requires a ***.arm** formatted certificate, which I believe is in the PEM format (ASCII version), I used the “**Keychain Access**” application on my Mac to convert the *.crt certificate file (binary) to a PEM certificate format (ASCII), and tried both through the driver below (both failed with the same error).

```node
var connStr ="DATABASE=<db-name>; HOSTNAME=<host-name>;
UID=<userid>;PWD=<pw>;PORT=<port>; 
PROTOCOL=TCPIP;
Security=SSL;SSLServerCertificate=<path-to-cert>/<cert>.arm;";

ibmdb.open(connStr, function (err,conn) {
  if (err) return console.log(err);
  
  conn.query('select 1 from sysibm.sysdummy1', function (err, data) {
    if (err) console.log(err);
    else console.log(data);
 
    conn.close(function () {
      console.log('done');
    });
  });
});

```

Is this not the correct way to establish the connection to a Db2 System that requires SSL certificates?

**Comment by bimalkjha** [comment]
@steven-ponessa We have updated odbc driver at latest level for ibm_db and hence there is no dependency on *.arm file. The SSL connection can work with *.pem file too. Updated the documentation.

I would request to install ibm_db@2.7.1 and retry the connection. If it fails, then follow below steps and shared the result:
```
cd ....\ibm_db\installer\clidriver\bin
.\db2cli writecfg add -dsn SSLDSN -database <dbname> -host <host-name> -port <ssl_port> -parameters "userid=<db_user>;password=<dbpasswd>;SecurityTransportMode=SSL;SSLServerCertificate=C:\mySSLServerCrt.pem"
db2cli validate -dsn SSLDSN -connect
```
If above `db2cli validate` command print SUCCESS near end, means it is working. You can just use "DSN=ssldsn" as connection string in your node.js program. It should work. Thanks.

**Comment by bimalkjha** [comment]
The 104 error also comes if we use invalid port in connection which is not ssl port. So, good to check the port. You can also execute the `writecfg` and `validate` command on server system to make sure server is configured properly to accept remote ssl connection. Thanks.

**Comment by NParikh-np** [comment]
Can we connect to IDM DB2 with TLS from node js without having gsKit generated certs as above option with secure port also giving an error: Error: message=[IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected:
