### ISSUE TITLE
ibm_db performance tweaks

### ISSUE THREAD

**Issue by siva-srini** [ibmdb/node-ibm_db#689]
Have been testing the new Array Insert feature and it can insert around 60k records within 10 seconds.  However, when we fetch the same 60k records, its taking more than 40 seconds.  i have varchar columns.  the largest column size in those tables are 350 and 500 varchar.  everything else is less than 50 and around 10 columns. wondering if anyone else is facing similar issue.

let me know if you need any additional information.

and my query is simple. all i do is select fields from qual.table

**Comment by bimalkjha** [comment]
@siva-srini It looks normal as ibm_db need to process every row one by one and convert the selected data to JSON format to return. The array insert does less processing than the select. Thanks.

**Comment by siva-srini** [comment]
@bimalkjha thanks for your response. if there is any way we can reduce the response time, like how we create the tables, please let  me know.  i can also check with our DBAs on this. you may close this issue.
