### ISSUE TITLE
Error when running from gulp - SQLSTATE=58004

### ISSUE THREAD

**Issue by devnieL** [ibmdb/node-ibm_db#69]
Hello,

Well, this is very strange, I was not able to fix it even following the instructions on https://github.com/ibmdb/node-ibm_db/issues/34 . 

![image](https://cloud.githubusercontent.com/assets/1231888/10658807/067924c4-7860-11e5-83b7-f7f5c80f36e0.png)

    var x = require("/Users/devniel/dev/node/pondetuparte/server").server;
    gulp.task('server', function() {
      try{
        x.listen(config.serverPort);
      }catch(e){
        console.error(e);
      }
    });

I have a gulp tasks project (pdtp.admin, pic1) and my main project folder (witch contains the node_modules with the ibm_db module, pic2). 

Basically in my project folder I have my express code with the db2 interaction through queries. If I run my code in my project folder (node server.js) the queries are executed without problems, but if I run my code with my gulp task (code above) that invoke this server.js, (gulp server) any query results with an error :

    { [Error: [IBM][CLI Driver] SQL1042C  An unexpected system error occurred.  SQLSTATE=58004] errors: [], error: '[node-odbc] SQL_ERROR',  message: '[IBM][CLI Driver] SQL1042C  An unexpected system error occurred.      SQLSTATE=58004\n',  state: 'HY000' }

I'm using the version that supports node 4.x. Any help is welcome.

Thanks.

**Comment by bimalkjha** [comment]
@devnieL We are looking into the issue. Meanwhile requesting you to fill this form: http://goo.gl/forms/EKzg7A6HZw Thanks.

**Comment by bimalkjha** [comment]
@devnieL First run below export command after edit and then run the test program:
export DYLD_LIBRARY_PATH=<node_modules_dir>/ibm_db/installer/clidriver/lib/icc:$DYLD_LIBRARYPATH

Thanks.

**Comment by bimalkjha** [comment]
No need to export DYLD_LIBRARY_PATH now. SQL1042C issue on Mac is fixed now. Thanks.

**Comment by neurotech** [comment]
@bimalkjha Are you saying that 0.0.19 fixes SQL1042C?

**Comment by bimalkjha** [comment]
@neurotech Yes. Please try now and confirm. Thanks.

**Comment by ggallo** [comment]
I'm still having trouble here, the same problem as OP. In Bluemix this runs fine, but locally it does not. OS X 10.11.5

```
$ npm list ibm_db
myProject@0.0.2 /Users/ggallo/Documents/myProject
└── ibm_db@0.0.19
$ echo $DYLD_LIBRARY_PATH 
node_modules/ibm_db/installer/clidriver/lib:/Applications/dsdriver/lib/icc:/Applications/dsdriver/lib:
```
I added that first line of `DYLD_LIBRARY_PATH` for good measure; it doesn't work with or without.

The file:
```
import ibmdb from 'ibm_db';
import config from './environment'

var connection = null;

ibmdb.open(config.dashDBConnectionString, (err, conn) => {
  if (err) return console.error(err);
  connection = conn;
});

module.exports = connection;
```
And the result:
```
{ [Error: [IBM][CLI Driver] SQL1042C  An unexpected system error occurred.  SQLSTATE=58004
]
  errors: [],
  error: '[node-odbc] SQL_ERROR',
  message: '[IBM][CLI Driver] SQL1042C  An unexpected system error occurred.  SQLSTATE=58004\n',
  state: 'HY000' }
```

**Comment by bimalkjha** [comment]
@ggallo From ibm_db@0.0.19 onwards, setting DYLD_LIBRARY_PATH to lib/icc is not required. There should be some other issue with your system. When you get this SQL1042C, check ibm_db/installer/clidriver/db2dump/db2diag.log file. There should be error detail in last. Share those logs about GSKit Error. Thanks.

**Comment by bimalkjha** [comment]
@ggallo Also, requesting you to help us by filling this form: http://goo.gl/forms/EKzg7A6HZw

**Comment by bimalkjha** [comment]
@ggallo Seems you already have a dsdriver installed in the system as /Applications/dsdriver and issue may be because of that. Please share the output of db2level command too. Thanks.

**Comment by ggallo** [comment]
@bimalkjha I will fill out the Google form and leave this issue unpolluted, since it's closed already. Thanks.

**Comment by ggallo** [comment]
@bimalkjha I filled out the Google form but never heard back. Yet removing `/Applications/dsdriver` was the solution.

Which begs the question, what if we want to install dsdriver system wide too? Remove that path from `$DYLD_LIBRARY_PATH`?

**Comment by bimalkjha** [comment]
@ggallo I thought you are going to open a new issue. we are still waiting for db2level from you. This issue seems due to older dsdriver installed in your system. Alternatively, below export should fix the issue:
```
export DYLD_LIBRARY_PATH=<path_to_ibm_db>/installer/clidriver/lib:<path_to_ibm_db>/installer/clidriver/lib/icc:$DYLD_LIBRARY_PATH
```
Thanks.
