### ISSUE TITLE
connection.closeSync() not working with pool

### ISSUE THREAD

**Issue by gdelory** [ibmdb/node-ibm_db#692]
## Issue

`connection.closeSync()` is not closing the connection in a pool, when `connection.close()` is.

## Version

Version: ibm_db@2.7.1

## Description

I know the use-case is weird, since pool methods are almost all async, but apparently closeSync is not actually releasing anything, and as soon as I reach the max pool size, the app hangs since there is no connections available in the pool.

I know it seems silly to use `closeSync()`, when all other methods are async, but since it does exist, and it makes the code clearer ,we used it, and it took us long to figure out it was the issue.

Replacing
`conn.closeSync()` with `await promisify(conn.close).bind(conn)()` fixes it. But it took me a really long time to figure this out, and since closeSync does exist, IMO it should work, or [this section of the doc](https://github.com/ibmdb/node-ibm_db/blob/master/APIDocumentation.md#PoolAPIs) should clearly state you shouldn't use closeSync().

## Code to reproduce 

Here is a basic code to reproduce this issue:

```
const ibmdb = require('ibm_db')
const {promisify} = require('util')

const dbName=process.env.DB2_NAME
const hostname=process.env.DB2_HOST
const db2user=process.env.DB2_USER
const schema=process.env.DB2_SCHEMA
const pwd=process.env.DB2_PWD
const port=process.env.DB2_PORT
const ssl = process.env.DB2_SSL == 'true' ? ';Security=SSL' : ''

const pool = new ibmdb.Pool({autoCleanIdle: true})
const cn = `DATABASE=${dbName};HOSTNAME=${hostname};UID=${db2user};PWD=${pwd};PORT=${port};PROTOCOL=TCPIP${ssl}`

const resInit = pool.init(5, cn)
if(resInit != true){
  throw new Error(resInit)
}
pool.setMaxPoolSize(10)


const withPool = async f => {
  const conn = await promisify(pool.open).bind(pool)(cn)
  try {
    const r = await f(conn)
    // Issue is here, if you comment the next line an uncomment hte following one, the issue is solved
    conn.closeSync()
    //await promisify(conn.close).bind(conn)()
    return r
  } catch (error) {
    // same as above
    conn.closeSync()
    //await promisify(conn.close).bind(conn)()
    throw error
  }
}

const executeWithPool = async (query, values) => {
  return await withPool(async conn => {
    const stmt = await promisify(conn.prepare).bind(conn)(query)
    const result = await promisify(stmt.execute).bind(stmt)(values)
    let finalRes = await promisify(result.fetchAll).bind(result)()
    result.closeSync()
    stmt.closeSync()
    return finalRes
  })
}

async function main() {
  for (let i = 0; i < 100; i++) {
    // This will become really slow after 5 iterations (opening new connection from the initial pool size)
    // then actually hang or crash at 10 (max pool size reached since no connection were released)
    console.log(await executeWithPool(`select * from ${schema}."files" where "file_uid"=?`, [i]))
  }
}

main()
```

**Comment by bimalkjha** [comment]
@gdelory The latest commit has addressed this issue by adding support for closeSync api. It'll part of next release of ibm_db. Hence, closing this issue. Thanks.

**Comment by dima19972525** [comment]
I faced this issue with 2.7.4 version
