### ISSUE TITLE
Decimals treated as strings

### ISSUE THREAD

**Issue by lucaskuperman** [ibmdb/node-ibm_db#693]
Hello, when fetching decimals as in `console.log(conn.querySync("values 1.0"))` ibm_db returns `'1.0'` when I would have expected to be returned as number, not string.

Further investigated, and apparently all returned columns with medatada `SQL_DESC_TYPE_NAME: 'DECIMAL'` are treated as strings by ibm_db. I can't properly do any arithmetic with them, so doesn't seem right to me.
Am I misinterpreting something? Is this a defect in ibm_db? Or maybe in odbc driver, or even dbms? Tried running in Windows and Linux, against different DMBS versions (10.5, 11.0, 11.1) and with different ibm_db module versions (2.6, 2.7, 2.7.1) without any difference.
Please advise. Thanks

**Comment by vvm13ru** [comment]
Things are even worse.  ibm_db returns '1,0' for Russian locale. Generally speaking, this is a typical problem for DB2 CLI. 
This thing always behaves like this. Usually solved in wrappers for different programming languages (like ibm_db2 for node.js). Sweeping trash under the carpet. So people usually don't know. In this case, there was no one to do it yet.

**Comment by bimalkjha** [comment]
@lucaskuperman @vvm13ru ibm_db@2.7.2 has fixed this bug. Please verify. Thanks.

**Comment by gialf** [comment]
Hello, as reported in [#816](https://github.com/ibmdb/node-ibm_db/issues/816) returning BigInt as number introduces a serious problem. 
Can you please fix this and return BigInt(only bigint columns) as string?

**Comment by bimalkjha** [comment]
@lucaskuperman @vvm13ru Are you fine with returning the big int columns as string and revert this fix? Could you please check the issue #816 and comment about it? Thanks.
