### ISSUE TITLE
Abends with nodev12

### ISSUE THREAD

**Issue by patbossman** [ibmdb/node-ibm_db#694]
I have a node server app that uses node-ibm_db.  When I upgraded to node v12, it abends using node-ibm_db.
/usr/lpp/nodejs/v12r0/cnj/IBM/node-latest-os390-s390x

I tried a variety of nodev12 levels.

Falling back to nodev8, the application works again.

+CEE3797I LANGUAGE ENVIRONMENT HAS DYNAMICALLY CREATED A DUMP.         
+CEE0374C CONDITION=CEE3561S TOKEN=00030DE9 59C3C5C5 00000000_0000004B 
170                                                                    
          WHILE RUNNING PROGRAM _register_odbc WHICH STARTS AT 204C93C8
          AT THE TIME OF INTERRUPT                                     
          PSW     00000001 80000000 00000000_1902F072                  
          GPR 0-2 BBBBBBBB_BBBBBBBB BBBBBBBB_BBBBBBBB BBBBBBBB_BBBBBBBB
          GPR 3-5 BBBBBBBB_BBBBBBBB 00000050_082F1FB8 00000000_1902E958
          GPR 6-8 00000000_1902E430 00000000_1902F072 00000050_00108398
          GPR 9-B 00000050_082F2DB0 00000050_082F2DB0 00000050_082F2DD0
          GPR C-E 00000000_00000009 00000000_19581D50 00000000_00000000
          GPR F   00000000_193412B4

**Comment by patbossman** [comment]
Some additional info - update to node-ibm_db 2.7.0 installs and runs OK.
node-ibm-db 2.7.1 install failes.

**Comment by bimalkjha** [comment]
@patbossman Please share the complete output of `npm install ibm_db@2.7.1` to check what is the issue. Thanks.
