### ISSUE TITLE
Is Array Update with binding parameters possible?

### ISSUE THREAD

**Issue by siva-srini** [ibmdb/node-ibm_db#696]
similar to array insert, is array update possible?  i have 10k records for which i need to update the same status for each records. have primary key data thats associated to these. instead of writing in condition, wondering if array update is possible.

```var param1 = {ParamType:"ARRAY", DataType:1, Data:[4,5,6,7,8]};
  var param2 = {ParamType:"ARRAY", DataType:"DOUBLE", Data:[4.1,5.3,6.14,7,8.3]};
  var param3 = {ParamType:"ARRAY", DataType:1, Data:[0,1,false,true,0]};
  var namearr = ["Row 10", "Row 203456", "Row 30", "Row 40", "Last Row"];

  var param4 = {ParamType:"ARRAY", DataType:1, Data:namearr, Length:8};
  // *** Use "Length: <maxDataLen>" in param Object for unequal size of data.
  // Default value is the length of first member of Array.

  var queryOptions = {sql:"insert into arrtab values (?, ?, ?, ?)", 
                      params: [param1, param2, param3, param4],
                      ArraySize:5};

  conn.querySync("create table arrtab (c1 int, c2 double, c3 boolean, c4 varchar(10))");
  conn.query(queryOptions, function(err, result) {
    if(err) console.log(err);
    else {
      var data = conn.querySync("select * from arrtab");
      console.log("\nSelected data for table ARRTAB =\n", data);
    }
  });```

**Comment by bimalkjha** [comment]
@siva-srini Given example is for array insert. What is your query for update and how you want it to behave?
Update happens conditionally and only those columns get updated which satisfies the criteria. So, would like to your test program and expected sql before commenting on the subject. Thanks.

**Comment by siva-srini** [comment]
@bimalkjha here is the information requested.

Query
```
{
  sql: 'UPDATE QUAL.TABLE SET COL3 = ?, COL4 = ?, COL5 = ?, COL6 = ?  WHERE COL1 = ? AND COL2 = ?',
  params: [
    { ParamType: 'ARRAY', DataType: 1, Length: 15, Data: [Array] },
    { ParamType: 'ARRAY', DataType: 1, Length: 35, Data: [Array] },
    { ParamType: 'ARRAY', DataType: 1, Length: 250, Data: [Array] },
    { ParamType: 'ARRAY', DataType: 1, Data: [Array] },
    { ParamType: 'ARRAY', DataType: 1, Data: [Array] },
    { ParamType: 'ARRAY', DataType: 1, Data: [Array] }
  ],
  ArraySize: 2
}
```

Data
```
[
  {
    ParamType: 'ARRAY',
    DataType: 1,
    Length: 15,
    Data: [ 'COL3 DATA', 'COL3 DATA' ]
  },
  {
    ParamType: 'ARRAY',
    DataType: 1,
    Length: 35,
    Data: [ 'COL4 DATA', 'COL4 DATA' ]
  },
  {
    ParamType: 'ARRAY',
    DataType: 1,
    Length: 250,
    Data: [
      'COL5 DATA',
      'COL5 DATA'
    ]
  },
  {
    ParamType: 'ARRAY',
    DataType: 1,
    Data: [ '2020-09-14 13:27:53', '2020-09-14 13:27:53' ]
  },
  { ParamType: 'ARRAY', DataType: 1, Data: [ 1, 1 ] },
  { ParamType: 'ARRAY', DataType: 1, Data: [ 1, 2 ] }
]
```

and here is the error we are seeing.

```
{
  "error":"[node-ibm_db] SQL_ERROR",
  "sqlcode":-99999,
  "message":"[IBM][CLI Driver] CLI0652W The execution of the query will not be atomic because the database server does not support atomic operations for non-insert queries. SQLSTATE=xxxxx",
  "state":"xxxxx"
}
```

**Comment by debrajo** [comment]
I'm also getting this error on the  conn.query()  with a where in ( <list>) 
When I use a query with the list filled in, it works successful 

```
var queryByCustNumFilled = "select CUST_NO, CUST_NAME from CUSTOMER WHERE CUST_NO IN ( '123456','456789','234567' ) WITH UR "
conn.query(queryByCustNumFilled, function (err, rows, sqlca)
{ .......
});
Success
```
when using queryOptions, it fails with atomic error 

```
var queryByCustNum = "select CUST_NO, CUST_NAME from CUSTOMER WHERE CUST_NO IN ( ? ) WITH UR "
let custList = ['123456','456789','234567']
var custArray = { ParamType: "ARRAY", DataType: 1, Data: custList, Length: 6 };
var queryOptions = {
    sql: queryByCustNum ,
    params: [custArray],
    ArraySize: custList.length
conn.query(queryOptions, function (err, result) { ...... }
};
Fails with 
{ [Error: [IBM][CLI Driver] CLI0652W  The execution of the query will not be atomic because the database server does not support atomic operations for non-insert queries. SQLSTATE=xxxxx]
  error: '[node-ibm_db] SQL_ERROR',
  sqlcode: -99999,
  message:
   '[IBM][CLI Driver] CLI0652W  The execution of the query will not be atomic because the database server does not support atomic operations for non-insert queries. SQLSTATE=xxxxx',
  state: 'xxxxx' }

```
My custList is dynamical based upon a previous query result. 
 "ibm_db": "^2.7.1",
And I'm connecting to a zOS DB

**Comment by bimalkjha** [comment]
@debrajo You are getting this warning as this feature is not supported by zOS server for non-insert statement. If you check the IBM documentation about CLI0652W [here](https://www.ibm.com/support/knowledgecenter/en/SSEPGG_11.5.0/com.ibm.db2.luw.messages.cli.doc/com.ibm.db2.luw.messages.cli.doc-gentopic1.html#cli0652w), it says to ignore this warning.
Please add `IgnoreWarnings=1` in your connection string and then try. Share the result here. Thanks.

**Comment by bimalkjha** [comment]
@siva-srini This warning comes against z/OS server only. I would suggest to use `IgnoreWarnings=1;` in connection string to avoid this error. It should work. Thanks.

**Comment by bimalkjha** [comment]
@siva-srini You can not have two values in a single field of column. So, you can not set an array for a single field of column. Fields should be set with single value in statement. Array can be used in insert statement only to insert multiple rows at once in a table. 
We have added a test file https://github.com/ibmdb/node-ibm_db/blob/master/test/test-sp-array.js to show how to pass an array to SP and insert the array into a table. Please refer it. Thanks.
