### ISSUE TITLE
Using db.openSync results in malloc error

### ISSUE THREAD

**Issue by TimonLukas** [ibmdb/node-ibm_db#697]
Hey all! We've been using this module for more than a year in one of our projects without any problem. Since a few weeks ago, executing `db.openSync` crashes the Node process on my machine with the following error:

```
node(65944,0x10f8135c0) malloc: *** error for object 0x7fff913dc8c0: pointer being freed was not allocated
node(65944,0x10f8135c0) malloc: *** set a breakpoint in malloc_error_break to debug
/bin/sh: line 1: 65944 Abort trap: 6
```

(the PID and memory addresses change between calls) This doesn't happen for colleagues of mine, making it difficult to figure out where the problem actually lies.

I've tried the following:
- Use different versions of Node
- Update the used versions of Node
- Use different versions of `ibm_db`
- Update to the newest version of `ibm_db`

I'm 100% certain that the problem is caused by the `db.openSync` call, but I can't figure out how to get around this. Any ideas?

Environment:
- IBM managed Mac with Mac OS 10.14.6 (18G1012)
- Node 10.22.0 (but also tried older 10.x releases, 12 and 14)
- DB2 is running on IBM Cloud

If you need additional info please reach out through this issue or through IBM Slack.

**Comment by bimalkjha** [comment]
@TimonLukas Is it possible to share some test program that reproduces this error?
I would request you to try below commands and then share the output. If you can figure out which line of code is throwing this malloc error from file under `ibm_db\src` directory, it would be great!
```
cd ....\ibm_db
npm install --debug
node test.js  > testout.txt
```
This would run ibm_db in debug mode and would print lot of logs on prompt so better to redirect output to a file.
To restore the previous behavior, you can execute `npm install` under ibm_db directory.
Thanks.

**Comment by bimalkjha** [comment]
Also, check the macos version of your colleagues. If it is not same as you and if possible, upgrade your os to 10.15.x

**Comment by TimonLukas** [comment]
> Is it possible to share some test program that reproduces this error?

This program triggers the error for me: https://github.com/TimonLukas/ibm_db-error-reproduction

> I would request you to try below commands and then share the output. If you can figure out which line of code is throwing this malloc error from file under ibm_db\src directory, it would be great!

The repo doesn't have a file `test.js`, instead I executed `npm run test`. Here is the output (sadly not really helpful because of the connection problems): https://gist.github.ibm.com/Timon-Lukas/b37c89eeb6ee16b7278c3e5e1736e5b3

> Also, check the macos version of your colleagues. If it is not same as you and if possible, upgrade your os to 10.15.x

My colleagues are already on 10.15.x, but I'd rather not update for now. If this persists we'll most likely just switch to Postgres instead.

**Comment by bimalkjha** [comment]
@TimonLukas `https://github.com/TimonLukas/ibm_db-error-reproduction` is using app.js, so you should run `node app.js > testout.txt` command after `npm install --debug`. `npm run test` will not give any useful info. Thanks.

**Comment by TimonLukas** [comment]
@bimalkjha Oh sorry, I thought I should execute tests directly in the `ibm_db` directory.

Here is the output: https://gist.github.ibm.com/Timon-Lukas/dc365abcbaaacdd92bc277b3cb1cf68a

I included both the test output as well as the actual console output without redirecting.

**Comment by bimalkjha** [comment]
Most probably it is due to use of MacOS 10.14. We have updated clidriver used by ibm_db to db2 v11.5.4.0 which requires macos 10.15.x or gcc >= 8.4.0.

**Comment by bimalkjha** [comment]
@TimonLukas In [app.js](https://github.com/TimonLukas/ibm_db-error-reproduction/blob/master/app.js), db.open() is called and not db.openSync(). But, in first post, you mentioned that issue is in db.openSync(). So, are you hitting it with both open() and openSync(0 APIs? Thanks.

**Comment by TimonLukas** [comment]
> Most probably it is due to use of MacOS 10.14. We have updated clidriver used by ibm_db to db2 v11.5.4.0 which requires macos 10.15.x or gcc >= 8.4.0.

Interesting, that would make sense. But shouldn't older versions continue to work then? Or are the drivers there updated as well? I'd argue that older versions should continue to work, it's annoying when a software package suddenly doesn't work on a system without any explicit version changes.

> @TimonLukas In [app.js](https://github.com/TimonLukas/ibm_db-error-reproduction/blob/master/app.js), db.open() is called and not db.openSync(). But, in first post, you mentioned that issue is in db.openSync(). So, are you hitting it with both open() and openSync(0 APIs? Thanks.

Sorry, I forgot to use `openSync` in the file. I just checked, `openSync` has the same behavior: https://gist.github.ibm.com/Timon-Lukas/5dbf5864a1ad0420412ac2d234d2e13f

**Comment by bimalkjha** [comment]
@TimonLukas Yes, older version should continue to work. But, you need to apply a small work-around for that as below:
```
1. Download https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64/macos64_odbc_cli.tar.gz
2. untar it, you'll get clidriver directory.
3. export IBM_DB_HOME=<full_path_of_clidriver>
4. npm install ibm_db
```
It should work as before. Thanks.
