### ISSUE TITLE
why do warnings generate an error an is there a way to prevent this behaviour

### ISSUE THREAD

**Issue by peterprib** [ibmdb/node-ibm_db#699]
Why is a warning telling you that your request to ignore if exists on create table treated as an error.  To what extent are SQL warnings handling in this way.  Is there an easy way of  discerning between the two without having to decode the message.

e.g.
CREATE TABLE IF NOT EXISTS 
causes the following if run twice

{"db2":"[IBM][CLI Driver][DB2/NT64] SQL4136W  Table or view \"TEST    \".\"SHARE\" already exists.\r\n"}

To what extend is this problem with warnings?  e.g does running an update a which updates no rows being +100 mean an error messages is raised?  Why isn't the sqlcode in  the error object to to facilitate easy of coding along.  Actually why not do the sensible thing and provide the SQLSTATE information and associated SQLCA data in the returned error object.

**Comment by bimalkjha** [comment]
@peterprib The query() API returns `sqlca` in 3rd argument of `callback (err, rows, sqlca)` function. sqlca contains sqlcode and sqlstate. You can check that. `test-basic-test.js` has example uses of sqlca. Also, it is documented [here](https://github.com/ibmdb/node-ibm_db/blob/master/APIDocumentation.md#-3-querysqlquery--bindingparameters-callback). Thanks.

**Comment by peterprib** [comment]
Thanks hadn't noticed this.  See it actually changes the format of err so assume this is to support legacy code when this was not available.   Be better still if a parameter was available on call to detail how to handle possible warning messages, either ignore or list of acceptable.

**Comment by peterprib** [comment]
Is there similar for prepare + execute as they will have similar problems.  Looked at documentation and can't spot if implemented.

**Comment by bimalkjha** [comment]
@peterprib Only query() returns sqlca as third argument of callback function. prepare+execute do not. Thanks.

**Comment by peterprib** [comment]
why not as they can get similar issues and for performance one is likely to use these calls.

**Comment by bimalkjha** [comment]
@peterprib `ibm_db` APIs will ignore warnings if you use `"IgnoreWarnings=1;"` in connection string. By default, it returns both warnings and errors. If you want to suppress specific warnings with known SQLSTATE numbers, you can use `"IgnoreWarnList=\"'01000', '01004','01504'\";"` in connection string.
These keywords are documented here: 
https://www.ibm.com/support/knowledgecenter/SSEPGG_11.5.0/com.ibm.db2.luw.apdv.cli.doc/doc/r0008796.html
https://www.ibm.com/support/knowledgecenter/SSEPGG_11.5.0/com.ibm.db2.luw.apdv.cli.doc/doc/r0008797.html
Thanks.
