### ISSUE TITLE
.Pipe() or stream() support

### ISSUE THREAD

**Issue by thomasbuchis** [ibmdb/node-ibm_db#70]
I didn't find it in the documentation, but it could be useful if pipe or streaming support is available for big queries that need to be writed on files.

**Comment by rhtpandeyIBM** [comment]
Hi @thomasbuchis can you describe your problem statement more specifically. If possible can you share what kind of queries and files you are talking about. thanks

**Comment by gmsewell6** [comment]
+1. definitely looking for the ability to stream query results.

eg. something like
```
// table 'foo' has 2 million rows & 25 columns
var resultShim = conn.query('select * from foo')
```

**Comment by kathywang** [comment]
I am also looking for the large query results stream and/or pip solution to improve performance. @thomasbuchis @rhtpandeyIN @gmsewell6 , have you guys get a good solution for the large data query? 
Would you please share your experience if you have idea?

**Comment by gildean** [comment]
I did implement a readable stream on top of the undocumented queryResults method, you can check the pr here: #184

**Comment by bimalkjha** [comment]
@thomasbuchis stream support has been added in latest commit. Please pull the latest code from git and verify. Thanks.
