### ISSUE TITLE
Error installing ibm-db with a new version 2.7.1

### ISSUE THREAD

**Issue by Namratasai1** [ibmdb/node-ibm_db#700]
We are facing an issue that when we are installing the dependencies,  ibm-db installed successfully, But we are facing some issue

ibm_db@2.7.1 install C:\Users\AchantaSai\Pictures\sdu-api-test-master\sdu-api-test-master\node_modules\ibm_db
> node installer/driverInstall.js

platform =  win32 , arch =  x64 , node.js version =  v12.16.1
Downloading DB2 ODBC CLI Driver from https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/ntx64_odbc_cli.zip...

100.00% | 24911373 bytes downloaded out of 24911373 bytes.

****************************************
You are downloading a package which includes the Node.js module for IBM DB2/Informix.  The module is licensed under the Apache License 2.0. The package also includes IBM ODBC and CLI Driver from IBM, which is automatically downloaded as the node module is installed on your system/device. The license agreement to the IBM ODBC and CLI Driver is available in undefined   Check for additional dependencies, which may come with their own license agreement(s). Your use of the components of the package and dependencies constitutes your acceptance of their respective license agreements. If you do not accept the terms of any license agreement(s), then delete the relevant component(s) from your device.
****************************************

Downloading and extraction of DB2 ODBC CLI Driver completed successfully... 

C:\Users\AchantaSai\Pictures\sdu-api-test-master\sdu-api-test-master\node_modules\ibm_db>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure build  --IS_DOWNLOADED=true --IBM_DB_HOME=$IBM_DB_HOME )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" configure build  --IS_DOWNLOADED=true --IBM_DB_HOME=$IBM_DB_HOME )

Error: Command failed: node-gyp configure build  --IS_DOWNLOADED=true --IBM_DB_HOME=$IBM_DB_HOME
gyp ERR! find Python
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - "python" is not in PATH or produced an error
gyp ERR! find Python checking if "python2" can be used
gyp ERR! find Python - "python2" is not in PATH or produced an error
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - "python3" is not in PATH or produced an error
gyp ERR! find Python checking if the py launcher can be used to find Python 2
gyp ERR! find Python - "py.exe" is not in PATH or produced an error
gyp ERR! find Python checking if Python is C:\Python27\python.exe
gyp ERR! find Python - "C:\Python27\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Python37\python.exe
gyp ERR! find Python - "C:\Python37\python.exe" could not be run
gyp ERR! find Python
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="C:\Path\To\python.exe"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python "C:\Path\To\python.exe"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:307:47)
gyp ERR! stack     at PythonFinder.runChecks (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:136:21)    
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:225:16)  
gyp ERR! stack     at PythonFinder.execFileCallback (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:271:16)
gyp ERR! stack     at exithandler (child_process.js:310:5)
gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:322:5)
gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
gyp ERR! stack     at onErrorNT (internal/child_process.js:469:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:84:21)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "build" "--IS_DOWNLOADED=true" "--IBM_DB_HOME=$IBM_DB_HOME"
gyp ERR! cwd C:\Users\AchantaSai\Pictures\sdu-api-test-master\sdu-api-test-master\node_modules\ibm_db
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:311:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node-gyp configure build  --IS_DOWNLOADED=true --IBM_DB_HOME=$IBM_DB_HOME'
}

node-gyp build process failed!

Proceeding with Pre-compiled Binary Installation.

===================================
node-ibm_db installed successfully!
===================================

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

PS C:\Users\AchantaSai\Pictures\sdu-api-test-master\sdu-api-test-master> node app.js
server starting on http://localhost:6001                                                                                                   server starting on http
PS C:\Users\AchantaSai\Pictures\sdu-api-test-master\sdu-api-test-master> npm i      
npm WARN sdu-backend@1.0.0 No repository field.

audited 177 packages in 2.797s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

Can you help us on this issue

**Comment by Namratasai1** [comment]
@bimalkjha Can you help us on this issue

**Comment by Namratasai1** [comment]
Can anyone please help us on this issue

**Comment by bimalkjha** [comment]
@Namratasai1 As long as you are getting "node-ibm_db installed successfully!" message, it installed successfully. In the pasted output, we do not see any issue and you can use this installed ibm_db.
The error is because python2.7 is not installed in the system, so ibm_db is using pre-compiled binary on Windows. You can ignore this error and proceed. Thanks.

**Comment by Namratasai1** [comment]
@bimalkjha when we are trying to login, we are facing some issue like 

  |  
-- | --
error | "[node-ibm_db] SQL_ERROR"
sqlcode | -1598
message | "[IBM][CLI  Driver] SQL1598N  An attempt to connect to the database server failed  because of a licensing problem.  SQLSTATE=42968\n"
state | "42968"

So, I thought this is because of this error. Can you help us on this

**Comment by bimalkjha** [comment]
@Namratasai1 You need to get db2connect license and copy it under ibm_db as documented here: https://github.com/ibmdb/node-ibm_db#for-zos-and-iseries-connectivity

**Comment by Namratasai1** [comment]
@bimalkjha Hello,

We are have that license file in the folder on which you mentioned,

project>node_modules>ibm_db>installer>cli driver>license>db2consv_zs.lic

This is inside that license file

[LicenseCertificate]
CheckSum=5FE2B64874CAA0AC4A6BF7C433370766
TimeStamp=1455522757
PasswordVersion=4
VendorName=IBM Toronto Lab
VendorPassword=7v8p4fq2dtfpc
VendorID=5fbee0ee6feb.02.09.15.0f.48.00.00.00
ProductName=DB2 Connect Unlim Ed zSeries
ProductID=1411
ProductVersion=11.1
ProductPassword=ez62rhyaap7seh3yaf2ssat5
ProductAnnotation=12;(_zs)
LicenseStyle=nodelocked
LicenseStartDate=02/15/2016
LicenseDuration=7991
LicenseEndDate=12/31/2037
LicenseCount=1
MultiUseRules=
RegistrationLevel=3
TryAndBuy=No
SoftStop=No
TargetType=ANY
TargetTypeName=Open Target
TargetID=ANY
ExtendedTargetType=
ExtendedTargetID=
DerivedLicenseStyle=
DerivedLicenseStartDate=
DerivedLicenseEndDate=
DerivedLicenseAggregateDuration=
SerialNumber=
Upgrade=No
CapacityType=
Bundle=No
InstallProgram=
AdditionalLicenseData=
CustomAttribute1=No
CustomAttribute2=No
CustomAttribute3=No
SubCapacityEligibleProduct=No
MaxOfflinePeriod=


Can you help us on this

**Comment by Namratasai1** [comment]
@bimalkjha ,

When we are trying to login, we are getting 2 errors,

1)  This one


error | "[node-ibm_db] SQL_ERROR"
-- | --
sqlcode | -30081
message | "[IBM][CLI  Driver] SQL30081N  A communication error has been detected.  Communication protocol being used: \"TCP/IP\".  Communication API being  used: \"SOCKETS\".  Location where the error was detected:  \"169.53.60.113\".  Communication function detecting the error:  \"recv\".  Protocol specific error code(s): \"*\", \"*\", \"0\".   SQLSTATE=08001\n"
state | "08001"

2) and second one is licensing problem

Can you help us on this.

**Comment by Namratasai1** [comment]
@bimalkjha Can you help us on this

**Comment by bimalkjha** [comment]
@Namratasai1 Your license file is of db2 v11.1. You can see the Product Version in your license file is 11.1. You need to get a license file of db2 v11.5. Then it will work. Thanks.

**Comment by Namratasai1** [comment]
@bimalkjha Thank you. I will use the updated version of that file and will let you know

**Comment by Namratasai1** [comment]
@bimalkjha Hello,

The license file got updated and the license file issue got resolved.

But we are facing this issue.


error | "[node-ibm_db] SQL_ERROR"
-- | --
sqlcode | -30081
message | "[IBM][CLI  Driver] SQL30081N  A communication error has been detected.  Communication protocol being used: "TCP/IP".  Communication API being  used: "SOCKETS".  Location where the error was detected:  "169.53.60.113".  Communication function detecting the error:  "recv".  Protocol specific error code(s): "", "", "0".   SQLSTATE=08001\n"
state | "08001"

Can you help us on this

**Comment by Namratasai1** [comment]
We are facing this issue also after trying to login,

"[IBM][CLI Driver] SQL30082N  Security processing failed with reason \"24\" (\"USERNAME AND/OR PASSWORD INVALID\").  SQLSTATE=08001\n"
​
Can you help us on this

**Comment by Namratasai1** [comment]
@bimalkjha  Can you help us on this

**Comment by bimalkjha** [comment]
@Namratasai1 It seems your server or network is slow and client is unable to get connection within 30seconds which is the default connection timeout set in odbc.js file and hence SQL30081N error.
You can increase the timeout value by passing an option in open() function as below:
```
ibmdb.open(connStr, { connectTimeout : 300}, function (err, connection) {
```
`connectTimeout` is mentioned in documentation [here](https://github.com/ibmdb/node-ibm_db/blob/master/APIDocumentation.md#-2-opensyncconnectionstring-options). Also, you can grep for it under `ibm_db\test` directory and can see many test files are using it. Thanks.

**Comment by bimalkjha** [comment]
@Namratasai1 Is it working now? May I close the issue? Thanks.

**Comment by Namratasai1** [comment]
@bimalkjha I still need to work on that and will let you know. Till then please don't close this issue.

Thanks,
Namrata

**Comment by Namratasai1** [comment]
@bimalkjha Hello,

I tried by adding that open function. But still I am facing the same issue.

Can you help us to resolve this issue

**Comment by Namratasai1** [comment]
@bimalkjha We are not getting any data when we are running a query.

{…}
​
error: "[IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: \"TCP/IP\".  Communication API being used: \"SOCKETS\".  Location where the error was detected: \"169.53.60.113\".  Communication function detecting the error: \"recv\".  Protocol specific error code(s): \"*\", \"*\", \"0\".  SQLSTATE=08001\n"
​
Can you help us on this

Thanks

**Comment by madsteer** [comment]
> @Namratasai1 Your license file is of db2 v11.1. You can see the Product Version in your license file is 11.1. You need to get a license file of db2 v11.5. Then it will work. Thanks.

Does the new `ibm-db` driver require a V11.5 license file or how did you know that you needed a new license file?  My license file has `ProductVersion=11.1` in it, but I'm not seeing anything in the error messages to suggest it needs to be 11.5  Thanks,

**Comment by Namratasai1** [comment]
@madsteer 

Hello,

Yes, I updated my license file from 11.1 to 11.5. Now it is working fine.

You can close this issue

Thanks,
Namrata

**Comment by madsteer** [comment]
@Namratasai1 how did you do change the version in the license file?  I got this file from another area.  They don't necessarily know anything about NodeJS.  Not sure they will understand about this version.

**Comment by madsteer** [comment]
my db2 area says they are currently rolling out 11.5, but it's not done yet.  am I supposed to use an older version of ibm-db until 11.5 is deployed?

**Comment by Namratasai1** [comment]
@madsteer 

Hello,

Yeah, actually i got file by some one in our team and i replaced that. After updating it to new version. It worked fine.

I think you cannot use 11.1 version now may be because of upgrade. 

Thanks,
Namrata

**Comment by madsteer** [comment]
I've backed my `ibm_db` version all the way back down to 2.5.3 and I still get this licensing error.  Is the version tied to the node module or the version of the value behind the `IBM_DB_INSTALLER_URL=**` (in my case macos64_odbc_cli.tar.gz) or something else?  My company is not using 11.5 yet, so I'm not sure why I'm requiring a new license file

**Comment by Namratasai1** [comment]
@madsteer 

Hello,

I am using the version for ibm_db is 2.7.1.

**Comment by madsteer** [comment]
yeah.  not sure how I got myself into this mess, but I've tried most versions from 2.5.3 to 2.7.1 and I can't get back to a version that works with the 11.1 license file.  this was all working before I tried to update my nodeJS and ibm_node versions.

**Comment by madsteer** [comment]
I was able to get an 11.5 license file and it also fixed my issues.  I would like to understand what that version is tied too.  once I started upgrading things I had trouble getting back to a working state using the 11.1 license file.  We are not on 11.5 yet.

**Comment by suzck** [comment]
I was having this issue for a week, just figured it out talking to one of my co-workers. Between 2.7.0 and 2.7.1 they changed the minimum requirement for the gcc compiler. I rolled back to 2.7.0 and everything works as expected again. Not my favorite solution but it works for now.

**Comment by bimalkjha** [comment]
@suzck This gcc compiler requirement is independent of version of ibm_db. So, if 2.7.0 is working for you, 2.7.1 will too work. You need to have a fresh installation. If still issue is there, then please open a new issue with full output of `npm install ibm_db` command and the error that you are hitting. Thanks.
