### ISSUE TITLE
Bulk Insertion - Characters Omission 

### ISSUE THREAD

**Issue by Akshay9790** [ibmdb/node-ibm_db#701]
Hi,

I am trying to insert bulk data using ibm_db 2.7.1 node module into DB2 using following approach -

  var param1 = {ParamType:"ARRAY", DataType:1, Data:[null,5,6,7,8]};
  var param2 = {ParamType:"ARRAY", DataType:"DOUBLE", Data:[4.1,null,6.14,7,8.3]};
  var param3 = {ParamType:"ARRAY", DataType:1, Data:[0,1,null,false,true]};
  var param4 = {ParamType:"ARRAY", DataType:1, Data:["ABCDEF","QWERTY",null,"TYUIO","HJLKG"]};
  var queryOptions = {sql:"insert into arrtab values (?, ?, ?, ?)", 
                      params: [param1, param2, param3, param4],
                      noResults: true,
                      ArraySize:5};

 conn.queryResult(queryOptions, CALLBACK_METHOD);

Data gets successfully inserted with this approach. But due to some reason, data in some columns is getting omitted and only few characters are stored. This is happening randomly. 
I tried debugging this, and from the code I am passing the correct string only.

For e.g. ->
If I pass "ABCDEF" as one of the column value, it gets stored as "ABC" sometimes. 

Could you please look into this? or point out what I am missing over here.

**Comment by Akshay9790** [comment]
@bimaljha  Could you please look into this issue.

**Comment by bimalkjha** [comment]
@Akshay9790 We can see below text in query() and querySync() API [documentation](https://github.com/ibmdb/node-ibm_db/blob/master/APIDocumentation.md#-3-querysqlquery--bindingparameters-callback) example for Array Insert:
```
  var namearr = ["Row 10", "Row 203456", "Row 30", "Row 40", "Last Row"];

  var param4 = {ParamType:"ARRAY", DataType:1, Data:namearr, Length:8};
  // *** Use "Length: <maxDataLen>" in param Object for unequal size of data.
  // Default value is the length of first member of Array.
```
So, for character data array, where size of each character data is unequal, pass `Length` value in object to mention the maximum length of character values in char array. Else, any data which has more characters than the first element of array will get truncated. Basically, value of `Length` should be the column size in table. You can modify your `param4` as below and it should work:
```
var param4 = {ParamType:"ARRAY", DataType:1, Data:["ABCDEF","QWERTY",null,"TYUIO","HJLKG"], Length:6};
```
You can refer [ibm_db/test/test-array-insert.js](https://github.com/ibmdb/node-ibm_db/blob/master/test/test-array-insert.js) for example. Thanks.

**Comment by Akshay9790** [comment]
Thanks @bimalkjha for quick response. However I have a follow up question, can we give max length as same for all the columns. 
For e.g. -> 
I have 4 columns in DB table.
Column A - VARCHAR(20)
Column B - INT
Column C - VARCHAR(32000)
Column D - DATETIME

So I will need to pass 4 array to DB. Can I use Length as 32000 for all the 4 array (param1, param2, param3, param4)?
Will using the same length value have any performance impact?

**Comment by bimalkjha** [comment]
@Akshay9790 Length is the size of individual column and not the length of full array. For fixed length datatypes like `int`, `Length` is not required.
Since, only column C is of 32000 length so use this value only for this column, not for other column. For array of Column A, `Length` should be used as 20 only.
Note that the ibm_db need to allocate memory for the `Length` x array size to pass data from JS to C and vice-versa. Having large Length value may cause problem if system is unable to allocate that much memory or memory is not available to allocate.
Having big Length value will affect performance too.
So, use `Length` for every array individually only for Character types array. Thanks.

**Comment by Akshay9790** [comment]
Thanks @bimalkjha for clarifying my doubts. Since it's not an issue, I am closing this ticket.
