### ISSUE TITLE
Not able to connect to IBM db2 

### ISSUE THREAD

**Issue by tanvi-sambari** [ibmdb/node-ibm_db#703]
I get the following error when I try to connect to DB2 from my application:
DATABASE=BLUDB;HOSTNAME=db2whoc-flex-hlmokby.services.dal.bluemix.net;UID=onbrdprtal;PWD=xxxxxxx;PORT=50001;PROTOCOL=TCPIP;Security=SSL;
[16:41:14] [ERROR]      Error connecting to DB2: [IBM][CLI Driver] SQL1042C  An unexpected system error occurred.  SQLSTATE=58004

[16:41:14] [ERROR]      Error authenticating user: [IBM][CLI Driver] SQL1042C  An unexpected system error occurred.  SQLSTATE=58004

[16:41:14] [INFO]       DB2 connection closed (due to a query execution error)

**Comment by bimalkjha** [comment]
@tanvi-sambari It looks your system has another version of db2 client installed and hence it is causing problem. Same connection string works fine for me.
Please share the output of below commands:
```
node -v
npm ls ibm_db
db2cli validate
cd ibm_db\installer
source setenv.sh
db2cli validate
```
If you are not using ibm_db@2.7.1, then I would suggest to upgrade the ibm_db and use latest version. Latest version should fix this issue. Thanks.

**Comment by tanvi-sambari** [comment]
**node -v :** v12.18.2
**npm ls ibm_db :** `-- (empty)
**db2cli validate:** 'db2cli' is not recognized as an internal or external command,
operable program or batch file.
**cd ibm_db\installer:** 'source' is not recognized as an internal or external command,
operable program or batch file.
source setenv.sh
**db2cli validate**:'db2cli' is not recognized as an internal or external command,
operable program or batch file.

**Comment by bimalkjha** [comment]
Issue got fixed after following below steps:
1. open windows command prompt and run below commands.
2. cd D:\IBM DBG\Offering-next\offering-next
3. npm uninstall ibm_db
4. npm install ibm_db@2.7.1

The system had older version of gskit library installed and ibm_db v2.6.1 was installed.
