### ISSUE TITLE
Array Insert unable to handle empty strings after fix for #679

### ISSUE THREAD

**Issue by lucaskuperman** [ibmdb/node-ibm_db#706]
Hello, after fix [#679](https://github.com/ibmdb/node-ibm_db/issues/679) was released in v2.7.1, now the array insert does not properly handle empty strings (working fine in v2.7.0)

`params: [{ParamType:"ARRAY", DataType:1, Data: ["","Hello"], Length:5}]` 
Result: Junk characters inserted in column 1 

`params: [{ParamType:"ARRAY", DataType:1, Data: ["Hello",""], Length:5}]` 
Result: Junk characters inserted in column 2

Please advise if there's something I'm doing wrong

**Comment by bimalkjha** [comment]
@lucaskuperman I enhanced `test\test-array-insert.js` to insert same data as you shared. ibm_db is able to insert the data and select too without any issue. You can also copy the latest test file from git and run it after updating database connection info in `config.testConnectionStrings.json` file.
If this test file fails for you, please share the complete output of this test file. Also, share the name of the Operating System on which you have installed `ibm_db`. Thanks.
