### ISSUE TITLE
Cannot connect to db2 hostname that exceeds 70 characters.

### ISSUE THREAD

**Issue by 1000aki** [ibmdb/node-ibm_db#707]
Hi all, We use ibm_db to connect to Db2 on cloud instance.

Last week, Our db2 on cloud instance has upgraded to new instance and hostname has changed.
So we switched dsn in our node app to new instance.
After switching dsn, our app cannot connect new db2 instance and get following messages.

The hostname is truncated in the first 70 characters.
Full hostname is "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx.xxxxxxxxxxxxxxxxxxxx.databases.appdomain.cloud".

This only happens on Linux, and does not happens in Windows and Mac.
We have tested by running same app on each os.

```
{ [Error: [IBM][CLI Driver] SQL1336N  The remote host "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx.xxxxxxxxxxxxxxxxxxxx.databases.ap" was not found.  SQLSTATE=08001
]
  error: '[node-ibm_db] SQL_ERROR',
  sqlcode: -1336,
  message:
   '[IBM][CLI Driver] SQL1336N  The remote host "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx.xxxxxxxxxxxxxxxxxxxx.databases.ap" was not found.  SQLSTATE=08001\n',
  state: '08001' }
```

- Client environment details:
    - Red Hat Enterprise Linux Server 7.8 (Maipo)
    - Node v10.21.0 (but also tried older 7.x releases, 8 and 12)
    - ibm_db 2.7.1

- Server environment details:	
    - Db2 on Cloud Standard plan, Db2 v11.5

**Comment by bimalkjha** [comment]
@1000aki The hostname is truncated only in the error message as there is limitation with the message to show only 70 chars. Driver is picking the full host name and I verified it on linux with similar cloud instance and ibm_db is working fine with long host name too.
So, we need to see why are you getting SQL1336N? Could you replace the long hostname with the ip address of this system in connection string and try? If it still fails, I would suggest to update connection string in `ibm_db\installer\testODBCConnection.sh` script for `db2cli validate` command and execute the script. zip all generated files and share here along with complete output of the script. 
The validate command would connect to TCPIP port only and not to SSL port if you are trying to connect to SSL port. Let me know if  you are trying the SSL connection to Db2 on cloud. Thanks.
