### ISSUE TITLE
Unable to connect to ibm db2 instance

### ISSUE THREAD

**Issue by sam-almighty** [ibmdb/node-ibm_db#708]
I created an instance of IBM Cloud DB2 standard (xxxxxd-xxxxx-xxxx-xxxx-zzzzzzzz.databases.appdomain.cloud), when I try connecting to it using the ibm_db node app it fails to connect to the same. I am able to connect with the same code sample to another older instance of db2, so there are no issues in the code. 

I do not see any error logs as well when it fails to connect to the new instance.

Here's the sample i am trying for my testing https://github.com/IBM-Cloud/dashdb-nodejs-helloworld

**Comment by sam-almighty** [comment]
We are able to connect using the Java client, however, the node client still fails. Can someone please help?

**Comment by bimalkjha** [comment]
@sam-almighty Please update the connection info in `db2cli validate` command in `ibm_db\installer\testODBCConnection.sh` file at line number 29 and run this script. Please share the output of this script and generated 1.* files for investigation.

**Comment by bimalkjha** [comment]
For connection on SSL port of Db2 in Cloud, we need to use "Security=SSL" in connection string. Thanks.

**Comment by sam-almighty** [comment]
@bimaljha Thank you. That worked we are now able to connect with the change suggested.
