### ISSUE TITLE
After a while my node program crashes with an error from src/odbc.cpp:614

### ISSUE THREAD

**Issue by rws-github** [ibmdb/node-ibm_db#71]
node: ../src/odbc.cpp:614: static v8::Handle<v8::Value> ODBC::GetColumnValue(SQLHSTMT, Column, uint16_t*, int): Assertion `ret != -2' failed.

I have 2 node processes on the same VM connected to the same database and they are both suffering from crashes seemingly randomly after a while.

**Comment by bimalkjha** [comment]
@rws-github What is your node version and ibm_db version. Please share the platform name and any small test program to repro the issue. Thanks.

**Comment by bimalkjha** [comment]
At first glance, the crash happened because the statement handle passed to ODBC::GetColumnValue() is an invalid handle. But, why any invalid handle got passed to ODBC::GetColumnValue() that requires investigation. thanks.

**Comment by bimalkjha** [comment]
@rws-github Is it possible to share any repro script?

**Comment by rws-github** [comment]
I haven't reproduced it in non-proprietary code. I've switched the database to Postgresql and we are experiencing and error trying to store a null character in a string. Could something like that cause this failure?

**Comment by rws-github** [comment]
Inserting a null character did not seem to cause any problem. This is no longer an active issue for us. Thank you for the responses.

**Comment by rhtpandeyIN** [comment]
@rws-github Thanks for your feedback.
