### ISSUE TITLE
How do I get dsn when running Nodejs code in Cloud Functions?

### ISSUE THREAD

**Issue by cloud8lz** [ibmdb/node-ibm_db#712]

**Comment by cloud8lz** [comment]
This code below used to work

  function main(params) {
    dsn=params.__bx_creds[Object.keys(params.__bx_creds)[0]].dsn;
    return db2Setup(dsn, params.mode);
  }

However, dsn is "undefined" after the above code.

Thank you

**Comment by bimalkjha** [comment]
@cloud8lz I do not see ibm_db is involved here. Its problem with your node.js code. Please debug your code to get the solution. Thanks.
