### ISSUE TITLE
Supported Db2 odbc driver version

### ISSUE THREAD

**Issue by trsvax** [ibmdb/node-ibm_db#713]
Perhaps I missed it but I don't see a list of the supported driver versions. Would it be possible to add that to the documentation?

Thanks

**Comment by bimalkjha** [comment]
@trsvax We have documented the download links for clidriver here: https://github.com/ibmdb/node-ibm_db#-download-clidriver-based-on-your-platform--architecture-from-the-below-ibm-hosted-url

There is no requirement to install Db2 odbc driver before installing the node-ibm_db. ibm_db downloads and install minimized version of clidriver automatically during installation and use it. These clidriver is repackaged for open source drivers use with minimum size.

ibm_db also works with preinstalled Db2 client. In that case, you need to set environment variable `IBM_DB_HOME=<full_path_of_install_dir>` and then run `npm install ibm_db`. In this case, ibm_db will not download clidriver but use the db2client pointed by `IBM_DB_HOME`.

Note that the minimum supported Db2 versions by IBM as of now is Db2 V10.5. So, ibm_db works with all supported versions of Db2 Client, Db2 Server or dsdriver installations. ibm_db do not work if you download and install IBM ODBC and CLI driver from fix central or passport advantage.

Hope, it clarifies your doubt. If you want anything to be updated in ibm_db documentation, please let us know. Thanks.

**Comment by trsvax** [comment]
Thanks, 

That's exactly what I needed. Perhaps you could add this into the Prerequisites

ibm_db works with all supported versions of Db2 Client

**Comment by bimalkjha** [comment]
Updated doc with info. Thanks.
