### ISSUE TITLE
was the default query optimization used by the ibm_db package changed between 2.6.0 and 2.6.1 ?

### ISSUE THREAD

**Issue by chris-ratcliffe** [ibmdb/node-ibm_db#714]
We have a few complex queries in our node.js application, and when I upgrade to a version at or above 2.6.1, we start to see sql437, reason code 1 errors when trying to execute those queries.  2.6.0 is fine.

**Comment by bimalkjha** [comment]
@chris-ratcliffe Use "IgnoreWarnings=1" in connection string to avoid the sql437w. Thanks.

**Comment by chris-ratcliffe** [comment]
Thanks.
