### ISSUE TITLE
Convert the library to support Promises for all methods.

### ISSUE THREAD

**Issue by vchouhan** [ibmdb/node-ibm_db#715]
Currently, some of the code base uses callbacks and some promises and it is hard to write clean code around Promises and Callbacks. It would be better to convert the library with Promises so we can leverage Async/Await rather than having to write code with callbacks and querySync and query.
E.g.
1. Pool
2. Transactions
3. Prepare and Execute

**Comment by huineng** [comment]
i second this , i used ibm_db for many many years, but i guess it's now the last one i have with callbacks.

**Comment by bimalkjha** [comment]
There are few APIs which do not return Promise. So, we kept it open to address those gaps and close it. Thanks.

**Comment by bimalkjha** [comment]
@vchouhan This support is added in ibm_db@3.0.0. Please refer test file https://github.com/ibmdb/node-ibm_db/blob/master/test/test-asyc-await.js to see the usage. Thanks.
