### ISSUE TITLE
Inserting BLOB from Stored Procedure

### ISSUE THREAD

**Issue by Yusuf023** [ibmdb/node-ibm_db#716]
I've to store a file which can be an image or pdf into a table of size up to 5 MB. 
To do that, I've created the column as data type BLOB. I did not give any size which initialized the column with size 1048576.
On my server, I'm getting the file as a base64 String or as a Buffer. 
I need to use a Stored Procedure for the insertion because there's additional logic there.
In the stored procedure, I'm expecting a few other values and the BLOB value which is then inserted into the table. 
I am using the latest version of ibm_db i.e. 2.7.1. Since node js doesn't have a primitive blob data type, I tried the following methods and got the corresponding error:
Calling the Stored Procedure with base 64 string datatype for the variable expecting blob:
[Error: [IBM][CLI Driver][DB2/LINUXX8664] SQL0102N  The string constant beginning with "'data:application/pdf;base64,JVBERi0xLjMKJbrfrOAKMyAllIG9iago8PC9UeXBlI" is too long.  SQLSTATE=54002]
   error: '[node-ibm_db] SQL_ERROR',
   sqlcode: -102,
   message:
    '[IBM][CLI Driver][DB2/LINUXX8664] SQL0102N  The string constant beginning with "\'data:application/pdf;base64,JVBERi0xLjMKJbrfrOAKMyAllIG9iago8PC9UeXBlI" is too long.  SQLSTATE=54002\r\n',
   state: '54002'

Calling the Stored Procedure with buffer datatype for the variable expecting blob:
[Error: [IBM][CLI Driver] CLI0118E  Invalid SQL syntax. SQLSTATE=37000]
   error: '[node-ibm_db] SQL_ERROR',
   sqlcode: -99999,
   message:
    '[IBM][CLI Driver] CLI0118E  Invalid SQL syntax. SQLSTATE=37000',
   state: '37000'

Please help as to how should I be sending the above-mentioned data types to the stored procedure which is expecting BLOB. Alternatively, would BLOB be the correct data type to be storing these values?
@bimalkjha Can you please look into this?

**Comment by bimalkjha** [comment]
@Yusuf023 yes, BLOB would be the correct data type for storing binary file. Could you please share your SP definition and if possible, modify test/test-sp*.js test file to reproduce the problem? If you can share modified repro file, it would be good help to fine the root cause. Thanks.

**Comment by Yusuf023** [comment]
@bimaljha 
Thanks for confirming that.
My SP definition looks something like this:

CREATE OR REPLACE PROCEDURE ABC.ATTACHMENT_INSERT (
		IN pATTACHMENT_NAME VARCHAR(256 OCTETS),
		IN pATTACHMENT_VALUE BLOB, 		
		IN pCREATE_DATE TIMESTAMP)

And the insert statement is:
INSERT INTO ABC.ATTACHMENT
    (ATTACHMENT_NAME, ATTACHMENT_VALUE, CREATE_DATE) VALUES(pATTACHMENT_NAME, pATTACHMENT_VALUE, pCREATE_DATE);

And sure, I'll try to share a modified repro file in some time. Thanks.

**Comment by Yusuf023** [comment]
I'll also like to add that I tried storing the req.file which I receive upon sending the file as a formData from my client and using multer as a middleware.  Doing this isn't failing but the data that is going in the table is just "[Object Object]" in HEX.

**Comment by bimalkjha** [comment]
Use data.toString() to convert object to string and then pass to ibm_db api. Thanks.

**Comment by Yusuf023** [comment]
to String was throwing an exception. I am storing the base 64 Data URL string in a CLOB data type and it is working fine. Thanks.
