### ISSUE TITLE
result.fetchAllSync() calls odbc.cbQuery which throws uncaught SQL0904N 

### ISSUE THREAD

**Issue by debrajo** [ibmdb/node-ibm_db#718]
I have a node.js web service that queries  zOS tables and sometimes, when host batch jobs are running, the jobs take the db2 resource offine .   I have the following code pattern: 

```
return new Promise((resolve, reject) => {
try {
    ibmdb.open(iwConnString, function (err, conn) {
        if (err) {
            //could not connect for some reason
            console.log(err);
            conn.closeSync(function (err) { console.logConnection Closed."); });;
            reject(err)
        }
        conn.queryResult(queryByCustNumSub, function (err, result) {
            if (err) {
                //could not connect for some reason
                conn.closeSync()
                reject(err)
            }
            else {
                let jsonRtn = { colNames: [], resultSet: [] };
                jsonRtn.colNames = result.getColumnNamesSync()
                jsonRtn.resultSet = result.fetchAllSync()
                result.closeSync(); // Must call in application.
                conn.closeSync()
                resolve(jsonRtn)
            }
        });
    });
} catch (err) {
    console.logFatal error')
    console.log(err.message);
    reject('Error during setup: ${err} ')
}
});
```
When the jobs takes the tables off-line, the node.js server throws the following error and exits back to OS
```
....\finiwReports.js:591
   jsonRtn.resultSet = result.fetchAllSync()
                                                       ^
  Error: [IBM][CLI Driver][DB2] SQL0904N  Unsuccessful execution caused by an unavailable resource.  Reason code: "00C90081", type of resource: "00000200", and resource name: "WGFDUA1 .WGFSUA1".  SQLSTATE=57011

    at finiwReports.js:591:56
    at cbQuery (....\node_modules\ibm_db\lib\odbc.js:717:51)
```
Other, service calls, which use  `results.fetchAll({ fetchMode: 4 }, function (err, data, colcount)`  and the err is returned to be checked. 

Suggestions on how to add the check?

**Comment by debrajo** [comment]
<sigh> 
After writing up the issue and posting it.. the now obvious solution is to rewrite result.fetchAllSync() to results.fetchAll( ... ) .  Which I will do and try to test/validate the next jobs runs (which is bi-weekly)  
But I still think odbc.js should gracefully catch that and keep on running

**Comment by bimalkjha** [comment]
@debrajo You may use try-catch to catch the error and check:
```
try {
  jsonRtn.resultSet = result.fetchAllSync();
} catch (e) { console.log(e); }
```
Thanks.

**Comment by debrajo** [comment]
Would it need a 2nd try catch surrounding just the fetchAllSync() ?    the entire  ibmdb call was already surrounded by try/catch

**Comment by bimalkjha** [comment]
@debrajo I think the outer try-catch will not catch the exception inside callback function. The callback function will crash.
Better to modify the code and verify that suggested try-catch solves the problem or not. Thanks.

**Comment by debrajo** [comment]
Yes, thank you.  I plan to do that. 
Thanks for your suggestion.  I'm closing the issue
