### ISSUE TITLE
Support URI-like connection string

### ISSUE THREAD

**Issue by data-henrik** [ibmdb/node-ibm_db#719]
Db2 on Cloud switched to a new credential structure. It no longer includes DSN settings, see https://cloud.ibm.com/docs/Db2onCloud?topic=Db2onCloud-connect_options

Support URI-like connection strings that allow to directly consume from the provided credentials.

**Comment by bimalkjha** [comment]
@data-henrik I think you are taking about below plan:
**Enterprise and Standard plans**
The following VCAP Services json file can be used to make connections to your Enterprise and Standard plans database instances:

{
  "apikey": "<apikey>",
  "connection": {
    "cli": {
      "arguments": [
        [
          "-u",
          "ipa8emxc",
          "-p",
          "e2haTt1FJ7m3UQXY",
          "--ssl",
          "--sslCAFile",
          "2ac5a4d3-1307-40f5-99a4-043e278fb084",
          "--authenticationDatabase",
          "admin",
          "--host",
          "a1d53ce7-166c-42d1-af26-7809dexxxxxx.yyyyyy.databases.appdomain.cloud:32447"
        ]
      ],
      "bin": "db2",
      "certificate": {
        "certificate_base64": "<certificate_code>",
        "name": "2ac5a4d3-1307-40f5-99a4-043e278fb084"
      },
      "composed": [
        "db2 -u ipa8emxc -p e2haTt1FJ7m3UQXY --ssl --sslCAFile 2ac5a4d3-1307-40f5-99a4-043e278fb084 --authenticationDatabase admin --host a1d53ce7-166c-42d1-af26-7809dexxxxxx.yyyyyy.databases.appdomain.cloud:32447"
      ],
      "environment": {},
      "type": "cli"
    },
    "db2": {
      "authentication": {
        "method": "direct",
        "password": "<password>",
        "username": "<user_name>"
      },
      "certificate": {
        "certificate_base64": "<certificate_code>",
        "name": "2ac5a4d3-1307-40f5-99a4-043e278fb084"
      },
      "composed": [
        "db2://ipa8emxc:e2haTt1FJ7m3UQXY@a1d53ce7-166c-42d1-af26-7809dexxxxxx.yyyyyy.databases.appdomain.cloud:32447/bludb?authSource=admin&replicaSet=replset"
      ],
      "database": "bludb",
      "host_ros": [
        "a1d53ce7-166c-42d1-af26-7809dexxxxxx.yyyyyy.databases.appdomain.cloud:31196"
      ],
      "hosts": [
        {
          "hostname": "a1d53ce7-166c-42d1-af26-7809dexxxxxx.yyyyyy.databases.appdomain.cloud",
          "port": 32447
        }
      ],
      "jdbc_url": [
        "jdbc:db2://a1d53ce7-166c-42d1-af26-7809dexxxxxx.yyyyyy.databases.appdomain.cloud:32447/bludb:user=<userid>;password=<your_password>;sslConnection=true;"
      ],
      "path": "/bludb",
      "query_options": {
        "authSource": "admin",
        "replicaSet": "replset"
      },
      "replica_set": "replset",
      "scheme": "db2",
      "type": "uri"
    }
  },
}

**Comment by bimalkjha** [comment]
The shared cloud link mentions that - ` The VCAP Services json file can be used to make connections to Enterprise and Standard plans database instances`.
So, you need to use specify specific fields from this json file in the connection string as below:
```
var db2 = VCAP.connecitons.db2;
var connStr = "Database=" + db2.database+";HostName="+db2.hosts.hostname+";Port="+db2.hosts.port+
                       ";UID="+db2.authentication.username+";PWD="+db2.authentication.password+";PROTOCOL=TCPIP";
```
You may need to use other keywords in connection string which is not in VCAP as per the application requirement. For example, `SchemaName`, `Security`, `QueryTimeout`, etc. All keywords and values are not in VCAP. We need to use values from VCAP in connection string. Thanks.
