### ISSUE TITLE
Trouble building on alpine linux

### ISSUE THREAD

**Issue by davidshepard989** [ibmdb/node-ibm_db#72]
Hi, I'm having a lot of trouble trying to get this to build on alpine linux which uses http://www.musl-libc.org/ for the C library. I'm using IBM Node SDK 0.12.7 and when I try to run the following after cloning the master branch, 

`node-gyp configure --IBM_DB_HOME=/node-ibm_db/installer/clidriver --IS_DOWNLOADED=true`

I get the following error:

<pre>node: /usr/lib/libstdc++.so.6: no version information available (required by node)
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
gyp: Call to 'node -e "require('nan')"' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.13.0-53-generic
gyp ERR! command "node" "/usr/local/bin/node-gyp" "configure" "--IBM_DB_HOME=/node-ibm_db/installer/clidriver" "--IS_DOWNLOADED=true"
gyp ERR! cwd /node-ibm_db
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v3.1.0
gyp ERR! not ok</pre>

Any help would be greatly appreciated

Thanks, David

**Comment by mhamann** [comment]
I believe Alpine has a glibc implementation available as well, but either way, one needs to know what dependencies are required in order to build this successfully. Seems like it should be possible, but that perhaps we're missing some required libs.

**Comment by bimalkjha** [comment]
@davidshepard989 The fist line of your posted error is
`node: /usr/lib/libstdc++.so.6: no version information available (required by node)`
I think you'll get same error when you run "node -v" command.
This issue is not related with node-ibm_db. This dependency is of node.
Please install libstdc++.so.6 library to fix this issue. Thanks.

**Comment by mhamann** [comment]
@bimalkjha I agree that would fix the issue. PR #73 still needs to be merged though, as the module will not compile without that change.

**Comment by bimalkjha** [comment]
@mhamann done. I have merged #73 to master and changes would be available in next release.

**Comment by mhamann** [comment]
Thanks!
