### ISSUE TITLE
Connect to db2 database in IBM Cloud with Cloud Foundry VCAP Services with SSL 

### ISSUE THREAD

**Issue by Chiangmg84** [ibmdb/node-ibm_db#720]
I'm able to connect to a db2 database with the following DSN and having the cert in the root directory of my project with the following string. 
DATABASE=bludb;HOSTNAME=XXXX;PORT=XXX;Security=SSL;SSLServerCertificate=./DigiCertGlobalRootCA.crt;PROTOCOL=TCPIP;UID=XXXX;PWD=XXXX;

In Cloud Foundry I should be able to connect to the database using VCAP Services but the only property I receive for the cert is 
      "certificate": {
        "certificate_base64": "XXXXXXXXXXX",
        "name": "XXXXXXXXXXX"
      }

How can I connect to the database without an actual file since SSLServerCertificate is expecting a path?

**Comment by bimalkjha** [comment]
@Chiangmg84 I think `DATABASE=bludb;HOSTNAME=XXXX;PORT=XXX;Security=SSL;PROTOCOL=TCPIP;UID=XXXX;PWD=XXXX;` should work for you. Check [this](https://github.com/ibmdb/node-ibm_db/blob/master/APIDocumentation.md#SSLConnection) documentation for details. Thanks.

**Comment by bimalkjha** [comment]
If `DigiCertGlobalRootCA.crt` is available under `ibm_db\installer\clidriver\cfg` directory, `ibm_db` automatically read and use it. No need to specify `SSLServerCertificate` keyword in connection string. If `DigiCertGlobalRootCA.crt` file at different location or name is different then only we need to specify it using `SSLServerCertificate` keyword. So, verify the directory contents to make sure this file exists under `clidriver\cfg` directory. Thanks.
