### ISSUE TITLE
Connection string with 2 certificates

### ISSUE THREAD

**Issue by jsalcedoa** [ibmdb/node-ibm_db#721]
Hi, 

I'm trying to establish a connection to a Database using SSL, but this database requires me to use 2 certificates, I did something like this `Security=SSL;SSLServerCertificate=[<masked path>/certificates/caintermediatecert.der,<masked path>/certificates/carootcert.der];` but I'm getting the following error:

[Error: [IBM][CLI Driver] CLI0157E  Error opening a file. SQLSTATE=HY507] {
  error: '[node-ibm_db] SQL_ERROR',
  sqlcode: -99999,
  state: 'HY507'
}

**Comment by bimalkjha** [comment]
@jsalcedoa Two certificates in connection string is not supported by `ibm_db` as of now. It should be supported by IBM ODBC/CLI driver first and it should be a new feature. Currently, if you need to use multiple certificates, you need to create keystore db using GSKit and add all certificates to keydb. Then use the keydb path and keydb password or stash file in connection string. The detail instructions about how to do it is documented here: https://www.ibm.com/support/knowledgecenter/SSEPGG_11.1.0/com.ibm.db2.luw.admin.sec.doc/doc/t0053518.html
Thanks.
