### ISSUE TITLE
Segmentation violations on node v12 with v2.7.1 driver for SSL connection

### ISSUE THREAD

**Issue by PeteDaGuru** [ibmdb/node-ibm_db#722]
We're seeing segmentation violations with our nodejs client driver (node v12.18.3 and v2.7.1 of ibm_db driver, on Mac OSX 10.14.6 but also on linux in IBM cloud).
 This started when our database was migrated to new IBM cloud DB2 instances, so wondering if something related to driver communications.

To recreate:
 ```
 node -e "require('ibm_db').open(process.env.DB2_CONNECTION_STRING, async function (err, conn){
  if (err) return console.log('error ' + err)
  const result = await conn.query('select 1 from sysibm.sysdummy1')
  console.log(result)
})
"
```

We also ran the ODBC connection test: `cd ./ node_modules/ibm_db/installer; ./testODBCConnection.sh`
It runs but cannot connect to sample:hotel.torolab.ibm.com:21169

**Comment by PeteDaGuru** [comment]
FWIW I created a Lite test database in IBM Cloud and tried to connect, and got a little bit more information out of node failure:
```
node(9748,0x70001289f000) malloc: *** error for object 0x7fffab0a78c0: pointer being freed was not allocated
node(9748,0x70001289f000) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

**Comment by PeteDaGuru** [comment]
The DB2_CONNECT_STRING I'm using is like: ` DATABASE=ddddd;HOSTNAME=xxxxx.databases.appdomain.cloud;PORT=nnnnn;PROTOCOL=TCPIP;UID=uuuu;PWD=ppppp;` .   Trial DB works, Standard DB does not.   Both fail with trap:6 with `;Security=SSL;` specified.

**Comment by PeteDaGuru** [comment]
Interestingly, I've tried using a JDBC connection, error I get there is:

[jcc][t4][2034][11148][4.27.25] Execution failed due to a distribution protocol error that caused deallocation of the conversation.
A DRDA Data Stream Syntax Error was detected.  Reason: 0x3. ERRORCODE=-4499, SQLSTATE=58009

This might indicate that DB2 communications over port 32486 is not being handled/routed correctly by the cloud firewall (note that the connections are not on the 'normal' port 50000).

**Comment by bimalkjha** [comment]
@PeteDaGuru So, your problem is only in case of Secure connection. Yes, server must be configured to accept connection on SSL port. Check with Db2Cloud team about it.
In case of secure connection, ibm_db tries to create in-memory keydb to store server certificate file and malloc error tells that some security configuration in cloud env is not allowing to do it. Same SSL connection works for me with my db2 cloud instance. It looks something to be looked by db2cloud team, please follow up with them. Thanks.

**Comment by PeteDaGuru** [comment]
Thanks!  I've got a ticket open with them, will put the resolution here for posterity's sake when we get one.    FWIW, we aren't trying to use the secure connection, but it may be enforced somehow with the standard plan (different than with the Trial plan).

**Comment by PeteDaGuru** [comment]
BTW, this driver still gives trap-6 abort no matter what parameters if SSL is activatated by having 'SECURITY=SSL;' in the connect string.  No resolution so far.

**Comment by PeteDaGuru** [comment]
FYI I've gotten support to give me the non-SSL port so we can connect.    We're still working on debugging the abort when we enable SSL security.  

FWIW, https://github.ibm.com/DB2LUW-content/Db2-Content-Tasks/issues/1112  is a doc upgrade for DB2 to try to make it more explicit about the need for Security=SSL or sslConnection=true parameters.
