### ISSUE TITLE
How to do mutual authentication to mainframe z/os db2

### ISSUE THREAD

**Issue by r3wt** [ibmdb/node-ibm_db#723]
Security has told us we must use certificate authentication to authenticate to db2 without UID and PWD. I have received a certificate from them called with a `.p12` extension, for example like `certificate.p12` which is a certificate for a specific user on the database in question. I am not able to find any information about this procedure in the node.js db2 client, so is this supported and if so can you provide me details? I've tried various things and no dice

Here is the connection string i have tried:

```
`DRIVER={DB2};DATABASE=${DB_NAME};HOSTNAME=${DB_HOST};Security=SSL;SSLServerCertificate=${DB_CERT};PORT=${SSL_PORT};`;
```

**Comment by bimalkjha** [comment]
@r3wt Info about Secure connection to db2 server using ibm_db is documented here: https://github.com/ibmdb/node-ibm_db/blob/master/APIDocumentation.md#SSLConnection
To use the Certificate Authentication, you need to follow Db2 Infocenter documentation as suggested in above link.
You need to download and install IBM Global Security ToolKit (GSKit) in your system, you need to create KeyStoreDB, add server certificate to it, generate client certificate and add client certificate on the Db2 server. Then use `Authentication=Certificate;Security=SSL;SSLClientKeyStoreDB=<fullpath of keydb>;SSLClientLabel=<label>;SSLClientKeystoreDBPassword=<password>;` in connection string. Certificate Authentication is supported by `Db2 for z/OS` server only. Follow the sections **CLI/ODBC client applications** and **Certificate-based authentication** of this doc:  https://www.ibm.com/support/knowledgecenter/SSEPGG_11.1.0/com.ibm.db2.luw.admin.sec.doc/doc/t0053518.html
Thanks.
