### ISSUE TITLE
Getting error when trying to connect to DB

### ISSUE THREAD

**Issue by Akash-H** [ibmdb/node-ibm_db#725]
node version: 12.18.2
npm: 6.14.6
ibm_db: 2.6.4

Connection string used -
```
connString = 'dsn=DSN;PROTOCOL=TCPIP;UID=' + dbUserid +';PWD=' + dbPassword + ';CurrentSchema=' + dbSchema +(dbDisableSsl ? ';' : ';Security=SSL;');
```
Also changes are done in db2dsdriver.cfg
```
<configuration>  
  <dsncollection>    
    <dsn alias="DSN" name="DB_NAME" host="DB_HOSTNAME" port="DB_PORT"/> 
  </dsncollection>  
  <databases>    
    <database name="DB_NAME" host="DB_HOSTNAME" port="DB_PORT">      
      <acr>        
        <parameter name="enableAcr" value="true"/>        
        <parameter name="maxAcrRetries" value="8"/>       
        <parameter name="acrRetryInterval" value="5"/>        
        <parameter name="enableAlternateServerListFirstConnect" value="true"/>       
        <alternateserverlist>           
          <server name="Server" hostname="DB_HOSTNAME" port="DB_PORT"/>                          
        </alternateserverlist>
        <affinitylist>
          <list name="list" serverorder="Server"/>
        </affinitylist>
      </acr>    
    </database>   
  </databases>
</configuration>
```
Application is running in a container and sometimes the same issue appear when running locally on Windows 10 Pro.
Following is the error message that we get when we try to connect to DB
```
[IBM][CLI Driver] SQL1531N  The connection failed because the name specified with the DSN connection string keyword could not be found in either the db2dsdriver.cfg configuration file or the db2cli.ini configuration file.  Data source name specified in the connection string: \"DSN\".\n
```

**Comment by bimalkjha** [comment]
@Akash-H It seems your system has another version of db2 client installed in the system. I would suggest to install `ibm_db@2.7.1` and verify. Remove the db2dsdriver.cfg file and use only connection string. It should work. Thanks.

**Comment by Akash-H** [comment]
@bimalkjha We upgraded `ibm_db@2.7.1`. But still we are getting same issue. Also earlier we were getting empty result set from DB hence we had switched to DSN for ACR (suggested by you).
What should be the next steps? Thanks.

**Comment by bimalkjha** [comment]
@Akash-H Let me know your Operating System where ibm_db is installed. If you are using non-windows system, go to `ibm_db\test` directory, update database connection info in `config.testConnectionStrings.json` file and run `trace test-basic-test.js` script to collect the db2trace files. If you are able to reproduce the problem using simple test file, you can execute `trace yourRepro.js` and share the generated 1.* files here for investigation about SQL1531N error. Thanks.
