### ISSUE TITLE
Help me, i can't read thai

### ISSUE THREAD

**Issue by jojo0004** [ibmdb/node-ibm_db#726]
i connect db2v10.5 
this is the code that connects to the database.

var ibmdb = require('ibm_db');
conn = new ibmdb.Database()
var connStr = "DATABASE=datasf;HOSTNAME=;UID=;PWD=;PORT=50000;PROTOCOL=TCPIP;";
conn.openSync(connStr)
process.env.DB2CODEPAGE = process.env.DB2CODEPAGE || 872;
    conn.query("SELECT NAME1,NAME2 FROM CUSTMAST  ", function (err, result) {
       const name = JSON.parse(JSON.stringify(result));

}
this is the value obtained by processing
���� ���Ũ�ʵԡ�� �ӡѴ

this is the codepage obtained by db2v10.5
![image](https://user-images.githubusercontent.com/12427294/102162055-1231eb80-3ebb-11eb-88b3-0460a18f3382.png)

#node ibm_db:^2.7.1

**Comment by bimalkjha** [comment]
@jojo0004 If you can not read THAI, then why you created database using territory TH and code page 874? If you have not created then contact the person who created it.
If you want to read the data in different codepage, then change it to code page of English language. Currently, you have set it 872 in ibm_db using the code `process.env.DB2CODEPAGE = process.env.DB2CODEPAGE || 872;`. Change 872 to 1208 and see it make any difference or not.
To know all supported territory codes and code pages, see this page: https://www.ibm.com/support/knowledgecenter/SSEPGG_11.5.0/com.ibm.db2.luw.admin.nls.doc/doc/r0004565.html

**Comment by jojo0004** [comment]
Thank you i can do it
