### ISSUE TITLE
Installer issue

### ISSUE THREAD

**Issue by juler69** [ibmdb/node-ibm_db#727]
When I try to install ibm_db on our zOS system I get errors because it cannot get to the default installer url location.  I followed the instructions to set the  IBM_DB_INSTALLER_URL environment variable to the path where the clidriver file is (name unchanged) but the installer script seems to ignore it.  I still get ECONNREFUSED and the switch on node-gyp **--IS_DOWNLOADED=false** indicates it is trying to go external for the driver.

>A123456:/u/A123456/projects/mis-role-revals: >npm i ibm_db
[..................] / rollbackFailedOptional: verb npm-session a77ee390cd7b4aaf
[..................] / rollbackFailedOptional: verb npm-session a77ee390cd7b4aaf
npm WARN registry Unexpected warning for https://example.com/artifactory/api/npm/node: Miscellaneous Warning ECONNREFUSED: request to https://example.com/artifactory/api/npm/node/ibm_db failed, reason: connect ECONNREFUSED 10.154.201.156:443
npm WARN registry Using stale data from https://example.com/artifactory/api/npm/node due to a request error during revalidation.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
> ibm_db@2.7.1 install /u/A123456/projects/mis-role-revals/node_modules/ibm_db
> node installer/driverInstall.js
platform =  os390 , arch =  s390x , node.js version =  v12.18.0
make: Error -- FSUM8705 No target
Unable to find 'make' in PATH. Installation may fail!
oput 'SYS1.DB2T.SDSNMACS(DSNAO64C)' '/u/A123456/projects/mis-role-revals/node_modules/ibm_db/build/dsnao64c.x'
Error: Command failed: node-gyp configure build  --IS_DOWNLOADED=false --IBM_DB_HOME="$IBM_DB_HOME"
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: connect ETIMEDOUT 104.20.23.46:443
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1147:16)
gyp ERR! System OS/390 26.00
gyp ERR! command "/usr/lpp/node-v12-os390-s390x/IBM/node-v12.18.0-os390-s390x/bin/node" "/usr/lpp/node-v12-os390-s390x/IBM/node-v12.18.0-os390-s390x/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build" "--IS_DOWNLOADED=false" "--IBM_DB_HOME=SYS1.DB2T"
gyp ERR! cwd /u/A123456/projects/mis-role-revals/node_modules/ibm_db
gyp ERR! node -v v12.18.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1042:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node-gyp configure build  --IS_DOWNLOADED=false --IBM_DB_HOME="$IBM_DB_HOME"'
}
npm WARN mis-role-revals@1.0.0 No description
npm WARN mis-role-revals@1.0.0 No repository field.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ibm_db@2.7.1 install: `node installer/driverInstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ibm_db@2.7.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /u/A123456/.npm/_logs/2020-12-11T06_30_24_870Z-debug.log

The log file contains these errors at the bottom of the log:

2508 verbose stack Error: ibm_db@2.7.1 install: `node installer/driverInstall.js`
2508 verbose stack Exit status 1
2508 verbose stack     at EventEmitter.<anonymous> (/usr/lpp/node-v12-os390-s390x/IBM/node-v12.18.0-os390-s390x/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
2508 verbose stack     at EventEmitter.emit (events.js:315:20)
2508 verbose stack     at ChildProcess.<anonymous> (/usr/lpp/node-v12-os390-s390x/IBM/node-v12.18.0-os390-s390x/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
2508 verbose stack     at ChildProcess.emit (events.js:315:20)
2508 verbose stack     at maybeClose (internal/child_process.js:1042:16)
2508 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
2509 verbose pkgid ibm_db@2.7.1

**Comment by bimalkjha** [comment]
@juler69 To install ibm_db on Z/OS system, you need to first configure the ODBC driver on z/OS by following the steps documented here: https://github.com/ibmdb/node-ibm_db#configure-odbc-driver-on-zos
Then set the IBM_DB_HOME environment variable which should point to the HLQ of the Db2 datasets. Then install ibm_db. Setting IBM_DB_INSTALLER_URL environment variable requires a downloaded clidriver .zip or .tar.gz file. IBM_DB_INSTALLER_URL is not for installation on Z/OS system. Hope it'll help you. Thanks.

**Comment by juler69** [comment]
The configuration steps for the driver are already in place.  I cannot install the package though so I can't use it.  The link you gave refers to the documentation I already followed to the point of my error.  The environment variable you say is not used on z/OS - why does the documentation not indicate this?  How then do I point to a downloaded driver on my z/OS filesystem and avoid the error where it is trying to download it?

**Comment by juler69** [comment]
Tried again using the git clone option and npm install - same issue and still seems to be trying to connect externally for something and is timing out.

> ibm_db@2.7.1 install /u/A123456/projects/mis-service-monitoring/node-ibm_db
> node installer/driverInstall.js

platform =  os390 , arch =  s390x , node.js version =  v12.18.0
make: Error -- FSUM8705 No target
Unable to find 'make' in PATH. Installation may fail!
oput 'SYS1.DB2T.SDSNMACS(DSNAO64C)' '/u/A123456/projects/mis-service-monitoring/node-ibm_db/build/dsnao64c.x'

Error: Command failed: node-gyp configure build  --IS_DOWNLOADED=false --IBM_DB_HOME="$IBM_DB_HOME"
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: connect ETIMEDOUT 104.20.22.46:443
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1147:16)
gyp ERR! System OS/390 26.00
gyp ERR! command "/usr/lpp/node-v12-os390-s390x/IBM/node-v12.18.0-os390-s390x/bin/node" "/usr/lpp/node-v12-os390-s390x/IBM/node-v12.18.0-os390-s390x/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build" "--IS_DOWNLOADED=false" "--IBM_DB_HOME=SYS1.DB2T"
gyp ERR! cwd /u/P719952/projects/mis-service-monitoring/node-ibm_db
gyp ERR! node -v v12.18.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1042:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node-gyp configure build  --IS_DOWNLOADED=false --IBM_DB_HOME="$IBM_DB_HOME"'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ibm_db@2.7.1 install: `node installer/driverInstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ibm_db@2.7.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /u/A123456/.npm/_logs/2021-01-10T23_35_01_743Z-debug.log
