### ISSUE TITLE
DB2 Conection issue. Protocol specific error code(s): "420", "*", "*". SQLSTATE=08001 

### ISSUE THREAD

**Issue by abbasgolestani** [ibmdb/node-ibm_db#728]
I am not able to make the SSL connection to a DB2 database using Python. I have the server certificate; the arm file (DigiCertGlobalRootCA.arm). I can make the SSL connection using Dbeaver and JDBC using the db2jcc4.jar file but I really need the Python connection. Appreciate any hints.

Here is the connection string that I am using:
String = "database=BLUDB;HOSTNAME=" + "hostname" + ";PORT=" + "31246" + ";PROTOCOL=TCPIP;UID=" + "userid" + ";PWD=" + "MyPass" + ";SECURITY=ssl;"+"SSLServerCertificate=C:/SSL/DigiCertGlobalRootCA.arm;"

Below is the error I am getting:
_SQL30081N A communication error has been detected. Communication protocol
being used: "SSL". Communication API being used: "SOCKETS". Location where
the error was detected: "". Communication function detecting the error:
"sqlccSSLSocketSetup". Protocol specific error code(s): "420", "", ""._
SQLSTATE=08001

**Comment by bimalkjha** [comment]
@abbasgolestani Please share the output of `db2level` command. Also, let me know if you have installed clidriver driver or any other db2 client in your system. Please share the complete output of `db2cli validate` command too.
You need not to use `SSLSeverCertificate` keyword in connection string when you are connecting to db2 server in IBM Cloud. The clidriver which get automatically downloaded with ibm_db comes with DigiCert certificate and use automatically for cloud db. Thanks.

**Comment by bimalkjha** [comment]
@abbasgolestani Make sure the port that you are using in connection string is an SSL port. If port is correct, then remove `SSLServerCertificate=C:/SSL/DigiCertGlobalRootCA.arm` from connection string and try. Closing the issue as of now as no response received from you. You can still post update here if you are still facing the problem. Thanks,

**Comment by bimalkjha** [comment]
If application is running inside code engine container on IBM Cloud and throwing this error, we need to add IP Address of code engine application in the whilelist to allow connection to Db2 on Cloud. Thanks.
