### ISSUE TITLE
Driver Install Issue.Error: Command failed: node-gyp configure build

### ISSUE THREAD

**Issue by asoj1987** [ibmdb/node-ibm_db#730]
Hi Team,
We are getting below error while trying to install ibm_db. 
**Node Version : v10.16.0
ibm_db version : 2.3.1**
We have IBM_DB_INSTALLER_URL set to download the driver zip from a network path.  We were using node v8.9.4 earlier and now performing an uplift to v10.16.0. Is this error due to any node version vs ibm_db module compatibility issue. 

Driver  is getting downloaded fine and it is extracted but then we are getting the below error. 

16:47:45  Downloading and extraction of DB2 ODBC CLI Driver completed successfully ...
16:47:45  
16:47:47  make: Entering directory ` /jenkins/workspace/olutions-mbp_feature_JenkinsFile/node_modules/ibm_db/build'
16:47:47    CXX(target) Release/obj.target/odbc_bindings/src/odbc.o
16:47:47  make: Leaving directory ` /jenkins/workspace/olutions-mbp_feature_JenkinsFile/node_modules/ibm_db/build'
16:47:47  
16:47:47  { Error: Command failed: node-gyp configure build  --IS_DOWNLOADED=true --IBM_DB_HOME="$IBM_DB_HOME"
16:47:47  In file included from ../../nan/nan.h:190:0,
16:47:47                   from ../src/odbc.h:23,
16:47:47                   from ../src/odbc.cpp:28:
16:47:47  ../../nan/nan_maybe_43_inl.h: In function 'Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)':
16:47:47  ../../nan/nan_maybe_43_inl.h:88:15: error: 'class v8::Object' has no member named 'ForceSet'
16:47:47     return obj->ForceSet(GetCurrentContext(), key, value, attribs);
16:47:47                 ^
16:47:47  In file included from ../src/odbc.h:23:0,
16:47:47                   from ../src/odbc.cpp:28:
16:47:47  ../../nan/nan.h: In function 'v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)':
16:47:47  ../../nan/nan.h:817:60: warning: 'v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)' is deprecated (declared at  /jenkins/.cache/node-gyp/10.16.0/include/node/node.h:176): Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
16:47:47           v8::Isolate::GetCurrent(), target, func, argc, argv);
16:47:47                                                              ^
16:47:47  ../../nan/nan.h: In function 'v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)':
16:47:47  ../../nan/nan.h:831:62: warning: 'v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)' is deprecated (declared at  /jenkins/.cache/node-gyp/10.16.0/include/node/node.h:169): Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
16:47:47           v8::Isolate::GetCurrent(), target, symbol, argc, argv);
16:47:47                                                                ^
16:47:47  ../../nan/nan.h: In function 'v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)':
16:47:47  ../../nan/nan.h:845:62: warning: 'v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)' is deprecated (declared at  /jenkins/.cache/node-gyp/10.16.0/include/node/node.h:162): Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
16:47:47           v8::Isolate::GetCurrent(), target, method, argc, argv);
16:47:47                                                                ^
16:47:47  ../../nan/nan.h: In member function 'v8::Local<v8::Value> Nan::Callback::Call_(v8::Isolate*, v8::Local<v8::Object>, int, v8::Local<v8::Value>*) const':
16:47:47  ../../nan/nan.h:1463:5: warning: 'v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)' is deprecated (declared at  /jenkins/.cache/node-gyp/10.16.0/include/node/node.h:176): Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
16:47:47       ));
16:47:47       ^
16:47:47  ../src/odbc.cpp: In static member function 'static void ODBC::UV_AfterCreateConnection(uv_work_t*, int)':
16:47:47  ../src/odbc.cpp:207:99: error: no matching function for call to 'v8::Function::NewInstance(int, v8::Local<v8::Value> [2])'
16:47:47       Local<Object> js_result = Nan::New<Function>(ODBCConnection::constructor)->NewInstance(2, info);
16:47:47                                                                                                     ^
16:47:47  ../src/odbc.cpp:207:99: note: candidates are:
16:47:47  In file included from ../src/odbc.cpp:22:0:
16:47:47   /jenkins/.cache/node-gyp/10.16.0/include/node/v8.h:3993:44: note: v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>, int, v8::Local<v8::Value>*) const
16:47:47     V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
16:47:47                                              ^
16:47:47   /jenkins/.cache/node-gyp/10.16.0/include/node/v8.h:3993:44: note:   candidate expects 3 arguments, 2 provided
16:47:47   /jenkins/.cache/node-gyp/10.16.0/include/node/v8.h:3996:44: note: v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const
16:47:47     V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
16:47:47                                              ^
16:47:47   /jenkins/.cache/node-gyp/10.16.0/include/node/v8.h:3996:44: note:   candidate expects 1 argument, 2 provided
16:47:47  ../src/odbc.cpp: In static member function 'static Nan::NAN_METHOD_RETURN_TYPE ODBC::CreateConnectionSync(Nan::NAN_METHOD_ARGS_TYPE)':
16:47:47  ../src/odbc.cpp:250:99: error: no matching function for call to 'v8::Function::NewInstance(int, v8::Local<v8::Value> [2])'
16:47:47     Local<Object> js_result = Nan::New<Function>(ODBCConnection::constructor)->NewInstance(2, params);
16:47:47                                                                                                     ^
16:47:47  ../src/odbc.cpp:250:99: note: candidates are:
16:47:47  In file included from ../src/odbc.cpp:22:0:
16:47:47   /jenkins/.cache/node-gyp/10.16.0/include/node/v8.h:3993:44: note: v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>, int, v8::Local<v8::Value>*) const
16:47:47     V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
16:47:47                                              ^
16:47:47   /jenkins/.cache/node-gyp/10.16.0/include/node/v8.h:3993:44: note:   candidate expects 3 arguments, 2 provided
16:47:47   /jenkins/.cache/node-gyp/10.16.0/include/node/v8.h:3996:44: note: v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const
16:47:47     V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
16:47:47                                              ^
16:47:47   /jenkins/.cache/node-gyp/10.16.0/include/node/v8.h:3996:44: note:   candidate expects 1 argument, 2 provided
16:47:47  ../src/odbc.cpp: In static member function 'static Parameter* ODBC::GetParametersFromArray(v8::Local<v8::Array>, int*)':
16:47:47  ../src/odbc.cpp:856:51: warning: 'int64_t v8::Value::IntegerValue() const' is deprecated (declared at  /jenkins/.cache/node-gyp/10.16.0/include/node/v8.h:2476): Use maybe version [-Wdeprecated-declarations]
16:47:47             params[i].paramtype = val->IntegerValue();
16:47:47                                                     ^
16:47:47  ../src/odbc.cpp:860:48: warning: 'int64_t v8::Value::IntegerValue() const' is deprecated (declared at  /jenkins/.cache/node-gyp/10.16.0/include/node/v8.h:2476): Use maybe version [-Wdeprecated-declarations]
16:47:47             params[i].c_type = val->IntegerValue();
16:47:47                                                  ^
16:47:47  ../src/odbc.cpp:866:46: warning: 'int64_t v8::Value::IntegerValue() const' is deprecated (declared at  /jenkins/.cache/node-gyp/10.16.0/include/node/v8.h:2476): Use maybe version [-Wdeprecated-declarations]
16:47:47             params[i].type = val->IntegerValue();
16:47:47                                                ^
16:47:47  ../src/odbc.cpp:874:59: warning: 'int64_t v8::Value::IntegerValue() const' is deprecated (declared at  /jenkins/.cache/node-gyp/10.16.0/include/node/v8.h:2476): Use maybe version [-Wdeprecated-declarations]
16:47:47                 params[i].buffer_length = val->IntegerValue();
16:47:47                                                             ^
16:47:47  ../src/odbc.cpp: In static member function 'static void ODBC::GetInt32Param(v8::Local<v8::Value>, Parameter*, int)':
16:47:47  ../src/odbc.cpp:1010:56: warning: 'int64_t v8::Value::IntegerValue() const' is deprecated (declared at  /jenkins/.cache/node-gyp/10.16.0/include/node/v8.h:2476): Use maybe version [-Wdeprecated-declarations]
16:47:47       int64_t  *number = new int64_t(value->IntegerValue());
16:47:47                                                          ^
16:47:47  ../src/odbc.cpp: In static member function 'static void ODBC::GetNumberParam(v8::Local<v8::Value>, Parameter*, int)':
16:47:47  ../src/odbc.cpp:1026:54: warning: 'double v8::Value::NumberValue() const' is deprecated (declared at  /jenkins/.cache/node-gyp/10.16.0/include/node/v8.h:2475): Use maybe version [-Wdeprecated-declarations]
16:47:47       double *number   = new double(value->NumberValue());
16:47:47                                                        ^
16:47:47  ../src/odbc.cpp: In static member function 'static v8::Local<v8::Value> ODBC::GetSQLError(SQLSMALLINT, SQLHANDLE, char*)':
16:47:47  ../src/odbc.cpp:1198:87: error: no matching function for call to 'v8::Object::SetPrototype(v8::Local<v8::Value>)'
16:47:47         objError->SetPrototype(Exception::Error(Nan::New(errorMessage).ToLocalChecked()));
16:47:47                                                                                         ^
16:47:47  ../src/odbc.cpp:1198:87: note: candidate is:
16:47:47  In file included from ../src/odbc.cpp:22:0:
16:47:47   /jenkins/.cache/node-gyp/10.16.0/include/node/v8.h:3442:37: note: v8::Maybe<bool> v8::Object::SetPrototype(v8::Local<v8::Context>, v8::Local<v8::Value>)
16:47:47     V8_WARN_UNUSED_RESULT Maybe<bool> SetPrototype(Local<Context> context,
16:47:47                                       ^
16:47:47   /jenkins/.cache/node-gyp/10.16.0/include/node/v8.h:3442:37: note:   candidate expects 2 arguments, 1 provided
16:47:47  make: *** [Release/obj.target/odbc_bindings/src/odbc.o] Error 1
16:47:47  gyp ERR! build error 
16:47:47  gyp ERR! stack Error: `make` failed with exit code: 2
16:47:47  gyp ERR! stack     at ChildProcess.onExit ( /jenkins/installables/nodejs/node10/node-v10.16.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
16:47:47  gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
16:47:47  gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
16:47:47  gyp ERR! System Linux 3.10.0-1160.2.1.el7.x86_64
16:47:47  gyp ERR! command " /jenkins/installables/nodejs/node10/node-v10.16.0-linux-x64/bin/node" " /jenkins/installables/nodejs/node10/node-v10.16.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build" "--IS_DOWNLOADED=true" "--IBM_DB_HOME= /jenkins/workspace/olutions-mbp_feature_JenkinsFile/node_modules/ibm_db/installer/clidriver"
16:47:47  gyp ERR! cwd  /jenkins/workspace/olutions-mbp_feature_JenkinsFile/node_modules/ibm_db
16:47:47  gyp ERR! node -v v10.16.0
16:47:47  gyp ERR! node-gyp -v v5.0.3
16:47:47  gyp ERR! not ok 
16:47:47  
16:47:47      at ChildProcess.exithandler (child_process.js:294:12)
16:47:47      at ChildProcess.emit (events.js:198:13)
16:47:47      at maybeClose (internal/child_process.js:982:16)
16:47:47      at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
16:47:47    killed: false,
16:47:47    code: 1,
16:47:47    signal: null,
16:47:47    cmd:
16:47:47     'node-gyp configure build  --IS_DOWNLOADED=true --IBM_DB_HOME="$IBM_DB_HOME"' }
16:47:48  npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/chokidar/node_modules/fsevents):
16:47:48  npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

16:47:48  
16:47:48  npm ERR! code ELIFECYCLE
16:47:48  npm ERR! errno 1
16:47:48  npm ERR! ibm_db@2.3.1 install: `node installer/driverInstall.js`
16:47:48  npm ERR! Exit status 1
16:47:48  npm ERR! 
16:47:48  npm ERR! Failed at the ibm_db@2.3.1 install script.
16:47:48  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
16:47:48  
16:47:48  npm ERR! A complete log of this run can be found in:
16:47:48  npm ERR!      /jenkins/.npm/_logs/2021-01-08T21_47_48_562Z-debug.log
16:47:48  [Pipeline] fileExists

**Comment by bimalkjha** [comment]
@asoj1987 Are you installing `ibm-db@2.3.1` first time in your system or it was working before and now it fails with updated node.js? I think you have recently updated your node.js which is causing this issue. The error is coming from the node.js header file v8.h which is not compatible with old version of ibm_db. Please move back to older version of node.js that you was using or install latest version of ibm_db. Latest version of ibm_db is 2.7.1. Thanks.

**Comment by asoj1987** [comment]
Thanks @bimalkjha for the quick response. No we had version 2.3.1 installed for a long time and working fine with node 8.9.4. Now we are doing a node version uplift to 10.16.0. Thanks for your recommendations. I will give a try with ibm_db 2.7.1 and will update here how it went. I am assuming v 2.7.1 has backward compatibility with 2.3.1

**Comment by asoj1987** [comment]
@bimalkjha Here's the latest results with ibm_db 2.71 and node v10.16.0 

12:53:30  Downloading and extraction of DB2 ODBC CLI Driver completed successfully ...
12:53:30  
12:53:34  make: Entering directory ` /jenkins/workspace/olutions-mbp_feature_JenkinsFile/node_modules/ibm_db/build'
12:53:34    CXX(target) Release/obj.target/odbc_bindings/src/odbc.o
12:53:34    CXX(target) Release/obj.target/odbc_bindings/src/odbc_connection.o
12:53:34  make: Leaving directory ` /jenkins/workspace/olutions-mbp_feature_JenkinsFile/node_modules/ibm_db/build'
12:53:34  
12:53:34  { Error: Command failed: node-gyp configure build  --IS_DOWNLOADED=true --IBM_DB_HOME="$IBM_DB_HOME"
12:53:34  ../src/odbc.cpp: In static member function 'static void ODBC::UV_AfterCreateConnection(uv_work_t*, int)':
12:53:34  ../src/odbc.cpp:216:27: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated (declared at ../../nan/nan.h:1742) [-Wdeprecated-declarations]
12:53:34       data->cb->Call(1, info);
12:53:34                             ^
12:53:34  ../src/odbc.cpp:228:27: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated (declared at ../../nan/nan.h:1742) [-Wdeprecated-declarations]
12:53:34       data->cb->Call(2, info);
12:53:34                             ^
12:53:34  ../src/odbc.cpp: In static member function 'static void ODBC::GetArrayParam(v8::Local<v8::Value>, Parameter*, int)':
12:53:34  ../src/odbc.cpp:1223:25: warning: deleting 'SQLPOINTER {aka void*}' is undefined [enabled by default]
12:53:34             delete param->buffer;
12:53:34                           ^
12:53:34  ../src/odbc.cpp:1244:25: warning: deleting 'SQLPOINTER {aka void*}' is undefined [enabled by default]
12:53:34             delete param->buffer;
12:53:34                           ^
12:53:34  ../src/odbc.cpp:1278:53: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
12:53:34             if( param->length > 0 && bufflen > param->length ) {
12:53:34                                                       ^
12:53:34  ../src/odbc.cpp: In static member function 'static v8::Local<v8::Value> ODBC::CallbackSQLError(SQLSMALLINT, SQLHANDLE, char*, Nan::Callback*)':
12:53:34  ../src/odbc.cpp:1394:19: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated (declared at ../../nan/nan.h:1742) [-Wdeprecated-declarations]
12:53:34     cb->Call(1, info);
12:53:34                     ^
12:53:34  ../src/odbc_connection.cpp: In static member function 'static void ODBCConnection::UV_AfterOpen(uv_work_t*, int)':
12:53:34  ../src/odbc_connection.cpp:310:35: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated (declared at ../../nan/nan.h:1742) [-Wdeprecated-declarations]
12:53:34     data->cb->Call(err ? 1 : 0, argv);
12:53:34                                     ^
12:53:34  ../src/odbc_connection.cpp: In static member function 'static void ODBCConnection::UV_AfterClose(uv_work_t*, int)':
12:53:34  ../src/odbc_connection.cpp:534:35: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated (declared at ../../nan/nan.h:1742) [-Wdeprecated-declarations]
12:53:34     data->cb->Call(err ? 1 : 0, argv);
12:53:34                                     ^
12:53:34  ../src/odbc_connection.cpp: In static member function 'static void ODBCConnection::UV_AfterCreateStatement(uv_work_t*, int)':
12:53:34  ../src/odbc_connection.cpp:909:26: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated (declared at ../../nan/nan.h:1742) [-Wdeprecated-declarations]
12:53:34     data->cb->Call( 2, info);
12:53:34                            ^
12:53:34  ../src/odbc_connection.cpp: In static member function 'static void ODBCConnection::UV_Query(uv_work_t*)':
12:53:34  ../src/odbc_connection.cpp:1094:51: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
12:53:34                                   (SQLPOINTER)data->arraySize, 0);
12:53:34                                                     ^
12:53:34  ../src/odbc_connection.cpp: In static member function 'static void ODBCConnection::UV_AfterQuery(uv_work_t*, int)':
12:53:34  ../src/odbc_connection.cpp:1148:27: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated (declared at ../../nan/nan.h:1742) [-Wdeprecated-declarations]
12:53:34       data->cb->Call(2, info);
12:53:34                             ^
12:53:34  ../src/odbc_connection.cpp:1178:27: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated (declared at ../../nan/nan.h:1742) [-Wdeprecated-declarations]
12:53:34       data->cb->Call(3, info);
12:53:34                             ^
12:53:34  ../src/odbc_connection.cpp: In static member function 'static Nan::NAN_METHOD_RETURN_TYPE ODBCConnection::QuerySync(Nan::NAN_METHOD_ARGS_TYPE)':
12:53:34  ../src/odbc_connection.cpp:1341:46: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
12:53:34                                   (SQLPOINTER) arraySize, 0);
12:53:34                                                ^
12:53:34  ../src/odbc_connection.cpp: In static member function 'static void ODBCConnection::UV_AfterBeginTransaction(uv_work_t*, int)':
12:53:34  ../src/odbc_connection.cpp:1714:36: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated (declared at ../../nan/nan.h:1742) [-Wdeprecated-declarations]
12:53:34     data->cb->Call( err ? 1 : 0, argv);
12:53:34                                      ^
12:53:34  ../src/odbc_connection.cpp: In static member function 'static void ODBCConnection::UV_AfterEndTransaction(uv_work_t*, int)':
12:53:34  ../src/odbc_connection.cpp:1896:35: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated (declared at ../../nan/nan.h:1742) [-Wdeprecated-declarations]
12:53:34     data->cb->Call(err ? 1 : 0, argv);
12:53:34                                     ^
12:53:34  ../src/odbc_connection.cpp: In static member function 'static void ODBCConnection::UV_AfterGetInfo(uv_work_t*, int)':
12:53:34  ../src/odbc_connection.cpp:2100:26: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated (declared at ../../nan/nan.h:1742) [-Wdeprecated-declarations]
12:53:34     data->cb->Call( 2, info);
12:53:34                            ^
12:53:34  ../src/odbc_connection.cpp: In function 'v8::Local<v8::Value> getInfoValue(SQLUSMALLINT, SQLPOINTER)':
12:53:34  ../src/odbc_connection.cpp:2138:14: error: 'SQL_DBMS_FUNCTIONLVL' was not declared in this scope
12:53:34           case SQL_DBMS_FUNCTIONLVL          :
12:53:34                ^
12:53:34  make: *** [Release/obj.target/odbc_bindings/src/odbc_connection.o] Error 1
12:53:34  gyp ERR! build error 
12:53:34  gyp ERR! stack Error: `make` failed with exit code: 2
12:53:34  gyp ERR! stack     at ChildProcess.onExit ( /jenkins/installables/nodejs/node10/node-v10.16.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
12:53:34  gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
12:53:34  gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
12:53:34  gyp ERR! System Linux 3.10.0-1160.2.1.el7.x86_64
12:53:34  gyp ERR! command " /jenkins/installables/nodejs/node10/node-v10.16.0-linux-x64/bin/node" " /jenkins/installables/nodejs/node10/node-v10.16.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build" "--IS_DOWNLOADED=true" "--IBM_DB_HOME= /jenkins/workspace/olutions-mbp_feature_JenkinsFile/node_modules/ibm_db/installer/clidriver"
12:53:34  gyp ERR! cwd  /jenkins/workspace/olutions-mbp_feature_JenkinsFile/node_modules/ibm_db
**12:53:34  gyp ERR! node -v v10.16.0
12:53:34  gyp ERR! node-gyp -v v5.0.3**
12:53:34  gyp ERR! not ok 
12:53:34  
12:53:34      at ChildProcess.exithandler (child_process.js:294:12)
12:53:34      at ChildProcess.emit (events.js:198:13)
12:53:34      at maybeClose (internal/child_process.js:982:16)
12:53:34      at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
12:53:34    killed: false,
12:53:34    code: 1,
12:53:34    signal: null,
12:53:34    cmd:
12:53:34     'node-gyp configure build  --IS_DOWNLOADED=true --IBM_DB_HOME="$IBM_DB_HOME"' }
12:53:35  npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/chokidar/node_modules/fsevents):
12:53:35  npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
12:53:35  npm WARN solutionsapi@0.0.1 No license field.
12:53:35  
12:53:35  npm ERR! code ELIFECYCLE
12:53:35  npm ERR! errno 1
12:53:35  npm ERR! ibm_db@2.7.1 install: `node installer/driverInstall.js`
12:53:35  npm ERR! Exit status 1
12:53:35  npm ERR! 
12:53:35  npm ERR! Failed at the ibm_db@2.7.1 install script.
12:53:35  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
12:53:35  
12:53:35  npm ERR! A complete log of this run can be found in:
12:53:35  npm ERR!      /jenkins/.npm/_logs/2021-01-10T17_53_35_113Z-debug.log

**Comment by bimalkjha** [comment]
@asoj1987 Now you are hitting issue #729 because of use of v10.5 clidriver. So there are three options for you:
1. install v11.1.1.1 or latter version of db2 client
2. Install ibm_db v2.7.0
3. Wait for release of next version of ibm_db.
Thanks.

**Comment by asoj1987** [comment]
Thanks @bimalkjha . I went ahead with option2 and it build was success.. Yet to do testing :)
Thanks for your support on this.
