### ISSUE TITLE
The command was not processed because the database manager failed to load the following DLL: ""

### ISSUE THREAD

**Issue by linaedua** [ibmdb/node-ibm_db#732]
I am getting the below error message when trying to establish an SSL connection using nodejs: 

```
{ [Error: [IBM][CLI Driver] SQL1109N  The command was not processed because the database manager failed to load the following DLL: "".  SQLSTATE=42724  
]                                                                                                                                                       
  error: '[node-ibm_db] SQL_ERROR',                                                                                                                     
  sqlcode: -1109,                                                                                                                                       
  message:                                                                                                                                              
   '[IBM][CLI Driver] SQL1109N  The command was not processed because the database manager failed to load the following DLL: "".  SQLSTATE=42724\r\n',  
  state: '42724' }                                                                                                                                      
```
**Connection string**: `connStr = "DATABASE=database;HOSTNAME=host;PORT=port;Security=SSL;SSLServerCertificate=certificate.arm;PROTOCOL=TCPIP;UID=user;PWD=password;";`

**node version**: '10.16.0'

**npm version**: '6.9.0'

**ibm_db version**: 6.9.0

**Operating system**: Windows 10

**System type**: 64 bit

**GSKit version**: 8.0.55.17

**db2 version**: DB21085I  This instance or install (instance name, where applicable: "DB2")
uses "64" bits and DB2 code release "SQL1005A" with level identifier
"060B010E".
Informational tokens are "**DB2 v10.5.1000.898**", "s180615", "IP24058", and Fix
Pack "10".
Product is installed at "C:\PROGRA~1\IBM\SQLLIB" with DB2 Copy Name "DB2COPY1".

"Set" command result: 
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\LinaEduardaCaridadeF\AppData\Roaming
CLASSPATH=.;C:\PROGRA~1\IBM\SQLLIB\java\db2java.zip;C:\PROGRA~1\IBM\SQLLIB\java\db2jcc.jar;C:\PROGRA~1\IBM\SQLLIB\java\sqlj.zip;C:\PROGRA~1\IBM\SQLLIB\java\db2jcc_license_cu.jar;C:\PROGRA~1\IBM\SQLLIB\bin;C:\PROGRA~1\IBM\SQLLIB\java\common.jar
CMDER_ROOT=C:\Users\LinaEduardaCaridadeF\Cmder
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=DESKTOP-9J2JCQP
ComSpec=C:\WINDOWS\system32\cmd.exe
DB2INSTANCE=DB2
DriverData=C:\Windows\System32\Drivers\DriverData
HOMEDRIVE=C:
HOMEPATH=\Users\LinaEduardaCaridadeF
INCLUDE=C:\PROGRA~1\IBM\SQLLIB\INCLUDE;C:\PROGRA~1\IBM\SQLLIB\LIB
IWBPath=C:\Program Files (x86)\SAP\FrontEnd\iwb
LIB=C:\Program Files\IBM\SQLLIB\BIN;C:\Program Files\IBM\SQLLIB\BIN\icc64;C:\Program Files\IBM\SQLLIB\lib
LOCALAPPDATA=C:\Users\LinaEduardaCaridadeF\AppData\Local
LOGONSERVER=\\DESKTOP-9J2JCQP
NUMBER_OF_PROCESSORS=8
OneDrive=C:\Users\LinaEduardaCaridadeF\OneDrive
OPENSSL_CONF=C:\Program Files\openssl-0.9.8h-1-bin\share\openssl.cnf
OS=Windows_NT
Path=C:\ProgramData\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\Program Files (x86)\IBM\Personal Communications\;C:\Program Files (x86)\IBM\Trace Facility\;C:\Program Files\nodejs\;C:\Program Files (x86)\Webex\Webex\Applications;C:\Program Files\kubectl;C:\Program Files\helm\windows-amd64;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\IBM\Cloud\bin;C:\Program Files\openssl-0.9.8h-1-bin\bin;C:\Program Files (x86)\ibm\gsk8\lib;C:\Program Files\ibm\gsk8\lib64;C:\PROGRA~1\IBM\SQLLIB\BIN;C:\PROGRA~1\IBM\SQLLIB\FUNCTION;C:\PROGRA~1\IBM\SQLLIB\SAMPLES\REPL;C:\Program Files\IBM\SQLLIB\BIN;C:\Program Files\IBM\SQLLIB\BIN\icc64;C:\Program Files\IBM\SQLLIB\lib;C:\TrustStore;C:\Users\LinaEduardaCaridadeF\AppData\Local\Microsoft\WindowsApps;"C:\Users\LinaEduardaCaridadeF\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\IBM\SQLLIB\java;C:\Users\LinaEduardaCaridadeF\AppData\Roaming\IBM\QMF for Workstation\jre";C:\Users\LinaEduardaCaridadeF\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\LinaEduardaCaridadeF\AppData\Local\GitHubDesktop\bin;C:\Users\LinaEduardaCaridadeF\AppData\Roaming\npm;C:\Users\LinaEduardaCaridadeF\AppData\Local\Microsoft\WindowsApps;C:\Program Files\IBM\gsk8\bin;C:\Program Files\IBM\IBM DATA SERVER DRIVER\bin\db2cli.exe;C:\Users\LinaEduardaCaridadeF\AppData\Local\Box\Box Edit\;C:\Program Files\IBM\gsk8\lib64
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PCOMM_Root=C:\Program Files (x86)\IBM\Personal Communications\
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=8e0a
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=$P$G
PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
PUBLIC=C:\Users\Public
SNC_LIB=C:\Program Files (x86)\SAP\SNCEncryption\x86\sapsncencryption.dll
SNC_LIB_64=C:\Program Files (x86)\SAP\SNCEncryption\x64\sapsncencryption.dll
SystemDrive=C:
SystemRoot=C:\WINDOWS
TEMP=C:\Users\LINAED~1\AppData\Local\Temp
TMP=C:\Users\LINAED~1\AppData\Local\Temp
USERDOMAIN=AzureAD
USERDOMAIN_ROAMINGPROFILE=AzureAD
USERNAME=LinaEduardaCaridadeF
USERPROFILE=C:\Users\LinaEduardaCaridadeF
windir=C:\WINDOWS

**Comment by bimalkjha** [comment]
@linaedua In the output of `set` command, if you check LIB and PATH values, we can see `C:\Program Files\IBM\SQLLIB\BIN\icc64` in LIB and `C:\Program Files (x86)\ibm\gsk8\lib;` in PATH environment variable. So, when you use `ibm_db`, GSKit libraries from these locations are getting picked up and throwing error.
In the output of `db2cli validate` command, we can see below db2 clients are installed in your system:
```
DB2COPY1[D]                                                                               10.5.10 CLNT    EN       C:\Program Files\IBM\SQLLIB
IBMDBCL1                                                                                  11.1.4050 DSD     EN       C:\Program Files\IBM\IBM DATA SERVER DRIVER
```
These installations are causing the problem. If you uninstall both from your system and restart system, `ibm_db` would work fine.
If you do not want to uninstall it, then edit the system environment variables LIB and PATH and remove the reference for GSKit and icc64 directories, then ibm_db can work. Thanks.

**Comment by linaedua** [comment]
After all the tests, we have come to the conclusion that the certificate could not be accessed. Solved by having the command prompt, powershell or simil opened as admin (for windows 10)
