### ISSUE TITLE
DB reconnection is strange when MaxPoolSize is set

### ISSUE THREAD

**Issue by LQ-001** [ibmdb/node-ibm_db#734]
Hello, I want to use the connection pool function... However, if MaxPoolSize is set, the behavior after DB reconnection (connection is disconnected for some reason and reconnects) will be incorrect as shown in the following cases. In any of the following cases, if MaxPoolSize is not set, it will work normally.
Is this an issue for MaxPoolSize? Or is my usage incorrect?
Case-1 setMaxPoolSize + pool.init => pool.open does not complete
  1) pool.setMaxPoolSize
  2) pool.init
  3) disconnect the DB connection of the connection pool
  4) pool.open => OK
  5) query execution => SQL30081N Error occurred
  6) pool.open => pool.open does not complete and remains running.
Case-2 setMaxPoolSize (without running pool.init) => connection pool count is 1
  1) pool.setMaxPoolSize (for example, set 2)
  2) pool.open => OK
  3) query execution => OK
  4) close => OK
  5) disconnect the DB connection of the connection pool
  6) pool.open => OK
  7) query execution => SQL30081N Error occurred
  8) pool.open => OK
  9) query execution => OK
  10) close => OK <=== There is no problem so far, but the number of connection pools can not be 1 or more after that

Thank you.

**Comment by bimalkjha** [comment]
@LQ-001 Probably you need to provide more details. Is it possible to reproduce the problem by modifying https://github.com/ibmdb/node-ibm_db/blob/vscode/test/test-bad-pool-connection-issue-42.js? Please share the modified version.
The MaxPoolSize is to simply keep checking the maximum number of connections in a pool. If maxpoolsize is set to 5, the maximum number of actual connections opened by pool.open against the server would be 5 only. When you do pool.open() for 6th connection, it'll throw error after sometime, if any open connection is not closed and returned to the pool.  that means, if you are returning the connection to the pool using conn.close() and then calling pool.open(), it would work. maxpoolsize is to restrict the number of active connection with Db2 server.
When conn.query() gets SQL30081N error, ibm_db removes all connections from the pool and then try reconnection to get fresh connection. So, stale connections are getting removed.
Please share some test program to repro the problem. Also, use debug(true) to see the contents of connection pool to validate the values. Thanks.
