### ISSUE TITLE
ibmdb.debug(true) is dumping sensitive data

### ISSUE THREAD

**Issue by Kuilau** [ibmdb/node-ibm_db#738]
when enabling for debug, it will dump the sensitive data, personal information, i.e. social insurance number, credit card #, etc

i.e.
ibmdb.debug(true);

Does it really need to dump the content during the debug ? 

Can we not to or choose not to dumping the content (_params_), as potentially there are sensitive data, PI, etc?

for example, in odbc.js:
 exports.debug && console.log("%s odbc.js:executeNonQuery() bind params = ", getElapsedTime(), params);

it will dump whatever in _params_.

Thanks.

**Comment by bimalkjha** [comment]
@Kuilau We do not suggest user to enable debug mode and run application as it causes performance. debug(true) functionality is there for problem diagnostics purpose and we suggest user to enable debug mode and share logs after removing sensitive data.
We are dumping params to diagnose the params related issues. If you need to run app in debug mode and have sensitive data in params, then comment the code of odbc.js file as you pointed out and then start application. I think that should solve the issue. Thanks.

**Comment by Kuilau** [comment]
@bimalkjha. Thanks for your quick answer. For some of our debug scenario, we might want to turn the debug on, I.e. connection, or ssl connection issue or connection pooling to see more details underneath of what the problem originating from our customers/users environment. I am afraid exposing customer sensitive data might not be acceptable due to privacy/etc during the debug process.
Could you consider to have a feature or an option to turn on/off the content (param) in the future?
Thanks.

**Comment by bimalkjha** [comment]
@Kuilau I have pushed the changes on github and it should be available with next release if ibm_db.
Meanwhile, if you want to test it on non-windows system, you can install `ibm_db` using command `npm install git+https://git@github.com/ibmdb/node-ibm_db.git` and verify it. You should have git installed in the system to run this command. thanks.
