### ISSUE TITLE
Error on cypress integration

### ISSUE THREAD

**Issue by lhimo** [ibmdb/node-ibm_db#740]
I'm trying to integrate the module as a plugin but I'm getting the following error:

`Error: The module '\\?\C:\Users\usr\Documents\prj\node_modules\ibm_db\build\Release\odbc_bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 85. Please try re-compiling or re-installing
the module (for instance, using 'npm rebuild' or 'npm install').`

What can it be the cause?

**Comment by bimalkjha** [comment]
@lhimo What the result of "node -v" command? It seems your system has latest version of node.js installed but cypress is using electron "versions": ">=3 <4.0.4" which requires node.js version 10.x : https://github.com/nodejs/node/blob/c8df5cf74a2b495ccbc8b25a29c1692391c505f3/doc/abi_version_registry.json#L9
You need to install node.js version 10.x. Thanks.

**Comment by bimalkjha** [comment]
@lhimo Let us know if you are using vscode or electron. I think reinstalling the ibm_db should fix the issue if problem is not with your installed node.js version. Thanks.

**Comment by lhimo** [comment]
@bimaljha Running "node -v" I get "v10.16.0"

I'm using vscode, I tried "npm install ibm_db" and "npm install" but I get the same error

**Comment by bimalkjha** [comment]
@lhimo What is the version of your vscode? Please check the "Help -> About" window and share screenshot. Check the node.js version their and you need to install same version of node.js. Then install ibm_db. it should work. thanks.

**Comment by lhimo** [comment]
The problem was that cypress is using a bundle version of node js, I finally managed to fix this 😃

Now I'm trying to return the data from the query, ho can I do this from inside the conn.query() function?

So far I tried:
```
function queryDB (dbConfig, query) {
    ibmdb.open(dbConfig, function (err, conn) {
        if (err) {
          return console.log(err);
        }
        return conn.query(query, function (err, data) {
            if (err) console.log(err);
            else return data
            conn.close(function () {
                console.log('done');
            });
        });
    });
    return data
}
```

**Comment by bimalkjha** [comment]
@lhimo Its a logical programming problem. Your return will not work with callback function. Better to use conn.querySync() which will return data and then you can return. Else, define a new variable say dataResult outside queryDB and assign data to this variable inside conn.query. Thanks.

**Comment by lhimo** [comment]
For posterity, I ended up doing something like this on `plugin/index.js`:
```
const ibmdb = require('ibm_db');
var dataResult;

function queryDB (dbConfig, query) {
  
      return new Promise((resolve, reject) => {
          ibmdb.open(dbConfig, function (err, conn) {
          if (err) {
              console.log('connKO');
              return reject(err);
          }
          conn.query(query, function (err, data) {
              if (err) {
                  conn.close(function () {
                  console.log('doneKO');
                  console.log(err);
                  return reject(err)
                  });
              }
              else {
                  conn.close(function () {
                  console.log('doneOK');
                  dataResult = data;
                  return resolve(dataResult)
                  });
              }
          });
      });
  })
  }

module.exports = (on, config) => {
    on('task', {
        queryDatabase ({ dbConfig, query }) {
            console.log('%s, %s', dbConfig, query)
            return queryDB(dbConfig, query)
        }
    })
}
```

and in my spec file:
```
      cy.task('queryDatabase', { dbConfig: Cypress.env('db'), query: 'SELECT * FROM TABLE'}).then((result) =>{
        cy.log(result);
      })
```

**Comment by bimalkjha** [comment]
@lhimo Ok. So, using above code, your application works fine and are you able to get desired data or still have some issue? I think your problem is solved now, so please close the issue. Thanks.

**Comment by lhimo** [comment]
Solved! thanks

**Comment by Akhnatenn** [comment]
Hi i did the same, but im getting an error. 


index.js

const ibmdb = require('ibm_db');
var dataResult;

function queryDB (dbConfig, query) {
  
      return new Promise((resolve, reject) => {
          ibmdb.open("DATABASE=cards;HOSTNAME=192.168.150.182;PORT=9209;PROTOCOL=TCPIP;UID=username;PWD=password;", function (err, conn) {
            // SERVER=inst0016_drt_06;DATABASE=cards;HOSTNAME=192.168.150.182;PORT=7306;PROTOCOL=TCPIP; 
            if (err) {
              console.log('connKO');
              return reject(err);
          }
          conn.query(query, function (err, data) {
              if (err) {
                  conn.close(function () {
                  console.log('doneKO');
                  console.log(err);
                  return reject(err)
                  });
               
              }
              else {
                  conn.close(function () {
                  console.log('doneOK');
                  dataResult = data;
                  return resolve(dataResult)
                  });
              }
          });
      });
  })
  }

module.exports = (on, config) => {
    on('task', {
        queryDatabase ({ dbConfig, query }) {
            console.log('%s, %s', dbConfig, query)
            return queryDB(dbConfig, query)
        }
    })
}


Testcase file

  it.only('testvcased',function(){

        cy.task('queryDatabase', { dbConfig: Cypress.env('db'), query: 'select count(switch_type)as CardName from mcp.aav_gen_opt_esi_map where aav_gen_opt_esi_map.switch_type = "MASTERCARD"'}).then((result) =>{
            cy.log(result);
          })
    })



![error](https://user-images.githubusercontent.com/100988542/156871952-fcd05bce-54a9-41fe-8490-612f58ca03ff.png)
