### ISSUE TITLE
Version of this package to version of lic file

### ISSUE THREAD

**Issue by kentonbmax** [ibmdb/node-ibm_db#741]
Where is this documented so that I can work with the version that matches my license file?

**Comment by kentonbmax** [comment]
currently we are using 11.1. and lts version of nodejs.

**Comment by bimalkjha** [comment]
@kentonbmax The inquired information is documented here: https://github.com/ibmdb/node-ibm_db#sql1598n
The default clidriver which comes with ibm_db require db2 v11.5 db2connect license. You can work with v11.1 license file too but you need to download dsdriver of version 11.1 from fix central, install it, set IBM_DB_HOME env var to the install directory of dsdriver and then install ibm_db. 
Let us know if you need more info. Thanks.

**Comment by kentonbmax** [comment]
Thank you. I got this working after installing the 11.1.4 and setting the env to C:\Program Files\IBM\IBM DATA SERVER DRIVER\bin
