### ISSUE TITLE
Stale connections in pool is not cleaned up after database restart and SQL30081N error persists after the database becomes available

### ISSUE THREAD

**Issue by tozhangkai** [ibmdb/node-ibm_db#742]
There's a related issue https://github.com/ibmdb/node-ibm_db/issues/569, and the fix was to clean up the stale connections in the pool ([see here](https://github.com/ibmdb/node-ibm_db/blob/1fde4bf221d7f8a56d84809725ffaa9f0466c2a3/lib/odbc.js#L458)). However, this fix doesn't always work as desired, leaving stale connections in the pool, causing intermittent but persistent SQL30081N errors in our web application, until we restart the entire application. We use the connection pool from node-ibm_db v 2.7.1 with `{ autoCleanIdle: true }`

The fix in `Database.prototype.checkConnectionError` uses `self.availablePool` on the connection to close other free connections in the pool when SQL30081N happens. The assumption is that the connection's `availablePool` is always pointing to the same array of the pool's `pool.availablePool[connStr]`. However, this is not always the case due to two bugs:

1. When getting a connection from the pool in [`Pool.prototype.open`](https://github.com/ibmdb/node-ibm_db/blob/1fde4bf221d7f8a56d84809725ffaa9f0466c2a3/lib/odbc.js#L1996) method for the first time, the connection's `db.availablePool` is assigned [here](https://github.com/ibmdb/node-ibm_db/blob/1fde4bf221d7f8a56d84809725ffaa9f0466c2a3/lib/odbc.js#L2103), before allocating the pool's `pool.availablePool[connStr]`. The allocation of `pool.availablePool[connStr]` happens in the method of returning the connection ([`db.close`](https://github.com/ibmdb/node-ibm_db/blob/1fde4bf221d7f8a56d84809725ffaa9f0466c2a3/lib/odbc.js#L2050).) So any connections created before the first one being returned have their `db.availablePool` pointing to a wild array, irrelevant to the pool's `pool.availablePool[connStr]` array, and thus breaking the error checking code on these connections.

2. When `autoCleanIdle` is enabled, and `Pool.prototype.cleanUp` gets called, the pool's `pool.availablePool[connStr]` is replaced with a new array, disconnecting it from the `availablePool` on all existing connections in the pool. The method uses `Array.filter` to take out and kill the idle connections [here](https://github.com/ibmdb/node-ibm_db/blob/1fde4bf221d7f8a56d84809725ffaa9f0466c2a3/lib/odbc.js#L2217). However, `Array.filter` returns a brand new array to `pool.availablePool[connStr]`.

You can test the 2 bugs by:

Test 1:
1. Create a pool with no option set
2. Get 10 connections from the pool, run a simple SQL (for example, `SELECT 1 FROM SYSIBM.SYSDUMMY1`) to ensure they are connected to the database, and then close them all. You now have 10 free connection in the pool
3. Restart your database or force applications all. That makes the connections in the pool stale
4. Try to get a connection from the pool and run the SQL - you'll see `SQL30081N` - this is fine. Then close it.
5. Repeat step 4 many times - you'll see regardless of how many times you try, you always get `SQL30081N`. You have to restart the application to get rid of it.

Test 2:
1. Create a pool with `autoCleanIdle` enabled, keep other options default, then set `pool.availablePool[connStr] = []` beforehand to workaround bug 1.
2. Get 5 connections from the pool, and then close them all. You now have 5 free connection in the pool
3. Get 10 connections from the pool, and then close them all. You now have 10 free connection in the pool
4. Restart your database or force applications all. That makes the 10 connections in the pool stale
5.  Try to get all 10 connections from the pool and run the SQL on all of them. You may see `SQL30081N` happening, which is fine if it happens only once. Close them all.
6. Repeat step 5 many times - you'll see regardless of how many times you try, you'll always have `SQL30081N` for some of the connections.

**Comment by bimalkjha** [comment]
@tozhangkai Thanks for detailed analysis report. I am looking into code to see how to fix these problems.
Btw, the test file https://github.com/ibmdb/node-ibm_db/blob/master/test/test-bad-pool-connection-issue-42.js is intended to test the similar scenario. It would help us if you can look into this test file, modify it to show the behavior of test1 and test2; and share the updated test file here to repro the problem. Thanks.

**Comment by sakesun** [comment]
Any update on this ?

**Comment by bimalkjha** [comment]
@sakesun We have pushed fix of this issue with latest commit. It'll be available as part of next release. Thanks @tozhangkai for reporting it. Now both reported issue 1 & 2 are fixed. We have removed db.availablePool from code. Hence, closing this issue now. Thanks.
