### ISSUE TITLE
suppress showDownloadProgress() log entries

### ISSUE THREAD

**Issue by ibmrcruicks** [ibmdb/node-ibm_db#743]
showDownloadProgress() generates 3000-4000 log entries showing working function of download -- 
for "batch" installs, can this be suppressed or changed to show a start with expected bytes, an end with retrieved bytes, and an error with the amount downloaded on failure?

The logging floods what should be a 50-100  entry npm install log, with unnecessary, uninteresting and unhelpful messages, which slow down the progress of the application installation

**Comment by ibmrcruicks** [comment]
IBM_DB_INSTALLER_QUIET = YES
export  IBM_DB_INSTALLER_QUIET

for example

**Comment by bimalkjha** [comment]
@ibmrcruicks We'll try to implement this enhancement request. Thanks.

**Comment by ibmrcruicks** [comment]
got a likely date/timeframe for this?

**Comment by bimalkjha** [comment]
@ibmrcruicks We have picked up this request and code change will be added this week so that it would be part of next release of ibm_db. Thanks.

**Comment by bimalkjha** [comment]
Code change has been delivered. It'll part of next release of ibm_db. Hence, closing the issue now. Thanks.

**Comment by ibmrcruicks** [comment]
thanks -- I can see how this works for individual installs, but how does this mechanism get invoked from a package.json  dependencies list?

**Comment by bimalkjha** [comment]
@ibmrcruicks You can set below env vars:
`export npm_config_loglevel=warn` => It is equivalent to '--quiet' option.
`export npm_config_loglevel=silent`  => It is equivalent to '--silent' option.
Thanks.

**Comment by ibmrcruicks** [comment]
a-ha! thanks -- will give that a go in the node-red installation  process
