### ISSUE TITLE
verbose stack Error: ibm_db@2.7.2 install: `node installer/driverInstall.js`

### ISSUE THREAD

**Issue by davidmrg** [ibmdb/node-ibm_db#744]
Hi folks.
I tried to install a project (by running git clone in advance) that was originally developed in a old node.js version. The project originally used the ibm_db version 2.4.0, therefore I modified the line in package.json from "ibm_db": "2.4.0" to "ibm_db": "2.7.2" in order to make the install with an updated version of the ibm_db.

After running npm install, the following error appears:

`57633 verbose stack Error: ibm_db@2.7.2 install: `node installer/driverInstall.js`
57633 verbose stack Exit status 1
57633 verbose stack     at EventEmitter.<anonymous> (/Users/davidmramirez/.nvm/versions/node/v10.23.2/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
57633 verbose stack     at EventEmitter.emit (events.js:198:13)
57633 verbose stack     at ChildProcess.<anonymous> (/Users/davidmramirez/.nvm/versions/node/v10.23.2/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
57633 verbose stack     at ChildProcess.emit (events.js:198:13)
57633 verbose stack     at maybeClose (internal/child_process.js:982:16)
57633 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
57634 verbose pkgid ibm_db@2.7.2
57635 verbose cwd /Users/davidmramirez/Desktop/Onboarding/onboardingMan18022021v8.11.4_ibm_db@2.4.0/onboarding-management
57636 verbose Darwin 19.6.0
57637 verbose argv "/Users/davidmramirez/.nvm/versions/node/v10.23.2/bin/node" "/Users/davidmramirez/.nvm/versions/node/v10.23.2/bin/npm" "install"
57638 verbose node v10.23.2
57639 verbose npm  v6.14.10
57640 error code ELIFECYCLE
57641 error errno 1
57642 error ibm_db@2.7.2 install: `node installer/driverInstall.js`
57642 error Exit status 1
57643 error Failed at the ibm_db@2.7.2 install script.
`

Any suggestion will be really appreciated, 

Thanks and regards.

**Comment by bimalkjha** [comment]
@davidmrg Please run "npm install ibm_db --verbose" command and share the complete output. In current shared error, I do not see much info about error to find the root cause. Thanks.

**Comment by davidmrg** [comment]
Hi bimalkjha, thank you su much for replying. I already found a solution. I ran npm install ibm_db@2.7.2 on the old node.js version, (v8.11.4), committed and pushed to a repository including the package.json files, changed my node version with nvm  (v10.23.2), git clonned and installed everything back, and it worked fine. Thanks again!
