### ISSUE TITLE
Compatible version of node

### ISSUE THREAD

**Issue by janaanba** [ibmdb/node-ibm_db#746]
Facing some issues with incompatible node versions

Kindly share the compatible version of node for ibm_db version 2.4.1 and 2.5.0

For centOs and macOs

**Comment by bimalkjha** [comment]
@janaanba Please use `npm install ibm_db@2.7.2` command to install latest version of ibm_db which works on CentOS and MacOS. If you are facing any issue with latest version of ibm_db, please share the complete output of `npm install ibm_db@2.7.2` command. Thanks.

**Comment by janaanba** [comment]
@bimalkjha Due to our project requirements we cannot upgrade the ibm_db, could you please share the compatible version of node for ibm_db version 2.4.0 and 2.5.1. No problem if it requires different version of node for centOs and macOs.

**Comment by bimalkjha** [comment]
@janaanba Compatible versions < v12.x. So, I think you use latest version of node.js v10.x. If 10.x do not work, then try with node.js version 8.x. Thanks.
