### ISSUE TITLE
Using this package with Cypress

### ISSUE THREAD

**Issue by hassaanmasood** [ibmdb/node-ibm_db#748]
I have a very specific requirement. I want to use this module alongside Cypress Testing Package in Visual Studio Code. For that purpose I need complied version of this. 

Please tell me a way on how to do this.

**Comment by bimalkjha** [comment]
@hassaanmasood To compile `ibm_db` in vscode environment, open command prompt, cd to ibm_db directory and execute "npm install --vscode" command. If you are on Windows system, then Visual Studio along with C++ compiler must be installed in the system and directory of msbuild.exe should be in PATH system environment variable. Thanks.
