### ISSUE TITLE
Problem to connect with ssl

### ISSUE THREAD

**Issue by janaanba** [ibmdb/node-ibm_db#749]
I'm facing an issue while connecting my DB2 server through ssl connection.

The problem is as follows:
[IBM][CLI Driver] SQL30081N  A communication error has been detected. 
Communication protocol being used: "TCP/IP".  
Communication API being used: "SOCKETS". 

OS: CentOs

Also, i would like to know if there is any other possibility for creating an ssl connection other than .arm file and keystore??

Whether GsKit software is not available for MacOS??

Thanks in Advance!!

**Comment by bimalkjha** [comment]
@janaanba This error tells that either server is not configured to accept SSL connection at the used port or you are using a wrong port number in connection string. Please verify the server configuration by executing this db2 command on db2 server system: `db2 get dbm cfg | grep SSL`.  The SSL port is the value of `SSL service name                         (SSL_SVCENAME) =`.

If port is correct, then make sure you are using `Security=SSL;SSLServerCertificate=<full_path_of_certificate_file>` in connection string. Check [this doc](https://github.com/ibmdb/node-ibm_db/blob/master/APIDocumentation.md#SSLConnection) for more info about SSL connection using `ibm_db` package.

GSKit Software should be available for MacOS too. A customer can download it from IBM Passport Advantage website. For detail info about GSKit download and Installation, please check this db2 knowledge center page: https://www.ibm.com/support/knowledgecenter/en/SSEPGG_11.5.0/com.ibm.swg.tivoli.gskit.install.doc/doc/c0055353.html

If you have Certificate file generated for client from server in any format, then you need not to install GSKit on MacOS system. If you install Db2 Server, GSKit also get installed in the system along with server, so you need not to install it separately.
On client system, no need to create keystoredb if you need to use single certificate file for secure connection. Just use Security and SSLServerCertificate keywords in connection string.
For secure connection suing `ibm_db` package, we must need to use GSKit libraries. GSKit libraries comes with clidriver that get installed by ibm_db when you run `npm install ibm_db`. Recommended file extension is .arm but .cert file can also be used for secure connection. If you need to use more than once certificate file, then keystore db is must.
Thanks.
