### ISSUE TITLE
BigInt data type with ibm_db@2.7.2

### ISSUE THREAD

**Issue by lgwrld** [ibmdb/node-ibm_db#750]
Starting from version 2.7.2, the BigInt data types are returned as number. Up to version 2.7.1, BigInt were returned as string.
Having a value like this: 2234567890 into a BigInt Column, the select query of this table done via ibm_db returns wrong results.

Code Snippet based on examples/singleRowFetch.js:

```
...
conn.querySync("create table mytab (c1 bigint, c2 varchar(20))");
conn.querySync("insert into mytab values (2234567890, 'bimal')");
// Select data from table
conn.queryResult("select * from mytab", function (err, result) {
...
```

It returns :
{ C1: -272669936, C2: 'bimal' }
Instead of 
{ C1: 2234567890, C2: 'bimal' } 

I tested both on Linux and MacOS. 
The issue occurs only when data in the BigInt column is large.

**Comment by cpibm** [comment]
I also faced this issue with 2.7.2 and it broke the application, had to revert back to 2.7.1 for it to work properly.

**Comment by rcronin** [comment]
Having this same issue. Please fix asap!

**Comment by world2mark** [comment]
> Having this same issue. Please fix asap!

Problem for me too.
NodeJS app: BIGINT values that are large are being returned as the value 1.  

My current workaround is SELECT CAST(MyLargeVal as nvarchar(20)) AS MyLargeVal FROM LargeTableTest;

(Casting the value to strings give accurate value as a string.  Javascript natively supports large integers so I'd expect it to work.

**Comment by mikaello** [comment]
This seems to be the offending commit: https://github.com/ibmdb/node-ibm_db/commit/9df778efa2a7d7b949825b907aa18e9fb5ae7398 

A long in C++ is 4 bytes, and a [BigInt in Oracle](https://docs.oracle.com/javadb/10.8.3.0/ref/rrefsqlj30435.html) is 8 bytes. It can seem from number conversion that `BigInts` fall in the `else`-block:

https://github.com/ibmdb/node-ibm_db/blob/822f2dcfddeb3f8438723d37cbd061f3635d3fb0/src/odbc.cpp#L431-L466

...  and does not get casted. 

In C++ you have the type `long long` which is 8 bytes, maybe a another if-else is the solution:

```c++
       else if((int)len == sizeof(long long)){ 
         return scope.Escape(Nan::New<Number>((long long)value)); 
       } 
```

**Comment by bimalkjha** [comment]
@lgwrld pushed the fix on github. It would be available with next release of ibm_db. Thanks.
