### ISSUE TITLE
DB Pool without init and max size

### ISSUE THREAD

**Issue by giacomobartoli** [ibmdb/node-ibm_db#751]
What if I create and use a new Pool without init(n) and without setting a max pool size?
How does it behave?
Ex: it creates a pool with 1 connection and then it adds connections automatically according to the app needs?

This question stems from the fact that is not easy to estimate a max pool size in my case.

```
var Pool = require("ibm_db").Pool
	, pool = new Pool()
    , cn = "DATABASE=dbname;HOSTNAME=hostname;PORT=port;PROTOCOL=TCPIP;UID=dbuser;PWD=xxx";

pool.open(cn, function (err, db) {
	if (err) {
		return console.log(err);
	}
```

**Comment by bimalkjha** [comment]
@giacomobartoli It creates a pool with 1 connection and then it adds connections automatically according to app need.

**Comment by bimalkjha** [comment]
@giacomobartoli The number of active connections in the pool will keep growing on demand unless maximum number of connections supported by server is not reached. Under once pool instance, we can have maximum 512 active connections. So, in your case, pool can grow up to size of 512. After that any new connection request will have to wait until some connection get closed and get available for new request within 60 seconds as set [here](https://github.com/ibmdb/node-ibm_db/blob/master/lib/odbc.js#L1993).  After 60 seconds, SQL30081N error will get returned. Thanks.

**Comment by giacomobartoli** [comment]
Thank you @bimaljha for all the details.
