### ISSUE TITLE
db2cli not found on MacOS Catalina install of ibm_db

### ISSUE THREAD

**Issue by drtrotter74** [ibmdb/node-ibm_db#753]
I am trying to connect node.js to Db2 for z/OS database.  I suspected an issue with some of the rdbms binds so I tried to run the db2cli bind command on the mac end.   db2cli is not found.  Is there a problem with my ibm_db install on MacOS?

**Comment by bimalkjha** [comment]
@drtrotter74 You need to add location of db2cli in PATH system environment variable, then it can be executed from anywhere. 
Otherwise, you can just `source ibm_db/installer/setenv.sh` and then run the bind command. It should work. Thanks.

**Comment by drtrotter74** [comment]
drtrotter@Davids-MacBook-Pro node_modules % source ./ibm_db/installer/setenv.sh
./ibm_db/installer/setenv.sh:5: command not found: db2cli
./ibm_db/installer/setenv.sh:7: = not found
drtrotter@Davids-MacBook-Pro node_modules %

**Comment by drtrotter74** [comment]
drtrotter@Davids-MacBook-Pro node_modules % source ./ibm_db/installer/setenv.sh
./ibm_db/installer/setenv.sh:5: command not found: db2cli
./ibm_db/installer/setenv.sh:7: = not found
drtrotter@Davids-MacBook-Pro node_modules %

**Comment by drtrotter74** [comment]
I restored my .setenv.sh back to original.  When I do a source. setenv.sh I get:  

drtrotter@Davids-MacBook-Pro installer % source ./setenv.sh                    
./setenv.sh:5: = not found

**Comment by drtrotter74** [comment]
I think I found part of the issue......macOS is not using zsh as the default shell, and it has some issues with the setenv.sh script.  I switched to bash shell and not the setenv.sh is running
