### ISSUE TITLE
openSync() and new Pool() taking an extremely long time

### ISSUE THREAD

**Issue by mdgozza** [ibmdb/node-ibm_db#757]
We have been noticing extremely long times to make a query with the ibm_db module. 
In an effort understand what is taking so long, we have broken the module down into performance tests. 

> EDIT: We use this module at version 2.7.1 and the db2_cli_driver at 11.5.5.0 when experiencing these issues.

We see unusual behavior with `openSync` and  `new Pool()` taking extremely long amounts of time.
Internal to the module, it looks like `new odbc.Obdc()` might be the one taking a long time - but this is just a guess.

a lightweight example looks like this:

```javascript
const ibmd = require('ibm_db');
function ibmQueries(){
  console.log("starting ibm single query")
  performance.mark("ibmQueries-start");
  performance.mark("ibmConnectionCreate-start")
  const ibmdbCon = ibmd.openSync(ibmCliConStr);
  performance.mark("ibmConnectionCreate-end")
  performance.mark("ibmSingleQuery-start")
  const cliResult = ibmdbCon.querySync(getQuery());
  performance.mark("ibmSingleQuery-end");
  performance.mark("ibmQueries-end")
}
```

and the performance output shows connection create taking an extremely long time.
![image](https://user-images.githubusercontent.com/9098106/111791709-d9c6f280-8899-11eb-8f58-66ac8a9854ae.png)

Any thoughts or directional debugging to understand more about why this could be taking so long?
We have tried both with node-odbc and node-jdbc and did not experience such an issue. 
We may even be considering to moving from ibm_db to node-odbc or node-jdbc because of this.

Thanks so much for your time and support!

**Comment by mdgozza** [comment]
Update:

Further debugging has revealed that the issue might not be directly related with the javascript portion nor the C++ portion of this module but rather with the db2 cli driver that is downloaded as a part of the installation of this node_module.

When using the `node-odbc` node_module with the ibm db2 cli driver ( the same one that is installed with `ibm_db` ) we found the exact same 40 second startup but when attempting to get a connection via the `node-odbc` node_module.

In this instance, our connection string looks to be as follows:

```Driver={IBM CLI ODBC Driver};DATABASE=S1070DAC;HOSTNAME=${DB2_HOST};UID=${DB2_USER};PWD=${DB2_PASS};PORT=446;PROTOCOL=TCPIP```

It is important to note that we **DO NOT** have this bug when using the **IBM i Access ODBC Driver**. However that driver is not installed with this `ibm_db` module.

In those cases, the connection string looks to be as follows:
```Driver={IBM i Access ODBC Driver};System=${DB2_HOST};Port=446;UID=${DB2_USER};Password=${DB2_PASS};```

**Comment by bimalkjha** [comment]
@mdgozza I would suggest to update connection info in file `config.testConnectionStrings.json` and run below commands to verify the connection time and collect db2 trace to look further. If you have a simple repro program you can collect trace for that program too and share the generated trace files (1.* files) along with your repro program. We have lots of sample programs under `ibm_db\test` directory which uses openSync() function. You can use any one and modify as per your usages scenario.
```
cd ibm-db\test
node test-querySync-select.js
.\trace test-querySync-select.js
```
Thanks.

**Comment by bimalkjha** [comment]
If you are still facing this issue, please share the requested file here for further investigation. Thanks.
