### ISSUE TITLE
unable to install on AIX

### ISSUE THREAD

**Issue by bzhuibm** [ibmdb/node-ibm_db#76]
Got the err msg as below. It seems the download url for DB2 ODBC CLI Driver is wrong. http://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/aixppc64_odbc_cli.tar.gz does not exist. BUT http://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/aix64_odbc_cli.tar.gz exists.

> ibm_db@0.0.15 install /ibm/node/node_modules/ibm_db
> node installer/driverInstall.js

Downloading DB2 ODBC CLI Driver from http://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/aixppc64_odbc_cli.tar.gz...
/ibm/node/node_modules/ibm_db/installer/driverInstall.js:159
            log( "Unable to download IBM ODBC and CLI Driver from " +
            ^

**Comment by bimalkjha** [comment]
Please try this command and let me know the result:
`npm install git+https://git@github.com/ibmdb/node-ibm_db.git`

Remove any older installation from the path of current directory before running this command. Thanks.

**Comment by GWlodarek** [comment]
I'm having this issue as well on AIX.
Using the command mentioned above @bimalkjha I got:

'''
> ibm_db@0.0.16 install /home/svtdbm2/node/node_modules/ibm_db
> node installer/driverInstall.js

Downloading DB2 ODBC CLI Driver from http://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/aix64_odbc_cli.tar.gz...
FATAL ERROR: node::smalloc::Alloc(v8::Handle<v8::Object>, size_t, v8::ExternalArrayType) Out Of Memory
IOT/Abort trap (core dumped)
'''

**Comment by bimalkjha** [comment]
@GWlodarek You are getting "Out of Memory" error. Seems your system has some memory issue. Please check on other system. Thanks.

**Comment by GWlodarek** [comment]
@bimalkjha The system had over 80 GB left in memory. The same issue happened on another machine.

**Comment by bimalkjha** [comment]
@GWlodarek here memory means RAM not HDD. try below commands:
ulimit -d unlimited
npm install ibm_db

**Comment by GWlodarek** [comment]
Yes, both machines have 80 GB of ram.

**Comment by bimalkjha** [comment]
@GWlodarek Have you tried "ulimit -d unlimited"?
If you run "ulimit -a" on you AIX, you can see memory allocated to data is very less like "data(kbytes)         131072". If you run "ulimit -d unlimited", it will remove such limitations on AIX and installation will work. Thanks.

**Comment by bimalkjha** [comment]
@GWlodarek If you are still getting "Out of Memory" error, please share the output of "ulimit -a" command. Thanks.

**Comment by smartmouse** [comment]
which AIX version? Is it AIX 6.x or AIX 7? Also which node version? Can you do a
node -e console.log("process.config")

**Comment by bimalkjha** [comment]
ibm_db has came out with a new version 0.0.17. This version has support for AIX platform. Please try it. Thanks.
