### ISSUE TITLE
my connection string has a semicolon (;) in the password value.

### ISSUE THREAD

**Issue by perale** [ibmdb/node-ibm_db#760]
my connection string is : dsn= DRIVER={DB2};DATABASE=SAMPLE;HOSTNAME=localhost;UID=user01;PWD=ps;WROD;PORT=8081;PROTOCOL=TCPIP

and when I try to connect the following error occurs :

```
 [Error: [IBM][CLI Driver] SQL30082N  Security processing failed with reason "24" ("USERNAME AND/OR PASSWORD INVALID").  SQLSTATE=08001
]
  error: '[node-ibm_db] SQL_ERROR',
  sqlcode: -30082,
  message:
   '[IBM][CLI Driver] SQL30082N  Security processing failed with reason "24" ("USERNAME AND/OR PASSWORD INVALID").  SQLSTATE=08001\n',
  state: '08001' }
```

The question is: Is it possible to make the package to accept a password with semicolon sign in it, instead of forcing me to change the password of database to not have a semicolong sign in it ?

thanks.

**Comment by bimalkjha** [comment]
@perale As per IBM Documentation: https://www.ibm.com/support/knowledgecenter/en/SSEPGG_11.5.0/com.ibm.swg.im.dbclient.install.doc/doc/c0060749.html
`The ; character, ASCII code 0x3b, is not supported for use in passwords.`

ibm_db driver accepts database connection string in the form of keyword, values pair separated by semicolon. Next, keywords get extracted from connection string based on semicolon as terminator. So, a semicolon used in password or any other keyword value, caused problem in parsing. So, use of semicolon in not recommended. Please change your password to proceed. Thanks.
