### ISSUE TITLE
'DECIMAL' bindingParameters issue

### ISSUE THREAD

**Issue by jkamleh** [ibmdb/node-ibm_db#761]
Reference: https://github.com/ibmdb/node-ibm_db/blob/master/APIDocumentation.md#bindingparameters

Issue:
Have a stored procedure in IBM DB2 with one param like:
`IN P_IN_SOMEDECIMAL          	DECIMAL(12,0),`

Calling stored procedure with object as follows:
```
const queryObj = {
    sql: queryString, 
    params: bindingParameters
}
```

queryString equals:
`CALL SOME_PROCEDURE_NAME(?, ?, ?, ?)`

bindingParameters equals:
```
[
{ParamType: 'INPUT', DataType: 'DECIMAL', Data: **11 digit value here** },
...
]
```
or 
```
[
**11 digit value here**,
...
]
```

When i don't specify this param as a object or when using DataType: 'DECIMAL', i get the following error:
`[IBM][CLI Driver] CLI0111E Numeric value out of range. SQLSTATE=22003]`

I found my solution was to change **DataType**: 'DECIMAL' to **CType**: 'DECIMAL'. 

The problem is that the above code with DataType: 'DECIMAL' was working with 10 digit characters, it only started breaking and throwing IBM CLI Driver error listed above after we passed in 11 digits?

I found it's safest to just use CType. The documentation regarding these bindingParameters is also very light and doesn't mention much about CType, DataType, SQLType etc.

*Also* Using **DataType: 'DOUBLE'** works for the 11 digit value?

Working:
`{ParamType: 'INPUT', DataType: 'DOUBLE', Data: **11 digit value here** },`
and
`{ParamType: 'INPUT', CType: 'DECIMAL', Data: **11 digit value here** },`

Not working:
`{ParamType: 'INPUT', DataType: 'DECIMAL', Data: **11 digit value here** },`
and 
`**11 digit value here**`

**Comment by bimalkjha** [comment]
@jkamleh Please share a simple test program to reproduce the problem so that we can look into it further to find the root cause and can fix it. Thanks.

**Comment by bimalkjha** [comment]
@jkamleh ibm_db v2.7.4 has fixed this issue. Thanks.
