### ISSUE TITLE
[Error: [IBM][CLI Driver] SQL1109N  The command was not processed because the database manager failed to load the following DLL: "".  SQLSTATE=42724

### ISSUE THREAD

**Issue by sabhowal** [ibmdb/node-ibm_db#763]
Hello,
I am trying to connect to a remote IBM DB2 server with SSL certificate from a node.js application. I am using the below connection string - 
- **ibmdb = require('ibm_db');**
- **db2ConnectionString = "DATABASE=<name>; HOSTNAME=<host_name>; UID=<id>; PWD=<pwd>; PORT=60002; PROTOCOL=TCPIP; Security=SSL; SSLServerCertificate=<path to the .pem server certificate file>**

However I am getting the error as -
**" [Error: [IBM][CLI Driver] SQL1109N  The command was not processed because the database manager failed to load the following DLL: "".  SQLSTATE=42724"**
Also, when I try with a different server certificate file with I received from the DB2 DBA, I receive a different error as - 
**{ [Error: [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: 
"SSL".  Communication API being used: "SOCKETS".  Location where the error was detected: "".  Communication function detecting the error: "sqlccSSLSocketSetup".  Protocol specific error code(s): "414", "*", "*".  SQLSTATE=08001   
]
  error: '[node-ibm_db] SQL_ERROR',
  sqlcode: -30081,
  message:
   '[IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "SSL".  Communication API being used: "SOCKETS".  Location where the error was detected: "".  Communication function detecting the error: "sqlccSSLSocketSetup".  Protocol specific error code(s): "414", "*", "*".  SQLSTATE=08001\r\n',   
  state: '08001' }**
  Any one is aware of the issue or any comment on the same will be very helpful. Is it some gskit8 related error?

**Comment by bimalkjha** [comment]
@sabhowal Why are you getting two different error using two different certificate file? What is the difference between two files? The certificate file pointed by SSLServerCertificate keyword should be generated from database server for client use using the gskit command line tool on server system.

Let me know if you have any Db2 client or server installed in your system before installing ibm_db. Having different versions of gskit libraries in the system causes such issue. Also, make sure you are using SSL Port in the connection string.

If you are on non-windows system, you can try below commands, it should work:
```
cd ibm_db\installer
source setenv.sh
db2level
node test.js
```

If above steps do not resolve the issue, I'd suggest to find the `ibm_db\installer\testODBCConnection.sh` file, replace the `db2cli validate` command with `node test.js` where test.js is your repro program. Run this script, zip all generated files along with output of the script and share here. You need to use testODBCConnection.bat file on Windows. Also, share the output of db2level command.

Thanks.

**Comment by sabhowal** [comment]
Hi @bimaljha 

Thanks for the reply. I am not sure of the differences between the two .pem files. When I received the first one and got an error with it, I got the second one from the DB2 DBA.
Yes, I had local IBM DB installed and the dbm of the same was configured to have another set of .kdb file to connect to another remote DB2.
However switching to another system with NO DB2/ GSKit is giving an issue as - 
**"[Error: [IBM][CLI Driver] SQL10013N  The specified library "" could not be loaded.  SQLSTATE=42724
] {
  error: '[node-ibm_db] SQL_ERROR',
  sqlcode: -10013,
  state: '42724'
}"**
I am using a MAC.

**Comment by bimalkjha** [comment]
@sabhowal No. SSLServerCertificate keyword is introduced to remove dependency on creation of Keydbfile and stash file. When SSLServerCertificate is used, ibm_db internally creates keydb in memory, add the certificate file into it and proceed for connection. So, you need not to create the keydbfile and stash files. However, if there is any specific need for that and keydbfile is provided in connection string, ibm_db do not create the in-memory keydb but used the passed one. Thanks.
