### ISSUE TITLE
[Question] Are older versions of DB2 like 7.2 supported ?

### ISSUE THREAD

**Issue by UserSina** [ibmdb/node-ibm_db#769]
I couldn't find any mentioning of older versions so here I am asking.
If not, what are some alternatives I can use to execute `DB2 7.2` queries with `nodejs` ?

**Comment by bimalkjha** [comment]
@UserSina I think DB2 7.2 is more than 15 years old and minimum supported DB2 LUW server is Db2 V11.1 as of today. 
Anyway, you can try if it works for you out of the box. But, I am sure, this version of Db2 client or server is out of support.
