### ISSUE TITLE
ibmdb async problem

### ISSUE THREAD

**Issue by MapleWorld** [ibmdb/node-ibm_db#77]
Given 2 database connection strings, for example
```
var ibmdb = require('ibm_db');

//All correct info
var dbConnectString1 = 
'DRIVER={DB2};DATABASE=TEST;HOSTNAME=test111.hostname.com;UID=test;PWD=test;PORT=50000;PROTOCOL=TCPIP';

//All correct info but wrong port number or the database is down
var dbConnectString2 = 
'DRIVER={DB2};DATABASE=TEST;HOSTNAME=test222.hostname.com;UID=test;PWD=test;PORT=50000123;PROTOCOL=TCPIP';

server.listen(3000, function() {
	ibmdb.open(dbConnectString1, function(err, conn) {
	   	if (err) { 
	   		console.log(err.message); 
	   		return; 
	   	} else { 
	        conn.close(function() {
	            console.log("DB 1 Connection Closed");
	        });
	    }
	});

	ibmdb.open(dbConnectString2, function(err, conn) {
	   	if (err) { 
	   		console.log(err.message); 
	   		return; 
	   	} else { 
	        conn.close(function() {
	            console.log("DB 2 Connection Closed");
	        });
	    }
	});
});
```
dbConnectString1 wouldn't close the connection until dbConnectString2 print and return the error, which takes like 10 second if the port number is wrong or the database is down.

How to execute both connection async and close the ibmdb connection for dbConnectString1 without waiting for dbConnectionString to return error?

**Comment by rhtpandeyIN** [comment]
@MapleWorld are you still facing this issue? you first closed and then reopened the issue, that's why I am asking.

**Comment by MapleWorld** [comment]
@rhtpandeyIN yes, sorry for the confusion. Still having the problem

**Comment by rhtpandeyIN** [comment]
@MapleWorld can you briefly explain your problem, how can I reproduce this error? and why you are giving wrong port?

**Comment by MapleWorld** [comment]
Hey, I am building a multi-user website that allows the user to connect to their own db2 remotely, and the website will test the connection to the database making sure it is a valid connection before adding the connection string to the database, the problem that I am having is that, if one user typed their port number wrong or their database is down, none all other users must wait for like 10 second. 

You can reproduce the error by just copy and paste in my code and add 2 separate database connection string to it, with 1 of them close or wrong port number.

**Comment by rhtpandeyIN** [comment]
ok @MapleWorld thanks for description, once I got fix will update you.

**Comment by rhtpandeyIN** [comment]
This is working as designed. Let users call the node application independently, so that each user will have different process. Node.js is single threaded and it does not support multithreading. So, this behavior is obvious. thanks.
