### ISSUE TITLE
Release Timeline

### ISSUE THREAD

**Issue by castasint** [ibmdb/node-ibm_db#770]
Hi @bimalkjha ,

Could you please share some light on when the next version will be published to npm registry? Waiting for the fix for [https://github.com/ibmdb/node-ibm_db/issues/750](https://github.com/ibmdb/node-ibm_db/issues/750)

Thanks,
Hanuma

**Comment by marutgoyal** [comment]
Since the last version was published to NPM around 2 months ago, can we expect a new version soon - in the next 1 or 2 weeks?

**Comment by Akshay9790** [comment]
Hi @bimaljha , Even I am facing the issue mentioned in #[750](https://github.com/ibmdb/node-ibm_db/issues/750). I see that you have already made the required changes and checked in. Please let me know when will the next release be.

**Comment by bimalkjha** [comment]
Yes, it will be released by 15th June. Thanks.

**Comment by margoyal** [comment]
> Yes, it will be released by 15th June. Thanks.

Thanks @bimalkjha
