### ISSUE TITLE
Can't resolve 'bindings' in electron

### ISSUE THREAD

**Issue by hannapa1114** [ibmdb/node-ibm_db#772]
Hello, I am making electron-app. I want to connect to netezza db. so I install ibm_db and import ibm_db.
but error occur when building app .
I don't know why it didn't install when 'npm install ibm_db' 
how can I get binding.js file? 
thank you.

O.S.--> Windows 10, X64
Nodejs --> 14.15.4

![binding error](https://user-images.githubusercontent.com/49268125/120575741-93c30900-c45c-11eb-880c-570ec2208bbc.jpg)

**Comment by bimalkjha** [comment]
@hannapa1114 Use command `npm install ibm_db --vscode` to install ibm_db. Or, if you have already installed ibm_db, then `cd ibm_db` and run `npm install --vscode`. `--vscode` option is their to tell ibm_db that this installation is for electron framework as we need to include electron header files while building ibm_db for electron which is not required for normal installation. Thanks.

**Comment by hannapa1114** [comment]
@bimalkjha I tried that command and install successfully. it doesn't work yet. error message is changed. thanks for your help.
![1](https://user-images.githubusercontent.com/49268125/120727808-73f01b80-c516-11eb-915e-daac32be648e.JPG)
![2](https://user-images.githubusercontent.com/49268125/120727814-75b9df00-c516-11eb-952f-0cd3191a2308.JPG)
![3](https://user-images.githubusercontent.com/49268125/120727818-76eb0c00-c516-11eb-9337-f7d0fae73118.JPG)
![4](https://user-images.githubusercontent.com/49268125/120727822-78b4cf80-c516-11eb-826d-faf8ec828eb6.JPG)

**Comment by bimalkjha** [comment]
@hannapa1114 In the pasted log, we can see the message "node-ibm_db installed successfully". As long as this message comes, installation is good despite other errors. Please try to run your app and paste any error if you see.
If you face any issue, that should be due to the version of node.js. Probably you need to use the same version of node.js that is used by vscode 1.56. Thanks.

**Comment by hannapa1114** [comment]
@bimalkjha As see the last image, 'Could not locate the binding file.' error has occured when run the app. I think error change from 'Can't resolve binding file' to 'Could not locate the binding file'. How you think? thanks.

**Comment by bimalkjha** [comment]
@hannapa1114 You are using electron v12.0.4 which requires node.js v14.16.0. Your current node.js version is 14.15.4. So, I would recommend to install node.js v14.16.0 only and not other version. Then execute `npm install --vscode` under `ibm_db` directory and try. Thanks.

**Comment by hannapa1114** [comment]
@bimalkjha I tried but same error has occured. I will find other solution. I think it via server. Anyway, thanks for your help. Have a good day!
