### ISSUE TITLE
Installing ibm_db offline using IBM_DB_INSTALLER_URL

### ISSUE THREAD

**Issue by philip-leaper** [ibmdb/node-ibm_db#774]
Hi,

I'm trying to install the ibm_db package with IBM_DB_INSTALLER_URL set.  I have manually downloaded the cli driver and placed in a location referenced by that environment variable, but the npm install command results in a failure to find driverInstall.js - it doesn't seem to be creating the node module before attempting to execute the driver install.  Is there any guidance that can be provided?

```

180 verbose stack Error: ibm_db@2.7.3 install: `node installer/driverInstall.js`
180 verbose stack Exit status 1
180 verbose stack     at EventEmitter.<anonymous> (/opt/rh/rh-nodejs12/root/usr/lib/node_modules/npm/node_modules.bundled/npm-lifecycle/index.js:332:16)
180 verbose stack     at EventEmitter.emit (events.js:314:20)
180 verbose stack     at ChildProcess.<anonymous> (/opt/rh/rh-nodejs12/root/usr/lib/node_modules/npm/node_modules.bundled/npm-lifecycle/lib/spawn.js:55:14)
180 verbose stack     at ChildProcess.emit (events.js:314:20)
180 verbose stack     at maybeClose (internal/child_process.js:1022:16)
180 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
181 verbose pkgid ibm_db@2.7.3
182 verbose cwd /home/ibm-user/loopback/loopback-connector-server
183 verbose Linux 3.10.0-1160.25.1.el7.x86_64
184 verbose argv "/opt/rh/rh-nodejs12/root/usr/bin/node" "/opt/rh/rh-nodejs12/root/usr/bin/npm" "install" "ibm_db"
185 verbose node v12.21.0
186 verbose npm  v6.14.11
187 error code ELIFECYCLE
188 error errno 1
189 error ibm_db@2.7.3 install: `node installer/driverInstall.js`
189 error Exit status 1
190 error Failed at the ibm_db@2.7.3 install script.
190 error This is probably not a problem with npm. There is likely additional logging output above.
191 verbose exit [ 1, true ]
```

**Comment by bimalkjha** [comment]
@philip-leaper please share the complete output of below commands:
```
echo $IBM_DB_INSTALLER_URL 
npm install ibm_db
```
Note that if you have manually downloaded the clidriver then, do not untar it. The IBM_DB_INSTALLER_URL  should point to the full path of tar.gz file. If you have untared the clidriver, then set IBM_DB_HOME to full path of clidriver directory and then install ibm_db. Thanks.

**Comment by philip-leaper** [comment]
Thanks for the response - the $IBM_DB_INSTALLER_URL needs to be set to the containing folder of that file (not including the filename, right) because when I set it to the filename it fails looking for [path]/linuxx64_odbc_cli.tar.gz/linuxx64_odbc_cli.tar.gz

I subsequently tried extracting the clidriver file and setting IBM_DB_HOME to that location and got a little further, but ultimately failed with the following output:
(the 'connect ETIMEDOUT 104.20.23.46:443' is confusing me?  Why should it be trying to go out, this is an environment with no external access - the very reason I'm using the offline method)

```
> ibm_db@2.7.4 install /home/ibm-user/loopback/loopback-connector-server/node_modules/ibm_db
> node installer/driverInstall.js

platform =  linux , arch =  x64 , node.js version =  v12.21.0
make version = GNU Make 3.82
IBM_DB_HOME environment variable have already been set to -> /home/ibm-user/clidriver

Downloading of clidriver skipped - build is in progress...


Error: Command failed: node-gyp configure build  --IS_DOWNLOADED=false --IBM_DB_HOME="$IBM_DB_HOME"
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: connect ETIMEDOUT 104.20.23.46:443
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16)
gyp ERR! System Linux 3.10.0-1160.25.1.el7.x86_64
gyp ERR! command "/opt/rh/rh-nodejs12/root/usr/bin/node" "/opt/rh/rh-nodejs12/root/usr/lib/node_modules/npm/node_modules.bundled/node-gyp/bin/node-gyp.js" "configure" "build" "--IS_DOWNLOADED=false" "--IBM_DB_HOME=/home/ibm-user/clidriver"
gyp ERR! cwd /home/ibm-user/loopback/loopback-connector-server/node_modules/ibm_db
gyp ERR! node -v v12.21.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node-gyp configure build  --IS_DOWNLOADED=false --IBM_DB_HOME="$IBM_DB_HOME"'
}
npm WARN @loopback/model-api-builder@2.3.1 requires a peer of @loopback/repository@^3.7.0 but none is installed. You must install peer dependencies yourself.
npm WARN loopback-connector-server@0.11.0 No repository field.
npm WARN loopback-connector-server@0.11.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ibm_db@2.7.4 install: `node installer/driverInstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ibm_db@2.7.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ibm-user/.npm/_logs/2021-06-18T10_29_13_076Z-debug.log
```

**Comment by bimalkjha** [comment]
@philip-leaper This seems the main error: `gyp ERR! stack Error: connect ETIMEDOUT 104.20.23.46:443`
Please check output of `ping -a 104.20.23.46` from command prompt. It seems a Cloudflare IP Address as per this link: https://www.lookip.net/ip/104.20.23.46
I have node-gyp installed in my system and clidriver too. Removed internet connection from my laptop. So, after setting IBM_DB_HOME env var, I can run `npm install` under `ibm_db` directory. I do not see any issue and ibm_db get installed successfully.
Probably, node-gyp package is trying to download some dependent package from net. I would suggest to run `npm install -g node-gyp@3.6.2` first and then `npm install ibm_db`. Thanks.

**Comment by bimalkjha** [comment]
@philip-leaper `node-gyp` command is trying to download node.js header files and if there is no internet or no proxy configured, it will fail and hence installation of ibm_db. So, suggesting you to download node.js headers too and set tarball using below commands. It may solve your issue. Check last comment of issue #775 for more info.
```
COPY ./tarball/node-v12.21.0-headers.tar.gz /tmp/node-v12.21.0-headers.tar.gz
RUN npm config set tarball /tmp/node-v12.21.0-headers.tar.gz
```
Thanks.
