### ISSUE TITLE
binding array parameter using IN operator

### ISSUE THREAD

**Issue by bsandr** [ibmdb/node-ibm_db#776]
Are arrays only possible to use in inserts? I'm trying to create a select query like this:
`SELECT distinct
    contr
    FROM table  
    where inv in (?)`

but the array is ignored and only the first element is binded. Is there any way this would work?

**Comment by bimalkjha** [comment]
@bsandr Yes, arrays are only supported for Insert statements. So, it is array insert support.
The SQL that you mentioned is not supported by Db2. Thanks.
