### ISSUE TITLE
Unable to connect to DB2 when the password includes a semicolon

### ISSUE THREAD

**Issue by ptsk5** [ibmdb/node-ibm_db#777]
I just spent some time debugging why I cannot connect to the DB2 on IBM Cloud, and I realised that the password includes a semicolon which probably ruined the connection string very badly... 

There is no answer I would wait for. If this is a known limitation and something blocks you to put "values" into quotation marks, then everything is all right, and you can close this issue. 

Have a great day!

Jiri

**Comment by bimalkjha** [comment]
@ptsk5 Semicolon (;) is not a valid character for Db2 connection string keyword Password from clidriver. It is documented in Db2 Knowledge Center page here:
https://www.ibm.com/support/producthub/db2/docs/content/SSEPGG_11.5.0/com.ibm.swg.im.dbclient.install.doc/doc/c0060749.html
```
Password rules for drivers and CLPPlus

Starting in Version 10.1 Fix Pack 2, the ODBC, CLI, .NET data provider, and the CLPPlus interface support password values containing the ASCII code range of 0x20 to 0x7E.
Support for this range of characters is subject to the following limitations:

    The ; character, ASCII code 0x3b, is not supported for use in passwords.
```
Thanks.
