### ISSUE TITLE
Cannot write null to blob field

### ISSUE THREAD

**Issue by dongryphon** [ibmdb/node-ibm_db#778]
# Test Case

I am using version 2.7.4 but also version 2.5.3 and 2.6.4 (as suggested by https://github.com/ibmdb/node-ibm_db/issues/604).

I get this error:
```
  return self._executeSync();
              ^
Error: [IBM][CLI Driver][DB2/LINUXX8664] SQL0301N  The value of input variable, expression or parameter number "2" cannot be used because of its data type.  SQLSTATE=07006

    at ODBCStatement.odbc.ODBCStatement.executeSync (.../node_modules/ibm_db/lib/odbc.js:1601:15)
    at ibmdb.open (.../blob.js:39:19)
    at .../node_modules/ibm_db/lib/odbc.js:138:11
    at .../node_modules/ibm_db/lib/odbc.js:360:11
```

When I run this code:

```javascript
const ibmdb = require('ibm_db');

const connString = [
    'DATABASE=...',
    'HOSTNAME=...',
    'PORT=...',
    'PROTOCOL=...',
    'UID=...',
    'PWD=...'
].join(';');

const createTable = `create table Aaa (
    id CHAR(128) primary key not null,
    derp BLOB(65536)
)`;

const updateBlob = `merge into Aaa as T
USING (VALUES(?, ?))
    as V(id, derp)
on T.id = V.id
WHEN MATCHED THEN UPDATE SET
    T.derp = V.derp
WHEN NOT MATCHED THEN
    INSERT (id, derp)
    VALUES (V.id, V.derp)
`;

ibmdb.open(connString, (err, conn) => {
    if (err) {
        console.log(err);

        return;
    }

    let result = conn.querySync(createTable);

    let stmt = conn.prepareSync(updateBlob);

    result = stmt.executeSync(['Aaa_123', null]);

    result.closeSync();
    conn.closeSync();
});
```

## Notes

I have tried wrapping the null blob in `{ CType: 'BLOB', DataType: 'BLOB', Data: null }` and that does not always work. I am struggling to find a reproducible test case for that, but the above would be the best way to set the BLOB field to null in any respect.

**Comment by bimalkjha** [comment]
@dongryphon The statement `result = stmt.executeSync(['Aaa_123', null]);` is causing the problem. We need to pass `null` as bind parameter. Update code with below lines and it works fine.
```
    let param = { CType: 'BLOB', DataType: 'BLOB', Data: null };
    let result = conn.querySync(createTable);
    let stmt = conn.prepareSync(updateBlob);
    result = stmt.executeSync(['Aaa_123', param]);
    result.closeSync();
    data = conn.querySync('select * from Aaa;');
    console.log(data);
    conn.querySync('drop table Aaa;');
    conn.closeSync();
```
I have added your test program in `test/test-blob-insert.js` and pushed it as latest commit. You can run this test file to verify.
Thanks.

**Comment by rklbgiw** [comment]
hi my node js application crashes with the error 'zsh: segmentation fault  npm run start' when I bind one of INOUT param with BIGINT data type, I bind the param like mentioned below.

  const number  = {
    ParamType: 'INOUT',
    DataType: 'BIGINT',
    Data: null
  }

I need to pass only null for my as if I set NaN it's parsed to 0 at the DB end SP and it throws a validation error, I saw the call breaks in odbc.js at the line result = self.conn.querySync(sql, params); I use querySync in app code

**Comment by bimalkjha** [comment]
@rklbgiw Please try to reproduce issue using small standalone test program that has SP definition too. Open a new issue and share the repro test program so that we can easily reproduce the problem and investigate to find the root cause. Thanks.
