### ISSUE TITLE
Breaking change in whole table update statement behavior from 2.5.3 to 2.7.4

### ISSUE THREAD

**Issue by dongryphon** [ibmdb/node-ibm_db#779]
Not sure what version introduced this, but I am seeing this after upgrading to latest:

I run this:
```
update RESOURCETYPE set active = 0
```

And I now get an error when running such bulk update statements:
 ```
[IBM][CLI Driver][DB2/LINUXX8664] SQL0513W  The SQL statement will modify an entire table or view.  SQLSTATE=01504
```

I understand this can be accidental, but there are plenty of legitimate reasons to update the whole table.

This type of behavior change seems inappropriate for any release in the 2.x line, but aside from semver debates, how can this be disabled? Perhaps a connection option?

**Comment by bimalkjha** [comment]
@dongryphon You can use `IgnoreWarnings=1` in connection string to avoid such error as documented here; https://www.ibm.com/docs/en/db2/11.5?topic=keywords-ignorewarnings
Thanks.
