### ISSUE TITLE
Not getting expected results using Decimal output field in stored procedure

### ISSUE THREAD

**Issue by msmith-hpg** [ibmdb/node-ibm_db#782]
I have a stored procedure that is returning an incremented value.  The problem is, the value is not what I am being told should be returned.  For example, when I set the DataType value for the batchID field to 1 (I'm not sure what one is for, seems like a general catch all. I haven't seen the documentation on it) I get values like (100,101,102).  The weird thing is, I'm being told the values should be  30035,30036,30037.  

The datatype for the field is Decimal (15,3) however, when I use 3 as the DataType (for Decimal) I get:

 Error: [IBM][CLI Driver] CLI0143E  Invalid precision value. SQLSTATE=HY104

Here are the relevant parts of my code:

   ```
   let seqIdKey = 'mykey;
   let batchId = 0;
   let query = "call MySP(?, ?)";
    let params = [
        {ParamType: "INPUT", DataType:1, Data: seqIdKey, Length: 8}
        {ParamType: "OUTPUT", CType: 8, DataType: 3, Data: batchId, Length: 15}
    ];
```

Thank you for your help in advance.

**Comment by bimalkjha** [comment]
@msmith-hpg What is the version of ibm_db that you have installed? Please share below info:
1. ibm_db version
2. node.js version
3. Operating System name
4. DDL for mySP
Thanks.

**Comment by bimalkjha** [comment]
@msmith-hpg change the value of `batchId = 1.1`, it should work. Actually, value of Data should be a decimal value when a decimal data is expected in output parameter. Thanks.

**Comment by bimalkjha** [comment]
Although, using a decimal value for `Data` in output parameter should work around the problem; we have pushed fix for this issue along with test file as [this commit](https://github.com/ibmdb/node-ibm_db/commit/992a289c83566cd3905ec836a9f9ef4c357d48f9). Hence, closing the issue now. Thanks.
