### ISSUE TITLE
Having issue with installing ibm_db on windows

### ISSUE THREAD

**Issue by berlinbrown** [ibmdb/node-ibm_db#783]
With node version 10+ and Windows 10, we are having issues installing ibm_db on Windows.

Is there some flag missing

The "npm install" command succeeds

And downloaded the odbc driver for win 64.

mkdir /drivers
cd /drivers
Download https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz
set IBM_DB_INSTALLER_URL=/drivers
npm i -g --unsafe-perm ibm_db

But when running, we get the following errors.

Error: Could not locate the bindings file. Tried:
→ /home/src/app/node_modules/ibm_db/build/odbc_bindings.node
→ /home/src/app/node_modules/ibm_db/build/Debug/odbc_bindings.node
→ /home/src/app/node_modules/ibm_db/build/Release/odbc_bindings.node
→ /home/src/app/node_modules/ibm_db/out/Debug/odbc_bindings.node
→ /home/src/app/node_modules/ibm_db/Debug/odbc_bindings.node
→ /home/src/app/node_modules/ibm_db/out/Release/odbc_bindings.node
→ /home/src/app/node_modules/ibm_db/Release/odbc_bindings.node
→ /home/src/app/node_modules/ibm_db/build/default/odbc_bindings.node
→ /home/src/app/node_modules/ibm_db/compiled/8.9.3/linux/x64/odbc_bindings.node
at bindings (/home/src/app/node_modules/bindings/bindings.js:93:9)
at Object. (/home/src/app/node_modules/ibm_db/lib/odbc.js:31:31)
at Module._compile (module.js:635:30)
at Object.Module._extensions..js (module.js:646:10)
at Module.load (module.js:554:32)
at tryModuleLoad (module.js:497:12)
at Function.Module._load (module.js:489:3)
at Module.require (module.js:579:17)

**Comment by bimalkjha** [comment]
@berlinbrown Please share the complete output of `npm install ibm_db` command. If you think it installed correctly, then update database connection info in `ibm_db\test\config.testConnectionStrings.json` and share the complete output of `node test\test-basic-test.js` command. Thanks.

**Comment by bimalkjha** [comment]
@berlinbrown Are you still facing this issue? If yes, please share the requested info. Thanks.

**Comment by berlinbrown** [comment]
Yea, it is this an issue.  Here is output from from npm install

C:\cygwin64\home\USER\git-main5\penshop-orders-proc>npm install ibm_db
 
> ibm_db@2.7.4 install C:\cygwin64\home\USER\git-main5\penshop-orders-proc\node_modules\ibm_db
> node installer/driverInstall.js
 
platform =  win32 , arch =  x64 , node.js version =  v10.16.3
IBM_DB_HOME environment variable have already been set to -> C:\cygwin64\home\USER\git-main5\penshop-orders-proc\app\drivers
 
Downloading of clidriver skipped - build is in progress...
 
 
C:\cygwin64\home\USER\git-main5\penshop-orders-proc\node_modules\ibm_db>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure build  --IS_DOWNLOADED=false --IBM_DB_HOME=$IBM_DB_HOME )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" configure build  --IS_DOWNLOADED=false --IBM_DB_HOME=$IBM_DB_HOME )
 
{ Error: Command failed: node-gyp configure build  --IS_DOWNLOADED=false --IBM_DB_HOME=$IBM_DB_HOME
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
gyp ERR! build error
gyp ERR! stack Error: Command failed: reg query "HKLM\Software\Microsoft\MSBuild\ToolsVersions" /s /reg:32
gyp ERR! stack ERROR: Registry editing has been disabled by your administrator.
gyp ERR! stack
gyp ERR! stack Can't find "msbuild.exe". Do you have Microsoft Visual Studio C++ 2008+ installed?
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:142:25
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:301:5)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "build" "--IS_DOWNLOADED=false" "--IBM_DB_HOME=$IBM_DB_HOME"
gyp ERR! cwd C:\cygwin64\home\USER\git-main5\penshop-orders-proc\node_modules\ibm_db
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
 
    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   'node-gyp configure build  --IS_DOWNLOADED=false --IBM_DB_HOME=$IBM_DB_HOME' }

**Comment by berlinbrown** [comment]
It looks like this is not an issue, still can't tell what fixed the error:

This seems to wrong properly. the test application:


C:\cygwin64\home\User\git-main5\penshop-orders-proc\node_modules\ibm_db>node test\test-basic-test.js
Trying to open a connection ...
... Got the connection.
insertedRows =  1
[ [ 1, 4, 5 ] ]
[]
Selected data with special character  =  { Error: [IBM][CLI Driver][DB2] SQLSTATE 01517: A character that could not be converted was replaced with a substitute character.
 
    at Database.querySync (C:\cygwin64\home\User\git-main5\penshop-orders-proc\node_modules\ibm_db\lib\odbc.js:829:26)
    at C:\cygwin64\home\User\git-main5\penshop-orders-proc\node_modules\ibm_db\test\test-basic-test.js:45:14
    at C:\cygwin64\home\User\git-main5\penshop-orders-proc\node_modules\ibm_db\lib\odbc.js:585:76
  error:
   '[node-ibm_db] Error in ODBCConnection::QuerySync while executing query.',
  sqlcode: 0,
  message:
   '[IBM][CLI Driver][DB2] SQLSTATE 01517: A character that could not be converted was replaced with a substitute character.\r\n',
  state: '01517' }
assert.js:84
  throw new AssertionError(obj);

**Comment by berlinbrown** [comment]
Can we run node db2 windows install with basic terminal or do we need something like mingw or cygwin?

**Comment by bimalkjha** [comment]
@berlinbrown You have just shared the 50% output of `npm install ibm_db`. Despite the pasted errors, as long as you see the message "node-ibm_db installed successfully!" at end, installation is good.

In second update, since you are able to run `node test\test-basic-test.js`, it tells installation is good. The errors are due to use of special characters in the test file and seems those characters are not supported by your system. But, your other node application should work fine.

Yes, you can run node db2 windows install with basic terminal. It has no dependency on mingw or cygwin.
Thanks.

**Comment by bimalkjha** [comment]
Since, `node test\test-basic-test.js` is running well without any error, so ibm_db has installed successfully. Closing the issue now. Thanks.
