### ISSUE TITLE
How to install on Apple Silicon / M1 Chip?

### ISSUE THREAD

**Issue by christo-ph** [ibmdb/node-ibm_db#784]
I am unable to get ibm_db to work on Apples M1 Chip, as the installer is complaining about:

```
platform =  darwin , arch =  arm64 , node.js version =  v16.5.0
make version = GNU Make 3.81
Mac OS 32 bit not supported. Please use an x64 architecture.
```

How can I get this to work?

**Comment by bimalkjha** [comment]
@christo-ph The arm64 platform is not supported, hence the error.  You need an x64 architecture chip to install it. Actually, IBM ODBC driver is not supported on arm64 chip for Macbook which is used by `ibm_db` internally for connectivity.

I do not have access to any Apple system with M1 chip, so I can not verify `ibm_db`, but you can give a try by following below steps:
```
1. Download https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/macos64_odbc_cli.tar.gz and 
untar it. You'll get clidriver directory.
2. export IBM_DB_HOME=full/path/of/clidriver
3. git clone https://github.com/ibmdb/node-ibm_db.git
4. cd node-ibm_db
5. npm install
```
If there is no error by `npm install` command, update the database connection string in `ibm_db\test\config.testConnectionStrings.json` file and save it. Then run `node test\test-basic-test.js` to verify the connectivity.

If it do not work, you can share the complete output of `npm install` and `node test-basic-test.js` commands to look further.
Thanks.

**Comment by christo-ph** [comment]
Hi @bimalkjha 

```console
$ npm install                                                                                                                                                           So 25 Jul 20:41:59 2021
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile

> ibm_db@2.7.4 install
> node installer/driverInstall.js

platform = darwin, arch = arm64, node.js version = v16.5.0
make version =GNU Make 3.81
IBM_DB_HOME environment variable have already set to -> /Users/xxx/coding/clidriver

Downloading of clidriver skipped - build is in progress...


added 63 packages, and audited 64 packages in 2s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

```
 node test/test-basic-test.js                                                                                                                                 2190ms  So 25 Jul 20:42:05 2021
/Users/xxx/coding/node-ibm_db/node_modules/bindings/bindings.js:135
  throw err;
  ^

Error: Could not locate the bindings file. Tried:
 → /Users/xxx/coding/node-ibm_db/build/odbc_bindings.node
 → /Users/xxx/coding/node-ibm_db/build/Debug/odbc_bindings.node
 → /Users/xxx/coding/node-ibm_db/build/Release/odbc_bindings.node
 → /Users/xxx/coding/node-ibm_db/out/Debug/odbc_bindings.node
 → /Users/xxx/coding/node-ibm_db/Debug/odbc_bindings.node
 → /Users/xxx/coding/node-ibm_db/out/Release/odbc_bindings.node
 → /Users/xxx/coding/node-ibm_db/Release/odbc_bindings.node
 → /Users/xxx/coding/node-ibm_db/build/default/odbc_bindings.node
 → /Users/xxx/coding/node-ibm_db/compiled/16.5.0/darwin/arm64/odbc_bindings.node
 → /Users/xxx/coding/node-ibm_db/addon-build/release/install-root/odbc_bindings.node
 → /Users/xxx/coding/node-ibm_db/addon-build/debug/install-root/odbc_bindings.node
 → /Users/xxx/coding/node-ibm_db/addon-build/default/install-root/odbc_bindings.node
 → /Users/xxx/coding/node-ibm_db/lib/binding/node-v93-darwin-arm64/odbc_bindings.node
    at bindings (/Users/xxx/coding/node-ibm_db/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/Users/xxx/coding/node-ibm_db/lib/odbc.js:57:31)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/Users/xxx/coding/node-ibm_db/test/common.js:1:12)
    at Module._compile (node:internal/modules/cjs/loader:1095:14) {
  tries: [
    '/Users/xxx/coding/node-ibm_db/build/odbc_bindings.node',
    '/Users/xxx/coding/node-ibm_db/build/Debug/odbc_bindings.node',
    '/Users/xxx/coding/node-ibm_db/build/Release/odbc_bindings.node',
    '/Users/xxx/coding/node-ibm_db/out/Debug/odbc_bindings.node',
    '/Users/xxx/coding/node-ibm_db/Debug/odbc_bindings.node',
    '/Users/xxx/coding/node-ibm_db/out/Release/odbc_bindings.node',
    '/Users/xxx/coding/node-ibm_db/Release/odbc_bindings.node',
    '/Users/xxx/coding/node-ibm_db/build/default/odbc_bindings.node',
    '/Users/xxx/coding/node-ibm_db/compiled/16.5.0/darwin/arm64/odbc_bindings.node',
    '/Users/xxx/coding/node-ibm_db/addon-build/release/install-root/odbc_bindings.node',
    '/Users/xxx/coding/node-ibm_db/addon-build/debug/install-root/odbc_bindings.node',
    '/Users/xxx/coding/node-ibm_db/addon-build/default/install-root/odbc_bindings.node',
    '/Users/xxx/coding/node-ibm_db/lib/binding/node-v93-darwin-arm64/odbc_bindings.node'
  ]
}
```

**Comment by bimalkjha** [comment]
@christo-ph Open file `ibm_db\installer\driverInstall.js` and remove check for x64 arch from line number [186](https://github.com/ibmdb/node-ibm_db/blob/master/installer/driverInstall.js#L186). i.e.
change `(platform == 'darwin' && arch == 'x64'))` to `(platform == 'darwin'))` and save the file. Then try from step 5 i.e. `npm install` and check. Thanks.

**Comment by christo-ph** [comment]
In addition to line 186 I had to change line 229 to

```
if(arch == 'x64' || arch == 'arm64') {
```

that the compile step started.

Output:

```
 npm install                                                                                                                                                    1.2m  So 25 Jul 20:59:17 2021

> ibm_db@2.7.4 install
> node installer/driverInstall.js

platform = darwin, arch = arm64, node.js version = v16.5.0
make version =GNU Make 3.81

****************************************
You are downloading a package which includes the Node.js module for IBM DB2/Informix.  The module is licensed under the Apache License 2.0. The package also includes IBM ODBC and CLI Driver from IBM, which is automatically downloaded as the node module is installed on your system/device. The license agreement to the IBM ODBC and CLI Driver is available in /Users/xxx/coding/node-ibm_db/installer/clidriver. Check for additional dependencies, which may come with their own license agreement(s). Your use of the components of the package and dependencies constitutes your acceptance of their respective license agreements. If you do not accept the terms of any license agreement(s), then delete the relevant component(s) from your device.
****************************************

Downloading DB2 ODBC CLI Driver from https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/macos64_odbc_cli.tar.gz ...

100.00% | 30120620 bytes downloaded out of 30120620 bytes.

Downloading and extraction of DB2 ODBC CLI Driver completed successfully.

  CXX(target) Release/obj.target/odbc_bindings/src/odbc.o

Error: Command failed: node-gyp configure build  --IS_DOWNLOADED=true --IBM_DB_HOME="$IBM_DB_HOME"
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@16.5.0 | darwin | arm64
gyp info find Python using Python version 3.9.6 found at "/opt/homebrew/opt/python@3.9/bin/python3.9"
(node:99041) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp info spawn /opt/homebrew/opt/python@3.9/bin/python3.9
gyp info spawn args [
gyp info spawn args   '/Users/xxx/.nvm/versions/node/v16.5.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/xxx/coding/node-ibm_db/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/xxx/.nvm/versions/node/v16.5.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/xxx/Library/Caches/node-gyp/16.5.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/xxx/Library/Caches/node-gyp/16.5.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/xxx/.nvm/versions/node/v16.5.0/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/xxx/Library/Caches/node-gyp/16.5.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/xxx/coding/node-ibm_db',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
In file included from ../src/odbc.cpp:29:
In file included from ../src/odbc.h:23:
In file included from ../node_modules/nan/nan.h:2884:
../node_modules/nan/nan_typedarray_contents.h:34:43: warning: 'GetContents' is deprecated: Use GetBackingStore. See http://crbug.com/v8/9908. [-Wdeprecated-declarations]
      data   = static_cast<char*>(buffer->GetContents().Data()) + byte_offset;
                                          ^
/Users/xxx/Library/Caches/node-gyp/16.5.0/include/node/v8.h:5590:3: note: 'GetContents' has been explicitly marked deprecated here
  V8_DEPRECATED("Use GetBackingStore. See http://crbug.com/v8/9908.")
  ^
/Users/xxx/Library/Caches/node-gyp/16.5.0/include/node/v8config.h:415:35: note: expanded from macro 'V8_DEPRECATED'
# define V8_DEPRECATED(message) [[deprecated(message)]]
                                  ^
In file included from ../src/odbc.cpp:29:
../src/odbc.h:27:10: fatal error: 'sqlcli1.h' file not found
#include <sqlcli1.h>
         ^~~~~~~~~~~
1 warning and 1 error generated.
make: *** [Release/obj.target/odbc_bindings/src/odbc.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/xxx/.nvm/versions/node/v16.5.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Darwin 20.5.0
gyp ERR! command "/Users/xxx/.nvm/versions/node/v16.5.0/bin/node" "/Users/xxx/.nvm/versions/node/v16.5.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build" "--IS_DOWNLOADED=true" "--IBM_DB_HOME=/Users/xxx/coding/node-ibm_db/installer/clidriver"
gyp ERR! cwd /Users/xxx/coding/node-ibm_db
gyp ERR! node -v v16.5.0
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok

    at ChildProcess.exithandler (node:child_process:397:12)
    at ChildProcess.emit (node:events:394:28)
    at maybeClose (node:internal/child_process:1067:16)
    at Socket.<anonymous> (node:internal/child_process:453:11)
    at Socket.emit (node:events:394:28)
    at Pipe.<anonymous> (node:net:672:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node-gyp configure build  --IS_DOWNLOADED=true --IBM_DB_HOME="$IBM_DB_HOME"'
}
npm ERR! code 1
npm ERR! path /Users/xxx/coding/node-ibm_db
npm ERR! command failed
npm ERR! command sh -c node installer/driverInstall.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxx/.npm/_logs/2021-07-25T18_59_37_543Z-debug.log

```

(was a new shell, without IBM HOME. Therefore the download.

**Comment by bimalkjha** [comment]
@christo-ph Now python3 is causing the issue. Node-gyp need python2 to work. 
Install python 2.7.x and set `npm config set python python2.7`, then try `npm install`. Thanks.

**Comment by christo-ph** [comment]
Actually, I get the same deprecated message as before.

**Comment by bimalkjha** [comment]
@christo-ph After checking the output of your npm install, I see below error which looks the root cause:
```
In file included from ../src/odbc.cpp:29:
../src/odbc.h:27:10: fatal error: 'sqlcli1.h' file not found
#include <sqlcli1.h>
         ^~~~~~~~~~~
1 warning and 1 error generated.
make: *** [Release/obj.target/odbc_bindings/src/odbc.o] Error 1
gyp ERR! build error
```
Need to set some environment variable to get this file. Better is to source file `ibm_db\installer\setevn.sh` and then run `npm install`. Thanks.

**Comment by bimalkjha** [comment]
@christo-ph Let me know if you are able to progress by sourcing `setenv.sh` file. Otherwise try below commands, it should work:
```
export PATH=/Users/xxx/coding/node-ibm_db/installer/clidriver/bin:/Users/xxx/coding/node-ibm_db/installer/clidriver/lib:$PATH
export DYLD_LIBRARY_PATH=/Users/xxx/coding/node-ibm_db/installer/clidriver/lib:$DYLD_LIBRARY_PATH
export INCLUDE=/Users/xxx/coding/node-ibm_db/installer/clidriver/include:$INCLUDE
cd /Users/xxx/coding/node-ibm_db
npm install
```
Thanks.

**Comment by smontoya24** [comment]
@christo-ph Have you been able to found a solution for this ? I recently changed to an Apple Computer with Apple Silicon, I was starting to change and test some projects and I encountered this same problem.  @bimalkjha Do you know if there is any information about a possible  version for Apple Silicon of the drivers ?

**Comment by bimalkjha** [comment]
@smontoya24 Download https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/macos64_odbc_cli.tar.gz and 
untar it. You'll get clidriver directory. Now, run below commands from terminal and share the output. Based on the result of below commands, we can suggest the next step:
```
cd clidriver
export PATH=`pwd`\bin:`pwd`:lib:$PATH
export DYLD_LIBRARY_PATH=`pwd`\lib:$DYLD_LIBRARY_PATH
cd bin
db2level
db2cli validate
```
Thanks.

**Comment by smontoya24** [comment]
@bimalkjha this is what I got in response of the commands.

db2level
-----------------------
<img width="588" alt="db2level" src="https://user-images.githubusercontent.com/86731015/128514686-99e787b8-3700-4e67-b4c1-a1b4d2b7675c.png">

db2cli validate
----------------------
<img width="583" alt="db2cli" src="https://user-images.githubusercontent.com/86731015/128514965-9022b677-ca08-4f9a-bfac-6becb9be3ecf.png">

After that I tried to run my node project, but I still have the same error 

Error: Could not locate the bindings file.

**Comment by bimalkjha** [comment]
@smontoya24 It looks good and I think it worked for @christo-ph. So, now follow below steps:
```
1. export INCLUDE=<full_path_of_clidriver>\include:$INCLUDE
2. export IBM_DB_HOME=<full_path_of_clidriver>
3. git clone https://github.com/ibmdb/node-ibm_db.git
4. cd node-ibm_db\installer
5. Open file ibm_db\installer\driverInstall.js and remove check for x64 arch from line number 186. i.e.
change (platform == 'darwin' && arch == 'x64')) to (platform == 'darwin')). 
6. Update line 229 of driverInstall.js as `if(arch == 'x64' || arch == 'arm64') {` and save the file.
7. cd node-ibm_db
8. npm install
```
If there is no error by npm install command, update the database connection string in `ibm_db\test\config.testConnectionStrings.json` file and save it. Then run `node test\test-basic-test.js` to verify the connectivity.

If it do not work, you can share the complete output of `npm install` and `node test-basic-test.js` commands to look further.
Thanks.

**Comment by bimalkjha** [comment]
@christo-ph @smontoya24 I have delivered the code changes to support installation on Apple Silicon. You can install `ibm_db` using command `npm install git+https://git@github.com/ibmdb/node-ibm_db.git` to verify it. After next release, you can install using `npm install ibm_db` command.
Please install using command `npm install git+https://git@github.com/ibmdb/node-ibm_db.git` and confirm here. Thanks.

**Comment by GuptaMegha** [comment]
@bimalkjha I am able to successfully installed ibm_db on Apple M1 with npm install git+https://git@github.com/ibmdb/node-ibm_db.git. But I am getting this error while using it : 
dyld: lazy symbol binding failed: Symbol not found: _SQLAllocHandle
  Referenced from: /Users/megupt/Projects/ecom-e2e-test/node_modules/ibm_db/build/Release/odbc_bindings.node
  Expected in: flat namespace

**Comment by GuptaMegha** [comment]
@bimalkjha I am able to install ibm_db using npm install git+https://git@github.com/ibmdb/node-ibm_db.git. Thanks !
But I am getting below error while using it:
dyld: lazy symbol binding failed: Symbol not found: _SQLAllocHandle
  Referenced from: /Users/megupt/Projects/ecom-e2e-test/node_modules/ibm_db/build/Release/odbc_bindings.node
  Expected in: flat namespace

**Comment by bimalkjha** [comment]
@GuptaMegha Please share the complete output of below commands:
```
otool -L /Users/megupt/Projects/ecom-e2e-test/node_modules/ibm_db/build/Release/odbc_bindings.node
otool -L /Users/megupt/Projects/ecom-e2e-test/node_modules/ibm_db/installer/clidriver/lib/libdb2.dylib
cd ibm_db/installer
source setenv.sh
db2level
db2cli validate -database "<dbname>:<hostname>:<port>" -connect -user <dbuser> -passwd <dbpass>
```
Update database connection info in above `db2cli validate` command. You can update connection info in `ibm_db\installer\testODBCConnection.sh` script too and share the complete output of script testODBCConnection.sh.
Thanks.

**Comment by bimalkjha** [comment]
@@christo-ph @smontoya24 @GuptaMegha `ibm_db@2.8.0` is released with support for MacOS M1 Chip system. Please have fresh installation of latest version of `ibm_db` and share the result. Thank you!

**Comment by cuauhfer** [comment]
@GuptaMegha did you solve the error? I'm currently getting the same output:
```
dyld: lazy symbol binding failed: Symbol not found: _SQLAllocHandle
  Referenced from: /Users/cuauhfer/Documents/project/node_modules/ibm_db/build/Release/odbc_bindings.node
  Expected in: flat namespace
```

I already tried reinstalling node, all my dependencies and xcode tools, but the same error persists.

ibm_db version: 2.8.0
SO: MacOS Big Sur 11.6
Chip: Apple M1

**Comment by bimalkjha** [comment]
@cuauhfer Please share the complete output of `npm install ibm_db` command. Such problem comes due to installation issue. Thanks.

**Comment by mdgozza** [comment]
Anyone who is still looking for help - feel free to try:

While we wait for ibm to officially support the new Apple arm chip, you can try to run the npm modules under Apple's Rosetta for cross compatibility ( although it will be a bit slower ) 
Simply asking npm to install with this in mind you need to run `npm install --target_arch=x64`

Alternatively, you can run your application in a docker container and ask docker to emulate it for you. ( also slower ) 
https://docs.docker.com/desktop/mac/apple-silicon/

by passing the --platform flag to the run command and setting it's value to `linux/x86_64`

_Originally posted by @mdgozza in https://github.com/ibmdb/node-ibm_db/issues/819#issuecomment-1042325919_

**Comment by batbrain9392** [comment]
> @christo-ph The arm64 platform is not supported, hence the error. You need an x64 architecture chip to install it. Actually, IBM ODBC driver is not supported on arm64 chip for Macbook which is used by `ibm_db` internally for connectivity.
> 
> I do not have access to any Apple system with M1 chip, so I can not verify `ibm_db`, but you can give a try by following below steps:
> 
> ```
> 1. Download https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/macos64_odbc_cli.tar.gz and 
> untar it. You'll get clidriver directory.
> 2. export IBM_DB_HOME=full/path/of/clidriver
> 3. git clone https://github.com/ibmdb/node-ibm_db.git
> 4. cd node-ibm_db
> 5. npm install
> ```
> 
> If there is no error by `npm install` command, update the database connection string in `ibm_db\test\config.testConnectionStrings.json` file and save it. Then run `node test\test-basic-test.js` to verify the connectivity.
> 
> If it do not work, you can share the complete output of `npm install` and `node test-basic-test.js` commands to look further. Thanks.

`ibm_db` is an optional dep from `@sequelize/core@7`, thus during `npm ci`, we faced the same issue in M1 Macs (arm64).
I ended up running just the first 2 steps from the above comment and `npm ci` ran fine, as shown below:
```
1. Download https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/macos64_odbc_cli.tar.gz and 
untar it. You'll get clidriver directory.
2. export IBM_DB_HOME=full/path/of/clidriver
```

However, in the official doc, there's instruction to install an intel version of [python](https://github.com/ibmdb/node-ibm_db/blob/master/INSTALL.md#steps-to-install-intel-python-after-verifying-setup) & [node](https://github.com/ibmdb/node-ibm_db/blob/master/INSTALL.md#steps-to-install-x64-version-of-nodejs). However, we already have python & node in the M1 Mac.
Also, intel version of node didn't work when I ran a node command after the installation.

**Comment by bimalkjha** [comment]
@batbrain9392 Follow the instructions as documented [here](https://github.com/ibmdb/node-ibm_db/blob/master/INSTALL.md#m1chip). If still you face problem, open a new issue with all the information as requested in issue template. Thanks.

**Comment by bimalkjha** [comment]
@christo-ph @GuptaMegha @batbrain9392 @smontoya24 @mdgozza @cuauhfer `ibm_db@3.3.0` has been released with native installation support for MacOS M1 Chip system with clidriver of version 12.1.0. You may install it and check. Thanks.
