### ISSUE TITLE
db2connect license version

### ISSUE THREAD

**Issue by mxcd** [ibmdb/node-ibm_db#788]
How can one identify the correct db2connect license version. I want to connect to a DB2 z/OS that has recently been upgraded to version 12. Do I also need db2connect license version 12 then, or is version 11.5 still fine as stated implicitly in the documentation?

**Comment by bimalkjha** [comment]
@mxcd Yes, version 11.5 is still fine as stated implicitly in the documentation.
The client side license file version depends on version of client which is unchanged in this case. Thanks.
