### ISSUE TITLE
Release new version on npm

### ISSUE THREAD

**Issue by tanganellilore** [ibmdb/node-ibm_db#791]
Team,

can you release new version on npm and github?

Actually all pool sync is not available in 2.7.4.

Thanks

**Comment by bimalkjha** [comment]
@tanganellilore Yes, it is on track and will be released before 10th Sep. Thanks.

**Comment by bimalkjha** [comment]
@tanganellilore `ibm_db@2.8.0` released now on npm and github. Thanks.
