### ISSUE TITLE
unable to open a connection using ibm_db module 

### ISSUE THREAD

**Issue by shruti729** [ibmdb/node-ibm_db#794]
Hi,
I am unable to open a connection using ibm_db module . 
it says connection not open when i am trying to query the database.

**Comment by bimalkjha** [comment]
@shruti729 Update database connection info in `test\config.testConnectionStrings.json` and then run `node test\test-basic-test.js`. Share the complete output of `node test-basic-test.js` file. If it works, then check your failing application code. If fails, then share the complete output of `npm install ibm_db` command. Thanks.

**Comment by shruti729** [comment]
Hi, 
It gives me below error if if i run the basic test

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'bindings'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\azureTask\IBM_DB_TestCode\node-ibm_db\lib\odbc.js:57:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! Test failed.  See above for more details.

**Comment by bimalkjha** [comment]
@shruti729 I requested complete output of `npm install ibm_db` command too. Please share that. Thanks.

**Comment by shruti729** [comment]
Hi,
below is the output of the command 'npm install ibm_db' 


ibm_db@2.8.0 install C:\azureTask\FO-7545\react-helloworld\acceptance\node_modules\ibm_db
> node installer/driverInstall.js

platform = win32, arch = x64, node.js version = v10.24.1
IBM_DB_HOME environment variable have already set to -> C:\Users\spandura\Downloads\db2_drivers\clidriver

Downloading of clidriver skipped - build is in progress...


C:\azureTask\FO-7545\react-helloworld\acceptance\node_modules\ibm_db>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure build  --IS_DOWNLOADED=false --IBM_DB_HOME=$IBM_DB_HOME )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" configure build  --IS_DOWNLOADED=false --IBM_DB_HOME=$IBM_DB_HOME )

{ Error: Command failed: node-gyp configure build  --IS_DOWNLOADED=false --IBM_DB_HOME=$IBM_DB_HOME
gyp ERR! find VS
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS checking VS2019 (16.11.31624.102) found at:
gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community"
gyp ERR! find VS - "Visual Studio C++ core features" missing
gyp ERR! find VS checking VS2017 (15.9.28307.1622) found at:
gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional"
gyp ERR! find VS - "Visual Studio C++ core features" missing
gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at findVisualStudio2013 (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16)
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at findVisualStudio2015 (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14)
gyp ERR! stack     at regSearchKeys (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16)
gyp ERR! stack     at regGetValue (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:301:5)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
gyp ERR! System Windows_NT 10.0.19043
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "build" "--IS_DOWNLOADED=false" "--IBM_DB_HOME=$IBM_DB_HOME"
gyp ERR! cwd C:\azureTask\FO-7545\react-helloworld\acceptance\node_modules\ibm_db
gyp ERR! node -v v10.24.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   'node-gyp configure build  --IS_DOWNLOADED=false --IBM_DB_HOME=$IBM_DB_HOME' }

node-gyp build process failed!

Proceeding with Pre-compiled Binary Installation.


===================================
ibm_db installed successfully.
===================================

npm WARN gulp-cucumber@0.0.24 requires a peer of cucumber@^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN bdd-cucumberjs-playwright-auto@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ ibm_db@2.8.0
added 39 packages from 26 contributors and audited 837 packages in 10.665s

54 packages are looking for funding
  run `npm fund` for details

found 3 vulnerabilities (1 low, 2 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by bimalkjha** [comment]
@shruti729 The above `npm install ibm_db` output is correct and it seems ibm_db has installed correctly. After above install, you try `node test-basic-test.js` again. If still getting same error, then share the contents of `ibm_db\build\Release\` directory. It should have `odbc_bindings.node` file. If file is present, then it should be an issue with system environment variable as you have set the `IBM_DB_HOME` variable. So, cd to ibm_db directory and share the output of below comamnds:
```
db2level
db2cli validate
```
If above commands gives error, then update database connection info in `test\config.testConnectionStrings.json` and run below commands one by one. Then share complete output of below commands:
```
cd C:\azureTask\FO-7545\react-helloworld\acceptance\node_modules\ibm_db
set PATH=C:\Users\spandura\Downloads\db2_drivers\clidriver\bin;C:\Users\spandura\Downloads\db2_drivers\clidriver\lib;%PATH%
set LIB=C:\Users\spandura\Downloads\db2_drivers\clidriver\bin;C:\Users\spandura\Downloads\db2_drivers\clidriver\lib;%LIB%
node test\test-basic-test.js
db2cli validate -database "dbname:hostname:port" -user dbuser -passwd dbpasswd -connect
```
Update the database connection info in above `db2cli validate` command before executing it. Thanks.

**Comment by shruti729** [comment]
Hi,
1. I retried executing test again and it gave below error:
Trying to open a connection ...
{ [Error: [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "149.81.181.98".  Communication function detecting the error: "selectForConnectTimeout".  Protocol specific error code(s): "0", "*", "*".  SQLSTATE=08001
]
  error: '[ibm_db] SQL_ERROR',
  sqlcode: -30081,
  message:
   '[IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "149.81.181.98".  Communication function detecting the error: "selectForConnectTimeout".  Protocol specific error code(s): "0", "*", "*".  SQLSTATE=08001\r\n',
  state: '08001' }
assert.js:84
  throw new AssertionError(obj);
  ^

AssertionError [ERR_ASSERTION]: { [Error: [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP". ... == null
    at C:\azureTask\IBM_DB_TestCode\node-ibm_db\test\test-basic-test.js:10:10
    at C:\azureTask\IBM_DB_TestCode\node-ibm_db\lib\odbc.js:142:11
    at C:\azureTask\IBM_DB_TestCode\node-ibm_db\lib\odbc.js:369:18




2.  odbc_bindings.node file is generated successfully under ibm_db\build\Release\


3. Below is the output for db2level command:

	DB21085I  This instance or install (instance name, where applicable: "*") uses
"64" bits and DB2 code release "SQL11055" with level identifier "0606010F".
Informational tokens are "DB2 v11.5.5000.1587", "s2011011400",
"DYN2011011400WIN64", and Fix Pack "0".
Product is installed at "C:\Users\spandura\Downloads\db2_drivers\clidriver"
with DB2 Copy Name "IBM Data Server Driver For ODBC and CLI".



4. Below is the output of  db2cli validate command
===============================================================================
Client information for the current copy (copy name: C_Users_spandura_Downloads_db2_drivers_clidriver):
===============================================================================

Client Package Type       : IBM Data Server Driver For ODBC and CLI
Client Version (level/bit): DB2 v11.5.5000.1587 (s2011011400/64-bit)
Client Platform           : NT 64BIT
Install/Instance Path     : C:\Users\spandura\Downloads\db2_drivers\clidriver

Common App Data Path      : C:\ProgramData\IBM\DB2\C_Users_spandura_Downloads_db2_drivers_clidriver
DB2DSDRIVER_CFG_PATH value: <not-set>
db2dsdriver.cfg Path      : <Common App Data Path>\cfg\db2dsdriver.cfg
DB2CLIINIPATH value       : <not-set>
db2cli.ini Path           : <Common App Data Path>\cfg\db2cli.ini
db2diag.log Path          : <Common App Data Path>\db2diag.log

===============================================================================
List of all IBM Data Server client packages on the current workstation:
===============================================================================

Copyname                                            Version Package Language Installed-Location
-------------------------------------------------------------------------------
C_Users_spandura_Downloads_db2_drivers_clidriver[C] 11.5.0500 CLI     EN       C:\Users\spandura\Downloads\db2_drivers\clidriver
-------------------------------------------------------------------------------
 CLI: IBM Data Server Driver for ODBC and CLI
-------------------------------------------------------------------------------

===============================================================================
db2dsdriver.cfg schema validation for the entire file:
===============================================================================

Note: The validation utility could not find the configuration file
db2dsdriver.cfg. The file is searched at
"C:\ProgramData\IBM\DB2\C_Users_spandura_Downloads_db2_drivers_clidriver\cfg\db2dsdriver.cfg".

===============================================================================
The validation is completed.



Thank you in advance

**Comment by bimalkjha** [comment]
@shruti729 Now, everything looks good except your database connection information. `ibm_db` installation is good and communication error by `test-basic-test.js` tells that the database connection info in `test\config.testConnectionStrings.json` is not correct. Once, you update the correct connection info in `test\config.testConnectionStrings.json`, the `node test\test-basic-test.js` should work and your application too.
Please check about database connection info with your server admin. Make sure port is TCPIP port and sever is listening on tcpip port. If server is enabled for SSL Port only, then use ssl port in connection info along with Security=SSL.

Also, you have not shared the complete output of `db2cli validate -database "dbname:hostname:port" -user dbuser -passwd dbpasswd -connect` command. This command will print SUCCESS in last if your connection info is correct. Thanks.
