### ISSUE TITLE
Drop the use of big-integer package since it's marked as a Critical vulnerability

### ISSUE THREAD

**Issue by Ernesto-Hernandez-IBM** [ibmdb/node-ibm_db#795]
**CWE-77: Improper Neutralization of Special Elements used in a Command ('Command Injection') (OSSINDEX)**

The software constructs all or part of a command using externally-influenced input from an upstream component, but it does not neutralize or incorrectly neutralizes special elements that could modify the intended command when it is sent to a downstream component.
CWE-77 Improper Neutralization of Special Elements used in a Command ('Command Injection')

CVSSv3:

- Base Score: CRITICAL (9.8)
- Vector: CVSS:/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H

References:

- [OSSINDEX - CWE-77: Improper Neutralization of Special Elements used in a Command ('Command Injection')](https://ossindex.sonatype.org/vulnerability/afbfcdda-fd2d-42b6-aa10-bf8343466d99?component-type=npm&component-name=big-integer&utm_source=dependency-check&utm_medium=integration&utm_content=6.3.1)

Vulnerable Software & Versions (OSSINDEX):

- cpe:2.3:a:*:big-integer:1.6.48:*:*:*:*:*:*:*

**[Identifiers](https://ossindex.sonatype.org/component/pkg:npm/big-integer@1.6.48?utm_source=dependency-check&utm_medium=integration&utm_content=6.3.1
)**

**Comment by bimalkjha** [comment]
@Ernesto-Hernandez-IBM It is dependency of `unzipper` package and not `ibm_db`. Hence, we do not see `big-integer` in pacakge.json file rather it is in `package-lock.json` file. Once, unzipper fixes this issue, it will fixed for ibm_db too.  Thanks.
