### ISSUE TITLE
npm install should provide diagnostics on error

### ISSUE THREAD

**Issue by pmuellr** [ibmdb/node-ibm_db#8]
This package appears to die various sorts of death when you don't have ODBC/sql stuff pre-installed on your system.  Eg, when trying to install on my mac, I see:

    > ibm_db@0.0.1 preinstall ~/tmp/foo/bar/node_modules/ibm_db
    > node-gyp configure build

      CXX(target) Release/obj.target/odbc_bindings/src/odbc.o
    In file included from ../src/odbc.cpp:25:
    ../src/odbc.h:29:10: fatal error: 'sqlcli1.h' file not found
    #include <sqlcli1.h>
             ^
    1 error generated.
    make: *** [Release/obj.target/odbc_bindings/src/odbc.o] Error 1
    gyp ERR! build error
    gyp ERR! stack Error: `make` failed with exit code: 2
    ...
    gyp ERR! command 
       "node" 
       "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" 
       "configure" 
       "build"
    gyp ERR! cwd ~/tmp/foo/bar/node_modules/ibm_db
    gyp ERR! node -v v0.10.26
    gyp ERR! node-gyp -v v0.12.2
    gyp ERR! not ok

Is there any way to "catch" that, to make it a little more understandable?  Perhaps even tell the user where to get the package that needs to be pre-installed?

**Comment by mariobriggs** [comment]
@pmuellr late reply i know. In 0.6.6 we upgraded the windows and linux install of the npm to download its dependencies (odbc/sql stuff). Still not there yet on Mac, since we dont yet have a dependent module bundle of the right size (but looks like that might get fixed soon). Until then updated the readme that calls out to install DB2Express-C first when on Mac (not yet a message during npm install :-( )

**Comment by mariobriggs** [comment]
version 0.0.8 now automatically downloads required dependencies on Mac OS. Give it a try ( v 0.12 not supported as of today :-) )

**Comment by mwhitlaw** [comment]
Yeah, I can't get this to install on Mac OS and v 0.12 of node, as mariobriggs mentioned, I guess this is not supported yet. Any eta on when v0.12 on MacOS will be supported?

**Comment by mil** [comment]
(osx 10.9.5) ibm_db throws:
```
> ibm_db@0.0.8 install /Users/mil/Desktop/repos/projectregistrationapp/node_modules/ibm_db
> node installer/driverInstall.js

Downloading DB2 ODBC CLI Driver from http://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/macos64_odbc_cli.tar.gz...

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: EACCES, open '/myrepo/node_modules/ibm_db/installer/clidriver/msg/en_US.iso88591/db2adm.mo'
```
any tips @mariobriggs -- assuming this just means variables renamed somewhere?

**Comment by avikalar** [comment]
@mil EACESS error code means permission denied, does the user running the install command has sufficient privileges ? Can you send me the complete error trace, if there are any ?

**Comment by mil** [comment]
Full error trace:
```
~/D/r/projectregistrationapp > npm install
npm WARN package.json ProjectRegistration@0.0.1 No repository field.
npm WARN package.json ProjectRegistration@0.0.1 No README data
\
> ibm_db@0.0.8 install /Users/mil/Desktop/repos/projectregistrationapp/node_modules/ibm_db
> node installer/driverInstall.js

Downloading DB2 ODBC CLI Driver from http://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/macos64_odbc_cli.tar.gz...

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: EACCES, open '/Users/mil/Desktop/repos/projectregistrationapp/node_modules/ibm_db/installer/clidriver/msg/en_US.iso88591/db2adm.mo'

npm ERR! ibm_db@0.0.8 install: `node installer/driverInstall.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the ibm_db@0.0.8 install script.
npm ERR! This is most likely a problem with the ibm_db package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node installer/driverInstall.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls ibm_db
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 13.4.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/mil/Desktop/repos/projectregistrationapp
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.5.0-alpha-4
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/mil/Desktop/repos/projectregistrationapp/npm-debug.log
npm ERR! not ok code 0
```

**Comment by mil** [comment]
```
~/D/r/projectregistrationapp > cat npm-debug.log | tail -n 32
150 verbose rebuild bundle /Users/mil/Desktop/repos/projectregistrationapp/node_modules/ibm_db
151 info build /Users/mil/Desktop/repos/projectregistrationapp/node_modules/ibm_db
152 info preinstall ibm_db@0.0.8
153 verbose linkStuff [ false,
153 verbose linkStuff   false,
153 verbose linkStuff   false,
153 verbose linkStuff   '/Users/mil/Desktop/repos/projectregistrationapp/node_modules' ]
154 info linkStuff ibm_db@0.0.8
155 verbose linkBins ibm_db@0.0.8
156 verbose linkMans ibm_db@0.0.8
157 verbose rebuildBundles ibm_db@0.0.8
158 verbose rebuildBundles [ '.bin', 'bindings', 'fstream', 'tar.gz', 'unzip' ]
159 info install ibm_db@0.0.8
160 verbose unsafe-perm in lifecycle true
161 info ibm_db@0.0.8 Failed to exec install script
162 error ibm_db@0.0.8 install: `node installer/driverInstall.js`
162 error Exit status 8
163 error Failed at the ibm_db@0.0.8 install script.
163 error This is most likely a problem with the ibm_db package,
163 error not with npm itself.
163 error Tell the author that this fails on your system:
163 error     node installer/driverInstall.js
163 error You can get their info via:
163 error     npm owner ls ibm_db
163 error There is likely additional logging output above.
164 error System Darwin 13.4.0
165 error command "node" "/usr/local/bin/npm" "install"
166 error cwd /Users/mil/Desktop/repos/projectregistrationapp
167 error node -v v0.10.29
168 error npm -v 1.5.0-alpha-4
169 error code ELIFECYCLE
170 verbose exit [ 1, true ]
```

**Comment by mil** [comment]
Problem had to do with old deps in the filesystem. `rm node_modules && npm install` fixes.

**Comment by avikalar** [comment]
@mil: glad to know that your issue is fixed
