### ISSUE TITLE
Windows support on node v4+

### ISSUE THREAD

**Issue by osdlge** [ibmdb/node-ibm_db#80]
Just wondering if/when windows will be supported on node v4+

**Comment by rhtpandeyIN** [comment]
For NodeJS V 4.x, use below command:

npm install git+https://git@github.com/ibmdb/node-ibm_db.git#v4_support

Update: node-ibm_db is now available on Windows using NodeJS V4.x.

Thanks.
Rohit Pandey

**Comment by bimalkjha** [comment]
@osdlge It is supported now.
