### ISSUE TITLE
Segmentation fault when connecting to db2 on IBM cloud

### ISSUE THREAD

**Issue by yliu138** [ibmdb/node-ibm_db#804]
I am getting an "Segmentation fault" error when connecting to IBM DB2 on Cloud Version 11.5.0 based on the README file provided when running locally with Node version: v16.9.1

This can be fixed by adding `Security=SSL`  to the connection string from my environment. For example, `const connStr = DATABASE=${dbname};HOSTNAME=${myhost};UID=${db2user};PWD=${password};PORT=${dbport};PROTOCOL=TCPIP;Security=SSL;`

If this is a must-have parameter, can you please update the README file?

**Comment by bimalkjha** [comment]
@yliu138 Please share the stack trace of segfault. Other users are not facing it, so what is different in your environment?
SSL port is enabled or not for DB2 on Cloud, it depends on the service and plan you are using. DB2 server accepts connections on TCPIP Port and SSL port. But, it should be configured on the server. Few cloud plan has only SSL port enabled, few has only TCPIP and few has both. So, check with your service provider. 
When we use `Security=SSL` in connection string, the PORT value must be the SSL Port which is different from the PORT that we use without `Security=SSL`. `Security=SSL` is not a must have parameter, but it is required for SSL based secured connection. I have Db2 on Cloud instance with both TCPIP and SSL port enabled and using ibm_db driver, we can connect to server via TCPIP with using Security=SSL in connection string.
I hope above update have provided the clarity. Thanks.

**Comment by bimalkjha** [comment]
@yliu138 Let us know if you are still facing this issue. Thanks.
