### ISSUE TITLE
Does the library support hostvarparameters ?

### ISSUE THREAD

**Issue by dyonatan** [ibmdb/node-ibm_db#805]
I need to run the command:
SELECT * FROM COMPANY WHERE NAME IN (:names) or ID IN (:ids)
How to do this ?

**Comment by bimalkjha** [comment]
@dyonatan Are you able to run above SQL using any other client with Db2 server? Does your `names` and `ids` are array so using IN operator? Please clarify. Thanks.

**Comment by bimalkjha** [comment]
@dyonatan Db2 server supports SQL like : `select empno, firstnme, workdept from emp where empno in (00010, 00020) or workdept in ('E21', 'D11', 'A00')`.
Here you can see the values for IN operator is not array but individual values. So, you can not pass an array for IN.
So, you can add below code for `SELECT * FROM COMPANY WHERE NAME IN (:names) or ID IN (:ids)` to work with Db2 using `ibm_db`:
```
let names = ['abc', 'xyz'];
let ids = [10, 20, 30];
let sql = "SELECT * FROM COMPANY WHERE NAME IN (" + names + ") or ID IN (" + ids + ")";
let result = conn.querySync(sql);
```
Thanks.
