### ISSUE TITLE
 Informix - Connection error - sqlcode: -30081,  state: '08001'

### ISSUE THREAD

**Issue by sap99** [ibmdb/node-ibm_db#806]
MAC OS - Big Sur
Node - V 16.13.0, npm - 8.1.0
ibm_db - 2.8.0

Install is successful, but unable to establish a remote connection with ibm_db ( error details below)
Connection is successful via JDBC driver ( 4.50.3). 
Did refer to https://github.com/ibmdb/node-ibm_db/issues/145 

Is there any alternate workaround to establish connection to such Informix configuration?

node test-basic-test.js 

Trying to open a connection ...
[Error: [IBM][CLI Driver] SQL30081N A communication error has been detected. Communication protocol being used: "TCP/IP". Communication API being used: "SOCKETS". Location where the error was detected: "xx.xxx.xx.xxx". Communication function detecting the error: "recv". Protocol specific error code(s): "*", "*", "0". SQLSTATE=08001
] {
 error: '[ibm_db] SQL_ERROR',
 sqlcode: -30081,
 state: '08001'
}
node:assert:123
 throw new AssertionError(obj);
AssertionError [ERR_ASSERTION]: [Error: [IBM][CLI Driver] SQL30081N A communication error has been detected. Communication protocol being used: "TCP/IP". Communication API being used: "SOCKETS". Location where the error was detected: "xx.xxx.xx.xxx". Communication function detecting the error: "recv". Protocol specific error code(s): "*", "*", "0". SQLSTATE=08001
] {
 error: '[ibm_db] SQL_ERROR',
 sqlcode: -30081,
 state: '08001'
} == null

**Comment by bimalkjha** [comment]
@sap99 Your JDBC connection might be working, but seems issue with ODBC connection.
test-basic-test.js works only if you update database connection info in `ibm_db\test\config.testConnectionStrings.json` file.
I would suggest to update database connection info for `db2cli validate` command in `ibm_db\installer\testODBCConnection.sh` or `.bat` file based on OS and run it to verify the connectivity. Please share the complete output of script file along with generated `1.*` files as a zip here.
You can also `cd ibm_db\installer\clidriver\bin` directory and run below command with correct connection info:
```
db2cli validate -database "sample:hotel.torolab.ibm.com:21169" -connect -user newton -passwd serverpass
```
If above validate command fails, means either connection string is incorrect or server is not configured properly to accept remote connection. If validate command works, then ibm_db will also work. Thanks.

**Comment by sap99** [comment]
Thanks @bimalkjha , yes had updated ibm_db\test\config.testConnectionStrings.json before running test-basic-test.js .
db2cli validate results in the same TCP / IP communication error.

What can be a workaround for this?

02g2348md6n installer % ./testODBCConnection.sh 
Trace is turned on

===============================================================================
Client information for the current copy:
===============================================================================

Client Package Type       : IBM Data Server Driver For ODBC and CLI
Client Version (level/bit): DB2 v11.5.5.0 (s2011011400/64-bit)
Client Platform           : Darwin
Install/Instance Path     : /Users/a1/fx/node-ibm_db/installer/clidriver
DB2DSDRIVER_CFG_PATH value: <not-set>
db2dsdriver.cfg Path      : /Users/a1/fx/node-ibm_db/installer/clidriver/cfg/db2dsdriver.cfg
DB2CLIINIPATH value       : <not-set>
db2cli.ini Path           : /Users/a1/fx/node-ibm_db/installer/clidriver/cfg/db2cli.ini
db2diag.log Path          : /Users/a1/fx/node-ibm_db/installer/clidriver/db2dump/db2diag.log

===============================================================================
db2dsdriver.cfg schema validation for the entire file:
===============================================================================

Note: The validation utility could not find the configuration file 
db2dsdriver.cfg. The file is searched at 
"/Users/a1/fx/node-ibm_db/installer/clidriver/cfg/db2dsdriver.cfg".

===============================================================================
db2cli.ini validation for database "dbname:xxx.xx.com:23400":
===============================================================================

Note: The validation utility could not find the configuration file db2cli.ini. 
The file is searched at 
"/Users/a1/fx/node-ibm_db/installer/clidriver/cfg/db2cli.ini".

===============================================================================
db2dsdriver.cfg validation for database "dbname:xxx.xx.com:23400":
===============================================================================
[ibm_db_trace.zip](https://github.com/ibmdb/node-ibm_db/files/7497415/ibm_db_trace.zip)

Note: The validation utility could not find the configuration file 
db2dsdriver.cfg. The file is searched at 
"/Users/a1/fx/node-ibm_db/installer/clidriver/cfg/db2dsdriver.cfg".

===============================================================================
Connection attempt for database "dbname:xxx.xx.com:23400":
===============================================================================

[FAILED]: [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "10.246.82.145".  Communication function detecting the error: "recv".  Protocol specific error code(s): "*", "*", "0".  SQLSTATE=08001


===============================================================================
Error: The validation operation failed.
===============================================================================

===============================================================================
The validation is completed.
===============================================================================

Trace has been dumped to file "1.trc"
Trace is turned off
Total number of trace records     : 9593
Trace truncated                   : NO
Trace wrapped                     : NO
Number of trace records formatted : 7773 (pid: 93250 tid 4678405632 node: -1) 
Number of trace records formatted : 1730 (pid: 93250 tid 259 node: -1) 
Trace truncated                   : NO
Trace wrapped                     : NO
Total number of trace records     : 9593
Number of trace records formatted : 9503
Trace truncated                   : NO
Trace wrapped                     : NO
Total number of trace records     : 9593
Number of trace records formatted : 3
Trace truncated                   : NO
Trace wrapped                     : NO
Total number of trace records     : 9593
Number of trace records formatted : 90

**Comment by bimalkjha** [comment]
@sap99 Please login to your db2 server system using the credential used in `db2cli validate` command in `testODBCConnection.sh` script and run the same `db2cli validate` command. It would fail with same SQL30081N error. It means either port is incorrect or server is not configured properly. Then you need to contact your db admin.
Please share the jdbc connection string which is working for you. Are you using TCPIP port of SSL port?
