### ISSUE TITLE
CWE-300:

### ISSUE THREAD

**Issue by huineng** [ibmdb/node-ibm_db#807]
using a depscan tool, we encounter the following vulnerability

```
Filename: ibm_db:2.8.0 | Highest CVSS Score: 7.1 | Amount of CVSS: 1 | References: CWE-300: Channel Accessible by Non-Endpoint ('Man-in-the-Middle') (7.1)See Rule
```

is this something i can ignore, or something that might need to be fixed ? 

thanks

**Comment by bimalkjha** [comment]
@huineng It can be ignored. Thanks.
