### ISSUE TITLE
Failure in getting connection to db2 on SKILLS NETWORK LABS after entering Service Credentials

### ISSUE THREAD

**Issue by Afridi730** [ibmdb/node-ibm_db#809]
In order to complete one of my " Assignment : Notebook for Peer Assignment "on IBM Developer Skills Network after I entered my service credentials in order to get connected to Db2 when I run the code in the cell I get the following message/error below the cell: 

Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys([])
Can't load plugin: sqlalchemy.dialects:ibm_db_sa
Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys([])
This indicates that I am not connected to Db2 and therefore when I enter any code in the other cells I do not get any output. In other words I cannot complete my assignment. Instead of getting any output I get the following message/error:

Environment variable $DATABASE_URL not set, and no connect string given.
Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys([])
I would be extremely grateful if someone could guide me to solve this issue.
Thanks

**Comment by bimalkjha** [comment]
@Afridi730 First, you opened issue in wrong forum. You should open issue here: https://github.com/ibmdb/python-ibmdbsa/issues
Next, you need to follow instructions documented here: https://github.com/ibmdb/python-ibmdbsa
```
     pip install ibm_db
     pip install sqlalchemy==1.3.23
     pip install ibm_db_sa
```
Then follow this documentation: https://docs.sqlalchemy.org/en/14/tutorial/engine.html
