### ISSUE TITLE
Non-english characters are garbled when running on Jenkins

### ISSUE THREAD

**Issue by william-glasse** [ibmdb/node-ibm_db#812]
We are having issues with our node app, which is fetching data from a DB2 instance, whereby some of the returned data is garbled. This behaviour only happens when run on a Jenkins job. When run on my MacOs machine, I do not get the same issue. I have tried to ensure that my local environment matches as closely as possible as that of the jenkins job, by matching node versions, npm etc. 

We are running this version of the package:
"ibm_db": "^2.8.0",

NODE: v14.18.2
NPM: 6.14.15

We set these environment variables both locally and on Jenkins:
DB2CODEPAGE=1208
LANG=en_US.UTF-8

When running the following query:
```SELECT XMLCAST(XMLPARSE(DOCUMENT CAST (cl.XML_DOCUMENT AS BLOB) PRESERVE WHITESPACE) as XML)```

On jenkins, we get the following data returned:
```'<DocTitle>IBM Data ... descoberta, governan��a e consumo de dados </DocTitle>\n'```

Whilst on my local I get 
```'<DocTitle>IBM Data ... descoberta, governança e consumo de dados </DocTitle>\n' +```

Any ideas on how to fix this?

See similar issues to #402

**Comment by bimalkjha** [comment]
@william-glasse What is the OS name in your Jenkins env? In your node.js program on Jenkins, use console.log to print value of `process.env` and see if DB2CODEPAGE value is effective in node.js environment or not. Thanks.

**Comment by bimalkjha** [comment]
I hope issue is fixed by setting DB2CODEPAGE, so closing the issue. If issue still persist, please provide info. Thanks.

**Comment by mrsideshowjack** [comment]
So the issue turned out to be that the log output in Jenkins could not display UTF-8, sending the output somewhere else we could see the output was correct. Hope this may help anyone else running into the same thing.
