### ISSUE TITLE
I'm not able to connect to db2

### ISSUE THREAD

**Issue by brenokf** [ibmdb/node-ibm_db#817]
`const { Router } = require('express')
const ibmdb = require('ibm_db')

const queryDbRouter = Router()

const connectDb =
'DATABASE=' + process.env.DB_DATABASE +
';HOSTNAME=' + process.env.DB_HOSTNAME +
';PORT=' + process.env.DB_PORT +
';PROTOCOL=' + process.env.DB_PROTOCOL +
';UID=' + process.env.DB_UID +
';PWD=' + process.env.DB_PWD + ';'

queryDbRouter.post('/', async (request, response) => {
  console.log('hi')
  ibmdb.open(connectDb, (err, conn) => {
    if (err) {
      return response.json({ sucess: -1, message: err })
    }`

**Comment by bimalkjha** [comment]
@brenokf Please provide below info:
1. Name of the Operating System on which you have installed `ibm_db`
2. Node.js version and ibm_db version
3. Output of `db2level` command. If unable to find, then cd to ibm_db\installer\clidriver\bin and then run it.
4. Update connection info in `ibm_db\test\config.testConnectionStrings.json` fle and share output of `node ibm_db\test\test-basic-test.js` command.
Thanks.

**Comment by brenokf** [comment]
my OS is MacOsMonterey version 12.1
ibm_db version: 2.8.1
db2leve : I couldn't run 
`[Running] node "/Users/brenomelo/Kyndryl/githubKyndryl/DiscountApi-demo_server/node_modules/ibm_db/test/test-basic-test.js"
Trying to open a connection ... 

[Done] exited with code=null in 0.873 seconds`

**Comment by brenokf** [comment]
[Error: [IBM][CLI Driver] CLI0157E  Error opening a file. SQLSTATE=HY507] {
  error: '[ibm_db] SQL_ERROR',
  sqlcode: -99999,
  state: 'HY507'
}

**Comment by bimalkjha** [comment]
@brenokf In your shared result, you have not used the test file name after node. See the below error:
```
[Running] node ""
Trying to open a connection ...
```
You should use `node ibm_db\test\test-basic-test.js` command and share its result. Thanks.

**Comment by bimalkjha** [comment]
If you are still facing the issue, please reopen with requested info. Closing the issue now. Thanks.
