### ISSUE TITLE
Error: Command failed: node-gyp configure build  --IS_DOWNLOADED=false --IBM_DB_HOME=$IBM_DB_HOME

### ISSUE THREAD

**Issue by gouthamr22** [ibmdb/node-ibm_db#818]
I am getting below error when I am trying to install ibm_db, any advice on how to fix it.

$ npm install ibm_db

> ibm_db@2.8.1 install C:\bench\new\eua-backend-service\node_modules\ibm_db
> node installer/driverInstall.js

platform = win32, arch = x64, node.js version = v14.18.1
IBM_DB_HOME environment variable have already set to -> pull_path_of_clidriver

Downloading of clidriver skipped - build is in progress...

pull_path_of_clidriver directory does not exist. Please check if you have set the IBM_DB_HOME environment variable's value correctly.

C:\bench\new\eua-backend-service\node_modules\ibm_db\pull_path_of_clidriver\include directory does not exist. Please check if you have set the IBM_DB_HOME environment variable's value c
orrectly.

C:\bench\new\eua-backend-service\node_modules\ibm_db\pull_path_of_clidriver\lib  directory does not exist. Please  check if you have set the IBM_DB_HOME environment  variable's value co
rrectly.

C:\bench\new\eua-backend-service\node_modules\ibm_db>if not defined npm_config_node_gyp (node "C:\Users\PYPFQ61\AppData\Roaming\nvm\v14.18.1\node_modules\npm\node_modules\npm-lifecycle\
node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure build  --IS_DOWNLOADED=false --IBM_DB_HOME=$IBM_DB_HOME )  else (node "C:\Users\PYPFQ61\AppData\Roaming\nvm\v14.18.1
\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" configure build  --IS_DOWNLOADED=false --IBM_DB_HOME=$IBM_DB_HOME )

Error: Command failed: node-gyp configure build  --IS_DOWNLOADED=false --IBM_DB_HOME=$IBM_DB_HOME
gyp ERR! find VS
gyp ERR! find VS msvs_version was set from command line or npm config
gyp ERR! find VS - looking for Visual Studio version 2013
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS checking VS2017 (15.9.28307.1500) found at:
gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
gyp ERR! find VS - found "Visual Studio C++ core features"
gyp ERR! find VS - found VC++ toolset: v141
gyp ERR! find VS - found Windows SDK: 10.0.17763.0
gyp ERR! find VS - msvs_version does not match this version
gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS valid versions for msvs_version:
gyp ERR! find VS - "2017"
gyp ERR! find VS - "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\PYPFQ61\AppData\Roaming\nvm\v14.18.1\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at C:\Users\PYPFQ61\AppData\Roaming\nvm\v14.18.1\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\PYPFQ61\AppData\Roaming\nvm\v14.18.1\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at C:\Users\PYPFQ61\AppData\Roaming\nvm\v14.18.1\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at C:\Users\PYPFQ61\AppData\Roaming\nvm\v14.18.1\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at C:\Users\PYPFQ61\AppData\Roaming\nvm\v14.18.1\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Users\PYPFQ61\AppData\Roaming\nvm\v14.18.1\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:390:5)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at maybeClose (internal/child_process.js:1058:16)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\PYPFQ61\\AppData\\Roaming\\nvm\\v14.18.1\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "bu
ild" "--IS_DOWNLOADED=false" "--IBM_DB_HOME=$IBM_DB_HOME"
gyp ERR! cwd C:\bench\new\eua-backend-service\node_modules\ibm_db
gyp ERR! node -v v14.18.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok

    at ChildProcess.exithandler (child_process.js:383:12)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1058:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node-gyp configure build  --IS_DOWNLOADED=false --IBM_DB_HOME=$IBM_DB_HOME'
}

node-gyp build process failed!

Proceeding with Pre-compiled Binary Installation.

===================================
ibm_db installed successfully.
===================================

npm WARN @deere/jest-config@7.2.19 requires a peer of enzyme@^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN enzyme-to-json@3.6.2 requires a peer of enzyme@^3.4.0 but none is installed. You must install peer dependencies yourself.
npm WARN jest-puppeteer@6.0.2 requires a peer of puppeteer@>= 1.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN @deere/eua-backend-service@1.0.0 No repository field.
npm WARN @deere/eua-backend-service@1.0.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\jest-haste-map\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\nodemon\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ ibm_db@2.8.1
updated 1 package and audited 1169 packages in 13.562s

47 packages are looking for funding
  run `npm fund` for details

found 63 vulnerabilities (31 moderate, 32 high)
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by bimalkjha** [comment]
@gouthamr22 The error you see because you do not have visual studio compiler installed in the system. So, ibm_db went ahead with precompile binary.
As long as you see the message `ibm_db installed successfully.` at end, it is success and usable. You can run `node test\test-basic-test.js` to verify the installation. It should work. Yes, you need to update database connection info in file `test\config.testConnectionStrings.json` file. Thanks.
