### ISSUE TITLE
Apple Silicon - M1 - missing symbol called

### ISSUE THREAD

**Issue by welsh11** [ibmdb/node-ibm_db#819]
I have installed version 2.8.1 and have a very simple test JS file with a single line:

`var ibmdb = require('ibm_db')();`

When I run the file I get the following error:

`dyld[14986]: missing symbol called`

and nothing else.

Any help would be appreciated, thanks.

**Comment by bimalkjha** [comment]
@welsh11 Please share the complete output of below commands:
```
npm install ibm_db
cd ibm_db\installer\clidriver\bin
.\db2level
.\db2cli validate
cd ibm_db\test
node test-basic-test.js
```
Thanks.

**Comment by welsh11** [comment]
Hi there, thanks for getting back to me. Outputs are as follows:

`.\db2level`

```
DB21085I  This instance or install (instance name, where applicable: "*") uses 
"64" bits and DB2 code release "SQL11055" with level identifier "0606010F".
Informational tokens are "DB2 v11.5.5.0", "s2011011400", "DYN2011011400MAC", 
and Fix Pack "0".
Product is installed at 
"/Users/<REDACTED>/node_modules/ibm_db/installer/clidriver".
```

`.\db2cli validate`

```
===============================================================================
Client information for the current copy:
===============================================================================

Client Package Type       : IBM Data Server Driver For ODBC and CLI
Client Version (level/bit): DB2 v11.5.5.0 (s2011011400/64-bit)
Client Platform           : Darwin
Install/Instance Path     : /Users/<REDACTED>/node_modules/ibm_db/installer/clidriver
DB2DSDRIVER_CFG_PATH value: <not-set>
db2dsdriver.cfg Path      : <REDACTED>/node_modules/ibm_db/installer/clidriver/cfg/db2dsdriver.cfg
DB2CLIINIPATH value       : <not-set>
db2cli.ini Path           : /Users/<REDACTED>/node_modules/ibm_db/installer/clidriver/cfg/db2cli.ini
db2diag.log Path          : /Users/<REDACTED>/node_modules/ibm_db/installer/clidriver/db2dump/db2diag.log

===============================================================================
db2dsdriver.cfg schema validation for the entire file:
===============================================================================

Note: The validation utility could not find the configuration file 
db2dsdriver.cfg. The file is searched at 
"/Users/<REDACTED>/node_modules/ibm_db/installer/clidriver/cfg/db2dsdriver.cfg".

===============================================================================
The validation is completed.
===============================================================================
```

`node test-basic-test.js`

```
Trying to open a connection ... 
dyld[40365]: missing symbol called
[1]    40365 abort      node test-basic-test.js
```

**Comment by bimalkjha** [comment]
@welsh11 I am able to reproduce the problem on M1 Chip MacOS system. It looks clidriver built by IBM is not supporting this new arm64 platform and hence linking issue during installation of ibm_db on M1 Chip System. We are in talk with IBM to support this platform. Thanks.

**Comment by mdgozza** [comment]
@welsh11 While we wait for ibm to officially support the new Apple arm chip, you can try to run the npm modules under Apple's Rosetta for cross compatibility ( although it will be a bit slower ) 
Simply asking npm to install with this in mind you need to run `npm install --target_arch=x64`

Alternatively, you can run your application in a docker container and ask docker to emulate it for you. ( also slower ) 
https://docs.docker.com/desktop/mac/apple-silicon/

by passing the --platform flag to the run command and setting it's value to `linux/x86_64`

**Comment by alok0007** [comment]
@mdgozza I tried with above command as you suggested but still no difference

**Comment by bimalkjha** [comment]
@alok0007 @welsh11 We need to use x64 version of node.js on M1 Chip system to install ibm_db. So, download and install https://nodejs.org/dist/v17.6.0/node-v17.6.0-darwin-x64.tar.gz or replace the installed nodejs directory with this one and then install ibm_db. It works for me. Thanks.

**Comment by niightly** [comment]
For me I tried everything, and the only option that worked was:

1. Download the clidriver from https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli
2. Select the `MACOS64` (for me was [macos64_odbc_cli.tar.gz](https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/macos64_odbc_cli.tar.gz))
3. Decompress the content into a final location (avoid the Downloads folder).
4. Run `export IBM_DB_HOME=<PATH-TO-YOUR-UNCOMPRESSED-CLIDRIVER>`
5. Run `npm un ibm_db && npm i ibm_db`

> Node: Now every new installation should point to this folder, Licenses, CFGs, etc, will point to there as well.

**Comment by bimalkjha** [comment]
@niightly @welsh11 @alok0007 ibm_db@3.3.0 has been released with native installation support for MacOS M1 Chip system. Please try it. Thanks.
