### ISSUE TITLE
Error SQL30081N

### ISSUE THREAD

**Issue by rbonillajr** [ibmdb/node-ibm_db#82]
Hello could help me , I have communication with the database server . DB2 version is 7.1

{ [Error: [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "172.18.1.104".  Communication function detecting the error: "selectForConnectTimeout".  Protocol specific error code(s): "115", "*", "*".  SQLSTATE=08001
]

**Comment by rhtpandeyIN** [comment]
Can you please check your server connectivity, it seems server is down and it refusing connection. 
or may be your connection string is not right.

**Comment by martov1** [comment]
is this an expected error if for example the database name/username/password is wrong? dont we get a more specific error?

**Comment by bimalkjha** [comment]
Yes, it is an expected error in cases of above stated things are wrong. Please visit this link for info about SQL30081N error: http://www.ibm.com/support/knowledgecenter/en/SSEPGG_10.5.0/com.ibm.db2.luw.messages.sql.doc/doc/msql30081n.html
