### ISSUE TITLE
Using the ibm_db query call with node and large resultset

### ISSUE THREAD

**Issue by berlinbrown** [ibmdb/node-ibm_db#820]
I am using nodejs and ibm_db and have a large result set.  Let's say 500k records.  In the java world the same query will return (I assume chunks at a time automatically).  The result set in java will result the result so I can process the data.  I get a response in milliseconds.

WIth the same query ibm_db and I expect a result set of 500k, the call hangs and I never get a response for several minutes.  How can I handle large results? And is the approach different from the jdbc driver?

**Comment by berlinbrown** [comment]
Ended up doing something like this:


const result = await this.database.queryResult(RepositorySQL.TEST_ADDITION_DB, [RepositorySQL.BOOTSTRAP_TS]);
        if (result) {
            result.fetch((error, val) => {
                this.logger.log(`>>> ${JSON.stringify(error)}`);
                this.logger.log(`>>> ${JSON.stringify(val)}`);
            });
        }

**Comment by berlinbrown** [comment]
This didn't pull the right result set though, didn't move to next operation.


      result = await this.database.queryResult(RepositorySQL.TEST_READ_NOTES_RECORDS, []);
        let data = null;

        if (result) {
                result.fetch((error, val) => {
                    data = val;
                    this.logger.log(`>>> ${JSON.stringify(error)}`);
                    this.logger.log(`>>> ${JSON.stringify(val)}`);
                });

                result.fetch((error, val) => {
                data = val;
                this.logger.log(`>>> ${JSON.stringify(error)}`);
                this.logger.log(`>>> ${JSON.stringify(val)}`);
            });
            }

**Comment by bimalkjha** [comment]
@berlinbrown Are you able to execute the test file `singleRowFetch.js` and does it fail?
Please update the database connection info at line no 11 and select query at line no 22 in file `singleRowFetch.js` and save it. Then execute it. Check the result. It should return all data. It is using `fetchSync()` API and not the `fetch()`. We need while loop to call it repeatedly.
Better way is you should update database connection string in file `test\config.testConnectionStrings.json` file and execute `test\test-fetch-apis.js` file. It uses all kind of fetch APIs with proper example. You can see example for `result.fetch()` here: https://github.com/ibmdb/node-ibm_db/blob/master/test/test-fetch-apis.js#L49
Actually, if you want to call fetch() API which is asynchronous, logic may get messy. First try to use fetchSync() and then move on fetch(). I think for your case fetchSync() would be better. Don't forget to use `while` loop. Thanks.

**Comment by berlinbrown** [comment]
FetchSyncworkjed.   Is there. a way to control the amount of data sent back. Does it default to 64, buffer?
