### ISSUE TITLE
overwrite the value of a column with the same name

### ISSUE THREAD

**Issue by radovanrusz** [ibmdb/node-ibm_db#821]
Example SQL: 
select 'text 1' as name, 'text 2' as name from SYSIBM.SYSDUMMY1 

Result:
NAME | NAME_1
-------------------
text 2  | text 2

please fix it.

Regards Radovan

**Comment by bimalkjha** [comment]
@radovanrusz Since ibm_db returns rows in JSON Object form which can not have duplicate keys, the value of columns having same colname as key gets overwritten. To avoid it, fetch the data in array form as below:
```
let ibmdb = require('ibm_db');
ibmdb.open(connString, {fetchMode : ibmdb.FETCH_ARRAY}, function(err, conn) {
  conn.query(....
```
It returns the result as `[ [ 'text 1', 'text 2' ] ]`. Thanks.

**Comment by radovanrusz** [comment]
But ibm db2 does not return duplicate column names. When you join two tables that have the same column names, then ibm db2 renames the second name to columnName_1. Therefore, there is no duplication of keys. I prefer fetched data in json format.

**Comment by bimalkjha** [comment]
@radovanrusz Please share the repro test program along with Operating System name and Node.js version. I am unable to get colname renamed as colname_1 using below program:
```
$ cat test-same-name-col.js
let ibmdb = require("ibm_db");
let connectionString = "database=........";
ibmdb.open(connectionString, function(err, conn) {
  var sql = "select 'text 1' as name, 'text 2' as name from SYSIBM.SYSDUMMY1";

  conn.query(sql, function (err, data) {
    console.log("data = ", data);
    conn.close(function () {
    });
  });
});
$ node test-same-name-col.js
select 'text 1' as name, 'text 2' as name from SYSIBM.SYSDUMMY1
data =  [ { NAME: 'text 2' } ]
$
```
Also, to avoid the issue, if I change the colname in query itself, it gives correct result: `select 'text 1' as name, 'text 2' as name from SYSIBM.SYSDUMMY1`. Thanks.

**Comment by bimalkjha** [comment]
I checked on Mac, Linux and Windows using above test and it gives same result on all platforms using latest node.js. Thanks.

**Comment by radovanrusz** [comment]
Yes you're right. It's a property of our old client in Delphi. DB2 returns two columns with the same name. Could you implement this feature in your package? If you find the same name in the column order, add _1, _2, _3 ....? Then there would be no duplication of keys.

From DB2 command line
db2 => select 'text 1' as name, 'text 2' as name from SYSIBM.SYSDUMMY1

NAME   NAME
------ ------
text 1 text 2

Output of your package: 
"items": [
    {
      "NAME": "text 2"
    }
  ],
  "fieldsName": [
    "NAME",
    "NAME"
  ]

**Comment by bimalkjha** [comment]
@radovanrusz We can update the code as per your request, but it'll degrade the performance drastically. Support there is 100 columns in a table and to find the duplicate columns and rename it, we need to compare each column name with remaining 99 column names. i.e. a string comparison of 99*99 times! The gain vs performance loss for this code change is huge. We would suggest to check all such queries which having duplicate column alias and correct the SQL. Thanks.
