### ISSUE TITLE
driverInstall.js prints far too many messages

### ISSUE THREAD

**Issue by AWare** [ibmdb/node-ibm_db#826]
`driverInstall` prints a log line, what seems like every 192 bytes, this would be 129193 log lines or 58% of the driver size in log lines. this seems to be triggered by `response.data.on('data'`  please can this be rate limited?

 ```
#13 68.92 .../ibm_db@2.8.0/node_modules/ibm_db install: 26.16% | 6488064 bytes downloaded out of 24805204 bytes.
  #13 68.92 .../ibm_db@2.8.0/node_modules/ibm_db install: 26.19% | 6496256 bytes downloaded out of 24805204 bytes.
  #13 69.02 .../ibm_db@2.8.0/node_modules/ibm_db install: 26.22% | 6504448 bytes downloaded out of 24805204 bytes.```

**Comment by bimalkjha** [comment]
@AWare Use -q or -s option to avoid so many messages. Check full details as documented here: https://github.com/ibmdb/node-ibm_db#install

**Comment by AWare** [comment]
Sorry but disabling npm logging entirely is not an acceptable solution, as we need to keep and examine the npm output for other installed packages.

**Comment by bimalkjha** [comment]
@AWare `npm install -q ibm_db` is not disabling the npm logging entirely. Only `-s` option is disabling the npm logging entirely. Use both options and see the deference. Thanks.

**Comment by cjol** [comment]
That's not how packages are typically installed - they are added to a package.json (along with other dependencies) and all installed at the same time (e.g. with `npm install`. In this way there is no way to silence _just_ the ibm_db logging.

**Comment by bimalkjha** [comment]
@cjol In that case just set the environment variable `export npm_config_loglevel=warn` and then run `npm install`. It should work. Thanks.

**Comment by cjol** [comment]
Again, that will mute _all_ packages, not just ibm_db

**Comment by bimalkjha** [comment]
@cjol If I am not wrong, I think you have not tried it yet. It is not muting completely like `--silent` option. It is equivalent of  `--quiet` option and that too if some other package has updated code to read the config_loglevel in their package. We have recently updated ibm_db to support `warn` and `silent` log levels and I think rarely other packages could have code to read the npm_config_loglevel.
For `warn`, ibm_db prints the downloaded % only 3 times. By default many times - to see the download progress and find any bug if there is any problem in download. We can try to reduce the no of logs in future release but same thing can be achieved by using --quiet option and `export npm_config_loglevel=warn`. I would suggest to try different options and see the difference and best mechanism as per your convenience.
Another way is to completely avoid the downloading of clidriver and install will not print any message. That you can do by manually downloading the clidriver.tar.gz file, untar it, get clidriver directory, export IBM_DB_HOME=<full_path_of_clidriver>, then npm install. ibm_db will not download the clidriver and no messages. 
Again I would suggest to try all these mechanism and choose the best. Thanks.
