### ISSUE TITLE
Cypress integration with informix db

### ISSUE THREAD

**Issue by Akhnatenn** [ibmdb/node-ibm_db#829]
When i connect my informix db and run the test case, its throwing the following error. Kindly can someone guide me in this. im stuck badly.

**index.json**

const ibmdb = require('ibm_db');
var dataResult;

function queryDB (dbConfig, query) {
  
      return new Promise((resolve, reject) => {
          ibmdb.open("DATABASE=cards;HOSTNAME=192.168.150.182;PORT=9209;PROTOCOL=TCPIP;UID=username;PWD=password;", function (err, conn) {
            // SERVER=inst0016_drt_06;DATABASE=cards;HOSTNAME=192.168.150.182;PORT=7306;PROTOCOL=TCPIP; 
            if (err) {
              console.log('connKO');
              return reject(err);
          }
          conn.query(query, function (err, data) {
              if (err) {
                  conn.close(function () {
                  console.log('doneKO');
                  console.log(err);
                  return reject(err)
                  });
               
              }
              else {
                  conn.close(function () {
                  console.log('doneOK');
                  dataResult = data;
                  return resolve(dataResult)
                  });
              }
          });
      });
  })
  }

module.exports = (on, config) => {
    on('task', {
        queryDatabase ({ dbConfig, query }) {
            console.log('%s, %s', dbConfig, query)
            return queryDB(dbConfig, query)
        }
    })
}

***********************************************************************

**test.js**
my test case

it.only('testvcased',function(){

        cy.task('queryDatabase', { dbConfig: Cypress.env('db'), query: 'select count(switch_type)as CardName from mcp.aav_gen_opt_esi_map where aav_gen_opt_esi_map.switch_type = "MASTERCARD"'}).then((result) =>{
            cy.log(result);
          })
    })
![error](https://user-images.githubusercontent.com/100988542/156873174-11467cda-f7b9-4dbe-9c3b-df68a266c3cc.png)

**Comment by bimalkjha** [comment]
@Akhnatenn In your shared SQL30081N error, we can see the protocol specific error code is: *, *, 0.
We can see details about this error here: https://www.ibm.com/docs/en/db2/11.5?topic=messages-sql28000-sql33999#sql30081n
```
If protocol = TCP/IP, rc1=*, rc2=*, and rc3=0, possible causes include:

    The database agent at the server was forced off by the system administrator.
```
It tells that you are not connecting to the DRDA port of IDS or it is not enabled by the administrator. Please ask your admin to enable `drsoctcp ` and share the port number with you. We have documented about it here: https://github.com/ibmdb/node-ibm_db#issues-while-connecting-to-informix-server
Thanks.
