### ISSUE TITLE
How to insert BLOB data

### ISSUE THREAD

**Issue by dgkimfirm** [ibmdb/node-ibm_db#83]
I am developing an application with Bluemix and nodejs.
My client app post an image data and location information to my server and
the server save them to SQLDB.
We have succeed to insert location information to VARCHAR, INTEGER column, but failed to insert image data to BLOB column.
 
Could you show me how to save binary image data to BLOB type SQLDB with node-ibm_db package.
Or, Please give me any advice.

**Comment by rhtpandeyIN** [comment]
Hi @dgkimfirm ,
can you please post your sql query which you are currently using for this purpose.
(Insert Statement)

**Comment by dgkimfirm** [comment]
Hi Rohit pandey



We test the SQLDB with folling code:



//Insert

var stmt = conn.prepareSync("insert into PICTURETABLE VALUES(BLOB('?'))");

stmt.executeSync([img]);



//Check result of insert

conn.query("select * from PICTURETABLE", function(err, data) {

    if ( !err ) {

        res.send("successfull");

        console.log("successfull");

        console.log(data);

    } else {

       res.send("error occurred " + err.message);

       console.log("error occurred " + err.message);

    }

    conn.closeSync();

});

**Comment by rhtpandeyIN** [comment]
Ok,
1) I guess this { var stmt = conn.prepareSync("insert into PICTURETABLE VALUES(BLOB('?'))"); } line should be like this -> { var stmt = conn.prepareSync("insert into PICTURETABLE **(column_name)** VALUES(BLOB('?'))");  }

2) and do you getting any error message for this? if any please post that also.
    (error message for Inserting into database BLOB column)

**Comment by rhtpandeyIN** [comment]
Hi @dgkimfirm 

See the output of below program:

$ cat selectblob.js

ibmdb = require('ibm_db')
, cn="DATABASE=SAMPLE;HOSTNAME=host.ibm.com;UID=user;PWD=userpass;PORT=50000;PROTOCOL=TCPIP";
ibmdb.open(cn, function (err,conn)
{
if (err) return console.log(err);
conn.querySync("create table mytab (empId int, value BLOB)");
conn.query("insert into mytab(empId, value) VALUES (18, blob('abc'))", function (err, data) {
if (err) {
console.log(err);
return conn.closeSync();
}
conn.prepare("select * from mytab", function (err, stmt) {
if(err) {
console.log(err);
return conn.closeSync();
}
stmt.execute([], function(err, result) {
if(err) console.log(err);
else {
data = result.fetchAllSync();
console.log("Selected Data = " );
console.log(data);
result.closeSync();
}
conn.querySync("drop table mytab");
result.closeSync();
conn.close(function () { console.log('done'); });
});
});
});
});

$ node selectblob.js
Selected Data =
[ { EMPID: 18, VALUE: '616263' } ]
done
$

Thanks.

**Comment by dgkimfirm** [comment]
Thanks for code.
I will try the code.
By the way, is there any limit at length of single quotation string(i.e. 'abc')

**Comment by rhtpandeyIN** [comment]
Hi @dgkimfirm,

A binary large object is a varying-length binary string that can be up to 2 gigabytes minus 1 byte (2 147 483 647 bytes) long.

Thanks.

**Comment by rhtpandeyIN** [comment]
Hi @dgkimfirm ,

are you still facing an issue with insertion of BLOB data, do let us know, we'll look into it.
Thanks.

**Comment by Alwarja** [comment]
Hi!

I tried your code, but the BLOB conversion is not working.

I receive:

[ { EMPID: 18, VALUE: 'abc' } ] as answer.
