### ISSUE TITLE
[IBM][CLI Driver] SQL4917N  Element "SQLE_CLIENT_INFO_WRKSTNNAME" in the option array is not valid

### ISSUE THREAD

**Issue by mlasprilla** [ibmdb/node-ibm_db#831]
I ran the following `node test/test-basic-test.js` after updating config.testConnectionStrings.json and got: 
`Trying to open a connection... zsh:segmentation fault node test/test-basic-test.js`

And then I ran testODBCConnection.sh after updating the script and got the following:

Trace is turned on

===============================================================================
Client information for the current copy:
===============================================================================

Client Package Type       : IBM Data Server Driver For ODBC and CLI
Client Version (level/bit): DB2 v11.5.5.0 (s2011011400/64-bit)
Client Platform           : Darwin
Install/Instance Path     : /Users/martinlasprilla/Desktop/promontory/SE2-Promontory-App/server/node_modules/ibm_db/installer/clidriver
DB2DSDRIVER_CFG_PATH value: <not-set>
db2dsdriver.cfg Path      : /Users/martinlasprilla/Desktop/promontory/SE2-Promontory-App/server/node_modules/ibm_db/installer/clidriver/cfg/db2dsdriver.cfg
DB2CLIINIPATH value       : <not-set>
db2cli.ini Path           : /Users/martinlasprilla/Desktop/promontory/SE2-Promontory-App/server/node_modules/ibm_db/installer/clidriver/cfg/db2cli.ini
db2diag.log Path          : /Users/martinlasprilla/Desktop/promontory/SE2-Promontory-App/server/node_modules/ibm_db/installer/clidriver/db2dump/db2diag.log

===============================================================================
db2dsdriver.cfg schema validation for the entire file:
===============================================================================

Note: The validation utility could not find the configuration file
db2dsdriver.cfg. The file is searched at
"/Users/martinlasprilla/Desktop/promontory/SE2-Promontory-App/server/node_modules/ibm_db/installer/clidriver/cfg/db2dsdriver.cfg".

./testODBCConnection.sh: line 29: 26606 Segmentation fault: 11  db2cli validate -database "bludb:9938aec0-8105-433e-8bf9-0fbb7e483086.c1ogj3sd0tgtu0lqde00.databases.appdomain.cloud:32459" -connect -user kwn37490 -passwd "____"
Trace has been dumped to file "1.trc"
Trace is turned off
Total number of trace records     : 5754
Trace truncated                   : NO
Trace wrapped                     : NO
Number of trace records formatted : 4533 (pid: 26606 tid 4530095616 node: -1)
Number of trace records formatted : 1177 (pid: 26606 tid 259 node: -1)
Trace truncated                   : NO
Trace wrapped                     : NO
Total number of trace records     : 5754
Number of trace records formatted : 5710
Trace truncated                   : NO
Trace wrapped                     : NO
Total number of trace records     : 5754
Number of trace records formatted : 3
Trace truncated                   : NO
Trace wrapped                     : NO
Total number of trace records     : 5754
Number of trace records formatted : 44

**Comment by bimalkjha** [comment]
@mlasprilla Please zip all generated 1.* files and share here. Also, share the output of `node --version` and `uname -m` commands. Thanks.

**Comment by mlasprilla** [comment]
@bimalkjha
node version: v17.6.0
[1-.zip](https://github.com/ibmdb/node-ibm_db/files/8216084/1-.zip)

uname -m: x86_64

**Comment by bimalkjha** [comment]
@mlasprilla I checked shared files and found below logs in 1.flw file:
```
5701           0.748580000   | | | | | | | | | | | sqljrConnectBasedOnServerList exit
5702           0.748581000   | | | | | | | | | | | sqloPdbTcpIpGetAddrInfo entry
5703           0.748581000   | | | | | | | | | | | sqloPdbTcpIpGetAddrInfo data [probe 5]
5704           0.749581000   | | | | | | | | | | | sqloPdbTcpIpGetAddrInfo data [probe 10]
5705           0.749581000   | | | | | | | | | | | sqloPdbTcpIpGetAddrInfo exit
5706           0.749582000   | | | | | | | | | | | sqloPdbTcpIpGetAddrInfo entry
5707           0.749582000   | | | | | | | | | | | sqloPdbTcpIpGetAddrInfo data [probe 5]
5708           0.749591000   | | | | | | | | | | | sqloPdbTcpIpGetAddrInfo data [probe 10]
5709           0.749591000   | | | | | | | | | | | sqloPdbTcpIpGetAddrInfo exit
5710           0.749592000   | | | | | | | | | | | sqloGetServByName entry
```
We can see there is entry in function `sqloGetServByName` but there is no exit. It seems crashing in this function while retrieving the server name.
It seems there is some bug in the underlying ODBC/CLI driver used by node-ibm_db. You can try using the ipaddress of the host(169.60.146.125) instead of full hostname in connection string and try.
We have update the underlying clidriver for macos to recent stable version. So, you can delete the older installation of ibm_db and go for a fresh installation and then try. New installation will download the latest clidriver with ibm_db.

The subject of the problem reports about SQL4917N error, but we do not see it in the shared logs. Also, db2cli validate command crashes and it do not repro the SQL4917N error. So, question is: how are you getting SQL4917N error? If you have sample test to repro the SQL4917N error, can can replace the `db2cli validate` command in testODBCConnection.sh script with `node test.js` and run the script to collect the logs/trace for SQL4917N error.
Thanks and Regards,
Bimal Jha

**Comment by mlasprilla** [comment]
Tried with new version same SQL4917N error, also tried using the host instead of full hostname, and same error. Also attached is the new logs/trace that contain that SQL4917N error.
[1-updated.zip](https://github.com/ibmdb/node-ibm_db/files/8235896/1-updated.zip)

**Comment by mlasprilla** [comment]
@bimalkjha 
The issue was due to LocalHostName and HostName being different.
scutil --get LocalHostName
scutil --get HostName

scutil --set HostName/LocalHostName to match
