### ISSUE TITLE
[IBM-z/OS] binding.gyp not found (cwd: $path) while trying to load binding.gyp

### ISSUE THREAD

**Issue by isl-raph** [ibmdb/node-ibm_db#832]
Hi everyone,

I ran into an issue trying to install the NPM package **ibm_db** in the Unix environment on z/OS 15. The problem seems to concern the loading of an untraceable file "binding.gyp" by node-gyp. Here are some relevant informations and  complete a trace of the log:

Node version : v14.17.6
NPM version : 6.14.15
uname -m output : 8561

Note that the following bits "$user" "PATH" and "HQL" have replaced out of scope informations

**First trace :** 
>(base) $user:PATH: >npm install ibm_db
> ibm_db@2.8.1 install /PATH/nodejs/appl/_helloworld/node_modules/bindings/node_modules/ibm_db
> node installer/driverInstall.js
>platform = os390, arch = s390x, node.js version = v14.17.6
>make: Error -- FSUM8705 No target
>Unable to find 'make' in PATH. Installation may fail!
>oput 'HLQ.SDSNMACS(DSNAO64C)' >'/PATH/nodejs/appl/_helloworld/node_modules/bindings/node_modules/ibm_db/build/dsnao64c.x'
>
>Error: Command failed: node-gyp configure build  --IS_DOWNLOADED=false --IBM_DB_HOME="$IBM_DB_HOME"
>FSUM9380 make: Unknown option -C
>Usage: make [-eEinpqrstuvVx] [-k|-S] [-c dir] [-D macro=value] [-f file] [macro=value ...] [target ...]
>gyp ERR! build error
>gyp ERR! stack Error: 'make' failed with exit code: 2
>gyp ERR! stack     at ChildProcess.onExit (/PRDS/nodejs/v14/lib/node_modules/npm/node_modules/node->gyp/lib/build.js:194:23)
>gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
>gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
>gyp ERR! System OS/390 26.00
>gyp ERR! command "/PRDS/nodejs/v14/bin/node" "/PRDS/nodejs/v14/bin/node-gyp" "configure" "build" "-->IS_DOWNLOADED=false" "--IBM_DB_HOME=HLQ"
>gyp ERR! cwd /PATH/nodejs/appl/_helloworld/node_modules/bindings/node_modules/ibm_db
>gyp ERR! node -v v14.17.6
>gyp ERR! node-gyp -v v5.1.0
>gyp ERR! not ok
>
>   at ChildProcess.exithandler (child_process.js:390:12)
>    at ChildProcess.emit (events.js:400:28)
>    at maybeClose (internal/child_process.js:1076:16)
>    at Socket.<anonymous> (internal/child_process.js:462:11)
>    at Socket.emit (events.js:400:28)
>    at Pipe.<anonymous> (net.js:675:12) {
>  killed: false,
>  code: 1,
>  signal: null,
>  cmd: 'node-gyp configure build  --IS_DOWNLOADED=false --IBM_DB_HOME="$IBM_DB_HOME"'
>}
>npm ERR! code ELIFECYCLE
>npm ERR! errno 1
>npm ERR! ibm_db@2.8.1 install: 'node installer/driverInstall.js'
>npm ERR! Exit status 1
>npm ERR!
>npm ERR! Failed at the ibm_db@2.8.1 install script.
>npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
>
>npm ERR! A complete log of this run can be found in:
>npm ERR!     /u/$user/.npm/_logs/2022-03-10T12_33_17_352Z-debug.log

Moving on running `node-gyp configure build  --IS_DOWNLOADED=false --IBM_DB_HOME="$IBM_DB_HOME"` leads to : 

**Second trace :** 
>(base) ~user:$path >node-gyp configure build  --IS_DOWNLOADED=false --IBM_DB_HOME="$IBM_DB_HOME"
>gyp info it worked if it ends with ok
>gyp info using node-gyp@5.1.0
>gyp info using node@14.17.6 | os390 | s390x
>gyp info find Python using Python version 3.9.5 found at "/PRDS/ported/bin/python"
>gyp info spawn /PRDS/ported/bin/python
>gyp info spawn args [
>gyp info spawn args   '/PRDS/nodejs/v14/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
>gyp info spawn args   'binding.gyp',
>gyp info spawn args   '-f',
>gyp info spawn args   'make',
>gyp info spawn args   '-I',
>gyp info spawn args   '/PATH/nodejs/appl/_helloworld/build/config.gypi',
>gyp info spawn args   '-I',
>gyp info spawn args   '/PRDS/nodejs/v14/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
>gyp info spawn args   '-I',
>gyp info spawn args   '/u/$user/.cache/node-gyp/14.17.6/include/node/common.gypi',
>gyp info spawn args   '-Dlibrary=shared_library',
>gyp info spawn args   '-Dvisibility=default',
>gyp info spawn args   '-Dnode_root_dir=/u/$user/.cache/node-gyp/14.17.6',
>gyp info spawn args   '-Dnode_exp_file=/PRDS/nodejs/v14/lib/libnode.x',
>gyp info spawn args   '-Dnode_gyp_dir=/PRDS/nodejs/v14/lib/node_modules/npm/node_modules/node-gyp',
>gyp info spawn args   '-Dnode_lib_file=/u/$user/.cache/node-gyp/14.17.6/<(target_arch)/node.lib',
>gyp info spawn args   '-Dmodule_root_dir=/PATH/nodejs/appl/_helloworld',
>gyp info spawn args   '-Dnode_engine=v8',
>gyp info spawn args   '--depth=.',
>gyp info spawn args   '--no-parallel',
>gyp info spawn args   '--generator-output',
>gyp info spawn args   'build',
>gyp info spawn args   '-Goutput_dir=.'
>gyp info spawn args ]
>gyp: binding.gyp not found (cwd: /PATH/nodejs/appl/_helloworld) while trying to load binding.gyp
>gyp ERR! configure error
>gyp ERR! stack Error: 'gyp' failed with exit code: 1
>gyp ERR! stack     at ChildProcess.onCpExit (/PRDS/nodejs/v14/lib/node_modules/npm/node_modules/node->gyp/lib/configure.js:361:16)
>gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
>gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
>gyp ERR! System OS/390 26.00
>gyp ERR! command "/PRDS/nodejs/v14/bin/node" "/PRDS/nodejs/v14/bin/node-gyp" "configure" "build" "-->IS_DOWNLOADED=false" "--IBM_DB_HOME=HLQ"
>gyp ERR! cwd /PATH/nodejs/appl/_helloworld
>gyp ERR! node -v v14.17.6
>gyp ERR! node-gyp -v v5.1.0
>gyp ERR! not ok

I already tried to create a file binding.gyp with the following content (according to [this question](https://stackoverflow.com/questions/42638918/cannot-npm-install-due-to-node-gyp-binding-gyp-not-found))
`{
        "targets": [
        {
                "target-name":"binding",
                "sources":["src/binding.cc"]
        }
        ]
}`
And received the following result after running `node-gyp configure build  --IS_DOWNLOADED=false --IBM_DB_HOME="$IBM_DB_HOME"` again: 
>(base) ~user:$path >node-gyp configure build  --IS_DOWNLOADED=false --IBM_DB_HOME="$IBM_DB_HOME"
>gyp info it worked if it ends with ok
>gyp info using node-gyp@5.1.0
>gyp info using node@14.17.6 | os390 | s390x
>gyp info find Python using Python version 3.9.5 found at "/PRDS/ported/bin/python"
>gyp info spawn /PRDS/ported/bin/python
>gyp info spawn args [
>gyp info spawn args   '/PRDS/nodejs/v14/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
>gyp info spawn args   'binding.gyp',
>gyp info spawn args   '-f',
>gyp info spawn args   'make',
>gyp info spawn args   '-I',
>gyp info spawn args   '/PATH/nodejs/appl/_helloworld/build/config.gypi',
>gyp info spawn args   '-I',
>gyp info spawn args   '/PRDS/nodejs/v14/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
>gyp info spawn args   '-I',
>gyp info spawn args   '/u/$user/.cache/node-gyp/14.17.6/include/node/common.gypi',
>gyp info spawn args   '-Dlibrary=shared_library',
>gyp info spawn args   '-Dvisibility=default',
>gyp info spawn args   '-Dnode_root_dir=/u/$user/.cache/node-gyp/14.17.6',
>gyp info spawn args   '-Dnode_exp_file=/PRDS/nodejs/v14/lib/libnode.x',
>gyp info spawn args   '-Dnode_gyp_dir=/PRDS/nodejs/v14/lib/node_modules/npm/node_modules/node-gyp',
>gyp info spawn args   '-Dnode_lib_file=/u/$user/.cache/node-gyp/14.17.6/<(target_arch)/node.lib',
>gyp info spawn args   '-Dmodule_root_dir=/PATH/nodejs/appl/_helloworld',
>gyp info spawn args   '-Dnode_engine=v8',
>gyp info spawn args   '--depth=.',
>gyp info spawn args   '--no-parallel',
>gyp info spawn args   '--generator-output',
>gyp info spawn args   'build',
>gyp info spawn args   '-Goutput_dir=.'
>gyp info spawn args ]
>Traceback (most recent call last):
>  File "/PRDS/nodejs/v14/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 50, in <module>
>    sys.exit(gyp.script_main())
>  File "/PRDS/nodejs/v14/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 554, in script_main
>    return main(sys.argv[1:])
>  File "/PRDS/nodejs/v14/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 547, in main
>    return gyp_main(args)
>  File "/PRDS/nodejs/v14/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 520, in gyp_main
>    [generator, flat_list, targets, data] = Load(
>  File "/PRDS/nodejs/v14/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 136, in Load
>    result = gyp.input.Load(build_files, default_variables, includes[:],
>  File "/PRDS/nodejs/v14/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2789, in Load
>    targets = BuildTargetsDict(data)
>  File "/PRDS/nodejs/v14/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 1357, in >BuildTargetsDict
 >   target['target_name'],
>KeyError: 'target_name'
>gyp ERR! configure error
>gyp ERR! stack Error: 'gyp' failed with exit code: 1
>gyp ERR! stack     at ChildProcess.onCpExit (/PRDS/nodejs/v14/lib/node_modules/npm/node_modules/node->gyp/lib/configure.js:361:16)
>gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
>gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
>gyp ERR! System OS/390 26.00
>gyp ERR! command "/PRDS/nodejs/v14/bin/node" "/PRDS/nodejs/v14/bin/node-gyp" "configure" "build" "-->IS_DOWNLOADED=false" "--IBM_DB_HOME=HLQ"
>gyp ERR! cwd /PATH/nodejs/appl/_helloworld
>gyp ERR! node -v v14.17.6
>gyp ERR! node-gyp -v v5.1.0
>gyp ERR! not ok

Does anybody know something about this issue ? Any help will be much appreciated.

**Comment by bimalkjha** [comment]
@isl-raph Have you set IBM_DB_HOME environment variable? If not, its ok.
Share output of below commands:
```
make --version
gcc --version
uname
db2level
```
If make and gcc is not present, install it. binding.gyp file comes with ibm_db. Alternatively, you can clone https://github.com/ibmdb/node-ibm_db.git, cd to node-ibm_db and run `npm install` command and share the complete output of `npm install` command. Thanks.

**Comment by isl-raph** [comment]
Hi, thank you for your help.
I did set IBM_DB_HOME as well as IBM_DB_INSTALLER_URL, though the following outputs might point out the lacks we're seeking:
make --version : 
> (base) ~user:/PATH/nodejs/appl/_helloworld: >make --version
>>>> Defined macro MAKECMD=make
> FSUM9380 make: Unknown option --
gcc --version:
> bash: gcc: command not found
(I'll be working on this)
uname:
> OS/390
db2level:
> bash: db2level: command not found

Is the "make" result a strange behaviour ? I do have make installed in /HOT4B0/bin

**Comment by isl-raph** [comment]
Alright, after a bit of digging and a clone of the repository, here's the result, where [HQL] has replaced the real Dsname : 

>(base) ~user:/PATH/nodejs/appl/_helloworld/node-ibm_db-master: >npm install
>npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated >for lockfileVersion@2. I'll try to do my best with it!
> ibm_db@2.8.1 install /PATH/nodejs/appl/_helloworld/node-ibm_db-master
> node installer/driverInstall.js
>platform = os390, arch = s390x, node.js version = v14.17.6
>make version =GNU Make 4.3
>[HQL] directory does not exist. Please check if you have set the IBM_DB_HOME environment variable's value correctly.
>Please set the environment variable IBM_DB_HOME to the High Level Qualifier (HLQ) of your Db2 libraries.
>npm ERR! code ELIFECYCLE
>npm ERR! errno 1
>npm ERR! ibm_db@2.8.1 install: `node installer/driverInstall.js`
>npm ERR! Exit status 1
>npm ERR!
>npm ERR! Failed at the ibm_db@2.8.1 install script.
>npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
>npm ERR! A complete log of this run can be found in:
>npm ERR!     /u/~user/.npm/_logs/2022-03-11T09_49_17_707Z-debug.log

it is strange to notice that the package installation complains about the environment variable IBM_DB_HOME not being set or not being set on the HLQ, as the Dsname actually exists and and echo of the environment variable shows the expected output.

**Comment by isl-raph** [comment]
ABORD !
after an upgrade of make to the 4.3 version, the package has been installed successfully:

>(base) ~user:/PATH/nodejs/appl/_helloworld: >npm install ibm_db
> ibm_db@2.8.1 install /nrb/nodejs/appl/_helloworld/node_modules/ibm_db
> node installer/driverInstall.js
>platform = os390, arch = s390x, node.js version = v14.17.6
>make version =GNU Make 4.3
>oput 'HQL.SDSNMACS(DSNAO64C)' '/PATH/nodejs/appl/_helloworld/node_modules/ibm_db/build/dsnao64c.x'
>make: Entering directory '/nrb/nodejs/appl/_helloworld/node_modules/ibm_db/build'
 > CXX(target) Release/obj.target/odbc_bindings/src/odbc.o
 > CXX(target) Release/obj.target/odbc_bindings/src/odbc_connection.o
 > CXX(target) Release/obj.target/odbc_bindings/src/odbc_statement.o
 > CXX(target) Release/obj.target/odbc_bindings/src/odbc_result.o
 > SOLINK_MODULE(target) Release/obj.target/odbc_bindings.node
 > COPY Release/odbc_bindings.node
>make: Leaving directory '/PATH/nodejs/appl/_helloworld/node_modules/ibm_db/build'
>ibm_db installed successfully.
>npm WARN helloworld@1.0.0 No description
>npm WARN helloworld@1.0.0 No repository field.
+ ibm_db@2.8.1
>added 67 packages from 47 contributors and audited 129 packages in 79.053s
>
>4 packages are looking for funding
>  run `npm fund` for details
> found 0 vulnerabilities

Thank's for your help.
