### ISSUE TITLE
Integer not mapping properly when binding to Stored Procedure

### ISSUE THREAD

**Issue by rcronin** [ibmdb/node-ibm_db#835]
Hello, using version 2.8.1 and experiencing an issue when binding an integer to an OUTPUT parameter on a stored procedure. It's returning a value that is not even close. We are targeting an IBM i - V7R4M0.
`const parameters: BindingParameters = [454548, {
        ParamType: 'OUTPUT',
        SQLType: 'INTEGER',
        Data: 0
      },{
        ParamType: 'OUTPUT',
        DataType: 'VARCHAR',
        Data: '',
        Length: 500
      }]`
`const results = await databaseService.db2.call('call rcclib.test_proc(?, ?, ?)', parameters);`

Above is abstracted to the follow function logic:

`async call(queryString: string, _parameters?: BindingParameters) {
    const connection = await this.connect();
    const statement = connection.prepareSync(queryString);
    statement.bindSync(_parameters);
    const results = statement.executeSync();
    await connection.close();
    return results;
  }`

Body of the stored procedure is as follows:

`CREATE or replace PROCEDURE RCCLIB.TEST_PROC ( IN INPUT1 INTEGER, OUT OUTPUT1 INTEGER, OUT OUTPUT2 VARCHAR(500) ) 
	LANGUAGE SQL 
	SPECIFIC RCCLIB.TEST_PROC
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	BEGIN 
  SET OUTPUT1 = INPUT1 + 300;
  SET OUTPUT2 = 'Hello this a returned result';
END  ; `

Here are the results when the code executes. Why is the integer output parameter returning like this? -64? Not even close to 454548

![image](https://user-images.githubusercontent.com/11710708/158257207-a8753d99-182c-4616-9039-d091b762268e.png)

**Comment by bimalkjha** [comment]
@rcronin We have executed below test file and can see it is returning the correct result:
```
$ cat intTest.js
var ibmdb= require('ibm_db');
var connStr =  'DATABASE=sample;HOSTNAME=waldevdbclnxtst06.dev.rocketsoftware.com;PORT=60000;PROTOCOL=TCPIP;UID=dbuser;PWD=dbpass';;
ibmdb.open(connStr,(err,conn)=>{
    var proc1 = "CREATE PROCEDURE RCCLIB.TEST_PROC ( IN INPUT1 INTEGER, OUT OUTPUT1 INTEGER, OUT OUTPUT2 VARCHAR(500) ) " +
                "LANGUAGE SQL SPECIFIC RCCLIB.TEST_PROC NOT DETERMINISTIC MODIFIES SQL DATA BEGIN " +
                "SET OUTPUT1 = INPUT1 + 300; SET OUTPUT2 = 'Hello this a returned result'; END ;";
    var params = [454548, { ParamType: 'OUTPUT', SQLType: 'INTEGER', Data: 0 },{ ParamType: 'OUTPUT', DataType: 'VARCHAR', Data: '', Length: 500 }];
    var query = "call RCCLIB.TEST_PROC(?, ?, ?)";
    var dropProc = "drop procedure RCCLIB.TEST_PROC( INT, INT, VARCHAR(500) )";

    var err = conn.querySync(proc1);
    if(err.length) { console.log(err); }

    var result = conn.querySync(query, params);
    console.log("Result for Sync call of test_proc ==>");
    console.log(result);
    conn.querySync(dropProc);
    conn.close(function (err) { console.log("done.");});
})

$ node intTest.js
Result for Sync call of test_proc ==>
[ 454848, 'Hello this a returned result' ]
done.
$
```
We have executed this test file against Linux server. Please try above test file and let us know the result.
We have updated the test file `ibm_db\test\test-sp-resultset.js` too to test this scenario and it works fine.
Thanks and Regards,
Bimal Jha

**Comment by bimalkjha** [comment]
I'll check it against IBMi server too and update you. Thanks.

**Comment by bimalkjha** [comment]
@rcronin I executed above test file from my Ubuntu18.04 system against V7R4M0 server and getting the same result as above. The integer value returned is 454848 which seems correct. Please let us know if you are still facing this issue.
You can call ibmdb.debug(true) in your code and see the detailed output. I think ibm_db is returning correct value but the receiver is messing up with the data may be due to datatype mismatch? Thanks.

**Comment by bimalkjha** [comment]
@rcronin Are you still facing this issue. Could you please share the result of test file ibm_db\test\test-sp-resultset.js as shared in previous update? Thanks.
