### ISSUE TITLE
Impossible to download CLI Driver - 403 Forbidden

### ISSUE THREAD

**Issue by Hermaniandr** [ibmdb/node-ibm_db#836]
Hey! 

It is impossible to download any DB2 ODBC CLI Driver as server returns "Forbidden"

![image](https://user-images.githubusercontent.com/25537824/158352020-6d8341d7-b732-427d-9783-506e168c41ae.png)

**Comment by bimalkjha** [comment]
@Hermaniandr It is up and available. You can open this page in browser and check: https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/
Thanks.
