### ISSUE TITLE
npm audit revealing critical vulnerabilities - Prototype Pollution in minimist  

### ISSUE THREAD

**Issue by repomike** [ibmdb/node-ibm_db#837]
Running `npm audit` (ibm_db v. 2.8.1) getting a few critical errors regarding minimist:

## Critical      │ Prototype Pollution in minimist
> Package `minimist`                                                     
> Dependency of  `ibm_db`                                                       
> Path  `ibm_db > fstream > mkdirp > minimist `                                 

## Critical      │ Prototype Pollution in minimist 
> Package `minimist `                                                    
> Dependency of  `ibm_db     `                                                  
> Path  `ibm_db > unzipper > fstream > mkdirp > minimist`

More info   https://github.com/advisories/GHSA-xvch-5gv4-984h

**Comment by bimalkjha** [comment]
Fixed using pull request #839

**Comment by repomike** [comment]
@bimalkjha Is this in the current version or do we need to wait until the next release?
