### ISSUE TITLE
Error connection using certificate for version 2.7.1 and higher

### ISSUE THREAD

**Issue by oipavlish** [ibmdb/node-ibm_db#841]
My application ( build from Apr 13 ibm_db version 2.7.1 ) cannot connect to database using certificate

Error Message: ibmdb.open: Create connection Exception
Message Inner: [IBM][CLI Driver] SQL30081N A communication error has been detected. Communication protocol being used: "SSL". Communication API being used: "SOCKETS". Location where the error was detected: "". Communication function detecting the error: "sqlccSSLSocketSetup". Protocol specific error code(s): "420", "*", "*". SQLSTATE=08001

Last successful build was Apr 11

I've tried 2.7.0 , 2.8.0, 2.8.1 - the same error
I've compare node_modules/ibm_db that was builded Apr 11 and Apr 13 - many files are changed

How to fix this issue ?

**Comment by huineng** [comment]
maybe have a look here https://github.com/ibmdb/node-ibm_db/issues/426

**Comment by bimalkjha** [comment]
@oipavlish `node_modules/ibm_db/installer/clidriver` is changed. So, you need to delete the existing node_modules/ibm_db/installer/clidriver directory and run `npm install` under ibm_db directory. Thanks.

**Comment by oipavlish** [comment]
I've removed clidriver and run npm install under ibm_db directory. 
Error the same 

Thanks

**Comment by bimalkjha** [comment]
@oipavlish Check your connection string or SSL port. The SQL30081N error says, the socket is closed by the server which happens if we use wrong host name or port in connection string. Thanks.
