### ISSUE TITLE
Getting error "Cannot read properties of undefined (reading 'indexOf')" in Cypress

### ISSUE THREAD

**Issue by Vsn92** [ibmdb/node-ibm_db#842]
I am working on UI testing using Cypress and wanted to connect to DB2/zOS. I have installed ibm_db and added the below code. I am using latest version of all node, cypress and ibm_db.

```
describe('Test DB2',()=>{
    it('Test',()=>{
        var ibmdb = require('ibm_db');   
        let connStr= "DATABASE=DSNT;SERVER=<hostname>;UID=<username>;PWD=<password>;PROTOCOL=TCPIP;PORT=446;"
        const conn = mysql.createConnection()
        ibmdb.open(connStr, (err,conn)=>{
            if (err) return console.log(err);
            conn.query('SELECT count(*) FROM STORE', (err,data)=>{
                if (err) console.log(err);
                else console.log(data);

                conn.close(()=> {
                console.log('done');
                });
            })
        })
    })
})
```

When running i am getting the error 

`TypeError: Cannot read properties of undefined (reading 'indexOf')
      at Function.getFileName (/__cypress/tests?p=cypress/Tests/DbTest.spec.js:8347:16)
      at bindings (/__cypress/tests?p=cypress/Tests/DbTest.spec.js:8251:48)
      at Object.eval (/__cypress/tests?p=cypress/Tests/DbTest.spec.js:9603:86)
      at Object../node_modules/ibm_db/lib/odbc.js (/__cypress/tests?p=cypress/Tests/DbTest.spec.js:12074:30)
      at __webpack_require__ (/__cypress/tests?p=cypress/Tests/DbTest.spec.js:20:30)
      at Context.eval (/__cypress/tests?p=cypress/Tests/DbTest.spec.js:8145:17)`

**Comment by Vsn92** [comment]
When i use ibm_db in a js file directly and execute it, i am not getting this error. But i execute it in cypress getting this error as  `st[i].getFileName()` returns undefined when using ibm_db in cypress.

**Comment by bimalkjha** [comment]
@Vsn92 We can see all codes in error from cypress only. I do not see `st[i].getFileName()` anywhere is ibm_db code. Could clarify which line in your shared code of `describe` function throws error? I do not see st[i].getFileName() anywhere. Thanks.

**Comment by Vsn92** [comment]
This is the stack trace i am getting in Cypress for this issue.

`cypress_runner.js:194882 TypeError: Cannot read properties of undefined (reading 'indexOf')
    at Function.getFileName (bindings.js:182:1)
    at bindings (bindings.js:82:1)
    at Object.eval (odbc.js:57:30)
    at Object../node_modules/ibm_db/lib/odbc.js (odbc.js:2525:1)
    at __webpack_require__ (bootstrap:19:1)
    at Context.eval (DbTest.spec.js:3:21)`

**Comment by bimalkjha** [comment]
@Vsn92 So, this error is from file `bindings.js:182`. This error could be due to missing file `ibm_db\build\Release\odbc_bindings.node`. Please check the contents of directory `ibm_db\build\Release`.
`odbc_bindings.node` get generated post installation and if it is missing, then there was some error during installation.
Please update database connection info in file `ibm_db\test\config.testConnectionStrings.json` and share the complete output of below commands:
```
cd ibm_db
npm install
node test\test-basic-test.js
```
Thanks.

**Comment by Vsn92** [comment]
@bimalkjha , I check the contents of the folder `ibm_db\build\Release` and i am able to see the file odbc_bindings.node. I updtaed the database connection info and ran the commands you shared. Please find the results below. It seems to be working fine. But the issue still exists when i run cypress test

`s0v03w5@m-c02fg15jml87 ibm_db % npm install

> ibm_db@2.8.1 install
> node installer/driverInstall.js

platform = darwin, arch = x64, node.js version = v16.14.2
make version =GNU Make 3.81
Rebuild Process: Found clidriver at -> /Users/s0v03w5/VSCode_WS/Cypress_SamShare/node_modules/ibm_db/installer/clidriver

Downloading of clidriver skipped - build is in progress...

  CXX(target) Release/obj.target/odbc_bindings/src/odbc.o
  CXX(target) Release/obj.target/odbc_bindings/src/odbc_connection.o
  CXX(target) Release/obj.target/odbc_bindings/src/odbc_statement.o
  CXX(target) Release/obj.target/odbc_bindings/src/odbc_result.o
  SOLINK_MODULE(target) Release/odbc_bindings.node

ibm_db installed successfully.

up to date, audited 63 packages in 8s

3 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
s0v03w5@m-c02fg15jml87 ibm_db % node test/test-basic-test.js
Trying to open a connection ... 
 ... Got the connection.
insertedRows =  1
[ [ 1, 4, 5 ] ]
[]
Selected data with special character  =  [ [ 4, 'für', null ] ]
[ [ 3, 7, 8 ] ]
Inserted row count = 1
Column Names =  [ 'C1', 'C2', 'C3' ]
Column Meta Data =  [
  {
    index: 1,
    SQL_DESC_NAME: 'C1',
    SQL_DESC_TYPE_NAME: 'INTEGER',
    SQL_DESC_CONSIZE_TYPE: 4,
    SQL_DESC_DISPLAY_SIZE: 11,
    SQL_DESC_PRECISION: 0,
    SQL_DESC_SCALE: 0,
    SQL_DESC_LENGTH: 11
  },
  {
    index: 2,
    SQL_DESC_NAME: 'C2',
    SQL_DESC_TYPE_NAME: 'VARCHAR',
    SQL_DESC_CONSIZE_TYPE: 12,
    SQL_DESC_DISPLAY_SIZE: 10,
    SQL_DESC_PRECISION: 0,
    SQL_DESC_SCALE: 0,
    SQL_DESC_LENGTH: 10
  },
  {
    index: 3,
    SQL_DESC_NAME: 'C3',
    SQL_DESC_TYPE_NAME: 'BLOB',
    SQL_DESC_CONSIZE_TYPE: -98,
    SQL_DESC_DISPLAY_SIZE: 200,
    SQL_DESC_PRECISION: 0,
    SQL_DESC_SCALE: 0,
    SQL_DESC_LENGTH: 100
  }
]
Fetched Data = 
[
  { C1: 4, C2: 'für', C3: null },
  { C1: 34245, C2: 'bimal', C3: null }
]
conn.querySync('select * from mytab1 where c1 = ?;', valueArray)
[ [ 345, 'bimal', null ] ]
Result of UPDATE Query =  [ [], [ [ 1 ] ] ]
SQLCA =  { state: '0', sqlcode: 0 }
conn.prepare('delete from mytab1 where c1 = 89')
Deleted row count = 0
done
s0v03w5@m-c02fg15jml87 ibm_db %  `

**Comment by bimalkjha** [comment]
@Vsn92 It seems `ibm_db` is installed correctly and it is working fine. But, cypress_runner.js is unable to load the ibm_db. I have no idea about this cypress_runner.js. If you can share some steps to repro the problem, I can try to identify the root cause.

Some pointer for you to debug:
Problem seems with below stack:
```
at Function.getFileName (bindings.js:182:1)
at bindings (bindings.js:82:1)
```
You can find bindings.js file as `ibm_db\node_modules\bindings\bindings.js`. The `getFileName` function is defined in this file. Use some console.log in this file to see why filename is not initialized? You should be able to figure out the problem easily.
Thanks and Regards,
Bimal Jha

**Comment by Vsn92** [comment]
Yeah, When i create a seperate js file and run i am able to connect to DB without any issue. But when i copy the same to the Cypress test and run it it is throwing an error. I tried to debug, Since cypress open a web app and the tests are executed in that, i am unable to debug this issue. Other driver modules like mysql are working fine in cypress. Will try and reach back if i get any leads.

**Comment by VishnuKugarthi** [comment]
Hi @Vsn92, I'm facing the similar issue. I can connect to db in a separate file but when i try to connect from my project it is failing with same issue which you have. Were you able to resolve this? If so please let me know how you have resolved it. Thanks
