### ISSUE TITLE
Mac - Error: [IBM][CLI Driver] SQL10013N  The specified library "GSKit Error: 2" could not be loaded.  SQLSTATE=42724

### ISSUE THREAD

**Issue by TheHun89** [ibmdb/node-ibm_db#845]
MacOS Big Sur
NodeJS 17.8
ibm_db 2.8.1
VS Code IDE 1.65.2

I have a Nodejs app that connects to a corporate DB2 database using SSL (with a cacerts file - no extension, just type File).  It connects/queries the database successfully on my Windows machine.  I already have a driver installed on that one and have the IBM_DB_HOME env variable set to point to the GSKit.  Also catalog scripts have been run.  

Connection String:
ibm_db.connect("SslServerCertificate=/Users/id/DEV/app/cacerts;SECURITY=SSL;DATABASE=xxxxxxx;HOSTNAME=xxxxxxxxxx.xxx.xxxxx.com;PORT=xxxxx;UID=xxxxxx;PROTOCOL=TCPIP;PWD=xxxxxxx;", '','')

**I am trying to run the same app on my Mac.  On my Mac I don't have anything db2 related installed (db2 client/driver/GSKit)**.  So my understanding is that the npm install would download a fresh driver.  After the npm install I try to run the app on my Mac and I get this error message.  Is there some additional setup I need to do for my Mac?  

Error: [IBM][CLI Driver] SQL10013N  The specified library "GSKit Error: 2" could not be loaded.  SQLSTATE=42724
    at Database.openSync (/Users/c6z3cw/DEV/iview-api/node_modules/ibm_db/lib/odbc.js:413:26)
    at Pool.init (/Users/c6z3cw/DEV/iview-api/node_modules/ibm_db/lib/odbc.js:2297:22)

**Comment by TheHun89** [comment]
Any thoughts on this issue?

**Comment by bimalkjha** [comment]
@TheHun89 Try below commands from your terminal and share the complete output:
```
cd /Users/c6z3cw/DEV/iview-api/node_modules/ibm_db/test
vi config.testConnectionStrings.json  => and update connection info. Add Security and SSLServerCertificate keywords too.
cd ../installer
source setenv.sh
cd ../test
node test-basic-test.js
db2level
db2cli validate
```
Thanks.

**Comment by TheHun89** [comment]
@bimalkjha  I updated the config.testConnectionStrings.json:
{ 
"DRIVER" : "{DB2 ODBC Driver}",
"SslServerCertificate" : "xxxxx",
"SECURITY" : "SSL",
"DATABASE" : "xxxxx",
"HOSTNAME" : "xxxxx",
"UID" : "xxxxx",
"PWD" : "xxxxx",
"PORT" : "xxxxx",
"PROTOCOL" : "TCPIP"
"CURRENTSCHEMA" : "xxxxx"
}

Do I need to update the driver?  What would the value be?
Below is my output when I ran the commands you told me to run:


c6z3cw@xxxxx test % cd ../installer
c6z3cw@xxxxx installer % source setenv.sh
setenv.sh:5: = not found
c6z3cw@xxxxx installer % cd ../test
c6z3cw@xxxxx test % node test-basic-test.js
Trying to open a connection ... 
[Error: [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "127.0.0.1".  Communication function detecting the error: "selectForConnectTimeout".  Protocol specific error code(s): "36", "*", "*".  SQLSTATE=08001
] {
  error: '[ibm_db] SQL_ERROR',
  sqlcode: -30081,
  state: '08001'
}
node:assert:123
  throw new AssertionError(obj);
  ^

AssertionError [ERR_ASSERTION]: [Error: [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "127.0.0.1".  Communication function detecting the error: "selectForConnectTimeout".  Protocol specific error code(s): "36", "*", "*".  SQLSTATE=08001
] {
  error: '[ibm_db] SQL_ERROR',
  sqlcode: -30081,
  state: '08001'
} == null
    at /Users/c6z3cw/DEV/iview-api/node_modules/ibm_db/test/test-basic-test.js:10:10
    at /Users/c6z3cw/DEV/iview-api/node_modules/ibm_db/lib/odbc.js:142:11
    at /Users/c6z3cw/DEV/iview-api/node_modules/ibm_db/lib/odbc.js:369:18 {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: [Error: [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "127.0.0.1".  Communication function detecting the error: "selectForConnectTimeout".  Protocol specific error code(s): "36", "*", "*".  SQLSTATE=08001
  ] {
    error: '[ibm_db] SQL_ERROR',
    sqlcode: -30081,
    state: '08001'
  },
  expected: null,
  operator: '=='
}

Node.js v17.8.0
c6z3cw@xxxxx test % db2level
zsh: command not found: db2level
c6z3cw@xxxxx test % db2cli validate
zsh: command not found: db2cli

**Comment by TheHun89** [comment]
@bimalkjha Any thoughts on this?
1. Does the config.testConnectionStrings.json look valid and do I need to update the driver?
2. When I run 'source setenv.sh' - why is the output: 'setenv.sh:5: = not found'

Any other information/instructions would be much appreciated.

**Comment by TheHun89** [comment]
I figured it out. I was using the wrong certificate.
