### ISSUE TITLE
pool init concurrently 

### ISSUE THREAD

**Issue by huineng** [ibmdb/node-ibm_db#847]
Hi it looks to me that ibmd.init(poolsize) in opening poolsize sequentially.

That is eg opening pool 5 takes 5 times more time then opening 1
This is just a question if connections cannot be opened in parallel so that opening 5 or 10 would still take the same time as 1

If not possible , no problem , i will then close this ticket

thanks

**Comment by bimalkjha** [comment]
@huineng Yes, your observation is correct. The worker thread of node.js takes the open request one by one and executes it. So, it will be sequential only. That is why our suggestion is to call pool.init() during app initialization so that it will be one time activity. Thanks.
