### ISSUE TITLE
Support for BLOB/CLOB

### ISSUE THREAD

**Issue by gjwilson21** [ibmdb/node-ibm_db#85]
Hi, 

 We are planning to use node js for pulling data from DB2,so just wanted to check if the node-ibm_db nodejs module supports BLOB/CLOB read operations.

Can you please confirm? Also if there are tutorial/documentation on using the module for clob/blob, please share.

Thanks
Joel Wilson G

**Comment by bimalkjha** [comment]
Hi Joel,

Yes, node-ibm_db supports the BLOB/CLOB read operations. See the output of below program:

$ cat selectblob.js
ibmdb = require('ibm_db')
, cn="DATABASE=SAMPLE;HOSTNAME=host.ibm.com;UID=user;PWD=userpass;PORT=50000;PROTOCOL=TCPIP";
ibmdb.open(cn, function (err,conn) 
{
  if (err) return console.log(err);
  conn.querySync("create table mytab (empId int, value BLOB)");
  conn.query("insert into mytab(empId, value) VALUES (18, blob('abc'))", function (err, data) {
    if (err) {
      console.log(err);
      return conn.closeSync();
    }
    conn.prepare("select * from mytab", function (err, stmt) {
      if(err) {
        console.log(err);
        return conn.closeSync();
      }
      stmt.execute([], function(err, result) {
        if(err) console.log(err);
        else {
          data = result.fetchAllSync();
          console.log("Selected Data = " );
          console.log(data);
          result.closeSync();
        }
        conn.querySync("drop table mytab");
        result.closeSync();
        conn.close(function () { console.log('done'); });
      });
    });
  });
});

$ node selectblob.js
Selected Data = 
[ { EMPID: 18, VALUE: '616263' } ]
done
$

Thanks.

**Comment by gjwilson21** [comment]
Thanks Bimal
