### ISSUE TITLE
z/os connections

### ISSUE THREAD

**Issue by betogm08** [ibmdb/node-ibm_db#854]
Hello!

I would like to know how to configure a z/OS connection. Can you help? What I need to consider?

**Comment by aabhajha** [comment]
@betogm08 If you know the database name, hostname, port number, userid and password for your z/OS database, you can connect to it using ibm_db driver by specifying these values in connection string as shown in [this example](https://github.com/ibmdb/node-ibm_db/blob/master/APIDocumentation.md#-1-openconnectionstring-options-callback). You can copy and run the example code to test it. Thanks.

**Comment by bimalkjha** [comment]
@betogm08 If you know the database name, hostname, port number, userid and password for your z/OS database, you can connect to it using ibm_db driver by specifying these values in connection string as shown in [this example](https://github.com/ibmdb/node-ibm_db/blob/master/APIDocumentation.md#-1-openconnectionstring-options-callback). You can copy and run the example code to test it. Thanks.

**Comment by betogm08** [comment]
Hi @bimalkjha thanks you for your response!

I did the test and what I got is the following error:
`An attempt to connect to the database server failed because of a licensing problem.  SQLSTATE=42968`

Do you know what it means?

**Comment by bimalkjha** [comment]
@betogm08 Yes, to connect a z/OS system using ibm_db driver from Linux, Unix, Windows or MacOS, you need a db2connect license file. Please see the detailed documentation about it here: https://github.com/ibmdb/node-ibm_db#sql1598n
Thanks.
