### ISSUE TITLE
Stop query while running

### ISSUE THREAD

**Issue by Colucho** [ibmdb/node-ibm_db#867]
Hi, i would need to stop a query that takes a lot of time.

How can i stop the query before ended?

Thanks

```
var ibmdb = require("ibm_db"), cn = "DATABASE=dbname;HOSTNAME=hostname;PORT=port;PROTOCOL=TCPIP;UID=dbuser;PWD=xxx";

ibmdb.open(cn, function (err, db) {
    if (err) {
	    return console.log(err);
    }
    console.log("Connection opened successfully.");
    db.query("SELECT ... FROM ..."); //Its takes a lot of time
    db.close(function (error) { //Its is called after query end
	if (error) {
		console.log("Error while closing connection,", error);
		return;
	}else{
		console.log("Connection clossed successfully.");
	}
    });
});
```

**Comment by bimalkjha** [comment]
@Colucho You can add "QueryTimeout=30;" in connection string to cancel the query execution after 30 seconds. For more info about this keyword, check [this doc](https://www.ibm.com/docs/en/db2/11.5?topic=keywords-querytimeout). Thanks.

**Comment by Colucho** [comment]
@bbigras  thanks for your answer.

It wouldn't solve my problem. That will make it impossible to execute queries of more than 30 seconds.

I will try to explain better.
I can have queries of a few seconds or several minutes.
I would need to cancel or destroy the query whenever I want.

For instance:
I execute a query that takes 2 minutes.
After 20 seconds or x seconds, I want to stop it or destroy it. (before query ends)
would that be possible?

Thanks again

**Comment by bimalkjha** [comment]
@Colucho No that is not possible. You have to kill the running application and restart it. Thanks.
