### ISSUE TITLE
There's no 'build' folder after installing ibm_db.

### ISSUE THREAD

**Issue by DaisyYangl** [ibmdb/node-ibm_db#869]
Hi, There was no 'build' folder after installing ibm_db happened today.

 RUN ls -l /usr/src/app/node_modules/ibm_db
total 5524
-rw-r--r-- 1 root root   59036 Jul  4 01:44 APIDocumentation.md
-rw-r--r-- 1 root root   24571 Jul  4 01:44 CHANGES.md
-rw-r--r-- 1 root root   12134 Jul  4 01:44 INSTALL.md
-rw-r--r-- 1 root root    1149 Jul  4 01:44 LICENSE
-rw-r--r-- 1 root root   22657 Jul  4 01:44 README.md
-rw-r--r-- 1 root root      26 Jul  4 01:44 _config.yml
-rw-r--r-- 1 root root    3493 Jul  4 01:44 binding.gyp
-rw-r--r-- 1 root root 5491286 Jul  4 01:44 build.zip
drwxr-xr-x 2 root root    4096 Jul  4 01:44 contributing
drwxr-xr-x 2 root root    4096 Jul  4 01:44 examples
drwxr-xr-x 2 root root    4096 Jul  4 01:44 installer
drwxr-xr-x 2 root root    4096 Jul  4 01:44 lib
-rw-r--r-- 1 root root    1121 Jul  4 01:44 package.json
drwxr-xr-x 2 root root    4096 Jul  4 01:44 src
drwxr-xr-x 4 root root    4096 Jul  4 01:44 test

Application log error:
   /usr/src/app/node_modules/bindings/bindings.js:135
  throw err;
  ^

Error: Could not locate the bindings file. Tried:
 → /usr/src/app/node_modules/ibm_db/build/odbc_bindings.node
 → /usr/src/app/node_modules/ibm_db/build/Debug/odbc_bindings.node
 → /usr/src/app/node_modules/ibm_db/build/Release/odbc_bindings.node
 → /usr/src/app/node_modules/ibm_db/out/Debug/odbc_bindings.node
 → /usr/src/app/node_modules/ibm_db/Debug/odbc_bindings.node
 → /usr/src/app/node_modules/ibm_db/out/Release/odbc_bindings.node
 → /usr/src/app/node_modules/ibm_db/Release/odbc_bindings.node
 → /usr/src/app/node_modules/ibm_db/build/default/odbc_bindings.node

**Comment by bimalkjha** [comment]
@DaisyYangl The platform specific clidriver file is missing under https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli directory which is causing this issue. We have informed IBM about it. Once it will be available, we'll update here. Thanks.

**Comment by mogamin2** [comment]
Same here. I want to install ibm-db for python to build a container. But cannot build. How fix?

```
$ docker build . 
...
Collecting ibm-db==3.1.0
  Downloading ibm_db-3.1.0.tar.gz (797 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /tmp/tmpxduo9vlb_in_process.py get_requires_for_build_wheel /tmp/tmpkov9s5kc
       cwd: /tmp/pip-install-6iyns7s6/ibm-db
  Complete output (30 lines):
  Detected 64-bit Python
  Downloading https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz
  Traceback (most recent call last):
  ...
  urllib.error.HTTPError: HTTP Error 500: Internal Server Error

```

**Comment by Luke-Roy-IBM** [comment]
Seeing the same issue

``` bash
...
 ibm_db@2.7.3 install /node_modules/ibm_db

> node installer/driverInstall.js

platform =  linux , arch =  x64 , node.js version =  v10.24.1

make version = GNU Make 4.1

Downloading DB2 ODBC CLI Driver from https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz...

{ Error: Request failed with status code 500

    at createError (/node_modules/ibm_db/node_modules/axios/lib/core/createError.js:16:15)

    at settle (/node_modules/ibm_db/node_modules/axios/lib/core/settle.js:17:12)

    at RedirectableRequest.handleResponse (/node_modules/ibm_db/node_modules/axios/lib/adapters/http.js:238:9)

    at RedirectableRequest.emit (events.js:198:13)

    at RedirectableRequest._processResponse (/node_modules/ibm_db/node_modules/follow-redirects/index.js:351:10)

    at ClientRequest.RedirectableRequest._onNativeResponse (/node_modules/ibm_db/node_modules/follow-redirects/index.js:57:10)

    at Object.onceWrapper (events.js:286:20)

    at ClientRequest.emit (events.js:198:13)
...
```

**Comment by MadelinTom** [comment]
Same issue 

`Error: connect ECONNREFUSED 9.214.168.53:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '9.214.168.53',
  port: 443,
  config: {
    url: 'https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/0.21.4'
    },`

**Comment by bimalkjha** [comment]
This issue is fixed now. File is getting downloaded. Thanks.

**Comment by mspsoft** [comment]
Hi,
I m facing this issue, required build folder is not getting generated.
I am using webdriverio, with ibm_db on windows platform.

Can anyone give more information on how to resolve this issue on windows.

**Comment by bimalkjha** [comment]
Check https://github.com/ibmdb/node-ibm_db/issues/991#issuecomment-2027322169 for workaround. Thanks.

**Comment by mspsoft** [comment]
Hi @bimalkjha, 
Thanks for the quick reply, I tried the installation npm install adm-zip@0.5.10 and then npm install, but it did not work

as discussed in the https://github.com/ibmdb/node-ibm_db/issues/991#issuecomment-2027322169, I am not getting any HTTP error while npm install

My Problem is- npm install doesnt throw any error.
When I am trying to execute any query on any table.. at that time I am getting below errors
Error:  Could not locate the bindings file. Tried:
→ C:\Users\abc\Documents\newworkarea\project\node_modules\ibm_db\build\odbc_bindings.node
→ C:\Users\abc\Documents\newworkarea\project\node_modules\ibm_db\build\Debug\odbc_bindings.node
→ C:\Users\abc\Documents\newworkarea\project\node_modules\ibm_db\build\Release\odbc_bindings.node
→ C:\Users\abc\Documents\newworkarea\project\node_modules\ibm_db\out\Debug\odbc_bindings.node
→ C:\Users\abc\Documents\newworkarea\projct\node_modules\ibm_db\Debug\odbc_bindings.node

any help in this is highly appreciated

**Comment by bimalkjha** [comment]
@mspsoft Please open a new issue with complete output of `npm install ibm_db --verbose` command along with other info requested in new issue template. This issue is very old and already closed. Thanks.
