### ISSUE TITLE
Error: '[node-ibm_db] Error in ODBC::GetColumnValue'

### ISSUE THREAD

**Issue by techabhay366** [ibmdb/node-ibm_db#871]
OS -: Windows 10
Db2Level -: 
DB21085I  This instance or install (instance name, where applicable: "*") uses 
"64" bits and DB2 code release "SQL11014" with level identifier "0205010F".
Informational tokens are "DB2 v11.1.4050.860", "special_39510",
"DYN1911120100WIN64_39510", and Fix Pack "5".
Product is installed at
"C:\XYZ\Redox\node_modules\ibm_db\installer\clidriver" with DB2 Copy Name
"IBM Data Server Driver For ODBC and CLI".

node.js version 
v17.2.0

ibm_db version 
2.8.1

I am using following to create open a connection with IBM Db2 database and run a simple Query. 

  var ibmdb = require('ibm_db');
    var connStr = "DRIVER={IBM DB2 ODBC DRIVER - DB2COPY1};HOSTNAME=XXXXXDATABASE=XXXX;PORT=XXXX;PROTOCOL=TCPIP;UID=xxxxxxxxxx;PWD=xxxxxxxxx";
    var conn = ibmdb.open(connStr, function (err,conn) {
        if (err) return console.log(err);
        else console.log(conn);
        conn.query('select 1 from sysibm.sysdummy1 ',function (err, data) {
          if (err) console.log(err);
          else {
                console.log(data)
                }
          conn.close(function () {
            console.log('done');
          });
        });
      });

When I run this Query i get following error -: 
Database {
  odbc: ODBC {},
  queue: SimpleQueue { fifo: [], executing: false },
  fetchMode: null,
  connected: true,
  connectTimeout: null,
  systemNaming: undefined,
  codeSet: null,
  mode: null,
  pool: null,
  conn: ODBCConnection {
    systemNaming: false,
    connectTimeout: 30,
    connected: true
  }
}
**[Error: [Microsoft][ODBC Driver Manager] Invalid descriptor index] {
  error: '[node-ibm_db] Error in ODBC::GetColumnValue',**
  sqlcode: 0,
  state: '07009'
}
done

I am connecting to remote database sitting on z/OS and I have proper license to connect . I tried using the same license for the Db2 extension and I am able to connect and rum my queries from there.

I looked at some issues raised earlier with similar error but could not fix the issue. 
May I know the reason for this error " Error in ODBC::GetColumnValue', "

**Comment by bimalkjha** [comment]
@techabhay366 In the error output, we can see `[Microsoft][ODBC Driver Manager]`. It is the root cause of problem. Probably, your installation is not correct.
First remove `DRIVER={IBM DB2 ODBC DRIVER - DB2COPY1};` from your connection string and return the test. If issue persists, then cd to C:\XYZ\Redox\node_modules\ibm_db and run `npm install`. On successful installation, rerun the test program. If still issue exist, share the complete output of `npm install` command here. Thanks.

**Comment by bimalkjha** [comment]
@techabhay366 Now you shared the complete info. From your shared output, we can see that `npm install ibm_db` successfully installed ibm_db. But, the `npm run rebuild` command has messed up. When `npm install ibm_db` is success, why you need to rebuild it again? After `npm install ibm_db`, you can update database connection info in `ibm_db\test\config.testConnectionStrings.json` file and execute `node test\test-basic-test.js` command. It'll work fine without any issue.
Now, coming to your problem. It seems you are building an `electron` application. For that we need to use `npm install ibm_db --vscode` command. It is documented on ibm_db documentation page. Just search for electron.

For your case, `electron-rebuild` is recompiling the ibm_db code and this is not generating the correct binaries.
The `npm run start` command should work fine for you after `npm install ibm_db --vscode` command, but you are not using the right version of node.js which is required for your version of electron. So, you are getting NODE_MODULE_VERSION error.
Please share version of electron.
Check required node.js version for your electron here: https://www.npmjs.com/package/electron-releases
Install same version of node.js as per: https://www.npmjs.com/package/electron-releases
Then uninstall ibm_db and reinstall using `npm install ibm_db --vscode` command.
Now, `npm run start` should work. No need to do the `electron-rebuild`. It'll corrupt ibm_db as electron-build links ibm_db with microsoft ODBC Driver and not with IBM ODBC/CLI Driver. Hence, you are getting error message from Microsoft ODBC Driver Manager. Hope it clarifies. Thanks.

**Comment by bimalkjha** [comment]
@techabhay366 We have released a new version of ibm_db@2.8.2 with electron specific enhancement.
I think you are using electron version 19.0.6. So, uninstall the existing ibm_db and reinstall it using `npm install ibm_db -electron=19.0.6`. It should work fine. Thanks.

**Comment by techabhay366** [comment]
Thanks @bimalkjha , I reinstalled ibm_db@2.8.2 and it worked like charm. No changes required.
