### ISSUE TITLE
ROW_NUMBER() OVER() returns a string instead of a number

### ISSUE THREAD

**Issue by Stoyz** [ibmdb/node-ibm_db#876]
- node.js Version: 16.15.1
- ibm_db version: 2.8.2
- For non-Windows, output of below commands:
  uname: Linux
  uname -m: x86_64

Steps to Reproduce:

1. execute query `SELECT ROW_NUMBER() OVER() FROM SYSIBM.SYSDUMMY1`
2. returned value is a string

**Comment by Stoyz** [comment]
Find out ROW_NUMBER returns a BIG_INT ([see documentation](https://www.ibm.com/docs/en/db2-for-zos/11?topic=expressions-olap-specification)), thus this is not a bug as it is returning a string for a BIG_INT.

If you agree, please close this issue.

Thank you

**Comment by bimalkjha** [comment]
@Stoyz Yes, ibm_db@2.8.2 returns BIG INT as string. Thanks for update. Closing it.
