### ISSUE TITLE
Return values from an insert statement

### ISSUE THREAD

**Issue by sprinkaan88** [ibmdb/node-ibm_db#877]
**Is your feature request related to a problem? Please describe.**
Not related to a problem.

**Describe the solution you'd like**
On inserting into a table that generates a primary key from a sequence, I would like the new primary key from the sequence number returned as an output parameter.

**Describe alternatives you've considered**
Have not come  up with an alternative.

**Additional context**
Apologies if this is already a capability, but I have not been able to determine how to do this with this package.
It seems possible from Java libraries, assuming the drivers must support it.

**Comment by bimalkjha** [comment]
@sprinkaan88 You need to use FINAL TABLE to get the primary key as ` SELECT * FROM FINAL TABLE (INSERT INTO mytab VALUES (2, 3, 'abc'))`. Thanks.

**Comment by sprinkaan88** [comment]
Thank you so much, will give this a try and revert.

**Comment by bimalkjha** [comment]
@sprinkaan88 Have you checked it? Thanks.

**Comment by sprinkaan88** [comment]
@bimalkjha apologies for the late reply, was on a short break. Yes we have tried it and it works perfectly, thanks so much.
