### ISSUE TITLE
ibm_db2 failing to install on Cirrus Openshift Environment  -  RedHat Universal base image

### ISSUE THREAD

**Issue by sagarcasm** [ibmdb/node-ibm_db#878]
IBM_Db2 package does not install while deploying on Openshift Cirrus at IBM

Docker Image: `registry.cirrus.ibm.com/public/nodejs-14:latest`
DB2 npm version: `"ibm_db": "^2.8.2",`

```
> ibm_db@2.8.2 install /backend/node_modules/ibm_db
> node installer/driverInstall.js

platform = linux, arch = x64, node.js version = v14.18.2
make version =GNU Make 4.2.1

****************************************
You are downloading a package which includes the Node.js module for IBM DB2/Informix.  The module is licensed under the Apache License 2.0. The package also includes IBM ODBC and CLI Driver from IBM, which is automatically downloaded as the node module is installed on your system/device. The license agreement to the IBM ODBC and CLI Driver is available in /backend/node_modules/ibm_db/installer/clidriver. Check for additional dependencies, which may come with their own license agreement(s). Your use of the components of the package and dependencies constitutes your acceptance of their respective license agreements. If you do not accept the terms of any license agreement(s), then delete the relevant component(s) from your device.
****************************************

Downloading DB2 ODBC CLI Driver from https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz ...

[Error: EACCES: permission denied, open '/backend/node_modules/ibm_db/installer/linuxx64_odbc_cli.tar.gz'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/backend/node_modules/ibm_db/installer/linuxx64_odbc_cli.tar.gz'
}

0.03% | 8192 bytes downloaded out of 25012651 bytes.
> core-js@3.24.0 postinstall /backend/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"
```

**Comment by sagarcasm** [comment]
Are we sill having this issue - https://www.ibm.com/support/pages/why-does-ibmdb-npm-module-fail-download-db2-odbc-cli-driver

**Comment by bimalkjha** [comment]
@sagarcasm Looking on the logs, `0.03% | 8192 bytes downloaded out of 25012651 bytes.` this message seems root cause. Why it has downloaded only 0.03%? May be some network issue? Are you able to see same error on reinstall also?
Please run these commands: `npm uninstall ibm_db` and `npm install ibm_db`.
If still fails, try to download file https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz manually by clicking on this link. Let us know the result. Thanks.

**Comment by bimalkjha** [comment]
> It looks like the linux cli driver cannot be downloaded from the below link
> 
> Are we sill having this issue - https://www.ibm.com/support/pages/why-does-ibmdb-npm-module-fail-download-db2-odbc-cli-driver

It was different issue and has been fixed. Thanks.

**Comment by bimalkjha** [comment]
If you are able to download file `https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz`, then share the complete output of below commands:
```
npm uninstall ibm_db
npm install ibm_db --loglevel verbose
```

**Comment by bimalkjha** [comment]
@sagarcasm Are you still facing this issue or your problem got resolved? Please update. Thanks.
