### ISSUE TITLE
Package.json Node Engine outdated?

### ISSUE THREAD

**Issue by jthomas** [ibmdb/node-ibm_db#88]
With the recent changes to add support for Node v4, does this package still run on node versions lower than 0.12? I've tried this locally but it fails to compile the native code. 
If not, the package.json option for the node engine is still suggesting 0.8 onwards work.

**Comment by knolleary** [comment]
Just to be clear, you dropped support for a version of node, but only incremented the minor version of your package. This is not proper semantic versioning and has broken node-red on bluemix. We're now rushing out an update for the boilerplate to use node 0.12, but this would not have happened if you had release this breaking change with a proper version number change.

**Comment by bimalkjha** [comment]
Fixed issues related to node.js v0.10.x. ibm_db@0.0.19 is working with node.js v0.10.x, 0.12.x and 4.x. Thanks.
