### ISSUE TITLE
Still having problems using node ibm_db with node v18.9 and electron 20.1

### ISSUE THREAD

**Issue by markddrake** [ibmdb/node-ibm_db#882]
Using the latest node and ibm_db@v3.0.0

```
C:\Development\YADAMU\src>node -v
v18.9.0

C:\Development\YADAMU\src> npm uninstall ibm_db

removed 33 packages, and audited 781 packages in 2s

45 packages are looking for funding
  run `npm fund` for details

5 vulnerabilities (1 low, 4 moderate)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

C:\Development\YADAMU\src>npm install ibm_db@latest

added 33 packages, and audited 814 packages in 24s

45 packages are looking for funding
  run `npm fund` for details

5 vulnerabilities (1 low, 4 moderate)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

C:\Development\YADAMU\src>node  scratch\db2\BlankPaddingArray.js
[]
[]
{
  sql: 'insert into VARCHAR_TAB (VC30) values (?)',
  params: [
    {
      ParamType: 'ARRAY',
      SQLType: 1,
      Data: [ 'Alberta', 'A', 'AA', ' ', '' ],
      Length: 10
    }
  ],
  ArraySize: 5
}
[]
[
  { VC30: 'Alberta', LEN: 7 },
  { VC30: 'A', LEN: 1 },
  { VC30: 'AA', LEN: 2 },
  { VC30: ' ', LEN: 1 },
  { VC30: '', LEN: 0 }
]
success
```

Everything works as expected.

However I need to be able to use both node and electron from the same environment
If I load the version of idb_db with the electron flag and repeat the same test I get
```
C:\Development\YADAMU\src> npm uninstall ibm_db

removed 33 packages, and audited 781 packages in 1s

45 packages are looking for funding
  run `npm fund` for details

5 vulnerabilities (1 low, 4 moderate)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

C:\Development\YADAMU\src> npm install ibm_db@latest -electron=20.1.0

added 33 packages, and audited 814 packages in 12s

45 packages are looking for funding
  run `npm fund` for details

5 vulnerabilities (1 low, 4 moderate)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

C:\Development\YADAMU\src>node  scratch\db2\BlankPaddingArray.js
node:internal/modules/cjs/loader:1203
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The module '\\?\C:\Development\YADAMU\src\node_modules\ibm_db\build\Release\odbc_bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 107. This version of Node.js requires
NODE_MODULE_VERSION 108. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
[90m    at Module._extensions..node (node:internal/modules/cjs/loader:1203:18)[39m
[90m    at Module.load (node:internal/modules/cjs/loader:997:32)[39m
[90m    at Module._load (node:internal/modules/cjs/loader:838:12)[39m
[90m    at Module.require (node:internal/modules/cjs/loader:1021:19)[39m
[90m    at require (node:internal/modules/cjs/helpers:103:18)[39m
    at bindings [90m(C:\Development\YADAMU\src\[39mnode_modules\[4mbindings[24m\bindings.js:112:48[90m)[39m
    at Object.<anonymous> [90m(C:\Development\YADAMU\src\[39mnode_modules\[4mibm_db[24m\lib\odbc.js:57:31[90m)[39m
[90m    at Module._compile (node:internal/modules/cjs/loader:1119:14)[39m
[90m    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)[39m
[90m    at Module.load (node:internal/modules/cjs/loader:997:32)[39m {
  code: [32m'ERR_DLOPEN_FAILED'[39m
}

Node.js v18.9.0

C:\Development\YADAMU\src>
```

My electron version is 
```
C:\Development\YADAMU\src>node_modules\.bin\electron.cmd -v

v20.1.0
```

Is there a way to configure my environment so I can run node applications and electron applications?. I have a primarily command and server-based application, that can also be used using an electron-based user interface.

**Comment by markddrake** [comment]
Also,regardless of whether I specify the 'electron' switch I get the following error when I try to using ibm_db. 

```
SyntaxError: Invalid or unexpected token
    at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:117:18)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:337:14)
    at async link (node:internal/modules/esm/module_job:70:21)
```
The statement that throws this error is dynamically importing a node module that in in turn imports the 'ibm_db' package e.g.

```
const test = await import('../dbi/db2/db2IDBI.js')
```

If I run the same code node (as district from electron) the code works fine, and I can import the module.

I use similar logic with the other databases I support (oracle, postgres, mssql, mysql, mongo, snowflake etc.) without encountering this error

**Comment by bimalkjha** [comment]
@markddrake Electron uses its own node.js embedded with electron having own NODE_MODULE_VERSION which is always different from NODE_MODULE_VERSION of system wide Node.js. You can check NODE_MODULE_VERSION for Electron and Node.js here: https://github.com/nodejs/node/blob/master/doc/abi_version_registry.json
For electron v20.x, NODE_MODULE_VERSION is 107 and for Node.js V18.x, NODE_MODULE_VERSION is 108.
So, basically you have two Node.js environments. One that comes with electron and other the system wide node.js (v18.x).
You can not compile a node-add on for electron and use with system Node.js and vice-versa. It is how electron works. So, the behavior observed by you is correct.
If ibm_db is installed for electron, you can use it only with electron applications like VSCode. You can not use it with normal Node.js applications.
If ibm_db is installed for node.js application, you can not use it for electron application.
You need to find a way to use the embedded node.js of electron as library and use it. Probably info on this page help you: https://www.electronjs.org/blog/electron-internals-using-node-as-a-library
The behavior observed by you is explained on this page in detail: http://blog.cinan.sk/2018/02/22/integrate-native-node-dot-js-modules-into-an-electron-app-1-slash-2/
Thanks.

**Comment by markddrake** [comment]
I assume this is a side effect of ibm_db using ODBC under the covers, and all the other databases using a more 'node native' transport protocol?. 

Is there anyway that you are aware of to have both versions of ibm_db installed in different location and configure node to look in one location and electron to look in another ?

Other wise I guess I need to pick up a node version that using NODE_MODULE_VERSION 107 for this to work.

**Comment by markddrake** [comment]
I think I can do something like this

```
npm install ibm_db_electron@npm:ibm_db -electron=20.1.0
``
And then use a conditional import to load the electron version of the package when running under electron. Will need to experiment further

**Comment by markddrake** [comment]
And then dynamically load ibm_db as follows 

```
  async testConnection() {   
    const ibmdb = await ( import(process.versions.hasOwnProperty('electron') ? "ibm_db_electron" : "ibm_db"))
	const stack = new Error().stack
	const connection = await new Promise((resolve,reject) => {
      ibmdb.open(this.createConnectionString(),(err,conn) => {
	    if (err) reject(new DB2Error(this.DRIVER_ID,err,stack,'DB2.open()'))
	    resolve(conn)
	  })
	})
	return connection
  }
```
