### ISSUE TITLE
Memory allocation error while using IBM_DB node lib 

### ISSUE THREAD

**Issue by sagarcasm** [ibmdb/node-ibm_db#885]
I have been getting memory allocation error after the OS upgrade to Monterey. 12.6

```
node(17535,0x1066a2600) malloc: *** error for object 0x7ffb4debd440: pointer being freed was not allocated
node(17535,0x1066a2600) malloc: *** set a breakpoint in malloc_error_break to debug
```

System and lib version:
OS: 
![Screen Shot 2022-09-21 at 1 10 50 AM](https://user-images.githubusercontent.com/16631348/191451066-80f8a423-52f1-41a1-b674-c8fa0c582193.png)

Node: tried both with node v14.19.3 (npm v6.14.17) and node 12.11.1
"ibm_db": 2.8.2

**Comment by bimalkjha** [comment]
@sagarcasm It seems after upgrade, libstdc++ got removed from your system. Check output of `file /usr/lib/libstdc++.6.dylib` command from terminal, it should be broken as it is pointing to a deleted file.
```
$ file /usr/lib/libstdc++.6.dylib
/usr/lib/libstdc++.6.dylib: broken symbolic link to libstdc++.6.0.9.dylib
```
To fix it, run below commands from your terminal:
```
$ brew tap homebrew/versions
$ brew install homebrew/versions/gcc8
$ export DYLD_LIBRARY_PATH=/usr/local/lib/gcc/8:$DYLD_LIBRARY_PATH
```
If issue do not get resolved, then:
```
sudo cp /usr/local/lib/gcc/8/libstdc++.6.dylib /usr/lib/libstdc++.6.0.9.dylib
reinstall ibm_db@latest
mv ..../ibm_db/clidriver/lib/libstdc++.6.dylib  ..../ibm_db/clidriver/lib/old_libstdc++.6.dylib
```
Thanks.

**Comment by sagarcasm** [comment]
Renaming the /ibm_db/clidriver/lib/libstdc++.6.dylib worked but can we have his fixed -  renaming the library every time doesn't sound like  fix to me. We have all our mac users having this issue.

**Comment by bimalkjha** [comment]
@sagarcasm Your system may have gcc8 installed so, renaming clidriver/lib/libstdc++.6.dylib fixed the issue. Few systems do not have gcc8 installed and broken link of /usr/lib/libstdc++.6.dylib creates different error. So, we need to ship this library with clidriver.
If ibm_db is installed, it already have clidriver downloaded and next install will not download it as it is already present. So, user need to rename/delete this lib only once if they see issue. Thanks.
