### ISSUE TITLE
Need support for setting autocommit

### ISSUE THREAD

**Issue by qpresley** [ibmdb/node-ibm_db#89]
Hey, I'm aware that you can set the autocommit value on a connection when the connection is acquired but also need the ability in Node.js to set/unset autocommit on an existing connection.  I've been unable to find this in the current ibm_db driver.

**Comment by bimalkjha** [comment]
By default auto commit is on. If you want to unset auto commit, use conn.beginTransaction() and conn.commitTransaction() OR conn.beginTransactionSync() and conn.commitTransactionSync(). Check the documentation for example. Thanks.
