### ISSUE TITLE
A hardcoded path to libdb2.dylib in Db2 Connect v2.3.0

### ISSUE THREAD

**Issue by aosadchyy** [ibmdb/node-ibm_db#899]
The installation of Db2 Connect v2.3.0 extension  in VS Code fails on Mac. It's looking for a hardcoded library. 
  Note,  my user is not bjha.  Must be a hardcoded path. /Users/bjha/nodework/clidriver/lib/libdb2.dylib

**Comment by bimalkjha** [comment]
@aosadchyy Thanks for reporting the issue. We have pushed the fix. Please have fresh install of Db2 Connect v2.3.0 and verify the fix. Thanks.

**Comment by aosadchyy** [comment]
Great. Thank you @bimalkjha  for the quick turnaround.  The issue is fixed. Closing it.
