### ISSUE TITLE
Release tag not available

### ISSUE THREAD

**Issue by mijikim** [ibmdb/node-ibm_db#90]
Hello,

We've been testing ibm_db with our environment and noticed that as versions change, there isn't any way for us to know what has changed between released versions because there is no tag provided in git.  Would it be possible for the team to start integrating commit tags when newer version is published into npm? 

Thank you!

**Comment by rhtpandeyIN** [comment]
Hi @mijikim 

All suggestions are open. Thanks for Suggesting us, we will consider it now onwards.
