### ISSUE TITLE
Bug Report: Can't install it on MacOS (Permission denied on driver's dylibs)

### ISSUE THREAD

**Issue by guilherme-gm** [ibmdb/node-ibm_db#902]
- Operating System Name: MacOS Monterey v12.6.3 (Also experienced on MacOS Ventura v13.1)
     - M1 macs and not M1 macs gives the same result
- db2level output from clidriver if in use: -
- Target Db2 Server Version: -
- node.js Version: 18.13.0
- ibm_db version: 3.1.0 (also tried on 2.8.2)
- For non-Windows, output of below commands:
  uname : Darwin
  uname -m : arm64
- Value of below environment variables if set: no environment vars set

- For installation related issue, complete output of `npm install ibm_db` command.
```
dev/test_ibmdb » npm i ibm_db
npm ERR! code 1
npm ERR! path /Users/guilhermemenaldo/Documents/dev/test_ibmdb/node_modules/ibm_db
npm ERR! command failed
npm ERR! command sh -c -- node installer/driverInstall.js
npm ERR! platform = darwin, arch = x64, node.js version = v18.13.0
npm ERR! make version =GNU Make 3.81
npm ERR!
npm ERR! ****************************************
npm ERR! You are downloading a package which includes the Node.js module for IBM DB2/Informix.  The module is licensed under the Apache License 2.0. The package also includes IBM ODBC and CLI Driver from IBM, which is automatically downloaded as the node module is installed on your system/device. The license agreement to the IBM ODBC and CLI Driver is available in /Users/guilhermemenaldo/Documents/dev/test_ibmdb/node_modules/ibm_db/installer/clidriver. Check for additional dependencies, which may come with their own license agreement(s). Your use of the components of the package and dependencies constitutes your acceptance of their respective license agreements. If you do not accept the terms of any license agreement(s), then delete the relevant component(s) from your device.
npm ERR! ****************************************
npm ERR!
npm ERR! Downloading DB2 ODBC CLI Driver from https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/macos64_odbc_cli.tar.gz ...
npm ERR!
100.00% | 30577610 bytes downloaded out of 30577610 bytes.[Error: EACCES: permission denied, open '/Users/guilhermemenaldo/Documents/dev/test_ibmdb/node_modules/ibm_db/installer/clidriver/lib/icc/libgsk8km.dylib'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'open',
npm ERR!   path: '/Users/guilhermemenaldo/Documents/dev/test_ibmdb/node_modules/ibm_db/installer/clidriver/lib/icc/libgsk8km.dylib'
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/guilhermemenaldo/.npm/_logs/2023-01-31T15_03_32_052Z-debug-0.log
```

Steps to Reproduce:
1.  `mkdir test_ibmdb`
2. `cd test_ibmdb`
3. `npm init -y`
4. `npm i ibm_db`
5. receive this error.

Some extra info:
1. If I follow the download link, download it myself and extract somewhere and use `IBM_DB_HOME` during `npm i`, it does pass the installation process (MacOS will then start complaining about being downloaded from the internet and etc, but it passes this first issue).
2. Running it on Linux through a container with RHEL works fine.
3. When it fails, `node_modules` doesn't get an `ibm_db` folder.
4. It was working fine until last week

Me and other 2 co-workers are experiencing the same issue.

I will update here if I find something else. Let me know if I can help with additional information.

**Comment by mariwade** [comment]
Squad found this: https://www.ibm.com/support/pages/why-does-ibmdb-npm-module-fail-download-db2-odbc-cli-driver

**Comment by palebluepixel** [comment]
I was able to work around this by setting the env var IBM_DB_INSTALLER_URL=https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/v11.1.4 (an older version of all the drivers from august) and then doing npm i normally

**Comment by bimalkjha** [comment]
I am looking into it and will update driver today. Thanks.

**Comment by bimalkjha** [comment]
@guilherme-gm @mariwade @palebluepixel Permission issue with the driver has been fixed now. Thanks.

**Comment by bimalkjha** [comment]
@guilherme-gm @mariwade @palebluepixel `ibm_db@3.3.0` has been released with native installation support for MacOS M1 Chip system with clidriver of version 12.1.0. You may install it and check. Thanks.
