### ISSUE TITLE
deferred.promise is not a function

### ISSUE THREAD

**Issue by weslleyshavo** [ibmdb/node-ibm_db#904]
When calling these two methods from the lines below, the error `deferred.promise is not a function` is occurring after version 3.0.0, referring to [enhancement](https://github.com/ibmdb/node-ibm_db/labels/enhancement) #715

https://github.com/ibmdb/node-ibm_db/blob/773fde8efa66e5e1b01e12c7fbf86599409ef364/lib/odbc.js#L2209

https://github.com/ibmdb/node-ibm_db/blob/773fde8efa66e5e1b01e12c7fbf86599409ef364/lib/odbc.js#L2285

The correct one would be just  `deferred.promise`.

**Comment by bimalkjha** [comment]
@weslleyshavo We have delivered fix for this issue and it would be available as part of next release. Thanks for reporting it. Closing the issue now. Thanks.
