### ISSUE TITLE
Security issues in dependencies

### ISSUE THREAD

**Issue by orangecoding** [ibmdb/node-ibm_db#905]
Latest ibmdb is using `minimist` in a version, that has security issues. Plz update asap, thanks.

<img width="574" alt="image" src="https://user-images.githubusercontent.com/1519704/221790783-77b97642-30fb-499c-85a9-25c49da218e0.png">

**Comment by bimalkjha** [comment]
@orangecoding Though `npm audit` is not showing any vulnerability, I have updated the version of `minimist` in package-json.lock file to latest level and pushed. It should be available in next release of ibm_db. Closing the issue now. Thanks.
