### ISSUE TITLE
Error while ibm_db driver loading

### ISSUE THREAD

**Issue by RjNayak** [ibmdb/node-ibm_db#91]
Hi ,
I am trying to do a connectivity from Node Js to DB2 instance. I have installed DB Express C in the local system. I am able to connect tothe DB2 instace from Toad and able to do DDL and DML operations. But when I am trying to connect to the same instance from Node Js , its throwing error. The error is getting thrown after  the line of code 

var ibmdb = require('ibm_db');

The error is
error: Could not load the bindings file. Tried:
→ D:\Practice\DB2POC\node_modules\ibm_db\build\odbc_bindings.node
→ D:\Practice\DB2POC\node_modules\ibm_db\build\Debug\odbc_bindings.node
→ D:\Practice\DB2POC\node_modules\ibm_db\build\Release\odbc_bindings.node
→ D:\Practice\DB2POC\node_modules\ibm_db\out\Debug\odbc_bindings.node
→ D:\Practice\DB2POC\node_modules\ibm_db\Debug\odbc_bindings.node
→ D:\Practice\DB2POC\node_modules\ibm_db\out\Release\odbc_bindings.node
→ D:\Practice\DB2POC\node_modules\ibm_db\Release\odbc_bindings.node
→ D:\Practice\DB2POC\node_modules\ibm_db\build\default\odbc_bindings.node
→ D:\Practice\DB2POC\node_modules\ibm_db\compiled\5.5.0\win32\ia32\odbc_bindings.node
    at bindings (D:\Practice\DB2POC\node_modules\bindings\bindings.js:84:13)
    at Object.<anonymous> (D:\Practice\DB2POC\node_modules\ibm_db\lib\odbc.js:27:31)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at D:\Practice\DB2POC\routes\users.js:9:13
    at Layer.handle [as handle_request] (D:\Practice\DB2POC\node_modules\express\lib\router\layer.js:95:5)

Version of Node we are using is 4.2.6.
The machine is Windows machine. I have tried with both 32 bit and 64 bit machine.

Could you please help me with this issue ?

Thanks,

Rajesh

**Comment by kathywang** [comment]
I am getting same error, have you got it resolved? could some one help solve this issue. 
Thanks.

**Comment by RjNayak** [comment]
Hi Kathywang,
Yes , I got it resolved. In my case it is resolved by changing my 32 bit
machine to 64 bit. This driver does not work with 32 bit Windows machine.

Thanks,

Rajesh

**Comment by kathywang** [comment]
Thanks Rajesh for your response.

You are right the same error as yours happened on 32 bit windows machine.
My 64 bit machine get different error after I upgrade node.js to 5.7.0
It was working on node.js 0.42.10, it seems not working on latest node.js.

Sent from my iPad

On Feb 26, 2016, at 10:05 PM, RjNayak <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Kathywang,
Yes , I got it resolved. In my case it is resolved by changing my 32 bit
machine to 64 bit. This driver does not work with 32 bit Windows machine.

Thanks,

Rajesh

On Sat 27 Feb, 2016 3:19 am kathywang, <notifications@github.com<mailto:notifications@github.com>> wrote:

> I am getting same error, have you got it resolved? could some one help
> solve this issue.
> Thanks.
>
> -
> Reply to this email directly or view it on GitHub
> <https://github.com/ibmdb/node-ibm_db/issues/91#issuecomment-189494577>.
>

-

**Comment by RjNayak** [comment]
What's the new error? Did you get any clue about this new error? May be you
can share the issue on the forum , someone else might be having a solution
for the issue. As I am new to Node , I would like to know every bit
challenges coming in Node Js and their resolutions.

Thanks,

Rajesh

**Comment by kathywang** [comment]
Thanks again Rajesh!

I will paste the exactly error message to the github issues tomorrow.
Mainly the error happens when npm install, it can not install driver.

Sent from my iPad

On Feb 26, 2016, at 11:06 PM, RjNayak <notifications@github.com<mailto:notifications@github.com>> wrote:

What's the new error? Did you get any clue about this new error? May be you
can share the issue on the forum , someone else might be having a solution
for the issue. As I am new to Node , I would like to know every bit
challenges coming in Node Js and their resolutions.

Thanks,

Rajesh

On Sat 27 Feb, 2016 9:29 am kathywang, <notifications@github.com<mailto:notifications@github.com>> wrote:

> Thanks Rajesh for your response.
>
> You are right the same error as yours happened on 32 bit windows machine.
> My 64 bit machine get different error after I upgrade node.js to 5.7.0
> It was working on node.js 0.42.10, it seems not working on latest node.js.
>
> Sent from my iPad
>
> On Feb 26, 2016, at 10:05 PM, RjNayak <notifications@github.com<mailto:notifications@github.com><mailto:
> notifications@github.com<mailto:notifications@github.com>>> wrote:
>
> Hi Kathywang,
> Yes , I got it resolved. In my case it is resolved by changing my 32 bit
> machine to 64 bit. This driver does not work with 32 bit Windows machine.
>
> Thanks,
>
> Rajesh
>
> On Sat 27 Feb, 2016 3:19 am kathywang, <notifications@github.com<mailto:notifications@github.com><mailto:
> notifications@github.com<mailto:notifications@github.com>>> wrote:
>
> > I am getting same error, have you got it resolved? could some one help
> > solve this issue.
> > Thanks.
> >
> > -
> > Reply to this email directly or view it on GitHub
> > <https://github.com/ibmdb/node-ibm_db/issues/91#issuecomment-189494577>.
> >
>
> -
> Reply to this email directly or view it on GitHub<
> https://github.com/ibmdb/node-ibm_db/issues/91#issuecomment-189564566>.
>
> -
> Reply to this email directly or view it on GitHub
> <https://github.com/ibmdb/node-ibm_db/issues/91#issuecomment-189573402>.
>

-

**Comment by bimalkjha** [comment]
@kathywang On Windows, ibm_db works with node.js v 4.x only. It also works with v5.0 but does not work with later versions. Install node.js v4.x and then ibm_db. It'll work. 
We have also documented that ibm_db is not supported on nt32 platform. Thanks.

**Comment by RjNayak** [comment]
@bimalkjha

My production environment will be Linux , so is there any specific compatibility issues of this driver with Linux Redhat 6 with Node 4.2.6 ?

**Comment by kathywang** [comment]
Here is the exactly error message I got, it's in Node.js V5.7 windows, it's run time error not npm install, I will try to re-install a Node.js 4.x version, but my co-worker he installed 5.x on Max it works.

E:\myApp\node_modules\bindings\bindings.js:79
        throw e
        ^

Error: Module version mismatch. Expected 47, got 46.
    at Error (native)
    at Object.Module._extensions..node (module.js:440:18)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at bindings (E:\myApp\node_modules\bindings\bindings.js:74:1
5)
    at Object.<anonymous> (E:\myApp\node_modules\ibm_db\lib\odbc
.js:27:31)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)


On Linux Node.js V5.5 got npm install error:

14730 error Linux 2.6.32-504.el6.x86_64
14731 error argv "/usr/bin/node" "/usr/bin/npm" "install"
14732 error node v5.5.0
14733 error npm  v3.3.12
14734 error code ELIFECYCLE
14735 error ibm_db@0.0.19 install: `node installer/driverInstall.js`
14735 error Exit status 1
14736 error Failed at the ibm_db@0.0.19 install script 'node installer/driverInstall.js'.
14736 error Make sure you have the latest version of node.js and npm installed.
14736 error If you do, this is most likely a problem with the ibm_db package,
14736 error not with npm itself.
14736 error Tell the author that this fails on your system:
14736 error     node installer/driverInstall.js
14736 error You can get their info via:
14736 error     npm owner ls ibm_db
14736 error There is likely additional logging output above.
14737 verbose exit [ 1, true ]


Please check if there is workaround for Node.js 5.x


Thanks and regards.

________________________________
发件人: RjNayak <notifications@github.com>
发送时间: 2016年2月28日 19:27
收件人: ibmdb/node-ibm_db
抄送: kathywang
主题: Re: [node-ibm_db] Error while ibm_db driver loading (#91)


@bimalkjha<https://github.com/bimalkjha>

My production environment will be Linux , so is there any specific compatibility issues of this driver with Linux Redhat 6 with Node 4.2.6 ?

―

**Comment by bimalkjha** [comment]
@RjNayak @kathywang This issue of node.js v5.x is only for Windows platform where we ship precompiled .node add-on to bypass the requirement of VisualStudio. On non-Windows platforms, ibm_db works fine with node.js v5.x too. Thanks.

**Comment by kathywang** [comment]
do you have any plans to fix the issue?

Thanks

________________________________
发件人: Bimal Kumar Jha <notifications@github.com>
发送时间: 2016年3月1日 7:50
收件人: ibmdb/node-ibm_db
抄送: kathywang
主题: Re: [node-ibm_db] Error while ibm_db driver loading (#91)


@RjNayak<https://github.com/RjNayak> @kathywang<https://github.com/kathywang> This issue of node.js v5.x is only for Windows platform where we ship precompiled .node add-on to bypass the requirement of VisualStudio. On non-Windows platforms, ibm_db works fine with node.js v5.x too. Thanks.

―

**Comment by bimalkjha** [comment]
Yes, we'll fix it soon for windows. Thanks.

**Comment by RjNayak** [comment]
Closing the issue for now. As we got the clarification. Request the forum to update once the issue is fixed for Windows.

Thanks

**Comment by sanraj22** [comment]
npm install ibm_db, is failing in redhat rhel6 with ibm_db@0.0.19 and Node version 4.2.6 also with below error.

Can you please suggest.
Error:
npm info ibm_db@0.0.19 Failed to exec install script
npm verb unlock done using /root/.npm/_locks/ibm-db-ba18bfce146f2908.lock for /root/NodeDataProvider/node_modules/ibm_db
npm verb stack Error: ibm_db@0.0.19 install: node installer/driverInstall.js
npm verb stack Exit status 1
npm verb stack at EventEmitter. (/root/softwares/node-v4.2.6-linux-x64/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
npm verb stack at emitTwo (events.js:87:13)
npm verb stack at EventEmitter.emit (events.js:172:7)
npm verb stack at ChildProcess. (/root/softwares/node-v4.2.6-linux-x64/lib/node_modules/npm/lib/utils/spawn.js:24:14)
npm verb stack at emitTwo (events.js:87:13)
npm verb stack at ChildProcess.emit (events.js:172:7)
npm verb stack at maybeClose (internal/child_process.js:821:16)
npm verb stack at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
npm verb pkgid ibm_db@0.0.19
npm verb cwd /root/NodeDataProvider
npm ERR! Linux 2.6.32-573.18.1.el6.x86_64
npm ERR! argv "/root/softwares/node-v4.2.6-linux-x64/bin/node" "/root/softwares/node-v4.2.6-linux-x64/bin/npm" "install" "ibm_db" "--verbose"
npm ERR! node v4.2.6
npm ERR! npm v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! ibm_db@0.0.19 install: node installer/driverInstall.js
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ibm_db@0.0.19 install script 'node installer/driverInstall.js'.
npm ERR! This is most likely a problem with the ibm_db package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node installer/driverInstall.js
npm ERR! You can get their info via:
npm ERR! npm owner ls ibm_db
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]
npm verb unbuild node_modules/ibm_db
npm info preuninstall ibm_db@0.0.19
npm info uninstall ibm_db@0.0.19
npm verb unbuild rmStuff ibm_db@0.0.19 from /root/NodeDataProvider/node_modules
npm info postuninstall ibm_db@0.0.19
npm verb gentlyRm don't care about contents; nuking /root/NodeDataProvider/node_modules/ibm_db

npm ERR! Please include the following file with any support request:
npm ERR! /root/NodeDataProvider/npm-debug.log

**Comment by kathywang** [comment]
It might be you OS is 32 bit, if run it on 64 bit OS, the issue might disappear.

Sent from my iPad

On Mar 21, 2016, at 3:01 PM, sanraj22 <notifications@github.com<mailto:notifications@github.com>> wrote:


npm install ibm_db, is failing in redhat rhel6 with ibm_db@0.0.19 and Node version 4.2.6 also with below error.

Can you please suggest.
Error:
npm info ibm_db@0.0.19 Failed to exec install script
npm verb unlock done using /root/.npm/_locks/ibm-db-ba18bfce146f2908.lock for /root/NodeDataProvider/node_modules/ibm_db
npm verb stack Error: ibm_db@0.0.19 install: node installer/driverInstall.js
npm verb stack Exit status 1
npm verb stack at EventEmitter. (/root/softwares/node-v4.2.6-linux-x64/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
npm verb stack at emitTwo (events.js:87:13)
npm verb stack at EventEmitter.emit (events.js:172:7)
npm verb stack at ChildProcess. (/root/softwares/node-v4.2.6-linux-x64/lib/node_modules/npm/lib/utils/spawn.js:24:14)
npm verb stack at emitTwo (events.js:87:13)
npm verb stack at ChildProcess.emit (events.js:172:7)
npm verb stack at maybeClose (internal/child_process.js:821:16)
npm verb stack at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
npm verb pkgid ibm_db@0.0.19
npm verb cwd /root/NodeDataProvider
npm ERR! Linux 2.6.32-573.18.1.el6.x86_64
npm ERR! argv "/root/softwares/node-v4.2.6-linux-x64/bin/node" "/root/softwares/node-v4.2.6-linux-x64/bin/npm" "install" "ibm_db" "--verbose"
npm ERR! node v4.2.6
npm ERR! npm v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! ibm_db@0.0.19 install: node installer/driverInstall.js
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ibm_db@0.0.19 install script 'node installer/driverInstall.js'.
npm ERR! This is most likely a problem with the ibm_db package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node installer/driverInstall.js
npm ERR! You can get their info via:
npm ERR! npm owner ls ibm_db
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]
npm verb unbuild node_modules/ibm_db
npm info preuninstall ibm_db@0.0.19
npm info uninstall ibm_db@0.0.19
npm verb unbuild rmStuff ibm_db@0.0.19 from /root/NodeDataProvider/node_modules
npm info postuninstall ibm_db@0.0.19
npm verb gentlyRm don't care about contents; nuking /root/NodeDataProvider/node_modules/ibm_db

npm ERR! Please include the following file with any support request:
npm ERR! /root/NodeDataProvider/npm-debug.log

**Comment by IronGremlin** [comment]
Hey guys, I had a variant of this issue as well - see issue 96

https://github.com/ibmdb/node-ibm_db/issues/96


Not 100% sure it'll work for you, but here's the exact steps I took to get it working - I think it will probably work to build for 5.x also with a little tweaking:

http://stackoverflow.com/questions/35445372/trouble-building-node-ibm-db-package-with-electron
