### ISSUE TITLE
Batch insert truncating email data post successful run

### ISSUE THREAD

**Issue by sagarcasm** [ibmdb/node-ibm_db#917]
- Operating System Name:
- MAC Apple M1 MAX
- Memeory 32Gb

- db2level output from clidriver if in use:
- Target Db2 Server Version:
- node.js Version: v14.21.1
- ibm_db version:  "ibm_db": "3.1.0"

Steps to Reproduce:

I am using bulk data uploads to the Table which has 2 email columns - after successfully running the scrip with 10 records I noticed that the email get truncated after they are inserted in the table.

Below is the table DDL
```
create table schema.table (
   AUTO_ID integer not null GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
   EMAIL1 VARCHAR(1000 CODEUNITS32) NOT NULL , //tried octets too
EMAIL2 VARCHAR(1000 CODEUNITS32) NOT NULL
   PRIMARY KEY (EMAIL1),
..........
);
```
I am using the below code to add the bulk data with parameterized query

```
stmt = this.db2conn.prepareSync(sql);
await stmt.bindSync(data);
stmt.setAttrSync(ibmdb.SQL_ATTR_PARAMSET_SIZE, size);
result = await stmt.executeSync();
```

I tried a simple insert  but later also switched to insert by casting to VARCHAR
```
const insertQuery = `INSERT INTO schema.table
(EMAIL1, EMAIL2)
VALUES(CAST (? AS VARCHAR),CAST (? AS VARCHAR))`;
```
Below is how the insert array looks like 

```
[
  {
    ParamType: 'ARRAY',
    DataType: 'VARCHAR',
    Data: [
      email,email2
    ]
  },
  {
    ParamType: 'ARRAY',
    DataType: 'VARCHAR',
    Data: [
     email,email2
    ]
  },
```
Below is how the data gets inserted

![Screenshot 2023-04-19 at 3 43 24 PM](https://user-images.githubusercontent.com/16631348/233215478-24dcbdc1-be88-4b3b-840d-d6a7c8468348.png)

This issue happens for both email fields, can you help me understand what should the email columns be cast as? while printing the data before `await stmt.bindSync(data);` I get all the values appropriately but post insert when I check the db they are truncated from the right.

**Comment by bimalkjha** [comment]
@sagarcasm Use `Length:50` key in your param as used here: https://github.com/ibmdb/node-ibm_db/blob/master/test/test-array-insert.js#L25
I see data as `Data: [ email,email2 ]` in your shared code, should it be `Data: [ email1,email2 ]`?
Please share the contents of EMAIL1 and EMAIL2. Better to share small test.js file to repro the issue. Thanks.

**Comment by bimalkjha** [comment]
@sagarcasm Hope your issue get resolved by correcting the application code. Let us know otherwise. Closing the issue now. Thanks.
