### ISSUE TITLE
Bug Report, English displays fine but non-English languages break when using DB2 connection ibm_db in nodejs

### ISSUE THREAD

**Issue by mbleeDev** [ibmdb/node-ibm_db#918]
I used ibm_db to connect to a db2 db in nodejs, it connects fine and even selects, but I have one problem.

I'm getting a language breaking issue.

There is a problem that the language breaks even if I declare like below.
Or how can I make the language not break?

English is fine, but other languages are broken.
The DB2 side is UTF-8, and when I query the same query with dbTool, the language is not broken.

var connStr = "DATABASE=database;HOSTNAME=ip;PORT=port;UID=id;PWD=pass;PROTOCOL=TCPIP;charset=utf8";

How can we ensure that non-English languages are not broken?

Results from using nodejs db2 ibm_db)

[
  {
    COMPANYID: '000001',
    USERID: 'TEST01',
    USERNAME: '������',
    USEYN: 'Y'
  },
  {
    COMPANYID: '000001',
    USERID: 'TEST02',
    USERNAME: '����',
    USEYN: 'Y'
  }
]

- Operating System Name:
- db2level output from clidriver if in use:
- Target Db2 Server Version:
- node.js Version:
- ibm_db version:
- For non-Windows, output of below commands:
  uname
  uname -m
- Value of below environment variables if set:
  IBM_DB_HOME:
  PATH:
  LIB/LD_LIBRARY_PATH/DYLD_LIBRARY_PATH:

- Test script to reproduce the problem.
- For installation related issue, complete output of `npm install ibm_db` command.
- For connection related issue, update database connection info in `ibm_db/test/config.testConnectionStrings.json` file and share complete output of below commands:
  * cd .../ibm_db
  * npm install
  * node test/test-basic-test.js

Steps to Reproduce:

1.
2.

**Comment by bimalkjha** [comment]
@mbleeDev You have not answered the questions asked in issue template. We want to know which OS you are using: Mac, Windows or Linux?
To solve your issue, you need to set system level environment variable DB2CODEPAGE=1208 and then run your app. You can also code in your app after importing ibm_db as `process.env.DB2CODEPAGE = 1208;`. Thanks.

**Comment by mbleeDev** [comment]
Thank you. I tried the process.env.DB2CODEPAGE = 1208; you mentioned and it worked.

Thank you!
