### ISSUE TITLE
Failed to catch error message when query failed to execute

### ISSUE THREAD

**Issue by MapleWorld** [ibmdb/node-ibm_db#92]
I am building a website for the QA team, and we are using the SQL Query Engine to generate random db2 sql query using genetic algorithm, most of the queries were able to execute just fine using this module, however, sometime it doesn't catch and display the error when the query failed to execute.

The error message shows up properly when we execute them directly in db2 command line, but not in nodejs.

I created a sample repository on github for you guys to see the actual sql query and the structure of the sample database and table that I was testing on https://github.com/MapleWorld/ibmdbTest

These error messages below are not in the err even though conn.query failed
It only returned { errors: [] }

But in db2 command line it returns 

Query 1 error message

```
C224
---------------------------------
SQL0413N  Overflow occurred during numeric data type conversion.
SQLSTATE=22003
```

Query 2 error message

```
C104
------------------------------------------
SQL0420N  Invalid character found in a character string argument of the
function "DECFLOAT".  SQLSTATE=22018
```

Query 3 error message

```
C569
-----------
SQL0801N  Division by zero was attempted.  SQLSTATE=22012
```

**Comment by bimalkjha** [comment]
@MapleWorld Thanks for providing the repro. I am able to repro it and looking further. Will provide update soon. Thanks.

**Comment by bimalkjha** [comment]
@MapleWorld conn.query() is written to ignore Fetch time error because Fetch on a DDL will always return error. Since, ibm_db do not parses the SQL, we can't know the SQL passed to query() is an INSERT or SELECT. I would say it is the current design of ibm_db. If you want to catch such errors, recommended way is to use conn.prepare() and stmt.execute(). You'll get above errors. Thanks.

**Comment by bimalkjha** [comment]
Also, query2 seems working fine with latest version of ibm_db. I am able to get below result from query2:

[ { C104: '1' },
  { C104: '2' },
  { C104: '3' },
  { C104: '4' },
  { C104: '5' },
  { C104: '6' },
  { C104: '7' } ]

Thanks.
