### ISSUE TITLE
npm install ibm_db is returning error: "gyp ERR! stack Error: `make` failed with exit code: 2" on WSL Ubuntu

### ISSUE THREAD

**Issue by fmgyotoku** [ibmdb/node-ibm_db#937]
## Operating System Name where ibm_db is installed: Windows WSL2 with Ubuntu

  name: Linux
  uname -m: x86_64
  node -v: v18.16.0

  npm ls ibm_db
      data-comparator@1.0.0 /home/john.doe/Development/IBM/data-comparator
      └── (empty)

  db2level
      DB21085I  This instance or install (instance name, where applicable: "*") uses
      "64" bits and DB2 code release "SQL11058" with level identifier "0609010F".
      Informational tokens are "DB2 v11.5.8.0", "special_26260",
      "DYN2301190517AMD64_26260", and Fix Pack "0".
      Product is installed at "..".

  echo $IBM_DB_HOME: Not set

  echo $LD_LIBRARY_PATH $DYLD_LIBRARY_PATH: Returning nothing
  
- Value of any other ibm_db specific environment variable if in use.

## Please provide below problem specific info:
=========================================
I executed the following command to install ibm_db: npm install ibm_db.

No variable was set as I'm expecting to download and install the clidriver in the installation process.

Here is the log execution:
0 verbose cli /home/john.doe/.nvm/versions/node/v18.16.0/bin/node /home/john.doe/.nvm/versions/node/v18.16.0/bin/npm
1 info using npm@9.5.1
2 info using node@v18.16.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/home/john.doe/.nvm/versions/node/v18.16.0/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/home/john.doe/Development/IBM/data-comparator/.npmrc Completed in 1ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:/home/john.doe/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/home/john.doe/.nvm/versions/node/v18.16.0/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 1ms
16 timing config:load Completed in 6ms
17 timing npm:load:configload Completed in 6ms
18 timing npm:load:mkdirpcache Completed in 0ms
19 timing npm:load:mkdirplogs Completed in 1ms
20 verbose title npm install ibm_db
21 verbose argv "install" "ibm_db"
22 timing npm:load:setTitle Completed in 0ms
23 timing config:load:flatten Completed in 1ms
24 timing npm:load:display Completed in 3ms
25 verbose logfile logs-max:10 dir:/home/john.doe/.npm/_logs/2023-07-29T09_27_41_992Z-
26 verbose logfile /home/john.doe/.npm/_logs/2023-07-29T09_27_41_992Z-debug-0.log
27 timing npm:load:logFile Completed in 3ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 14ms
31 timing arborist:ctor Completed in 1ms
32 silly logfile start cleaning logs, removing 2 files
33 silly logfile done cleaning log files
34 timing arborist:ctor Completed in 0ms
35 timing idealTree:init Completed in 9ms
36 timing idealTree:userRequests Completed in 3ms
37 silly idealTree buildDeps
38 silly fetch manifest ibm_db@*
39 http fetch GET 200 https://registry.npmjs.org/ibm_db 12ms (cache hit)
40 silly placeDep ROOT ibm_db@3.2.1 OK for: data-comparator@1.0.0 want: *
41 silly fetch manifest adm-zip@^0.5.10
42 silly fetch manifest axios@^0.26.1
43 silly fetch manifest big-integer@^1.6.51
44 silly fetch manifest bindings@^1.5.0
45 silly fetch manifest fs-extra@^8.1.0
46 silly fetch manifest lodash@^4.17.21
47 silly fetch manifest nan@^2.17.0
48 silly fetch manifest q@^1.5.1
49 silly fetch manifest targz@^1.0.1
50 http fetch GET 200 https://registry.npmjs.org/adm-zip 24ms (cache hit)
51 http fetch GET 200 https://registry.npmjs.org/axios 25ms (cache hit)
52 http fetch GET 200 https://registry.npmjs.org/bindings 26ms (cache hit)
53 http fetch GET 200 https://registry.npmjs.org/targz 25ms (cache hit)
54 http fetch GET 200 https://registry.npmjs.org/big-integer 31ms (cache hit)
55 http fetch GET 200 https://registry.npmjs.org/fs-extra 31ms (cache hit)
56 http fetch GET 200 https://registry.npmjs.org/lodash 32ms (cache hit)
57 http fetch GET 200 https://registry.npmjs.org/q 32ms (cache hit)
58 http fetch GET 200 https://registry.npmjs.org/nan 33ms (cache hit)
59 timing idealTree:#root Completed in 58ms
60 silly placeDep ROOT adm-zip@0.5.10 OK for: ibm_db@3.2.1 want: ^0.5.10
61 silly placeDep ROOT axios@0.26.1 OK for: ibm_db@3.2.1 want: ^0.26.1
62 silly placeDep ROOT big-integer@1.6.51 OK for: ibm_db@3.2.1 want: ^1.6.51
63 silly placeDep ROOT bindings@1.5.0 OK for: ibm_db@3.2.1 want: ^1.5.0
64 silly placeDep ROOT fs-extra@8.1.0 OK for: ibm_db@3.2.1 want: ^8.1.0
65 silly placeDep ROOT lodash@4.17.21 OK for: ibm_db@3.2.1 want: ^4.17.21
66 silly placeDep ROOT nan@2.17.0 OK for: ibm_db@3.2.1 want: ^2.17.0
67 silly placeDep ROOT q@1.5.1 OK for: ibm_db@3.2.1 want: ^1.5.1
68 silly placeDep ROOT targz@1.0.1 OK for: ibm_db@3.2.1 want: ^1.0.1
69 silly fetch manifest follow-redirects@^1.14.8
70 silly fetch manifest file-uri-to-path@1.0.0
71 silly fetch manifest graceful-fs@^4.2.0
72 silly fetch manifest jsonfile@^4.0.0
73 silly fetch manifest universalify@^0.1.0
74 silly fetch manifest tar-fs@^1.8.1
75 http fetch GET 200 https://registry.npmjs.org/file-uri-to-path 10ms (cache hit)
76 http fetch GET 200 https://registry.npmjs.org/follow-redirects 12ms (cache hit)
77 http fetch GET 200 https://registry.npmjs.org/tar-fs 10ms (cache hit)
78 http fetch GET 200 https://registry.npmjs.org/graceful-fs 16ms (cache hit)
79 http fetch GET 200 https://registry.npmjs.org/jsonfile 16ms (cache hit)
80 http fetch GET 200 https://registry.npmjs.org/universalify 16ms (cache hit)
81 timing idealTree:node_modules/ibm_db Completed in 29ms
82 timing idealTree:node_modules/adm-zip Completed in 0ms
83 silly placeDep ROOT follow-redirects@1.15.2 OK for: axios@0.26.1 want: ^1.14.8
84 timing idealTree:node_modules/axios Completed in 1ms
85 timing idealTree:node_modules/big-integer Completed in 0ms
86 silly placeDep ROOT file-uri-to-path@1.0.0 OK for: bindings@1.5.0 want: 1.0.0
87 timing idealTree:node_modules/bindings Completed in 1ms
88 timing idealTree:node_modules/file-uri-to-path Completed in 0ms
89 timing idealTree:node_modules/follow-redirects Completed in 0ms
90 silly placeDep ROOT graceful-fs@4.2.11 OK for: fs-extra@8.1.0 want: ^4.2.0
91 silly placeDep ROOT jsonfile@4.0.0 OK for: fs-extra@8.1.0 want: ^4.0.0
92 silly placeDep ROOT universalify@0.1.2 OK for: fs-extra@8.1.0 want: ^0.1.0
93 timing idealTree:node_modules/fs-extra Completed in 2ms
94 timing idealTree:node_modules/graceful-fs Completed in 0ms
95 timing idealTree:node_modules/jsonfile Completed in 0ms
96 timing idealTree:node_modules/lodash Completed in 0ms
97 timing idealTree:node_modules/nan Completed in 0ms
98 timing idealTree:node_modules/q Completed in 0ms
99 silly placeDep ROOT tar-fs@1.16.3 OK for: targz@1.0.1 want: ^1.8.1
100 silly fetch manifest chownr@^1.0.1
101 silly fetch manifest mkdirp@^0.5.1
102 silly fetch manifest pump@^1.0.0
103 silly fetch manifest tar-stream@^1.1.2
104 http fetch GET 200 https://registry.npmjs.org/tar-stream 7ms (cache hit)
105 http fetch GET 200 https://registry.npmjs.org/chownr 9ms (cache hit)
106 http fetch GET 200 https://registry.npmjs.org/mkdirp 8ms (cache hit)
107 http fetch GET 200 https://registry.npmjs.org/pump 9ms (cache hit)
108 timing idealTree:node_modules/targz Completed in 12ms
109 silly placeDep ROOT chownr@1.1.4 OK for: tar-fs@1.16.3 want: ^1.0.1
110 silly placeDep ROOT mkdirp@0.5.6 OK for: tar-fs@1.16.3 want: ^0.5.1
111 silly placeDep ROOT pump@1.0.3 OK for: tar-fs@1.16.3 want: ^1.0.0
112 silly placeDep ROOT tar-stream@1.6.2 OK for: tar-fs@1.16.3 want: ^1.1.2
113 silly fetch manifest minimist@^1.2.6
114 silly fetch manifest end-of-stream@^1.1.0
115 silly fetch manifest once@^1.3.1
116 silly fetch manifest bl@^1.0.0
117 silly fetch manifest buffer-alloc@^1.2.0
118 silly fetch manifest end-of-stream@^1.0.0
119 silly fetch manifest fs-constants@^1.0.0
120 silly fetch manifest readable-stream@^2.3.0
121 silly fetch manifest to-buffer@^1.1.1
122 silly fetch manifest xtend@^4.0.0
123 http fetch GET 200 https://registry.npmjs.org/bl 22ms (cache hit)
124 http fetch GET 200 https://registry.npmjs.org/buffer-alloc 22ms (cache hit)
125 http fetch GET 200 https://registry.npmjs.org/once 23ms (cache hit)
126 http fetch GET 200 https://registry.npmjs.org/end-of-stream 22ms (cache hit)
127 http fetch GET 200 https://registry.npmjs.org/minimist 25ms (cache hit)
128 http fetch GET 200 https://registry.npmjs.org/xtend 19ms (cache hit)
129 http fetch GET 200 https://registry.npmjs.org/to-buffer 21ms (cache hit)
130 http fetch GET 200 https://registry.npmjs.org/end-of-stream 26ms (cache hit)
131 http fetch GET 200 https://registry.npmjs.org/fs-constants 22ms (cache hit)
132 http fetch GET 200 https://registry.npmjs.org/readable-stream 22ms (cache hit)
133 timing idealTree:node_modules/tar-fs Completed in 32ms
134 timing idealTree:node_modules/chownr Completed in 0ms
135 silly placeDep ROOT minimist@1.2.8 OK for: mkdirp@0.5.6 want: ^1.2.6
136 timing idealTree:node_modules/mkdirp Completed in 1ms
137 timing idealTree:node_modules/minimist Completed in 0ms
138 silly placeDep ROOT end-of-stream@1.4.4 OK for: pump@1.0.3 want: ^1.1.0
139 silly placeDep ROOT once@1.4.0 OK for: pump@1.0.3 want: ^1.3.1
140 silly fetch manifest wrappy@1
141 http fetch GET 200 https://registry.npmjs.org/wrappy 4ms (cache hit)
142 timing idealTree:node_modules/pump Completed in 6ms
143 timing idealTree:node_modules/end-of-stream Completed in 0ms
144 silly placeDep ROOT wrappy@1.0.2 OK for: once@1.4.0 want: 1
145 timing idealTree:node_modules/once Completed in 0ms
146 silly placeDep ROOT bl@1.2.3 OK for: tar-stream@1.6.2 want: ^1.0.0
147 silly placeDep ROOT buffer-alloc@1.2.0 OK for: tar-stream@1.6.2 want: ^1.2.0
148 silly placeDep ROOT fs-constants@1.0.0 OK for: tar-stream@1.6.2 want: ^1.0.0
149 silly placeDep ROOT readable-stream@2.3.8 OK for: tar-stream@1.6.2 want: ^2.3.0
150 silly placeDep ROOT to-buffer@1.1.1 OK for: tar-stream@1.6.2 want: ^1.1.1
151 silly placeDep ROOT xtend@4.0.2 OK for: tar-stream@1.6.2 want: ^4.0.0
152 silly fetch manifest safe-buffer@^5.1.1
153 silly fetch manifest buffer-alloc-unsafe@^1.1.0
154 silly fetch manifest buffer-fill@^1.0.0
155 silly fetch manifest core-util-is@~1.0.0
156 silly fetch manifest inherits@~2.0.3
157 silly fetch manifest isarray@~1.0.0
158 silly fetch manifest process-nextick-args@~2.0.0
159 silly fetch manifest safe-buffer@~5.1.1
160 silly fetch manifest string_decoder@~1.1.1
161 silly fetch manifest util-deprecate@~1.0.1
162 http fetch GET 200 https://registry.npmjs.org/safe-buffer 22ms (cache hit)
163 http fetch GET 200 https://registry.npmjs.org/buffer-alloc-unsafe 23ms (cache hit)
164 http fetch GET 200 https://registry.npmjs.org/isarray 21ms (cache hit)
165 http fetch GET 200 https://registry.npmjs.org/safe-buffer 20ms (cache hit)
166 http fetch GET 200 https://registry.npmjs.org/string_decoder 20ms (cache hit)
167 http fetch GET 200 https://registry.npmjs.org/buffer-fill 23ms (cache hit)
168 http fetch GET 200 https://registry.npmjs.org/inherits 22ms (cache hit)
169 http fetch GET 200 https://registry.npmjs.org/core-util-is 24ms (cache hit)
170 http fetch GET 200 https://registry.npmjs.org/process-nextick-args 22ms (cache hit)
171 http fetch GET 200 https://registry.npmjs.org/util-deprecate 21ms (cache hit)
172 timing idealTree:node_modules/tar-stream Completed in 30ms
173 silly placeDep ROOT safe-buffer@5.2.1 OK for: bl@1.2.3 want: ^5.1.1
174 timing idealTree:node_modules/bl Completed in 2ms
175 silly placeDep ROOT buffer-alloc-unsafe@1.1.0 OK for: buffer-alloc@1.2.0 want: ^1.1.0
176 silly placeDep ROOT buffer-fill@1.0.0 OK for: buffer-alloc@1.2.0 want: ^1.0.0
177 timing idealTree:node_modules/buffer-alloc Completed in 1ms
178 timing idealTree:node_modules/buffer-alloc-unsafe Completed in 0ms
179 timing idealTree:node_modules/buffer-fill Completed in 0ms
180 timing idealTree:node_modules/fs-constants Completed in 0ms
181 silly placeDep ROOT core-util-is@1.0.3 OK for: readable-stream@2.3.8 want: ~1.0.0
182 silly placeDep ROOT inherits@2.0.4 OK for: readable-stream@2.3.8 want: ~2.0.3
183 silly placeDep ROOT isarray@1.0.0 OK for: readable-stream@2.3.8 want: ~1.0.0
184 silly placeDep ROOT process-nextick-args@2.0.1 OK for: readable-stream@2.3.8 want: ~2.0.0
185 silly placeDep node_modules/readable-stream safe-buffer@5.1.2 OK for: readable-stream@2.3.8 want: ~5.1.1
186 silly placeDep ROOT string_decoder@1.1.1 OK for: readable-stream@2.3.8 want: ~1.1.1
187 silly placeDep ROOT util-deprecate@1.0.2 OK for: readable-stream@2.3.8 want: ~1.0.1
188 silly fetch manifest safe-buffer@~5.1.0
189 timing idealTree:node_modules/readable-stream Completed in 6ms
190 timing idealTree:node_modules/core-util-is Completed in 0ms
191 timing idealTree:node_modules/inherits Completed in 0ms
192 timing idealTree:node_modules/isarray Completed in 0ms
193 timing idealTree:node_modules/process-nextick-args Completed in 0ms
194 timing idealTree:node_modules/safe-buffer Completed in 0ms
195 silly placeDep node_modules/string_decoder safe-buffer@5.1.2 OK for: string_decoder@1.1.1 want: ~5.1.0
196 timing idealTree:node_modules/string_decoder Completed in 1ms
197 timing idealTree:node_modules/to-buffer Completed in 0ms
198 timing idealTree:node_modules/universalify Completed in 0ms
199 timing idealTree:node_modules/util-deprecate Completed in 0ms
200 timing idealTree:node_modules/wrappy Completed in 0ms
201 timing idealTree:node_modules/xtend Completed in 0ms
202 timing idealTree:node_modules/readable-stream/node_modules/safe-buffer Completed in 0ms
203 timing idealTree:node_modules/string_decoder/node_modules/safe-buffer Completed in 0ms
204 timing idealTree:buildDeps Completed in 186ms
205 timing idealTree:fixDepFlags Completed in 0ms
206 timing idealTree Completed in 199ms
207 timing reify:loadTrees Completed in 200ms
208 timing reify:diffTrees Completed in 1ms
209 silly reify moves {}
210 timing reify:retireShallow Completed in 0ms
211 timing reify:createSparse Completed in 5ms
212 timing reify:loadBundles Completed in 0ms
213 silly audit bulk request {
213 silly audit   ibm_db: [ '3.2.1' ],
213 silly audit   'adm-zip': [ '0.5.10' ],
213 silly audit   axios: [ '0.26.1' ],
213 silly audit   'big-integer': [ '1.6.51' ],
213 silly audit   bindings: [ '1.5.0' ],
213 silly audit   'fs-extra': [ '8.1.0' ],
213 silly audit   lodash: [ '4.17.21' ],
213 silly audit   nan: [ '2.17.0' ],
213 silly audit   q: [ '1.5.1' ],
213 silly audit   targz: [ '1.0.1' ],
213 silly audit   'follow-redirects': [ '1.15.2' ],
213 silly audit   'file-uri-to-path': [ '1.0.0' ],
213 silly audit   'graceful-fs': [ '4.2.11' ],
213 silly audit   jsonfile: [ '4.0.0' ],
213 silly audit   universalify: [ '0.1.2' ],
213 silly audit   'tar-fs': [ '1.16.3' ],
213 silly audit   chownr: [ '1.1.4' ],
213 silly audit   mkdirp: [ '0.5.6' ],
213 silly audit   pump: [ '1.0.3' ],
213 silly audit   'tar-stream': [ '1.6.2' ],
213 silly audit   minimist: [ '1.2.8' ],
213 silly audit   'end-of-stream': [ '1.4.4' ],
213 silly audit   once: [ '1.4.0' ],
213 silly audit   wrappy: [ '1.0.2' ],
213 silly audit   bl: [ '1.2.3' ],
213 silly audit   'buffer-alloc': [ '1.2.0' ],
213 silly audit   'fs-constants': [ '1.0.0' ],
213 silly audit   'readable-stream': [ '2.3.8' ],
213 silly audit   'to-buffer': [ '1.1.1' ],
213 silly audit   xtend: [ '4.0.2' ],
213 silly audit   'safe-buffer': [ '5.2.1', '5.1.2' ],
213 silly audit   'buffer-alloc-unsafe': [ '1.1.0' ],
213 silly audit   'buffer-fill': [ '1.0.0' ],
213 silly audit   'core-util-is': [ '1.0.3' ],
213 silly audit   inherits: [ '2.0.4' ],
213 silly audit   isarray: [ '1.0.0' ],
213 silly audit   'process-nextick-args': [ '2.0.1' ],
213 silly audit   string_decoder: [ '1.1.1' ],
213 silly audit   'util-deprecate': [ '1.0.2' ]
213 silly audit }
214 timing reifyNode:node_modules/buffer-alloc-unsafe Completed in 299ms
215 timing reifyNode:node_modules/buffer-fill Completed in 300ms
216 timing reifyNode:node_modules/buffer-alloc Completed in 301ms
217 timing reifyNode:node_modules/process-nextick-args Completed in 308ms
218 timing reifyNode:node_modules/end-of-stream Completed in 309ms
219 timing reifyNode:node_modules/chownr Completed in 310ms
220 timing reifyNode:node_modules/wrappy Completed in 311ms
221 timing reifyNode:node_modules/once Completed in 311ms
222 timing reifyNode:node_modules/universalify Completed in 311ms
223 timing reifyNode:node_modules/bindings Completed in 312ms
224 timing reifyNode:node_modules/core-util-is Completed in 314ms
225 timing reifyNode:node_modules/inherits Completed in 315ms
226 timing reifyNode:node_modules/fs-constants Completed in 315ms
227 timing reifyNode:node_modules/util-deprecate Completed in 318ms
228 timing reifyNode:node_modules/to-buffer Completed in 317ms
229 timing reifyNode:node_modules/jsonfile Completed in 318ms
230 timing reifyNode:node_modules/string_decoder Completed in 321ms
231 timing reifyNode:node_modules/xtend Completed in 320ms
232 timing reifyNode:node_modules/mkdirp Completed in 321ms
233 timing reifyNode:node_modules/pump Completed in 321ms
234 timing reifyNode:node_modules/graceful-fs Completed in 321ms
235 timing reifyNode:node_modules/targz Completed in 322ms
236 timing reifyNode:node_modules/string_decoder/node_modules/safe-buffer Completed in 323ms
237 timing reifyNode:node_modules/readable-stream/node_modules/safe-buffer Completed in 322ms
238 timing reifyNode:node_modules/safe-buffer Completed in 322ms
239 timing reifyNode:node_modules/isarray Completed in 324ms
240 timing reifyNode:node_modules/tar-stream Completed in 324ms
241 timing reifyNode:node_modules/bl Completed in 325ms
242 timing reifyNode:node_modules/follow-redirects Completed in 326ms
243 timing reifyNode:node_modules/file-uri-to-path Completed in 327ms
244 timing reifyNode:node_modules/q Completed in 329ms
245 timing reifyNode:node_modules/big-integer Completed in 336ms
246 timing reifyNode:node_modules/adm-zip Completed in 346ms
247 timing reifyNode:node_modules/minimist Completed in 350ms
248 timing reifyNode:node_modules/readable-stream Completed in 352ms
249 timing reifyNode:node_modules/tar-fs Completed in 365ms
250 timing reifyNode:node_modules/fs-extra Completed in 368ms
251 timing reifyNode:node_modules/axios Completed in 375ms
252 timing reifyNode:node_modules/nan Completed in 377ms
253 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 422ms
254 timing auditReport:getReport Completed in 424ms
255 silly audit report {}
256 timing auditReport:init Completed in 0ms
257 timing reify:audit Completed in 424ms
258 timing reifyNode:node_modules/ibm_db Completed in 527ms
259 timing reifyNode:node_modules/lodash Completed in 549ms
260 timing reify:unpack Completed in 551ms
261 timing reify:unretire Completed in 0ms
262 timing build:queue Completed in 3ms
263 timing build:link:node_modules/mkdirp Completed in 2ms
264 timing build:link Completed in 2ms
265 info run ibm_db@3.2.1 install node_modules/ibm_db node installer/driverInstall.js
266 info run ibm_db@3.2.1 install { code: 1, signal: null }
267 timing reify:rollback:createSparse Completed in 70ms
268 timing reify:rollback:retireShallow Completed in 0ms
269 timing command:install Completed in 109292ms
270 verbose stack Error: command failed
270 verbose stack     at ChildProcess.<anonymous> (/home/john.doe/.nvm/versions/node/v18.16.0/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:53:27)
270 verbose stack     at ChildProcess.emit (node:events:513:28)
270 verbose stack     at maybeClose (node:internal/child_process:1091:16)
270 verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
271 verbose pkgid ibm_db@3.2.1
272 verbose cwd /home/john.doe/Development/IBM/data-comparator
273 verbose Linux 5.15.90.1-microsoft-standard-WSL2
274 verbose node v18.16.0
275 verbose npm  v9.5.1
276 error code 1
277 error path /home/john.doe/Development/IBM/data-comparator/node_modules/ibm_db
278 error command failed
279 error command sh -c node installer/driverInstall.js
280 error platform = linux, arch = x64, node.js version = v18.16.0
280 error make version =GNU Make 4.3
280 error
280 error ****************************************
280 error You are downloading a package which includes the Node.js module for IBM DB2/Informix.  The module is licensed under the Apache License 2.0. The package also includes IBM ODBC and CLI Driver from IBM, which is automatically downloaded as the node module is installed on your system/device. The license agreement to the IBM ODBC and CLI Driver is available in /home/john.doe/Development/IBM/data-comparator/node_modules/ibm_db/installer/clidriver. Check for additional dependencies, which may come with their own license agreement(s). Your use of the components of the package and dependencies constitutes your acceptance of their respective license agreements. If you do not accept the terms of any license agreement(s), then delete the relevant component(s) from your device.
280 error ****************************************
280 error
280 error Downloading DB2 ODBC CLI Driver from https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz ...
280 error
280 error 
0.03% | 8000 bytes downloaded out of 25304884 bytes.
0.06% | 16000 bytes downloaded out of 25304884 bytes.
0.09% | 24000 bytes downloaded out of 25304884 bytes.
0.13% | 32000 bytes downloaded out of 25304884 bytes.
0.16% | 40000 bytes downloaded out of 25304884 bytes.
0.19% | 48000 bytes downloaded out of 25304884 bytes.
...
92.38% | 23376000 bytes downloaded out of 25304884 bytes.
92.41% | 23384000 bytes downloaded out of 25304884 bytes.
92.44% | 23392000 bytes downloaded out of 25304884 bytes.
92.47% | 23400000 bytes downloaded out of 25304884 bytes.
92.50% | 23408000 bytes downloaded out of 25304884 bytes.
92.54% | 23416000 bytes downloaded out of 25304884 bytes.
92.57% | 23424000 bytes downloaded out of 25304884 bytes.
92.60% | 23432000 bytes downloaded out of 25304884 bytes.
92.63% | 23440000 bytes downloaded out of 25304884 bytes.
92.66% | 23448000 bytes downloaded out of 25304884 bytes.
92.69% | 23456000 bytes downloaded out of 25304884 bytes.
92.73% | 23464000 bytes downloaded out of 25304884 bytes.
92.76% | 23472000 bytes downloaded out of 25304884 bytes.
92.79% | 23480000 bytes downloaded out of 25304884 bytes.
92.82% | 23488000 bytes downloaded out of 25304884 bytes.
100.00% | 25304000 bytes downloaded out of 25304884 bytes.
100.00% | 25304884 bytes downloaded out of 25304884 bytes.
280 error
280 error Downloading and extraction of DB2 ODBC CLI Driver completed successfully.
280 error
280 error make: Entering directory '/home/john.doe/Development/IBM/data-comparator/node_modules/ibm_db/build'
280 error   CXX(target) Release/obj.target/odbc_bindings/src/odbc.o
280 error make: Leaving directory '/home/john.doe/Development/IBM/data-comparator/node_modules/ibm_db/build'
280 error
280 error Error: Command failed: node-gyp configure build  --IS_DOWNLOADED=true --IBM_DB_HOME="$IBM_DB_HOME"
280 error gyp info it worked if it ends with ok
280 error gyp info using node-gyp@9.3.1
280 error gyp info using node@18.16.0 | linux | x64
280 error gyp info find Python using Python version 3.10.6 found at "/usr/bin/python3"
280 error gyp info spawn /usr/bin/python3
280 error gyp info spawn args [
280 error gyp info spawn args   '/home/john.doe/.nvm/versions/node/v18.16.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
280 error gyp info spawn args   'binding.gyp',
280 error gyp info spawn args   '-f',
280 error gyp info spawn args   'make',
280 error gyp info spawn args   '-I',
280 error gyp info spawn args   '/home/john.doe/Development/IBM/data-comparator/node_modules/ibm_db/build/config.gypi',
280 error gyp info spawn args   '-I',
280 error gyp info spawn args   '/home/john.doe/.nvm/versions/node/v18.16.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
280 error gyp info spawn args   '-I',
280 error gyp info spawn args   '/home/john.doe/.cache/node-gyp/18.16.0/include/node/common.gypi',
280 error gyp info spawn args   '-Dlibrary=shared_library',
280 error gyp info spawn args   '-Dvisibility=default',
280 error gyp info spawn args   '-Dnode_root_dir=/home/john.doe/.cache/node-gyp/18.16.0',
280 error gyp info spawn args   '-Dnode_gyp_dir=/home/john.doe/.nvm/versions/node/v18.16.0/lib/node_modules/npm/node_modules/node-gyp',
280 error gyp info spawn args   '-Dnode_lib_file=/home/john.doe/.cache/node-gyp/18.16.0/<(target_arch)/node.lib',
280 error gyp info spawn args   '-Dmodule_root_dir=/home/john.doe/Development/IBM/data-comparator/node_modules/ibm_db',
280 error gyp info spawn args   '-Dnode_engine=v8',
280 error gyp info spawn args   '--depth=.',
280 error gyp info spawn args   '--no-parallel',
280 error gyp info spawn args   '--generator-output',
280 error gyp info spawn args   'build',
280 error gyp info spawn args   '-Goutput_dir=.'
280 error gyp info spawn args ]
280 error gyp info spawn make
280 error gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
280 error make: g++: No such file or directory
280 error make: *** [odbc_bindings.target.mk:120: Release/obj.target/odbc_bindings/src/odbc.o] Error 127
280 error gyp ERR! build error 
280 error gyp ERR! stack Error: `make` failed with exit code: 2
280 error gyp ERR! stack     at ChildProcess.onExit (/home/john.doe/.nvm/versions/node/v18.16.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:203:23)
280 error gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
280 error gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
280 error gyp ERR! System Linux 5.15.90.1-microsoft-standard-WSL2
280 error gyp ERR! command "/home/john.doe/.nvm/versions/node/v18.16.0/bin/node" "/home/john.doe/.nvm/versions/node/v18.16.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build" "--IS_DOWNLOADED=true" "--IBM_DB_HOME=/home/john.doe/Development/IBM/data-comparator/node_modules/ibm_db/installer/clidriver"
280 error gyp ERR! cwd /home/john.doe/Development/IBM/data-comparator/node_modules/ibm_db
280 error gyp ERR! node -v v18.16.0
280 error gyp ERR! node-gyp -v v9.3.1
280 error gyp ERR! not ok 
280 error
280 error     at ChildProcess.exithandler (node:child_process:419:12)
280 error     at ChildProcess.emit (node:events:513:28)
280 error     at maybeClose (node:internal/child_process:1091:16)
280 error     at ChildProcess._handle.onexit (node:internal/child_process:302:5) {
280 error   code: 1,
280 error   killed: false,
280 error   signal: null,
280 error   cmd: 'node-gyp configure build  --IS_DOWNLOADED=true --IBM_DB_HOME="$IBM_DB_HOME"'
280 error }
281 verbose exit 1
282 timing npm Completed in 109326ms
283 verbose unfinished npm timer reify 1690622862021
284 verbose unfinished npm timer reify:build 1690622862789
285 verbose unfinished npm timer build 1690622862789
286 verbose unfinished npm timer build:deps 1690622862789
287 verbose unfinished npm timer build:run:install 1690622862794
288 verbose unfinished npm timer build:run:install:node_modules/ibm_db 1690622862794
289 verbose code 1
290 error A complete log of this run can be found in:
290 error     /home/john.doe/.npm/_logs/2023-07-29T09_27_41_992Z-debug-0.log

**Comment by bimalkjha** [comment]
@fmgyotoku In the shared install log, we can see below error which is the root cause:
```
280 error make: g++: No such file or directory
280 error make: *** [odbc_bindings.target.mk:120: Release/obj.target/odbc_bindings/src/odbc.o] Error 127
280 error gyp ERR! build error
280 error gyp ERR! stack Error: make failed with exit code: 2
```
Please install g++(gcc-c++) on this system and retry installation. Having gcc and g++ in the system is a prerequisite for installation of ibm_db package.
 If still fails, look in the output for root cause. There might be other missing OS packages in this system that you need to install. Thanks.

**Comment by bimalkjha** [comment]
@fmgyotoku Are you able to install g++ on WSL? Please check output of `g++ --version` command. g++ is required by make to compile the native code. Thanks.

**Comment by fmgyotoku** [comment]
Hi @bimalkjha! Thank you so much for your reply. I installed the build-essentials package and it worked fine in my next attempt. Maybe, as a suggestion, this step could be added to any troubleshooting section on the project instructions page.

**Comment by bimalkjha** [comment]
@fmgyotoku Glad to know that your problem is resolved!
We have added below info under prerequesite section in documentation: https://github.com/ibmdb/node-ibm_db#prerequisite
```
Make sure your system has C++ compiler installed that support C++11 standard.

For non-windows platforms: gcc compiler version >= 8.4 is required to install ibm_db. Default compiler on RHEL 6 does not have the required support. Install a newer compiler or upgrade older one.
```
If you feel it should be mentioned about requirement of `build-essentials` on WSL, then we can add that. Thanks.
