### ISSUE TITLE
node-gyp rebuild fails to function on Windows

### ISSUE THREAD

**Issue by IronGremlin** [ibmdb/node-ibm_db#96]
Based on responses to prior issues ([18](https://github.com/ibmdb/node-ibm_db/issues/18) , [64](https://github.com/ibmdb/node-ibm_db/issues/64)), it seems as though the design intent here is that windows users should rely upon the pre-compiled .node file supplied by npm-install.

If that is the case, and it is not within the intended scope of this project to provide support for rebuilding the package on Windows, could we at least get some documentation on what the contents of the $(IBM_HOME_DB)/include and $(IBM_DB_HOME)/lib folders should look like, and where we can find the files that should live there?

**Comment by bimalkjha** [comment]
When you install ibm_db on windows, the IBM_DB_HOME points to ibm_db/installer/clidriver folder and hence clidriver/include and clidriver/lib are the folders of your interest. Thanks.

**Comment by bimalkjha** [comment]
The reason for shipping pre-compiled .node add-on file on windows is the requirement of Visual Studio to build the .node add-on which may not exist on all ntx64. By shipping the pre-compiled add-on, we are removing the dependenc on VS. If you have VS and want to compile yourself, just run below command from ibm_db folder:
set IBM_DB_HOME=.../ibm_db/installer/clidriver
node-gyp rebuild --IBM_DB_HOME=%IBM_DB_HOME%  --IS_DOWNLOADED=false

After executing above commands, the odbc_bindings.node file has dependency on odbc32.dll . You need to remove this dependency. It should link to db2app64.dll.
To get correct .node file, after running node-gyp command, update the build\odbc_bindings.vcxproj file, remove the odbc32.dll from AdditionalDependencies tag from two places, and run below msbuild command:

C:\nodework\master\node-ibm_db>msbuild build/binding.sln /clp:Verbosity=minimal /nologo /p:Configuration=Release;Platform=x64
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
  odbc_bindings.vcxproj -> C:\nodework\master\node-ibm_db\build\Release\\odbc_bindings.node

C:\nodework\master\node-ibm_db>

Delete build\Release folder before running msbuild command.

Thanks.

**Comment by IronGremlin** [comment]
There is no 'include' directory.

Hence, running:

  set IBM_DB_HOME=.../ibm_db/installer/clidriver
    node-gyp rebuild --IBM_DB_HOME=%IBM_DB_HOME%  --IS_DOWNLOADED=false

Throws an error about the missing header files, because they don't exist.

Note this archive, which 'driverInstall.js' downloads:
http://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/ntx64_odbc_cli.zip

There is no include folder in that archive.

**Comment by bimalkjha** [comment]
@IronGremlin You are right. Please get the include folder from linuxx64_odbc_cli.tar.gz after download. Both are same. If future we'll include for windows image too. Thanks.
