### ISSUE TITLE
Error: /node_modules/ibm_db/build/Release/odbc_bindings.node: ELF file's phentsize not the expected size

### ISSUE THREAD

**Issue by kevin-omi** [ibmdb/node-ibm_db#968]
# Please provide below information while opening an issue to understand your problem

- Operating System Name where ibm_db is installed:  Amazon Linux 2
- Target Db2 Server Version or output of `db2level` command from Db2 database system:

### For non-Windows system, output of below commands from terminal:
  uname
  uname -m
  node -v
  npm ls ibm_db
  db2level
  echo $IBM_DB_HOME
  echo $PATH
  echo $LD_LIBRARY_PATH $DYLD_LIBRARY_PATH
  
node v18.18.2
PATH=/var/lang/bin:/usr/local/bin:/usr/bin/:/bin:/opt/bin
LD_LIBRARY_PATH=/var/lang/lib:/lib64:/usr/lib64:/var/runtime:/var/runtime/lib:/var/task:/var/task/lib:/opt/lib
 
- Value of any other ibm_db specific environment variable if in use.

LAMBDA_TASK_ROOT=/var/task
NODE_PATH=/opt/nodejs/node12/node_modules/:/opt/nodejs/node_modules:$LAMBDA_RUNTIME_DIR/node_modules:/var/runtime/node_modules:/mnt/efs/node/node_modules

## Please provide below problem specific info:
=========================================

I'm having an issue loading the ibm_db module in my AWS Lambda function code.  The node_modules is inside the mounted EFS at /mnt/efs/node/node_modules.  The node_modules is built from a CI/CD pipeline (Ubuntu linux) and then uploaded to S3 from within the pipeline, and then copied from S3 to EFS via AWS DataSync.  The Lambda function is deployed via a custom container using the official base image from https://gallery.ecr.aws/lambda/nodejs using node version 18.  I was able to run the application by running the container locally on my computer without any issues.  

Dockerfile:
```
FROM public.ecr.aws/lambda/nodejs:18

ENV NODE_PATH /opt/nodejs/node12/node_modules/:/opt/nodejs/node_modules:$LAMBDA_RUNTIME_DIR/node_modules:/var/runtime/node_modules:/mnt/efs/node/node_modules

RUN yum update -y && yum install make gcc gcc-c++ kernel-devel openssl-devel bzip2-devel python3 -y \
  && yum groupinstall 'Development Tools' -y

COPY index.js package.json ${LAMBDA_TASK_ROOT}

EXPOSE 8080

CMD [ "index.handler" ]

```

I got the following error message when executing the Lambda function:

```
{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "Error: /mnt/efs/node/node_modules/ibm_db/build/Release/odbc_bindings.node: ELF file's phentsize not the expected size",
    "reason": {
        "errorType": "Error",
        "errorMessage": "/mnt/efs/node/node_modules/ibm_db/build/Release/odbc_bindings.node: ELF file's phentsize not the expected size",
        "code": "ERR_DLOPEN_FAILED",
        "stack": [
            "Error: /mnt/efs/node/node_modules/ibm_db/build/Release/odbc_bindings.node: ELF file's phentsize not the expected size",
            "    at Module._extensions..node (node:internal/modules/cjs/loader:1340:18)",
            "    at Module.load (node:internal/modules/cjs/loader:1119:32)",
            "    at Module._load (node:internal/modules/cjs/loader:960:12)",
            "    at Module.require (node:internal/modules/cjs/loader:1143:19)",
            "    at require (node:internal/modules/cjs/helpers:119:18)",
            "    at bindings (/mnt/efs/node/node_modules/bindings/bindings.js:112:48)",
            "    at Object.<anonymous> (/mnt/efs/node/node_modules/ibm_db/lib/odbc.js:57:31)",
            "    at Module._compile (node:internal/modules/cjs/loader:1256:14)",
            "    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)",
            "    at Module.load (node:internal/modules/cjs/loader:1119:32)"
        ]
    },
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: Error: /mnt/efs/node/node_modules/ibm_db/build/Release/odbc_bindings.node: ELF file's phentsize not the expected size",
        "    at process.<anonymous> (file:///var/runtime/index.mjs:1276:17)",
        "    at process.emit (node:events:517:28)",
        "    at emit (node:internal/process/promises:149:20)",
        "    at processPromiseRejections (node:internal/process/promises:283:27)",
        "    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)"
    ]
}
```

**Comment by bimalkjha** [comment]
@kevin-omi I suspect the odbc_bindings.node file is getting corrupted when ibm_db get copied from S3 to EFS via AWS DataSync. Please check the transfer mode. If it is not a binary transfer, the binary files will get corrupted.
You may try to install ibm_db under /tmp folder where lambda function has the write permission. Thanks.

**Comment by bimalkjha** [comment]
@kevin-omi Let us know if you tried file transfer in binary mode and any update about the issue? Thanks.
