### ISSUE TITLE
Providing extended client information

### ISSUE THREAD

**Issue by Elaldradrain** [ibmdb/node-ibm_db#970]
**Is your feature request related to a problem? Please describe.**
I need a way to track workloads for nodejs services. For java service its possible to set client infomation using the following documentation: 
https://www.ibm.com/docs/en/db2-for-zos/12?topic=jies-providing-extended-client-information-data-source-client-info-properties

**Describe the solution you'd like**
I would like a way of setting client information using the ibm_db driver for nodejs.

**Comment by bimalkjha** [comment]
@Elaldradrain The extended client information is saved on Db2 for z/OS in special registers. You can set client information for non-Java clients by setting the value of special registers `CURRENT CLIENT_USERID` and `CURRENT CLIENT_WRKSTNNAME`.
I think this documentation can provide you detailed info about it: https://www.ibm.com/docs/en/db2-for-zos/11?topic=registers-general-rules-special#db2z_rules4specialregisters__chgregvals

For non-Java clients, you can set special registers using two methods: 1) By setting corresponding connection level attribues (SQLSetConnectAttr) and 2) By setting special register values in db2dsdriver.cfg file.

Currently, ibm_db has support for few connection level attributes only, but you can set client info using db2dsdriver.cfg file.
To set CURRENT CLIENT_USERID and CURRENT CLIENT_WRKSTNNAME special register, you need to create a `.../ibm_db/installer/clidriver/cfg/db2dsdriver.cfg` file and specify special register as below:
```
<configuration>
	<databases>
		<database name="sample" host="hotelfvt02.torolab.ibm.com" port="21169">
			<specialregisters>  				
				<parameter name="CURRENT CLINET_USERID" value="B Jha"/>
				<parameter name="CURRENT CLINET_WRKSTNNAME" value="hotelfvt02"/>
			</specialregisters>
	 	</database>
		<database name="sample2" host="hotelfvt02.torolab.ibm.com" port="21169">
		</database>
	</databases>
</configuration>
```
I would also suggest to check "General Rules for Special Registers" here: https://www.ibm.com/docs/en/db2-for-zos/11?topic=registers-general-rules-special
and https://www.ibm.com/docs/en/db2/11.1?topic=applications-application-compatibility-db2-zos too. Thanks.

**Comment by Elaldradrain** [comment]
Thank you very much for this very detailed reply!

I'm still missing one feature which I hope you can clarify for me. I need to change the client user dynamically on runtime, but I can't find any api for it. With dotnet I could do the following
`
Dim sqlconn As D2Connection = new DB2Connection()
sqlconn = new DB2Connection(szconnect_X)
sqlconn.Open()
sqlconn.ClientUser = "foobar"
`

The SQLSetConnectAttr you mentioned doesn't seem to be exposed by the nodejs clidriver wrapper.

**Comment by bimalkjha** [comment]
Added support in latest release. Hence, closing the issue now. Thanks.
