### ISSUE TITLE
insert  data error

### ISSUE THREAD

**Issue by HollyXun** [ibmdb/node-ibm_db#973]
When I want to insert database data, the node program stops running and reports the following information:
FATAL ERROR: v8::HandleScope::CreateHandle() Cannot create a handle without a HandleScope

  1: 00007FF64054436F node::SetCppgcReference+15695
  2: 00007FF6404BC686 EVP_MD_meth_get_input_blocksize+76102
  3: 00007FF6404BE57C node::OnFatalError+252
  4: 00007FF640F2B20B v8::FunctionTemplate::RemovePrototype+331
  5: 00007FF640DC1276 v8::CppHeap::wrapper_descriptor+64918
  6: 00007FF640BE0095 v8::base::Thread::StartSynchronously+1165893
  7: 00007FF640BC388C v8::base::Thread::StartSynchronously+1049148
  8: 00007FF640F3A135 v8::PropertyDescriptor::writable+11765
  9: 00007FF640F3A285 v8::PropertyDescriptor::writable+12101
10: 00007FF640EE0EA7 v8::SharedValueConveyor::SharedValueConveyor+414295
11: 00007FF640EE1A89 v8::SharedValueConveyor::SharedValueConveyor+417337
12: 00007FF640DF60EF v8::StackTrace::GetFrameCount+3055
13: 00007FF640DF6711 v8::StackTrace::GetFrameCount+4625
14: 00007FF640F27FBE v8::Function::NewInstanceWithSideEffectType+734
15: 00007FF640F27980 v8::Function::NewInstance+32
16: 00007FFF2374AD64 node_register_module_v115+21732
17: 00007FFF2374121C
18: 00007FF640EE165E v8::SharedValueConveyor::SharedValueConveyor+416270
19: 00007FF640EE125A v8::SharedValueConveyor::SharedValueConveyor+415242
20: 00007FF640EE151F v8::SharedValueConveyor::SharedValueConveyor+415951
21: 00007FF640EE1390 v8::SharedValueConveyor::SharedValueConveyor+415552
22: 00007FF640FDC74E v8::PropertyDescriptor::writable+676878
23: 00007FF640F4DDF0 v8::PropertyDescriptor::writable+92848
24: 00007FF640F4DDF0 v8::PropertyDescriptor::writable+92848
25: 00007FF640F4DDF0 v8::PropertyDescriptor::writable+92848
26: 00007FF640F4DDF0 v8::PropertyDescriptor::writable+92848
27: 00007FF640F4DDF0 v8::PropertyDescriptor::writable+92848
28: 00000123CE8DC78C

At this time, the Node program stops running and the database is viewed through DataGrip. The data has been successfully inserted.
The amount of data inserted is about 100 items
node version: 20.10.0
ibmdb version: 3.2.3

**Comment by bimalkjha** [comment]
@HollyXun We need detailed log to understand the issue. I would suggest to `cd node_modules\ibm_db` and run `npm install --debug` command. Then run your repro program. It should generate lots of logs on stdout. You can redirect it to a file using `node repro.js > run.txt` command. Share the generated logs here.
It would be really helpful, if you can share some sample test program that can reproduce the issue for us. We would also like to see your application logic if possible. Thanks.

**Comment by bimalkjha** [comment]
Closing due to lack of response. Thanks.
