### ISSUE TITLE
adm-zip can it be moved to dev dependencies

### ISSUE THREAD

**Issue by huineng** [ibmdb/node-ibm_db#978]
Other then being used to do an install (build and install face) It's not really used

Can this be moved to the dev dependencies as such ?

It's not a big deal, it's just being reported as unused by contrast security when we use a ci/cd

thanks

**Comment by bimalkjha** [comment]
@huineng If we move it to dev, it will not get installed during installation of ibm_db and hence, installation of ibm_db will fail. So, let it be a dependency. There should be some way to ignore it by contrast security. Thanks.

**Comment by huineng** [comment]
ok, no problem
