### ISSUE TITLE
Connection not using library list

### ISSUE THREAD

**Issue by drudge** [ibmdb/node-ibm_db#98]
I can not get the connection to honor my library list when connecting to DB2 for i:

```js
'use strict';

const ibmdb = require('ibm_db');

const opts = [
  'DRIVER={DB2}',
  'DATABASE=*LOCAL',
  'PROTOCOL=TCPIP',
  'HOSTNAME=10.x.x.x',
  'PORT=446',
  'UID=IP15NP',
  'PWD=x',
  'NAM=1',
  'DBQ=,*USRLIBL'
];

ibmdb.open(opts.join(';'), (err, conn) => {
  if (err) return console.log(err);

  conn.query('select * from tfts271h fetch first 10000 rows only', (err, data) =>{
    if (err) console.log(err);
    else console.log(data);
    conn.close(() => console.log('done'));
  });
});
```

It always ends with the error:

```
{ [Error: [IBM][CLI Driver][AS] SQL0204N  "IP15NP.TFTS271H" is an undefined name.  SQLSTATE=42704
]
  errors: [],
  error: '[node-odbc] SQL_ERROR',
  message: '[IBM][CLI Driver][AS] SQL0204N  "IP15NP.TFTS271H" is an undefined name.  SQLSTATE=42704\n',
  state: '42S02' }
```

**Comment by bimalkjha** [comment]
@drudge Where is your library list and where connection is not honoured? Please provide details.

From the error, it seems you are able to connect to the server and while executing the select query, server returns SQL204N error. This error tells, you have well connected to the server.
Error tells that there is no table of name TFTS271H under schema( for user) IP15NP on server. I think first you need to create table and then select. Thanks.

**Comment by drudge** [comment]
@bimaljha the library list is defined in my user's profile on the IBM i. You can see that I'm requesting that the connection use my library list by specifying `NAM1;DBQ=,*USRLIBL` in the [connection string](http://www-01.ibm.com/support/knowledgecenter/ssw_ibm_i_71/rzaik/rzaikconnstrkeywordsservprop.htm).

The table does exist, it is simply in a library other than `IP15NP`. The same query runs just fine using JDBC + JT400.jar with `naming=system;libraries=*LIBL`.

**Comment by bimalkjha** [comment]
@drudge Thanks for providing the link for connection string. You are using [IBM i Access ODBC connection string keywords for Server properties](http://www-01.ibm.com/support/knowledgecenter/ssw_ibm_i_71/rzaik/rzaikconnstrkeywordsservprop.htm). DBQ is supported by iAccess ODBC Driver. But, ibm_db uses db2connect driver which does not support DBQ connection string keyword and hence ignored. ibm_db supports only [CLI/ODBC configuration keywords](http://www-01.ibm.com/support/knowledgecenter/#!/SSEPGG_10.5.0/com.ibm.db2.luw.apdv.cli.doc/doc/r0007964.html) as connection string. Thanks.

**Comment by drudge** [comment]
@bimaljha Thanks. I tried to pass `SchemaList=*USRLIBL` in the connection string, but that did not change anything. The same error is returned.

**Comment by bimalkjha** [comment]
`SchemaList=*USRLIBL` affects only following catalog functions not the select statement. See this link: http://www-01.ibm.com/support/knowledgecenter/#!/SSEPGG_10.5.0/com.ibm.db2.luw.apdv.cli.doc/doc/r0008810.html

```
Following catalog functions are affected by the *USRLIBL value for the SchemaList keyword when you are connecting to the DB2 for i server:
SQLTables()
SQLTablePrivileges()
SQLColumns()
SQLColumnPrivileges()
A catalog function call to a DB2 for i server returns a result set that contains database objects with schema that belong to user library list (*USRLIBL) and schema names that are listed in the SchemaList keyword. For example, following SchemaList keyword example returns a result set that contains database objects with schemas associated with the user library list, “schema1” name and “schema2” name:
  [DSNSAMP]
  SCHEMALIST=”*USRLIBL, ‘schema1’, ‘schema2’"
To obtained database objects with combined user library list (*USRLIBL) and schema names that you specified for the SchemaList keyword, the DB2 for i server must meet the following requirements:
You must apply PTF Group SF99601 Version 21 or later on DB2 for i V6R1.
You must apply PTF Group SF99701 Version 11 or later on DB2 for i V7R1.
```

Also use CacheUsrLibL=TRUE in connection string with SchemaList. May be you are missing something more. If the same connection string is working for you using ODBC/CLI driver but not with ibm_db, then we can look. Thanks.

**Comment by drudge** [comment]
@bimaljha Okay, so rather than me guessing which keywords I should be using, let me explain what I am trying to accomplish.  I am simply looking for a way to utilize the library list of the user connecting to the server for schema lookups so that I do not have to fully qualify my tables when querying.

We have operational processes that change a users library list in order to maintain availability during backups, etc. We also use different libraries in our test environment than we do on production, so hard-coding the fully qualified name is not feasible. This was accomplished easily in JDBC through the `naming=system;libraries=*LIBL` keywords. Is there no way to do this using the CLI/ODBC driver?

**Comment by bimalkjha** [comment]
@drudge I think you need to use [CurrentSchema CLI/ODBC configuration keyword](http://www-01.ibm.com/support/knowledgecenter/#!/SSEPGG_10.5.0/com.ibm.db2.luw.apdv.cli.doc/doc/r0008779.html) in connection string. Thanks.

**Comment by tylerjprice** [comment]
I know this issue is closed but there doesn't seem to be a solution to this issue. Can I assume that you can't use a user's library list with ibm_db and db2 connect?

Thanks.

**Comment by bimalkjha** [comment]
@tylerjprice This issue is fixed. You can use user's library list with ibm_db and db2 connect.
For system naming, you can use `ibmdb.open(config, {systemNaming: true}, (err,conn) => {`
For user library, in the database connection string, you just need to add `CurrentSchema=<library_name>;`
Thanks.

**Comment by tylerjprice** [comment]
@bimalkjha Okay, thanks. I was hoping to use the entire library list not just the user's library. That way I wouldn't have to fully qualify the schema. If the table isn't found in the first library it would check the next,  just like it does if you are using DB2 in an rpg application.

**Comment by bimalkjha** [comment]
@tylerjprice In that case you can use the` SchemaList` keyword in connection string as documented here: https://www.ibm.com/support/knowledgecenter/SSEPGG_11.1.0/com.ibm.db2.luw.apdv.cli.doc/doc/r0008810.html
For Db2 for IBM® i servers, if you specify the `*USRLIBL` value, the ibm_db driver searches the current libraries of the server job. The `*USRLIBL` value that is retrieved from the server, on the first catalog function call, is cached by default. The same `*USRLIBL` value is used for all subsequent catalog function calls in the same connection handle. You can change the caching behavior of the user library list by using `CacheUsrLibL` keyword in connection string.
Thanks.
