### ISSUE TITLE
Support of ibm_db with arm64 for MacOS with M1/M2 Chip

### ISSUE THREAD

**Issue by nickhais** [ibmdb/node-ibm_db#997]
Hello!

Do you have any plans to support `arm64` for MacOS with M1 Chip? 
Because installing `ibm_db` with `x64` version of `node.js` is a bit tricky.

Thanks,
Nick.

**Comment by bimalkjha** [comment]
@nickhais Please check this comment: https://github.com/ibmdb/python-ibmdb/issues/739#issuecomment-1086600314
and you can vote for idea https://ibm-data-and-ai.ideas.ibm.com/ideas/DB2CON-I-92
ibm_db can't support unless there is db2 driver from IBM for arm64. I am expecting this support from IBM at start of 2025. Thanks.

**Comment by bimalkjha** [comment]
@nickhais ibm_db@3.3.0 has been released with support for MacOS ARM64 platform. Please try it. Thanks.

**Comment by kirrg001** [comment]
Works for us. Thanks so much!

**Comment by jorgeramirezamora** [comment]
Just tried `3.3.0` and I am still getting:

```
Error: dlopen(/Users/jorgito/Code/my-repo/node_modules/lz4/build/Release/xxhash.node, 0x0001): tried: '/Users/jorgito/Code/my-repo/node_modules/lz4/build/Release/xxhash.node' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/jorgito/Code/my-repo/node_modules/lz4/build/Release/xxhash.node' (no such file), '/Users/jorgito/Code/my-repo/node_modules/lz4/build/Release/xxhash.node' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64'))
```

**Comment by bimalkjha** [comment]
@jorgeramirezamora The error message says that `/Users/jorgito/Code/my-repo/node_modules/lz4/build/Release/xxhash.node` is not an arm64 binary. You need to remove current nodejs and install arm64 version of nodejs, then install ibm_db.
The current error is about `/Users/jorgito/Code/my-repo/node_modules/lz4/build/Release/xxhash.node` which is not part of ibm_db driver. Thanks.

**Comment by jorgeramirezamora** [comment]
Yes @bimalkjha you are right. The error is not about this package, I already removed that dependency (which was an optionalPeerDependency of mine) and now it works! Thanks

**Comment by nickhais** [comment]
Thanks a lot @bimalkjha ! 
Works as expected!
